### ISSUE TITLE
Missing phonetic characters for representing English

### ISSUE THREAD

**Issue by ajgrf** [be5invis/Iosevka#10]
Since the release notes say you wish to represent English phonetic texts, I opened up an English transcription I had and took note of the glyphs that are missing:

* 02A4 ʤ (can be written as d followed by Ʒ, but this ligature is common)
* 02A7 ʧ (same as above)
* 025A ɚ (may want to implement 025D and 02DE too, they are related but less common)

**Comment by be5invis** [comment]
/dezh and /tesh are nonstandard glyphs in IPA. It will be included later.
/er (U+025A) is in the repository now, not released yet. The next release will contain this glyph, after I rebuilt glyphs using spiros.

**Comment by be5invis** [comment]
In version v0.1.5 /d_ezh, /t_esh and /er are included. Close.
