### ISSUE TITLE
Please include : : ligature to ::

### ISSUE THREAD

**Issue by Ziggizag** [be5invis/Iosevka#100]
Hi!

It would be great to make double colons more ligated so it would read :: rather than : : in case of Iosevka font. I mean to make this ligature a little bit narrower (to make these colons a bit closer together).

I mean "Paamayim Nekudotayim" operator in PHP specifically:

https://en.wikipedia.org/wiki/Scope_resolution_operator#PHP

What do you think?

**Comment by be5invis** [comment]
Do you mean... a little kerning?

**Comment by Ziggizag** [comment]
Perhaps - I do not know technically how to achieve this better:

- with kerning adjustment
or
- with special "Paamayim Nekudotayim" ligature

I would only like visually little bit narrower layout between two colons in this particular case.

Rgs!

**Comment by be5invis** [comment]
![image](https://cloud.githubusercontent.com/assets/240091/17067798/02bffb20-5080-11e6-9438-5487d4734a2c.png)
@Ziggizag How about this?

**Comment by Ziggizag** [comment]
I think this is fine !!!

**Comment by Ziggizag** [comment]
By the way - in my humble opinion, your Iosevka is absolutely BEST looking ligature-supporting font on Windows versions of Jet Brain's PhpStorm programming IDE. I tried all ligature-supporting fonts and definitely, Iosevka rulez!

**Comment by Ziggizag** [comment]
Thank you !!!

**Comment by Ziggizag** [comment]
BTW - when compiled TTF files with this fix will be publicly available?

**Comment by be5invis** [comment]
early august

???? iPhone

? 2016?7?23??03:53?Ziggizag <notifications@github.com<mailto:notifications@github.com>> ???


BTW - when compiled TTF files with this fix will be publicly available?

-
