### ISSUE TITLE
No *-top-left-and-bottom-right-serifed for k-like glyphs?

### ISSUE THREAD

**Issue by pv4** [be5invis/Iosevka#1009]
Hello!

`capital-k`, `cyrl-capital-ka` and `cyrl-ka` have no `*-top-left-and-bottom-right-serifed` variants. Is this an intentional decision?

**Comment by be5invis** [comment]
> Is this an intentional decision?
Yes, because I do not see samples of these. If you want them, please file another issue with justification.
Closing as by design.
