### ISSUE TITLE
Variant request: lowercase m with shortened middle leg

### ISSUE THREAD

**Issue by AndydeCleyre** [be5invis/Iosevka#101]
Hello!

I'm loving this font, thank you. I compile with dotted-zero, open-g, and hooky-i.

I find that the lowercase m is very dense next to any and all other characters. I think it would be easier to visually process and be less disruptive of the flow if the middle leg did not extend as low as the left and right legs.

Any chance of adding a variant m with a shortened middle leg?

**Comment by be5invis** [comment]
You mean this?
![image](https://cloud.githubusercontent.com/assets/240091/17345614/692cd86c-5939-11e6-82a9-4e2483977219.png)
The latest `master` supports additional two style selectors: `v-m-longleg` and `v-m-shortleg`, and features `cv25` and `cv26`, to activate short-legged `m`.

**Comment by be5invis** [comment]
Added in 1.9.2

**Comment by AndydeCleyre** [comment]
Hmmm, this doesn't seem to work for me. I built 1.9.2 with

```bash
make STYLE_COMMON='v-zero-dotted v-g-opendoublestorey v-m-shortleg' STYLE_UPRIGHT='v-i-hooky'
```

and the lowercase `m`s still have long middle legs.

![screenshot_20160803_165500](https://cloud.githubusercontent.com/assets/1787385/17381686/20819b54-599b-11e6-974b-105a9de0e1f7.png)

**Comment by be5invis** [comment]
@AndydeCleyre have you tried the latest code i just pushed to `master`?

**Comment by AndydeCleyre** [comment]
No, I tried the `1.9.2` release with md5sum `d9fd36a63120dd874662ddbaff7746bd`, based on the release notes.

I didn't understand before that the feature was present in the release, but without a way to build with it. I see now. I'll wait for the next release. Thanks.

**Comment by be5invis** [comment]
The new two build variant selectors are introduced after r1.9.2 release. The OT features do not depend on them so r1.9.2 release does not use them either.
If you want to build the variant, use `master` instead of `releases`.

**Comment by AndydeCleyre** [comment]
Thanks, I got it now, I'm just waiting because I like to manage this with a version-bound `PKGBUILD`.
