### ISSUE TITLE
Bolder curly W/w, like in Iosevka 2.x

### ISSUE THREAD

**Issue by pv4** [be5invis/Iosevka#1011]
In Iosevka 2.x (curly) W/w had bolder central part and slightly bolder vertical bars (at the top of the glyph). The vertical bar width seemed to be equal to the width of the vertical bars of other glyphs like u/v/x.

In general, W/w looked more "similar" to other glyphs as seen on the image attached.

The issue most visible on bolder weights (the image presents `heavy`) but also notable on `regular` weight.

Could you fix this please?

![image](https://user-images.githubusercontent.com/2502094/118631365-f068c780-b7be-11eb-937b-9cd7c76ab4a7.png)

**Comment by pv4** [comment]
@be5invis The central part is still thinner than in 2.x.

**Comment by be5invis** [comment]
@pv4 Central part needs contrast with the outer part, so it is sort of by design.
