### ISSUE TITLE
'cv37' does not apply to all variants of ⟨l⟩

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#1015]
'cv37' affects ⟨l⟩ and most characters derived from it, but some variants are missed:

* U+0234 LATIN SMALL LETTER L WITH CURL
* U+026B LATIN SMALL LETTER L WITH MIDDLE TILDE
* U+026C LATIN SMALL LETTER L WITH BELT
* U+026D LATIN SMALL LETTER L WITH RETROFLEX HOOK
* U+026E LATIN SMALL LETTER LEZH
* U+02AA LATIN SMALL LETTER LS DIGRAPH
* U+02AB LATIN SMALL LETTER LZ DIGRAPH
* U+1DA9 MODIFIER LETTER SMALL L WITH RETROFLEX HOOK
* U+A78E LATIN SMALL LETTER L WITH RETROFLEX HOOK AND BELT
* U+FB02 LATIN SMALL LIGATURE FL

![ȴɫɬɭɮʪʫᶩꞎﬂ](https://user-images.githubusercontent.com/1124347/118695273-01bfcd00-b7db-11eb-9ad4-9d24879f6dfb.png)

---

* Your font version: 7.0.0-preview.2
* Your font variant: Iosevka Slab Extended
* Your operating system (name and version): macOS 10.14.6
* Your application using Iosevka: hb-view

**Comment by be5invis** [comment]
A lot of variants don't make sense for these letters, especially for `ʪ`, `ʫ`, and `ﬂ`.

**Comment by dscorbett** [comment]
Right. For U+02AA and U+02AB, only the variants that affect the top of the ⟨l⟩ should have an effect, and for U+FB02, only the variants that affect the bottom should have an effect.
