### ISSUE TITLE
Medium font usage in GVim

### ISSUE THREAD

**Issue by mnsr** [be5invis/Iosevka#102]
Hey,

First off, i love this font! I have PragmataPro, but i actually prefer this one in Windows due to it's rendering and the Medium weight option.

I like using the medium weight font, but in GVIM, i'm having an issue loading it by default.

In my .vimrc, i have:

`set gfn=Iosevka_Medium:h11`

For some reason though, it always loads the regular weight. If i manually change it in GVim using the menus, it'll set it to medium. And if i do a `:set gfn`, it'll show the exact text in the above line. I'm not sure if it's something to do with this font, or GVim itself. But i haven't come across anything like this before.
- The version i'm using is 1.9.2.
- I used the ZIP download.
- My Vim is v7.4.1782
- OS: Windows 10 Pro

**Comment by be5invis** [comment]
I tried to use
`set guifont=Iosevka\ Medium:h12`
and it works like this:
![image](https://cloud.githubusercontent.com/assets/240091/17676276/5fadcc20-6360-11e6-8648-a0717445fa5e.png)

**Comment by mnsr** [comment]
I tried this, but it didn't work. Still defaults to the regular weight.

**Comment by be5invis** [comment]
@mnsr I am using the same vim directly downloaded from `vim.org` and setting to Medium works.

**Comment by mnsr** [comment]
It happens in the tuxproject version of vim. 

https://tuxproject.de/projects/vim/x64/

**Comment by be5invis** [comment]
@mnsr 
I’ve downloaded the x64 version from that website and the result is:

![image](https://cloud.githubusercontent.com/assets/240091/17726516/19f6e384-6486-11e6-802c-f22eb0741a5d.png)

the vimrc is
```vim
set encoding=utf-8
set fileencoding=utf-8
set fileencodings=ucs-bom,utf-8,cp936 
set termencoding=cp936
language messages zh_CN.utf-8
sy on

set guifont=Iosevka\ Medium:h12
set guifontwide=Inziu\ Iosevka\ SC:h12
```

It is completely normal.

**Comment by be5invis** [comment]
Closed due to inactivity and lack of information.
