### ISSUE TITLE
Customizable line heights

### ISSUE THREAD

**Issue by jearbear** [be5invis/Iosevka#103]
Hi, I absolutely love this font and it's quickly become my favorite! 

I was wondering if support for customizable line heights is at all planned? By that I mean something akin to what [Input](http://input.fontbureau.com/preview/?size=14&language=python&theme=solarized-dark&family=InputSans&width=300&weight=300&line-height=1.2&a=0&g=0&i=0&l=0&zero=0&asterisk=0&braces=0&preset=default&customize=please) and [Monoid](http://larsenwork.com/monoid/) offer. I'm only really looking for some variants that have more spacing between lines as I find it a bit cramped sometimes and my terminal doesn't support changing it. 

I don't have any experience with this, but I would love to contribute to this if possible. I also recognize that Iosevka already has many different variants and this could increase that significantly so I understand if this isn't desired. Thanks!

**Comment by be5invis** [comment]
Have you checked out the `leading` parameter in `parameters.toml`?

**Comment by be5invis** [comment]
https://github.com/be5invis/Iosevka/blob/master/parameters.toml#L11
The default line height is 1.25em, and you can custom by changing this parameter and build your own variant.

**Comment by jearbear** [comment]
That works perfectly, thanks!

**Comment by NormMonkey** [comment]
Hi, I love the idea of Iosevka, especially being able to customize so much as well as how narrow it is.

I really want to replace my default font DejaVu Sans Mono size 9 with Iosevka but I can't get the line height down to the same as DejaVu.

I'm having a lot of trouble customizing the line height.  I've tried reducing the "leading" parameter as well as the "cap" parameter but I can't seem to find a value for these that doesn't end up cutting off part of the font.  I haven't tried changing "xheight" yet, I'm not sure if it will help.  I tried changing descenderPad to a negative value but again part of the font text is cut off.

I wonder if you could explain what the difference is between these parameters -- the ones that have an effect on line height.  I would really like to understand the difference between "leading", "cap" and "xheight".

Especially, I wonder if you can explain how I can choose the minimum value for these that will shorten the line height without cutting off part of the text.

**Comment by rofrol** [comment]
https://github.com/be5invis/Iosevka/blob/main/params/parameters.toml#L13
