### ISSUE TITLE
Some geometric(?) characters missing

### ISSUE THREAD

**Issue by TJYSunset** [be5invis/Iosevka#104]
* Your font version: 1.9.2
* Your font variant: Inziu Iosevka SC
* Your operating system (name and version): Windows 10 Build 10586
* Your application using Iosevka: Command prompt

I noticed that the following characters are missing while checking out a box-drawing application: 
◣◤◥◢
Maybe some more symbols like these are missing. Please consider adding them.

Thanks.

---
TJYSunset

**Comment by be5invis** [comment]
Moved to #81.
