### ISSUE TITLE
Unable to use with Salamander

### ISSUE THREAD

**Issue by tormento** [be5invis/Iosevka#1041]
I have tried to replace the default font in Salamander internal viewer but it shows me a blank window.

I have tried Iosevka Curly superttf 7.0 preview from 1 to 3. The fonts I normally use in the internal viewer are Cascadia Code (with ligatures) or Fira Code (with ligatures too).

You can find Salamander (I use x64 version) on altap.cz and the internal viewer can be called by F3. From there you can customize font too.

**Comment by be5invis** [comment]
Can you try the TTF version? Some software may dislike TTCs.

**Comment by be5invis** [comment]
(Note: **uninstall existing fonts before installing another edition of the font!**)

**Comment by tormento** [comment]
@be5invis as I wrote, I successfully use Salamander Fira Code which is a variable TTF too.

I uninstalled every preview or stable version before doing the tests.

**Comment by be5invis** [comment]
I mean, using TTF version of Iosevka, instead of TTC.
