### ISSUE TITLE
'cv17' does not fully apply to all variants of ⟨R⟩

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#1049]
Some glyphs derived from U+0052 LATIN CAPITAL LETTER R do not lose their serifs for values of 'cv17' for which they should. Also, U+01A6 doesn’t have variants with open bowls.

* U+01A6 LATIN LETTER YR
* U+042F CYRILLIC CAPITAL LETTER YA
* U+1DE3 COMBINING LATIN SMALL LETTER R ROTUNDA
* U+A75A LATIN CAPITAL LETTER R ROTUNDA
* U+A75B LATIN SMALL LETTER R ROTUNDA

For example, here they are with 'cv17' = 12.
![RƦЯᷣꝚꝛ](https://user-images.githubusercontent.com/1124347/119280164-0e3e8e00-bbfe-11eb-8786-24e468b3ad7a.png)

---

* Your font version: 7.0.0-preview.4
* Your font variant: Iosevka Slab Extended
* Your operating system (name and version): macOS 10.14.6
* Your application using Iosevka: hb-view

**Comment by be5invis** [comment]
fixed in dev

**Comment by dscorbett** [comment]
In the release notes, “rotunda” is misspelled “roundta”.
