### ISSUE TITLE
Line height / Vertical alignment

### ISSUE THREAD

**Issue by firedev** [be5invis/Iosevka#105]
* Your font version: Release
* Your font variant: Any
* Your operating system (name and version): OS X 10.11.6 El Capitan
* Your application using Iosevka: Terminal, iTerm

---

Hi, thanks for free Pragmata, the only thing I wish is x-height is to be a little bit bigger...

Could you please explain line-height/vertical alignment behaviour in terminals? This is the case with other fonts as well but I hope it can be fixed with Iosevka.

Terminal:
![image](https://cloud.githubusercontent.com/assets/115612/18189703/58a6d946-70e7-11e6-80ed-78f93601367f.png)
![image](https://cloud.githubusercontent.com/assets/115612/18189805/29dc400a-70e8-11e6-8a79-030cfda2a078.png)

Iterm:
![image](https://cloud.githubusercontent.com/assets/115612/18189722/774631f8-70e7-11e6-90f5-8eeb99f13672.png)
![image](https://cloud.githubusercontent.com/assets/115612/18189817/3fed0e9c-70e8-11e6-9984-fbaef7cab14b.png)

The letters are always shifted a little bit downwards in regards to the letter space. I tried to correct it by changing line height but it's never vertically aligned perfectly.

It is something that can be fixed?

Thank you.

**Comment by firedev** [comment]
It seems to be ok with bigger font-size, is it a bug in terminal implementation?

![image](https://cloud.githubusercontent.com/assets/115612/18189924/16b04458-70e9-11e6-81c0-a3c318002a1c.png)

**Comment by be5invis** [comment]
Perhaps related to rounding I think.
You can try to enlarge `leading` and `descenderPad` in `parameters.toml` to increase line height.

**Comment by Hyzeta** [comment]
By enlarging descenderPad to 65, the font looks good in iterm, BUT may failed in other cases (Too many spaces at the bottom of the font if enlarge descenderPad. Using the origin font is fine.). I only observe this vertical-align problem in iterm, maybe iterm's font rendering should be blamed, but other fonts do not have this vertical-align problem.

**Comment by Hyzeta** [comment]
First, thanks for the great work. Iosevka is a very amazing font

* Font version: 01-iosevka-2.2.1.zip
* Application: iterm2 Build 3.2.9 on macOS 10.14.5 (18F132)
* Font size: Regular 12

<img width="602" alt="Screen Shot 2019-06-23 at 3 41 41 PM" src="https://user-images.githubusercontent.com/23468295/59973152-c0fab180-95cd-11e9-9bdd-45b4ff83c25a.png">

<img width="602" alt="Screen Shot 2019-06-23 at 3 42 18 PM" src="https://user-images.githubusercontent.com/23468295/59973154-c3f5a200-95cd-11e9-8009-35f21077e0d0.png">

It seems that Iosevka is not aligned to the center when vertical-align, but aligned to the bottom. Of course enlarging descenderPad to 65 will solve this problem for iterm2, but it will add unnecessary bottom padding in other cases, such as sublime text editor.

Is there a general solution for this? Thanks.
