### ISSUE TITLE
Letter Spacing

### ISSUE THREAD

**Issue by firedev** [be5invis/Iosevka#106]
Hi,

Is it possible to have a more narrow and dense version? I am compressing the font a bit via iTerm settings and it would be great if it was possible to build it like this.

![image](https://cloud.githubusercontent.com/assets/115612/18189974/5707c062-70e9-11e6-9bef-483f27bb825e.png)
 
Thanks.

**Comment by be5invis** [comment]
Change the `width` parameter in `parameters.toml`. But Iosevka is narrow enough now: it is narrower than Pragmata Pro, to be honest.

**Comment by firedev** [comment]
Thanks, I haven't tried to build it myself yet, was using ready-made builds. And I was squeezing Pragmata Pro in Terminal as well .
