### ISSUE TITLE
Correct alignment for diacritical marks and tails

### ISSUE THREAD

**Issue by VladWinner** [be5invis/Iosevka#1063]
Affected glyphs:
`U+00CA` | Ê
`U+00CB` | Ë
`U+0114` | Ĕ
`U+0206` | Ȇ
`U+0213` | ȓ
`U+025D` | ɝ
`U+02A8` | ʨ
`U+02A9` | ʩ
`U+0401` | Ё
`U+1E6B` | ṫ
`U+1E97` | ẗ

Demonstration:
![image](https://user-images.githubusercontent.com/13555921/119419652-6b703780-bd03-11eb-8e75-6a08d1d7d574.png)

---

* Your font version: (7.0.0-preview.5)
* Your operating system (name and version): Windows 10

**Comment by be5invis** [comment]
`U+02A8` is considered by design. Drawing a "smooth" is too hard. All those phonetics are built using two parts so a "smooth" transition is not implementable.
