### ISSUE TITLE
'cv25' does not apply to all variants of ⟨Z⟩

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#1064]
'cv25' has no effect on U+2C7F LATIN CAPITAL LETTER Z WITH SWASH TAIL, and some variants of ⟨Z⟩ never get a crossbar.
* U+0179 LATIN CAPITAL LETTER Z WITH ACUTE
* U+017B LATIN CAPITAL LETTER Z WITH DOT ABOVE
* U+017D LATIN CAPITAL LETTER Z WITH CARON
* U+01C4 LATIN CAPITAL LETTER DZ WITH CARON
* U+0224 LATIN CAPITAL LETTER Z WITH HOOK
* U+1E90 LATIN CAPITAL LETTER Z WITH CIRCUMFLEX
* U+1E92 LATIN CAPITAL LETTER Z WITH DOT BELOW
* U+1E94 LATIN CAPITAL LETTER Z WITH LINE BELOW
* U+2C6B LATIN CAPITAL LETTER Z WITH DESCENDER
* U+2C7F LATIN CAPITAL LETTER Z WITH SWASH TAIL

![ZŹŻŽǄȤẐẒẔⱫⱿ](https://user-images.githubusercontent.com/1124347/119425249-0aca0600-bcd5-11eb-881f-535479963de0.png)

---

* Your font version: 7.0.0-preview.5
* Your font variant: Iosevka Slab Extended
* Your operating system (name and version): macOS 10.14.6
* Your application using Iosevka: hb-view

**Comment by NoxUltima** [comment]
The variants of `Z` does not also apply to Zeta too (I wonder if its by design):
![Uploading delta xi.png…]()

**Comment by pv4** [comment]
@dscorbett
Thanks to your bug reports, 7.0 is going to become one of the most well-tested bug-free releases of Iosevka :)

**Comment by dscorbett** [comment]
@NoxUltima, the capital Greek zeta should not get a crossbar because that would look too much like a handwritten capital xi.

**Comment by NoxUltima** [comment]
Oh. Thanks.
