### ISSUE TITLE
Stylistic sets - Further fix

### ISSUE THREAD

**Issue by VladWinner** [be5invis/Iosevka#1065]
Source font — green highlight, Iosevka SS** (current) — orange highlight.

### Andale Mono SS01:
![image](https://user-images.githubusercontent.com/13555921/119532806-e67e3000-bd8d-11eb-8cf9-d61c9d208024.png)
`B` → `prime.capital-b.variants.more-asymmetric-serifless`
`D` → `prime.capital-d.variants.more-rounded-serifless`
`I` → `prime.capital-i.variants.short-serifed`
`J` → `prime.capital-j.variants.serifless`
`f` → `prime.f.variants.flat-hook`
`ſ` → `prime.long-s.variants.flat-hook-tailed`
`ι` → `prime.lower-iota.variants.tailed`
`К` → `prime.cyrl-capital-ka.variants.straight-serifless`
`к` → `prime.cyrl-ka.variants.straight-serifless`

### Anonymous Pro SS02:
![image](https://user-images.githubusercontent.com/13555921/119533062-26451780-bd8e-11eb-95ce-798ab55dabc9.png)
`I` → `prime.capital-i.variants.short-serifed`
`T` → `prime.capital-t.variants.serifed`
`c` → `prime.c.variants.unilateral-serifed`
`w` → `prime.w.variants.straight-flat-top`
`ſ` → `prime.long-s.variants.flat-hook-tailed` + bottom serif
`К` → `prime.cyrl-capital-ka.variants.straight-serifless`
`к` → `prime.cyrl-ka.variants.straight-serifless`

### Consolas SS03:
![image](https://user-images.githubusercontent.com/13555921/119533119-3826ba80-bd8e-11eb-9586-bd99c50817b2.png)
`D` → `prime.capital-d.variants.more-rounded-serifless`
`b` → `prime.b.variants.toothless-corner`
`f` → `prime.f.variants.flat-hook`
`ſ` → `prime.long-s.variants.flat-hook`
`К` → `prime.cyrl-capital-ka.variants.symmetric-touching-serifless`
`к` → `prime.cyrl-ka.variants.symmetric-touching-serifless`
`6` → `prime.six.variants.open-contour` // flat ending tail
`8` → `prime.eight.variants.crossing` // very slight asymmetry in Consolas
`9` → `prime.nine.variants.open-contour` // flat ending tail

### Menlo SS04:
![image](https://user-images.githubusercontent.com/13555921/119533158-3fe65f00-bd8e-11eb-9f3b-25887f853470.png)
`B` → `prime.capital-b.variants.more-asymmetric-serifless`
`D` → `prime.capital-d.variants.more-rounded-serifless`
`j` → `prime.j.variants.flat-hook-serifed`
`ſ` → `prime.long-s.variants.flat-hook-tailed`

### Fira Mono SS05:
![image](https://user-images.githubusercontent.com/13555921/119535151-65746800-bd90-11eb-9798-8348b9037fd3.png)
`D` → `prime.capital-d.variants.more-rounded-serifless`
`0` → `prime.zero.variants.dotted-oval`
`1` → `prime.one.variants.base`
`8` → `prime.eight.variants.crossing-asymmetric`
`9` → `prime.nine.variants.open-contour`

### Liberation Mono SS06:
![image](https://user-images.githubusercontent.com/13555921/119533225-4ffe3e80-bd8e-11eb-94a6-6421e28de553.png)
`D` → `prime.capital-d.variants.more-rounded-serifless`
`f` → `prime.f.variants.flat-hook`
`l` → `prime.l.variants.serifed-flat-tailed`
`ſ` → `prime.long-s.variants.flat-hook`
`5` → `prime.five.variants.oblique-upper-left-bar`

### Monaco SS07:
![image](https://user-images.githubusercontent.com/13555921/119535080-52fa2e80-bd90-11eb-8ae3-c6c797b4afdd.png)
`D` → `prime.capital-d.variants.more-rounded-serifless`
`b` → `prime.b.variants.toothless-corner`
`w` → `prime.w.variants.straight-flat-top`
`0` → `prime.zero.variants.slashed-oval`
`8` → `prime.eight.variants.crossing-asymmetric`
`( )` → `prime.paren.variants.large-contour`

### Source Code Pro SS09:
![image](https://user-images.githubusercontent.com/13555921/119535046-4675d600-bd90-11eb-9c31-88bd764dabe9.png)
`D` → `prime.capital-d.variants.more-rounded-serifless`
`ſ` → `prime.long-s.variants.flat-hook-tailed`
`α` → `prime.lower-alpha.variants.tailed-barred`
`0` → `prime.zero.variants.dotted-oval`
`1` → `prime.one.variants.base-flat-top-serif`
`5` → `prime.five.variants.oblique-upper-left-bar`
`8` → `prime.eight.variants.crossing-asymmetric`

### Envy Code R SS10:
![image](https://user-images.githubusercontent.com/13555921/119533361-6d330d00-bd8e-11eb-91cc-04639c45678d.png)
`A` → `prime.capital-a.variants.curly-serifless` // It's actually more like an arch in Envy Code R
`K` → `prime.capital-k.variants.symmetric-touching-serifless`
`M` → sharp v-part
`W` → `prime.capital-w.variants.straight-vertical-sides` + sharp v-part
`a` → `prime.a.variants.double-storey-toothless-corner`
`g` → `prime.g.variants.single-storey-flat-hook-serifless`
`m` → `prime.m.variants.earless-rounded-double-arch`
`w` → `prime.w.variants.cursive`
`ſ` → `prime.long-s.variants.flat-hook-tailed`
`1` → `prime.one.variants.base-flat-top-serif`

### Ubuntu Mono SS12:
![image](https://user-images.githubusercontent.com/13555921/119534969-2f36e880-bd90-11eb-8df0-e1682691503c.png)
`A` → `prime.capital-a.variants.curly-serifless` // very slight curly
`D` → `prime.capital-d.variants.more-rounded-serifless`
`M` → `prime.capital-m.variants.slanted-sides-hanging` // very slight curly
`R` → `prime.capital-r.variants.curly` // very slight curly
`W` → `prime.capital-w.variants.curly` // slight curly
`Z` → `prime.capital-z.variants.curly-serifless` // very slight curly
`p` → `prime.p.variants.earless-corner`
`w` → `prime.w.variants.curly` // slight curly
`Γ` → `prime.capital-gamma.variants.top-right-serifed` but with bottom serif only
`0` → `prime.zero.variants.dotted-oval`
`5` → `prime.five.variants.oblique-upper-left-bar`
`8` → `prime.eight.variants.crossing-asymmetric`

### Lucida Console SS13:
![image](https://user-images.githubusercontent.com/13555921/119534845-0a427580-bd90-11eb-9f79-e4a91cd8ad4a.png)
`D` → `prime.capital-d.variants.more-rounded-serifless`
`a` → `prime.a.variants.double-storey-tailed`
`g` → `prime.g.variants.single-storey-serifless`
`i` → `prime.i.variants.hooky`
`l` → `prime.l.variants.hooky`
`ſ` → `prime.long-s.variants.flat-hook-tailed`
`ι` → `prime.lower-iota.variants.tailed`
`λ` → `prime.lower-lambda.variants.straight-turn`
`К` → `prime.cyrl-capital-ka.variants.symmetric-connected-serifless`
`к` → `prime.cyrl-ka.variants.symmetric-connected-serifless`
`0` → `prime.zero.variants.unslashed-oval`
`8` → `prime.eight.variants.crossing-asymmetric`
`( )` → `prime.paren.variants.large-contour`

### JetBrains Mono SS14:
![image](https://user-images.githubusercontent.com/13555921/119533449-8471fa80-bd8e-11eb-94ca-0980faa5fc1d.png)
`( )` → `prime.paren.variants.flat-arc`

### IBM Plex Mono SS15:
![image](https://user-images.githubusercontent.com/13555921/119533477-8c319f00-bd8e-11eb-91f4-6c03c45f09ec.png)
`M` → sharp v-part
`w` → `prime.w.variants.straight-flat-top`
`5` → `prime.five.variants.oblique-upper-left-bar`

### PT Mono SS16:
![image](https://user-images.githubusercontent.com/13555921/119533517-95227080-bd8e-11eb-938b-935aeb530f57.png)
`ſ` → `prime.long-s.variants.flat-hook-tailed`
`≤ ≥` → `prime.lig-ltgteq.variants.slanted`

### Recursive Mono SS17:
![image](https://user-images.githubusercontent.com/13555921/119538128-75417b80-bd93-11eb-91e5-d8a7e9d0bf60.png)
`K` → `prime.capital-k.variants.symmetric-touching-serifless`
`0` → `prime.zero.variants.slashed-oval` // narrower than O
`8` → `prime.eight.variants.crossing-asymmetric`

### Input Mono SS18:
![image](https://user-images.githubusercontent.com/13555921/119533572-a5d2e680-bd8e-11eb-8ff8-cedb45160d12.png)
`ſ` → `prime.long-s.variants.flat-hook-tailed`
`λ` → `prime.lower-lambda.variants.straight-turn`
`1` → `prime.one.variants.base`
`#` → `prime.number-sign.variants.slanted` // slight slanted
`%` → `prime.percent.variants.rings-continuous-slash`

Also I noticed incorrect description in variants.toml for `prime.j.variants.flat-hook-serifless` and `prime.j.variants.flat-hook-serifed` (vice versa)

Your font version: (7.0.0-preview.5)
Your operating system (name and version): Windows 10

**Comment by be5invis** [comment]
I am sorry but performing an exact match of Iosevka's stylistic sets is not in scope.
Some shapes, like the "very slightly curly" letters in Ubuntu Mono or the unique shape from Envy Code R is just too hard to implement.
Sorry. Sorry. Sorry. Sorry. Sorry. Sorry. Sorry. Sorry. Sorry. Sorry.

**Comment by be5invis** [comment]
Some changes not added:
 * `B`: Iosevka's asymmetric `B` is **highly asymmetric**, so it is not applied.
 * Oval `0`: Only applies to the stylistic sets that their source font's `0` is significantly narrower than `O`.
 * For SS10: I think toothed `a` and `g` matches better for it overall look. Still, this source font is too unique, and **I may delete SS10 in a later release**.
 * For SS12: Ubuntu Mono has a lot of handwriting features. Iosevka cannot mimick that. Sorry.

**Comment by VladWinner** [comment]
@be5invis And again, thank you for your prompt response and detailed answer! I am sure that the new added commits will appeal to those who are used this fonts. It's amazing how rapidly Iosevka font is developing and improving, while remaining unique and crisp.
