### ISSUE TITLE
'cv29' does not apply to all variants of ⟨d⟩

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#1067]
U+0256 LATIN SMALL LETTER D WITH TAIL and U+1D91 LATIN SMALL LETTER D WITH HOOK AND TAIL are not affected by 'cv29'. For example, here is 'cv29' = 2.
![dɖᶑ](https://user-images.githubusercontent.com/1124347/119585178-2a763280-bd98-11eb-91c4-89bb380e758d.png)

---

* Your font version: 7.0.0-preview.5
* Your font variant: Iosevka Slab Extended
* Your operating system (name and version): macOS 10.14.6
* Your application using Iosevka: hb-view

**Comment by be5invis** [comment]
Variants for `U+1D91` don't make sense, since all modifiable parts (top serif, bottom-right-corner) are occupied by hooks or tails.

**Comment by dscorbett** [comment]
There is also the transition (corner or rounded) between the bottom of the bowl and the vertical stroke: that still makes sense despite hooks and tails.
