### ISSUE TITLE
Crossbar of U+2C7F breaks apart

### ISSUE THREAD

**Issue by NoxUltima** [be5invis/Iosevka#1069]
Describe your problem here. Provide pictures and files if necessary.

![Screenshot_20210526-125822_Drive.jpg](https://user-images.githubusercontent.com/16898444/119604721-242c9880-be22-11eb-8091-c10e56b2d952.jpg)

---

* Your font version: (Release or git, version)
* Your font variant:
* Your operating system (name and version):
* Your application using Iosevka:

**Comment by be5invis** [comment]
Already fixed in `dev`. Closing.
![image](https://user-images.githubusercontent.com/240091/119605203-361c2600-bda5-11eb-80bc-986f6596f7b2.png)

**Comment by NoxUltima** [comment]
Thanks!
