### ISSUE TITLE
对于整体风格的建议

### ISSUE THREAD

**Issue by farteryhr** [be5invis/Iosevka#107]
群众纷纷吐槽太瘦。觉得还是可以考虑改改吧？
我觉得（结合起中文部分）可以保持英文行距，变矮英文，整体行高减小，但是汉字高度不变，减小汉字行距。

也不知道可以代表多少人。【虽然我是风格全反的 lucida console 用户。但是实在是看到v2ex用户普遍都觉得长了。代码里也不会出现成片中文，就算出现了，行距减小一些也还是够的。

另，跟 lucida console 一起用的时候那被压扁的宋体……想想如果用配上扁雅黑还很有趣呢【

**Comment by be5invis** [comment]
要改宽度去改 parameters.toml
