### ISSUE TITLE
Add `descending-non-tailed` variant for `long-s` and `eszet`

### ISSUE THREAD

**Issue by NoxUltima** [be5invis/Iosevka#1070]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [ ] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

![delta xi](https://user-images.githubusercontent.com/16898444/119619177-4af4ca00-be36-11eb-9fdd-f53e0df2cfe9.png)

**Comment by be5invis** [comment]
I am sorry but performing an exact match of Iosevka's stylistic sets is not in scope.
Sorry. Sorry. Sorry. Sorry. Sorry. Sorry. Sorry. Sorry. Sorry. Sorry.

**Comment by NoxUltima** [comment]
Its okay.

**Comment by be5invis** [comment]
No that little leftward swash though -- I do not mimic handwriting features.
