### ISSUE TITLE
Rendering of the triple-equal ligature

### ISSUE THREAD

**Issue by msgx** [be5invis/Iosevka#1073]
The **triple-equal** ligature looks a bit untidy (at least in my instances of VSCode). The same for the **double-equal** one.

![triple-equal-ligature](https://user-images.githubusercontent.com/7853057/119651541-cc942a00-be2d-11eb-9187-e10f4fa5bc1d.png)

---

* font version: 6.1.3
* font variant: Iosevka (Monospace, Default)
* operating system: Windows 10 version 1909 (build 18363.1556)
* application using Iosevka: Visual Studio Code 1.56.2

**Comment by msgx** [comment]
Ah, I see. Thank you for the clear explanation. I will try to deal with it somehow...

**Comment by be5invis** [comment]
Dupe #594. Chromium should fix its AA implementation.
