### ISSUE TITLE
Wrong glyphs for letter tone five

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#1074]
The images in [L2/19-201](https://www.unicode.org/L2/L2019/19201-correct-tone-six.pdf) show that U+01BC LATIN CAPITAL LETTER TONE FIVE has a noticeably different glyph from U+0035 DIGIT FIVE. The lowercase form should match the uppercase form. Here is <U+0035, U+01BC, U+01BD>.
![5Ƽƽ](https://user-images.githubusercontent.com/1124347/119726394-10dbf600-be3f-11eb-8022-a0b9e32237e3.png)

---

* Your font version: 7.0.0-preview.5
* Your font variant: Iosevka Extended
* Your operating system (name and version): macOS 10.14.6
* Your application using Iosevka: hb-view

**Comment by dscorbett** [comment]
This was fixed in version 7.0.0 but regressed in version 7.3.0.

**Comment by be5invis** [comment]
Fixed.
