### ISSUE TITLE
Mathematical glyph parts should not be italicized

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#1076]
Mathematical glyph parts should not be italicized in the italic fonts because, if they are, the parts no longer align. This is similar to box drawing glyphs, which are not italicized. For example, here is <U+2502, U+239B, U+000A, U+2502, U+239D>.
![│⎛␤│⎝](https://user-images.githubusercontent.com/1124347/119835525-e76aab00-bece-11eb-80ce-8095c8e091e5.png)

---

* Your font version: 7.0.0-preview.5
* Your font variant: Iosevka Extended Italic
* Your operating system (name and version): macOS 10.14.6
* Your application using Iosevka: hb-view

**Comment by stone-zeng** [comment]
I guess these extensible parts are not designed to be combined, as their precious behavior requires the MATH table which is not possible or very difficult for a monospaced font.

**Comment by dscorbett** [comment]
These characters _are_ meant to be combined and do not require the MATH table. They were first designed for a simpler, glyph-based math layout model predating the MATH table. See [section 2.13 of UTR #25](https://www.unicode.org/reports/tr25/#page=22).
