### ISSUE TITLE
Request for new variant & build selector: v-l-hookybottom

### ISSUE THREAD

**Issue by AndydeCleyre** [be5invis/Iosevka#108]
I think Iosevka would benefit from a new variant for `l`, equivalent to `cv09` rotated 180 degrees. This would do a good job of matching the hooky `i` variant `cv05` while being visually unambiguous, and it wouldn't require designing any new shapes. `cv07` and `cv09` both resemble numbers, and `cv10` resembles a `Z`. `cv08` is the most distinctly `l`-shaped `l` variant available, and it's good, but it would be nice to match a non-curvy `l` to the non-curvy `i` variants.

**Comment by be5invis** [comment]
You mean, `cv08` minus the top serif?

**Comment by AndydeCleyre** [comment]
No, but I guess I do mean cv10 minus the top serif.

**Comment by be5invis** [comment]
![image](https://cloud.githubusercontent.com/assets/240091/18617309/373d08b4-7dff-11e6-8dde-1f43477b3376.png)
Like, well, this?

**Comment by AndydeCleyre** [comment]
Nope. That looks alright, but what I'm describing has no curves.

**Comment by be5invis** [comment]
OK, it is two styles now

cv27:
![image](https://cloud.githubusercontent.com/assets/240091/18617437/9c8d1fea-7e01-11e6-8c18-143078822d06.png)
cv28:
![image](https://cloud.githubusercontent.com/assets/240091/18617426/922d62ee-7e01-11e6-8fae-8a3bbdb1dc8d.png)

**Comment by be5invis** [comment]
Added in the latest commit.

**Comment by AndydeCleyre** [comment]
Thanks! Do these have corresponding build selectors?
