### ISSUE TITLE
Feature Request: add glyphs required for exa --icons

### ISSUE THREAD

**Issue by juarezr** [be5invis/Iosevka#1080]
### Request

Want to request for adding symbols to make [exa](https://the.exa.website/features/icons) display the correct glyphs when using the option `--icons` with the `Iosevka` fonts.

### Example

When using plain Iosevka font in the terminal:

<img width="834" alt="exa--icons-font-iosevka" src="https://user-images.githubusercontent.com/576780/120050993-40346380-bff5-11eb-8e1f-3f191c709e16.png">

When using plain [Iosevka Nerd Font](https://www.nerdfonts.com/) font in the terminal: 

<img width="839" alt="exa--icons-font-iosevka-nerd-font" src="https://user-images.githubusercontent.com/576780/120051006-4f1b1600-bff5-11eb-8897-7eef1c215b72.png">

### How it Works

- The FAQ [points](https://the.exa.website/features/icons) to a subset of symbols in the codepoint range U+E000 to U+F8FF.
- The codepoint numbers for the file types and logos used by exa are standardized by convention among terminal application developers. 😟 
- The codepoints used can be found in this [file](https://github.com/ogham/exa/blob/master/src/output/icons.rs#L93).

**Comment by be5invis** [comment]
I think [NERD fonts](https://www.nerdfonts.com/) already did it?
Closing as external.
