### ISSUE TITLE
U+23B0 and U+23B1 are not tall enough

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#1089]
U+23B0 UPPER LEFT OR LOWER RIGHT CURLY BRACKET SECTION and U+23B1 UPPER RIGHT OR LOWER LEFT CURLY BRACKET SECTION should connect to each other above and below. The following is <U+23B0, U+23B1, U+000A, U+23B1, U+23B0>. It should look like an open brace and a close brace, with no gap in the middle.
![⎰⎱␤⎱⎰](https://user-images.githubusercontent.com/1124347/120083807-5136b080-c099-11eb-9baf-c1452347477b.png)

---

* Your font version: 7.0.0
* Your font variant: Iosevka Slab Extended
* Your operating system (name and version): macOS 10.14.6
* Your application using Iosevka: hb-view

**Comment by dscorbett** [comment]
This is not a bug after all.

**Comment by be5invis** [comment]
@dscorbett ?

**Comment by dscorbett** [comment]
These code points seem to be unifications of multiline braces and of single-line moustache delimiters. A font may or may not make them connect between lines. So this could be a valid change request but it is not a valid bug report.

According to [UTR #25 table 2.6](https://www.unicode.org/reports/tr25/tr25-15.pdf#page=23), the purpose of these characters is to make multiline braces as I described, so it would not be wrong to make them taller. However, according to the names list, they are “left moustache” and “right moustache”, i.e. TeX’s `\lmoustache` and `\rmoustache`, which are normal delimiter characters. According to [UTR #25’s data file](https://www.unicode.org/Public/math/revision-15/MathClass-15.txt), U+23B0 and U+23B1 are relations, not glyph parts. I infer it would not be wrong to keep the glyphs as they are.
