### ISSUE TITLE
请问带-CL的是什么意思？这套字体包含CJK还是只有CJ？

### ISSUE THREAD

**Issue by peakvision** [be5invis/Iosevka#109]
另外要修改cmd.exe字体，是不是要在[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Console\TrueTypeFont]为每个代码页增加一条0开头的值？我之前增加过一些字体，后来连字体文件和注册表这个值一起删了，但cmd属性的选字窗口依然有这些不存在字体。

**Comment by be5invis** [comment]
CL means Classical.
