### ISSUE TITLE
Please add character variants of U+2306 PERSPECTIVE ⌆

### ISSUE THREAD

**Issue by rekollekt** [be5invis/Iosevka#1097]
![gh](https://user-images.githubusercontent.com/15945329/120098895-c2797080-c138-11eb-9c0f-843ecc2fc31b.png)
(Please same add to U+2305 PROJECTIVE ⌅.)

_Originally posted by @rekollekt in https://github.com/be5invis/Iosevka/issues/780#issuecomment-850968465_

**Comment by be5invis** [comment]
I do not understand this. Is it a _variant request_ or _shape correction request_?
I do not see any existing fonts that have `⌆` aligned to digit metrics.
Please provide justifiaction.

**Comment by rekollekt** [comment]
It is a variant request:
![as](https://user-images.githubusercontent.com/15945329/120099821-ed19f800-c13d-11eb-92fb-c67b796c7e21.png)

**Comment by be5invis** [comment]
I do not think low-frequency symbols (`⌆` and `⌅`) need separate `cv` tags and variants. We could simply correct its "default" shape. However, I do not find any evidence showing PERSPECTIVE and PROJECTIVE need to **exactly match** the metrics of numbers / lower-case letters. Please note that the practice of other fonts is not evidence.

If you find evidence, please file a separate issue requesting a shape correction.
