### ISSUE TITLE
显示字体无效

### ISSUE THREAD

**Issue by supyoung** [be5invis/Iosevka#110]
* Your font version: (Release or git, version)1.9.4
* Your font variant:SC bold
* Your operating system (name and version):win7
* Your application using Iosevka: (some Java applications may have problem in showing Iosevka properly. It is a bug in Java's GUI components.) 安装不了粗体!!!
在chrome上修改了字体 然后粗体部分会糊在一起 我猜是因为没有安装对应的粗体 所以chrome自动渲染加粗导致的 然后就去安装 但是显示“无法安装，显示字体无效”
之后我查到知乎上有人问这个问题 但没有邀请你回答 其中一个回答说可能是字体封装太多了，win 10 以下不支持（PS：已经邀请你回答那个问题了）
那么如果是这样的话，请问支持win7安装的最新版本是？（PS：我电脑上另一个1.060是可以装粗体的）
还有具体要怎么操作才能让chrome完全支持这个字体（包含日，繁）？
chrome的设置里只能设置一种字体，难道是要用stylish，font-family里把J，TC，SC全都放进去吗？
还是说只放一个，就自动全部支持了，或者用font-link把J,TC链到SC上去？搞不明白，还望赐教，谢谢 
If you have problem when building Iosevka, please provide these informations:

* Your Node.js version:
* Your results of `npm list`
* Your _otfcc_ version：
* Your FontForge version:
* Your `parameters.toml`:

---

Describe your problem here. Provide pictures and files if necessary.

**Comment by be5invis** [comment]
Have you tried this?
![image](https://cloud.githubusercontent.com/assets/240091/19094662/ccec5f60-8ac3-11e6-8042-f42321930624.png)

**Comment by supyoung** [comment]
完美解决问题，原来是ttf和ttc的差别，还真是没注意到。
chrome设置里修改字体并不好使，把simplified Han，Han，Japanese都设置了，好像除了wikipedia都没有效果，但是用stylish就完美解决了。
有个很明显的问题就是日文字假名尤其是弧段的部分会糊，和汉字的锐利一对比就更难忍了，本来想传图的，但是不知道为什么截的图连汉字部分都是模糊的……
还有个想问的问题就是slab roboto是什么意思 这三者之间有什么区别 还有名字有什么来头吗

**Comment by be5invis** [comment]
假名不是 ideohint 做的反正浏览器里面都差不多
roboto 西文比例
slab 是有衬线。
以上。

**Comment by supyoung** [comment]
回的好快……刚发现了cc的副作用 居然会出现乱码（在windows系统里）但是网站还没发现会乱码 复制粘贴出来之后居然又是一样的 只看到说cc是也可用于控制台 还以为是兼容模式的 那cc系列具体是用来干嘛的
我想问的是Inziu Iosevka名字的由来 总不能是拍脑袋想出来的吧

**Comment by be5invis** [comment]
cc 一些标点是全角
8.1 以下的 OS 是不会作为兼容目标的
名字就是随便想的

**Comment by supyoung** [comment]
哈哈 好的 谢谢 那我关掉了
