### ISSUE TITLE
Stylistic sets – small edits

### ISSUE THREAD

**Issue by VladWinner** [be5invis/Iosevka#1104]
This is addition to #1065.

### New edits code (difference) for variants.toml:

```
[composite.ss02.design]
cyrl-capital-ze = "unilateralSerifed"

[composite.ss03.design]
~~question = "corner"~~ // delete from current 'dev'
question = "corner-flat-hooked"
cyrl-capital-ya = "curly"
cyrl-ya = "curly"

[composite.ss05.design]
~~lig-ltgteq = "slanted"~~ // delete from current 'dev', looks like moved accidentally instead of ss16

[composite.ss06.design]
~~cent = "open"~~ // delete from current 'dev'

[composite.ss08.design]
capital-d = "more-rounded-serifless"
capital-g = "toothless-rounded-serifless-hooked"
capital-i = "short-serifed"
capital-j = "serifless"
capital-n = "asymmetric"
capital-q = "straight"
eszet = "longs-s-lig"
lower-iota = "tailed-serifed"
~~asterisk = "penta-low"~~ // delete from current 'dev'
asterisk = "hex-low"
~~zero = "dotted"~~ // delete from current 'dev'
zero = "dotted-oval"
~~ampersand = "upper-open"~~ // delete from current 'dev'
ampersand = "lower-open"
cent = "open"
four = "closed"
seven = "curly-serifless"
cyrl-capital-ka = "curly-serifless"
cyrl-ka = "curly-serifless"
cyrl-capital-ya = "curly"
cyrl-ya = "curly"

[composite.ss16.design]
lig-ltgteq = "slanted"
```

Iosevka SS** (current) — orange highlight, Source font — green highlight
![image](https://user-images.githubusercontent.com/13555921/120261459-9ed13a00-c2a0-11eb-974b-2251961f2243.png)

---

Your font version: dev-5ef460d
Your operating system (name and version): Windows 10

**Comment by be5invis** [comment]
I will consider edits for `ss16` invalid. `lig-ltgteq` is for the `<=` and `>=` **ligation**, not Unicode characters. Unicode already has`≤` `≥` vs `⩽` `⩾`, so PT Mono's source font is considered wrong.

**Comment by be5invis** [comment]
`ss03`'s source `Я` and `я`, have slope at the terminal of the left leg, so marking it curly is invalid. The curly `R` / `Я`'s "leg" must end at baseline vertically.

**Comment by be5invis** [comment]
Where does your assignment for Pragmata Pro come from? Its official character set shows `*` and `&` differently: https://fsd.it/pragmatapro/All_chars.png

**Comment by VladWinner** [comment]
> Where does your assignment for Pragmata Pro come from? Its official character set shows `*` and `&` differently: https://fsd.it/pragmatapro/All_chars.png

Yes, now I noticed that these characters look different in latest version. Sorry!
![image](https://user-images.githubusercontent.com/13555921/120265023-c4157680-c2a7-11eb-8a35-c88f0a77c2f5.png)
