### ISSUE TITLE
a some info about the inner working of this font

### ISSUE THREAD

**Issue by pvinis** [be5invis/Iosevka#111]
Hello.
I have been using Iosevka for a couple of years now, and its awesome! Great work @be5invis.
I was wondering if I could get some more info about how you design a letter, how you code it, and how it's produced from code to actual font.
It would be awesome to learn a bit more about the whole process, and also maybe some more people could help you?
Thank you.

**Comment by KamranMackey** [comment]
Iosevka has only been around a little over a year (July, 2015 was technically the first release), so there's no way you've been using it for a couple years. Don't lie to us! 😛

**Comment by pvinis** [comment]
really? wow. it definitely feels like more. i remember looking for fonts to replace my old one and I found iosevka and was and still am super happy using it. 😀

**Comment by be5invis** [comment]
You can try to read the code in `.ptl` suffixes, or the compiled version in JS.
Since there are many tricky implementations in Iosevka, it is not recommended though.
