### ISSUE TITLE
Broken connecting underscore ligatures

### ISSUE THREAD

**Issue by NoxUltima** [be5invis/Iosevka#1110]
Describe your problem here. Provide pictures and files if necessary.

The below text is 7 underscores connected. It appears the medial and final forms are empty:
![broken underscores](https://user-images.githubusercontent.com/16898444/120944489-5a91de00-c767-11eb-8349-3bda893be2a2.png)

---

* Your font version: (Release or git, version):  7.0.3
* Your font variant: Iosevka with `dlig`
* Your operating system (name and version):
* Your application using Iosevka:

**Comment by be5invis** [comment]
Already fixed in `dev`. Closing.

**Comment by NoxUltima** [comment]
Thanks for informing ;)
