### ISSUE TITLE
Stylistic set to represent Aperçu Mono?

### ISSUE THREAD

**Issue by cssobral2013** [be5invis/Iosevka#1113]
This is desired because Aperçu Mono is a paid font, so it would be a good idea to have an opensource alternative.

**Comment by be5invis** [comment]
Do you have links to that font? Note that I am running out of tags. Currently only `ss19` is unused -- but I'd like to reserve it for some purposes.

**Comment by cssobral2013** [comment]
https://www.colophon-foundry.org/typefaces/apercu/

Em qua, 9 de jun de 2021 8:26 PM, Belleve ***@***.***>
escreveu:

**Comment by VladWinner** [comment]
@cssobral2013 You can try to [build it yourself](https://github.com/be5invis/Iosevka#customized-build).

### private-build-plans.toml
```
[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
no-cv-ss = true

[buildPlans.iosevka-custom.variants.design]
capital-j = "serifless"
capital-k = "symmetric-touching-serifless"
capital-q = "crossing"
a = "double-storey-serifless"
g = "double-storey"
k = "symmetric-touching-serifless"
l = "tailed-serifed"
eszet = "sulzbacher-descending"
lower-alpha = "tailed-barred"
cyrl-capital-ka = "symmetric-touching-serifless"
cyrl-ka = "symmetric-touching-serifless"
one = "base"
two = "straight-neck"
three = "flattop"
four = "closed"
five = "oblique-upper-left-bar"
eight = "two-circles"
brace = "straight"
number-sign = "slanted"
dollar = "open"
cent = "open"
percent = "rings-continuous-slash"
```

**Comment by ChiefMikeK** [comment]
Be aware that incorporating commercial/trademarked/proprietary fonts can lead to legal issues
---
please use & support ___open source___

**Comment by cssobral2013** [comment]
@ChiefMikeK - This ISN'T intended to incorporate paid fonts in this project; this CAN ONLY replicate a paid font into an open-source one. This is different.

**Comment by cssobral2013** [comment]
It looks like the solution from @VladWinner  solves this issue, then.
