### ISSUE TITLE
Stylistic set to represent RedHat Mono?

### ISSUE THREAD

**Issue by cssobral2013** [be5invis/Iosevka#1114]
This is desired because RedHat Mono has no italics, so it would be great.

**Comment by be5invis** [comment]
Do you have links to that font? Note that I am running out of tags. Currently only `ss19` is unused -- but I'd like to reserve it for some purposes.

**Comment by cssobral2013** [comment]
https://www.redhat.com/en/about/brand/standards/typography, section 'RedHat
Mono'

Em qua, 9 de jun de 2021 8:26 PM, Belleve ***@***.***>
escreveu:

**Comment by VladWinner** [comment]
> https://www.redhat.com/en/about/brand/standards/typography

![image](https://user-images.githubusercontent.com/13555921/121449799-2efb3780-c9a3-11eb-9abc-08a0cf52496c.png)

**Comment by cssobral2013** [comment]
The same, but just above RedHat Mono.

Em qua, 9 de jun de 2021 10:21 PM, Vlad ***@***.***> escreveu:

**Comment by cssobral2013** [comment]
@be5invis - Specimen for Latin below.
![20210609_222559](https://user-images.githubusercontent.com/19995437/121450364-fb53e980-c971-11eb-8729-5440b88cc12d.jpg)

**Comment by VladWinner** [comment]
@cssobral2013 You can try to [build it yourself](https://github.com/be5invis/Iosevka#customized-build).

### private-build-plans.toml
```
[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
no-cv-ss = true

[buildPlans.iosevka-custom.variants.design]
capital-d = "more-rounded-serifless"
capital-g = "toothless-rounded-serifless-hooked"
capital-j = "serifless"
capital-k = "symmetric-touching-serifless"
capital-q = "crossing"
capital-w = "straight-flat-top"
f = "flat-hook"
i = "tailed-serifed"
k = "symmetric-touching-serifless"
l = "tailed-serifed"
r = "compact-serifed"
t = "standard-short-neck"
w = "straight-flat-top"
y = "straight-turn"
eszet = "longs-s-lig"
cyrl-capital-ka = "symmetric-touching-serifless"
cyrl-ka = "symmetric-touching-serifless"
cyrl-capital-u = "straight-turn"
one = "base"
two = "straight-neck"
four = "closed"
five = "oblique-upper-left-bar"
six = "open-contour"
eight = "two-circles"
nine = "open-contour"
tilde = "low"
asterisk = "hex-high"
paren = "large-contour"
number-sign = "slanted"
percent = "rings-continuous-slash"
```

**Comment by cssobral2013** [comment]
@be5invis - Any plans on this?

**Comment by VladWinner** [comment]
@cssobral2013 The author has already answered above that he does not intend to use the last remaining slot for RedHat Mono style. And as I wrote above, you can relatively simply compile it yourself with the desired set of glyphs.
