### ISSUE TITLE
R+L+U+D arrow character support

### ISSUE THREAD

**Issue by hl2guide** [be5invis/Iosevka#1116]
- The requested character is...
  - [ ] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [x] Symbol
- [x] Some other monospace/programming fonts supported this character. Provide images below.

------

Please add the basic left, right, up and down arrow. mainly used for file explorers and "move" actions on sites.

example:
![issue](https://user-images.githubusercontent.com/17044982/121501495-a3c18680-ca22-11eb-974b-cbc1d09c261a.png)

**Comment by PyGamer0** [comment]
Arent they already there?
![image](https://user-images.githubusercontent.com/64531844/121630504-e9219a80-ca9a-11eb-9f2d-94d4fa5d83e0.png)

**Comment by be5invis** [comment]
I think these chars are PUA, outside standard Unicode.

**Comment by hl2guide** [comment]
ok
