### ISSUE TITLE
Ensure colon compatibility with Android and Windows apps

### ISSUE THREAD

**Issue by VladWinner** [be5invis/Iosevka#1118]
- The requested character is...
  - [ ] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [x] Punctuation
  - [x] Symbol
- [x] Some other monospace/programming fonts supported this character. Provide images below.

------

1) Already existing 'Ratio symbol' `∶` (U+2236) should be centered in height to look correct in cases where it is used (mostly, in formulas)
2) Add 'Modifier Letter Colon' `꞉` (U+A789) which also _preferably_ to be height-centered for use with numbers (this behavior is seen on Android)

These two characters are used in certain technical apps and system dialog windows (Android and Windows OS) instead of usual `:` (U+003A) colon.

![image](https://user-images.githubusercontent.com/13555921/121777037-bc53ad00-cb98-11eb-92d4-b3123d6efcc0.png)

**Comment by dscorbett** [comment]
U+A789 MODIFIER LETTER COLON is not for use with numbers. It’s a tone letter used for some languages of Africa and Papua New Guinea. Its glyph is not necessarily height-centered relative to digits: see [L2/06-259R](https://www.unicode.org/L2/L2006/06259r-mod-letters.pdf).

**Comment by VladWinner** [comment]
@dscorbett I reason from the fact that of all UI fonts I found, only in Segoe UI `U+A789` is not centered or raised. Regardless, this symbol is needed for applying Iosevka in some programs, where it is used to visual separate numbers plus for [Windows filenames](https://en.wikipedia.org/wiki/Colon_(punctuation)#:~:text=u%2Ba789)
I am talking now about relevance for code, and not as tone signs. I am sure that this was done intentionally, so as not to produce even more PUA chars.
