### ISSUE TITLE
support for Heavy Check Mark

### ISSUE THREAD

**Issue by PowerSnail** [be5invis/Iosevka#112]
* Your font version: Inziu Iosevka 1.9.4
* Your font variant: SC (no slab)
* Your operating system (name and version): Windows 
* Your application using Iosevka: fish shell running on bash for windows (WSL)

---

Some of fish shell themes uses Heavy Check Mark (U+2714) to express git conditions, and currently it only shows a rectangle box, so I assume that it is not yet supported in Inziu Iosevka.

Inziu Iosevka:
![image](https://cloud.githubusercontent.com/assets/7428673/19414670/7fc9915a-9322-11e6-8cbd-d94c7c481b3b.png)

DejaVu Sans Mono for Powerline:
![image](https://cloud.githubusercontent.com/assets/7428673/19414675/9d6cfe0e-9322-11e6-8d7c-5cb78db49fd0.png)

Thank you!

**Comment by be5invis** [comment]
It's already there. What's wrong?
![image](https://cloud.githubusercontent.com/assets/240091/19564322/c112525e-9715-11e6-84e8-2d33aaa89e08.png)
![image](https://cloud.githubusercontent.com/assets/240091/19564355/de4dd636-9715-11e6-929d-9bce270f6c50.png)
Sometimes overlapping an existing font may cause problems, you should delete all existing version of fonts, then remove the corresponded files located in `C:\Windows\Fonts` (`ttf` and `ttc`s started with `insiu` or `iosevka`), and install the latest one.

**Comment by be5invis** [comment]
Closed .
