### ISSUE TITLE
'cv30' does not apply to all variants of ⟨e⟩

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#1120]
Not all characters based on U+0065 LATIN SMALL LETTER E are affected by 'cv30':
* U+018F LATIN CAPITAL LETTER SCHWA
* U+01DD LATIN SMALL LETTER TURNED E
* U+0258 LATIN SMALL LETTER REVERSED E
* U+0259 LATIN SMALL LETTER SCHWA
* U+025A LATIN SMALL LETTER SCHWA WITH HOOK
* U+04D8 CYRILLIC CAPITAL LETTER SCHWA
* U+04D9 CYRILLIC SMALL LETTER SCHWA
* U+04DA CYRILLIC CAPITAL LETTER SCHWA WITH DIAERESIS
* U+04DB CYRILLIC SMALL LETTER SCHWA WITH DIAERESIS
* U+1D4A MODIFIER LETTER SMALL SCHWA
* U+1DEA COMBINING LATIN SMALL LETTER SCHWA
* U+2094 LATIN SUBSCRIPT SMALL LETTER SCHWA
![eƏǝɘəɚӘәӚӛᵊᷪₔ](https://user-images.githubusercontent.com/1124347/121818322-76f4b580-cc54-11eb-83e7-f0275a7a4316.png)

---

* Your font version: 7.0.4
* Your font variant: Iosevka Slab Extended
* Your operating system (name and version): macOS 10.14.6
* Your application using Iosevka: hb-view

**Comment by be5invis** [comment]
`e`'s rounded variant is somehow only for italics and mimics handwriting. Does this really make sense for reversed and turned shapes, especially Schwa?

**Comment by be5invis** [comment]
OK I saw rounded Schwa in some italics. It is legit now.
