### ISSUE TITLE
Ellipsis is two characters wide in SS05, should be one character?

### ISSUE THREAD

**Issue by krlmlr** [be5invis/Iosevka#1121]
The ellipsis character \u2026 seems to be two characters wide in Iosevka, other fonts (e.g. Fira Code) consistently use one character.

```
a…c
abc
```

This is a problem, because it messes up the display of software that assumes that the ellipsis is one character wide. The following output looks weird with Iosevka:

``` r
options(width = 20)
tibble::tibble(a = "1234567890", b = "abcdefghijk")
#> # A tibble: 1 x 2
#>   a         b       
#>   <chr>     <chr>   
#> 1 12345678… abcdefg…
```

<sup>Created on 2021-06-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

---

* Your font version: 7.0.4
* Your font variant: SS05
* Your operating system: macOS
* Your application using Iosevka: RStudio Desktop, Visual Studio Code

**Comment by be5invis** [comment]
This is by design.
The Term subfamilies have ellipsis being narrow, which should work for your case.
