### ISSUE TITLE
Fix overlapping in *bold/Heavy styles for U+013F and U+0198

### ISSUE THREAD

**Issue by VladWinner** [be5invis/Iosevka#1123]
U+013F
![image](https://user-images.githubusercontent.com/13555921/122138474-7e33e300-ce4f-11eb-83d3-e6bd79c787ef.png)

U+0198
![image](https://user-images.githubusercontent.com/13555921/122138983-99532280-ce50-11eb-8748-92e7938cd870.png)

---

* Your font version: 7.0.4
* Your font variant: Iosevka Extrabold/Heavy

**Comment by be5invis** [comment]
Wow, that's interesting: Ƙ should have hook at top right.
![image](https://user-images.githubusercontent.com/240091/122155843-a3f3c480-ce1c-11eb-8c3c-69db91c7d8e5.png)
