### ISSUE TITLE
U+A789 MODIFIER LETTER COLON looks like U+003A COLON

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#1126]
U+A789 MODIFIER LETTER COLON looks identical to U+003A COLON, but according to [L2/06-259R](https://www.unicode.org/L2/L2006/06259r-mod-letters.pdf#page=7), “Compared with a typical colon glyph, the dots of the MODIFIER LETTER COLON should be closer together, and the side bearings should be narrower.”

---

* Your font version: 7.1.0
* Your font variant: Iosevka Slab Extended
* Your operating system: macOS 10.14.6
* Your application using Iosevka: hb-view

**Comment by be5invis** [comment]
Iosevka follows a very rigid set of metrics so we cannot change side bearing. Distance between dots is reduced.
