### ISSUE TITLE
Cannot even run the command to build Iosevka in a docker

### ISSUE THREAD

**Issue by cssobral2013** [be5invis/Iosevka#1127]
It displays the following error:
Unable to find image 'de:latest' locally
docker: Error response from daemon: pull access denied for de, repository does not exist or may require 'docker login'.
But, I'm just logged.
---

* Your font version: 3.7.1
* Your font variant: Aile
* Your operating system (name and version): AIMS (based on Debian 10 buster)

**Comment by be5invis** [comment]
It looks like an environmental issue. I do not maintain docker images, perhaps you should reach out https://github.com/avivace/iosevka-docker.
Resolve as external.
