### ISSUE TITLE
Improvements for Cyrillic

### ISSUE THREAD

**Issue by VladWinner** [be5invis/Iosevka#1128]
In this request, I will cite some comments of professional font designers (about other fonts), so that my suggestions do not seem subjective, plus use Root UI and Golos UI fonts as a reference.

### U+0431 `б`
> The lowercase **б** is a failure: the terminal is deformed, too light, with a very sharp cut.

Suggestion of improvement (made in red) letter `б` in Inter font: [[Source]](https://type.today/en/journal/neo#:~:text=style-,the%20lowercase,-%D0%B1)

![image](https://user-images.githubusercontent.com/13555921/122691849-984c3780-d23a-11eb-9ad5-11a4d18784a1.png)
Demo:
![image](https://user-images.githubusercontent.com/13555921/122692034-87e88c80-d23b-11eb-9274-a3e4544a9104.png)

### U+041B `Л` | U+043B `л` | U+0414 `Д` | U+0434 `д`

> Unnecessarily dynamic stroke and incorrect contrast distribution in **д** and **л**.

Suggestion of improvement (made in red) letter `л` in Arimo font: [[Source]](https://type.today/en/journal/neo#:~:text=three-,unnecessarily,-dynamic)

![image](https://user-images.githubusercontent.com/13555921/122692316-ebbf8500-d23c-11eb-88d4-dead7c60f7c6.png)
Demo:
![image](https://user-images.githubusercontent.com/13555921/122692356-288b7c00-d23d-11eb-9a08-99c0080bbeb9.png)
![image](https://user-images.githubusercontent.com/13555921/122692704-570a5680-d23f-11eb-98e0-ca6a22570f26.png)

### U+042D `Э` | U+044D `э` | U+0404 `Є` | U+0454 `є`
> Width of the middle horizontal in **є**/**э** is too large

Demo:
![image](https://user-images.githubusercontent.com/13555921/122691645-b06f8700-d239-11eb-8410-70237efb3312.png)
Alternatively, you can reuse coordinates of middle horizontal from existing letter `з`:
![image](https://user-images.githubusercontent.com/13555921/122693743-d3069d80-d243-11eb-8f40-55d36e5ab5c8.png)

### U+0427 `Ч` | U+0447 `ч`
> In **Чч**, the arch is welded to the vertical mechanically — it desperately needs an angle.

Suggestion of improvement (made in red) letter `ч` in Jost font: [[Source]](https://type.today/en/journal/geo#:~:text=width-,in%20%D1%87%D1%87,-the)
![image](https://user-images.githubusercontent.com/13555921/122692402-7607e900-d23d-11eb-8298-786db1687884.png)

Demo:
![image](https://user-images.githubusercontent.com/13555921/122692428-a5b6f100-d23d-11eb-9c5e-76f987e3b19d.png)
It shouldn't repeat straight angle connection of `4` (U+0034).

### U+0424 `Ф` | U+0444 `ф`
> A slightly less rounded `ф`’s oval is required, just like default style of letter D

Demo:
![image](https://user-images.githubusercontent.com/13555921/122693400-617a1f80-d242-11eb-970f-8e32669cfaad.png)

**Comment by dom1n1k** [comment]
You read my mind
