### ISSUE TITLE
Russian п is Incorrect

### ISSUE THREAD

**Issue by firedev** [be5invis/Iosevka#113]
Small letter **п** is incorrect It should not look like **π**, PragmataPro does it right. Capital **П** is correct as well.

![image](https://cloud.githubusercontent.com/assets/115612/19547076/1ef4d9f2-96bf-11e6-8f37-2f173f5ce8c5.png)

**Comment by be5invis** [comment]
@firedev This?
![image](https://cloud.githubusercontent.com/assets/240091/19562781/32663048-9710-11e6-8381-327b4605064c.png)

**Comment by firedev** [comment]
Yep, pretty much.

**Comment by be5invis** [comment]
Fixed in the latest commit.
