### ISSUE TITLE
Slash and backslash aliased on small font sizes

### ISSUE THREAD

**Issue by SamantazFox** [be5invis/Iosevka#1131]
The slash `/` and backslash `\` characters are not properly anti-aliased on small font sizes (<=12 pt) resulting in a ladder look:

![font size 7 preview](https://user-images.githubusercontent.com/52980486/123178845-5b758000-d488-11eb-8487-01053ab4262b.png)
![font size 8 preview](https://user-images.githubusercontent.com/52980486/123178668-f588f880-d487-11eb-8c2e-19aa89e60ec4.png)
![font size 9 preview](https://user-images.githubusercontent.com/52980486/123178633-e4d88280-d487-11eb-85c6-3ffec8140334.png)
![font size 10 preview](https://user-images.githubusercontent.com/52980486/123178709-105b6d00-d488-11eb-8e28-ef5290dcd361.png)
![font size 11 preview](https://user-images.githubusercontent.com/52980486/123178733-1f421f80-d488-11eb-8b01-ec4f24399f14.png)
![font size 12 preview](https://user-images.githubusercontent.com/52980486/123178821-4d276400-d488-11eb-8d67-2638325e1b27.png)

Here is what it looks like with a large font size. You still see a litle bit of aliasing, but it's less noticeable than on smaller font sizes:

![image](https://user-images.githubusercontent.com/52980486/123178932-92e42c80-d488-11eb-9def-2d54d6b7a66d.png)

(Screenshots are for regular, but this happens for [italic] thin/light version too. The problem is less visible on [extra] bold variants).

---

* Your font version: v7.1.1 (latest at time of writing)
* Your font variant: Iosevka Fixed SS01 Regular
* Your operating system (name and version): Ubuntu 20.04
* Your application using Iosevka: Tilix

**Comment by be5invis** [comment]
I think it is a rendering configuration thing. Maybe you can try the unhinged version, which _may_ improve.

**Comment by SamantazFox** [comment]
> Maybe you can try the unhinged version, which _may_ improve.

unhinged? Do you mean [unhinted](https://github.com/be5invis/Iosevka/releases/download/v7.1.1/ttf-unhinted-iosevka-fixed-ss01-7.1.1.zip)?

**Comment by SamantazFox** [comment]
I've tried the unhinted version: the improvement is subtle, but it's still far from perfect...

**Comment by VladWinner** [comment]
Try to reconfigure FreeType on your Ubuntu machine.
I doubt that this is a problem of the font itself (I can find other examples where good fonts don't render well on some Linux builds).
