### ISSUE TITLE
Problems with square dots

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#1136]
Not all symbols and punctuation that include dots are affected by 'cv99' = 2:
* U+00BF INVERTED QUESTION MARK
* U+013F LATIN CAPITAL LETTER L WITH MIDDLE DOT
* U+0140 LATIN SMALL LETTER L WITH MIDDLE DOT
* U+203B REFERENCE MARK
* U+225F QUESTIONED EQUAL TO
* U+228D MULTISET MULTIPLICATION
* U+2339 APL FUNCTIONAL SYMBOL QUAD DIVIDE
* U+2360 APL FUNCTIONAL SYMBOL QUAD COLON
* U+2370 APL FUNCTIONAL SYMBOL QUAD QUESTION
* U+2A12 LINE INTEGRATION WITH RECTANGULAR PATH AROUND POLE
* U+2A13 LINE INTEGRATION WITH SEMICIRCULAR PATH AROUND POLE
* U+2A14 LINE INTEGRATION NOT INCLUDING THE POLE
* U+2A15 INTEGRAL AROUND A POINT OPERATOR
* U+2A40 INTERSECTION WITH DOT
* U+2E18 INVERTED INTERROBANG

![;¿Ŀŀ※≟⊍⌹⍠⍰⨒⨓⨔⨕⩀⸘](https://user-images.githubusercontent.com/1124347/123518015-1dd44b00-d672-11eb-9f78-411d9700e114.png)

I include the letters U+013F and U+0140 in this list because that dot is not a diacritic. They are compatibility characters for the sequences <U+004C, U+00B7> and <U+006C, U+00B7>. U+00B7 is affected by 'cv99', so these letters should be too.

'cv99' = 2 has no effect in any sequence of at least two of ⟨!⟩, ⟨.⟩, ⟨:⟩, and ⟨?⟩ in a row.
![;!.:?](https://user-images.githubusercontent.com/1124347/123518203-d8fce400-d672-11eb-83cb-ce00b237d246.png)

It also has no effect in the ⟨<!--⟩ ligature.
![!<!--](https://user-images.githubusercontent.com/1124347/123518654-e31fe200-d674-11eb-9c5c-8ad69687ec25.png)

'cv99' = 2 makes the dots of U+A789 MODIFIER LETTER COLON smaller. It should instead make them square or have no effect. Here is U+A789 after U+003A COLON:
![:꞉](https://user-images.githubusercontent.com/1124347/123518366-8cfe6f00-d673-11eb-9b54-5d7063d873fb.png)

---

* Your font version: 7.2.0
* Your font variant: Iosevka Slab Extended
* Your operating system (name and version): macOS 10.14.6
* Your application using Iosevka: hb-view

**Comment by be5invis** [comment]
L's dot is considered diacritic, so it will be left round.
