### ISSUE TITLE
what is the difference between iosevka and iosevka fixed?

### ISSUE THREAD

**Issue by CANBAAA** [be5invis/Iosevka#1137]
![image](https://user-images.githubusercontent.com/39176450/123532498-1f6c4480-d740-11eb-9713-f7da3dc4f183.png)

**Comment by be5invis** [comment]
Well, Fixed is mostly identical to Term, with symbols being narrow, however, it deleted ligations and also various wide-only characters, so it passes FontConfig's Monospace detection.
