### ISSUE TITLE
Missing Tugrik and Armenian dram signs (currency symbols)

### ISSUE THREAD

**Issue by VladWinner** [be5invis/Iosevka#1139]
- The requested character is...
  - [ ] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [x] Symbol (currency symbol)
- [x] Some other monospace/programming fonts supported this character. Provide images below.

------
### 1) Tugrik sign
![image](https://user-images.githubusercontent.com/13555921/123558795-d4364e00-d7a0-11eb-9782-baa07eb2e50d.png)
![image](https://user-images.githubusercontent.com/13555921/123558856-31ca9a80-d7a1-11eb-92ac-66a8c92a1f69.png)

https://ru.wikipedia.org/wiki/Символ_тугрика (In Russian)
https://en.wikipedia.org/wiki/Mongolian_t%C3%B6gr%C3%B6g#:~:text=the%20currency%20sign (In English, common page)
`U+20AE`

### 2) Armenian dram sign
![image](https://user-images.githubusercontent.com/13555921/123558934-c2a17600-d7a1-11eb-9084-a4a9e79dd437.png)
https://en.wikipedia.org/wiki/Armenian_dram_sign
`U+058F`

------
![image](https://user-images.githubusercontent.com/13555921/123559272-b0283c00-d7a3-11eb-83a2-ee18768b8aae.png)
![image](https://user-images.githubusercontent.com/13555921/123559482-ea460d80-d7a4-11eb-863d-dd854365a491.png)

**Comment by be5invis** [comment]
Armenian dram sign is located in the Armenian block, and its shape is not shared with other letters (unlike Baht sign). I'll reject it as out-of-scope, unless someone filed a feature request for the Armenian block.
