### ISSUE TITLE
Can`t download Iosevka version 7.2.1

### ISSUE THREAD

**Issue by in-in** [be5invis/Iosevka#1140]
Describe your problem here. Provide pictures and files if necessary.

Can't download _Iosevka version 7.2.1_
For example `super-ttc-sgr-iosevka-term-ss08-7.2.1` variant
```sh
Failure downloading https://github.com/be5invis/Iosevka/releases/download/v7.2.1/super-ttc-sgr-iosevka-term-ss08-7.2.1.zip, HTTP Error 404: Not Found'
```
![211791624840831](https://user-images.githubusercontent.com/8797432/123564573-9cd89900-d7c2-11eb-93fe-8d19717d2d35.png)

---

* Your font version: (Release or git, version) 7.2.1
* Your font variant: most of them (I think)
* Your operating system (name and version): Linux Mint 20.1 
* Your application using Iosevka: Desktop

**Comment by be5invis** [comment]
Recreating the release -- may take some time

**Comment by be5invis** [comment]
Recreated release, and download should work now. Closing.
