### ISSUE TITLE
SS13 Lucida Zero changed

### ISSUE THREAD

**Issue by nobk** [be5invis/Iosevka#1141]
0(zero) in 7.0.0-preview.5 and early 
![图片](https://user-images.githubusercontent.com/4659870/123611464-3724f500-d834-11eb-9820-58c756da483a.png)
7.0 and later, 0(zero) no center dot, it more like original lucida  but also copy its shortcomings, difficulty identifying O and 0.
![7](https://user-images.githubusercontent.com/4659870/123611858-9b47b900-d834-11eb-8f95-07cbb55a7b84.PNG)
Please revert 0(zero) to old version, because it is more friendly for programmer.

**Comment by be5invis** [comment]
This was changed by @vladwinner's #1065, but I found evidence of slashed zero, so changing it to slashed.

**Comment by be5invis** [comment]
Note: There ARE other editions of Lucida Console showing unslashed zero. For distinguishability, I decide to add slash.
