### ISSUE TITLE
Difficulties with ligations

### ISSUE THREAD

**Issue by funnym0nk3y** [be5invis/Iosevka#1143]
I just installed the default version of Iosevka and tried to use the ligations in Microsoft Terminal. Unfortunately just some of them work, eg `=>` works, but not `<=`, `->` or `->>`. In the case of  `->>` there is no arrow, but both smaller symbols get grouped together. 

---

* Your font version: 7.2.2
* Your font variant: default
* Your operating system (name and version): Win 10
* Your application using Iosevka: Microsoft Terminal

**Comment by be5invis** [comment]
I tried to reproduce this in Windows Terminal but all ligatures worked. One reminder: WT will not draw ligature between text with different colors, so that might be a reason.
Closing as Not Repro.

**Comment by funnym0nk3y** [comment]
Yeah, the different colors were the issue. Thanks!
