### ISSUE TITLE
Correction for the Bulgarian Cyrillic alphabet (contextual/language-specific substitutions)

### ISSUE THREAD

**Issue by VladWinner** [be5invis/Iosevka#1147]
Here I will point out the inconsistencies of the Bulgarian Cyrillic alphabet, the corrections _should not affect_ the default Cyrillic alphabet (Russian, Ukrainian etc.)
![image](https://user-images.githubusercontent.com/13555921/124401365-bda86d80-dd31-11eb-9c46-5f7f35dbc617.png)

<details>
  <summary>The difference between the Russian and Bulgarian Cyrillic alphabet</summary>

![image](https://user-images.githubusercontent.com/13555921/124399645-6b614f80-dd25-11eb-8b70-e7136aff15eb.png)
[Image source](https://commons.wikimedia.org/wiki/File:Bulgarian_cyrillic_(bg).svg)

</details>

### 1) [Fix] Revert `й` (that has the same basis as `и`; `и` already looks correct) to the previous iteration
languages.png — [r4.5.0](https://github.com/be5invis/Iosevka/blob/279bc1303c54f3333d595941a3d38c21a9ef753d/images/languages.png) (top) vs [7.2.5](https://github.com/be5invis/Iosevka/blob/74bb41773d973e92d14673cb1ae53582734ab0dc/images/languages.png) (bottom)
![image](https://user-images.githubusercontent.com/13555921/124399707-e460a700-dd25-11eb-9537-7b0d8afac7cf.png)
Screenshot of the previous iteration was taken randomly, degrade could have occurred later (than in 4.5.0)

### 2) Apply cursive shape to `ь`, `ъ` (but without slant) → `"cv69" 3` | `cyrl-yeri = 'cursive'`
![image](https://user-images.githubusercontent.com/13555921/124400084-a022d600-dd28-11eb-81bc-b23367781a64.png)
Comparison of Iosevka Extended with Akrobat, Bahnschrift, Cascadia Mono/Code :
![image](https://user-images.githubusercontent.com/13555921/124400605-5b993980-dd2c-11eb-8063-d232c0c87241.png)
(Russian/Ukrainian Cyrillic at top, Bulgarian Cyrillic at bottom)

### 3) Make a Bulgarian version of `Д` (with `Δ` or Bulgarian `Л`-like cap)
Comparison of Iosevka Extended with PT Root UI, Akrobat, Bahnschrift, Cascadia Mono/Code + Spectral & Vollkorn :
![image](https://user-images.githubusercontent.com/13555921/124400551-03623780-dd2c-11eb-872d-8e31aff1168f.png)
(Russian/Ukrainian Cyrillic at top, Bulgarian Cyrillic at bottom)

### 4) [Slab] Duplicate logic of upper serifs style from `ц`/`и` to `ч` and `н`
![image](https://user-images.githubusercontent.com/13555921/124401203-a452f180-dd30-11eb-9d7e-743d3944579a.png)

**Comment by VladWinner** [comment]
@be5invis
[Slab Italic] Is it possible to apply logic of default Cyrillic `к` serifs to Bulgarian glyph?
![image](https://user-images.githubusercontent.com/13555921/125212503-83514a00-e2b6-11eb-8c4c-d08680e3b7b8.png)

**Comment by be5invis** [comment]
@VladWinner fixed
