### ISSUE TITLE
\scr family of LaTeX characters

### ISSUE THREAD

**Issue by tpoisot** [be5invis/Iosevka#1149]
- The requested character is...
  - [x] Latin
- [ ] Some other monospace/programming fonts supported this character. Provide images below.

| Iosevka | [JuliaMono](https://github.com/cormullion/juliamono) |
|----|-----|
| ![2021-07-06-132833_379x257_scrot](https://user-images.githubusercontent.com/579329/124642565-fd6c7380-de5d-11eb-90c8-a098c084a980.png) | ![2021-07-06-132659_287x237_scrot](https://user-images.githubusercontent.com/579329/124642582-00fffa80-de5e-11eb-9bef-ec3d44507bad.png) |

------

The `\scr` family of LaTeX characters would be really good to have - in the screenshots above, the first line is the standard characters, second is `\itR\ite\ita\itl`, and third is `\scrR\scre\scra\scrl` - the last line doesn't look as good in Iosevka

**Comment by be5invis** [comment]
Merge into #714. 
This work needs some hand-drawn glyphs instead of code generating them. Perhaps you can use fallback to support these for now.
Closing.
