### ISSUE TITLE
Is "<" higher than lower-case letters by design?

### ISSUE THREAD

**Issue by wdhwg001** [be5invis/Iosevka#115]
Iosevka: 
![32](https://cloud.githubusercontent.com/assets/8943519/19756856/0a839a1a-9c52-11e6-8b6e-a1afdbd83f3a.png)

PragmataPro:
![34](https://cloud.githubusercontent.com/assets/8943519/19756955/9c5d47f6-9c52-11e6-8e29-5855f66669e2.png)

M+:
![20](https://cloud.githubusercontent.com/assets/8943519/19756961/a4f1abdc-9c52-11e6-8d93-ab618b292f67.jpg)

I'm wondering that it is made by design or just an issue?

**Comment by be5invis** [comment]
Yes, to synchronize with the height of hyphens.
Closed.
