### ISSUE TITLE
Inconsistent top hook on U+0284 LATIN SMALL LETTER DOTLESS J WITH STROKE AND HOOK

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#1151]
The top hook of U+0284 LATIN SMALL LETTER DOTLESS J WITH STROKE AND HOOK should be modified for consistency with the hooks modified for #1072.
![ʄ](https://user-images.githubusercontent.com/1124347/125080207-8b30a480-e092-11eb-9ccd-90b24f8f4c60.png)

---

* Your font version: 7.2.6
* Your font variant: Iosevka Slab Extended
* Your operating system: macOS 10.14.6
* Your application using Iosevka: hb-view

**Comment by be5invis** [comment]
Code chart says:
![image](https://user-images.githubusercontent.com/240091/125150460-cbc10a00-e0f4-11eb-970c-4be36e7647bd.png)

So it should follow variants of `f` and bring shapes from `U+025F`.
