### ISSUE TITLE
Issue with the ◌̆ diacritic on Cyrillic "т" and "я", and clash of the ◌̆ diacritic on Cyrillic "ґ"

### ISSUE THREAD

**Issue by Qonsyuma** [be5invis/Iosevka#1157]
![image](https://user-images.githubusercontent.com/20151443/126085335-de6cc528-5701-47bf-ba08-87b2c4c798a3.png)

The ◌̆ diacritic (U+0306) when put on many cyrillic characters works fine and works well with the height of the characters, though for the Cyrillic letter "т" and "я" the diacritic goes too high, even though the letters are the same height as many of the other characters on the picture. It's as if the diacritic is aligned with the assumption that "т" and "я" were in their uppercase versions (Я̆ and Т̆ work fine).

When the diacritic is put on the Cyrillic letter "ґ", the diacritic overlaps with the letter (this goes for the uppercase Ґ too: Ґ̆).

---

* Your font version: 7.3.0
* Your font variant: Iosevka Fixed
* Your operating system (name and version): Windows 21H1
* Your application using Iosevka: VSCode and Notepad (both have the same issue)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/126086302-8940710f-1a31-43f3-88ca-1d825951c9e8.png)

**Comment by Qonsyuma** [comment]
Awesome, thank you! 👍
