### ISSUE TITLE
宽高比

### ISSUE THREAD

**Issue by supyoung** [be5invis/Iosevka#116]
* Your font version: (Release or git, version)
* Your font variant:
* Your operating system (name and version):
* Your application using Iosevka: (some Java applications may have problem in showing Iosevka properly. It is a bug in Java's GUI components.)

If you have problem when building Iosevka, please provide these informations:

* Your Node.js version:
* Your results of `npm list`
* Your _otfcc_ version:
* Your FontForge version:
* Your `parameters.toml`:

---请问字体宽高比是多少啊？还有有什么工具或者方法得到一个字体的宽高比？再进一步能够自定义调整吗？

Describe your problem here. Provide pictures and files if necessary.

**Comment by be5invis** [comment]
there are options in `parameters.toml.` The default height/weight is 1.25em by 0.5em
Closed.

**Comment by supyoung** [comment]
请问有什么工具或者方法得到一个字体的宽高比……这个好像没回答
