### ISSUE TITLE
Italic-style look for upright font

### ISSUE THREAD

**Issue by pv4** [be5invis/Iosevka#1165]
Is it possible to add an option/setting to get an italic-style look for upright font?

On the picture attached you can see how cyrillic would look like if such an option existed and was enabled. E.g. look at `de` having `de.italic` style applied as well as many other glyphs.

The variant attached was got by building with
```
[buildPlans.iosevka-some.slopes]
upright='italic'
```
and applying the sed before building:
```
sed -i "s/\.upright/.italic/g" font-src/glyphs/common/derivatives.*
```

![image](https://user-images.githubusercontent.com/2502094/126728633-1e6a4dd7-ff4f-4d77-917b-3b819fe5245a.png)

**Comment by be5invis** [comment]
Merge into #599. This is about slope angle customization.

**Comment by pv4** [comment]
> This is about slope angle customization.

Not really. I don't want "Italic with a zero slope angle". I want "Regular with italic look AND zero slope angle".

I think I've found a better way than in the original post.

First, allow changing isItalic in private-build-plans.toml:

```diff
diff -Napur Iosevka-dev.orig/font-src/support/parameters.js Iosevka-dev/font-src/support/parameters.js
--- Iosevka-dev.orig/font-src/support/parameters.js     2021-07-17 08:50:52.000000000 +0300
+++ Iosevka-dev/font-src/support/parameters.js  2021-07-23 16:32:41.084191868 +0300
@@ -135,6 +135,9 @@ function createMetricDataSet(sink, mo) {
 function numericFieldHandler(sink, key, x) {
        if (x != null && isFinite(x)) sink[key] = x;
 }
+function booleanFieldHandler(sink, key, x) {
+       sink[key] = x;
+}
 function subObjectHandler(sink, key, obj) {
        sink[key] = {};
        createMetricDataSet(sink[key], obj);
@@ -154,5 +157,6 @@ const metricOverrideHandlers = {
        powerlineShiftX: numericFieldHandler,
        onumZeroHeightRatio: numericFieldHandler,
        multiplies: subObjectHandler,
-       adds: subObjectHandler
+       adds: subObjectHandler,
+       isItalic: booleanFieldHandler
 };

```

Then, use the following settings for build plan:
```toml
[buildPlans.iosevka-some.slopes]
upright='normal'

[buildPlans.iosevka-some.metric-override]
isItalic=true
```
Now iosevka-some-regular.ttf has the look I want.

Could you consider please making such a possibility supported? In #599 you wrote:
> I think slope angles less than 10° should work, but not tested.

I guess zero is less than 10 so it "should work". But font-src/meta/naming.ptl has the following code that makes me think that using isItalic for Regular family is wrong and would behave badly in some environments.
```
set font.os2.fsSelection : accumulate : list
[...]
    list  Ot.Os2.FsSelection.ITALIC            (isItalic || isOblique)
    list  Ot.Os2.FsSelection.REGULAR           (!isBold && !isItalic && !isOblique)
[...]
set font.head.macStyle : accumulate : list
[...]
    list  Ot.Head.MacStyle.Italic     (isItalic || isOblique)
```

What do you think?

**Comment by be5invis** [comment]
With the new slope customization, you can do that. The result is like
```toml
[buildPlans.iosevka-custom.slopes.upright]
angle = 0
shape = "italic"
menu  = "upright"
css   = "normal"
```

**Comment by pv4** [comment]
Thank you!
