### ISSUE TITLE
Undefined in `regular` stye filepath

### ISSUE THREAD

**Issue by bevanjkay** [be5invis/Iosevka#1167]
All of the Iosevka variants have `undefined` in the file path for the `regular` versions.
From what I can see, this may only be the case in the `.ttc` archives.

![Screen Shot 2021-07-26 at 10 15 52 am](https://user-images.githubusercontent.com/40621599/126918152-a4c139b2-16b8-499d-9b8d-850d245c2d34.png)

---

* Your font version: 8.0.0
* Your font variant: All
* Your operating system (name and version): MacOS Big Sur

**Comment by be5invis** [comment]
8.0.1 will have this fixed.

**Comment by iostapyshyn** [comment]
@be5invis as I can tell this commit has caused `extended` typefaces to be in separate files. As result the distribution now has 18 `.ttc` files, not 9. Was this intended? If yes, the release notes should definitely be updated.

As of now the homebrew packages are broken and are missing extended typefaces

**Comment by be5invis** [comment]
@iostapyshyn 8.0.2 will fix this
