### ISSUE TITLE
改了parameters.toml之后怎么弄成ttf？

### ISSUE THREAD

**Issue by supyoung** [be5invis/Iosevka#117]
* Your font version: (Release or git, version)
* Your font variant:
* Your operating system (name and version):
* Your application using Iosevka: (some Java applications may have problem in showing Iosevka properly. It is a bug in Java's GUI components.)

If you have problem when building Iosevka, please provide these informations:

* Your Node.js version:
* Your results of `npm list`
* Your _otfcc_ version:
* Your FontForge version:
* Your `parameters.toml`:

---...改参数只能用在网页上吗...想改变一些参数自定义一个ttf怎么弄……

Describe your problem here. Provide pictures and files if necessary.

**Comment by be5invis** [comment]
run make.
