### ISSUE TITLE
Remove top serifs on some barred letter variants

### ISSUE THREAD

**Issue by NoxUltima** [be5invis/Iosevka#1171]
Describe your problem here. Provide pictures and files if necessary.

The bar on some letters such as Cyrillic Small Letter Dje (shown below) has the bar overlapping with the top left serif, especially on the heavier weights. I suggest the top serif on top-serifed variants can be removed so the bar can be clearly distinguished.

![2021-07-27 17_31_01-FontCreator 12 0 (UNREGISTERED)](https://user-images.githubusercontent.com/16898444/127132272-6fa70ec3-7bac-4743-97a4-832cbb9842b6.png) ![2021-07-27 17_40_31-FontCreator 12 0 (UNREGISTERED)](https://user-images.githubusercontent.com/16898444/127132797-697c7a2e-c922-42a1-a818-8794e9fd61ab.png)

An example (Cascadia Code), showing this glyph and lowercase h: 

![2021-07-27 17_46_00-FontCreator 12 0 (UNREGISTERED)](https://user-images.githubusercontent.com/16898444/127133603-07ccbca4-a66b-47d2-bfa2-90bd612e9a44.png)

---

* Your font version: (Release or git, version)
* Your font variant:
* Your operating system (name and version):
* Your application using Iosevka:

**Comment by be5invis** [comment]
Made forward fix to make the bar and serif not overlapping. Closing.

**Comment by NoxUltima** [comment]
Regardless, thanks! :)
