### ISSUE TITLE
Default monospace TTC file bigger than SS variants

### ISSUE THREAD

**Issue by vincentbernat** [be5invis/Iosevka#1175]
Hey! 

Default monospace TTC file weights more than 200MB while all SS variants are about 50MB each. All of them contain 162 fonts.  I was wondering if there may have been an issue with the default file?

---

* Your font version: 8.0.2

**Comment by be5invis** [comment]
Because SS variants removed `cv##`/`ss##` OpenType feature (since they are, well, "fonts with pre-baked variation applied"), massively reduced file size.
Closing as by design.
