### ISSUE TITLE
number is 

### ISSUE THREAD

**Issue by phantomk** [be5invis/Iosevka#1177]
Describe your problem here. Provide pictures and files if necessary.
number is unaligned on vs code
![image](https://user-images.githubusercontent.com/3520021/127533055-32293768-3200-404f-9aa2-527faf5e5d62.png)

---

* Your font version: 8.0.2 SS07, SS12,SS14 
* Your font variant: SS07, SS12,SS14 
* Your operating system (name and version): mac 
* Your application using Iosevka: vs code

**Comment by phantomk** [comment]
ok, because i use
`  "editor.fontLigatures": "'ss01', 'ss02', 'ss03', 'ss04', 'ss05', 'ss06', 'zero', 'onum'",`
use `"editor.fontLigatures": true,` is ok

**Comment by mfocko** [comment]
Isn't it because the stylistic sets don't necessarily apply to all digits and if you have multiple of them enabled it makes them „broken“?

**Comment by be5invis** [comment]
@phantomk @mfocko Removing `onum` will fix this. See https://en.wikipedia.org/wiki/Text_figures.
