### ISSUE TITLE
Make cursive `w` similar to cursive `v`

### ISSUE THREAD

**Issue by wimstefan** [be5invis/Iosevka#1179]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

As already requested in #852 the cursive variant of `w` could be closer in form to the cursive `v` which is based on the form found in Recursive Mono.

To make it more clear I've mocked up an example `w` based on Recursive Mono and compared it to the cursive `v` as it is already in Iosevka ...

![iosevka-w-cursive](https://user-images.githubusercontent.com/4605934/127731756-63c9a1e8-f8c8-4e0d-92ed-63941485019a.png)
![iosevka-cursive-v](https://user-images.githubusercontent.com/4605934/127651519-2215d5c6-612d-45d4-a277-0d22903fe9c3.png)

**Comment by wimstefan** [comment]
Thank you so much for the lightning fast response!
I was trying both `cursive` and `cursive-motion-serifed` variants but they look very similar to the old variants as soon on the Iosevka Customizer with rounded forms. 
What I was trying to ask for was a sharp left down corner as in the `cursive` v-variant. I hope the new mockup shows that a little bit clearer ...
![Iosevka-w-v-comparison](https://user-images.githubusercontent.com/4605934/127732711-2628095a-480b-4baf-bfcb-d883f1bf79f2.png)

Sorry for the inconvenience :/

**Comment by be5invis** [comment]
If you look at the thin weight there is indeed a sharp corner. This corner is getting smoothed in cursive `v` when the weight grows.
![image](https://user-images.githubusercontent.com/240091/127745953-4d388907-e213-4e5a-b779-90de2cf54c23.png)
The Center bar is further reduced in `dev`.

**Comment by wimstefan** [comment]
Well what can I say? 
**I declare myself officially too stupid to understand your genius work after spending 4 hours this afternoon to understand the logic of variant creation.** 
By accident I discovered how to lower the center bar and I did that with 
```js
define y4 : top - [Math.max (top * 0.1) (3.5 * [AdviceStroke 3.5])]
```
But you simplified that solution again ...
At least I know how to get the center bar as low as the `straight-vertical-sides{,motion-serifed}` variant - that's what I like the most at the moment. The ideal form would be the left half of `straight-vertical-sides{,motion-serifed}` (with the low center bar) and the right half of `cursive` :)

In any case I want to thank you again that you took the time to look into my humble request 🙏

But most of all I want to thank you for the most beautiful and versatile font one could think of !!! 🙏🙏🙏
