### ISSUE TITLE
run make，get empty dist

### ISSUE THREAD

**Issue by supyoung** [be5invis/Iosevka#118]
* Your font version: (Release or git, version)
* Your font variant:
* Your operating system (name and version):
* Your application using Iosevka: (some Java applications may have problem in showing Iosevka properly. It is a bug in Java's GUI components.)

If you have problem when building Iosevka, please provide these informations:

* Your Node.js version:6.9.1
* Your results of `npm list`
$ make
node ./node_modules/patel/bin/patel-c --optimize --strict support/glyph.ptl -o s                                                                                                                upport/glyph.js
module.js:471
    throw err;
    ^

Error: Cannot find module 'F:\Iosevka-master—2\Iosevka-master\node_modules\patel                                                                                                                \bin\patel-c'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
make: *** [makesupport.mk:20：support/glyph.js] 错误 1

然后我就安装patel

$ npm install patel
iosevka@1.9.2 F:\Iosevka-master—2\Iosevka-master
`-- patel@0.31.4
  +-- escodegen@1.8.1
  | +-- esprima@2.7.3
  | +-- estraverse@1.9.3
  | +-- esutils@2.0.2
  | +-- optionator@0.8.2
  | | +-- deep-is@0.1.3
  | | +-- fast-levenshtein@2.0.5
  | | +-- levn@0.3.0
  | | +-- prelude-ls@1.1.2
  | | +-- type-check@0.3.2
  | | `-- wordwrap@1.0.0
  | `-- source-map@0.2.0
  |   `-- amdefine@1.0.1
  +-- esmangle@1.0.1
  | +-- escodegen@1.3.3
  | +-- escope@1.0.3
  | | `-- estraverse@2.0.0
  | +-- esprima@1.1.1
  | +-- esshorten@1.1.1
  | | `-- estraverse@4.1.1
  | +-- estraverse@1.5.1
  | +-- esutils@1.0.0
  | +-- optionator@0.3.0
  | | +-- fast-levenshtein@1.0.7
  | | +-- levn@0.2.5
  | | `-- wordwrap@0.0.3
  | `-- source-map@0.1.43
  +-- patrisika@0.21.0
  | `-- patrisika-scopes@0.11.0
  +-- resumer@0.0.0
  | `-- through@2.3.8
  `-- yargs@6.3.0
    +-- camelcase@3.0.0
    +-- cliui@3.2.0
    | +-- strip-ansi@3.0.1
    | | `-- ansi-regex@2.0.0
    | `-- wrap-ansi@2.0.0
    +-- decamelize@1.2.0
    +-- get-caller-file@1.0.2
    +-- os-locale@1.4.0
    | `-- lcid@1.0.0
    |   `-- invert-kv@1.0.0
    +-- read-pkg-up@1.0.1
    | +-- find-up@1.1.2
    | | +-- path-exists@2.1.0
    | | `-- pinkie-promise@2.0.1
    | |   `-- pinkie@2.0.4
    | `-- read-pkg@1.1.0
    |   +-- load-json-file@1.1.0
    |   | +-- graceful-fs@4.1.10
    |   | +-- parse-json@2.2.0
    |   | | `-- error-ex@1.3.0
    |   | |   `-- is-arrayish@0.2.1
    |   | +-- pify@2.3.0
    |   | `-- strip-bom@2.0.0
    |   |   `-- is-utf8@0.2.1
    |   +-- normalize-package-data@2.3.5
    |   | +-- hosted-git-info@2.1.5
    |   | +-- is-builtin-module@1.0.0
    |   | | `-- builtin-modules@1.1.1
    |   | +-- semver@5.3.0
    |   | `-- validate-npm-package-license@3.0.1
    |   |   +-- spdx-correct@1.0.2
    |   |   | `-- spdx-license-ids@1.2.2
    |   |   `-- spdx-expression-parse@1.0.4
    |   `-- path-type@1.1.0
    +-- require-directory@2.1.1
    +-- require-main-filename@1.0.1
    +-- set-blocking@2.0.0
    +-- string-width@1.0.2
    | +-- code-point-at@1.1.0
    | `-- is-fullwidth-code-point@1.0.0
    |   `-- number-is-nan@1.0.1
    +-- which-module@1.0.0
    +-- window-size@0.2.0
    +-- y18n@3.2.1
    `-- yargs-parser@4.0.2

npm WARN iosevka@1.9.2 No repository field.
npm WARN iosevka@1.9.2 No license field.

这个警告应该没有什么影响
之后再run make
$ make
node ./node_modules/patel/bin/patel-c --optimize --strict support/glyph.ptl -o s                                                                                                                upport/glyph.js
node ./node_modules/patel/bin/patel-c --optimize --strict support/spiroexpand.pt                                                                                                                l -o support/spiroexpand.js
node ./node_modules/patel/bin/patel-c --optimize --strict support/spirokit.ptl -                                                                                                                o support/spirokit.js
node ./node_modules/patel/bin/patel-c --optimize --strict parameters.ptl -o para                                                                                                                meters.js
node ./node_modules/patel/bin/patel-c --optimize --strict support/anchor.ptl -o                                                                                                                 support/anchor.js
node ./node_modules/patel/bin/patel-c --optimize --strict support/point.ptl -o s                                                                                                                upport/point.js
node ./node_modules/patel/bin/patel-c --optimize --strict support/transform.ptl                                                                                                                 -o support/transform.js
node ./node_modules/patel/bin/patel-c --optimize --strict support/utils.ptl -o s                                                                                                                upport/utils.js
node ./node_modules/patel/bin/patel-c --optimize --strict meta/aesthetics.ptl -o                                                                                                                 meta/aesthetics.js
node ./node_modules/patel/bin/patel-c --optimize --strict meta/naming.ptl -o met                                                                                                                a/naming.js
node ./node_modules/patel/bin/patel-c --optimize --strict meta/features.ptl -o m                                                                                                                eta/features.js
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/common-shapes.p                                                                                                                tl -o glyphs/common-shapes.js
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/overmarks.ptl -                                                                                                                o glyphs/overmarks.js
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/letters-unified                                                                                                                -basic.ptl -o glyphs/letters-unified-basic.js
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/letters-unified                                                                                                                -extended.ptl -o glyphs/letters-unified-extended.js
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/numbers.ptl -o                                                                                                                 glyphs/numbers.js
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/symbol-punctuat                                                                                                                ion.ptl -o glyphs/symbol-punctuation.js
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/symbol-math.ptl                                                                                                                 -o glyphs/symbol-math.js
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/symbol-letter.p                                                                                                                tl -o glyphs/symbol-letter.js
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/symbol-geometri                                                                                                                c.ptl -o glyphs/symbol-geometric.js
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/symbol-other.pt                                                                                                                l -o glyphs/symbol-other.js
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/symbol-braille.                                                                                                                ptl -o glyphs/symbol-braille.js
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/autobuilds.ptl                                                                                                                 -o glyphs/autobuilds.js
node ./node_modules/patel/bin/patel-c --optimize --strict buildglyphs.ptl -o bui                                                                                                                ldglyphs.js
make fonts config=d-sans
make[1]: 进入目录“/cygdrive/f/Iosevka-master—2/Iosevka-master”
make[2]: 进入目录“/cygdrive/f/Iosevka-master—2/Iosevka-master”
Microsoft Windows [▒汾 6.1.7601]
▒▒Ȩ▒▒▒▒ (c) 2009 Microsoft Corporation▒▒▒▒▒▒▒▒▒▒Ȩ▒▒▒▒

F:\Iosevka-master▒▒2\Iosevka-master>
它进入目录之后我猜会做点什么？然而并没有，到这就停止工作了，dist是空文件夹
* Your _otfcc_ version:0.5.1
* Your FontForge version:2016-10-04
* Your parameters.toml`: width=1250, 其余不变

---

Describe your problem here. Provide pictures and files if necessary.

**Comment by be5invis** [comment]
Building on Windows requires some UNIX commands being usable. It is preferred that you install MSYS2, and perform building in Bash.
Closed.

**Comment by cloudhan** [comment]
使用MSYS2 msys repo中的`make`会产生和上面一样的错误：
``` bash
$ make
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/common-shapes.ptl -o glyphs/common-shapes.js
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/overmarks.ptl -o glyphs/overmarks.js
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/letters-unified-basic.ptl -o glyphs/letters-unified-basic.js
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/letters-unified-extended.ptl -o glyphs/letters-unified-extended.js
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/numbers.ptl -o glyphs/numbers.js
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/symbol-punctuation.ptl -o glyphs/symbol-punctuation.js
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/symbol-math.ptl -o glyphs/symbol-math.js
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/symbol-letter.ptl -o glyphs/symbol-letter.js
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/symbol-geometric.ptl -o glyphs/symbol-geometric.js
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/symbol-other.ptl -o glyphs/symbol-other.js
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/symbol-braille.ptl -o glyphs/symbol-braille.js
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/autobuilds.ptl -o glyphs/autobuilds.js
node ./node_modules/patel/bin/patel-c --optimize --strict buildglyphs.ptl -o buildglyphs.js
make fonts config=d-sans
make[1]: 进入目录“/d/workspaces/Iosevka”
make[2]: 进入目录“/d/workspaces/Iosevka”
Microsoft Windows [▒汾 10.0.14393]
(c) 2016 Microsoft Corporation▒▒▒▒▒▒▒▒▒▒Ȩ▒▒▒▒

D:\workspaces\Iosevka>
```

使用mingw64 repo的`mingw32-make`，产生如下错误（清空`build/`只会多出`patel`那一部分）
``` bash
$ mingw32-make.exe
C:/msys64/mingw64/bin/mingw32-make fonts config=d-sans
mingw32-make[1]: Entering directory 'D:/workspaces/Iosevka'
mingw32-make[2]: Entering directory 'D:/workspaces/Iosevka'
    Start building font Iosevka Thin 1.10.5 (Juno)
    Iosevka Thin 1.10.5 (Juno) Successfully built.
    Writing outline as SVG -> build/.pass0-iosevka-thin.svg
    Writing metadata as JSON -> build/.pass0-iosevka-thin.fdt
onegroup.mk:115: recipe for target 'build/.pass1-iosevka-thin.ttf' failed
mingw32-make[2]: *** [build/.pass1-iosevka-thin.ttf] Error 1
mingw32-make[2]: Leaving directory 'D:/workspaces/Iosevka'
makefile:94: recipe for target 'fonts' failed
mingw32-make[1]: *** [fonts] Error 2
mingw32-make[1]: Leaving directory 'D:/workspaces/Iosevka'
makefile:138: recipe for target 'fonts-d-sans' failed
mingw32-make: *** [fonts-d-sans] Error 2
```

再次运行`mingw32-make`
``` bash
$ mingw32-make.exe
C:/msys64/mingw64/bin/mingw32-make fonts config=d-sans
mingw32-make[1]: Entering directory 'D:/workspaces/Iosevka'
mingw32-make[2]: Entering directory 'D:/workspaces/Iosevka'
otfccdump : Read SFNT : [ERROR] Cannot read SFNT file "build/.pass1-iosevka-thin.ttf". Exit.
undefined:1



SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at Socket.<anonymous> (D:\workspaces\Iosevka\pass2-finalize.js:12:19)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
otfccbuild : Parse into JSON : [ERROR] Cannot parse JSON file "(null)". Exit.
onegroup.mk:121: recipe for target 'build/iosevka-thin.ttf' failed
mingw32-make[2]: *** [build/iosevka-thin.ttf] Error 1
mingw32-make[2]: Leaving directory 'D:/workspaces/Iosevka'
makefile:94: recipe for target 'fonts' failed
mingw32-make[1]: *** [fonts] Error 2
mingw32-make[1]: Leaving directory 'D:/workspaces/Iosevka'
makefile:138: recipe for target 'fonts-d-sans' failed
mingw32-make: *** [fonts-d-sans] Error 2
```

搞不清楚 `onegroup.mk:115: recipe for target 'build/.pass1-iosevka-thin.ttf' failed` 这一行到底发生了什么，build所需要的命令和工具应该都能访问到

**Comment by be5invis** [comment]
it is fontforge, again

发自我的 iPhone

在 2017年1月23日，19:58，Cloud Han <notifications@github.com<mailto:notifications@github.com>> 写道：


使用MSYS2 msys repo中的make会产生和上面一样的错误：

$ make
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/common-shapes.ptl -o glyphs/common-shapes.js
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/overmarks.ptl -o glyphs/overmarks.js
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/letters-unified-basic.ptl -o glyphs/letters-unified-basic.js
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/letters-unified-extended.ptl -o glyphs/letters-unified-extended.js
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/numbers.ptl -o glyphs/numbers.js
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/symbol-punctuation.ptl -o glyphs/symbol-punctuation.js
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/symbol-math.ptl -o glyphs/symbol-math.js
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/symbol-letter.ptl -o glyphs/symbol-letter.js
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/symbol-geometric.ptl -o glyphs/symbol-geometric.js
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/symbol-other.ptl -o glyphs/symbol-other.js
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/symbol-braille.ptl -o glyphs/symbol-braille.js
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/autobuilds.ptl -o glyphs/autobuilds.js
node ./node_modules/patel/bin/patel-c --optimize --strict buildglyphs.ptl -o buildglyphs.js
make fonts config=d-sans
make[1]: 进入目录“/d/workspaces/Iosevka”
make[2]: 进入目录“/d/workspaces/Iosevka”
Microsoft Windows [▒汾 10.0.14393]
(c) 2016 Microsoft Corporation▒▒▒▒▒▒▒▒▒▒Ȩ▒▒▒▒

D:\workspaces\Iosevka>

使用mingw64 repo的mingw32-make，产生如下错误（清空build/只会多出patel那一部分）

$ mingw32-make.exe
C:/msys64/mingw64/bin/mingw32-make fonts config=d-sans
mingw32-make[1]: Entering directory 'D:/workspaces/Iosevka'
mingw32-make[2]: Entering directory 'D:/workspaces/Iosevka'
    Start building font Iosevka Thin 1.10.5 (Juno)
    Iosevka Thin 1.10.5 (Juno) Successfully built.
    Writing outline as SVG -> build/.pass0-iosevka-thin.svg
    Writing metadata as JSON -> build/.pass0-iosevka-thin.fdt
onegroup.mk:115: recipe for target 'build/.pass1-iosevka-thin.ttf' failed
mingw32-make[2]: *** [build/.pass1-iosevka-thin.ttf] Error 1
mingw32-make[2]: Leaving directory 'D:/workspaces/Iosevka'
makefile:94: recipe for target 'fonts' failed
mingw32-make[1]: *** [fonts] Error 2
mingw32-make[1]: Leaving directory 'D:/workspaces/Iosevka'
makefile:138: recipe for target 'fonts-d-sans' failed
mingw32-make: *** [fonts-d-sans] Error 2

再次运行mingw32-make

$ mingw32-make.exe
C:/msys64/mingw64/bin/mingw32-make fonts config=d-sans
mingw32-make[1]: Entering directory 'D:/workspaces/Iosevka'
mingw32-make[2]: Entering directory 'D:/workspaces/Iosevka'
otfccdump : Read SFNT : [ERROR] Cannot read SFNT file "build/.pass1-iosevka-thin.ttf". Exit.
undefined:1



SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at Socket.<anonymous> (D:\workspaces\Iosevka\pass2-finalize.js:12:19)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
otfccbuild : Parse into JSON : [ERROR] Cannot parse JSON file "(null)". Exit.
onegroup.mk:121: recipe for target 'build/iosevka-thin.ttf' failed
mingw32-make[2]: *** [build/iosevka-thin.ttf] Error 1
mingw32-make[2]: Leaving directory 'D:/workspaces/Iosevka'
makefile:94: recipe for target 'fonts' failed
mingw32-make[1]: *** [fonts] Error 2
mingw32-make[1]: Leaving directory 'D:/workspaces/Iosevka'
makefile:138: recipe for target 'fonts-d-sans' failed
mingw32-make: *** [fonts-d-sans] Error 2

搞不清楚 onegroup.mk:115: recipe for target 'build/.pass1-iosevka-thin.ttf' failed 这一行到底发生了什么，build所需要的命令和工具应该都能访问到

**Comment by be5invis** [comment]
You can try to remove `$(SUPPRESS_ERRORS)`, because FF always complains about contour orientation...

**Comment by sliceofcode** [comment]
Try running `git clean -xdf`. I think the cause is an incomplete build leaving files that confuse FF.

**Comment by cloudhan** [comment]
Sorry, that is because FontForge is not in the PATH. I found this problem
while I was opening a new issue...
