### ISSUE TITLE
Cleanup font table after generation

### ISSUE THREAD

**Issue by Zhern** [be5invis/Iosevka#1183]
Hi,

I am using nerd-fonts in order to add some icons.
I saw that FontForge cannot even just open and re-save the Iosevka-generated font (without even using nerd-fonts), it complains about too much characters being inside the font table (the addresses seem to be 16bit only and it complains about 65600+ chars).
My previous build vas with Iosevka release v7.0.2, and my new one is with v9.0, so I can't really say since what release it happens but after the 7.0.2 and before (or since) 9.0.

At the end of the table are all the possible characters variants in normal, bold, italic, bold+italic. It represents 13201 slots total (1/5th of the table).
I wonder if it could be possible to automatically remove all the ones that are not used by the font config in order to save space inside the table?

**Comment by be5invis** [comment]
You can try with a `no-cv-ss` custom build -- which will *significantly* reduce the glyph count.

**Comment by Zhern** [comment]
Indeed this solves my problem, thank you for the tip!
