### ISSUE TITLE
Add Monolisa variant

### ISSUE THREAD

**Issue by IvayloHrTonev** [be5invis/Iosevka#1186]
Hi

Recently I have learned about Monolisa font .
It is possible to add such variant.
I think Monolisa is very close to Iosevka

**Comment by be5invis** [comment]
The biggest problem is that I have no SS tags to assign to it. I have only `ss19` left, but I plan to reserve it.
Also Monolisa sort of cursive (?) which is not very Iosevka-style-matching.

**Comment by IvayloHrTonev** [comment]
I see thank you for the explanation ,
