### ISSUE TITLE
Is there a tip jar?

### ISSUE THREAD

**Issue by teauxfu** [be5invis/Iosevka#1190]
**Is your feature request related to a problem? Please describe.**
I'd like to support development with a tip, but there's not a clear way to do so

**Describe the solution you'd like**
A section on the site or readme suggesting ways to support development outside of issues/PRs

**Describe alternatives you've considered**
A "Buy me a coffee" button, or similar tip jar

**Additional context**
Thanks for making Iosevka

**Comment by be5invis** [comment]
Thanks but it is not needed :)
Closing.
