### ISSUE TITLE
Website oblique sample doesn't show upright |

### ISSUE THREAD

**Issue by clsn** [be5invis/Iosevka#1191]
Down in the "Variants a la carte" section, choose the "force-upright" option for the `|` character, and choose "Oblique" at the top of that section, above the sample text.  Expected the `|` to be upright and not slanted (tooltip for option says it would be "forced upright under italics and oblique.")  But the `|` character is slanted just like the rest of the letters.  If you choose "Italic", then the `|` *does* show straight, like it's supposed to.

I just noticed it on the website; I don't know if this means the actual font is built that way.

Observed on a Mac, OS 10.14.3, under Chrome, version 90.0.4430.212.  Iosevka version 9.0.1, but as a webfont, not a local one.

**Comment by be5invis** [comment]
This VS only applies to Italic for now... Should get fixed

**Comment by clsn** [comment]
Either that or change the tooltip/docs.
