### ISSUE TITLE
It is best to have a complete JetBrains mono ligature

### ISSUE THREAD

**Issue by liangjingkanji** [be5invis/Iosevka#1192]
- [ ] This ligation is implemented in other programming fonts. Provide samples below.
- [ ] A programming language requires this ligation. Provide the information below.

![image](https://user-images.githubusercontent.com/21078112/129479180-0e2b5822-5daa-46e2-837d-5bf1d3fb9d19.png)
![image](https://user-images.githubusercontent.com/21078112/129479189-123ca63a-49d7-4ed1-80ff-a43cfa036761.png)

------

*Please provide justification here.*

It is best to have a complete JetBrains mono ligature

**Comment by be5invis** [comment]
Those logical operators will be under `dlig`.
![image](https://user-images.githubusercontent.com/240091/129495385-9dd7aeb4-ebd2-4e59-90fd-3aac7e0caf8d.png)

Closing.
