### ISSUE TITLE
Can the second one be used by default slanted of `>=` ?

### ISSUE THREAD

**Issue by liangjingkanji** [be5invis/Iosevka#1194]
- [ ] A programming language requires this ligation. Provide the information below.
- [ ] This ligation is implemented in other programming fonts. Provide samples below.

![image](https://user-images.githubusercontent.com/21078112/129500219-850eef7f-093c-4b78-8623-75b8e60dc8c1.png)

------

*Please provide justification here.*

Can the second one be used by default?, I don't know much about customization

**Comment by be5invis** [comment]
If you are using in VSCode you can use `"editor.fontLigatures": "'calt' 1, 'cv95' 2"`.
Otherwise, you need a custom build. You can use https://typeof.net/Iosevka/customizer to generate a configuration file and make a custom build form it.
Closing.
