### ISSUE TITLE
License clarification and proper attribution

### ISSUE THREAD

**Issue by dntzu** [be5invis/Iosevka#1197]
I'd like to publish my custom build plan along with custom typeface so here is some questions that I have due to lack of information in README.

1. According to comments for issue #265 font files is licensed under SIL OFL but the source code is licensed under BSD is that still correct?
2. Is it completely permitted to use 'Iosevka' for names of derivative typefaces? Or it could be used but just as addition to its own name?
3. How we should properly attribute you? Just alongside with other names or maybe with something like this: "based on Iosevka by Renzhi Li..."?

**Comment by be5invis** [comment]
1. Currently everything is under OFL, just like other OSS fonts.
2. You can use the Iosevka name for derivatives.
3. "Based on Iosevka by Renzhi Li aka. Belleve Invis".
