### ISSUE TITLE
U+204A TIRONIAN SIGN ET

### ISSUE THREAD

**Issue by andrewmccarthy** [be5invis/Iosevka#1198]
- The requested character is...
  - [X] Punctuation
 - [X] Some other monospace/programming fonts supported this character. Provide images below.
 
Poorly supported, but in Fira Mono it looks like this:
![image](https://user-images.githubusercontent.com/6887733/130255726-a79f5a59-9cd5-4a1e-93b3-53ab5a0d7b9f.png)

The shape can vary, with the bars being either straight or curved. A serif is rare, and when present usually only seen on the top-left. See [https://www.fileformat.info/info/unicode/char/204a/fontsupport.htm](https://www.fileformat.info/info/unicode/char/204a/fontsupport.htm), but note the curved tail on the Junicode samples is very unusual.

------
*Please provide justification here.*
U+204A is like an ampersand "&" and is still used in Irish, but is poorly supported in existing fonts. Too often we have to fake it with slanted/subscript numeral 7, etc. Better support for it would be greatly appreciated! See also [Wikipedia](https://en.wikipedia.org/wiki/Tironian_notes#Current).

Many thanks!

**Comment by VladWinner** [comment]
More examples:
![image](https://user-images.githubusercontent.com/13555921/130305134-32a891c8-002a-4392-a882-9e25bac736f2.png)

**Comment by VladWinner** [comment]
@be5invis Now there is an opportunity to slightly improve glyphs preview (sample-code):

Before:
`¢ ſ ß ΓΛΔ αδιλξ КУЗЯ эльф язычник `
`1234567890 ,._-+= >< ¯-¬_ >~–÷+×< `
`!iIlL17|¦ coO08BbDQ $5SZ2zsz 96G& `
`dbqp E3 g9q CGQ vvw VVW /V <= >=`

After:
`¢ ſʒ ß ΓΛΔ ηταν КУЗЯ эльф язычник `
`0123456789 ,._-+= >< ¯-¬_ >~–÷+×< `
`!iIlL17⁊|¦ coO08BbDQ $5SZ2₴zs96G& `
`dbqp E3З g9q CGQ vvw VVW /V <= >=`

![image](https://user-images.githubusercontent.com/13555921/130332254-13874a52-43f8-4154-bc8f-9c42fc91b680.png)
