### ISSUE TITLE
Font not recognized as Fixed width on windows 7

### ISSUE THREAD

**Issue by Zhichao-Hong** [be5invis/Iosevka#12]
The font renders and looks great on osx.  On Windows 7, the font cannot be activated in Visual Studio and not shown as fixed width font.

**Comment by bitserf** [comment]
I am experiencing the same issue.

@Zhichao-Hong: I have found that Visual Studio can at least use the font if you restart it (the first time you select it, it uses Courier New for some reason).

@be5invis There is a discussion about this issue for other open fonts over here: http://fontforge.10959.n7.nabble.com/Regenerated-font-does-not-recognize-as-a-Monospace-in-Windows-td11291.html

They recommend checking how DejaVu Sans Mono does it, apparently the  isFixedPitch bit needs to be set to 1, but from the discussion it sounds like that isn't necessarily the only issue.

**Comment by be5invis** [comment]
Is it related to `sFamilyClass` field in OS/2 table? The PANOSE is already set to Monospace.

**Comment by bitserf** [comment]
Yes, I checked this in FontForge too, so I am not sure why Windows thinks it is not Monospace.

Are there any glyphs that are zero-width or not full-width, perhaps?

**Comment by be5invis** [comment]
@bitserf well Fontforge drops `post.isFixedPitch`. I added a new pass to bring them back. Could you please checkout the built result using the newest code in `master` works?
(maybe you should install `ttx` to make the building works.)

**Comment by bitserf** [comment]
@be5invis: Unfortunately I am currently on my Windows machine, so it's a bit difficult to build the font.

However, I used a script to set isFixedPitch and that makes Visual Studio think its Monospace, so I think your modified version should work.

The script I used is this one: https://git.fedorahosted.org/cgit/liberation-fonts.git/tree/scripts/setisFixedPitch-fonttools.py

I will try your change in master when I get home.

**Comment by be5invis** [comment]
@bitserf @Zhichao-Hong I released version 0.1.9. Is it fixed?

**Comment by bitserf** [comment]
@be5invis 0.1.9 works for me, thanks!

**Comment by Zhichao-Hong** [comment]
It nows works flawlessly on Windows 7.  Superb font and great job!
Thanks!
