### ISSUE TITLE
Slightly refine glyphs preview (sample-code)

### ISSUE THREAD

**Issue by VladWinner** [be5invis/Iosevka#1202]
Before (current):
`¢ ſ ß ΓΛΔ αδιλξ КУЗЯ эльф язычник `
`1234567890 ,._-+= >< ¯-¬_ >~–÷+×< `
`!iIlL17|¦ coO08BbDQ $5SZ2zsz 96G& `
`dbqp E3 g9q CGQ vvw VVW /V <= >=`

After (suggestion):
`¢ ſʒ ß ΓΛΔ ηταν КУЗЯ эльф язычник `
`0123456789 ,._-+= >< ¯-¬_ >~–÷+×< `
`!iIlL17⁊|¦ coO08BbDQ $5SZ2₴zs96G& `
`dbqp E3З g9q CGQ vvw VVW /V <= >=`

Preview:
![image](https://user-images.githubusercontent.com/13555921/130332254-13874a52-43f8-4154-bc8f-9c42fc91b680.png)

Changes:
- `ſʒ` (previous iteration of `ß`) next to `ß` instead of just `ſ`
- `ηταν` ('he/she/it was' in Greek) instead of `αδιλξ`
- `0` is placed to the left of other numbers in accordance with the order in Cherry-Picking
- Added Tironian sign representing et `⁊` next to `7` as a part of legibility test row
- Added Hryvnia sign `₴` next to `2` as a part of legibility test row
- `z` added twice in one line is now reduced to one 
- Added Cyrillic letter Ze `З` next to `3` for legibility test purposes
- Now absolutely each line has the same number of glyphs

Source: https://github.com/be5invis/Iosevka/issues/1198#issuecomment-903162106

**Comment by be5invis** [comment]
This sample is used to display character variants so `ξ` must be there.
For the legibility test, I do not think Cyrillic Ze(`З`), Tironian Et (`⁊`), and Hryvnia Sign (`₴`) are frequently used in programming -- so not worth adding them.
