### ISSUE TITLE
Weird tone marks rendering in Vietnamese

### ISSUE THREAD

**Issue by linhusp** [be5invis/Iosevka#1204]
The marks are taller and placed abit higher than usual. It seems there was some overlaps between them (the `ˆ` vs `˜`, `ˊ`, `ˋ`, etc). To me its harder to read in Bold or Heavy Bold. I checked an old version (8.0.2), the issue was not happened back then.

Some screenshots in Neovim, `Iosevka Extended 40`:

* On `v10.1.1`, notice those words `Buổi`, `nhiều` or `rất`

![Screenshot from 2021-08-30 23-50-15](https://user-images.githubusercontent.com/31442477/131418724-f18f38ad-b3f2-4614-a211-3aa114672f7f.png)

* On `v8.0.2`

![Screenshot from 2021-08-30 23-43-54](https://user-images.githubusercontent.com/31442477/131419681-e3f71667-b3d6-45f2-9748-16cb8444f23d.png)

For comparison, this is `Meslo LG S` font on the same size:

![Screenshot from 2021-08-30 23-56-16](https://user-images.githubusercontent.com/31442477/131419747-7f12c771-9c93-45ea-9c7a-24f0aa1939e5.png)

---

* Your font version: 10.1.1 release
* Your font variant: Default
* Your operating system (name and version): Arch Linux, Gnome 40, Kernel 5.13
* Your application using Iosevka: Neovim on Tilix Terminal

**Comment by be5invis** [comment]
Now it will not collide.
