### ISSUE TITLE
[Custom build query] How to request smaller geometric shapes?

### ISSUE THREAD

**Issue by bluz71** [be5invis/Iosevka#1205]
Hello,

Long time user.

I would like to know with the new custom build system how to specify building a custom font with the smaller geometric shapes. Currently I always seem to be getting the larger shapes.

This is image may explain things better:

![iosevka](https://user-images.githubusercontent.com/11382509/131468576-db5913fc-13c3-4964-ab3c-3334b89b0955.png)

I want to build a font with the smaller in-red shapes.
But I always seem to be getting the larger in-green shapes via the new configurator.

Previously (aka last year) I used to be able to do the following to get the smaller geometric shapes:

```
[buildPlans.iosevka-custom]
family = "Iosevka Custom"
design = ["sp-fixed"]
...
...
```

But now the build system is quite different.

It must be obvious, but what is it that I need to specify in the build system to get the smaller geometric shapes?

Thanks.

**Comment by alexeyten** [comment]
Try
```toml
[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "fixed" # or "term"
...
```

See https://github.com/be5invis/Iosevka#configuring-custom-build

**Comment by bluz71** [comment]
I did, they did not appear to make a difference.

**Comment by pv4** [comment]
The "larger" triangle actually is not "larger", it's "wider". Iosevka suggests two variants of such glyphs: normal/single-width ("smaller" triangle in your case) and double-width (your "larger" one). Most glyphs are always single-width (e.g. latin letters and digits) but some can be made double-width to make them larger and more visible wherever possible (see below).

On the picture the left variant is the single-width one, and the right is the double-width one. Double-click the glyph variant on specimen page and the select it with the mouse to get the similar result. As you see, the "larger" is twice as wide as the "smaller".

Wider variants are for environments where glyphs are allowed to be of different widths where making them larger makes them more visible. But there are cases where all the glyphs MUST have the same width. `spacing='fixed'` is exactly for building Iosevka for such environments and it MUST work exactly the same way as `sp-fixed` in previous versions making the glyphs to be "smaller".

Are you SURE what you see is the "large" figure? How exactly do you check that?

![image](https://user-images.githubusercontent.com/2502094/131586540-0f1b6cd4-ce2b-4bc7-bdea-2cd1458ad5a4.png)

**Comment by bluz71** [comment]
Hello @pv4,

This is what I am seeing (in pictures).

Tag `v3.3.1` from August 2020 (with : `design = ["sp-fixed"]`):

![iosevka_old](https://user-images.githubusercontent.com/11382509/131602370-ee6ae287-7468-44f1-92bd-aa1a73da7c8c.png)

And current top of master, tag `v10.1.1` (with: `spacing = "fixed"`):

![iosevka_new](https://user-images.githubusercontent.com/11382509/131602478-eda564c4-9112-4cee-b30b-312c4dae9070.png)

There is a difference in size for the green triangles and red square. That may relate to single width vs double width, or maybe the geometric shape metrics have changed in the last year?

I am used to, and prefer, the smaller geometric shapes, hence I would like to build a custom font with the smaller shapes. But I don't know how (hence this issue).

I will experiment with git bisect and see if I can figure out what is going on here.
If you have some ideas that would also be appreciated.

Thanks.

**Comment by pv4** [comment]
Hello @bluz71

From your screenshots I see that the issue is NOT in single-width/double-width glyphs.

> the geometric shape metrics have changed in the last year?

I think you're right and the design has changed.

**Comment by pv4** [comment]
The glyph 0x25B6 shown on the first picture in the issue is defined in the files with urls provided below (look through the code).

The difference can partially be in triangleOvershoot. It has different values in 3.3.1 (`2 / [Math.sqrt 3]`) and 10.1.1 (`2.1 / [Math.sqrt 3]`). But I think there are also other factors that influence the view.

https://github.com/be5invis/Iosevka/blob/v3.3.1/font-src/glyphs/symbol-geometric.ptl#L211
https://github.com/be5invis/Iosevka/blob/v10.1.1/font-src/glyphs/symbol/geometric/plain.ptl#L237

**Comment by pv4** [comment]
> I am used to, and prefer, the smaller geometric shapes

The question of taste, but I personally prefer small font sizes. And the larger a symbol, the better it's visible and distinguishable. So I like the new, larger variant more.

**Comment by bluz71** [comment]
@pv4,

Yes, most definitely it is a different metric, not a single vs double issue. Apologies for the wrong assumption.

I had a look through the git log of `font-src/glyphs/symbol` and a lot of work has occurred, new symbols and changed metrics. A lot has changed.

This is a fundamentally a deliberate style change.

I am very used to the old geometric symbol sizes, so this change has quite discombobulated me.

But the new size is not wrong, some (maybe most) folk will prefer it. This is not a bug.

I will see whether I can get used to it.

Tag `v3.7.1` has the old geometric shape sizing (I may revert to this and stay there, to-be-determined).
`HEAD` has the new geometric shape sizing.

Thanks for the discussion, it has clarified the situation. Closing.

**Comment by bluz71** [comment]
> I will see whether I can get used to it.
> 
> Tag `v3.7.1` has the old geometric shape sizing (I may revert to this and stay there, to-be-determined).
> `HEAD` has the new geometric shape sizing.

I ended up reverting to the older `v3.7.1` tag (probably permanently). I simply couldn't get used to the new, larger, geometric shapes of Iosevka.

I find the older, and smaller, geometric shapes look great.

Cheers.
