### ISSUE TITLE
Full width Underscore

### ISSUE THREAD

**Issue by PyGamer0** [be5invis/Iosevka#1207]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.
![image](https://user-images.githubusercontent.com/64531844/131615242-1601c804-2249-4832-9b5a-9e138399b0bf.png)
![image](https://user-images.githubusercontent.com/64531844/131615318-3d8c23ff-e8a5-40be-834b-3b983d10939c.png)

------

*Please provide your justification here.*
I think the connected underscore looks better

**Comment by be5invis** [comment]
Well the term “full width underscore” is usually used to reference `U+FF3F`.
`dlig` has a ligation that connects underscores.
