### ISSUE TITLE
Should Fullwidth brackets look different than halfwidth brackets?

### ISSUE THREAD

**Issue by wdhwg001** [be5invis/Iosevka#121]
The `（` / `）` in Iosevka looks exactly the same as `&nbsp;(` / `)&nbsp;`.

It's hard to recognize, and will bring troubles to debugging.

Any plans to change them?

**Comment by firedev** [comment]
Do you have a picture?

**Comment by wdhwg001** [comment]
![brackets](https://cloud.githubusercontent.com/assets/8943519/20301402/20e68298-ab5e-11e6-989d-437872ced40f.jpg)

**Comment by firedev** [comment]
Pardon my ignorance, what do SBC and DBC mean? Why these should look different? The examples look the same.

**Comment by wdhwg001** [comment]
They're formally called `Fullwidth Left Parenthesis(U+FF08)` and `Fullwidth Right Parenthesis(U+FF09)`, I've changed the title.

**Comment by firedev** [comment]
Now I see what you mean, thanks `（` vs `(` and `)` vs`）`

**Comment by wdhwg001** [comment]
Using fullwidth characters is a common coding mistake in Eastern Asia, so Iosevka makes the debugging a bit harder.

IMO the right way is to widen, enlarge or center fullwidth characters, just like `＞`(U+FF1E) vs `>`.

**Comment by be5invis** [comment]
> ... center fullwidth characters
Centering brackets breaks the typesetting style about them.
Widing them may be a solution, but seriously, the current brackets are already wide enough.

**Comment by be5invis** [comment]
@wdhwg001 If you really want to distinguish...
I have an idea that adds a **boxed** version of them and you can enable them using a `cv##` or `ss##` style...

**Comment by wdhwg001** [comment]
@be5invis Well however they may look bad in some 'pure' localized CJK comments...

Since most CJK characters are square-like fullwidth ideographs, making fullwidth brackets curvier to 'fit the width' might not be a bad idea...

And actually, many Chinese fonts just made them bigger or curvier than halfwidth brackets. So even they may break some design principles, they are the most acceptable common practices.

**Comment by be5invis** [comment]
@wdhwg001 First, Iosevka's brackets are very deep compared to most Latin typefaces. Their natural width fits em-boxes well.
Second, the idea is to acquire a clean distinguish between FW and HW in the source code, not typesetting. And it is off by default, and not provided by the official builds either.

**Comment by wdhwg001** [comment]
@be5invis IMO if you add a feature which is off by default, that means this is not an common fix, and of course are not for Inziu versions.

BTW, I think those fullwidth brackets probably shouldn't be designed to be together with halfwidth Latin characters, so maybe we should try a bigger change that wides all fullwidth characters to 'fit fullwidth size'?

**Comment by be5invis** [comment]
@wdhwg001 You can build a special Iosevka, `Iosevka StFW` that can be installed SXS with the existing Iosevka and it will stress all FW glyphs.

**Comment by wdhwg001** [comment]
@be5invis lol if it's a big work then maybe you can just make the brackets curvier.
Or we can also simply remove fullwidth brackets from Iosevka so that system will fall back to another font(or roboto for Inziu), which makes fullwidth brackets look different :)

**Comment by be5invis** [comment]
@wdhwg001 Iosevka Term does not contain any FW glyphs. I think you are looking for that.

**Comment by wdhwg001** [comment]
@be5invis Yes, but currently I'm totally a newbie when talking about contributing Iosevka.

I'll try to read the code and document, but currently is there a plan or some workarounds about fullwidth graphs?

**Comment by be5invis** [comment]
@wdhwg001 Use Iosevka Term solely. It does not have any FW.

**Comment by wdhwg001** [comment]
Okay. Since there's at least a fall-back solution for this, I'll close this issue and open another one which requests different fullwidth graphs.
