### ISSUE TITLE
Variants of # that touch the baseline

### ISSUE THREAD

**Issue by nxltm** [be5invis/Iosevka#1210]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

I find it would be a good idea to include baseline-touching variants of the `#` sign, as the current variants of `#` in Iosevka **pass through** the baseline, unlike other existing symbols such as `%` and `&`. 

![image](https://user-images.githubusercontent.com/16898444/131848254-f69b16bd-bbe5-4ee3-969d-97d9ea329b0e.png)

Shown below from the left are IBM Plex Mono, Fira Code and DM Mono, which are just some of the countless mono fonts that have a `#` that just touch the baseline. 

![lambda](https://user-images.githubusercontent.com/16898444/131832494-3753c3b1-d50b-4c53-ba95-5a79eb20498d.png)

**Comment by be5invis** [comment]
The number sign should always align to baseline-CAP instead of other tall punctuations.
