### ISSUE TITLE
Uppercase Xi `Ξ` (Sans only) and lowercase Chi `χ` should not have serifs

### ISSUE THREAD

**Issue by nxltm** [be5invis/Iosevka#1212]
Describe your problem here. Provide pictures and files if necessary.

You can change the tag to Variant Request if you want.

![image](https://user-images.githubusercontent.com/16898444/131847915-8377d08b-0218-4f36-a234-c77da9b6bd1a.png)
![image](https://user-images.githubusercontent.com/16898444/131936910-7bb82e65-40cc-4e9f-ab3f-bb5d4fa2fdfb.png)

As for chi, here are the proposed variants (Anonymous Pro/Fira Code, IBM Plex Sans, Roboto Sans), with tails on the top left and bottom right, which should be like this throughout even if the font has slabs or not.

![image](https://user-images.githubusercontent.com/16898444/131937345-feac5719-7568-4218-a79a-28566e04326f.png)

---

* Your font version: (Release or git, version) 10.1.0
* Your font variant: 
* Your operating system (name and version): Windows 10
* Your application using Iosevka: NA

**Comment by be5invis** [comment]
If we remove serifs from `Ξ` then `χ` should not have serifs too.

**Comment by nxltm** [comment]
> If we remove serifs from `Ξ` then `χ` should not have serifs too.

Yep.
