### ISSUE TITLE
No horizontal ellipsis in ttc-iosevka-10.1.1

### ISSUE THREAD

**Issue by randomMesh** [be5invis/Iosevka#1213]
- The requested character is...
  - [ ] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [x] Punctuation
  - [ ] Symbol
- [ ] Some other monospace/programming fonts supported this character. Provide images below.

------

Hello, i use Ubuntu Server 21.04 on a Raspberry Pi 400, installed a gui and extracted the fonts in ttc-iosevka-10.1.1.zip to `/usr/local/share/fonts/iosevka/`. I use `rxvt-unicode` as my terminal emulator.

All renders fine, except the horizontal ellipsis ([…](https://www.fileformat.info/info/unicode/char/2026/index.htm)) which looks like this:

![2021-09-03-082308_1920x1080_scrot](https://user-images.githubusercontent.com/32773707/131960547-ec3176f7-65a7-401e-be25-52fc8508c1ac.png)

Locale is German, UTF-8:
```
xxx@xxx:~$ locale
LANG=de_DE.UTF-8
LANGUAGE=
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=
```

I load the font in `.Xresources` like this:
```
URxvt.font: xft:Iosevka:style=Regular:size=12
URxvt.boldFont: xft:Iosevka:style=Bold:size=12
URxvt.italicFont: xft:Iosevka:style=Italic:size=12
URxvt.boldItalicFont: xft:Iosevka:style=Bold Italic:size=12
```

Is there really no ellipsis in the font or am i doing something wrong? If it's not there, please add it.

**Comment by be5invis** [comment]
Iosevka has U+2026 in the files. Maybe need to check some settings...

**Comment by randomMesh** [comment]
Uhm, my mistake. Using ttf-iosevka instead of ttc-iosevka resolved the issue.
