### ISSUE TITLE
Customizer's highlighted characters don't show up in Safari

### ISSUE THREAD

**Issue by iostapyshyn** [be5invis/Iosevka#1214]
https://typeof.net/Iosevka/customizer

Having selected custom `D` and `d` letters, this is what I see in Safari:
<img width="1422" alt="Screen Shot 2021-09-03 at 13 52 59" src="https://user-images.githubusercontent.com/18750600/132001112-768f7a0d-fb4e-43f1-823c-ee8c448937c2.png">

After turning off "Highlight Customized Characters" the problem goes away:
<img width="1400" alt="Screen Shot 2021-09-03 at 13 53 56" src="https://user-images.githubusercontent.com/18750600/132001235-b4388774-1cab-471d-9e02-ce827bb7f761.png">

**Comment by be5invis** [comment]
O, safari dislikes gradient text in inline elements.
Next version will fix this.
