### ISSUE TITLE
Explain what "sgr" is in package list

### ISSUE THREAD

**Issue by bluikko** [be5invis/Iosevka#1217]
**Is your feature request related to a problem? Please describe.**
"sgr" versions of the packages have appeared but they are not explained in the "package list".

**Describe the solution you'd like**
"package list" document could have a word on what does "sgr" mean.

**Describe alternatives you've considered**
Searched the issues for "sgr" and looked around a bit but did not find an explanation.

**Additional context**
I'm a font noob.

**Comment by be5invis** [comment]
`sgr` means Single Group, and is added to differentiate the TTC packages that contain single spacing variant vs multiple spacing variants. It was introduced to fix #1112.

**Comment by brainchild0** [comment]
I am not finding the new text in the documentation or notes.

Also, I need help understanding the meanings of both "SGR" and "Super". The explanations are very terse, and they assume a certain level of knowledge.

**Comment by brainchild0** [comment]
I found the [full document](https://github.com/be5invis/Iosevka/blob/main/tools/amend-readme/src/fragments/packages-desc.md) buried in the source tree, although it seems not to be linked or invoked presently.

I believe I now understand that the monospaced variants are subdivided further into three spacing variants, for code, terminal, and "fixed". Each archive labeled SGR contains only one of the three spacing variants, whereas other archives are available that package all three together.

However, I continue to face confusion, by the observation that the SGR archives are sized larger than the ones containing all three variants.

Regardless, it would be beneficial for the documentation to explain the many variations in greater detail and clarity.
