### ISSUE TITLE
only two weights in Vs code

### ISSUE THREAD

**Issue by adsick** [be5invis/Iosevka#1219]
Hi, could someone help me setting up Iosevka in VSC?

I've downloaded super-ttc-iosevka-10.2.0.zip installed it on my Windows 10 laptop, then in VSC I wrote:
```   "editor.fontFamily": "Iosevka, monospace",```
and saw some nice, but thin Iosevka font, but that is too thin:
![image](https://user-images.githubusercontent.com/24528839/132946118-fc76aca8-31dc-4e39-9f44-4d48317051bc.png)

I've started messing up with ``` "editor.fontWeight": "normal"``` and after some time I realized that there is only two weights - the thinnest and the boldest. I've tried many different values and found out that 500 is same as 100, 549 same as 500, but 550 is same as 1000!

![image](https://user-images.githubusercontent.com/24528839/132946240-d67ca4dc-e4b6-4912-a5b0-cb563db4a3c1.png)

how can I fix that? I've expected this standard pack to have all 9 weights

**Comment by pv4** [comment]
Are you sure it's iosevka on the screenshots? Digit `5` and lowercase `t` visually differs from iosevka look.

**Comment by alexeyten** [comment]
That looks like Courier New. The default monospace font in Windows

**Comment by adsick** [comment]
so how to fix that? why there are no instructions on how to specify fonts? I'm from backend and that pisses me off

**Comment by pv4** [comment]
@adsick
Never have used vscode but there are some suggestions to try:
1. removing ", monospace" from fontFamily,
2. replacing the simple "Iosevka" family name by something like "Iosevka Term" or "Iosevka Fixed" (find it from opening font files using standard windows font viewer),
3. installing font some other way (have you installed it PROPERLY?)

**Comment by adsick** [comment]
1. I'll try
2. I think Iosevka Term worked, but what if I want regular? (also not sure if that fixes weightelection)

3. yep, there are no things that may go wrong. it's just right click -> install.

p.s. it would be nice if there were 'official' setup instructions from Iosevka

**Comment by pv4** [comment]
> what if I want regular?

It can always be an issue with how vscode handles font selection. Try installing only "simple Iosevka" files from zip (or whatever you installed it from) and not installing "Term" and "Fixed".

> it would be nice if there were 'official' setup instructions from Iosevka

There are lots of applications using fonts and such instructions would become really huge.

**Comment by adsick** [comment]
So, now everything is fine, I'm not sure what exactly did the thing, but it seems like regular reboot helped.
![image](https://user-images.githubusercontent.com/24528839/132957422-ebaaf486-dadc-4690-a60e-fee9dad9c708.png)

weights are working well as well.
