### ISSUE TITLE
The donation button stops working.

### ISSUE THREAD

**Issue by wdhwg001** [be5invis/Iosevka#122]
The link:
http://7xpe0v.com1.z0.glb.clouddn.com/aeqr9bewtqtvpkpl18.png
is probably not working.

**Comment by alehandrof** [comment]
I also wanted to donate and the button seems not be working. (Unless I don't understand what it's supposed to do.)

**Comment by be5invis** [comment]
@alehandrof It's an Alipay QR code, you need an Alipay account for donation.
