### ISSUE TITLE
Arrows (->) render incorrectly in VS Code, size 14

### ISSUE THREAD

**Issue by vjalle** [be5invis/Iosevka#1221]
Hi,

Some minor issues with VS Code and the best programming font ever:
- With font size 14, the arrows (C ligature for ->) are rendered asymmetrically. The head goes down 3 pixels from the middle bar but only 1 pixel up. Looks bad. It's better at other sizes, but it's only completely symmetrical at size 19.
-  With font size 15..17 and 20..21, the letter m looks bad. Opened a ticket for this earlier, the issue still exists.

As a consequence, the minimal acceptable size is 18 (arrow has minor asymmetry), and only 19 renders correctly.

Editor font zoom and view zoom were both fixed at 100%. There is a custom 100% scale factor set in Windows.

![image](https://user-images.githubusercontent.com/79142437/133321095-f60d085b-1853-40f4-8413-e38716b2e1b1.png)
![image](https://user-images.githubusercontent.com/79142437/133321796-23cf001e-300d-4409-83a3-0af4a44a8320.png)

I'd also recommend adding an arrow variant with solid head.

---

Iosevka 10.2 (custom build, release is affected too)
Curly Extralight (other variants and weights are affected too)
Win10 1909
VS Code 1.60.1, font size set to 14, zoom 100%

**Comment by be5invis** [comment]
This is bilevel (ink-and-paper)? No antialiasing?
Iosevka (and _many many modern fonts_) doesn't have manual hints so we expect it is used in environments with antialiasing.

**Comment by vjalle** [comment]
Hey,
Thanks for the quick response again!
It seems to be bilevel. Cleartype and enabling font smoothing seems to have no effect on the rendering in VS Code, though the change was visible on icon labels.
My concern is that antialiasing is expected to solve artifacts smaller than one pixel. Here we have 2 pixels of asymmetry / error. Could that be solved by antialiasing, or probably something is wrong with the design of these characters?
Or maybe it's a VS Code issue...
