### ISSUE TITLE
Example for Disabling Calt for building Iosevka custom Ligation

### ISSUE THREAD

**Issue by GulajavaMinistudio** [be5invis/Iosevka#1223]
I'm trying to build custom Iosevka Font , and reading your documentation about custom ligation here.
[https://github.com/be5invis/Iosevka#ligations](https://github.com/be5invis/Iosevka#ligations)

_"Iosevka supports Language-Specific Ligations, which is the ligation set enabled only under certain languages. These ligation sets are assigned to custom feature tags. To use them, **you need to turn off calt** and enable the corresponded feature."_ 

Can you give some example about how to turn of "calt" and  then make custom ligation set with enables and disables ? 

```bash
[buildPlans.iosevka-custom.ligations]
inherits = "default-calt"   # Optional; inherits an existing ligation set
disables = []               # Optional; disable specific ligation groups, overrides inherited ligation set
enables  = []               # Optional; enable specific ligation groups, overrides inherited ligation set
```

**Comment by PyGamer0** [comment]
I think you set the `inherits=` to something else?

BTW [heres the list](https://github.com/be5invis/Iosevka#configuring-ligations)

**Comment by GulajavaMinistudio** [comment]
> I think you set the `inherits=` to something else?
> 
> BTW [heres how to configure them](https://github.com/be5invis/Iosevka#configuring-ligations)

Inherits to default calt or dlig ? a bit confused about this.

And what enables for ? should we input all inherits in it ?

**Comment by PyGamer0** [comment]
> Inherits to default calt or dlig ? a bit confused about this.

It defaults to calt. You can remove the entire line to set it to nothing (no ligations)

From the readme:
> `inherits`: Optional, String, defines the inherited ligation set. When absent, the ligation set will not inherit any other sets. 

Then you can pick which ligatures to enable like this:
```toml
enables=["exeq", "eqeq", "arrow"]
```

All of the possible values are [here](https://github.com/be5invis/Iosevka#configuring-ligations), you just have read carefully.

**Comment by GulajavaMinistudio** [comment]
Ok, it look clear now. So if i want to custom ligation, should add parameters like this ?

```
[buildPlans.iosevka-custom.ligations]
inherits = "default-calt"   # Optional; inherits an existing ligation set
disables = []               # Optional; disable specific ligation groups, overrides inherited ligation set
enables  = ["exeq", "eqeq", "arrow"]               # Optional; enable specific ligation groups, overrides inherited ligation set
```

**Comment by PyGamer0** [comment]
Yes.

**Comment by GulajavaMinistudio** [comment]
Thank you for help, i will close it.
