### ISSUE TITLE
Installed fonts not showing up in ubuntu terminal

### ISSUE THREAD

**Issue by kaykhancheckpoint** [be5invis/Iosevka#1225]
Hi, i generated custom fonts and followed the steps on the documentation https://hub.docker.com/r/avivace/iosevka-build and moved the generated folder over `~/.local/share/fonts/` and ran `sudo fc-cache`.

I can see the fonts in text editor app but when i go to change the font of my ubuntu terminal > preferences > profile > text > custom font, i do not see the font there.

**private-build-plans.toml**
```
[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "quasi-proportional"
serifs = "slab"
no-cv-ss = true

[buildPlans.iosevka-custom.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.iosevka-custom.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"
```

The pre generated versions you have in release that come with a .ttc format works but i can't seem to generate a .ttc file

**Comment by alexeyten** [comment]
You don’t need sudo. Just run `fc-cache -r`

Have you closed *all* terminals after installing font?

**Comment by alexeyten** [comment]
And I guess you should replace `quasi-proportional` with `term`

**Comment by kaykhancheckpoint** [comment]
@alexeyten i use to have this installed and working and recently wanted to generate a new version of this same build plan. However it seems like whenever i use `quasi-proportional` i'm not able to use it in the gnome terminal? although the font is installed and i can use it in text editor. Any ideas?

**Comment by alexeyten** [comment]
Quasi-proportional is by design not monospaced. Why would you want it in gnome terminal?
