### ISSUE TITLE
Space and tab width shrinks when selected, using the woff2 font with monaco-editor

### ISSUE THREAD

**Issue by hillin** [be5invis/Iosevka#1226]
I've tried regular, medium and bold variants, all of them have the same problem.
![iosevka](https://user-images.githubusercontent.com/13517745/135050234-66ca4138-e7d9-4069-8298-a2abeee94f25.png)

The ttf version does not have any problem.

---

* Your font version: 10.3.0
* Your font variant: Regular/Medium/Bold
* Your operating system (name and version): Windows 10, Chrome 93
* Your application using Iosevka: monaco-editor

**Comment by be5invis** [comment]
I checked the `woff2` files generated and the metrics are correct. Should be a Monaco issue.
Resolve as external.

**Comment by hillin** [comment]
Thanks, this indeed is a monaco editor issue. It's tracked here: https://github.com/microsoft/monaco-editor/issues/2689

**Comment by hillin** [comment]
You can subscribe to the [document.fonts.ready](https://developer.mozilla.org/en-US/docs/Web/API/FontFaceSet/ready) promise and call it there.
