### ISSUE TITLE
Why do font package sizes differ so drastically?

### ISSUE THREAD

**Issue by trallnag** [be5invis/Iosevka#1227]
For example:

* JetBrainsMono-2.242.zip = 4 Megabytes
* super-ttc-iosevka-10.3.0.zip = 55 Megabytes

**Comment by PyGamer0** [comment]
Maybe because Iosevka has more glyphs among other things?

**Comment by be5invis** [comment]
JetBrains Mono has **1358** glyphs.
Iosevka has **23724** glyphs. It also has more weights, more widths, and more slope grades.
Closing as by design.
