### ISSUE TITLE
Brace "{" displays abnormal in IntelliJ IDEA 

### ISSUE THREAD

**Issue by TYZRPVX** [be5invis/Iosevka#123]
Font version: 1.9.4
Font variant: Inziu
application: IntelliJ IDEA version 2016.2.5 （64 bit）
OS version Windows 10 14393
Font size 18~21

It displayed like this:
![qq 20161116180330](https://cloud.githubusercontent.com/assets/7645818/20342847/07a3ba8e-ac27-11e6-86c8-8c1ab15cff13.png)

The upper part of brace display incorrect. Is it a bug in Java's GUI components? How to deal with it?

**Comment by TYZRPVX** [comment]
Font version: 1.9.4
Font variant: Inziu
application: IntelliJ IDEA version 2016.2.5
OS version Windows 10 14393
Font size 18~21

Is it a bug in Java's GUI components? How to deal with it?

**Comment by be5invis** [comment]
Maybe you can try to build a unhinted version.
It is a known Java bug.
Closed.
