### ISSUE TITLE
U+2044 FRACTION SLASH

### ISSUE THREAD

**Issue by van-de-bugger** [be5invis/Iosevka#1230]
I accidentally found that some (not all) fonts treat U+2044 FRACTION SLASH specially, see the samples below. 

The samples render the following text:

    123456789012345
    123/567 9/x y/5
    123456789012345

All the digits are regular digits from range U+0030...U+0039, no superscript or subscript digits are used.  The only difference is the slash character: in the text above slash is U+002F SOLIDUS (regular ASCII slash; to avoid problems with font used by the browser) while in the samples below slash is U+2044 FRACTION SLASH.

Cascadia Code:
![Cascadia Code](https://user-images.githubusercontent.com/721164/136632230-25d42fb8-48ea-4b63-9199-00d6919d62de.png)

Cascadia Mono:
![Cascadia Mono](https://user-images.githubusercontent.com/721164/136632236-fa55c8f4-afba-4491-a2c5-169e48488b5c.png)
(It looks identically to Cascadia Code.)

Fira Code:
![Fira Code](https://user-images.githubusercontent.com/721164/136632242-2869619f-57da-458c-98f0-6c2f92139129.png)
(Incorrect fractions 9/x and y/5 look bad.)

Fira Mono:
![Fira Mono](https://user-images.githubusercontent.com/721164/136632247-0265ed0b-045f-412b-9f01-8db52d9e699f.png)
(It looks like a bug: an extra space after the slash.)

IBM Plex Mono:
![IBM Plex Mono](https://user-images.githubusercontent.com/721164/136632254-6398bd4b-bb73-4334-ac43-3b34c3585698.png)

Source Code Pro:
![Source Code Pro](https://user-images.githubusercontent.com/721164/136632259-2762650e-9a56-48dc-8482-fa710d0101ff.png)
(Incorrect fractions 9/x and y/5 look bad.)

Ubuntu Mono:
![Ubuntu Mono](https://user-images.githubusercontent.com/721164/136632265-20561816-3294-4d98-a49f-36170ca5d3ae.png)
(It looks like a bug: too small 3 and 5 in the first fraction.)

Following fonts do not treat fraction slash specially:

Cousine:
![Cousine](https://user-images.githubusercontent.com/721164/136632272-665afca5-9f75-4991-b4ef-b3e5d9b121fb.png)

DejaVu Sans Mono:
![DejaVu Sans Mono](https://user-images.githubusercontent.com/721164/136632278-d1f10639-04f7-47a6-a190-fa55875ff1b7.png)

Droid Sans Mono:
![Droid Sans Mono](https://user-images.githubusercontent.com/721164/136632282-291657a3-b8d1-46e3-851b-74e1e231ad54.png)

Iosevka:
![Iosevka](https://user-images.githubusercontent.com/721164/136632289-ea76c2f3-2063-42d7-90ea-e53b80d1cb6c.png)

I think it is completely ok to render fraction slash as an ordinary slash, so it is not a real request, the ticket is just for your information.

**Comment by be5invis** [comment]
It looks like that you turned on `frac` feature?

**Comment by be5invis** [comment]
Resolve as fixed.
I added support for `frac` that you _need to manually enable this OT feature_, but when it is on it will look like this:

![image](https://user-images.githubusercontent.com/240091/136678469-32b5619d-fb7e-4327-bdb5-5bb1a96c3c2f.png)

**Comment by van-de-bugger** [comment]
What the difference between SOLIDUS and FRACTION SLASH then? Other fonts mentioned above do **not** convert `1/3` into a fraction `¹/₃` if numbers are separated by SOLIDUS. Conversion works only for FRACTION SLASH.
