### ISSUE TITLE
README.md: What is WWID and NWID OpenType features?

### ISSUE THREAD

**Issue by van-de-bugger** [be5invis/Iosevka#1234]
`README.md`:

> `fontconfig-mono`: Apply `term` spacing changes and <...> The changes include:
> <...>
> *   Remove `NWID` and `WWID` OpenType feature.

"Remove `NWID` and `WWID` OpenType feature" — this is too cryptic for ordinal desktop user. What does it mean? 

I googled "NWID OpenType feature", but all the results are about Iosevka. I googled "NWID OpenType feature -iosevka" to exclude Iosevka, and Google said "No results found". Googling for `WWID` gives exactly the same results: either Iosevka pages or nothing.

Could you please say few words (I actually mean add few words to `README.md`) what does it mean for font users?

**Comment by be5invis** [comment]
They are private features -- which turn certain symbols wide or narrow. No applications are using them.
I will remove this in docs.
