### ISSUE TITLE
OS X refuses to install Iosevka

### ISSUE THREAD

**Issue by r24y** [be5invis/Iosevka#124]
* Font version: 1.9.5, downloaded directly from "Releases" page
* Font variant: All variants in `01.iosevka-1.9.5.zip`
* Operating system: OS X 10.11.6

---

OS X gives a pretty grave-sounding warning when installing via FontBook:

![screen shot 2016-11-16 at 11 40 05 am](https://cloud.githubusercontent.com/assets/8356669/20356221/d98ea88c-abf1-11e6-93d1-dd82491aec10.png)

![screen shot 2016-11-16 at 11 42 07 am](https://cloud.githubusercontent.com/assets/8356669/20356191/bef1998a-abf1-11e6-8ff0-9432cc7607e3.png)

**Comment by be5invis** [comment]
What is the “serious error”?

**Comment by be5invis** [comment]
cc. @clerkma

**Comment by be5invis** [comment]
@r24y Are there any log? detailed info"?

**Comment by lychees** [comment]
Look good for me, I can installed on OX X.
What is your log and OX version?

**Comment by r24y** [comment]
I'm not sure; where might I find relevant logs for this? This attempt was with the ZIP file downloaded from the "Releases" page, not built locally, so there are no build logs. Clicking around the warning dialog yielded no new info.

I'm on OS X 10.11.6 as mentioned in original issue.

**Comment by be5invis** [comment]
@r24y 
Are you overriding your existing font, or performing clean install?
What's the hash of the ttfs?
I've asked three of my friends and they do not have any problem when installing it.

**Comment by clerkma** [comment]
**Duplicate fonts**. (macOS Sierra Version 10.12.1)
<img width="1680" alt="screen shot 2016-11-22 at 2 32 52 am" src="https://cloud.githubusercontent.com/assets/8791213/20495572/9a5a4e72-b05c-11e6-9720-1fddf08819ef.png">

**Comment by r24y** [comment]
@be5invis This is a clean install. In case you want to replicate my commands on a Linux system, use `sha1sum` instead of `openssl sha1`.

```bash
$ openssl sha1 01.iosevka-1.9.5.zip
SHA1(01.iosevka-1.9.5.zip)= 0667124762cbd761ca666f5acbc83db8a5bc359c

$ unzip 01.iosevka-1.9.5.zip
# ... skipped output of `unzip` ...

$ find . -name 'iosevka*' | xargs openssl sha1
SHA1(./iosevka-bold.ttf)= 719e7fbfbb483bc141d6d828ec5ef9f1d627883c
SHA1(./iosevka-bolditalic.ttf)= 4846de58f8893ab1a8d1a3a346e6f5880041cf0d
SHA1(./iosevka-boldoblique.ttf)= 0ba5177b7aff6c6cc1f1f3549d2694e8cde7ce5a
SHA1(./iosevka-extralight.ttf)= c5de78e675ba41b364331052b91b1bf1fbd2a1c3
SHA1(./iosevka-extralightitalic.ttf)= 5e1b08233b5cdccc875f993426229f5d5326f6a9
SHA1(./iosevka-extralightoblique.ttf)= 937cde7c0d60a1bc214a27248766e04cbc92c1ee
SHA1(./iosevka-heavy.ttf)= 45002aa1cd25748045a81abbd50df0b6ab276cbb
SHA1(./iosevka-heavyitalic.ttf)= f386f01eded93c7764aeae9def497ef6f586f9f8
SHA1(./iosevka-heavyoblique.ttf)= 54a95c5b7f95150539e15c71cd76d586dd90a4f6
SHA1(./iosevka-italic.ttf)= ec08dfdbf7a1a9b1e0925ab6a9aa4e65d42b587d
SHA1(./iosevka-light.ttf)= 6b8b079d0a16cb9b108010e1aa33118aaa788a2c
SHA1(./iosevka-lightitalic.ttf)= 421649491de50d11a21d2dad32e5d42df3a4f754
SHA1(./iosevka-lightoblique.ttf)= f020bc7956dfdc4b7b16a690bbfbd7e1c6c2cbbd
SHA1(./iosevka-medium.ttf)= 1ba6b66fbc2d648827369768064b34a1f6d397ed
SHA1(./iosevka-mediumitalic.ttf)= c3068f86d9768a116c21520c2553b389d352bf83
SHA1(./iosevka-mediumoblique.ttf)= d1b7defbe5b253abb3c3055ce95287eb5774d019
SHA1(./iosevka-oblique.ttf)= ab42899347c2397d413fa8acd64893280c1b5df3
SHA1(./iosevka-regular.ttf)= 06e3a4196dd757309fe411b4acf4205b7948d445
SHA1(./iosevka-thin.ttf)= 22671b2f798287e165a2725e788a2e57f8f016cd
SHA1(./iosevka-thinitalic.ttf)= ecacb7c51c4aac4a5010de0a2545f1741ccdaeb3
SHA1(./iosevka-thinoblique.ttf)= ccbbe5d7843fd03a8b1234a7a55d9731f48a70d3
```

@be5invis thanks a ton for your help by the way!

**Comment by be5invis** [comment]
@r24y The file is correct, but I cannot reproduce your problem.
Do you have ANY detailed log about what's wrong in these files? What is that “serious error”?

**Comment by r24y** [comment]
@be5invis I really have no clue. Everything I know about this is now in this thread. I tried clicking around the dialog, clicking around FontBook... no new info. I'll keep digging, though, and post here if I find anything new.

**Comment by be5invis** [comment]
@r24y

**Comment by be5invis** [comment]
@r24y can you install this?

http://7xpe0v.com1.z0.glb.clouddn.com/iosevka-regular.ttf

**Comment by r24y** [comment]
@be5invis I tried installing from your link, but OS X gave the same warning.

Despite the warnings, though, this time I continued installation regardless (even though OS X warned it would cause a system crash). It seems to be working fine in my editor. I'll still continue to research this, though, because I wouldn't want someone else to be turned off of this neat font because of an erroneous OS X error message. I'm guessing that perhaps there's a bug in FontBook, or maybe just the FontBook installation on my laptop.

**Comment by be5invis** [comment]
@r24y Looks like so.
@lychees @clerkma can successfully install it, therefore I think it is a specific problem on your system.
If you have any clue, please reply.
Closed.

**Comment by evmin** [comment]
I understand the issue is closed - but I got a similar problem

**Comment by jlmakes** [comment]
I created a custom build, and also had the "Duplicate Fonts" warning.

However, it was because I had a previously installed version of Iosevka in my trash can; once I emptied the trash, the warning went away.

**Comment by mikelui** [comment]
Happens when installing with homebrew still :)
