### ISSUE TITLE
The s neck gets thickened whenever I try to reduce Iosevka's sidebearings

### ISSUE THREAD

**Issue by cssobral2013** [be5invis/Iosevka#1241]
When compiling Iosevka with reduced sidebearings, the s neck gets unusually thickened.

![Sem título](https://user-images.githubusercontent.com/19995437/139516707-81b188b1-7772-40fa-a9c9-2e24dbd77ae1.png)

---

* Your font version: All versions from 7.0.0 onwards display this issue (perhaps earlier versions too)
* Your font variant: Stock (compiled from source)
* Your operating system (name and version): Windows 11 (but every OS display this issue, as this is glyph-level)
* Your application using Iosevka: All apps display this issue (it's glyph-level)

If you have problem when building Iosevka, please provide these information:

* Your Node.js version:
* Your _otfcc_ version:
* Your `params/parameters.toml`, paste if modified:
  ```
 parameters.toml is unchanged
  ```
* Your `build-plans.toml`, paste if modified:
  ```
  build-plans.toml is unchanged
  ```
* Your `private-build-plans.toml`, if present:
  ```
It's attached [here](https://github.com/be5invis/Iosevka/files/7445621/private-build-plans.toml.txt), 
added extension .txt to post. 
  ```
* The detailed error log:
  ```
It compiles succesfully, as this only appears after this glyph is compiled.
  ```

**Comment by be5invis** [comment]
Well, the neck of `s` is hyper tricky to deal with: is is sensitive to the parameters, so non-standard parameters may cause broken geometry...
I added metric override support for `essRatio`, which controls the ratio of the neck against normal stroke width. This should be able to help you.

**Comment by cssobral2013** [comment]
@be5invis - Thank you! It worked!
