### ISSUE TITLE
`README.md` is too large

### ISSUE THREAD

**Issue by stone-zeng** [be5invis/Iosevka#1242]
Describe your problem here. Provide pictures and files if necessary.

---

The `README.md` file is too large and it's a little bit slow to load this page. Please consider to move some detail (stylistic sets, character variants etc) to separate doc files. Thank you!

---

* Your font version: (Release or git, version)
* Your font variant:
* Your operating system (name and version):
* Your application using Iosevka:

**Comment by be5invis** [comment]
Done. Now, these lists are located in separate files.
