### ISSUE TITLE
The 'compact' variant of `r` is too light

### ISSUE THREAD

**Issue by efermi** [be5invis/Iosevka#1243]
The 'compact' variant of `r` stands out in text by being too light. The terminal should be heavier to compensate high contrast of the stroke or the stroke itself should be more regular in width.

* Your font version: 10.3.4
* Your font variant: iosevka-fixed-ss06-extended.ttf
* Your operating system (name and version): Manjaro Linux
* Your application using Iosevka: hb-view

Compare to fonts with similar design:
| Font | Example |
| --- | --- |
| Iosevka | ![r-iosevka](https://user-images.githubusercontent.com/3966555/139773744-2249413a-21ca-486f-a4d6-2fb254b260de.png) |
| Roboto Mono | ![r-roboto](https://user-images.githubusercontent.com/3966555/139773742-7f095b83-dfbd-4f8e-a4d0-c25f14339fad.png) |
| Liberation Mono | ![r-liberation](https://user-images.githubusercontent.com/3966555/139773743-319c7fd4-d007-4980-a1ee-962c7bb24d96.png) |

**Comment by be5invis** [comment]
I think it is a design choice: the compact `r` reused the left part of normal `r`, so at the conjunction, it will look thinner. This is somehow necessary to balance overall darkness for bold weights.

**Comment by efermi** [comment]
Try to use it yourself, in a text editor for example, and compare with similar fonts. It is more noticeable in inverse, even in bold it looks anemic to me:
![iosevka-r](https://user-images.githubusercontent.com/3966555/139786912-dac3fbf9-1e78-4782-9c48-733a6120087c.png)
![iosevka-b](https://user-images.githubusercontent.com/3966555/139786913-53a2406f-0af0-4612-bcd0-300bc6db968b.png)

**Comment by be5invis** [comment]
Slightly increased thickness. Resolve as fixed.

**Comment by efermi** [comment]
It does look better now, thank you!
