### ISSUE TITLE
Section glyph (U+ ) is defective whenever I try to reduce Iosevka's sidebearings

### ISSUE THREAD

**Issue by cssobral2013** [be5invis/Iosevka#1244]
As per title. (Note: This issue is displayed only in Thin/ExtraLight/Light (and their italics), and Medium to Black (italics only).
Edit: Screenshots below. The first is Bold Italic, and the other is Thin.
![Captura de tela em 2021-11-04 17-28-43](https://user-images.githubusercontent.com/19995437/140415241-6a1d2067-e6e8-4fe8-9f30-68f1e2d1fd66.png)
![Captura de tela em 2021-11-04 17-27-51](https://user-images.githubusercontent.com/19995437/140415245-73d10044-ef38-4287-aabd-9757d996481b.png)

---

* Your font version: 10.3.4 (latest, as of writing)

* Your font variant: Compiled from source
* Your operating system (name and version): Windows 11
* Your application using Iosevka: None (as this issue appears when compiling) 

If you have problem when building Iosevka, please provide these information:

* Your Node.js version: 17.0.1 (latest, as of writing)
* Your `params/parameters.toml`, paste if modified:
  ```
  This appears whenever I try to edit sb is shape-width.toml:
[shapeWeight]
canonicalStrokeWidthMin = 18  # sync with 100 entry below
canonicalStrokeWidthMax = 108 # sync with 900 entry below

[shapeWeight.blend.400]
stroke = 70        # Primary stroke width
contrast = 1.11    # Stroke width contrast
*sb* = 44            # Primary sidebearings
essRatio = 0.98    # Proportion of widen of center of "S"
dotSize = 125      # Size of dots
periodSize = 140   # Size of period

jut = 85           # Length of slab serif
vjut = 145         # Length of vertical slab serif
longjut = 175      # Length of long serifs, like that in `i`.

smooth = 195       # Vertical arc size in capital letters.
smallsmooth = 200  # Vertical arc size in lowercase letters.

rbalance = 60
rbalance2 = 15
tbalance = 50
tbalance2 = 30
jbalance = 63
fbalance = 6
onebalance = 30

hook  = 165        # Hook depth in most letters.
ahook = 130
shook = 120
jhook = 135
fhook = 120
hookx = 170
rhook = 110

cthin = 0.75
cthinb = 0.5
vtipfine = 0.8
vtipfineSlab = 0.9


[shapeWeight.blend.100]
stroke = 18
contrast = 1.08
*sb* = 50
essRatio = 1.04
dotSize = 53
periodSize = 55

jut = 70
vjut = 145
smooth = 195
rbalance = 60
rbalance2 = 15
cthin = 0.9
cthinb = 0.9
vtipfine = 1
vtipfineSlab = 1


[shapeWeight.blend.200]
vtipfine = 1
vtipfineSlab = 1

[shapeWeight.blend.300]
vtipfine = 0.9
vtipfineSlab = 0.9

[shapeWeight.blend.500]
rbalance = 60
rbalance2 = 15

[shapeWeight.blend.600]
# Interpolated

[shapeWeight.blend.700]
stroke = 96

[shapeWeight.blend.800]
# Interpolated

[shapeWeight.blend.900]
stroke = 114
contrast = 1.20
*sb* = 36
essRatio = 0.94
dotSize = 180
periodSize = 200

jut = 95
vjut = 200
smooth = 215
rbalance = 50
rbalance2 = 25
cthin = 0.75
cthinb = 0.5
  ```
* Your `build-plans.toml`, paste if modified:
  ```
 This is not related to build-plans.toml
  ```
* Your `private-build-plans.toml`, if present:
  ``` 
This is not related to private-build-plans.toml

  ```
* The detailed error log:
  ```
As per title, this issue is displayed by reducing sb in shape-width.toml, and compiling.
  ```

**Comment by be5invis** [comment]
Are you editing `params/shape-weight.toml`? Changing these files, or using metric override, is **highly discouraged** and **may produce broken shapes** -- like the section symbol mentioned here.

**Comment by cssobral2013** [comment]
@be5invis - However, I need to reduce Iosevka sidebearings, as I feel Iosevka Aile is too widely spaced, and I need Iosevka to use in UI (in which is essential to use horizontal space as maximum as possible).

**Comment by cssobral2013** [comment]
@be5invis - However, because you are kinda not responsible to these acts, because I modified metrics directly, I'll close this by myself.
