### ISSUE TITLE
README.md: spacing="fontconfig-mono"

### ISSUE THREAD

**Issue by van-de-bugger** [be5invis/Iosevka#1245]
That's not a feature request but request for clarification.

README.md:

>   *   `spacing`: Optional, String, denotes the spacing of the custom variant. Valid values include: 
>       *   `quasi-proportional`: The font will become quasi-proportional.
>       *   `term`: Make the symbols' width suitable for terminal emulators. Arrows and geometric symbols will become narrower.
>       *   `fontconfig-mono`: Apply `term` spacing changes and further apply changes to be compatible with FontConfig's Mono spacing, which recognizes a font as monospace if and only if its every non-combining characters having the same width. The changes include:
>           *   Completely remove wide glyphs. All non-combining glyphs will be exactly the same width.
>               *   As a consequence, the following characters will be **removed**:
>                   *   `U+27F5` LONG LEFTWARDS ARROW
>                   *   `U+27F6` LONG RIGHTWARDS ARROW
>       * `fixed`: Apply `fontconfig-mono` changes and further remove ligations.

Issues:

1.  Spacing `normal` is not mentioned.

2.  Iosevka releases include ttf files for `quasi-proportional` (Iosevka Aile and Iosevka Etoile), `normal` (Iosevka and Iosevka Slab), `term` (Iosevka Term and Iosevka Term Slab), and `fixed` (Iosevka Fixed and Iosevka Fixed Slab). Looks like there are no released ttf for `fontconfig-mono`. I am just wondering why?

3.  It looks like `U+27F5` LONG LEFTWARDS ARROW and `U+27F6` LONG RIGHTWARDS ARROW are **not** actually removed. Glyphs for these characters are present in Iosevka Fixed (ttf-iosevka-fixed-10.3.4.zip) which is expected to be `fontconfig-mono` + removed ligations. These glyphs are not full-width (my eye does not see any difference between `U+27F5` LONG LEFTWARDS ARROW and `U+2190` LEFTWARDS ARROW as well as between `U+27F6` LONG RIGHTWARDS ARROW and `U+2192` RIGHTWARDS ARROW in this font), but they a definitely present.

4. Since LONG LEFTWARDS ARROW and LONG RIGHTWARDS ARROW are not actually removed, what is the difference between `term` and `fontconfig-mono` then? Does `term` include any full-width glyphs?

**Comment by be5invis** [comment]
Q1, Q3, and Q4 are fixed in the latest `dev` with an updated long-arrow logic. Now it will become always wide and will be removed in `fontconfig-mono`/`fixed` spacing.

For Q2, initially, we only have `term` and `fixed`. `fontconfig-mono` is added later as a level between them. Considering the building cost (it will produce over 20 additional packages) it is not provided as prebuilt.
