### ISSUE TITLE
Swung dash (u+2053) should be a wide character

### ISSUE THREAD

**Issue by bkhl** [be5invis/Iosevka#1246]
When using Iosevka built with quasi-proportional spacing, the character `2053` (swung dash) appears the same as a tilde. I checked in a bunch of other fonts, and it seems this character is as a rule the same width (or very close) to an m-dash.

Screenshot from Libreoffice Writer illustrating the issue:

![image](https://user-images.githubusercontent.com/34634/140560709-fdee9600-84e6-40d0-b09c-56b11898ca67.png)

I think that in line with this, the character should be rendered as wide

The reason I noticed this is that I use this character interchangeably with an em-dash in an Emacs plugin, to indicate one of two modes.

---

* Your font version: 10.3.4
* Your font variant: custom build of slab, with `spacing` set to `quasi-proportional`
* Your operating system (name and version): Fedora 35
* Your application using Iosevka: Multiple (but screenshot from Libreoffice Writer)

**Comment by van-de-bugger** [comment]
@bkhl: If a glyph is missed in the font, many applications use glyps from another font. I believe LibreOffice Writer does that. Look at you picture: swung dash in Cantarell, Liberation Serif, Crimson Pro and DejaVu Sans look exactly the same (while tilde differs). It is highly likely these fonts does not include glyph for swung dash at all.

You should make sure the glyph is actually present in the referenced font. For example, use `fontimage` program:

    $ fontimage --pixelsize 120 --text "Sample text" --o font-name.png full-path-to-the-font-file.ttf

**Comment by be5invis** [comment]
It now follows the metric of em-dash.
