### ISSUE TITLE
Inziu IosevkaCC SC里韩语没有定义

### ISSUE THREAD

**Issue by yutuo** [be5invis/Iosevka#125]
* Your font version: 1.9.4 Release 
* Your font variant: Inziu IosevkaCC SC
* Your operating system (name and version): Windows7
* Your application using Iosevka: Eclipse

---

Describe your problem here. Provide pictures and files if necessary.

在使用Inziu IosevkaCC时，发现韩语没有定义，能不能把Source Han Sans里的韩语也加上

**Comment by be5invis** [comment]
Implementing Hangul is much more complex than CJ. For example, there is a Jamo-based Hangul encoding and SHS support that, but it is extremely complex.
It is not planned either.
Sorry for that.
