### ISSUE TITLE
The glyph section is defective in some styles whenever shape is greater than 600

### ISSUE THREAD

**Issue by cssobral2013** [be5invis/Iosevka#1252]
As per title, the glyph section is defective when compiling with shape > 600.
---

* Your font version: Any
* Your font variant: Any
* Your operating system (name and version): Any
* Your application using Iosevka: Any

If you have problem when building Iosevka, please provide these information:

  ```
not modified

 shape = any number greater than 600 (max. 664)
  ```
* Your `build-plans.toml`, paste if modified:
  ```
not modified
  ```
* Your `private-build-plans.toml`, if present:
  ```
  not modified
  ```

**Comment by be5invis** [comment]
What is broken? Cannot see details

**Comment by cssobral2013** [comment]
@be5invis - Screenshots in OP.

**Comment by cssobral2013** [comment]
@be5invis - Screenshots below.

![Sem título](https://user-images.githubusercontent.com/19995437/142786990-ab330724-06f8-4ae5-b80b-aa4e59d77b2a.png)

![Sem título1](https://user-images.githubusercontent.com/19995437/142787071-0fb76235-e998-4bed-990d-93ae77ecfb35.png)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/142789081-b2cf3e98-20df-4c15-826c-b7d88e28eb34.png)
![image](https://user-images.githubusercontent.com/240091/142789115-b0600090-fbe4-46c5-a4d2-2b78c42176d1.png)
