### ISSUE TITLE
Lower horizontal bar for lowercase latin f

### ISSUE THREAD

**Issue by pv4** [be5invis/Iosevka#1254]
Hello!

Could you please consider lowering horizontal bar of lowercase latin `f` (for NON `crossbar-at-x-height` variant)? The current implementation differs too little from `crossbar-at-x-height` variant, and when letters `t`/`i`/`f` are met together (especially tailed variants of `f`) the current `f` might look like a bug, as if `f` bar is lowered unintentionally compared to `t`/`i` bars.

I tried decreasing `fBarPosToXH` to 0.82 and the result was ugly. But 0.86 looks much better than the current 0.91. If possible, please consider adjusting (decreasing) `fBarPosToXH` (to you taste, not necessary to 0.86).

Not sure whether a new variant matrix should be created or just the current variants can be fixed instead.

![image](https://user-images.githubusercontent.com/2502094/143985659-7d7a2749-8d56-4781-b14c-6bc167391e20.png)

**Comment by be5invis** [comment]
`0.875` looks nice to me.

**Comment by pv4** [comment]
> `0.875` looks nice to me.

I agree. Thanks!
