### ISSUE TITLE
Less narrow "compact" quasi-proportional lowercase r

### ISSUE THREAD

**Issue by rben01** [be5invis/Iosevka#1255]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

Would it be possible to create a less narrow version of the "compact" style lowercase r in quasi proportional mode? I like the shape of the compact r in the normal (mono) version of the font:
<img width="52" alt="image" src="https://user-images.githubusercontent.com/766670/144453453-f2384acc-3fe7-4d5b-8224-5d8f9e55b1a8.png">

However, in quasi-proportional mode, the lowercase is very narrow — too narrow, IMO.
<img width="50" alt="image" src="https://user-images.githubusercontent.com/766670/144453565-6ad8fc02-2282-4847-85c1-e10b3fec48cb.png">

Would it be possible to create a slightly wider version of the lowercase r with the same basic shape as the mono version?

**Comment by be5invis** [comment]
I think `compact` should be, well, compact. We may be able to introduce some variants like "hookless" but it might confuse people at monospace variants since under such variants they look identical to "compact".

**Comment by rben01** [comment]
> I think `compact` should be, well, compact. We may be able to introduce some variants like "hookless" but it might confuse people at monospace variants since under such variants they look identical to "compact".

I agree a "hookless" r would be ideal.

This wouldn't be the only place where two variants look identical; it took me a while to see the difference between lowercase `l`'s `tailed` and `flat-tailed` variants. They're almost identical in the normal style, but once italicized you can see that the `tailed` variant's tail curves up, whereas the `flat-tailed` variant's remains flat. All this to say, I think it's ok if two variants look the same. What's important is leaving a note for the user to explain under what scenarios they appear different.
