### ISSUE TITLE
How to Build Normal Width Font Only?

### ISSUE THREAD

**Issue by Floaterest** [be5invis/Iosevka#1256]
In [Iosevka Customizer](https://typeof.net/Iosevka/customizer), you can build "standard (normal + extended)" width fonts and "extended as normal" with fonts. From the generated build plan, I see that an extended font has `shape = 600` and `menu = 5`. Therefore, I'd like to know what's the `shape` and `menu` for a normal width font (because I want to build the font with normal width only)?

**Comment by be5invis** [comment]
`shape = 500` and `menu = 5`

**Comment by Floaterest** [comment]
Thanks!
