### ISSUE TITLE
capital-n slab does not have bottom right serif

### ISSUE THREAD

**Issue by pv4** [be5invis/Iosevka#1258]
I suppose slab variants of capital-n (at least, the upper two) should have the bottom right serif.

![image](https://user-images.githubusercontent.com/2502094/145302411-a21f92c2-c08f-4b0a-ba95-6fd42faf7b10.png)

**Comment by be5invis** [comment]
Well `N` in serif fonts usually doesn't have bottom-right serif.
![image](https://user-images.githubusercontent.com/240091/145321745-187d7f93-fff0-4af2-9ada-cdc32beb7f83.png)
![image](https://user-images.githubusercontent.com/240091/145321763-1cbc1082-9af1-4a9f-ad20-c7b55d3ace08.png)

**Comment by pv4** [comment]
Wow, I can't believe I've never noticed that before!

Though there are fonts that have the serif:
https://www.myfonts.com/fonts/itc/benguiat/
https://www.myfonts.com/fonts/fype-co/king-and-queen/
https://www.myfonts.com/fonts/virtuecreative/hudson-ny/
https://www.myfonts.com/fonts/peach-creme/abramo/

But generally you're right since 99% of serifed fonts don't have the serif. It's a discovery for me (not a native English speaking one) since I always considered `N` to be similar to `H` which has all the serifs.

Then I'll leave it up to you to decide whether it's worth to create a set of `N` variants with the bottom right serif or not. I mean, feel free to just close the issue with no action if you want.

Thanks for the explanation.

**Comment by pv4** [comment]
I think there is no reason to keep this open.
