### ISSUE TITLE
Building Inziu by myself

### ISSUE THREAD

**Issue by leiserfg** [be5invis/Iosevka#126]
How can I build my own Inziu?, where is the building script?

**Comment by be5invis** [comment]
There is one on my PC, but it is too large to upload to GitHub.

**Comment by leiserfg** [comment]
I just wanna Inziu with z shaped iosekva.

**Comment by be5invis** [comment]
You can enable alternative shapes with `ss01`-`ss09` styles.
Building Inziu will create about 8GB temporary data and take about one day on ordinary computer... Are you sure?

**Comment by rixtox** [comment]
I'm also trying to build Inziu with an Ioveska variant (ss04) for Sublime Text since it doesn't support OpenType feature tags.

A build script would be appreciated though.
