### ISSUE TITLE
The tailed 'l' is defective in ExtraBold/Heavy (Italics only)

### ISSUE THREAD

**Issue by cssobral2013** [be5invis/Iosevka#1260]
![Sem título](https://user-images.githubusercontent.com/19995437/145333115-13dc710b-14f7-4663-ae36-3060ad9d60d8.png)

---

* Your font version: (Release or git, version)
* Your font variant:
* Your operating system (name and version):
* Your application using Iosevka: 

If you have problem when building Iosevka, please provide these information:

* Your Node.js version:
* Your _otfcc_ version:
* Your `params/parameters.toml`, paste if modified:
  ```
  Intact
  ```
* Your `build-plans.toml`, paste if modified:
  ```
  Intact
  ```
* Your `private-build-plans.toml`, if present:
  ```
 Build as width > 600, and as quasi-proportional sans (like Iosevka Aile)
  ```
* The detailed error log:
  ```
  paste here
  ```

**Comment by be5invis** [comment]
I tried width = 650 and `i`/`l` look normal
![image](https://user-images.githubusercontent.com/240091/145334111-cbdc9a75-1076-406f-8b35-36f4df7491a0.png)

**Comment by cssobral2013** [comment]
@be5invis - This is only displayed in quasi-proportional sans.

Em qui., 9 de dez. de 2021 1:24 AM, Belleve ***@***.***>
escreveu:

**Comment by cssobral2013** [comment]
@be5invis - This is only displayed in serifless tailed variants of i/l.

Em qui., 9 de dez. de 2021 11:15 AM, Cristiano Sobral <
***@***.***> escreveu:
