### ISSUE TITLE
[Question] Has the typeface become taller?

### ISSUE THREAD

**Issue by mustaqimM** [be5invis/Iosevka#1261]
I compared 3.6.1 to the latest version: 11.2.0. It seems like the height in both directions gained a bit. (I don't have the build plan for 3.6.1, but I never did touch anything other than change some of the variants)

Please see below:

https://user-images.githubusercontent.com/24436622/145395212-845d50fb-b19e-495b-9a4d-b579ad44c15c.mp4

This is just for curiosity's sake, please close if you wish.

**Comment by be5invis** [comment]
Maybe. 3.6.1 is _a long time ago_. Though I never changed line height.

**Comment by pv4** [comment]
As always, this can be hinting issue. Try the same comparison with hinting disabled.
