### ISSUE TITLE
Variant Request: Capital Q with Broken Ring

### ISSUE THREAD

**Issue by AndydeCleyre** [be5invis/Iosevka#1264]
- [ ] The requested variant shape does not go too far away from Iosevka's design.
- [ ] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [ ] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

The `Q` uses the common `O` shape, so could use a little extra differentiation for clarity.

I suggest to create variants with a small slice taken out of the major ring, parallel to and just next to the crossing stick, one on side or the other. This might make sense for the first 5 existing variants, and probably not for 6, 7, and 8. 

Here's a mockup for this applied to the `curly-tailed` (`cv16=1`) variant:

![capital-q](https://user-images.githubusercontent.com/1787385/146485449-b4f7a361-b116-4438-815a-9baf05ff2142.png)

But the request is just broadly to break the ring somewhere on a `Q` variant to distinguish it further from the `O`.

Here are the only monospaced precedents I could find:

![image](https://user-images.githubusercontent.com/1787385/146483680-c75c2a8b-23b7-4e4c-89cf-d77820eb04a7.png)

![image](https://user-images.githubusercontent.com/1787385/146484658-ef8d9757-9648-4116-8a84-2ff212f67f75.png)

![image](https://user-images.githubusercontent.com/1787385/146485054-ffd84541-1937-4b39-b714-2affe7538444.png)

**Comment by be5invis** [comment]
It needs to add 3 variants for each crossing tail style:
 * Breaks at left
 * Breaks at right
 * Breaks at both sides

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/146492754-52d1279d-6a47-490b-8d15-cfaf14123e08.png)
May become problematic for bolds

**Comment by AndydeCleyre** [comment]
I found some elephants and things but I'm not sure if they're any use:
![capital-q-2](https://user-images.githubusercontent.com/1787385/146499621-c2d52980-a748-4124-85ce-b58c080ca4c8.png)

**Comment by pv4** [comment]
Another possible solution is to move the tail left or right to have enough space.

Though I personally like the current non-broken-ring variant more and I will continue to use it.

![image](https://user-images.githubusercontent.com/2502094/146506149-16e2bb65-986d-44c6-8e56-cc9bcd6c0a3c.png)

**Comment by pv4** [comment]
Or even such one.

![image](https://user-images.githubusercontent.com/2502094/146506806-ca46631a-7daa-4304-9010-bd58daa1954e.png)

**Comment by pv4** [comment]
My variants above are just ideas. Don't blindly use them (if you don't like them).

I hope they will just help you to find the best possible option.

**Comment by be5invis** [comment]
Well, open Q reminds me of some serif fonts, so I made this:
![image](https://user-images.githubusercontent.com/240091/146542458-ce3b9146-93b6-4c17-b13e-73a0c64a75a3.png)

**Comment by wimstefan** [comment]
Absolutely beautiful!

**Comment by ViniciusGiroto** [comment]
Could that tail also be added to Ç? It would look beautiful.

**Comment by be5invis** [comment]
Resolve as fixed
