### ISSUE TITLE
option to remove the ttf declarations from webfont css files

### ISSUE THREAD

**Issue by teauxfu** [be5invis/Iosevka#1266]
I like having the option of serving font files statically, but by personal preference I don't include .ttf files in my repos/builds.

When using a static site generator like Gatsby or Next, I would run into this issue where the file loaders would complain about not having the .ttf files around, since the provided css references them.

```css
//iosevka-aile.css
@font-face {
	font-family: 'Iosevka Aile Web';
	font-display: swap;
	font-weight: 100;
	font-stretch: normal;
	font-style: normal;
	src: url('woff2/iosevka-aile-thin.woff2') format('woff2'), url('ttf/iosevka-aile-thin.ttf') format('truetype');
}
```

If using for example Next you'd hit
```
error - ./src/styles/global.scss:59:0
Module not found: Can't resolve '../../public/fonts/iosevka-aile/ttf/iosevka-aile-thin.ttf'

Import trace for requested module:
./src/styles/global.scss
./src/pages/_app.js

https://nextjs.org/docs/messages/module-not-found
```

Which is far too many lines to manually edit, especially if you want to try out multiple Iosevka variants (and also insist on deleting the .ttf files like me).

So I patched together this little Node script to do that as a learning exercise. This might be fragile, but it does work 😝

If there is a better way of going about this I'd be glad to hear it! Using Node seemed like a reasonable choice considering the environment, but it could probably be more easily done in Python or similar.  Posting here in case it would be useful for someone else. 

```js
// https://gist.github.com/teauxfu/7171b1d5e8fb20df74295a5a384a4e85
// this script trims the ttf declarations from default Iosevka webfont css files

// default:
// src: url('woff2/iosevka-thin.woff2') format('woff2'), url('ttf/iosevka-thin.ttf') format('truetype');
// desired:
// src: url('woff2/iosevka-thin.woff2') format('woff2');

// css isn't parsed. functionality hinges on the comma.
// formatting the css to line break that src declaration would give bad results

// the script expects an absolute path, or one relative to package.json
// example usage: node trimttf.js ".\public\fonts\iosevka-curly\iosevka-curly.css"
// the file is modified in place !

// todo: better logging / handling

const fs = require("fs");
const readline = require("readline");
const path = require("path");

const args = process.argv.slice(2);
const target = args[0];
const encoding = args[1] ? args[1] : "utf-8";

main(target, encoding);

async function main(target, encoding) {
  if (fs.existsSync(target) && path.extname(target) == ".css") {
    console.log(`Trimming ttf declarations from ${target}`);
    const css = await trim(target);
    fs.writeFile(target, css, encoding, (err) => {
      if (err) throw err;
      console.log(`Finished trimming ${target}.`);
    });
  } else {
    throw Error(
      `Expected one absolute path to a default Iosevka css file. got ${target}`
    );
  }
}

function trim(target) {
  return new Promise((resolve, reject) => {
    const rd = readline.createInterface({
      input: fs.createReadStream(target),
      output: process.stdout,
      terminal: false,
    });
    // just look for a comma
    // alternatively could skip regex and try splitting all lines at a comma ¯\_(ツ)_/¯
    const regex_pattern = /[,]/gm;
    let css = [];

    rd.on("line", function (line) {
      if (regex_pattern.test(line)) {
        [woff2, ttf] = line.split(",");
        console.log(`trimmed ${ttf}`);
        css.push(`\n${woff2};`);
      } else {
        css.push(`\n${line}`);
      }
    });

    rd.on("close", () => {
      resolve(css.join(""));
    });
  });
}

// thanks
// passing in args to node https://stackoverflow.com/a/5767589/13090245
// using readline https://stackoverflow.com/a/69516562/13090245
// destructuring a string https://stackoverflow.com/a/42185907/13090245
// await readline w/ promise https://stackoverflow.com/a/53981240/13090245
```

**Comment by be5invis** [comment]
Well `verdafile.js` actually has such definitions:

```js
const webfontFormats = [
	["woff2", "woff2"],
	["ttf", "TrueType"]
];
```

You can delete the `ttf` line and rebuild, and it will no longer include TTFs in web fonts.

Considering WOFF2 is now supported by all the browsers, maybe we can remove TTF in the default web font distribution?

**Comment by teauxfu** [comment]
Sounds good to me. I don't know if or why others who use the package depend on the TTF files, but it seems like functionality is already in place to build them if they are needed. I haven't yet thought of a downside to excluding them by default, and I think it would help reduce release bundle sizes. 

Thanks for the tip on using verdafile -- I had not even looked at it yet. Perhaps I could append a brief section on using that lever in the custom build doc?

---

Unrelated: is there something in there that could be used to build WOFF (not WOFF2) format?
I'm playing with a couple approaches to automate repackaging Iosevka variants for the Fontsource repo, and right now I'm using a 3rd tool to convert the TTF to WOFF, which is quick but perhaps more fragile and/or less elegant in the long run.

Thanks!

**Comment by be5invis** [comment]
@teauxfu Well there used to have WOFF, but I removed that several versions ago [since all modern browsers support WOFF2 now](https://caniuse.com/woff2).
