### ISSUE TITLE
Shorter lower case caracters for people with dyslexia

### ISSUE THREAD

**Issue by AlanCristhian** [be5invis/Iosevka#1268]
People with dyslexia have to put more effort into reading. I think that Iosevka already have most of the features of a dyslexic friendly font. The only missing feature is shorter lower case characters.

I think that could be great to have both the caracters and the configuration option for shorter lowercase characters.

You can read more about that here [https://www.dyslexiefont.com/en/dyslexiafont/](https://www.dyslexiefont.com/en/dyslexiafont/). There also you can see how a dyslexic friendly font looks.

**Comment by be5invis** [comment]
You can try using metric-override to reduce x-height, but beware: **Iosevka is NOT a font designed for dyslexia readers**. Overriding metrics will very likely create broken geometry.

**Comment by AlanCristhian** [comment]
Ok. I will experiment with that.
