### ISSUE TITLE
Failed building webfonts

### ISSUE THREAD

**Issue by visvadw** [be5invis/Iosevka#127]
Hello,

I am trying to build the webfont versions of this beautiful font.
Following the instructions, I started installing:
- `FontForge`
- `woff2_compress` and `woff2_decompress` tools (built from [source](https://github.com/google/woff2))
- `sfnt2woff` and `otfcc`

However, running `make webfonts` in the cloned project ends up with the following error:
```
$ make webfonts
node ./node_modules/patel/bin/patel-c --optimize --strict support/glyph.ptl -o support/glyph.js

....... (content omitted) .......

node ./node_modules/patel/bin/patel-c --optimize --strict buildglyphs.ptl -o buildglyphs.js
/Applications/Xcode.app/Contents/Developer/usr/bin/make fonts config=d-sans
    Start building font Iosevka Thin 1.9.5 (Ingrid)
    Iosevka Thin 1.9.5 (Ingrid) Successfully built.
    Writing outline as SVG -> build/.pass0-iosevka-thin.svg
    Writing metadata as JSON -> build/.pass0-iosevka-thin.fdt
make[2]: *** [build/.pass1-iosevka-thin.ttf] Error 127
make[1]: *** [fonts] Error 2
make: *** [fonts-d-sans] Error 2
$ 
```
Do you have any suggestions, please?

Thank you.

**Comment by be5invis** [comment]
Is `fontforge` accessable from the command line?

**Comment by visvadw** [comment]
Hi @be5invis,
Thanks for the feedback. `otfccbuild` is accessible as being installed in `/usr/local/bin`.
I also made `fontforge` accessible using:
```shell
$ cd /usr/local/bin
$ ln -s /Applications/FontForge.app/Contents/MacOS/FontForge fontforge
```
However, it looks like that FontForge needs X11 to be installed also.
```shell
$ make webfonts
/Applications/Xcode.app/Contents/Developer/usr/bin/make fonts config=d-sans
PKGBASE: /Applications/FontForge.app
dyld: Library not loaded: /opt/local/lib/libfontconfig.1.dylib
  Referenced from: /Applications/FontForge.app/Contents/MacOS/fc/fc-cache
  Reason: image not found
Done!

The following error occurred while opening font `build/.pass1-iosevka-thin.ttf.a.ttf':

  No such file or directory
make[2]: *** [build/.pass1-iosevka-thin.ttf] Error 1
make[1]: *** [fonts] Error 2
make: *** [fonts-d-sans] Error 2
$
```
I just installed X11 from [XQuartz](http://www.xquartz.org), I hope it won't break the system at the next logon. 😄  I'll get back with the result in a minute ...

**Comment by be5invis** [comment]
@visvadw 
Have you tried to remove the `build/` and rebuild from scratch?

**Comment by be5invis** [comment]
Maybe I should really get rid of FF.

**Comment by visvadw** [comment]
Yes, I removed the (partially resulted) `build` folder and rerun it, but the issue persisted.
I will try to build it on Linux and get back to you with a feedback
Yes, FontForge may not have a consistent behaviour the way it is built for macOS.

Anyway, I am in love with this font and I found it extremely elegant. 👍

**Comment by visvadw** [comment]
I made the building work on a Linux (Mint) system! Hooray! :smiley: 
For others like me who want to use the webfont versions of this beauty, you may include [this result](https://github.com/visvadw/design-assets/tree/master/iosevka-webfonts) to your current (1.9.6) release.
