### ISSUE TITLE
Add a new ligation set for the Dafny programming language?

### ISSUE THREAD

**Issue by cpitclaudel** [be5invis/Iosevka#1271]
Hello, and thanks for the work on Iosevka!

Would it be easy to add a new ligation set for the Dafny programming language (https://github.com/dafny-lang/dafny/)?

Here are the ligations which I think are relevant:

![image](https://user-images.githubusercontent.com/8181630/147971987-3692b0bf-4595-4d32-9055-2bc80ea1f868.png)

There are two more symbols that (I think) Iosevka does not have (`!!` which should have the exclamation points slightly closer to each other and `:|` which should center the bar like `:=` does), as well as one exception: `::` is rendered as a thick center dot in Dafny:

![image](https://user-images.githubusercontent.com/8181630/147972449-2da2d7bd-ca7b-4310-8db4-5a5b1d6b8f1d.png)

Happy to submit a patch if that's easier and if a new ligation set would be acceptable.

Thanks!

**Comment by be5invis** [comment]
> `::` is rendered as a thick center dot in Dafny
Wait what?

**Comment by cpitclaudel** [comment]
> Wait what?

That's just the convention when rendering Dafny code, both in academic papers and in the Emacs mode for it.  It's not completely unconventional, either: https://tex.stackexchange.com/questions/201539/how-to-produce-dot-between-quantifiers

**Comment by VladimirMarkelov** [comment]
Correct me if I am wrong, but I think that if a font provides a ligature, it works the same way for *everyone*. In this case, making "::" a think dot may make a lot of developers in other languages very surprised. E.g, ubiquitous C++ extensively uses "::" for namespace delimiter.

**Comment by be5invis** [comment]
I'd like to NOT add a ligature turning `::` into `·`, instead, I'd like to simply kern them together.

**Comment by be5invis** [comment]
Using fonts to do such a merge is a very, very bad idea. Actually, I do not want to do such things for the second time.
(The first time is for inequalities).

**Comment by cpitclaudel** [comment]
> Correct me if I am wrong, but I think that if a font provides a ligature, it works the same way for everyone.

I don't think that's right: for example Iosevka already has two different renderings for `<>` and for  `===`.

> I'd like to NOT add a ligature turning :: into ·, instead, I'd like to simply kern them together.

Works for me. Thanks a lot!
