### ISSUE TITLE
Different shapes for confusable letters in different scripts

### ISSUE THREAD

**Issue by JapanYoshi** [be5invis/Iosevka#1275]
**Is your feature request related to a problem? Please describe.**

I think it would be good for coders who use a different writing system in addition with English to have clearly distinguishable letter forms in the other script, e.g. Cyrillic АаВСсЕеНІіЈјКМОоРрЅѕТХху vs Latin AaBCcEeHIiJjKMOoPpSsTXxy. You might accidentally type a letter in the wrong alphabet and introduce a bug.

**Describe the solution you'd like**
Maybe there could be a version of Iosevka where different scripts look different enough to be noticeable, but similar enough to work as one font in the same environment. Maybe Latin can be one weight heavier or lighter and be slab-serif, while Cyrillic can be sans-serif.

**Describe alternatives you've considered**

It would be possible to composite two different fonts, but that may break monospace letter width.

**Additional context**

**Comment by be5invis** [comment]
Well according to Unicode they **SHOULD** look identical. I do not see any existing fonts differentiate them on purpose. Many editors, like VSCode, started adding a feature to mark "look-identical" characters in recent versions.
A solution might be building multiple families of Iosevka using different configurations, then subsetting them, then building a composite using the subsets.

**Comment by VladWinner** [comment]
I am sure that the problem of random typing of Cyrillic Extended letters on standard keyboard layout and further confusing it with the Latin alphabet is far-fetched. 
The only case with QWERTY layout where confusion is possible is the key with Latin letter `C` and Cyrillic letter `С` at the same time. 
![image](https://user-images.githubusercontent.com/13555921/149918945-31f66a4a-8bc2-4585-9515-7a4ac42f3d83.png)
But I also don't see any existing monospace fonts distinguishing them specifically.
