### ISSUE TITLE
Iosevka Fedora 35 COPR repo doesn't function correctly

### ISSUE THREAD

**Issue by VihagChaturvedi** [be5invis/Iosevka#1276]
```
Enabling a Copr repository. Please note that this repository is not part
of the main distribution, and quality may vary.

The Fedora Project does not exercise any power over the contents of
this repository beyond the rules outlined in the Copr FAQ at
<https://docs.pagure.org/copr.copr/user_documentation.html#what-i-can-build-in-copr>,
and packages are not held to any quality or security level.

Please do not file bug reports about these packages in Fedora
Bugzilla. In case of problems, contact the owner of this repository.

Do you really want to enable copr.fedorainfracloud.org/peterwu/iosevka? [Y/n]: y
Error: This repository does not have any builds yet so you cannot enable it now.

```
---

* Your font version: (Release or git, version) 
* Your font variant:
* Your operating system (name and version): Ultramarine Linux (based on Fedora 35) 
* Your application using Iosevka:

**Comment by be5invis** [comment]
What is this? Iosevka is just a standalone project, not having any part related to Fedora.

**Comment by nsemrau** [comment]
Copr repositories are user repositories for Fedora Linux. Software that is not yet in Fedora's own software repositories can be packaged, maintained, and distributed through these user repositories. As a Fedora user you may add and activate e.g. the Iosevka Copr. Afterwards, Iosevka is installabe as a regular package in your Fedora installation from this third party repository.

**Comment by alexeyten** [comment]
I guess the issue should be addressed to repository maintainer (peterwu).

**Comment by be5invis** [comment]
Resolve as external.
This repository here only maintains the "core" code of this font.
Please contact the COPR maintainer to fix their bugs.
