### ISSUE TITLE
Question about editing stroke widths

### ISSUE THREAD

**Issue by nashpatty** [be5invis/Iosevka#1277]
@be5invis not sure which category to put this under, cuz it's not really an issue, but a question.
I forked the repo to modify the split slash zero a little more to my liking, following the commit in [1270](https://github.com/be5invis/Iosevka/issues/1270).
Could you direct me to where I could change the weight of the slash stroke, to make it narrower? 
Wasn't able to find a good solution after trying different things out.

**Comment by be5invis** [comment]
`font-src/glyphs/number/0.ptl`, there's a definition like this:

```
define SplitSlashGap : Stroke * HVContrast + [clamp (CircleInnerWidth / 5) (CircleInnerWidth / 3) ([AdviceStroke 5] * HVContrast)]
```

**Comment by nashpatty** [comment]
> `font-src/glyphs/number/0.ptl`, there's a definition like this:
> 
> ```
> define SplitSlashGap : Stroke * HVContrast + [clamp (CircleInnerWidth / 5) (CircleInnerWidth / 3) ([AdviceStroke 5] * HVContrast)]
> ```

hey, I think I mis-phrased my question. I know this bit modifies the gap between the slash and the zero outline. 
I was asking about how to change the weight of the slash stroke itself, to make it thinner.

**Comment by be5invis** [comment]
Replace

```
	define [ZeroSlash top] : dispiro
		flat 0 (top * (1 - 0.77)) [widths.center OverlayStroke]
		curl Width (top * 0.77)

	define [ZeroReverseSlash top] : dispiro
		flat 0 (top * 0.77) [widths.center OverlayStroke]
		curl Width (top * (1 - 0.77))
```

with something like

```
	define [ZeroSlash top] : dispiro
		flat 0 (top * (1 - 0.77)) [widths.center [AdviceStroke 4]]
		curl Width (top * 0.77)

	define [ZeroReverseSlash top] : dispiro
		flat 0 (top * 0.77) [widths.center [AdviceStroke 4]]
		curl Width (top * (1 - 0.77))
```

Increasing the number in `[AdviceStroke ###]` will make the stroke further thinner.

**Comment by nashpatty** [comment]
It's perfect :grinning:... thank you!
<img width="480" alt="Screen Shot 2022-01-12 at 6 09 01 PM" src="https://user-images.githubusercontent.com/28615881/149237483-058d7cb4-4508-4408-bdf8-3a88be4175f3.png">
