### ISSUE TITLE
Bugs in cherry-picking tool on website.

### ISSUE THREAD

**Issue by a3b4c6** [be5invis/Iosevka#1278]
I am trying to create a variant of Etolie with rounded hooks for f, t, j, etc. instead of flat ones. But the cherry-picking tool selects is buggy.

Preparation to reproduce bug:
* Go to website.
* Scroll down to "Variants à la Carte".
* Click on "Etoline".

### First Bug:
With "stylistic sets" set to off, many letters are different in the "Cherry-Picking" matrix and the preview above it. For example, the preview shows a flat-hooked t, while the matrix shows a round-hooked t. Changing from round-hooked t to flat-hooked t does not change the preview. It is impossible to make a round-hooked t in the preview. This applies to many other letters too, like f and j.

![problem](https://user-images.githubusercontent.com/73483158/149619475-50e911ca-8c91-4d3d-b0e6-c89121ed26ff.gif)

### Second Bug:
Maybe this is just the same bug. Click on "ss01" for Andale Mono. The letter j is not highlighted as changed even though it is different from the default.

**Comment by be5invis** [comment]
Hmm, I think `Aile` and `Etoile` should not occur here (though the customizer does support making a customized quasi-proportional).

**Comment by be5invis** [comment]
Resolve as fixed.
