### ISSUE TITLE
[想法建议]能不能以现有部件组合一套OCR识别专用字体

### ISSUE THREAD

**Issue by nobk** [be5invis/Iosevka#1279]
这套字体不是给人看的，而是专门用于软件截屏后的OCR识别。
一些软件的屏显内容无法通过自动化界面API直接读取，但软件支持对显示内容的字体选择。
如果能开发一个字体，能对PaddleOCR或者EasyOCR识别率达到100%准确（可能需要向其提交针对性的训练数据），那还是非常有应用前景的。

**Comment by be5invis** [comment]
No plan for this.
Resolve as Out of scope.
