### ISSUE TITLE
Is there a tutorial on how to install custom builds of Iosevka on Windows 10?

### ISSUE THREAD

**Issue by CUBAN-MISSILE-CRISIS** [be5invis/Iosevka#1281]
For context, I'm not very coding-savvy nor am I familiar with how github works generally. But I have been trying my best to install a customized build of Iosevka on Windows 10 since I discovered it about a month ago to no avail.  

It doesn't seem that there's any tutorial on how to install a customized build other than the "building from source" written instructions, which are very unclear to someone like me. Even starting with step 1 was a seemingly impossible challenge that I'm still not sure if I got right at all.

If a video tutorial does exist on how to install a customized version of Iosevka, could someone send a link to it? Or could someone make a video tutorial on how to do it? That'd be very much appreciated.

**Comment by jamapy** [comment]
https://yewtu.be/watch?v=W77sZEkkIAk --> How to install font in Windows 10.
The font you want to install located in `/dist/(your custom iosevka font name/ttf` folder.

**Comment by lorenzogatti** [comment]
High level instructions:
1) install npm and Python
2) install required npm and Python packages
3) download current Iosevka sources
4) add your custom build file to the Iosevka sources
5) build Iosevka
6) if everything goes well, install ttf files.

Steps 1 and 2 are one-time tasks and as jamapy explains, step 6 is generic for any font.

I personally use a script to automate steps 3 to 5 (downloading sources with curl+unzip, updating npm packages just in case and regenerating the build file using JSonnet).

**Comment by AndydeCleyre** [comment]
FWIW I use GitHub Actions to build, in [this repo](https://github.com/AndydeCleyre/archbuilder_iosevka).
