### ISSUE TITLE
Custom build instructions

### ISSUE THREAD

**Issue by avivace** [be5invis/Iosevka#1284]
Custom build instructions are gone and many links around are broken, such as https://github.com/be5invis/Iosevka#customized-build (from the Iosevka customizer: https://typeof.net/Iosevka/customizer)

**Comment by be5invis** [comment]
It is here: https://github.com/be5invis/Iosevka/blob/master/doc/custom-build.md
On the next release the website will fix this link.

**Comment by avivace** [comment]
> It is here: https://github.com/be5invis/Iosevka/blob/master/doc/custom-build.md On the next release the website will fix this link.

Maybe we could still have a link to "Build from source" in the main README?
