### ISSUE TITLE
= looks weird on termite

### ISSUE THREAD

**Issue by Piczel** [be5invis/Iosevka#129]
* Your font version: AUR, 1.9.6-1
* Your operating system (name and version): arch 4.8.10
* Your application using Iosevka: termite 12-1

---

Hi guys ! 
Just discovered this amazing font ( :+1: ), but I'm wondering if the '=' sign is correctly displayed in my term.

Here is a scrot : http://img.piczel.tk/25751.png

(just checked)
Ok, the problem comes from termite, any suggestion ?

Thx !

**Comment by be5invis** [comment]
Some Linux environments cannot handle ligatures properly.
You can switch into `Iosevka Term` (listed in the Releases page) for terminals.
Closed.
