### ISSUE TITLE
ligatures at unicode codepoints

### ISSUE THREAD

**Issue by xsrvmy** [be5invis/Iosevka#1290]
Is it possible to provide the ligatures at unicode codepoints, so that non-ligature environments like emacs, gvim, and terminals can use them via software features like vim conceal?

They would probably have to go in the upper plane's private use area though. The main private-use area is used by nerd fonts in terminals, unless maybe there is a gap?

**Comment by be5invis** [comment]
https://github.com/be5invis/Iosevka/blob/master/doc/custom-build.md#compatibility-ligatures
