### ISSUE TITLE
Double square brackets

### ISSUE THREAD

**Issue by ObserverOfTime** [be5invis/Iosevka#1294]
- [x] A programming language requires this ligation. Provide the information below.
- [ ] This ligation is implemented in other programming fonts. Provide samples below.

------

A ligature for double square brackets would be nice for TOML amongst others.
You could probably use the existing ⟦ and ⟧ characters for them.

**Comment by be5invis** [comment]
We currently have `[|` and `|]` in `dlig`. However, I do not see any programming language implemented `[[` / `]]`.

**Comment by ObserverOfTime** [comment]
* [TOML](https://toml.io/en/v1.0.0#array-of-tables)
* [bash](https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Conditional-Constructs-1)
* [R](https://cran.r-project.org/doc/manuals/R-lang.html#Indexing)
* [C++](https://en.cppreference.com/w/cpp/language/attributes)

**Comment by be5invis** [comment]
I mean, no programming fonts are doing such ligation.

**Comment by ObserverOfTime** [comment]
Shut up, bot.

**Comment by ObserverOfTime** [comment]
https://github.com/TomasHubelbauer/fuck-you-stale-bot
