### ISSUE TITLE
Music double sharp 𝄪 and double flat 𝄫 symbols

### ISSUE THREAD

**Issue by dieggsy** [be5invis/Iosevka#1299]
- The requested character is...
  - [ ] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [x] Symbol
- [ ] Some other monospace/programming fonts supported this character. Provide images below.

------
These are U+1D12A and U+1D12B. I was recently writing some code dealing with musical notation and thought since Iosevka already has the regular music sharp/flat symbols these would be nice to have as well.

**Comment by be5invis** [comment]
These are in the "proper" music symbols block. I think a programming font won't need to support these. Are there programming languages using these? As far as I know, Agda uses Sharp and Flat for "delayed" data types.

**Comment by pv4** [comment]
> a programming font won't need to support these

Excuse me for interrupting, but I think Iosevka is too good now to be just a "programming" font.

I personally use it everywhere including as a program interface font and as a default font in web browser. I also saw a person here, on this issue tracker, who uses a customized Iosevka build as a default Android font on his Xiaomi (afair) smartphone.

**Comment by dieggsy** [comment]
> These are in the "proper" music symbols block. I think a programming font won't need to support these. Are there programming languages using these? As far as I know, Agda uses Sharp and Flat for "delayed" data types.

Not as far as I know. I leave it up to you.

@pv4 I agree with you to some degree, but I think there's a useful distinction between how users regard or use the project and what the author's intent or intended scope is. Which is to say, our usage doesn't demand that the author do anything to support it. Not that your point doesn't merit discussion or consideration at the very least.

Of course, I'm generally of the opinion that "the more the merrier" :), but in the end it's @be5invis that determines whether a request adheres to their design princples (and the one doing all the work) so I'm certainly not making any demands.

**Comment by pv4** [comment]
@dieggsy I absolutely agree with what you say. Creator is always the person who knows what is better for his product. I just wanted to point that Iosevka has overgrown lots of "programming fonts" that cannot be used for anything but programming just because they only support basic ascii character set.
