### ISSUE TITLE
ugly iosevka on qtcreator

### ISSUE THREAD

**Issue by dinama** [be5invis/Iosevka#130]
* Your font version: font-iosevka-1.9.6_1
* Your font variant:
* Your operating system (name and version): void linux
* Your application using Iosevka: qtcreator
If you have problem when building Iosevka, please provide these informations:

--
ugly (like Thin) iosevka on qtcreator main code editor window (see attachmets)
is qtcreator bug or fontconfig issue?

![2016-11-29-161703_998x315_scrot](https://cloud.githubusercontent.com/assets/10299205/20713432/4e439662-b659-11e6-8e92-37aebce9ae67.png)
![qt_iosevka_bug](https://cloud.githubusercontent.com/assets/10299205/20713441/542e526a-b659-11e6-8e56-2410402f66f2.png)

**Comment by be5invis** [comment]
Perhaps a QtCreator bug that accidentally applies the thin variant as default.
Uninstalling the thinner variants, with only `regular` and `bold` kept, would solve this.

**Comment by be5invis** [comment]
Closed as external.
