### ISSUE TITLE
Can't find the .TTF for Linux installation

### ISSUE THREAD

**Issue by hedonnn** [be5invis/Iosevka#1300]
I've been searching inside the repository but find no .TTF files for download in Linux or I don't know where to find them sorry. :(

**Comment by be5invis** [comment]
Please download them from [Releases](https://github.com/be5invis/Iosevka/releases).

**Comment by ChiefMikeK** [comment]
Suggested change to **README.md**
* **Linux** : Download the zip archive from [Releases](https://github.com/be5invis/Iosevka/releases) and copy the TTF files to your fonts directory → Run `sudo fc-cache`.

**Comment by jakecoble** [comment]
Your distribution may have packaged _TTC_ files instead of TTF files.
