### ISSUE TITLE
Some brackets are misaligned between weights

### ISSUE THREAD

**Issue by KogasaPls** [be5invis/Iosevka#1301]
Curly braces appear to shift downwards slightly when the font weight is increased (from 'regular'). 

![brackets](https://user-images.githubusercontent.com/87504405/153777057-07b43781-543b-40f3-9709-444009a2b1ac.gif)

Parentheses remain perfectly aligned, and square brackets shift _upwards_ slightly.

Tested with various versions, including `ttc-iosevka` (AUR package, 13.3.1), a custom build of 14.0, and regular/term/fixed variants from both. Also tested with `alacritty` terminal emulator and `gedit`.

---

* Your font version: 14.0
* Your font variant: 
* Your operating system (name and version): Arch Linux
* Your application using Iosevka: `nvim` in `foot` terminal emulator

**Comment by be5invis** [comment]
Another rounding error.
Perhaps you can try the unhinted version (not sure whether AUR package managers uploaded them).

**Comment by be5invis** [comment]
You can find them under the release page: https://github.com/be5invis/Iosevka/releases/latest

**Comment by KogasaPls** [comment]
Thanks for the quick reply. I see no change when using the unhinted versions, but I understand that rounding errors can be hard/impossible to fix.

**Comment by be5invis** [comment]
Perhaps some weirdness happened in Freetype's autofitting... who knows.
