### ISSUE TITLE
Downward bit on 7 too thin in thicker weights

### ISSUE THREAD

**Issue by AlsoScratch** [be5invis/Iosevka#1303]
I understand that maybe it was because of the bent stem variant, so I suggest only changing the variants with the straight stem.
<img width="157" alt="Untitled 27" src="https://user-images.githubusercontent.com/48752273/153819441-0bf86b4c-ed75-4f2f-be3a-536f86896dc1.png">

---

* Your font version: (Release or git, version) 14.0.0
* Your font variant:
* Your operating system (name and version): macOS 12.2
* Your application using Iosevka: Official website ([https://typeof.net/Iosevka/](https://typeof.net/Iosevka/))

**Comment by be5invis** [comment]
Well all the vertical serifs share this width, and it is thinner than stroke width (otherwise letters like `T` will look very strange).
![image](https://user-images.githubusercontent.com/240091/154012886-2f297cab-6cfa-4fd6-b610-d73ed8bf05cd.png)
