### ISSUE TITLE
Private-build-plans.toml to represent Courier Prime Sans?

### ISSUE THREAD

**Issue by cssobral2013** [be5invis/Iosevka#1304]
Specimens:
![Roman](https://user-images.githubusercontent.com/19995437/153935357-a029fe71-af1f-4304-a291-4842eb81307e.png)
![Italic](https://user-images.githubusercontent.com/19995437/153935352-5dea26cc-4f8f-4efc-8331-ad8e0ea34055.png)

**Comment by be5invis** [comment]
You can try using this to recreate one: https://typeof.net/Iosevka/customizer
