### ISSUE TITLE
Alternative split-slash zero

### ISSUE THREAD

**Issue by nashpatty** [be5invis/Iosevka#1306]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

Justification in this [comment](https://github.com/be5invis/Iosevka/issues/1306#issuecomment-1041624465)

@be5invis Thanks for your work on the [split-slash zero in #1270](https://github.com/be5invis/Iosevka/issues/1270).
Would it be possible to orient the split slash to truncate horizontally?
i.e. the slash should cut at the orange lines in this picture, as opposed to the red lines:
<img width="163" alt="Screen Shot 2022-02-14 at 9 56 19 PM" src="https://user-images.githubusercontent.com/28615881/153986311-2a76feb1-ac66-4f04-a861-d474717c148a.png">
Stylistically, this is how pragmata pro, and cartograph have it.

**Comment by be5invis** [comment]
I tried this before, but because of the narrowness of Iosevka, this shape looks very strange, so I decided to do vertical cut.

**Comment by nashpatty** [comment]
I understand.
Is there a branch/commit with the experimental horizontal cut? I'd like to check it out, and play around with it.

**Comment by nashpatty** [comment]
In the default style of the split slash 0, I agree, the horizontal cut looks very odd:
<img width="231" alt="Screen Shot 2022-02-16 at 10 07 50 AM" src="https://user-images.githubusercontent.com/28615881/154295295-0ebc471b-10ce-4278-95c0-e7d9cbce2293.png">

But I modified the stroke a little based off your feedback in [#1277](https://github.com/be5invis/Iosevka/issues/1277). I made the stroke thinner, increased the gap between the outline and the stroke, and changed the angle of the slash a little. The horizontal cut looks a little better here:
<img width="231" alt="Screen Shot 2022-02-16 at 10 09 03 AM" src="https://user-images.githubusercontent.com/28615881/154295645-5b883e26-d657-475e-a433-5569540c41f9.png">

This is similar to the horizontal cuts in both pragmata, and cartograph:
<img width="231" alt="Screen Shot 2022-02-16 at 10 13 54 AM" src="https://user-images.githubusercontent.com/28615881/154295753-8d98fd99-8cc4-4bbb-94ef-074e76ecd61b.png">

<img width="89" alt="Screen Shot 2022-02-16 at 10 14 56 AM" src="https://user-images.githubusercontent.com/28615881/154295795-11c201b7-d35d-4454-add4-e51a26b2b3c4.png">

If there's an experimental branch with the horizontal cuts, I could fiddle with it more to see if I can get to a nice, aesthetically pleasing form.
