### ISSUE TITLE
Request moon-phase Unicode glyphs

### ISSUE THREAD

**Issue by PhilHudson** [be5invis/Iosevka#1308]
- The requested character is...
  - [ ] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [x] Symbol
- [x] Some other monospace/programming fonts supported this character. Provide images below.
  Hack and Inconsolata-dz have them. This is literally the only thing I have come to regret about changing from Hack to Iosevka.
------

*Please provide justification here.*
They're cool. Also the 'spinner' Emacs package needs them.

**Comment by be5invis** [comment]
Please provide a list of these characters.

**Comment by PhilHudson** [comment]
NEW MOON SYMBOL: 01F311
WAXING CRESCENT MOON SYMBOL: 01F312
FIRST QUARTER MOON SYMBOL: 01F313
WAXING GIBBOUS MOON SYMBOL: 01F314
FULL MOON SYMBOL: 01F315
WANING GIBBOUS MOON SYMBOL: 01F316
LAST QUARTER MOON SYMBOL: 01F317
WANING CRESCENT MOON SYMBOL: 01F318

**Comment by be5invis** [comment]
I think those are considered Emoji... How did Hack and Inconsolata-DZ implement them?

**Comment by VladimirMarkelov** [comment]
It seems they are emoji added in "Unicode 6.0" standard (e.g, https://emojipedia.org/new-moon/).

I see "Deja Vu Sans" supports them, but "Deja Vu Sans Mono" does not. As of "Deja Vu Sans" they added those emoji support in the commit https://github.com/dejavu-fonts/dejavu-fonts/commit/2c7dc17e29c866b71d7cd73a8325522a7c52bb41

**Comment by PhilHudson** [comment]
![2022-02-17_06-18-24](https://user-images.githubusercontent.com/449330/154417493-dcf75a0f-fb6f-4f31-a67f-bd35bbd2b7ba.png)
Hack Regular 16

**Comment by PhilHudson** [comment]
Thank you.
