### ISSUE TITLE
Two feature requests, inspired bu input font

### ISSUE THREAD

**Issue by zou000** [be5invis/Iosevka#131]
Before coming across Iosevka I use a customized input font: http://input.fontbureau.com/download/index.html?customize
I use the "input mono compressed" variant, which is the narrowest one. I also customized a version of  Iosevka. In general I like Iosevka better than input font, but I do miss two features provided by input font customization:
* The variant of the more curved braces "{}", which are easier to read with small font size.
* The configurable built-in line spacing: I like lines to be a little bit denser. It would be great if there is make argument specify the multiplier.

Thanks for the great font!

**Comment by be5invis** [comment]
The line space can be configured using the `leading` property in the `parameters.toml`.

**Comment by be5invis** [comment]
Closed as consolidated into #140.
