### ISSUE TITLE
Moon-phase Unicode glyphs are too small

### ISSUE THREAD

**Issue by hroemer** [be5invis/Iosevka#1311]
The new moon phase glyphs (#1308) are too small in comparison to similar glyphs (U+1F30E, U+1F30F, ...):

![iosevka_ss05_moon_phase](https://user-images.githubusercontent.com/16097755/154838593-8e7a7f00-e92f-4e7c-b0cb-ac5a30f23825.png)

---

* Your font version: 14.0.1
* Your font variant: Term SS05
* Your operating system (name and version): Linux 5.15
* Your application using Iosevka: Alacritty, etc.

**Comment by hroemer** [comment]
I just realized that the other glyphs must be provided by a fallback font, e.g. same glyphs in IntelliJ:

![iosevka_ss05_moon_phase_idea](https://user-images.githubusercontent.com/16097755/154838897-c81cdb9f-b219-4ba5-bb3b-fbbad7e37bfc.png)

But still, the rendered sizes are way too small in my opinion.

**Comment by be5invis** [comment]
Well that's Iosevka Term's feature: they are single-cell wide.
The normal "Iosevka" have them twice large, having the similar size of other Emojis.

Resolve as by design.
