### ISSUE TITLE
Wider variant

### ISSUE THREAD

**Issue by glebd** [be5invis/Iosevka#132]
Is it possible to tweak font build options to stretch character box horizontally in order to produce wider variants that would be a little easier on the ageing eyes (1.5× to 2× wide)?

**Comment by glebd** [comment]
Found it: width = 500 in parameters.toml

**Comment by firedev** [comment]
If anything I would vote for a more narrow version, guess have to learn how to compile it.

**Comment by Cybolic** [comment]
For anyone else tinkering with this, a width of 550 gives a a result slightly narrower than Fira Code (a few pixels, from what I can see), but still plenty wide.

Example:
![screenshot from 2018-03-03 19-05-25](https://user-images.githubusercontent.com/1196197/36937031-df8b9504-1f15-11e8-90f8-0579f25340c8.png)
