### ISSUE TITLE
@-character lacks spacing in Aile

### ISSUE THREAD

**Issue by illfygli** [be5invis/Iosevka#1323]
* Your font version: 14.0.0, also happens with latest version on https://typeof.net/Iosevka/
* Your font variant: Iosevka Aile
* Your operating system (name and version): Arch Linux, rolling release
* Your application using Iosevka: Used as UI font in Sway, as well as default font in many other programs.

Recently, the spacing on the right side of `@` is missing.
I don't know exactly when it started, possibly 14.0.0.

![screen](https://user-images.githubusercontent.com/42881386/156879104-34c39620-553f-47d4-a1f6-20e0a11cfed6.png)

Thank you for these fonts, they are really very good and useful.

**Comment by be5invis** [comment]
Already fixed in dev. Closing.
