### ISSUE TITLE
Issue with ligatures on kitty

### ISSUE THREAD

**Issue by tpoisot** [be5invis/Iosevka#1326]
After using a private build plan, the ligatures do not work in kitty:

![1646763923](https://user-images.githubusercontent.com/579329/157316169-df4991bf-4920-40e3-aa87-678aa193e0ba.png)

---

* Your font version: 721fe3367f8a9e0a9107463584ba22c0dce27961
* Your font variant: Custom
* Your operating system (name and version): Linux 5.16.12-arch1-1
* Your application using Iosevka: `kitty 0.24.4`

If you have problem when building Iosevka, please provide these information:

* Your Node.js version: `v17.6.0`

* Your `private-build-plans.toml`, if present:

~~~
[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
no-cv-ss = true

  [buildPlans.iosevka-custom.variants]
  inherits = "ss08"

    [buildPlans.iosevka-custom.variants.design]
    a = "double-storey-serifless"
    d = "toothed-serifless"
    f = "tailed"
    g = "single-storey-flat-hook-serifless"
    h = "straight-motion-serifed"
    i = "serifed-flat-tailed"
    l = "serifed-flat-tailed"
    p = "eared"
    q = "straight"
    t = "flat-hook"
    v = "curly"
    x = "curly-serifless"
    y = "curly-turn"
    z = "straight-top-serifed"
    turn-v = "curly"
    lower-delta = "flat-top"
    capital-gamma = "top-right-serifed"
    lower-lambda = "curly-turn"
    lower-xi = "rounded"
    zero = "slashed-split"
    one = "base"
    two = "curly-neck"
    four = "semi-open"
    five = "oblique-upper-left-bar"
    seven = "curly-serifed"
    eight = "crossing-asymmetric"
    asterisk = "turn-hex-low"
    underscore = "high"
    pilcrow = "high"
    caret = "low"
    paren = "flat-arc"
    brace = "curly"
    number-sign = "upright"
    ampersand = "et-toothless-corner"
    at = "fourfold-solid-inner"
    dollar = "open-cap"
    cent = "bar-interrupted"
    percent = "rings-continuous-slash"
    lig-ltgteq = "slanted"
    question = "corner-flat-hooked"

[buildPlans.iosevka-custom.weights.light]
shape = 300
menu = 300
css = 300

[buildPlans.iosevka-custom.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-custom.weights.medium]
shape = 500
menu = 500
css = 500

[buildPlans.iosevka-custom.weights.semibold]
shape = 600
menu = 600
css = 600

[buildPlans.iosevka-custom.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-custom.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-custom.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
~~~

**Comment by be5invis** [comment]
You need to set `export-glyph-names` to true to make it work in Kitty. See https://github.com/be5invis/Iosevka/blob/master/doc/custom-build.md#configuring-custom-build

**Comment by real-or-random** [comment]
I just ran into the same issue. Could `export-glyph-names` be added to `private-build-plans.toml`, preferably enabled by default?

**Comment by be5invis** [comment]
@real-or-random @tpoisot  I added option in the customizer, which allows you to put that into your `privat-build-plans.toml`.

**Comment by zzhaolei** [comment]
my [private-build-plans.toml](https://github.com/zzhaolei/comfy-code/blob/v1.2.1/private-build-plans.toml)

<img width="345" height="132" alt="Image" src="https://github.com/user-attachments/assets/be86e8be-d89d-4fa5-ba72-ac504f204e1c" />

Apple M4, macOS26.3.1

I added `exportGlyphNames = true` in `private-build-plans.toml`, but Kitty still doesn’t render correctly. Why might this be?
