### ISSUE TITLE
Add glyphs to render progress bars (from Fira Code)

### ISSUE THREAD

**Issue by inkarkat** [be5invis/Iosevka#1327]
- The requested character is...
  - [ ] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [X] Symbol
- [X] Some other monospace/programming fonts supported this character.

![Fira Code progress bars](../../..//tonsky/FiraCode/raw/master/extras/progress.png)

![Fira Code example](../../../tonsky/FiraCode/raw/master/extras/progress.gif)

------

I've chosen Iosevka (in its _fixed slab_ variant) as my new programming font; it's beautiful; your dedication and care becomes obvious immediately! During the selection I've reviewed many other programming fonts. I liked the idea in [Fira Code](https://github.com/tonsky/FiraCode) about standardized custom glyphs to make progress bars in the terminal look more GUI-like. Its developers explicitly encourage adoption: _We hope more programming fonts will adopt this convention and ship their own versions._ So I would love to see this added to Iosevka.

Thanks again for your great work (and for considering this)!

**Comment by akarzim** [comment]
@inkarkat it's already there ! 🤩 

cf. https://github.com/be5invis/Iosevka/commit/52a865571ce22247267c81b758ecc2d6627d001b

**Comment by inkarkat** [comment]
@akarzim Oh, wow, even better :-) Thanks for pointing me to it; I apparently was looking at the wrong codepoint!

**Comment by inkarkat** [comment]
Although the readme already has this long and impressive list of features, it might be a good idea to mention these glyphs there as well. When I saw the animated GIF (linked above in this issue) on the Fira Code page, I was immediately wowed by it, and only decided against that font when I did not like its overall appearance.
