### ISSUE TITLE
Control the length of ascenders and descenders when changing xHeight

### ISSUE THREAD

**Issue by efermi** [be5invis/Iosevka#1334]
Currently when changing xHeight it happens within the bounding box and at the expense of the length of ascenders and descenders. Is it possible to proportionally change their length too, maybe by changing font's total body height?

**Additional context**
Trying to make the expanded width more legible on small sizes I set xHeight to 550, which helps, but feels cramped. Compare Iosevka and Hack:
![iosevka](https://user-images.githubusercontent.com/3966555/161967787-9b9c36b0-d641-4539-a901-4b01f6796155.png)![hack](https://user-images.githubusercontent.com/3966555/161967878-f2bbdf10-3239-4d60-88aa-fab76651399e.png)

**Comment by be5invis** [comment]
We have `cap` to control Cap height _and_ ascender (yes they are synchronized). Descender is derived from these values.

**Comment by be5invis** [comment]
> Could it be done independent of the cap height?

Currently no -- this needs A LOT OF refactors.

**Comment by efermi** [comment]
Wow, a huge thank you.
