### ISSUE TITLE
the crossbar in lowercase T

### ISSUE THREAD

**Issue by nashpatty** [be5invis/Iosevka#1336]
@be5invis 
Unsure which category this issue would go under. I want to modify the crossbar of the lower-case T, so that the crossbar extends further to the right. Essentially I want to make the crossbar on the right side of the T stem longer, and not just shift it to the right.
Where in the lower-case-t.ptl file would I make this edit?

As it currently stands, optically, the lower-case T looks like its leaning too far to the left, because the shape of the hook at the bottom extends way beyond the crossbar. I want to modify it to see how it looks.

I want to try something like this (in a forked repo):
<img width="207" alt="Screen Shot 2022-04-15 at 4 25 30 PM" src="https://user-images.githubusercontent.com/28615881/163629037-96300313-62c7-4d68-ba4e-9cd8baedb91b.png">

**Comment by be5invis** [comment]
This is about balancing, so modify existing variants instead.

**Comment by nashpatty** [comment]
Thanks for the guidance, as always!
