### ISSUE TITLE
Ioveska Aile and Etoile SGR

### ISSUE THREAD

**Issue by tormento** [be5invis/Iosevka#1338]
Would you please add (in the package description) what is the difference between the upper SuperTTC and TTC download links and the lower (finename starting with SGR) ones?

I really can't understand neither the difference nor what SGR stands for.

Thank you :)

**Comment by be5invis** [comment]
SuperTTC merges all weights into one TTC, while normal TTC don't merge weights.
SGR is for "single group". For Aile and Etoile, they are equivalent to the normal TTC. Maybe I should remove them...

**Comment by tormento** [comment]
@be5invis the files are not exactly the same. Perhaps some parameters during build change the output.

**Comment by be5invis** [comment]
@tormento They function the same, though, some minor details may differ.
