### ISSUE TITLE
Stylistic set to represent Hack (or, a private-build-plans.toml to make one)?

### ISSUE THREAD

**Issue by cssobral2013** [be5invis/Iosevka#1339]
http://www.identifont.com/find?font=hack&q=Go

**Comment by be5invis** [comment]
Looks like mostly identical to the Menlo variant -- maybe you can try the [Customizer](https://typeof.net/Iosevka/customizer).

**Comment by cssobral2013** [comment]
@be5invis - Thank you, I'll try it.
