### ISSUE TITLE
"@" glyph shape is problematic

### ISSUE THREAD

**Issue by p-e-w** [be5invis/Iosevka#134]
I have had Iosevka (1.9.6) in daily use for some time now, and while the font is well balanced overall, my eyes keep getting stuck on the `@` glyph.

![](https://cloud.githubusercontent.com/assets/2702526/21077927/a9fe165e-bf81-11e6-826a-7b5511ee2f4b.png)

That glyph is one many coding fonts struggle with. Here's what I think is problematic with Iosevka's current interpretation of `@`:

1. `@` is a stylized `a`. In Iosevka, it looks like a stylized `d`.
2. The shape of `@` approximates a circle (see the proportional font example above). In Iosevka, it approximates a rectangle with aspect ratio 3:1.

The result is a glyph that looks distorted and consistently stands out in code.

The best solution I've seen is the one implemented by Fira Code. Indeed, Fira Code is alone among programming fonts in providing an `@` that looks both balanced and recognizably like an `a`.

It would be nice if Iosevka could switch to an `@` that follows Fira Code's idea, or at least provide it as an alternate. Or perhaps another solution to the above mentioned problems can be found?

**Comment by be5invis** [comment]
There are three styles:

cv31:
![image](https://cloud.githubusercontent.com/assets/240091/21148775/42c3b70e-c194-11e6-82e3-0ef818c8186f.png)
cv32:
![image](https://cloud.githubusercontent.com/assets/240091/21148783/49ab1706-c194-11e6-9b45-2117f51e7a25.png)
cv33:
![image](https://cloud.githubusercontent.com/assets/240091/21148767/3a9de8ce-c194-11e6-8da6-50c77df074cd.png)

**Comment by p-e-w** [comment]
From feature request to implementation to new release containing the feature in just three days! I'm speechless... 😮 😲 💯

Thank you very much for those updates and the new default `@`. Iosevka is truly an "open-source" font – not just a Git repository with a single "binary" type change per year, but a living project where the commit log actually makes sense. It's a joy to watch this amazing font evolve!
