### ISSUE TITLE
New design for the comma & semicolon sign

### ISSUE THREAD

**Issue by ilyaw39** [be5invis/Iosevka#1342]
## Request:

I am wondering if the maintainer could add comma sign (as well as the semicolon sign) options based on the design in PragmataPro & Source Code Pro.

![](https://i.imgur.com/lJcyUee.png)

## Alternatives

If PragmataPro cannot be used due to copyright issues, please consider Source Code Pro as the first priority.

---

P.S. Please remove the text "(Variant Request)" from the title after correctly labelling.

**Comment by be5invis** [comment]
This is about glyph shape rather than a variant. Unfortunately, Source Code Pro and Pragmata Pro's shape are sort of misaligned with Iosevka's general geometry. Making the "neck" of the comma thinner is actually made to make its shape more "significant".
