### ISSUE TITLE
Would you consider enlarging U+02BE and U+02BF?

### ISSUE THREAD

**Issue by theodore-s-beers** [be5invis/Iosevka#1346]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

I'm sorry if I've used the wrong template. What I'm wondering is whether you would consider slightly enlarging the glyphs for U+02BE (ʾ) and U+02BF (ʿ). It's a good thing that these characters are included at all (they were added about two years ago as a result of #588). But they're pretty small relative to typefaces in which they are commonly used (see e.g. Brill in the examples below), to the point of legibility problems at normal font sizes.

I've also included in the image Iosevka's glyphs for the left and right single quotation marks. I wouldn't necessarily suggest that U+02BE and U+02BF be made quite so prominent, but I think it's a useful point of comparison.

Perhaps @thlinard, who originally requested these characters, will have an opinion here. Like him, I use ʾ and ʿ for romanization of Arabic-script text.

<img width="900" alt="Screen Shot 2022-05-03 at 12 07 43" src="https://user-images.githubusercontent.com/32523293/166438986-052c15e0-46f3-4778-8055-f7c1922b93bd.png">

Thank you for your maintainership of this project.

**Comment by thlinard** [comment]
Sure, a little enlargement would improve the glyphs.

**Comment by theodore-s-beers** [comment]
Thanks!
