### ISSUE TITLE
Git prompt overlap of characters in terminals st and xterm

### ISSUE THREAD

**Issue by thinkoid** [be5invis/Iosevka#1347]
I am using what appears to be version 15.2.0, installed via aur:

```
❯ yay -Ss iosevka | grep Installed
aur/ttf-iosevka 15.2.0-1 (+138 0.43) (Installed)
```
The OS is Linux, distro is Artix. The powerlevel10k git prompt shows overlapping characters like in the image attached.

![github](https://user-images.githubusercontent.com/8246305/166687867-42b25e5a-be63-4da8-b294-510cbc7a2e57.png)

This happens in the two terminals I tried, `st` and `xterm`. It has been suggested to me that it may be an issue with the font rather than with the terminal or the powerlevel10k theme. I confess ignorance on these matters and I am at a loss even where to start digging. Any insight? Thanks.

**Comment by be5invis** [comment]
Please use Iosevka Term instead.
