### ISSUE TITLE
[Question]  Can anyone explain why there is no letter 'O' in the customizer page?

### ISSUE THREAD

**Issue by hardistones** [be5invis/Iosevka#1348]
Customizer:  https://typeof.net/Iosevka/customizer

![image](https://user-images.githubusercontent.com/6490683/167073766-7bc6c30c-d4da-4dae-910a-0cf5579f24ea.png)

**Comment by alexeyten** [comment]
Because there is no customization variants for “O”.

**Comment by hardistones** [comment]
I see. Thanks.
