### ISSUE TITLE
"S" and "$" are difficult to tell apart

### ISSUE THREAD

**Issue by p-e-w** [be5invis/Iosevka#135]
(Iosevka 1.9.6)

The same text rendered in three coding fonts with line spacing 1.0:

![](https://cloud.githubusercontent.com/assets/2702526/21077983/40aa5e80-bf84-11e6-90fc-de34ae66491d.png)

Note that in Iosevka, you cannot tell that the second line consists of alternating `S` and `$` glyphs.

While this is an extreme example, the only thing that distinguishes `$` from `S` in Iosevka are two tiny lines at the top and bottom. I've found myself confused about which is which sometimes on a cursory glance.

[The vast majority of coding fonts](http://www.s9w.io/font_compare/) feature a `$` glyph with a continuous vertical line. I believe this should be default in Iosevka also, with the current design making a nice glyph variant. To further distinguish `$` and `S`, I like Source Code Pro's idea of making the serpentine curve a smaller size. It feels more like an operator that way, which is the function of `$` in most programming languages that use it.

**Comment by be5invis** [comment]
![image](https://cloud.githubusercontent.com/assets/240091/21148153/472e11ba-c192-11e6-9eab-1a8c1dda01db.png)
How about this
