### ISSUE TITLE
Kleisli arrow ligature not rendered correctly

### ISSUE THREAD

**Issue by alternateved** [be5invis/Iosevka#1350]
The Kleisi arrow ligature `>=>` is not rendered correctly when using Iosevka with kitty terminal. This issue appears with standard version of Iosevka installed from repository as well as with private build with `export-glyph-names` set to `true`. Even though `>=>` ligature seems broken, `<=<` looks correct as can be seen in below screenshot.

Issue [#5072](https://github.com/kovidgoyal/kitty/issues/5072) was closed on kitty side as it might be a problem with font itself. 

![Screenshot_20220509_083411](https://user-images.githubusercontent.com/45176912/167353277-38d1a25c-2265-4e50-9fa8-9f53d52ec9ac.png)

---

* Your font version: 9ceb2a46f61d89f28173052b77c62afabf86b5a0
* Your font variant: ss16 (but issue appears also with standard Iosevka)
* Your operating system (name and version): openSUSE Tumbleweed 20220506
* Your application using Iosevka: kitty

* `kitty.conf`:
```
font_family Iosevka Paratype LG
font_size 13
font_features Iosevka-Paratype-LG -calt +HSKL
```

* `private-build-plans.toml`:
```
[buildPlans.iosevka-paratype-lg]
family = "Iosevka Paratype LG"
spacing = "normal"
serifs = "sans"
no-cv-ss = true
export-glyph-names = true

[buildPlans.iosevka-paratype-lg.variants]
inherits = "ss16"

[buildPlans.iosevka-paratype-lg.ligations]
inherits = "haskell"

[buildPlans.iosevka-paratype-lg.weights.light]
shape = 300
menu = 300
css = 300

[buildPlans.iosevka-paratype-lg.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-paratype-lg.weights.medium]
shape = 500
menu = 500
css = 500

[buildPlans.iosevka-paratype-lg.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-paratype-lg.weights.extrabold]
shape = 800
menu = 800
css = 800

[buildPlans.iosevka-paratype-lg.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-paratype-lg.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
  ```

**Comment by be5invis** [comment]
@alternateved Can you try latest `dev` to see whether it is fixed?

**Comment by alternateved** [comment]
@be5invis Thank you! It seems that commit c901d79f7003585dd8f3ea574625820f92b7faa2 has fixed it.
