### ISSUE TITLE
sha256sum files for released zip files

### ISSUE THREAD

**Issue by ShuguangSun** [be5invis/Iosevka#1351]
**Is your feature request related to a problem? Please describe.**
Now there is no sha256sum for the released file and it not convenient for validation. For example, I install and update fonts with scoop, it needs a sha.

**Describe the solution you'd like**
A txt file with sha256sum for each of the zip files.

**Comment by be5invis** [comment]
Fixed in dev. Starting from next release the `doc/` directory will contain the hashes.
