### ISSUE TITLE
The character 'I' and 'l' looks identical in Aile

### ISSUE THREAD

**Issue by zhenlige** [be5invis/Iosevka#1352]
The character `I` and `l` is identical except an anchor.
That will make `google.com` and `googIe.com` (and other similar strings) identical, and words with `Ill` (such as `Illustrator`) appears strange (like `|||`).
Maybe this is not a bug, but I think there should be some differences between the two characters.

---

* Your font version: 15.3.0
* Your font variant: Iosevka Aile
* Your operating system (name and version): Windows 11 x64 build 22000.613
* Your application using Iosevka: Any application

**Comment by be5invis** [comment]
This is intentional, just like many other neo-Grotesque fonts. Differentiation is not a design goal for quasi-proportional.
Resolve as by design.
