### ISSUE TITLE
1-bit bitmap version (e.g. Linux Console .psf)

### ISSUE THREAD

**Issue by scy** [be5invis/Iosevka#1353]
**Is your feature request related to a problem? Please describe.**
I’m often using machines that do not have a “real” graphical user interface (GUI), but only a text-based interface with fixed-width fonts and no anti-aliasing. Examples of this are the [Linux console](https://en.wikipedia.org/wiki/Linux_console) on a server, or a microcontroller’s black-and-white (no gray) OLED screen like the one below. It would be awesome to be able to use Iosevka on these screens.

![image](https://user-images.githubusercontent.com/28629/168289714-ae100b60-d7e5-4e4d-b1a3-5498d5d7b73e.png)

**Describe the solution you'd like**
I’d love an official 1-bit (i.e. black and white, no gray, no antialiasing) bitmap (pixels, no vectors) rendering of Iosevka in a small font size, or maybe even several font sizes.

As you can see in the example above, there aren’t a lot of pixels on some of these screens. The screen in the example is 128×64 pixels small, the font uses 8×8 pixels per letter, and that includes 1 pixel of spacing between letters. Now, Iosevka is not square. This is how it looks in 8×21 pixels, with anti-aliasing turned off:

![image](https://user-images.githubusercontent.com/28629/168291938-79e96c7b-7c07-445a-b08d-6f8912e0fcb1.png)

You can immediately see the main reason why vector font to 1-bit conversion is hard: The stroke and counter widths are all over the place.

**Describe alternatives you've considered**
I could try using a vector to bitmap font converter like [FontBuilder](https://github.com/andryblack/fontbuilder), [Bitmap Font Generator](http://www.angelcode.com/products/bmfont/) or even [FontForge](https://fontforge.org/docs/tutorial/editexample8.html) to do a third-party conversion of Iosevka to a bitmap font, and then use something like [PSF Tools](http://www.seasip.info/Unix/PSF/) to convert them to the Linux console format – but maybe you’re interested in working on this challenge yourself. 😉 I can definitely help with converting between file formats once we have actual bitmaps, but I’m not a font designer myself, and the prospect of having to fix all the little quirks that occur after automated vector to pixel conversion isn’t making me happy at all.

**Additional context**
Linux console fonts may only contain 256 characters (512 are technically possible too, but will lead to a reduced number of available colors), but all Unicode characters are allowed. (In other words, you have to select 256 characters from all of Unicode). I personally would be most interested in ASCII, some accented Latin letters (I’m German), basic box drawing and a bit of powerline. But yeah, this means that we don’t have to convert _all_ of Iosevka to bitmap right from the start, but on the other hand we’ll probably need some kind of generator that will allow users to choose which characters should be contained in their selection of 256.

I can totally understand if your reaction to all of this is “nope, I don’t want anything to do with this Linux nonsense”. In that case, I will probably start working a bit on it myself, but only in my spare time, and it’s probably going to take me months. But, you know, I just had to ask. Iosevka is the first terminal font I’m absolutely in love with, the generative approach and customizability is awesome, and I really want to be able to use it in as many places as possible.

**Comment by be5invis** [comment]
For now Iosevka is a purely vector font. Creating raster fonts is very different from vector fonts, and if we really want to do that, perhaps it could be done in a separate project, built using a proper raster font creator. For the charset, _maybe_ we could just use [CP437](https://en.wikipedia.org/wiki/Code_page_437)...

**Comment by scy** [comment]
Thank you for the fast response :) As I said, I can totally understand if your focus is elsewhere.

If that’s alright for you, please leave this issue open for others to find, maybe someone else is also interested in working on this. I might do some experiments myself over the coming weeks, but don’t hold your breath, this is low-priority for me too.
