### ISSUE TITLE
The character weight of “❯” does not change significantly with the font weight 

### ISSUE THREAD

**Issue by akhilesh-balaji** [be5invis/Iosevka#1356]
* Your font version: (Release or git, version): v15.3.1
* Your font variant: Applicable to all
* Your operating system (name and version): Windows 10
* Your application using Iosevka: Alacritty, Inkscape, VS Code

The HEAVY RIGHT-POINTING ANGLE QUOTATION MARK ORNAMENT character, ❯, does not change its font weight significantly when the font weight is changed, remaining invariant. I tried this on my terminal emulator, Alacritty, Inkscaape, as well as VS Code, all with the same results.

In the following screenshot, the font weight is set to bold, and ❯ is clearly out of place:
![image](https://user-images.githubusercontent.com/69246693/170660414-c7140bac-40ff-4260-b6b8-01b65c37fc21.png)

Here is a screen recording within Inkscape, where I change the font weight:

https://akhilesh.wants.solutions/inkscape_skNL0sNPGv.gif

The font weight of ❯ changes significantly up to the normal font weight, after which it begins to look very out of place. Is this a problem that only I am facing? It looks very odd within my terminal.

**Comment by alexeyten** [comment]
`❭` — U+276D MEDIUM RIGHT-POINTING ANGLE BRACKET ORNAMENT
`❯` — U+276F HEAVY RIGHT-POINTING ANGLE QUOTATION MARK ORNAMENT
`❱` — U+2771 HEAVY RIGHT-POINTING ANGLE BRACKET ORNAMENT

May be you could use last one.
I don't think that changing weight of *decorative* symbols is a good idea.

**Comment by akhilesh-balaji** [comment]
OK, thanks for the suggestion. This works for me.
