### ISSUE TITLE
Problems with U+1D1E LATIN SMALL LETTER SIDEWAYS DIAERESIZED U

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#1357]
VXDD should apply to U+1D1E LATIN SMALL LETTER SIDEWAYS DIAERESIZED U. Compare U+00FC LATIN SMALL LETTER U WITH DIAERESIS.
![ᴞü](https://user-images.githubusercontent.com/1124347/170847435-40503a36-fa62-479e-855e-52ffa300b86f.png)

In the quasi-proportional fonts, U+1D1E need not be so squished. It would look better if it were the width of ⟨w⟩.

---

* Your font version: 15.4.0
* Your font variant: Iosevka Etoile
* Your operating system: macOS 10.14.6
* Your application using Iosevka: hb-view

**Comment by be5invis** [comment]
(I am sort of interested in what phonetic system used these sideways letters...)

**Comment by dscorbett** [comment]
They are used in the Uralic Phonetic Alphabet; see [L2/02-141](https://www.unicode.org/L2/L2002/02141-n2419-uralic-phonetic.pdf). A turned letter represents a reduced version of the plain letter’s sound. A sideways letter represents the same thing and is used when a turned letter would be visually ambiguous. Whether it would be visually ambiguous is not always well-defined: U+1D02 LATIN SMALL LETTER TURNED AE can also be sideways and U+1D1E LATIN SMALL LETTER SIDEWAYS DIAERESIZED U can also be turned. That means that, to avoid needing to squish U+1D1E, a valid alternative would be to use its turned (not sideways) form.
