### ISSUE TITLE
"^" should have a vertically centered variant (like "~" and "*" already do)

### ISSUE THREAD

**Issue by p-e-w** [be5invis/Iosevka#136]
(Iosevka 1.9.6)

Like `~` and `*`, the caret character `^` is used as an operator in some programming languages (usually signifying bitwise XOR).

It therefore would make sense to provide a vertically centered variant of `^` as well.

**Comment by firedev** [comment]
This is debatable. What about the cases where it actually means exponentiation like in Math. I think it should stay in place — above the line.

**Comment by p-e-w** [comment]
> This is debatable. What about the cases where it actually means exponentiation like in Math. I think it should stay in place — above the line.

That's precisely what glyph variants are for – they allow a single font to cover *both* use cases.

**Comment by be5invis** [comment]
Will apply High `^` to cv29, low `^` to cv30.
