### ISSUE TITLE
Double minus (--) ligation has weird hinting in the first minus

### ISSUE THREAD

**Issue by breucode** [be5invis/Iosevka#1360]
The double minus ligation has a weird hin in the first minus, just before the following one.

This is much more pronounced on my linux machine than on my mac. It makes the first minus seem a little bit higher than the rest (even though it isn't).

Screenshot from IntelliJ:
<img width="861" alt="intellij" src="https://user-images.githubusercontent.com/3304638/171028185-59ce2d8d-d6ae-4421-a57f-946a1f34d7e0.png">

Screenshot from wezterm:
<img width="509" alt="wezterm" src="https://user-images.githubusercontent.com/3304638/171028195-81dc9cdd-f68d-4e07-9858-b50ff12239ed.png">

---

* Your font version: (Release or git, version)
* Your font variant: SS15, extended as normal, dlig
* Your operating system (name and version): MacOS 12.4, Ubuntu 22.04
* Your application using Iosevka: Wezterm, IntelliJ Idea

* Your `private-build-plans.toml`, if present:
https://github.com/breucode/Iosevka-Breucode/blob/c42aad7289fce1cb28c82a2127e41b9f07afafab/private-build-plans.toml

Thanks btw for your great font and the amazing build system.

**Comment by breucode** [comment]
I just saw, that this also happens for the ligation `connected-hyphen-as-solid-line`

**Comment by be5invis** [comment]
Well, the second part is designed to overlap over the first one. Otherwise you might see "gaps" between them.
