### ISSUE TITLE
U+2060 Word Joiner displays incorrectly in kitty

### ISSUE THREAD

**Issue by sersorrel** [be5invis/Iosevka#1362]
In the kitty terminal, U+2060 Word Joiner makes the preceding character and subsequent characters until a space disappear. For example:
![image](https://user-images.githubusercontent.com/9433472/171208188-422a802b-56ab-49db-9593-6a57b9e01242.png)

This is reproducible on a friend's Mac, with a newer version of Iosevka:
![image](https://user-images.githubusercontent.com/9433472/171311713-b68ffc6d-809f-46ee-9da5-59dc6a4e670a.png)

If the word joiner is at the very start of the line, it seems to render ok.

I initially [thought](https://github.com/kovidgoyal/kitty/issues/5153) this was a problem in kitty, since I couldn't reproduce it in other terminals, but was told to report it here.

---

* Your font version: 11.0.1, 15.4.0
* Your font variant: unsure?, SS14
* Your operating system (name and version): NixOS 21.11, macOS 12.3
* Your application using Iosevka: kitty 0.24.0

**Comment by be5invis** [comment]
Iosevka doesn't support WJ at all. Please file an issue to Kitty.
Resolve as external.
