### ISSUE TITLE
Ligatures are broken in vscode

### ISSUE THREAD

**Issue by nightire** [be5invis/Iosevka#1364]
With the below settings in VSCode (version 1.67.2):

```json
{
  "editor.fontFamily": "Iosevka SS15, Sarasa Mono SC",
  "editor.fontLigatures": true,
}
```

all ligatures are broken, for example, this:

<img width="620" alt="image" src="https://user-images.githubusercontent.com/1104018/172563736-4e5ad49b-b04d-4018-a301-9b86c3a14da9.png">

should be: 

```ts
const sizes = this.propotions.map((propotion) => availableSize * proportion)
```

and this:

<img width="281" alt="image" src="https://user-images.githubusercontent.com/1104018/172563995-9ce90777-8430-4b6a-8a61-97053916f5b3.png">

should be:

```ts
if (typeof pane !== 'undefined') {
```

and this:

<img width="215" alt="image" src="https://user-images.githubusercontent.com/1104018/172564127-9da876fc-0c31-4561-acc0-e7411f1a698e.png">

should be: 

```ts
// console.log(engine);
// console.table(event);
```

---

* Your font version: 15.5.0
* Your font variant: tested on Iosevka SS05/SS08/SS09/SS14/SS15/SS17, others are not tested
* Your operating system (name and version): macOS Monterey 12.4
* Your application using Iosevka: Visual Studio Code

**Comment by alexeyten** [comment]
Have you restarted VS code?

**Comment by nightire** [comment]
> Have you restarted VS code?

You're right, and I didn't! I have executed the command: `Developer: reload window`, but turns out it's not the same as restarting the application.

Now it works as expected, thank you!
