### ISSUE TITLE
Ioveska Aile - indistinguishable upper case i and lower case L

### ISSUE THREAD

**Issue by TimGord** [be5invis/Iosevka#1367]
*Ioveska Aile* is almost perfect for people like me who code using a proportional font -- thank you.

There is one problem with it though, which is that upper case i (`I`) and lower case L (`l`) are indistinguishable: 
![current els](https://user-images.githubusercontent.com/13700667/173902656-e62559f2-0d78-4d2f-ab88-090c2cdb7a68.png)

**Please would it be possible to create a variant of *Ioveska Aile* with**
**(a) serifs on the capital i, and**
**(b) a bent terminal / tail at the bottom of the lowercase l?**

Something like this:
![els](https://user-images.githubusercontent.com/13700667/173902817-6246791a-1ddc-4bae-8eb7-81cef5b96cd3.png)

### Justification

1. People do use proportional fonts for coding -- see e.g. [here](https://storck.io/posts/proportional-programming-code-fonts/) and [here](https://news.ycombinator.com/item?id=4623781).

2. Multiple modern proportional sans serif fonts do at least one of (a) or (b):
    - [The proportional version of Go's own font](https://go.dev/blog/go-fonts) -- does (a) *and* (b)
    - [Linotype is updating its own fonts to address this issue](https://www.linotype.com/6990/din-1450.html) in line with [DIN 1450](https://www.en-standard.eu/din-1450-lettering-legibility/)
    - [The BBC's new sans serif font](https://www.bbc.co.uk/gel/articles/introducing-bbc-reith), which was designed 'to improve legibility'
    - [Andika](https://fonts.google.com/?query=Andika&preview.text=Il1&preview.text_type=custom)
    - [Noto Sans](https://fonts.google.com/?query=noto+sans&preview.text=Il1&preview.text_type=custom)
    - [Fira Sans](https://fonts.google.com/?query=Fira+Sans&preview.text=Il1&preview.text_type=custom) / [FiraGO](https://github.com/bBoxType/FiraGO)
    - [Public Sans](https://fonts.google.com/?query=public+sans&preview.text=Il1&preview.text_type=custom)

Cheers

**Comment by be5invis** [comment]
Resolve as dupe & by design. You **can** build your own distinguishing version, but for (the pre-built) Aile it is mostly for preparing docs.
