### ISSUE TITLE
Character Variants for `и`

### ISSUE THREAD

**Issue by P03T-life** [be5invis/Iosevka#1368]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [ ] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

There's only 1 style for italic `и` which is like `u = 'tailed'`:
![image](https://user-images.githubusercontent.com/43498546/174032962-51da5a81-f414-42a4-9d6a-07a52e372351.png)

**Comment by be5invis** [comment]
For Italic `и` we have 5 variants:
![image](https://user-images.githubusercontent.com/240091/174344799-0daa18c8-09c5-4d10-b6a9-ffa3a093184b.png)

**Comment by be5invis** [comment]
@P03T-life
For custom build -- enable a variant under `u`.
For OT -- use `cv45`.
