### ISSUE TITLE
Extra pixel in arrow =>

### ISSUE THREAD

**Issue by ilajosmanov** [be5invis/Iosevka#1369]
Thanks for Iosevka. This is the favorite font for me! I migrated from PragmataPro to your font. Let me share my small feedback:
---

* Your font version: 15.5.1
* Your font variant: SS12
* Your operating system (name and version): MacOS
* Your application using Iosevka:  VSCode

Looks like arrow has one extra pixel. Sometimes i think that arrow is disproportionate. What do you think?
<img width="416" alt="Знімок екрана 2022-06-20 о 00 38 33" src="https://user-images.githubusercontent.com/18512404/174502974-5d9c887d-7485-4f49-942b-c081e9715e16.png">

**Comment by be5invis** [comment]
Maybe you can try the unhinted version which _may_ look better. Again, this is not something that I control.
