### ISSUE TITLE
BLACK HOURGLASS U+29D7 in Miscellaneous Mathematical Symbols B

### ISSUE THREAD

**Issue by osdlman** [be5invis/Iosevka#1370]
- The requested character is...
  - [ ] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [x] Symbol
- [ ] Some other monospace/programming fonts supported this character. Provide images below.

![image](https://user-images.githubusercontent.com/19184912/174953339-9577cb50-9e5b-4b4b-82b7-39acffd592d0.png)

------

This character is used in the output of `commitlint`. When I use this output in documentation I need to configure a special fallback font just for this symbol.

### Example for commitlint

```
❯ "ops(git): improved." | commitlint
⧗   input: ops(git): improved.
✖   subject may not end with full stop [subject-full-stop]
✖   type must be one of [build, chore, ci, docs, feat, fix, perf, refactor, revert, style, test] [type-enum]
⚠   scope must be one of [server, client, AIS, EAI, OMD, PLD] [scope-enum]

✖   found 2 problems, 1 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
```

**Comment by be5invis** [comment]
We have to note that this symbol is a mathematical operator, so it follows math op's dimensions (that is, being narrow).
