### ISSUE TITLE
[Feature Request] Add Import functionality to the Web Iosevka Customizer

### ISSUE THREAD

**Issue by AZMCode** [be5invis/Iosevka#1371]
**Is your feature request related to a problem? Please describe.**
Every now and again, I find myself wishing to slightly customize my Iosevka custom build font, but I cannot use the Customizer again, unless I build it from scratch. This leaves me to find the documentation for the TOML build plan, and edit it manually.

**Describe the solution you'd like**
It'd be nice if the Customizer page allowed you to import a previous build plan and customize it further from there.

**Describe alternatives you've considered**
A standalone app? Not doing it at all? I don't think there are many alternatives to this idea TBH.

**Comment by AndydeCleyre** [comment]
FWIW I have set up a [fork-able repo](https://github.com/andydecleyre/archbuilder_iosevka) with instructions for having GitHub Actions build your variant, and you can either use the yaml file to generate the toml or an already configured toml file directly.

**Comment by be5invis** [comment]
Done.
