### ISSUE TITLE
Plus sign looks misaligned with minus sign

### ISSUE THREAD

**Issue by TsavyPrince** [be5invis/Iosevka#1374]
![image](https://user-images.githubusercontent.com/18726931/177211652-9e4db337-e94f-4018-9600-ba5087e811a6.png)
"+" and "++" don't line up with "-" but I would like them to be lined up.
I'm not sure if this counts as a character variant request or a bug report, since the degree of misalignment seems to be dependent on the font size.

**Comment by be5invis** [comment]
Rounding is not something that I can control. You can try the "unhinted" version which _may_ look better.
