### ISSUE TITLE
How to specify certain character variants (cv) in VS Code?

### ISSUE THREAD

**Issue by lethefrost** [be5invis/Iosevka#1376]
Hi, I am sorry for the stupid question, but I just could not find the answer from the internet after googling for a long time. 

If I have downloaded an arbitrary released stylistic set, but I want to specify some certain character variants when I use `Iosevka` in my editor (mainly Visual Studio Code), how could I do that? In the README file of `Iosevka` it says:

> ### Character Variants
> Alongside stylistic sets, Monospace Iosevka can also be configured to cherry-pick variants for each character using OpenType. The variants are shown below. To enable, assign the feature tag to the variant index. For example, setting `cv26` to `6` will enable single-storey `a`.
> 
> **Caution** : Certain software may limit the quantity of OpenType features and drop some of them if the feature list is too long. Please validate your feature configuration to ensure that it worked in your software.

And I found [here](https://github.com/microsoft/vscode/issues/10435), VSC finally became able to configure `OpenType font feature`, by the setting `"editor.fontLigatures": "'ss01', 'ss02', 'ss03', 'ss04', 'ss05', 'ss06', 'zero', 'onum'"`. It works for other fonts like [Cascadia Code](https://github.com/microsoft/cascadia-code), for example, I could set `"editor.fontLigatures": "'calt', 'ss01'"` to specify the usage of their alternative glyph sets, but how could I set, for example, `CV71` to `4` so that `Iosevka` has a dot inside glyph `0`, according to [this](https://github.com/be5invis/Iosevka/blob/master/doc/character-variants.md) table?

Thank you so much for creating this.

**Comment by be5invis** [comment]
`"editor.fontLigatures": "'cv01' 1, 'cv02' 2, ..."`

**Comment by be5invis** [comment]
But note that: Harfbuzz (the thing Chromium used to interpret OT features) have bugs that doesn't support too "long" feature list, so be careful.

**Comment by lethefrost** [comment]
> `"editor.fontLigatures": "'cv01' 1, 'cv02' 2, ..."`

> But note that: Harfbuzz (the thing Chromium used to interpret OT features) have bugs that doesn't support too "long" feature list, so be careful.

@be5invis Thank you so much for clarifying! Would you consider putting this instruction into the README file so that maybe people like me would not be confused about the usage anymore?

**Comment by be5invis** [comment]
In the [website](https://typeof.net/Iosevka/) there's already an **interactive** section that shows how to use CV/SS in CSS.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/178157041-7afc0bd4-eba5-4ffd-833c-fe3205957ffb.png)

**Comment by sh1boot** [comment]
I had the same question about something that was not CSS-based, but eventually I figured it out for myself.

I don't know if it's worth documenting as a part of this project, but since Google brought me here I'll just paste what [I think] I have figured out:

~/.config/fontconfig/fonts.conf (this works on foot, not sure what else):
```xml
    <match target="pattern">
         <test name="family" compare="contains"><string>Iosevka</string></test>
         <edit name="fontfeatures" mode="append">
             <string>cv96=8</string>
             <string>THND</string>
         </edit>
     </match>
```

~/.config/foot/foot.ini:
```
font=Iosevka Term:size=10:fontfeatures=cv96=8,THND
```
(don't expect `THND` to do anything in foot)

~/.config/kitty/kitty.conf
```
font_features Iosevka-Term cv96=8 +THND
```

Are these actually right?  I don't know.  They seem to work with limited testing, but there may be nuance.
