### ISSUE TITLE
Validation fails when installing "Super TTC" on macOS

### ISSUE THREAD

**Issue by GarrettAlbright** [be5invis/Iosevka#1377]
After downloading "super-ttc-iosevka-15.5.2.zip" and opening the resulting file in Font Book, three font windows open. When clicking one of the windows' Install Font buttons, FontBook attempts to validate the font, then shows this vague error message:

![Screen Shot 2022-07-13 at 16 00 55](https://user-images.githubusercontent.com/324483/178845063-38566b7b-a7d1-48bf-b156-621247da4d01.png)

I was not brave enough to try checking the box and installing the font anyway. Installing the non-super TTC version worked without issue.

---

* Your font version: 15.5.2
* Your font variant: (any)
* Your operating system (name and version): macOS 12.4
* Your application using Iosevka: n/a

**Comment by marchukov** [comment]
I am getting the same error for super-ttc-iosevka-15.6.0.zip. It is not clear what's wrong as all the errors messages are without specifics.

**Comment by be5invis** [comment]
I have no idea... Maybe Apple dislikes TTCs with too many instances?
Normal TTC being valid means that the fonts' structure aren't broken.

**Comment by julian45** [comment]
This problem is still present in the Super TTC single file for 16.3.6 (the first available asset [here](https://github.com/be5invis/Iosevka/releases/tag/v16.3.6)), so this issue should remain open.

**Comment by GarrettAlbright** [comment]
I decided to give it a try since I've recently updated to macOS 13.0 (Ventura). Font Book opens the font, but only one window this time, and the validator spinner at the bottom spins. And then… the "your system has run out of memory" box shows. None of the apps in the box seemed to be taking up much memory, but I quickly found the culprit:

![Screenshot 2022-11-11 at 13 17 02](https://user-images.githubusercontent.com/324483/201425226-a023a25b-8329-4f45-b6d8-320730b84646.png)

(I'm on a mini with 8 GB).

Force quitting Font Book didn't actually kill this process; I had to do `pkill -9 FontValidator` in the terminal to get my memory back.

macOS just really does not want us to use that file. :D

**Comment by Connorelsea** [comment]
@GarrettAlbright Thank you for the tip to pkill the process, I was so confused after I attempted and failed to install these fonts and found the Font Validator using an impressive 60+ gb of memory. I am on macOS Monterrey and am having the same validation failure issues.

<img width="438" alt="image" src="https://user-images.githubusercontent.com/1844458/202586049-f60c31e3-4351-4513-baf9-e109b498efea.png">

**Comment by thatbeautifuldream** [comment]
Any fixes seem to work? Was trying to install on Ventura.

**Comment by be5invis** [comment]
There's no useful information about where is wrong... Considering super TTCs are just normal TTCs bundled further together, you can use the alternative formats when needed.

**Comment by thatbeautifuldream** [comment]
Yes thank you @be5invis the others work just fine on the system.

[ttf-iosevka-16.5.0.zip](https://github.com/be5invis/Iosevka/releases/download/v16.5.0/ttf-iosevka-16.5.0.zip)

![Screenshot 2022-11-27 at 9 29 24 AM](https://user-images.githubusercontent.com/28717686/204118639-78a7f075-2f74-4e65-81aa-d61cec6e126a.png)

**Comment by julian45** [comment]
Also, a workaround: if you simply take the super TTC file and manually move it into `~/Library/Fonts`, all of the variants included in that file will show up in your app of choice (e.g., Word), and the next time you open Font Book, they show up in there as well. All told, a slightly annoying manual fix, but not too big of a deal for me to replace a single file every so often.

**Comment by thatbeautifuldream** [comment]
Oh great that seems to work too, thanks for the tip @julian45 ! Did not face the issue on Windows and Linux. But the tip just works like a charm!

**Comment by h4x0rlol** [comment]
Out of memory on Sonoma 14.0 and 27.2.0 font ver

**Comment by thatbeautifuldream** [comment]
Try installing using Homebrew

@h4x0rlol 


```bash
brew tap homebrew/cask-fonts
brew install font-iosevka
```

> Out of memory on Sonoma 14.0 and 27.2.0 font ver
