### ISSUE TITLE
Shape of r in ss09 is not optimal

### ISSUE THREAD

**Issue by van-de-bugger** [be5invis/Iosevka#1378]
* Your font version: 15.5.2
* Your font variant: iosevka-fixed-ss09-regular.ttf
* Your operating system (name and version): Fedora Linux
* Your application using Iosevka: does not matter

Iosevka ss09 is intended to simulate Source Code Pro font, but shape of `r` letter is not optimal for this purpose:

Source Code Pro:
![SourceCodePro-Regular otf](https://user-images.githubusercontent.com/721164/179119925-34466db0-f93a-43e8-8f6b-b2ede78f3d3d.png)

iosevka-fixed-ss09-regular:
![iosevka-fixed-ss09-regular ttf](https://user-images.githubusercontent.com/721164/179120294-7831e75f-86f8-4875-a681-209346943f42.png)

Iosevka 'hookless' r is closer to Source Code Pro:
![iosevka-hard-sans-regular ttf](https://user-images.githubusercontent.com/721164/179120758-a5cf4781-e77c-435e-be8b-8d2933097bd0.png)

**Comment by be5invis** [comment]
Superscripts follow the base letter so there's no way to set their shape individually.
Resolve as by design.

**Comment by van-de-bugger** [comment]
Sorry, I do not understand. Why are you talking about superscripts?

I am talking about U+0072 LATIN SMALL LETTER R in Iosevka SS09. It seems the shape of r could be easily fixed by editing `params/variants.toml`:

    [composite.ss09.design]
    r = "hookless"

In such case Iosevka r will look like Source Code Pro r. How does it affect superscripts?

**Comment by be5invis** [comment]
Your screenshot looks like superscript (`ʳ` in particular)
