### ISSUE TITLE
Shape of w in ss09 is not optimal

### ISSUE THREAD

**Issue by van-de-bugger** [be5invis/Iosevka#1379]
* Your font version: 15.5.2
* Your font variant: iosevka-fixed-ss09-regular
* Your operating system (name and version): Fedora Linux
* Your application using Iosevka: does not matter

w in Source Code Pro:
![SourceCodePro-Regular otf](https://user-images.githubusercontent.com/721164/179121333-5b3dba58-31d3-4430-9610-c7f842628df7.png)

w in Iosevka ss09:
![iosevka-fixed-ss09-regular ttf](https://user-images.githubusercontent.com/721164/179121377-8078cf28-2747-4106-a9af-6f5452446d63.png)

Iosevka 'straight-flat-top' w is closer to Source Code Pro:
![iosevka-hard-sans-regular ttf](https://user-images.githubusercontent.com/721164/179121463-186d0f73-b1ec-44d0-ae13-3b7931a9aaa8.png)

**Comment by be5invis** [comment]
Superscripts follow the base letter so there's no way to set their shape individually.
Resolve as by design.
