### ISSUE TITLE
Cyrillic Hard Sign, Soft Sign and Yeru letters in quasi-proportional fonts

### ISSUE THREAD

**Issue by van-de-bugger** [be5invis/Iosevka#1382]
Iosevka 15.5.2.

This is not a bug, and not a request for a new variant. It is a propose for adjusting shapes of Cyrillic Hard Sign, Soft Sign and Yeru letters: Ъ, Ь, Ы (ъ, ь, ы). (Cyrillic Be and Cyrillic Ve on screenshot are just compare their shapes with Hard Sign, Soft Sing and Yeru.)

Let's consider glyphs of Soft Sign, Hard Sign and Yeru in several proportional fonts:

Arimo:
![Arimo-Regular ttf](https://user-images.githubusercontent.com/721164/179320354-a55469e1-29e4-4eec-8e4a-5b5d7159bdcf.png)
Carlito:
![Carlito-Regular ttf](https://user-images.githubusercontent.com/721164/179320363-aa77fcb1-116b-41b8-a5b4-09260fad1174.png)
DejaVu Sans:
![DejaVuSans ttf](https://user-images.githubusercontent.com/721164/179320401-a27d0afe-66b0-4d67-bb63-4bc7bb11881c.png)
Droid Sans:
![DroidSans ttf](https://user-images.githubusercontent.com/721164/179320410-73cc2bcc-5b9e-45e7-8ccf-d6fdd6a086d3.png)
Liberation Sans:
![LiberationSans-Regular ttf](https://user-images.githubusercontent.com/721164/179320472-8ed24b2f-709f-404c-86fe-c7e998ca89bf.png)
Roboto:
![Roboto-Regular ttf](https://user-images.githubusercontent.com/721164/179320486-17bedca4-b108-405b-a868-3c15fdbf4151.png)

Note:

1. In each font these letters share the base shape of Soft Sign; Hard Sign just adds tail, Yeru adds vertical stroke, but base shape remains exactly the same:
![shaoe](https://user-images.githubusercontent.com/721164/179318028-44bdf8a4-607f-418f-913d-9c4688a632ad.png)
2. In each font the distance between parts of Yeru is very close to the width of the vertical stroke.
![dist](https://user-images.githubusercontent.com/721164/179313927-a21dec06-f934-46ba-ad88-4197009b9088.png)

That's not true for Iosevka Aile:
![iosevka-prop-sans-regular ttf](https://user-images.githubusercontent.com/721164/179321206-e036bdfb-adcd-4e6d-b439-ae3aa71fea4e.png)
1. Soft Sign is wider than Hard Sign and Yeru:
![ios-shape](https://user-images.githubusercontent.com/721164/179318829-cf9a6c80-cc5d-40fe-8881-be8956f244c5.png)
2. Distance between parts of Yeru noticeable larger than widths of vertical stroke.

My proposal for Iosevka Aile (and Etoile too):
1. Make Capital Hard Sign and Capital Yeru wider to match Capital Soft Sign,
2. Make Small Soft Sign narrower to match Small Hard Sign and Small Yeru 
(to my eye Small Soft Sign looks too wide, however, someone may say that current Small Soft Sign shape matches shape of Small Be, so instead of narrowing Small Soft Sign it would be better to widen Small Hard Sign and Small Yeru), and
3. Adjust the distance between Yeru parts (both capital and small).

![ios-proposal](https://user-images.githubusercontent.com/721164/179323128-543f170c-c301-42fa-9a9a-4986740096e4.png)
(The first row: existing shapes; bottom row: proposed shapes, existing shapes are gray in background). 

Since Iosevka Aile and Etoile are (quasi-)proportional fonts, I guess the fix will not cause any troubles.

**Comment by be5invis** [comment]
Making the YERI parts _exactly_ the same might be problematic (especialy considering that quasi-proportional has a _modular_ width model). I can make them _visually_ look closer:

![image](https://user-images.githubusercontent.com/240091/179339359-4b97fbf1-1c35-4eb3-bb6e-5d579f478ac1.png)

**Comment by van-de-bugger** [comment]
Thanks, now these letters look *much* better.
