### ISSUE TITLE
I also cannot build a custom Iosevka font that has worked fine previously

### ISSUE THREAD

**Issue by frankspace** [be5invis/Iosevka#1383]
I am on Artix linux (basically Arch without systemd), trying to use a derivative of the ttf-iosvka-custom-git AUR package, which so far has worked perfectly well.  However, with the update to 15.6.0, compilation fails (even in a clean chroot) with the following repeated a vast number of times:

```
[ERROR] Target Error Error: Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/build/ttf-iosevka-sans-ss10-git/src/Iosevka/font-src/index' imported from /build/ttf-iosevka-sans-ss10-git/src/Iosevka/node_modules/verda/lib/actions/nodejs/nodejs-call-process.js
Did you mean to import /build/ttf-iosevka-sans-ss10-git/src/Iosevka/font-src/index.js?
    at new NodeError (node:internal/errors:387:5)
    at finalizeResolution (node:internal/modules/esm/resolve:404:11)
    at moduleResolve (node:internal/modules/esm/resolve:965:10)
    at defaultResolve (node:internal/modules/esm/resolve:1173:11)
    at nextResolve (node:internal/modules/esm/loader:173:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:852:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:439:18)
    at ESMLoader.import (node:internal/modules/esm/loader:536:22)
    at importModuleDynamically (node:internal/modules/cjs/loader:1059:29)
    at importModuleDynamicallyWrapper (node:internal/vm/module:438:21) {
  code: 'ERR_MODULE_NOT_FOUND'
}
    at ChildProcess.<anonymous> (/build/ttf-iosevka-sans-ss10-git/src/Iosevka/node_modules/verda/lib/actions/nodejs/command.js:53:31)
    at ChildProcess.emit (node:events:513:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

I have nodejs version 18.6.0 installed.  As far as I can determine, I had nodejs version 18.3.0 installed at the time I last successfully built this package/custom font, which at the time would have been Iosevka version 15.5.2.  I haven't changed anything in my build recipe since that time.  I build from git.

Unfortunately, I don't have even the vaguest idea how to troubleshoot this.

Other requested information below:

Font version: 15.6.0, but pulled from git (i.e., `git clone --depth 50 --branch master 'https://github.com/be5invis/Iosevka'`)
Font variant: custom, but pretty much ss10
Operating system: Artix linux (rolling release, up to date)
Application using Iosevka: several of them
Node.js version: 18.6.0
"Params/paremeters.toml": to the best of my knowledge, I haven't tampered with this
"Build-plans.toml":  okay:

```
[buildPlans.iosevka-sans-ss10]
family = "Iosevka Sans ss10"
spacing = "quasi-proportional"
serifs = "sans"
no-cv-ss = false

  [buildPlans.iosevka-sans-ss10.variants]
  inherits = "ss10"

  [buildPlans.iosevka-sans-ss10.ligations]
  inherits = "dlig"

[buildPlans.iosevka-sans-ss10.weights.light]
shape = 300
menu = 300
css = 300

[buildPlans.iosevka-sans-ss10.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-sans-ss10.weights.medium]
shape = 500
menu = 500
css = 500

[buildPlans.iosevka-sans-ss10.weights.semibold]
shape = 600
menu = 600
css = 600

[buildPlans.iosevka-sans-ss10.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-sans-ss10.weights.heavy]
shape = 900
menu = 900
css = 900

[buildPlans.iosevka-sans-ss10.widths.normal]
shape = 625
menu = 5
css = "normal"
```
Detailed error log: see above, same error is output multiple times.

**Comment by be5invis** [comment]
You can try `dev`, where I moved everything to ESM and that should work properly

**Comment by frankspace** [comment]
Well, changing `git clone --depth 50 --branch master 'https://github.com/be5invis/Iosevka'` to `git clone --depth 50 --branch dev 'https://github.com/be5invis/Iosevka'` does seem to have worked.  If you please, though: what is "ESM" and what just happened here?

**Comment by be5invis** [comment]
I am doing some serious refactors so it might break building of existing versions...

**Comment by be5invis** [comment]
Resolve as fixed -- next release will have it fixed
