### ISSUE TITLE
Julia ligation subset

### ISSUE THREAD

**Issue by kauesena** [be5invis/Iosevka#1386]
It would be nice to have amongst the custom options on the website a ligations set for the Julia language.

**Comment by be5invis** [comment]
Do you have a list of these symbols used?

**Comment by VladWinner** [comment]
> Do you have a list of these symbols used?

I guess you can take it from here:
https://cormullion.github.io/pages/2020-07-26-JuliaMono/#contextual_and_stylistic_alternates_and_ligatures
