### ISSUE TITLE
Single underscore symbol (weight is inconsistent / mispositioned) with the double underscore ligature on different font size and font face

### ISSUE THREAD

**Issue by CodexLink** [be5invis/Iosevka#1389]
Extends the issue #1361.

The referred issue seems to be an isolated case from a certain terminal app, however, it does not. The following figures show that a certain font size shows that the weight (thickness) is inconsistent or mispositioned / misaligned between the single underscore and the double underscore ligature,

## Font Section Test in Windows GIF
This section shows the inconsistencies from a variety of font faces at a certain font size. Note that the first picture (top) has a spacing of **Normal** while the second one (bottom) has a spacing of **Terminal**. I just wanted to see if they have different results.

![font_test_normal](https://user-images.githubusercontent.com/5953927/180645017-d4813aa7-87af-4757-9052-dfee155de286.gif)
![font_test_term](https://user-images.githubusercontent.com/5953927/180645022-b3f2930d-c347-48e3-b4b2-3e021af9d3d8.gif)

> Upon checking, the issue starts at 8 to 19 points. 20 points beyond does not show any issues.

## Terminal Test
This section shows how it appears in terminal + demonstration.

![on_terminal](https://user-images.githubusercontent.com/5953927/180646219-5b6caf24-f090-4a64-b430-733dceca73d6.gif)
![WindowsTerminal_A34e3BVwKb](https://user-images.githubusercontent.com/5953927/180646261-837b52d2-994c-49cd-82ef-a55a9c14a5e4.png)
> This second picture was taken from my `nvim`.

## Other Application: Notepad
This section clears the assumption that the terminal may be the one at fault for misrendering the symbol, however, this also affects Notepad and other applications. Though, in applications like these, it was quite unnoticed until at a certain font size.

![on_notepad](https://user-images.githubusercontent.com/5953927/180646207-f1a24401-9005-46af-84cc-40d00dd33c31.gif)

## Closer Inspection
This section shows the inconsistency when zoomed in. **This does not adjust the font size over time.**

![closer_inspection](https://user-images.githubusercontent.com/5953927/180646169-7b805e9f-e0f2-426f-ba19-d25d4f17033f.gif)

> Upon checking #1360, this may be an offset issue than a weight inconsistency issue, though, in my GIF sample, it _feels_ like a weight issue.

What I have tried:
- Tried to explicitly state that the `underscore` must be on `low`, `high` and `above-baseline` and the bug still appears.

Additional notes:
- The font was built with the `iosevka-docker` given from the **building from source** section.
- The font I have is built as a `SuperTTC`, though I think this does not affect the output.
- The font was not patched with Nerd Font and Powerline Ligatures.

---
* Your font version: (Release or git, version): Fetched via Git, 15.6.1
* Your font variant: Pragmata Pro Style (SS08), Discretionary Ligatures (dlig), Sans Serif, and Standard (Normal + Extended)
* Your operating system (name and version): Windows 11, Version 21H2
* Your application using Iosevka: Terminal (Windows Terminal with pwsh (Powershell), and Essential Apps (ie. Notepad).
* Private Build Plans (if needed): https://github.com/CodexLink/dotfiles-configs-archive/blob/latest/font-recipe/private-build-plans.toml

**Comment by CodexLink** [comment]
I retried everything from scratch and it seems that I was able to get it right with `underscore` set to `high`. I just notice that whenever you override one of the design variants of a certain character, there will be an **indent** after the **variant**. I apologize for this issue.

![image](https://user-images.githubusercontent.com/5953927/181611207-62a6bbf2-8ad7-4afa-96e4-de689d17fa43.png)

**Comment by ribru17** [comment]
I am still experiencing this issue sadly, also Wezterm. Tried everything mentioned here and in the other issue.
