### ISSUE TITLE
Leading and #/hash mark/octothorpe request

### ISSUE THREAD

**Issue by nick-s-b** [be5invis/Iosevka#139]
* Your font version: git
* Your font variant: mostly zshaped
* Your operating system (name and version): Arch Linux with Xfce-terminal

I came across Iosevka today and immediately started building my own version and  spent some time customizing it. I'm a long-time PragmataPro user and that font has literally changed my happiness level when I am programming. I've used dozens of fonts in the past and was never happy with them until I found  PP. Iosevka fixes a lot of issues I've had with PragmataPro and I'm so happy to have come across Iosevka! I think it will be my next font because it's so customizable and looks great. I have two questions:

1. Is there a way to change leading? Spacing between the lines in Iosevka is about 15% larger than PragmataPro and I notice it on my laptop. I don't want to go a font size down because my eyes would hate me so I'm hoping to set leading to be the same as PP.

2. I dislike Iosevka's # so much. It just renders like a blob of lines when anti-aliasing is set. PP's and Monospace's (font that ships with most Linux distros) has # that is rendered perfectly and looks so much better. It's so common in most of my source files (comments) yet it renders badly. Can we do something about it?

Thank you for reading and thank you for Iosevka! I love it.
Nick

PS: I'm also not happy with @ sign and think that PP renders it much better but I don't use it much so it doesn't bother me as much as #.

**Comment by be5invis** [comment]
1. Change the `leading` property in `parameters.toml`.
2. Consolidated into #140.
