### ISSUE TITLE
Raku ligation subset

### ISSUE THREAD

**Issue by habere-et-dispertire** [be5invis/Iosevka#1391]
Raku has [many operators](https://docs.raku.org/language/operators), and composing them provides even more. I think it could be an exemplary showcase and a considerable test bed.

Special attention may be required for set theory operators and other ASCII equivalent operators for Unicode glyphs.

**Comment by be5invis** [comment]
Hmm I think `dlig` should work well?

**Comment by be5invis** [comment]
Maybe Iosevka (under Raku ligation set) will be the first font that properly implements `!===` ligation as triple-line, while `!==` and `!=` as double-line?
![image](https://user-images.githubusercontent.com/240091/188302063-813e83b5-4c8b-46a5-ae3a-02417c43b8c4.png)

**Comment by habere-et-dispertire** [comment]
Is Iosevka able to handle raku's hyper operators or is my setup confused ?
No whitespace seems allowed inside them and they seem to merge with the interior operator:

~~~raku
 > my @foo = [1, 2, 3]; # OK
[1 2 3]

> @foo >>/=>> 2; # I see it split as >> /=> > instead of >> /= >>
[0.5 1 1.5]
~~~

1. https://docs.raku.org/language/operators.html#Hyper_operators

**Comment by be5invis** [comment]
@habere-et-dispertire I do not think this is very doable at font level.
