### ISSUE TITLE
cyrl-zhe/capital-cyrl-zhe=curly at small sizes

### ISSUE THREAD

**Issue by pv4** [be5invis/Iosevka#1392]
The new curly variant of {,capital-}cyrl-zhe is a great idea. But it's a little bit less recognizable/readable at small font sizes than the previous (now default, symmetric-connected) variant.

At the first (large) picture it can be seen that the {,capital-}cyrl-zhe symmetric-connected variant is
1. generally wider than the curly one,
2. has much wider waist causing more space between left/right legs/hands and the central leg/hand.

![final-compare-large](https://user-images.githubusercontent.com/2502094/182157784-750fd96a-0ee1-451c-8842-8cd2e3d408ac.gif)

These points make curly variant of {,capital-}cyrl-zhe less recognizable/readable than non-curly ones. Unlike other letters like latin e.g. u, v, k , where curly variant makes glyph "larger" by having it more space between different parts (stems?) of the glyph, so making it MORE recognizable/readable at small font sizes.

Here is how the same text looks at small font size including 4x magnification:
![final-compare-small](https://user-images.githubusercontent.com/2502094/182157796-995a9f92-0db7-4758-a91b-121301e8febb.gif)

Notice that the vertically-central part of curly {,capital-}cyrl-zhe looks like a black blot, while symmetric-connected can be distinguished much better at this line.

Is it possible to improve the curly variant somehow please so it can be better recognizable/readable?

My thoughs (painted in GIMP) how this could be changed are presented below.

The first variant is to somehow make the waist wider.
The second variant is to make legs/hands more straight near the (bottom/top) ends and more curly at the center as if the curly part of the legs is "pulled up" while the curly part of the hands is "pulled down".

The final presented variant is NOT exactly what I'd like to get. It's just a demonstration of the direction where thoughts could go to get a better curly variant.

![final-howto](https://user-images.githubusercontent.com/2502094/182157799-7d798cba-77cc-4e6b-a12c-22d80958f9a6.png)

As always I trust you taste if you decide to fix this issue!

**Comment by pv4** [comment]
... or something closer to this:
![image](https://user-images.githubusercontent.com/2502094/182172099-d3ca6802-5ee1-4f91-bf5a-1c1be761cbad.png)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/183012332-8dc28f70-0f33-40d6-b4c4-481eb0ddf9de.png)
Changed to make it look like this

**Comment by pv4** [comment]
The total width (top and bottom) is still less in curly variant than in symmetric-connected one. Can you fix this too?

![compare-total-width](https://user-images.githubusercontent.com/2502094/183062359-c9e09870-6fb7-4212-bdf5-e4feba2d8585.gif)

**Comment by be5invis** [comment]
@pv4 fixed

**Comment by pv4** [comment]
@be5invis 

Not it's IDEAL. Thanks!
