### ISSUE TITLE
Build stalls indefinitely

### ISSUE THREAD

**Issue by winterqt** [be5invis/Iosevka#1394]
* Your font version: 15.6.3
* Your font variant: n/a
* Your operating system (name and version): macOS 12.5, Linux
* Your application using Iosevka: n/a

If you have problem when building Iosevka, please provide these information:

* Your Node.js version: 16.6.0
* The detailed error log:
```
$ npm run build -- ttf:iosevka
  ⡀⠀  | CPU:000% - RAM:000%⡀⠀ Complete 006 - Executing 8 - Pending 102 (05%) | CPU:000% - RAM:000%⠄⠀ Complete 072 - Executing 0 - Pending 114 (38%) | CPU:000% - RAM:000%⢂⠀ Complete 077 - Executing 8 - Pending 338 (18%) | CPU:000% - RAM:000%♦ Compile Script font-src/meta/macros.ptl
⡂⠀ Complete 077 - Executing 8 - Pending 338 (18%) | CPU:000% - RAM:000%♦ Compile Script font-src/meta/aesthetics.ptl
⡂⠀ Complete 077 - Executing 8 - Pending 338 (18%) | CPU:000% - RAM:000%♦ Compile Script font-src/meta/naming.ptl
⡂⠀ Complete 077 - Executing 8 - Pending 338 (18%) | CPU:000% - RAM:000%♦ Compile Script font-src/meta/unicode-knowledge.ptl
⡂⠀ Complete 077 - Executing 8 - Pending 338 (18%) | CPU:000% - RAM:000%♦ Compile Script font-src/otl/compat-ligature.ptl
⡂⠀ Complete 077 - Executing 8 - Pending 338 (18%) | CPU:000% - RAM:000%♦ Compile Script font-src/otl/gsub-ccmp.ptl
⡂⠀ Complete 077 - Executing 8 - Pending 338 (18%) | CPU:000% - RAM:000%♦ Compile Script font-src/otl/gpos-mark-mkmk.ptl
⡂⠀ Complete 077 - Executing 8 - Pending 338 (18%) | CPU:000% - RAM:000%♦ Compile Script font-src/otl/gsub-cv-ss.ptl
```

This stalls here for over an hour, with no completion in sight. I and others can reproduce this across Linux and macOS. See https://github.com/NixOS/nixpkgs/issues/185633 and https://github.com/NixOS/nixpkgs/pull/185824.

**Comment by be5invis** [comment]
Can you try this to get a verbose log?

```
npm run build -- --verbosity 9 ttf::iosevka
```

In addition I cannot reproduce this locally. Though I am on Node 16.15.

**Comment by be5invis** [comment]
Also tried to build on Ubuntu VM with Node 16.16. No hangs observed.

**Comment by winterqt** [comment]
> I suspect some `node_modules` dependency are broken in your environment?

Yes, that was the issue, see https://github.com/NixOS/nixpkgs/pull/185824#issuecomment-1211420220.

Even when running with verbosity cranked up, I feel like it would be good (if possible) to throw an error at some point, rather than the build stall indefinitely at

```
⡀⠀  | CPU:000% - RAM:000%⡀⠀ Complete 006 - Executing 8 - Pending 102 (05%) | CPU:000% - RAM:000%⠄⠀ Complete 072 - Executing 0 - Pending 114 (38%) | CPU:000% - RAM:000%⢂⠀ Complete 077 - Executing 8 - Pending 338 (18%) | CPU:000% - RAM:000%♦ Compile Script font-src/meta/macros.ptl
⡂⠀ Complete 077 - Executing 8 - Pending 338 (18%) | CPU:000% - RAM:000%♦ Compile Script font-src/meta/aesthetics.ptl
⡂⠀ Complete 077 - Executing 8 - Pending 338 (18%) | CPU:000% - RAM:000%♦ Compile Script font-src/meta/naming.ptl
⡂⠀ Complete 077 - Executing 8 - Pending 338 (18%) | CPU:000% - RAM:000%♦ Compile Script font-src/meta/unicode-knowledge.ptl
⡂⠀ Complete 077 - Executing 8 - Pending 338 (18%) | CPU:000% - RAM:000%♦ Compile Script font-src/otl/compat-ligature.ptl
⡂⠀ Complete 077 - Executing 8 - Pending 338 (18%) | CPU:000% - RAM:000%♦ Compile Script font-src/otl/gsub-ccmp.ptl
⡂⠀ Complete 077 - Executing 8 - Pending 338 (18%) | CPU:000% - RAM:000%♦ Compile Script font-src/otl/gpos-mark-mkmk.ptl
⡂⠀ Complete 077 - Executing 8 - Pending 338 (18%) | CPU:000% - RAM:000%♦ Compile Script font-src/otl/gsub-cv-ss.ptl
```

This already does happen in some scenarios, such as with v15.5.2 and updated Verda(?):

```
 Error: Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/private/tmp/nix-build-iosevka-15.5.2.drv-1/Iosevka-15.5.2/font-src/index' imported from /nix/store/s6myxyimwmrlsbwswvrcggz5qfm118r9-iosevka-15.5.2/lib/node_modules/iosevka/node_modules/verda/lib/actions/nodejs/nodejs-call-process.js
Did you mean to import /private/tmp/nix-build-iosevka-15.5.2.drv-1/Iosevka-15.5.2/font-src/index.js?
    at new NodeError (internal/errors.js:322:7)
    at finalizeResolution (internal/modules/esm/resolve.js:318:11)
    at moduleResolve (internal/modules/esm/resolve.js:776:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:887:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at Loader.import (internal/modules/esm/loader.js:177:28)
    at importModuleDynamically (internal/modules/cjs/loader.js:1028:27)
    at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:30:14)
    at process.<anonymous> (/nix/store/s6myxyimwmrlsbwswvrcggz5qfm118r9-iosevka-15.5.2/lib/node_modules/iosevka/node_modules/verda/lib/actions/nodejs/nodejs-call-process.js:17:52) {
  code: 'ERR_MODULE_NOT_FOUND'
}
    at ChildProcess.<anonymous> (/nix/store/s6myxyimwmrlsbwswvrcggz5qfm118r9-iosevka-15.5.2/lib/node_modules/iosevka/node_modules/verda/lib/actions/nodejs/command.js:53:31)
    at ChildProcess.emit (events.js:400:28)
    at emit (internal/child_process.js:935:14)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
```

**Comment by be5invis** [comment]
> Yes, that was the issue
Could you please elaborate? Is the dependency's version broken in _your_ environment caused this hang?
I cannot simply add a timeout to Iosevka's build script -- a full release will take hours to build!

**Comment by winterqt** [comment]
> Could you please elaborate? Is the dependency's version broken in _your_ environment caused this hang?

Correct -- to be more precise, I can reproduce this when using 15.5.2's dependencies with 15.6.3. (It was a mistake that the author of the linked PR made.)

> I cannot simply add a timeout to Iosevka's build script -- a full release will take hours to build!

How does this relate to what I said? I'm confused.

**Comment by be5invis** [comment]
> How does this relate to what I said? I'm confused.

Well, it looks like you are requesting me to add a watchdog so if the build runs too long, then kill it and throw errors...

> I can reproduce this when using 15.5.2's dependencies with 15.6.3.

That explains why -- I bumped Verda's version in 15.6 to support ESMs.
It looks like there are some problems related to the error handling when a `node` task's script cannot get found. I will investigate this later.

For this bug in particular, resolve as external and not repro.

**Comment by winterqt** [comment]
> Well, it looks like you are requesting me to add a watchdog so if the build runs too long, then kill it and throw errors...

Not at all. What I was suggesting is that this case *should* error, rather than hanging indefinitely when the scripts can't be run. Unless I misunderstand the issue?

> It looks like there are some problems related to the error handling when a `node` task's script cannot get found. I will investigate this later.

I assume this is what the solution to this would be. Feel free to comment here if you fix it and I'll be happy to test.
