### ISSUE TITLE
How can I bake a custom version of the "extended" variant?

### ISSUE THREAD

**Issue by aarav2you** [be5invis/Iosevka#1397]
Could not find an option in the [customizer](https://typeof.net/Iosevka/customizer) nor an option in the https://github.com/be5invis/Iosevka/blob/master/doc/custom-build.md.

I want to do cherry picking for this variant, how do I do so?
![image](https://user-images.githubusercontent.com/37036762/184354101-d2fa2eeb-6604-44f8-a0c7-66628f4b8e44.png)

Is quasi-proportional and this variant the same?

**Comment by be5invis** [comment]
By default Extended is built alongside "normal" width. If you want to make Extended the default, check this
![image](https://user-images.githubusercontent.com/240091/184463249-757f14ce-dec1-4cd6-8564-3c0b1ea611cd.png)

**Comment by iDad5** [comment]
I had the same problem, when I changed the Width Option in the configurator after I had made all the choices. When I started over and set the Width Option before I stared making my adjustments it worked for me.
