### ISSUE TITLE
no font available

### ISSUE THREAD

**Issue by mintty** [be5invis/Iosevka#14]
make: patel-c: Command not found
Your README lists a number of prerequisites to build this font, most quite exotic and not available on my system. This is not a useful way to propagate a font. What is the actual result of the build process - a .ttf file? Why don't you publish that?

**Comment by mintty** [comment]
OK, I see the release archives seem to contain ttf. I hadn't checked them because they are misleadingly called "Source code".

**Comment by be5invis** [comment]
Well Github names the content in `releases` branch "Source code". Perhaps I should upload a dedicated copy alongside the the existing link. Closed.
