### ISSUE TITLE
The inequality sign (!=) is TOO vertical

### ISSUE THREAD

**Issue by unbadfish** [be5invis/Iosevka#1400]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [ ] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.
![Pasted image 20220815105843](https://user-images.githubusercontent.com/61961263/184572986-af361640-86f7-427f-a5fb-03370352345b.png)

![Pasted image 20220815105857](https://user-images.githubusercontent.com/61961263/184573001-c29ac766-1686-4dcd-abb0-62e3f4cebedc.png)

------
![Pasted image 20220815110017](https://user-images.githubusercontent.com/61961263/184573007-034a56d0-7492-45a6-b5c7-c160217f5f14.png)

**The inequality sign (!=) in Iosevka is TOO vertical**, and looks like a TREE standing on the ground!
Please make it a bit more inclined.

![Pasted image 20220815112554](https://user-images.githubusercontent.com/61961263/184573013-c7e2119e-dda9-453a-9c5b-7fc19d5e05b1.png)

I think 55 degree (from horizon) in Jetbrains mono is ok.
But, as the Iosevka font is much thinner, I think 60 degree (from horizon) is acceptable too.

**Comment by unbadfish** [comment]
In my opinion, **at least in SS14**, the inequality sign (!=) should be more inclined.
By the way, what's task #_2 mean? does it means "*no other characters in Unicode that Iosevka currently supports* looks like the variant you requested"?  🤔

**Comment by be5invis** [comment]
@unbadfish That means your variant isn't ambiguous with existing characters.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/184590588-9f87ddbb-f2a5-4ac9-8e9f-10a1506d5860.png)
We now have -- different slopes controllable by a CV (`VXAF`).

![image](https://user-images.githubusercontent.com/240091/184590637-7234ae4b-cc0e-4827-9a0a-9506ee6b5d7a.png)
You can even get dots using this CV if the ligation is built from exclamation!
