### ISSUE TITLE
Character Request: U+279C (HEAVY ROUND-TIPPED RIGHTWARDS ARROW)

### ISSUE THREAD

**Issue by charbelnicolas** [be5invis/Iosevka#1401]
- The requested character is...
  - [ ] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [x] Symbol

- [x] Some other monospace/programming fonts supported this character. Provide images below.

DejaVu Sans Mono:
![dejavusansmono](https://user-images.githubusercontent.com/14960414/185631236-328cd7f6-0008-4912-9794-99c0b7483cb1.jpg)

Iosevka Fixed + Unifont:
![unifont](https://user-images.githubusercontent.com/14960414/185631383-a6402bb1-59b0-4ed3-859a-fe6881d3ebc3.jpg)

Iosevka Fixed:
![iosevkafixed](https://user-images.githubusercontent.com/14960414/185631461-5fbc6562-b1e7-4fc7-874a-88d961d21573.jpg)

------

Hello, this symbol is being used by VITE (https://vitejs.dev/) since a few weeks ago.... It would be nice to have the symbol in the Iosevka font itself instead of relying on other fonts.

If you do decide to add it, please don't make it a double width character, otherwise it will end up being cut off in terminals like XTerm.

![xterm](https://user-images.githubusercontent.com/14960414/185632208-6d0dd308-6d7e-4dd1-9bcd-42bc4e73daee.jpg)

Thank you!

**Comment by alexeyten** [comment]
> don't make it a double width character
You should use Iosevka Term or Iosevka Fixed in XTerm.
See https://github.com/be5invis/Iosevka/blob/master/doc/PACKAGE-LIST.md#prebuilt-packages

**Comment by charbelnicolas** [comment]
> > don't make it a double width character
> 
> You should use Iosevka Term or Iosevka Fixed in XTerm. See https://github.com/be5invis/Iosevka/blob/master/doc/PACKAGE-LIST.md#prebuilt-packages

I am already using the fixed version 😀

**Comment by be5invis** [comment]
This symbol follows the metrics of all the arrows we add in Iosevka: it is narrow in Term and Fixed, while wide in "normal" Iosevka.

**Comment by charbelnicolas** [comment]
![20220914_213820](https://user-images.githubusercontent.com/14960414/190300669-c3e83e6d-5fb6-495c-ba06-1e2488170290.png)

It looks great! Thank you!
