### ISSUE TITLE
'cv44' does not apply to all variants of ⟨t⟩

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#1405]
Some characters based on U+0074 LATIN SMALL LETTER T do not share all its 'cv44' variants. U+01AB, U+0236, U+0288, U+1DB5, and U+20A7 lack asymmetric crossbars. U+01AB, U+1DB5, and U+20A7 do not have tail variants. Here they are with 'cv44' set to 15.
![tƫȶʈᶵ₧](https://user-images.githubusercontent.com/1124347/186039442-35b61a66-121e-4ceb-89fd-c595c0bb54de.png)

---

* Your font version: 16.0.0
* Your font variant: Iosevka Slab Extended
* Your operating system: macOS 10.14.6
* Your application using Iosevka: hb-view

**Comment by be5invis** [comment]
(I am just wondering how did you find these?)

**Comment by dscorbett** [comment]
I scroll through the font in FontForge checking glyphs that seem susceptible to missing variants: those that are logically related to a base character but possibly not automatically derived from it.
