### ISSUE TITLE
"ß" has a very unusual shape

### ISSUE THREAD

**Issue by p-e-w** [be5invis/Iosevka#141]
(Iosevka 1.10.4)

The current design of the Eszett (`ß`) glyph is quite unusual for a modern typeface, to the point where I feel it disturbs the flow of reading text. It resembles a Fraktur `ß` and reminds me of decades-old street signs:

![](https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Berliner_Stra%C3%9Fe.JPG/320px-Berliner_Stra%C3%9Fe.JPG) ([Image source](https://commons.wikimedia.org/wiki/File:Berliner_Stra%C3%9Fe.JPG))

The following is now considered the "standard form" of `ß`, and is found in every other non-decorative font I've ever used:

![](https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Zeichen_220-20.svg/320px-Zeichen_220-20.svg.png) ([Image source](https://commons.wikimedia.org/wiki/File:Zeichen_220-20.svg))

This glyph form is also less dense and I believe would fit better with the rest of Iosevka.

**Comment by be5invis** [comment]
Merged into #140. Closed.

**Comment by be5invis** [comment]
Added (-> cv35). Traditional eszet is assigned into cv34.

**Comment by eiszfuchs** [comment]
D'oh! Is `cv34` default? I liked the ligature look, as it makes it easier to distinguish from the letter "B". Also, personal preference, that was the main reason I was hooked for Iosevka.

**Comment by be5invis** [comment]
@eiszfuchs You can make a custom build with `design=v-eszet-traditional`

**Comment by eiszfuchs** [comment]
I had issues compiling Iosevka when working on the *Braille* Pull request. For some reason, fonts appeared aliased and unhinted. 🤔

**Comment by be5invis** [comment]
@eiszfuchs The build script has been completely rewritten, no longer depends on FF.

**Comment by eiszfuchs** [comment]
*OOooOOOooo!* Gotta try that out. Thanks for the notice! 😍

**Comment by juarezr** [comment]
Yet another reference: [How to draw a Capital Sharp S](https://typography.guru/journal/how-to-draw-a-capital-sharp-s-r18).
