### ISSUE TITLE
Problem with kerning of arrow up glyph

### ISSUE THREAD

**Issue by oshytiko** [be5invis/Iosevka#1411]
Describe your problem here. Provide pictures and files if necessary.

I'm seeing this image when using `starship` in combination with `zsh` shell. I have tried basically all terminals and everywhere the picture is the same, arrow up is too close to closing bracket...

<img width="191" alt="image" src="https://user-images.githubusercontent.com/107051036/187235401-847077a9-1d32-406a-8db1-fb09e8b2374e.png">

That is happening only with normal variant. Fixed and Terminal are fine, but they are lacking ligatures. No other fonts like Hasklig, JetBrains Mono does not have such problem.

Could you please look at it, when you would have a time?

Many thanks in advance!

---

* Your font version: Version 16.0.2; ttfautohint (v1.8.4)
* Your font variant: Normal
* Your operating system (name and version): MacOS
* Your application using Iosevka: VSCode, Kitty

**Comment by oshytiko** [comment]
I think it's unicode character "Upwards Dashed Arrow" ⇡ (U+21E1).

**Comment by alexeyten** [comment]
Terminal variant (`Term`) *have* ligatures.

https://github.com/be5invis/Iosevka/blob/master/doc/PACKAGE-LIST.md#prebuilt-packages

**Comment by oshytiko** [comment]
Ok, then as a workaround I can switch to `Term`, but maybe you can point into right direction, how I can verify that there is no problem with ⇡ and it's how it supposed to be?

**Comment by alexeyten** [comment]
https://github.com/be5invis/Iosevka/blob/master/doc/PACKAGE-LIST.md#prebuilt-packages
> *Default*: The default variant with ligatures. Various symbols, like **arrows** and geometric, are **wide (2-column)**.

**Comment by oshytiko** [comment]
Thank you! Very much appreciated!

Maybe you can also share some insights why arrows became 2-column? I got upgraded from some earlier version of Iosevka, and it was fine there.

**Comment by alexeyten** [comment]
That was more than two years ago.
https://github.com/be5invis/Iosevka/releases/tag/v3.0.0

> [...]
> **3.0.0-rc.1**
> - The packaging and spacing is significantly changed:
>   - `Iosevka` → Kept, but made arrows and geometric symbols wide.
>   - `Iosevka Term` → `Iosevka Fixed`.
>   - `Iosevka TermLig` → `Iosevka Term`.
>
> [...]

**Comment by oshytiko** [comment]
I think I was on `1.3.0` or something... I really liked the way how early "impersonations" of PragmataPro were done. But then swapped my laptop :) 

Thank you again! Closing then!

**Comment by alexeyten** [comment]
Still there https://github.com/be5invis/Iosevka/releases/tag/v1.3.0

**Comment by be5invis** [comment]
@oshytiko If you want something that looks like Progmata Pro **AND** follows Terminal metrics, try “Iosevka Term Curly”.
