### ISSUE TITLE
Request for `</`, `/>`, `<>` and `</>` ligations

### ISSUE THREAD

**Issue by Aloso** [be5invis/Iosevka#1413]
- [x] A programming language requires this ligation. Provide the information below.
- [x] This ligation is implemented in other programming fonts. Provide samples below.

------

A `</` and `/>` ligation would be useful to have in HTML and XML documents, as well as JSX files. JSX files would also benefit from `<>` and `</>` ligations (`<></>` is a shortcut for `<Fragment></Fragment>`). The ligatures might also be useful for other programming languages that I'm not familiar with.

These ligatures are available in **Fira Code** and **JetBrains Mono**, and possibly more. Here's a comparison:

|  Iosevka (customized) | JetBrains Mono |
| --- | --- |
| ![Iosevka_Custom_lig](https://user-images.githubusercontent.com/15658558/189160811-1cda225b-537e-4159-a477-2c4b57c1e755.png) | ![Jetbrains_Mono_lig](https://user-images.githubusercontent.com/15658558/189160862-1cd70433-c6d7-45d5-8861-d073144e5412.png) |

I've gotten used to these ligatures and would like to have them in Iosevka as well.

**Comment by be5invis** [comment]
May need a special diamond for `<>` that doesn't "kern" inwards...
