### ISSUE TITLE
Get smaller file sizes to use as webfont

### ISSUE THREAD

**Issue by num-lock** [be5invis/Iosevka#1414]
Hi, I found the issue #916 because I face the same problem.

As suggested I tried subsetting the font (iosevka-regular.ttf) with `pyftsubset` to the latin subset **(*)** and converting it to woff2 in one go. The resulting file size is still 90kB. In comparison Roboto Mono for example is only 16kB and most other fonts targeted at web are in that range as well with some going up to high 30s of kBs when subsetting them to just the latin character set.

Are there any other steps one could use to reduce the size and make it more attractive as a webfont?

**(*)** Commonly used Unicode range is `U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+2000-206F,U+2074,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD` for anyone interested.

**Comment by be5invis** [comment]
You can try build a version without `cv##`/`ss##` and ligations (then subset), which will _massively_ reduce the file size.

`cv##`/`ss##` introduces many variant glyphs, and `pyftsubset` keeps them.

**Comment by num-lock** [comment]
Ditching _all_ layout features and subsetting to latin gives a size of around 19kB as woff2. Subsetting further to just ANSI (`U+0000-00FF`) ends up almost exactly at 15kB, which should suffice at least for 99% of my use cases, which is displaying simple code snippets.

I haven't done any actual visual testing yet to see if dropping all layout features cause any bogus but I am pretty confident it shouldn't, at least for a monospaced font mainly used to display code.

@be5invis Thanks again for the hint. I'll consider this mission accomplished for now.

**Comment by shot-codes** [comment]
@num-lock Mind sharing your build plans? The best I'm managing is 40kb with the setup below, 49kb if I include the full set up common unicode you provided above.

```toml
[buildPlans.iosevka-web]
family = "Iosevka Web"
spacing = "normal"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

[buildPlans.iosevka-web.weights.regular]
shape = 400
menu = 400
css = 400
```
`--unicodes=U+0000-00FF`
