### ISSUE TITLE
Bigger heads for fat arrow ligatures

### ISSUE THREAD

**Issue by johnw42** [be5invis/Iosevka#1416]
I'd like a different version of the fat arrow ligatures because I find the ones in Iosevka don't look enough like arrows in small sizes, making them hard to read.

Here's what Iosevka has now:
 ![image](https://user-images.githubusercontent.com/201923/190526043-9fbf7748-a8b5-4ee0-91ad-8627be7a49ac.png)

Here it is with ligatures turned off, which I find quite a bit easier to read than the ligature because the arrowhead is more distinct:
![image](https://user-images.githubusercontent.com/201923/190526162-5f7552a8-e2fd-4289-9f6d-409c8ab5597d.png)

Here's how some other fonts render a fat arrow:
![image](https://user-images.githubusercontent.com/201923/190525839-265440b9-4ab2-474d-86ce-69f3d50d95b2.png) Fira Code
![image](https://user-images.githubusercontent.com/201923/190525909-77247c79-f486-4b84-bbff-e094b234ac39.png) JetBrains Mono
![image](https://user-images.githubusercontent.com/201923/190525948-2048d6f8-782e-41e2-94bd-b9ca48897c7e.png) Cascadia Code
![image](https://user-images.githubusercontent.com/201923/190526319-a7aad25d-57b4-4ca2-b3cf-9496e258781c.png) Monoid

I'd be happy to create the alternate versions myself, but I haven't worked on fonts in a long time so I could use a recommendation of a good program to use.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/190832854-c7399a34-a1bc-4adb-b6fc-22fbf93e1013.png)
Actually, the arrow heads share the same dimension with inequality sign.

**Comment by johnw42** [comment]
I still find it harder to read than any of the other fonts I mentioned. To me it looks more like a small arrow with a heavy black outline than a proper fat arrow.
