### ISSUE TITLE
Extended with weight in VSCode

### ISSUE THREAD

**Issue by JameEnder** [be5invis/Iosevka#1417]
Hi, I want to use Iosevka Extended with weight inside VSCode.
First issue is that inside VSCode, Iosevka Extended is indeed called Iosevka Expanded.
How do I also combine it with weight styles?
I've tried:
Iosevka Expanded Semibold
Iosevka Semibold Expanded

Neither work.

---

* Your font version: (Release or git, version) 16.2.0
* Your font variant: Extended
* Your operating system (name and version): Windows 10
* Your application using Iosevka: VSCode

**Comment by be5invis** [comment]
VSCode doesn't support font width **at all**. There's a bug in their repo I think but I cannot find that.
Resolve as external.
