### ISSUE TITLE
Iosevka Term SS09 looks like a different font since 16.0.2

### ISSUE THREAD

**Issue by step-** [be5invis/Iosevka#1419]
Iosevka Term SS09 16.0.2 looks different from what this variant used to look. Numbers, particularly 1 and 0, are telling but g and i and other letters. I traced the change back to version 16.0.2. You can see some differences introduced since version 16.0.2 by comparing the "Term SS09" sections of the package list documents  as can be seen in the following screen captures:

[package list 16.0.1](https://github.com/be5invis/Iosevka/blob/v16.0.1/doc/PACKAGE-LIST.md) looks good as each previous release:

![iosevka-term-ss09-16 0 1](https://user-images.githubusercontent.com/1414102/190724210-e5dbcc59-2e77-4ba2-9d40-e37ed8eb33a9.png)

vs. [package list 16.0.2](https://github.com/be5invis/Iosevka/blob/v16.0.2/doc/PACKAGE-LIST.md) looks different - letters and numbers, 1 and 0 quite ugly...

![iosevka-term-ss09-16 0 2](https://user-images.githubusercontent.com/1414102/190724237-ccfaa74f-e1fc-4628-b75c-838fbd0d9eb7.png)

I downgraded back to 16.0.1 as a work-around.  Thanks.
---

* Your font version: 16.0.2 -- 16.2.0
* Your font variant: SS09
* Your operating system: Linux
* Your application using Iosevka: xterm, urvxt, vim, gvim

**Comment by be5invis** [comment]
The old picture is broken (the font files are correct -- just pictures aren't)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/190832746-7719e1c2-5ba0-4e9d-8788-f612a304d00a.png)
This is what it supposed to look like.
Resolve as not-a-bug.

**Comment by step-** [comment]
> This is what it supposed to look like.

I see. Indeed the font looked like that in my terminal when I upgraded from 3.4.3 to 16.2.0.  However, I still think there's been a big change in the look of Term SS09 somewhere along the chain of releases. Before upgrading to 16.2.0 I was using 3.4.3 TTF - which is now installed in my system. Take a look at what I see.

![iosevka-20220917](https://user-images.githubusercontent.com/1414102/190843281-bbe11e32-7fbf-4418-87a6-68551c76ea08.png)

The very bottom line shows the command I used to start urxvt.  The lines above sit in the urxvt terminal I just started. The purple line is italics font. The gray line is regular font.  You can see that the characters look like the picture I posted for 16.0.1, unlike the characters in the 16.0.2 picture.  In 2020 I had also saved the 3.4.3 font list PDF file, and the page for Term SS09 is attached.  You can see that the test characters look like the picture in 16.0.1, unlike the characters in 16.0.2.

[Release Iosevka, version 3.4.3.pdf](https://github.com/be5invis/Iosevka/files/9591071/Release.Iosevka.version.3.4.3.pdf)

Perhaps this change didn't happen between 16.0.1 and 16.0.2 as I thought.  When I upgraded to 16.2.0 [sic] the font in my terminal looked different from before.  I can think of three possible explanations: (a) I had installed the wrong font; (b) I had installed a TCC bundle, whereas earlier I had been using straight TTF 3.4.3, and maybe my system isn't properly configured for TCC; (c) the font changed indeed.  I feel I can rule out (a) because I only download Term SS09 TCC and TTF. I can't rule out (b) but I also tested TTF 16.2.0 and saw no improvement. So I filed this issue because I thought I had enough evidence of (c).
