### ISSUE TITLE
[EASY] [WEBSITE] Opentype features section broken!

### ISSUE THREAD

**Issue by sliceofcode** [be5invis/Iosevka#142]
The `height: 4.5em;` rule on these `li` elements are breaking them. Here is what the website looks like for me:

![20170115_084301_rao](https://cloud.githubusercontent.com/assets/4206232/21964330/bc6d80e8-dafe-11e6-93e0-f349aba1de63.png)

If I apply `height: 100%` instead:

![20170115_084249_mfj](https://cloud.githubusercontent.com/assets/4206232/21964333/c52fe82e-dafe-11e6-88bb-41b9f994b675.png)

Should I submit a patch?

**Comment by be5invis** [comment]
I'll increase the width of this column. They are DESIGNED to be one line. Closed.

**Comment by be5invis** [comment]
Added `white-space: nowrap`.
