### ISSUE TITLE
Iosevka's font version is shown as 18.0 in Windows Fonts

### ISSUE THREAD

**Issue by reregaga** [be5invis/Iosevka#1424]
Thank you for this great font!
I'm using the latest version of the Iosevka (16.2.0), but in Windows Fonts it version looks like a 18.0. Is this a bug?

![45](https://user-images.githubusercontent.com/76629445/192376888-dbbfa2cb-f98f-4558-98b7-048bcac1cbd4.jpg)

---

* Your font version: 16.2.0
* Your font variant: super-ttc-sgr-iosevka
* Your operating system (name and version): Windows 10

**Comment by lorenzogatti** [comment]
My custom-built Iosevka variants have the version number (matching) in the ttf files, in package.json and package-lock.json, and nowhere else.  
Inspecting sources (verdafile.mjs) confirms that the version number is extracted from package.json:

const Version = computed(`env::version`, async target => {
	const [pjf] = await target.need(sfu`package.json`);
	const pj = JSON.parse(await FS.promises.readFile(pjf.full, "utf-8"));
	return pj.version;
});

Are you sure you didn't modify your version number?

**Comment by reregaga** [comment]
@lorenzogatti, I just downloaded a `sgr-iosevka.tcc` file from the repository and installed it. Now I found this file on my computer, if I right click on it and select **Preview**, it shows the `16.2.0` version:
>![screenshot](https://user-images.githubusercontent.com/76629445/204095417-283c61e8-97e4-4d61-92f7-211c61a7a43c.png)

But in the Windows Fonts the version is different, I don't know if it's a problem with Windows or with the font file.
