### ISSUE TITLE
Artifacts in `==` ligature

### ISSUE THREAD

**Issue by rkiyanchuk** [be5invis/Iosevka#1425]
Ligatures for `==` and `===` have some kind of artifacts:

<img width="390" alt="Screen Shot 2022-09-28 at 14 58 08" src="https://user-images.githubusercontent.com/843725/192896392-4dbf660a-ebce-4245-8edc-496344712027.png">

While some other ligatures (like `==>`) involving repetition of `=` and `-` are fine.

I observe this issue in all apps I use for ligatures: iTerm, IntelliJ, VS Code.

---

* Your font version: 16.2.0
* Your font variant: Default
* Your operating system (name and version): MacOS 12.6
* Your application using Iosevka: iTerm and IDEs

**Comment by be5invis** [comment]
This is by design, to indicate how many equal signs are there in a chain.
Maybe worth adding a variant.

**Comment by rkiyanchuk** [comment]
@be5invis Thanks for the reply, is the bolding around the notches also expected (if you enlarge the screenshot you can see that some pixels around the notches protrude a bit weirdly). That's the part that looks a bit irritating to the eye.
