### ISSUE TITLE
Ogonek in Polish letter ę (U+0119 LATIN SMALL LETTER E WITH OGONEK) is not properly placed

### ISSUE THREAD

**Issue by raspy** [be5invis/Iosevka#1427]
Ogonek in Polish letter ę (U+0119 LATIN SMALL LETTER E WITH OGONEK) is not properly placed. This should be part of the letter as it was hand-written directly after writing e itself, so attached to the right part of the letter, not the middle of it. See https://www.twardoch.com/download/polishhowto/ogonek.html for quite complete explanation how it should and should not be. Most importantly:

> When ogonek is merged with lowercase e in order to create eogonek, please note that it should not be attached centrally like cedilla. It should be placed near the right boundaryof e (but should not exceed it).

![image](https://user-images.githubusercontent.com/475781/193545312-d170bb32-eed8-425a-9982-c5e6d1b13d7d.png)

It would be great if it could be fixed in some future release.

---

* Your font version: 16.0.2
* Your font variant: Iosevka Term
* Your operating system (name and version): Windows 11 22H2
* Your application using Iosevka: Font settings

**Comment by be5invis** [comment]
Needs to create this crafty shape...

![image](https://user-images.githubusercontent.com/240091/193994285-ae8c91fb-499e-48a7-aab6-b70a614055a2.png)![image](https://user-images.githubusercontent.com/240091/193994253-1a14f106-20b6-47c5-b3e3-0f4f0f13bb32.png)
