### ISSUE TITLE
VSCode settings 

### ISSUE THREAD

**Issue by ShalokShalom** [be5invis/Iosevka#1429]
Hi there

This is a feature request

I use VSCode, and there is currently NO information on the README, which exact text, (how formatted, etc) goes into the VSCode settings input box.

It is understandable, and obvious that Iosevka is the right term for the default configuration, but NO information is provided, or can be easily inferred, how to use any of the variations. 

I prefer the different configuration names right next to an example, so we can see, how the result will look. 

Thanks a lot

**Comment by alexeyten** [comment]
I'm not sure, but maybe this will help? https://github.com/tonsky/FiraCode/wiki/VS-Code-Instructions#stylistic-sets

**Comment by ShalokShalom** [comment]
No
