### ISSUE TITLE
misaligned ligatures

### ISSUE THREAD

**Issue by zou000** [be5invis/Iosevka#143]
* Your font version: (Release or git, version)
git, from head > r1.10.5
* Your font variant:
regular
* Your operating system (name and version):
font built on debian testing, used on ubuntu 14.04
* Your application using Iosevka: (some Java applications may have problem in showing Iosevka properly. It is a bug in Java's GUI components.)
chrome, eclipse

If you have problem when building Iosevka, please provide these informations:

* Your Node.js version:
* Your results of `npm list`
* Your _otfcc_ version:
* Your FontForge version:
* Your `parameters.toml`:

---
Describe your problem here. Provide pictures and files if necessary.
The ligatures for -> and -->, etc. are misaligned for some font sizes, i.e., the arrow shaft is not aligned with the center of the arrow head.
The picture shows the arrow '-->' from 6px to 20px.  The problem is most visible at 6px, 10px, 12px, 15px, 19px and 20px.
![misaligned_arrows](https://cloud.githubusercontent.com/assets/482689/22121515/48edbe10-de39-11e6-9ee0-955318af11a2.png)

**Comment by be5invis** [comment]
It's about hinting and rounding, and AFAIK, I cannot fix that, especially in Java.
Closed.
