### ISSUE TITLE
Equality ligatures missing pixels

### ISSUE THREAD

**Issue by Mango0x45** [be5invis/Iosevka#1430]
As you can see here, the equality ligatures (==, ===, !=, !==) seem to be missing some pixels?
![image](https://user-images.githubusercontent.com/57815710/194447495-0716b0ae-3d9d-48ea-bd6f-3fae2fb0fbca.png)

**Comment by be5invis** [comment]
This notch is by design. You can choose a variant to remove them.
Resolve as by design.
