### ISSUE TITLE
Inconsistent slab serifs on ∃ (exists) versus ∀ (for all)

### ISSUE THREAD

**Issue by raner** [be5invis/Iosevka#1435]
* Font version: 16.3.0
* Font variant: Slab Extended
* Operating system (name and version): MacOS 10.15.7
* Application using Iosevka: can be reproduced with any text editor or IDE (screen shot from MacOS TextEdit)

There is an inconsistency with the slab serifs between ∀ (for all; `U+2200`) and ∃ (exists; `U+2203`): while ∀ has slab serifs (as expected), ∃ is rendered without slab serifs. I would expect ∃ to have them as well:

<img width="211" alt="Screen Shot 2022-10-13 at 6 15 27 PM" src="https://user-images.githubusercontent.com/730344/195739913-5925ce58-22a8-41c8-8d4d-53c0276035bc.png">

(alternatively, one _could_ argue that neither of them should have slab serifs, similar to how math operators generally don't have serifs, but personally I feel that both characters should be rendered with serifs)

**Comment by be5invis** [comment]
Yeah ∃ and ∀ should be always sans-serif.

**Comment by raner** [comment]
Thanks for the prompt fix 👍
