### ISSUE TITLE
Inconsistent ⟨y⟩-like bases with ogonek

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#1437]
<U+0079 LATIN SMALL LETTER Y, U+0328 COMBINING OGONEK> has a special glyph in Iosevka. Where did this glyph come from? Is it used in Elfdalian? It is hard to find definitive information about this sequence. Anyway, this form is not shared by similar base letters:
* U+00FD LATIN SMALL LETTER Y WITH ACUTE
* U+00FF LATIN SMALL LETTER Y WITH DIAERESIS
* U+0177 LATIN SMALL LETTER Y WITH CIRCUMFLEX
* U+01B4 LATIN SMALL LETTER Y WITH HOOK
* U+0233 LATIN SMALL LETTER Y WITH MACRON
* U+024F LATIN SMALL LETTER Y WITH STROKE
* U+1E8F LATIN SMALL LETTER Y WITH DOT ABOVE
* U+1E99 LATIN SMALL LETTER Y WITH RING ABOVE
* U+1EF3 LATIN SMALL LETTER Y WITH GRAVE
* U+1EF5 LATIN SMALL LETTER Y WITH DOT BELOW
* U+1EF7 LATIN SMALL LETTER Y WITH HOOK ABOVE
* U+1EF9 LATIN SMALL LETTER Y WITH TILDE
![y̨ý̨ÿ̨ŷ̨ƴ̨ȳ̨ɏ̨ẏ̨ẙ̨ỳ̨ỷ̨ỹ̨](https://user-images.githubusercontent.com/1124347/198835931-cbd4ba07-ab60-45d6-8653-dd45e18fe332.png)

---

* Your font version: 16.3.5
* Your font variant: Iosevka Slab Extended
* Your application using Iosevka: hb-view

**Comment by be5invis** [comment]
> Is it used in Elfdalian? 

Y. I only did it for original `y`.

I followed Brill which only has the original `y`. Other combinations will have the ogonek detached.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/198849684-78d93674-5103-47e9-bd9d-74647ed0ed19.png)

**Comment by dscorbett** [comment]
Where did Brill get it from?

**Comment by be5invis** [comment]
Their website: https://brill.com/page/BrillFont/brill-typeface

**Comment by be5invis** [comment]
> Where did Brill get it from?

No idea. I tried Gentium Plus, and it doesn't have this.

**Comment by be5invis** [comment]
Found an interesting thread: https://github.com/rsms/inter/issues/285

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/198853846-d2023386-2ae4-433d-9e6a-fdc305cf1cf5.png)
