### ISSUE TITLE
Only build a single weight

### ISSUE THREAD

**Issue by robertgzr** [be5invis/Iosevka#144]
I am currently working on a homebrew formula to build Iosevka and it would be very helpful for debugging if I could tell it to only build a single weight - like Regular - instead of having to wait for it to build the entire set.

Is there something like this in the current makefile?

In case somebody is interested: [iosevka formula](https://github.com/robertgzr/homebrew-tap/blob/master/iosevka.rb) - it links itself into the user's `~/Library/Fonts` directory. I don't consider it finished atm as I am trying to implement switches for all the glyphs that have variants.

EDIT:

I found a way to do this. Applying the following patch will only build the `iosevka-regular.ttf`

```
diff --git a/onegroup.mk b/onegroup.mk
index 89c6269..5d9c5f8 100644
--- a/onegroup.mk
+++ b/onegroup.mk
@@ -42,7 +42,7 @@ NODE = node
 UPRIGHT = $(OBJDIR)/$(PREFIX)-thin.ttf $(OBJDIR)/$(PREFIX)-extralight.ttf $(OBJDIR)/$(PREFIX)-light.ttf $(OBJDIR)/$(PREFIX)-regular.ttf $(OBJDIR)/$(PREFIX)-medium.ttf $(OBJDIR)/$(PREFIX)-bold.ttf $(OBJDIR)/$(PREFIX)-heavy.ttf
 ITALIC  = $(OBJDIR)/$(PREFIX)-thinitalic.ttf $(OBJDIR)/$(PREFIX)-extralightitalic.ttf $(OBJDIR)/$(PREFIX)-lightitalic.ttf $(OBJDIR)/$(PREFIX)-italic.ttf $(OBJDIR)/$(PREFIX)-mediumitalic.ttf $(OBJDIR)/$(PREFIX)-bolditalic.ttf $(OBJDIR)/$(PREFIX)-heavyitalic.ttf
 OBLIQUE = $(OBJDIR)/$(PREFIX)-thinoblique.ttf $(OBJDIR)/$(PREFIX)-extralightoblique.ttf $(OBJDIR)/$(PREFIX)-lightoblique.ttf $(OBJDIR)/$(PREFIX)-oblique.ttf $(OBJDIR)/$(PREFIX)-mediumoblique.ttf $(OBJDIR)/$(PREFIX)-boldoblique.ttf $(OBJDIR)/$(PREFIX)-heavyoblique.ttf
-TARGETS = $(UPRIGHT) $(ITALIC) $(OBLIQUE)
+TARGETS = $(OBJDIR)/$(PREFIX)-regular.ttf
 MAPS    = $(if $(NOCHARMAP),,$(OBJDIR)/$(PREFIX)-regular.charmap)
 
 FDTS    = $(subst .ttf,.fdt,$(subst $(OBJDIR)/,$(OBJDIR)/.pass0-,$(TARGETS)))

```

**Comment by be5invis** [comment]
There are 10 predefined sets, and 21 fonts per each, so...
I have to add 210 targets into my makefile?

**Comment by be5invis** [comment]
The current Iosevka building is the `generate.js` that produces a `.otd` which would be converted into TTF using `otfcc`:

```
node generator iosevka [term|cc] [slab] <w-thin |...| w-book |...| w-heavy> <s-upright | s-italic | s-oblique> [<other styles>] -o output.otd
```

**Comment by be5invis** [comment]
@robertgzr 
I've rewritten the build script that you can configure a custom build set:
```bash
make custom-config set=set1 design='styles styles'
```
and then build your own:
```bash
make custom set=set1
```

In your case you can perform this:
```bash
make dist/iosevka-set1/iosevka-set1-regular.ttf __IOSEVKA_CUSTOM_BUILD__=true
```

**Comment by robertgzr** [comment]
Thanks! I updated my formula - with `1.11.0` everything works like a charm.
