### ISSUE TITLE
Can't install on iPhone -_-

### ISSUE THREAD

**Issue by InvaderJ** [be5invis/Iosevka#1443]
Seems like the ttc packages overwhelm various font installers, preventing installation of Iosevka on iOS. Even just selecting the Curly ttc, the 50+ variants within just steamroll installers such as AnyFont, etc. -__- 

Any way to get individual styles broken out?  xoxo

**Comment by alexeyten** [comment]
There are separate TTF-files:

> TTF | 54 .ttf files | Each TTF file contains one font for a specific weight, width, slope and spacing variant. This option is ideal for embedding Iosevka into applications, or for desktop usage if TTC options have compatibility issues.

**Comment by InvaderJ** [comment]
Oh wow I totally did not see these in the giant file list, nor mention of them as TTFs. Thanks so much, found them and grabbed them. Appreciate it!
