### ISSUE TITLE
v16.4.0减号出现显示问题

### ISSUE THREAD

**Issue by nobk** [be5invis/Iosevka#1446]
v16.4.0减号长度异常
![Snipaste_20221123T042830](https://user-images.githubusercontent.com/4659870/203415739-415bda48-c683-424b-8f4f-4c10c0cf6b25.jpg)
以下是换回v16.3.6的效果
![Snipaste_20221123T044237](https://user-images.githubusercontent.com/4659870/203417651-fdc675d3-5c37-4e8a-b881-43b680955fd8.jpg)

---

* Your font version: v16.4.0
* Your font variant: Iosevka Lucida SS13
* Your operating system (name and version): Windows 11
* Your application using Iosevka: Windows Terminal

**Comment by be5invis** [comment]
I cannot repro. If it is cache related, you can try uninstall the fonts then re-install, which might fix the problem.

**Comment by nobk** [comment]
用这个配置来构建应该可以重现，我用的docker编译的，没有cache
不知是否字体宽度设置了extended as normal情况下才有这个问题，我需要宽字体，默认字体太窄了眼睛看着不舒服。
```
[buildPlans.iosevka-lucida-term]
family = "Iosevka Lucida Term"
spacing = "term"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

  [buildPlans.iosevka-lucida-term.variants]
  inherits = "ss13"

    [buildPlans.iosevka-lucida-term.variants.design]
    zero = "dotted-oval"
    paren = "large-contour"
    brace = "straight"

[buildPlans.iosevka-lucida-term.weights.regular]
shape = 440
menu = 400
css = 400

[buildPlans.iosevka-lucida-term.weights.medium]
shape = 500
menu = 500
css = 500

[buildPlans.iosevka-lucida-term.weights.semibold]
shape = 600
menu = 600
css = 600

[buildPlans.iosevka-lucida-term.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-lucida-term.widths.normal]
shape = 600
menu = 5
css = "normal"
```

**Comment by be5invis** [comment]
The cache means Windows' font cache.

I tried your build options. No repro.

![image](https://user-images.githubusercontent.com/240091/203658551-654e235c-a351-43b5-a27a-9e7aab31fe77.png)
