### ISSUE TITLE
Consider submitting Iosevka fonts to Google Fonts

### ISSUE THREAD

**Issue by melefabrizio** [be5invis/Iosevka#1447]
**Is your feature request related to a problem? Please describe.**
Google Fonts is quite useful, and is a good place to find quality fonts. It also has the perk to be the font repo for the google docs suite, and quite handy to get webfonts in a web project. Currently it lacks a quality monospace font like Iosevka. It has some alternatives, like for instance JetBrains Mono, but I find Iosevka to have enough differences from it to bring forward the case to submit all of its "consumer" families (Mono, Slab, Aile, Etoile) to Google Fonts.

**Describe the solution you'd like**
Iosevka, especially Slab, Aile and Etoile variants, should be submitted to Google Fonts.

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by be5invis** [comment]
I think there are already outstanding issues at their repo. I don't have enough bandwidth though.
Resolve as external.
