### ISSUE TITLE
Missing several capital/lowercase forms from Latin Extended-C

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1448]
- The requested character is...
  - [x] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [ ] Symbol
- [x] Some other monospace/programming fonts supported this character. Provide images below.

------
The Latin Extended-C block contains several capital/lowercase counterparts of existing characters from lower blocks which are already supported by the font.<br>
Examples:<br>
- ᵽ → Ᵽ
- ɽ → Ɽ
- Ⱥ → ⱥ
- Ⱦ → ⱦ
- ɱ → Ɱ

------
Demonstration of the block in Consolas:<br>
![bildo](https://user-images.githubusercontent.com/37010132/203635645-9aef7d46-a27e-4f06-b620-bc0f178e4fa1.png)
Comparison with Iosevka:<br>
![bildo](https://user-images.githubusercontent.com/37010132/203636831-13880108-962f-4c2a-baaa-295e64d69ffb.png)

**Comment by be5invis** [comment]
Added in latest commit
