### ISSUE TITLE
Capital t is too narrow in Etoile

### ISSUE THREAD

**Issue by vincentbernat** [be5invis/Iosevka#1449]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [ ] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [ ] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------
Hey!

I find the capital T too narrow in Etoile, notably due to the serif. Removing the serif does not work as it makes the character look odd next to others. I would suggest to just expand its width. Other serifed font usually have larger T. In Etoile, the regular width (width of "h" for example) should be used instead of the width of "t".

![image](https://user-images.githubusercontent.com/631446/203641362-58a00616-df72-4c1f-a93b-1907dabfb5ba.png)

**Comment by be5invis** [comment]
Most capitals currently are, well considered narrow. Still thinking about a proper way to handle them...
