### ISSUE TITLE
Please, make a ttf file of my version of the Iosevka font. Thank so much!

### ISSUE THREAD

**Issue by Elektroair** [be5invis/Iosevka#1452]
Hi! I do not know how to create a ttf file of my Iosevka font variant, and I am asking someone to do this and send a ttf file. Thank you in advance!

```
[buildPlans.iosevka-elektroair]
family = "Iosevka Elektroair"
spacing = "normal"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

[buildPlans.iosevka-elektroair.variants.design]
capital-j = "serifed-both-sides"
capital-l = "motion-serifed"
capital-q = "crossing"
capital-w = "straight-flat-top"
capital-z = "straight-serifed"
b = "toothless-corner"
d = "toothless-corner-serifless"
f = "flat-hook"
g = "single-storey-flat-hook-serifless"
j = "flat-hook-serifed"
p = "earless-corner"
q = "earless-corner"
t = "flat-hook"
w = "straight-flat-top"
y = "cursive-flat-hook"
z = "straight-serifed"
eszet = "sulzbacher-descending"
lower-mu = "tailless"
one = "base"
two = "curly-neck"
three = "flat-top"
four = "closed"
six = "closed-contour"
seven = "straight-serifed"
eight = "two-circles"
nine = "closed-contour"
paren = "flat-arc"
brace = "straight"
at = "fourfold"
percent = "rings-continuous-slash"
lig-equal-chain = "without-notch"
```

**Comment by mfocko** [comment]
1. Fork the Iosevka repository
2. Create a branch with your config
3. Create a GitHub Action that will run the build on each push to the branch

I might try to do it and send you a link, but I'm kinda backed up right now, so I am not sure if I have time.

**Comment by Elektroair** [comment]
> 1. Fork the Iosevka repository
> 2. Create a branch with your config
> 3. Create a GitHub Action that will run the build on each push to the branch
> 
> I might try to do it and send you a link, but I'm kinda backed up right now, so I am not sure if I have time.

I would love to, but I don't quite understand how to follow this instruction. I don't understand how to create a branch with a configuration and I don't understand how to create a GitHub action. I'm sorry :(

**Comment by mfocko** [comment]
@Elektroair you can get it from [here](https://github.com/mfocko/Iosevka/actions/runs/3621266454) and you need [these](https://github.com/be5invis/Iosevka/compare/main...mfocko:Iosevka:private-builds) 5 commits to replicate on your end… The build configuration has few more variants than yours, so you just use `private-build-plans.toml` from this issue description.

**Comment by Elektroair** [comment]
> @Elektroair you can get it from [here](https://github.com/mfocko/Iosevka/actions/runs/3621266454) and you need [these](https://github.com/be5invis/Iosevka/compare/main...mfocko:Iosevka:private-builds) 5 commits to replicate on your end… The build configuration has few more variants than yours, so you just use `private-build-plans.toml` from this issue description.

> [Here's the setup I use](https://github.com/AndydeCleyre/archbuilder_iosevka), with instructions in the README.

I'm sorry, but I really don't understand what I need to do. I don't understand the meaning of the words "repository", I don't understand what is written in the code that you sent me. I followed all three links, but I didn't understand anything.

I read the readme on the constructor, but I didn't understand anything. There is such a command: npm run build -- contents::<your plan name>. But I don't understand where to enter it, what kind of command it is and what it runs.

I am not familiar with the working principle of GitHub, I do not understand its capabilities. I am almost not familiar with programming, I am only familiar with the Delphi language, and only as a procedural one. I am not familiar with the Delphi object-oriented language...

**Comment by AndydeCleyre** [comment]
It's just named Iosevka Custom, but otherwise [your build is here.](https://github.com/AndydeCleyre/archbuilder_iosevka/releases/download/elektroair-16.7.0-3/ttf-iosevka-custom-git-1670827914-1-any.pkg.tar.zst)

**Comment by Elektroair** [comment]
> It's just named Iosevka Custom, but otherwise [your build is here.](https://github.com/AndydeCleyre/archbuilder_iosevka/releases/download/elektroair-16.7.0-3/ttf-iosevka-custom-git-1670827914-1-any.pkg.tar.zst)

Thank you so much! Please say me, what program can open this file? How to install the font? I'm seeing ZST file also, and I don't know this format

**Comment by AndydeCleyre** [comment]
I don't know your OS, but try peazip to open this archive file. Poke around the nested folders to find the font files within, and open the ones you want to install. Probably whatever tool they get opened with will offer you an install button.

**Comment by Elektroair** [comment]
> I don't know your OS, but try peazip to open this archive file. Poke around the nested folders to find the font files within, and open the ones you want to install. Probably whatever tool they get opened with will offer you an install button.

Thanks again! The font works!

Closed.
