### ISSUE TITLE
Overshoots in top of open-contour 6 and bottom of open-contour 9 don't match the other figures, resulting in bad rendering

### ISSUE THREAD

**Issue by cssobral2013** [be5invis/Iosevka#1455]
![Screenshot_20221206-195221_WPS Office](https://user-images.githubusercontent.com/19995437/206042134-3a640e9c-1ea8-4378-8b6f-79f819de30c3.jpg)
This issue has been around since at least v2.0.

**Comment by cssobral2013** [comment]
A solution would be, implementing a metric override to reduce, or increase, these overshoots in 6 and 9.

**Comment by be5invis** [comment]
Could you point out which "overshoots" are you talking about? Both arches and corners can have overshoot.

**Comment by cssobral2013** [comment]
@be5invis - More specifically, the overshoots in open-contoured 6 and 9.

**Comment by be5invis** [comment]
@cssobral2013 I mean, WHERE are they. Could you box the parts you are talking about?

**Comment by cssobral2013** [comment]
@be5invis - Sorry for misunderstanding. In the of open-contour 6, and the bottom of the open-contour 9.

**Comment by be5invis** [comment]
@cssobral2013 Are you thinking these overshoots are too much or too less?

**Comment by cssobral2013** [comment]
@be5invis - These are too high, making rendering bad in many OSes.

**Comment by cssobral2013** [comment]
@be5invis - As per title , these overshoots (top of open-contour 6 and bottom of open-contour 9) should match the overshoots of other figures.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/206050343-79629d3c-74dd-4c27-8638-91db983c7bdb.png)

I think the actual probelm is... the oval zero's shape is too short!

**Comment by be5invis** [comment]
My purposed fixes:
 * Fix overshoot of (oval-shaped) 0.
 * Slightly reduce the overshoot of open 6 and 9's terminals.

![image](https://user-images.githubusercontent.com/240091/206071525-8fee776b-b79d-4a62-b8ca-ed157dde65de.png)
