### ISSUE TITLE
Thicker BQN symbols

### ISSUE THREAD

**Issue by gvolk0** [be5invis/Iosevka#1456]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

![Screenshot_3](https://user-images.githubusercontent.com/8690075/206642364-724d0dc3-2feb-4952-b651-19cdac8d7aa1.png)

------

*Please provide your justification here.*

Several of the current BQN symbols are substantially thinner and thus much harder to read compared to the rest of this (fantastic!) font.

Note that I'm on a 4K laptop with a very high PPI and it's still too hard to see/recognise those symbols without increasing the font size several times at which point the rest of the text is way too large (and wastes precious real estate which Iosevka is so good at utilising thanks to it's narrowness/compactness).

I haven't checked all of BQN's symbols (I'm very new to the language) but so far the following could be improved (which incidentally are also used quite frequently): `←⊸⟜⥊∘`

A special case is for `⊸⟜` - I think they're about the same thickness as the rest of the font, but the circles and dashes are a bit too small (it may not seem that way in my screenshot due to the high res but I couldn't shrink it without making the text very blurry - if you view the below code on your monitor I'm sure you'll see what I mean). Perhaps the circle could be oblong as a variant?  And/or less space at the edges to increase the size of the circle?

eg (src for the above image):
```
#!/usr/bin/env bqn
ndl←"inet "
hay←1⊑•SH "ip"‿"a"
id←/⟜(↕≠)ndl⍷hay
chk←16↕⊸+¨id+≠ndl
ip←hay⊸(⊏˜)¨chk
lst←({'/'⊐˜𝕩}⊸↑)¨ip
arr←(≠ip)‿∘⥊lst
•Show ar
#•Show lst←'/'(⊣(⊐˜⊸↑)¨)ip
```

Related PR: https://github.com/be5invis/Iosevka/issues/870

**Comment by gvolk0** [comment]
Additionally `←` sits quite low, it'd be nicer if it was v-centered.

**Comment by be5invis** [comment]
Maybe you can try use Iosevka Term? It looks like that there glyphs are actually get **SHRUNK** by the terminal

**Comment by be5invis** [comment]
This is what it looks like using Iosevka Term. Many terminals have their assumption about characters' width, and Iosevka Term is made for this case.

![image](https://user-images.githubusercontent.com/240091/206682073-9a89db77-bffc-4ac3-b1d7-e4a0edadc883.png)

**Comment by be5invis** [comment]
(ps. Do you have a full list of all the symbols that BQN uses? I may need to extend `apl-form` glyph transformation to support them.

**Comment by gvolk0** [comment]
ah, derp!  I thought I was using Term but I rechecked and you're right, I wasn't - with Term it indeed looks much better.

Sorry for the noise :grimacing: and thanks for looking into this.

However the circles `∘` and `⊸` are still a bit too thin (and again the latter is too small).

Here's the full list of BQN symbols: https://mlochbaum.github.io/BQN/keymap.html
And a more compact list here along with comparison with different fonts (including Iosevka Term): https://mlochbaum.github.io/BQN/fonts.html

In fact looking at them all I think the only other symbols that could use some love are: `⋄⍤⌺` (again, too thin), and maybe the eyes in `⚇` could be a touch fatter?  

The rest look great.

**Comment by be5invis** [comment]
@gvolk0 Done

**Comment by gvolk0** [comment]
Perfect!  Thanks for the speedy fix!

Leaving this here for reference:

![shot-2022-12-21_17-42-36](https://user-images.githubusercontent.com/8690075/208839637-65994131-e1d0-43f7-97f5-f40161b904d2.jpg)
