### ISSUE TITLE
Glyph adjustment for lowercase h with circumflex

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1457]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

having the circumflex hover over the empty space is undesirable, and there are many fonts which hang the circumflex over the stem which looks much more pleasing to the eye:<br>
![bildo](https://user-images.githubusercontent.com/37010132/206763578-8b4a49cb-56f8-41bc-a004-0e632c48191b.png)
additionally, there exist a few fonts which are unicode-aware enough to apply the same metrics to b/d/k with a combining circumflex:<br>
![bildo](https://user-images.githubusercontent.com/37010132/206764022-09fd630d-4250-4db2-b5a2-10fedf490b97.png)

**Comment by be5invis** [comment]
Many fonts do it differently, placing the marks centered, like Brill and Minion.

![image](https://user-images.githubusercontent.com/240091/206808899-ad634ec5-084e-46dd-91a7-d0debb95d446.png)

**Comment by jmcwilliams403** [comment]
The centered form comes from how it would look from typewriters but I would argue that it's not how most people would naturally write it by hand.
![bildo](https://user-images.githubusercontent.com/37010132/206873928-22d1a6b2-ad6d-4519-8241-8df3d218a3dd.png)
I would also like to point out that the official Unicode chart pdf appears to compromise between the two forms which leaves ambiguity:
![bildo](https://user-images.githubusercontent.com/37010132/206874017-ccda00de-b945-488f-a4ec-f5a960d8b63f.png)
