### ISSUE TITLE
Possible way to distinguish French Franc with capital F with stroke

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1459]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

In a previous character request I filed for letters with stroke, I mentioned that the capital F with stroke will unfortunately be a homoglyph with the French Franc sign. While this may very well end up being the case for many fonts, there may be a way around this.<br>
For the French Franc sign, perhaps you could extend the original stroke (the one on the base ascii F glyph) past its vertical line, putting it more in line with the styling of the Russian Ruble sign:

![bildo](https://user-images.githubusercontent.com/37010132/206869707-e1393e30-7a16-4e1c-aeb8-1afbee9fbcc3.png)

This would also go with a possible future addition of capital P with stroke through descender:
![bildo](https://user-images.githubusercontent.com/37010132/206869760-d4cbe600-c439-4a51-9068-d687b334fe1d.png)

**Comment by jmcwilliams403** [comment]
For what it's worth, this is how it looks in the official Unicode chart pdf:
![bildo](https://user-images.githubusercontent.com/37010132/206872789-70e2b3d6-8aaa-4b59-9154-5f84af83d3f2.png)

**Comment by jmcwilliams403** [comment]
Also it would probably be helpful if I simply cited the approved document which proposed the aforementioned glyph update in the first place:
https://www.unicode.org/L2/L2022/22196-cap-letter-f-with-stroke.pdf

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/206879235-54ecb3b4-b36d-4610-a942-ecb0456a7e5e.png)

**Comment by jmcwilliams403** [comment]
Perfect. I apologize for the confusion. I had to find the document again to clarify my error, which was buried.
