### ISSUE TITLE
Inziu Iosevka 基于思源的吗，CJK 中日都有了，韩文是否也考虑放进去

### ISSUE THREAD

**Issue by catcat520** [be5invis/Iosevka#146]
Inziu Iosevka 基于思源优化的吗，原版的思源是有韩文内嵌的

目前来看 Inziu Iosevka 的版本都没有韩文

<img width="1920" alt="2017-01-31_044610" src="https://cloud.githubusercontent.com/assets/9632762/22441161/3de5b4be-e771-11e6-9d8a-6d61880690fb.png">
<img width="1920" alt="2017-01-31_045143" src="https://cloud.githubusercontent.com/assets/9632762/22441160/3dddfff8-e771-11e6-9ef8-e098559b3004.png">

**Comment by be5invis** [comment]
Not purposed because hangul is much complex, especially related to old hangul jamos.
Closed.
