### ISSUE TITLE
Wrong glyph for U+AB5B MODIFIER BREVE WITH INVERTED BREVE

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#1468]
U+AB5B MODIFIER BREVE WITH INVERTED BREVE should be on the baseline, not superscripted. See [figure 75 of L2/11-202](http://www.unicode.org/L2/L2011/11202-n4081-teuthonista.pdf#page=39) for an example.
![a꭛](https://user-images.githubusercontent.com/1124347/208165496-fc2b7692-2b02-435a-a798-51e9a735b1a5.png)

---

* Your font version: 16.8.0
* Your font variant: Iosevka Slab Extended
* Your application using Iosevka: hb-view

**Comment by be5invis** [comment]
@dscorbett I am interested in ... are there an archive or something to find all the L2/WG2 documents of each character?

**Comment by dscorbett** [comment]
Unicode keeps a registry of proposal documents: the current year is at https://www.unicode.org/L2/L-curdoc.htm and other years’ pages are accessible through links. You can often find the documents for a specific character using a Google search like [“"MODIFIER BREVE WITH INVERTED BREVE" site:unicode.org inurl:L2”](https://www.google.com/search?q=%22MODIFIER+BREVE+WITH+INVERTED+BREVE%22+site%3Aunicode.org+inurl%3AL2) or by checking the Wikipedia article about the Unicode block (in this case, [Latin_Extended-E#History](https://en.wikipedia.org/wiki/Latin_Extended-E#History)).
