### ISSUE TITLE
Missing variants of U+1D86 LATIN SMALL LETTER M WITH PALATAL HOOK

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#1470]
U+1D86 LATIN SMALL LETTER M WITH PALATAL HOOK does not respect all the variants of 'cv38'.
![mmmmmmmmmmmmmmmmmmmmm ᶆᶆᶆᶆᶆᶆᶆᶆᶆᶆᶆᶆᶆᶆᶆᶆᶆᶆᶆᶆᶆ](https://user-images.githubusercontent.com/1124347/208247693-320f8904-3506-46be-ba36-ed2159ed2882.png)

---

* Your font version: 16.8.0
* Your font variant: Iosevka Slab Extended
* Your application using Iosevka: hb-view

**Comment by be5invis** [comment]
Arch variants make sense for this. Tailed variants aren't since the bottom-right serif is always present.
