### ISSUE TITLE
cyrl/shcha U+0449 indistinguishable from cyrl/sha U+0448

### ISSUE THREAD

**Issue by turbo-cafe** [be5invis/Iosevka#1477]
Unless cyrl/shcha has "tail" it reads as cyrl/sha. Please, add the rest of the glyph to cyrl/shcha bottom-right corner. Thanks!

---

* Your font version: Iosevka 16.8.0
* Your font variant: regular
* Your operating system (name and version): solus 4.3
* Your application using Iosevka: emacs 28.2

**Comment by turbo-cafe** [comment]
I just noticed same problem with cyrillic small letter tse(U+0446) with iosevka-regular.ttf same variant and version available from github release page

**Comment by turbo-cafe** [comment]
And if I rollback to 16.6 I get correct glyphs for both tse and shcha.

**Comment by turbo-cafe** [comment]
italic and bold have same problem as regular variant of 16.8 with cyrl/shcha and cyrl/tse

**Comment by turbo-cafe** [comment]
Capital (uppercase) and capital bold variant of cyrl/shcha and cyrl/tse have same problem with 16.8 and render ok with 16.6 version

**Comment by DGCK81LNN** [comment]
Seems already fixed: #1469

**Comment by be5invis** [comment]
Fixed in 16.8.2.
