### ISSUE TITLE
[Question] Some characters are much higher than my fallback CJK characters, is there a way to pan down a bit ?

### ISSUE THREAD

**Issue by fengyichui** [be5invis/Iosevka#1488]
Hi,

I found some characters are much higher than my fallback CJK (font is "Microsoft YaHei UI") characters, look like follow:
![higher](https://user-images.githubusercontent.com/17896291/208593548-ea6c529a-9b3b-41ee-a84f-4e465401c606.png)

And the old v11.1.1 version look good:
![ok](https://user-images.githubusercontent.com/17896291/208593558-8362b95f-5d42-4431-9ca5-b6800a3c3956.png)

Is there a way (or params) to pan down a bit?

**Comment by fengyichui** [comment]
Can anyone help me?

**Comment by Logo121** [comment]
Not a full solution, but you can try [Sarasa Gothic](https://github.com/be5invis/Sarasa-Gothic) if CJK support is all that's needed?

**Comment by fengyichui** [comment]
I've tried the Sarasa Gothic font, but its CJK doesn't look as good as Microsoft YaHei UI.
