### ISSUE TITLE
Serif forms of some existing characters

### ISSUE THREAD

**Issue by Logo121** [be5invis/Iosevka#1489]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.
(only some of them)
------

Below is a comparison between several serif (not necessarily monospace) fonts and Iosevka, on some glyphs that should have serifs, but is not given one in Iosevka. (unsupported characters are rendered in unifont instead)
![image](https://user-images.githubusercontent.com/21302803/208656382-9b7f19cf-6cf9-461c-8e47-e0831de24ab2.png)
Text: `ǷƿȜȝᵹꝽѠѡѼѽѾѿꙌꙍ`

Some notes:
- Cyrillic omega can be rendered either as that weird symmetric G, or as something like W. Both forms are correct, but I don't think you can add more variants anyway.
- The one glyph not supported by Iosevka here is [Capital Insular G](https://github.com/be5invis/Iosevka/issues/1483), for if you are going to support that as well.

**Comment by be5invis** [comment]
I ususally use Brill as reference. Here are the Crillic Omegas:

![image](https://user-images.githubusercontent.com/240091/208663687-190d788a-3fc8-4562-864c-b7f2a0a8295b.png)

I don't think inward hooks in the "broad" shape are serifs, so for these I will keep the current shape.
For non-broad Omega I will adopt the W-like shape for both the cases.

**Comment by Logo121** [comment]
Ok, but I don't feel like the current glyphs look like they have "inward hooks" either. 

Here's a comparison using the above fonts (+ Brill and Noto Sans) for reference (the ones on the left are the tangentially related latin omegas (Ꞷꞷ)):
![image](https://user-images.githubusercontent.com/21302803/208673384-f4dfa942-af2f-4e10-85c3-55a3404ef9f2.png)

Most fonts seem to at least make the non-greek omegas have more pronounced hooks to differentiate(?) them from the greek one.

Also these examples in the Russian Wikipedia:
![image](https://user-images.githubusercontent.com/21302803/208674412-ed8260de-2fd2-4d77-8290-1ccfeb706b82.png)

**Comment by pv4** [comment]
> Here are the Crillic Omegas:

@be5invis thank you very much! I will use one of them as my profile picture :D
