### ISSUE TITLE
Wacky kerning/overlap/hiding/something with Ⓐ (U+24B6) in konsole

### ISSUE THREAD

**Issue by AndydeCleyre** [be5invis/Iosevka#149]
* Your font version: `r886.2477121`
* Your font variant: `design='v-l-tailed v-i-hooky v-g-opendoublestorey v-m-shortleg v-zero-dotted'`
* Your operating system (name and version): Arch Linux
* Your application using Iosevka: konsole

In konsole, entering the characters `123Ⓐ456` displays as:

![screenshot_20170207_125149](https://cloud.githubusercontent.com/assets/1787385/22705757/d290db9c-ed3a-11e6-9b14-bd563e7df8d4.png)

The 6 (or whatever the last character in the line happens to be) does not display.

Not sure if this is a font issue or a konsole issue.

**Comment by AndydeCleyre** [comment]
I see a similar issue with ⋄, much less extreme:

![image](https://cloud.githubusercontent.com/assets/1787385/22712968/a7d2bde8-ed54-11e6-80ad-a34bcfb7babb.png)

**Comment by leiserfg** [comment]
Try with Iosevka term first.

**Comment by AndydeCleyre** [comment]
With iosevka term, the Ⓐ is skinny and all the characters show up fully in that example, while ⋄ is bigger and the last character still gets cropped.

**Comment by be5invis** [comment]
I do not think that Konsole supports characters wider than one latin letter. This is why Iosevka Term exists.
The `⋄` is NOT support by Iosevka yet.
Closed as external.

**Comment by AndydeCleyre** [comment]
Thanks for clearing that up for me.

> characters wider than one latin letter

In the standard build (not term) are different characters different widths?

**Comment by be5invis** [comment]
@AndydeCleyre Some will, like the circled A.

**Comment by AndydeCleyre** [comment]
Doesn't that contradict the whole monospaced font idea?

**Comment by be5invis** [comment]
@AndydeCleyre Well they are **two** latin letters' wide, so alignment can be preserved either.
We use monospaced fonts because we need alignment, right?

**Comment by AndydeCleyre** [comment]
> We use monospaced fonts because we need alignment, right?

In my opinion we use them because we need *predictable* alignment. The very definition of *mono* *spaced* fonts . . . well, here's how [Wikipedia](https://en.wikipedia.org/wiki/Monospaced_font) defines it (emphasis mine):

> A monospaced font, also called a fixed-pitch, fixed-width, or non-proportional font, is a font whose letters and **characters each occupy the same amount of horizontal space.** This contrasts with variable-width fonts, where the letters and spacings have different widths.

The article also lists as a traditional benefit:

> This increases the readability of source code, which is often heavily reliant on distinctions involving individual symbols

Your comment made me doubt my whole conception of monospaced fonts, but after checking with the all-knowing Wikipedia, I still believe that having some characters be wider than others (excluding ligatures that replace multiple characters) constitutes a serious bug in a purportedly monospace font.

**Comment by AndydeCleyre** [comment]
If you prefer to have this non-monospaced by default, is there a way to compile all double-width characters that correspond to a single character (i.e. excluding a representation of `->` but including `Ⓐ`) as relatively half their (double) width?
