### ISSUE TITLE
Latin Beta (U+A7B4, U+A7B5)

### ISSUE THREAD

**Issue by Logo121** [be5invis/Iosevka#1492]
- The requested character is...
  - [x] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [ ] Symbol
- [x] Some other monospace/programming fonts supported this character. Provide images below.
(Not very well though)

------

Unicode has encoded these IPA letters `ɑꞵɣɛɸꭓʋ` as Latin letters separate from their Greek counterparts `αβγεϕχυ`, which is done to avoid script mixing, and also because they have subtle difference in shapes. Latin beta is the only one left not supported.

Back in [this](https://github.com/be5invis/Iosevka/issues/1458) issue I noticed that some fonts adds a serif for the Greek beta.  
I thought of proposing that Iosevka do the same, but since then I realized later that this font by design does not include serifs for most Greek letters, so I didn't. But the Latin version seems to have bottom serifs from the original IPA standard:

![image](https://user-images.githubusercontent.com/21302803/208982015-4afc93b4-5f5d-4ea3-99ad-7b84a0de8ec9.png)

And also in the Unicode proposal:

![image](https://user-images.githubusercontent.com/21302803/208982322-f6d8a197-0759-4eaa-bec6-c84a783ef3ca.png)

For other fonts that supports these characters, I found Everson Mono, Fairfax HD, Noto Sans Mono and Julia Mono (lowercase only). Along with some other non-monospace fonts for reference (`Ꭓꭓ Χχ Ꞵꞵ Ββ`):

![image](https://user-images.githubusercontent.com/21302803/208983296-7c48365e-9c9c-4da5-9337-04128438e267.png)

Note that for the lowercase beta, some fonts renders the bottom curve(?) to touch the vertical bar (Noto Sans Mono), some don't and curve up instead, some even does so for the uppercase (Everson Mono). Probably either one is fine (both variations are shown in the Unicode proposal).

**Comment by Logo121** [comment]
Oh, I forgot to mention:

You seem to have created the "combining latin beta above" (U+1DE9) glyph based on the greek beta before this whole request, which should be `latn/beta`, given the name. (Although this glyph technically existed before latin beta was added)

https://github.com/be5invis/Iosevka/blob/de1841cd107a45630e3c3a9f7082b9a52dc1e40c/font-src/glyphs/auto-build/transformed.ptl#L556

The glyph as shown in unicode:
![image](https://user-images.githubusercontent.com/21302803/209125569-297b4d4d-9fee-4b40-8b07-913754bc1649.

**Comment by be5invis** [comment]
Fixed
