### ISSUE TITLE
Threefold solid inner at symbol

### ISSUE THREAD

**Issue by NomisIV** [be5invis/Iosevka#1495]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [ ] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------
[Mononoki](https://madmalik.github.io/mononoki/):
![image](https://user-images.githubusercontent.com/47303199/209407038-3ae64168-3eaa-48b6-b616-7a3743005c60.png)

I only know of mononoki having this at-symbol variant.

I personally like the original `threefold` at symbol in iosevka, but I think the inner space is a bit too small in lower font sizes, and thus I would prefer a more minimalistic version with a solid inner, just like `fourfold-solid-inner`.

**Comment by Logo121** [comment]
This is closable too
