### ISSUE TITLE
Five remaining Latin ligatures in the Alphabetic Presentation Forms block

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1497]
- The requested character is...
  - [x] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [ ] Symbol
- [x] Some other monospace/programming fonts supported this character. Provide images below.

------

These characters (FB00..FB06) have existed in Unicode since 1.1, however only FB01 and FB02 are currently supported by the font.<br>
Example using Consolas:
![bildo](https://user-images.githubusercontent.com/37010132/209435921-72cbee11-ad66-4494-9e3a-3dae4050750f.png)
Although I'm not a fan of how most fonts do the «ﬅ» ligature.<br>Here's how it's supposed to look according to the Unicode block's official PDF, showing more clearly that it's supposed to be «ſt»:
![bildo](https://user-images.githubusercontent.com/37010132/209435974-7f6ed3e3-f7bc-4b62-8856-8ef302d4a77a.png)

**Comment by be5invis** [comment]
I plan to resolve this as **out of scope**.
FB01 and FB02 are added because they are in WGL4.
For the others, I heard that they are not recommended to be used (but I cannot find the source article now).
