### ISSUE TITLE
Request: hooky t

### ISSUE THREAD

**Issue by therockmandolinist** [be5invis/Iosevka#150]
I think it would be a little more consistent with the font if the curve on the bottom of the `t` was more like the bottom of `cv08` or if at least it came with a hooky (straight bottom) variant as well.

Excellent font, by the way!

**Comment by be5invis** [comment]
Merged into #140.

**Comment by efermi** [comment]
The hooks on the upright `t` and `l` (cv40 and cv08) are different, while the italic variants are similar. Would it be possible to have shorter and straighter hook for `t` in the upright variant?
