### ISSUE TITLE
16.4.0 `asterisk=*-high` vertical placement regression?

### ISSUE THREAD

**Issue by pv4** [be5invis/Iosevka#1504]
Hi!

In 16.4.0 `asterisk=*-high` are placed lower than in 16.3.6. Is it an expected behavior? The placement of `*-low` variants is the same in both versions.

![image](https://user-images.githubusercontent.com/2502094/210023791-744c44c9-fd49-4efb-82a0-4f6749a197ac.png)

**Comment by be5invis** [comment]
This is intensional. Resolve as by design.

**Comment by pv4** [comment]
@be5invis
Then could you please add the previous variant as a separate character variant so that `asterisk` has 3 vertical-placement variants like `caret` do?

I got used to asterisk being vertically placed above any letter. The old asterisk variant was above any letter be it lowercase or uppercase. The new one is still above lowercase letters (that's good), but when being placed near an uppercase letter it imho takes a strange illegible position "somewhere between middle and top". Besides, at small font sizes asterisk looks much similar to plus sign and placing asterisk much higher that plus sign allows them to be to distinguished much easier.

P.S. I've just checked many monospace fonts, and in most of them asterisk is placed exactly like in iosevka 16.4.0 (new variant). But I always liked iosevka not for being like other fonts but for being better than them.

**Comment by be5invis** [comment]
@pv4 Please file a new issue about this (extra-high variants).
