### ISSUE TITLE
More degree symbol (º) variants

### ISSUE THREAD

**Issue by rben01** [be5invis/Iosevka#1505]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

The degree symbol, º, currently only has an underlined variant. It would be great to have a non-underlined variant as well — just the circle itself.

Separately, I think it would also be good to add a variant where the degree symbol is a bit higher up, like a superscript; ideally there would be a variant where its topmost point was level with the top of the superscript 0.

Current:
<img width="41" alt="image" src="https://user-images.githubusercontent.com/766670/210101219-2457aed3-4660-4c7e-8da7-8f7ee13c7ccb.png">

Desired:
<img width="41" alt="degrees" src="https://user-images.githubusercontent.com/766670/210101447-5ebe5188-c225-4693-9fab-cbe796816b46.png">

**Comment by be5invis** [comment]
Well, this is NOT degree symbol.It is an [ordinal indicator](https://en.wikipedia.org/wiki/Ordinal_indicator) used in Spainish, etc.

**Comment by be5invis** [comment]
The real degree symbols `°` (U+00B0) is designed to not have the underline.

**Comment by rben01** [comment]
Oh, my mistake. Thanks!
