### ISSUE TITLE
Request: Ligation Modification for `^-`

### ISSUE THREAD

**Issue by BearBearCodes** [be5invis/Iosevka#1507]
Currently, the `center-ops` ligation option vertically centres the operator `^` when it is preceded/followed by `-`, as seen below.

<img width="234" alt="image" src="https://user-images.githubusercontent.com/64443273/210227353-29da7bae-d457-43d9-a283-4afb78c36bf0.png">

Does there exist or is it possible to make a ligation variant where operators like `:=` are still centred but `^-` doesn't centre the caret? This would make it so typing text like `^-2` has the same caret positioning as `^2`.

This would be very useful for markup languages like TeX and markdown (e.g., `$e^-$` to denote units of electrons), as well as general writing (e.g., in a .txt file where I may want to use `3.14^-2`).

**Comment by be5invis** [comment]
Perhaps carets (`^`) could be directly removed from centering since it is highly "asymmetric".
