### ISSUE TITLE
Taller 0 slash from v2.x?

### ISSUE THREAD

**Issue by nathanielevan** [be5invis/Iosevka#1509]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [ ] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

Hi, many thanks for your work on Iosevka, been using it for months and loving it! A little question, I came across the older v2.x versions of Iosevka and found out that in that older version, the slash on the 0 is a little taller, like so:

- Older (v2.x): 
![scshot-090123-191755](https://user-images.githubusercontent.com/9361126/211306416-4087afb2-d66c-4538-8c4b-9f80e10e047f.png)
- Current: 
![scshot-090123-191826](https://user-images.githubusercontent.com/9361126/211306447-52b5d4dd-b7d2-40e2-af1f-986e25043b97.png)

And this might seem a bit minor, but I'm wondering if I can get the 0 from the older version with a certain build parameter? Or perhaps, would you consider adding that as a new variant?

Edit: did a little more digging and I found that version [3.0.0-beta.3](https://github.com/be5invis/Iosevka/releases/tag/v3.0.0-beta.3) was the last version to carry the taller 0 slash. The following version, [3.0.0-rc.1](https://github.com/be5invis/Iosevka/releases/tag/v3.0.0-rc.1), seems to no longer ship with that taller 0 slash. It was probably changed with commit [0bac9a1](https://github.com/be5invis/Iosevka/commit/0bac9a13dd5d3cb38e9e2230f73a2c6df3efdc66), but I failed to compile this version i.e. this repository at this commit. Version commit [34307b6](https://github.com/be5invis/Iosevka/tree/34307b6e8554a2281ef36b0cd3cd9c57c23162c9) is the nearest commit after it that compiles.

**Comment by be5invis** [comment]
Do you want more slope for the inner bar, or changing the metrics of the circle?

**Comment by nathanielevan** [comment]
More slope for the inner bar, I think! I'm not a font expert but I can't seem to make out any difference in the metrics of the circle between the two versions -- the slope is the only thing that stands out to me

**Comment by be5invis** [comment]
It will be added in version 24. Resolve as fixed.
