### ISSUE TITLE
In Visual Studio, som rows are lower than normal if has no letter.

### ISSUE THREAD

**Issue by Elderry** [be5invis/Iosevka#151]
* Your font version: 1.11.0
* Your font variant: SC
* Your operating system (name and version): Win 10 Pro 14393.693
* Your application using Iosevka: Visual Studio Community 2015
As shown below, line 45, 46 and 48 is lower than others:
![capture](https://cloud.githubusercontent.com/assets/1892221/23057236/22b26ec8-f52a-11e6-868e-d3955a138d83.JPG)

**Comment by be5invis** [comment]
Looks like a VS issue, probably because letters being too “large”?
Closed as external.

**Comment by Elderry** [comment]
You're right, I've found [the solution](http://stackoverflow.com/questions/25351636/visual-studio-different-line-heights-in-the-editor) for my problem.
