### ISSUE TITLE
U+0427, U+0447 unsymmetric bottom serif

### ISSUE THREAD

**Issue by pv4** [be5invis/Iosevka#1513]
In upright/italic slab variants of 17.0.2 U+0427, U+0447 (uppercase and lowercase cyrillic che) have unsymmetric bottom serif. Derived variants (e.g. U+04B7, U+04BA, etc) are affected as well.

16.3.6 had a correct look with symmetric serif. The pictures attached contain 3 columns:
1. difference between columns 2 and 3: red is what only present in column 2 (old version, 16.3.6), green is what only present in column 3 (new version, 17.0.2),
2. glyph image in old version (16.3.6),
3. glyph image in new version (17.0.2).

![image](https://user-images.githubusercontent.com/2502094/211380957-0780a486-0a8a-4d2d-b995-eada71b0fa58.png)
![image](https://user-images.githubusercontent.com/2502094/211381046-ec08201d-459d-4e88-af94-20368187cd64.png)
![image](https://user-images.githubusercontent.com/2502094/211381304-768c9ab7-5ad3-4cea-86f5-a345acac145b.png)
![image](https://user-images.githubusercontent.com/2502094/211381353-134e7dd6-8b42-494c-9249-efca29943c3a.png)

**Comment by be5invis** [comment]
This is intensional, these "side" serifs will be asymmetric, just like `L` and `Γ`.
Resolve as by design.
