### ISSUE TITLE
Chruch Slavonic (Cyrillic) Letters

### ISSUE THREAD

**Issue by Logo121** [be5invis/Iosevka#1517]
- The requested character is...
  - [ ] Latin
  - [x] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [ ] Symbol
- [x] Some other monospace/programming fonts supported this character. Provide images below.

------

(This is for backlogging mostly.) Mentioned in #1515, Hyperglot notes 4 letters necessary to support the old Cyrillic Alphabet used for Church Slavonic. This issue is a collection of these letters, + two that are related to those letters.

Monospace fonts that support them (+non-monospace for reference):
![image](https://user-images.githubusercontent.com/21302803/211622386-a6f4c0e8-72f7-4d2f-bf7e-6c40f840a57b.png)

Text: `Ꙁꙁ Ꙗꙗ Ꙃꙃ Ꙋꙋᲈᲂу`

Notes:
* Most fonts render the letter Zemlya with a long tail, but Brill renders it with a short one (resembling greek Zeta). This version is probably still correct as per wiki: ![](https://upload.wikimedia.org/wikipedia/commons/a/ae/Early_Cyrillic_letter_Zemlia.png)
* The most problematic one is probably the monograph Uk:
  * The uppercase `Ꙋ`, which may or may not have the tail (going through the O). 
  * The lowercase `ꙋ` has the two letters blending (looking somewhat like gamma), with a non-blended version `ᲈ` for contrast. So the JuliaMono's version of the former might be wrong.
  * Unicode additionally provides a "narrow o" `ᲂ` for composing the letter as `ᲂу` (like shown in the screenshot). The "narrow" part seems to be ignored by Noto Sans Mono.

**Comment by cormullion** [comment]
> * So the JuliaMono's version of the former might be wrong.

Please open an issue [here](https://github.com/cormullion/juliamono) as well. 😂

**Comment by be5invis** [comment]
Far-future target

**Comment by Logo121** [comment]
> > * So the JuliaMono's version of the former might be wrong.
> 
> Please open an issue [here](https://github.com/cormullion/juliamono) as well. :joy:

Done.

> Far-future target

Fair enough. This is a subset of #1142 which is marked far future as well anyway.

I'll just throw in [the original proposal](https://www.unicode.org/wg2/docs/n4607.pdf) (also mentioned in the JuliaMono issue) and [this technical note for church slavonic](https://www.unicode.org/notes/tn41/tn41-1.pdf) for future reference.

**Comment by be5invis** [comment]
For Uk I may follow Noto Sans Mono's uppercase and Brill's lowercase.
