### ISSUE TITLE
Minor z=cursive* regressions between 16.3.6 and 17.0.2

### ISSUE THREAD

**Issue by pv4** [be5invis/Iosevka#1519]
17.0.2's lowercase and uppercase z (and all related glyphs, including e.g. U+0225 but not only) have two minor regressions relative to 16.3.6:
1. the top-left and bottom-right inner curves are more "cornered"/"sharp", not so "round"/"smooth" as before,
2. the crossing central bar overflows with top-left element (even on regular weight).

According to the diff picture attached this is probably related to z having larger width in the previous versions.

The picture attached contain 3 columns:
1. difference between columns 2 and 3: red is what only present in column 2 (old version, 16.3.6), green is what only present in column 3 (new version, 17.0.2),
4. glyph image in old version (16.3.6),
5. glyph image in new version (17.0.2).

![image](https://user-images.githubusercontent.com/2502094/211617620-c8db3c7e-e8e2-4d4b-b78d-f2d96e5499e1.png)

Please, feel free to just close the issue if it's expected or hard to fix.

**Comment by be5invis** [comment]
It is mostly intensional. Though could be still improved a little.
