### ISSUE TITLE
combining long stroke overlay character looks strange

### ISSUE THREAD

**Issue by geier** [be5invis/Iosevka#152]
* Your font version: 1.11.0
* Your font variant: term
* Your operating system (name and version): 11.0-RELEASE-p2 FreeBSD
* Your application using Iosevka: gnome-terminal 3.18.1

If unicode character "combining long stroke overlay" (U+0336) is combined with "regular" characters, the rendering looks at bit off:

![iosevka](https://cloud.githubusercontent.com/assets/275330/23093385/644febbc-f5d9-11e6-9e59-6b8f2f9ab734.png)

I used the code sample from [this issue](https://github.com/pimutils/khal/issues/580#issuecomment-280843170), where you can also find examples of how this looks with DejaVu Sans Mono and M+1mn.

While I'm not sure if "combining long stroke overlay" should go in front or behind the character that is supposed to be strikken, my main issue here is, that the strokes seem to be sometimes missing and/or are unaligned.

**Comment by be5invis** [comment]
You mean U+0336 should be placed in a uniform height?

**Comment by geier** [comment]
yes, and preferably event make them touch each other.

**Comment by be5invis** [comment]
Fixed in 1.11.1. Closed.

**Comment by geier** [comment]
Thank you!

Quoting Belleve Invis (2017-02-20 03:22:29)
