### ISSUE TITLE
Closer descenders (hooks?) of almost all glyphs in 17.0.2 relative to 16.3.6

### ISSUE THREAD

**Issue by pv4** [be5invis/Iosevka#1520]
I looked through glyph diffs between the versions mentioned in the issue title and almost all (I even think, ALL) glyphs with descenders  now have descenders positioned closer making glyphs narrower, and making the descenders less distinguished (in terms of horizontal distance between the descender right end and the base glyph).

The pictures attached contain 3 columns:
1. difference between columns 2 and 3: red is what only present in column 2 (old version, 16.3.6), green is what only present in column 3 (new version, 17.0.2),
2. glyph image in old version (16.3.6),
3. glyph image in new version (17.0.2).

U+049B.cv61=2 :
![image](https://user-images.githubusercontent.com/2502094/211622818-8f3c9717-672b-43f0-9881-a16134a46241.png)

Much better noticable on curly k (U+049B.cv61=2):
![image](https://user-images.githubusercontent.com/2502094/211623150-d9909e4f-f580-4ff5-8e28-24db2d30e943.png)

But the most noticable on cyrillic zhe (U+0496, U+0497):
![image](https://user-images.githubusercontent.com/2502094/211623717-ba45d9f3-8a9b-4666-a409-619c32d8e677.png)

I've never seen these "with descenders" letters in real life but it seems for me something is wrong with U+0496, U+0497 at least. Because of such my experience, please, feel free to just close the issue if such behavior is expected (and I'm sorry then).

**Comment by be5invis** [comment]
This is intentional (as we unify downward hooks/descenders). Resolve as by design.

**Comment by pv4** [comment]
> we unify downward hooks/descenders

Unification is always a good thing.

Thanks for the explanations, both in this issue and in other ones!
