### ISSUE TITLE
Descender horizontal offset mismatch for curly and non-curly variants

### ISSUE THREAD

**Issue by pv4** [be5invis/Iosevka#1521]
Non-curly U+049B, U+049a, U+2C69 variants have descenders with larger horizontal shift to the right than the curly variants, thus making the descenders of non-curly variants distinguished better, than of curly ones.

U+049B.cv61=13 (non-curly)
![image](https://user-images.githubusercontent.com/2502094/211625965-66034e26-d1db-476c-bfea-86aaa505e486.png)
U+049B.cv61=14 (curly)
![image](https://user-images.githubusercontent.com/2502094/211626026-fe98f1e0-5c68-4e41-898e-4a6ecf6d5aeb.png)

I can't believe this is intentional. If you decide to fix curly variants by increasing descender's shift to the right, then could you please consider NOT closing this issue ASAP and altering other glyphs (all necessary variants) as well? Expecially U+0496, U+0497 and probably their non-slab/italic/italic-non-slab variants (but, I know, these are already too wide by themselves, so... use your taste).

![image](https://user-images.githubusercontent.com/2502094/211629284-b6154f0e-418a-4c1b-a7f2-21362b9e41a4.png)
![image](https://user-images.githubusercontent.com/2502094/211629328-ad57cccf-a5ef-493c-acfd-2fc119898ad4.png)
![image](https://user-images.githubusercontent.com/2502094/211629776-850bb917-2516-4e7f-827b-e71d50744ca7.png)
![image](https://user-images.githubusercontent.com/2502094/211629812-b4792c0a-96d8-49e4-a11e-c763ae7ffda9.png)
![image](https://user-images.githubusercontent.com/2502094/211631381-63c5f0fe-ddad-4281-b491-28bc21963fe1.png)

**Comment by be5invis** [comment]
Attached descenders' rightmost position should align to the position of corresponded serifs. May need fixing K and Zhe.
