### ISSUE TITLE
Ability to distinguish between Greek Tonos and Greek Oxia

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1527]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------
The way the Greek language handles diacritics in monotonic vs polytonic dialects is slightly different. The monotonic "Tonos" accent from the Greek and Coptic block should be more vertical, and the polytonic "Oxia" accent from the Greek Extended block should be how it already is currently.<br>example with Code2000 and Tahoma from Wikimedia:<br> ![Alpha with tonos and oxia](https://upload.wikimedia.org/wikipedia/commons/2/2d/Alpha_with_tonos_and_oxia.png)
Essentially, the Tonos would be handled kind of like a vertical line above (or above-left for capital letters) and Oxia would be completely unchanged from how it is now.

**Comment by be5invis** [comment]
At least in Unicode's NFD level they are not differentiated: `ά` (U+03AC) and `ά` (U+1F71) decomposes to the same sequence.

**Comment by dscorbett** [comment]
Since Unicode unifies tonos and oxeia, the only stable way for a font to distinguish them, which isn’t required, is to use language system tags.
