### ISSUE TITLE
17.0.3 shape regressions

### ISSUE THREAD

**Issue by pv4** [be5invis/Iosevka#1532]
Some glyphs had changed shapes in 17.0.3. I attach the diff images of those that imho became worse and probably were not expected to change their shapes in the way demonstrated. Feel free to fix any of the shapes or keep them as is if the look is expected.

The pictures attached contain 3 columns:

1. difference between columns 2 and 3: red is what only present in column 2 (old version, 17.0.2), green is what only present in column 3 (new version, 17.0.3),
2. glyph image in old version (17.0.2),
3. glyph image in new version (17.0.3).

---

U+1D7AB, sans/slab italic (similar is applied for U+1D737 sans/slab italic); in much less degree this also happens in U+1D6C3 slab italic.

![image](https://user-images.githubusercontent.com/2502094/212537792-555c42a3-1131-4fc9-93cb-c7c30c2eab74.png)

---

U+1D47A.cv18=3 sans/slab italic (also U+1D412 slab italic)

![image](https://user-images.githubusercontent.com/2502094/212538022-10f975f1-7882-41fa-94e1-7e9563b00fc9.png)

cv18=2 slab italic is good

![image](https://user-images.githubusercontent.com/2502094/212538107-90485d79-9ae0-4fb8-9fbe-520a8b61b69a.png)

---

U+1D494.cv43=3 slab italic

![image](https://user-images.githubusercontent.com/2502094/212538275-9f246bdb-dff8-4e4a-a4f9-1692d8f25e81.png)

---

U+1D484.cv28=3 slab italic

![image](https://user-images.githubusercontent.com/2502094/212538348-ea13b010-2d5d-441a-9142-e8fd2ea5758a.png)

---

U+1D7B5, 1D741 sans/slab italic (not so bad as previous ones but still); in the new variant the bottom arc looks too "straight", unlike in the previous one

![image](https://user-images.githubusercontent.com/2502094/212538474-be3b917d-6a26-44df-8e91-5ee0c6772c3a.png)

---

I tested only regular weight. It looks like the issues mostly happen on bolder weights, so bolder font weights can probably suffer more.

**Comment by be5invis** [comment]
This is intensional, as a part of unifying "oblique" arch control knots.
Resolve as by design.

**Comment by be5invis** [comment]
I can do some refinements though
