### ISSUE TITLE
Crossed "Q" that does NOT descend below the baseline

### ISSUE THREAD

**Issue by JapanYoshi** [be5invis/Iosevka#1533]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

It would be great if all-caps text all fit between cap height and baseline.

Consola Mono:
![image](https://user-images.githubusercontent.com/8707990/213913289-4e9091ca-5594-40dc-bcd0-642255406901.png)
Ellograph: 
![image](https://user-images.githubusercontent.com/8707990/213913308-e5e4a224-72cb-4a4d-a2a3-fa4a67c0ff04.png)
Fairfax HD:
![image](https://user-images.githubusercontent.com/8707990/213913313-dfc8a574-f5cd-498d-b329-c0b27df386e3.png)

**Comment by be5invis** [comment]
This should be a valid req. Reopen.

**Comment by Logo121** [comment]
closable?
