### ISSUE TITLE
Cannot build from source on node v19.4.0 (Arch Linux)

### ISSUE THREAD

**Issue by charbelnicolas** [be5invis/Iosevka#1536]
No matter what I try on my custom build, either the build fails, the terminal freezes or the whole computer freezes.

---

* Your font version: 17.1.0 (Git)
* Your font variant: Custom ss03 build with variations
* Your operating system (name and version): Arch Linux
* Your application using Iosevka:  Kitty Terminal

If you have problem when building Iosevka, please provide these information:

* Your Node.js version: 19.4.0

* Your `private-build-plans.toml`, if present:
```
[buildPlans.iosevka-sans-fixed-ss03]
family = "Iosevka Sans Fixed ss03"
spacing = "fixed"
serifs = "sans"
no-cv-ss = true

	[buildPlans.iosevka-sans-fixed-ss03.variants]
	inherits = "ss03"

		[buildPlans.iosevka-sans-fixed-ss03.variants.design]
		one = "no-base"
		f = "flat-hook-crossbar-at-x-height"
		l = "serifed-flat-tailed"
		at = "threefold"
		brace = "curly"
		question = "smooth"
		capital-m = "slanted-sides-flat-bottom"
		capital-w = "straight-flat-top"

		[buildPlans.iosevka-sans-fixed-ss03.variants.italic]
		one = "no-base"
		a = "double-storey-toothless-corner"
		f = "flat-hook-tailed-crossbar-at-x-height"
		l = "serifed-flat-tailed"
		at = "threefold"
		brace = "curly"
		question = "smooth"
		capital-m = "slanted-sides-flat-bottom"
		capital-w = "straight-flat-top"

		[buildPlans.iosevka-sans-fixed-ss03.variants.oblique]
		one = "no-base"
		f = "flat-hook-crossbar-at-x-height"
		l = "serifed-flat-tailed"
		at = "threefold"
		brace = "curly"
		question = "smooth"
		capital-m = "slanted-sides-flat-bottom"
		capital-w = "straight-flat-top"
```
* The detailed error log:

![20230126_190054](https://user-images.githubusercontent.com/14960414/214977978-388fb1c7-5e9f-4d62-9834-e6b30ab2dbe1.png)

**Comment by be5invis** [comment]
"Error loading cache" is ignorable (it is related to the caching system which speeds up second builds).
Uncahed build on my system (AMD 3970X) takes 10 minutes _per weight_, so it is slow if it is uncached.

**Comment by pv4** [comment]
> the terminal freezes or the whole computer freezes

Looks like out-of-memory issue (I had those). Can you monitor ram (rss) and cpu usage during the build?

**Comment by alexeyten** [comment]
May be this could help? 
https://github.com/be5invis/Iosevka/issues/847#issuecomment-805299137

**Comment by charbelnicolas** [comment]
I have 32 gigs of ram... I don't think that's it. I think it has more to do with the CPU being at 100% most of the time while building.

FWIW, I was able to build from source today with no errors or freezes. It is too random :(

**Comment by pv4** [comment]
> I have 32 gigs of ram... I don't think that's it.

AFAIK iosevka build process creates a process per cpu core. Each process requires something between 0.5GiB and 1GiB RAM. If you have 24-core cpu then 12-24GiB ram required for the build process. Add some ram usage for memory-leaking software like java- and electron-based, a browser with couple of opened tabs, a couple of virtual machines - and your 32GiB are gone.

What I want to say, I still believe it could be out-of-memory issue. The fact today you were able to build it successfully could mean today you were running less software then yesterday and more ram was free. Anyway, it's fine you've built iosevka successfully. But if (when) you have the similar issue next time you will know what can possibly be the root of the problem.
