### ISSUE TITLE
without-notch looks like it has a notch still

### ISSUE THREAD

**Issue by Seanld** [be5invis/Iosevka#1537]
The "no-notch" variant of the dashes appears to have a notch when zoomed out / font is small. What I _expected_ was that they would appear fairly smooth, because I don't want any "bump" on my dashes (it's super ugly imo).

Here's an example from Emacs' dired:

![Screenshot from 2023-01-27 09-51-17](https://user-images.githubusercontent.com/9366109/215146888-faea1813-129a-4ad0-af86-f7d142be327c.png)

![Screenshot from 2023-01-27 09-51-02](https://user-images.githubusercontent.com/9366109/215146918-b29f492b-ecc3-471b-856f-3cd474c9dce2.png)

---

* Your font version: Can't remember - quite recent
* Your font variant: Custom?
* Your operating system (name and version): Arch Linux (rolling)
* Your application using Iosevka: Emacs

In case it's a build plan issue, here's that:

[private-build-plans.toml.txt](https://github.com/be5invis/Iosevka/files/10521226/private-build-plans.toml.txt)

**Comment by be5invis** [comment]
Connected hyphens are controlled by ligation system's config (by enabling `connected-hyphen-as-solid-line`).
I should modify this... turning it into using variations.

**Comment by Seanld** [comment]
Oh, duh, I was referring to the "without-notch" value of "lig-equal-chain". Although the dashes were also a problem, so that's good to know. Thank you.

How would I go about smoothing out the connected equals symbols? Unless I'm running an old build of my config (work machine has less RAM than my home PC, so I can't check), I seem to still have notch cutout in my `==` and `===`.

**Comment by be5invis** [comment]
Version 18 will move the notch options into variant system. In addition, arrow rods can gain notches starting this version.

**Comment by be5invis** [comment]
Well the glyphs overlap a little. You should blame rasterizer (Apple?) about they are not properly implementing transparency/antialiasing/whatever.
Resolve as fixed.
