### ISSUE TITLE
Support a rounded variant

### ISSUE THREAD

**Issue by mjvh80** [be5invis/Iosevka#1540]
First off, great work, I really enjoy using (and customizing) this font!

I read somewhere this font was partially inspired by M+ (which I take to be [this](https://fonts.google.com/?query=M++Fonts+Project) one), looking at that font it turns out they have two variants: rounded and square.

To be precise, rounded looks like

![image](https://user-images.githubusercontent.com/562193/215791690-2bde8d79-3bb7-4349-be6e-b9e8d79e7265.png)

and the standard square variant:

![image](https://user-images.githubusercontent.com/562193/215791907-baa0d29b-4571-40b2-b6c4-6dd9b456ac00.png)

I've tried taking a look if this is configurable or doable, alas I got lost down the rabbit hole.

Thus my feature request would be to support a configuration option to round the glyphs as per the above screenshot, if this is something you would consider (and doesn't yet exist). I personally think the rounded font can look nicer particularly for larger font sizes.

**Comment by be5invis** [comment]
To support this I will need to add option to **EVERY** shape in the font. It could be better to have a separate tool that "rounds" contours.
