### ISSUE TITLE
Less pointy `greater` and `less`

### ISSUE THREAD

**Issue by shytikov** [be5invis/Iosevka#1542]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

Hej!

First of all, thank you for amazing work. I'm a huge `PragmataPro` fan, but honestly, you have overdone it by a mile! 

I'm currently working on my customization that suits me best, and have found several glyphs that would be very awesome to have.

I'm talking about `greater` and `less` that would be less "pointy", more elongated in vertical direction. 

I think these glyphs will be very much inline with condensed nature of Iosevka and in addition will provide more clarity when reading text in small size. I think it will improve readability for cases comparison cases in any programming language used. 

I think `Consolas` is great example here. Despite being ages old, it getting this aspect perfectly.

<img width="532" alt="image" src="https://user-images.githubusercontent.com/107051036/216950510-bf320110-fcde-408c-8055-cdd9f95269e0.png">

🙏 🙇

**Comment by be5invis** [comment]
Maybe simply increase slope instead of adding a variant.

**Comment by shytikov** [comment]
Is it possible to control this angle on per-character basis during custom build?

**Comment by be5invis** [comment]
I just made it universally wider... should look good now.

**Comment by rben01** [comment]
Would it be possible to make the choice configurable, e.g., `angle-bracket: "wide"` and `angle-bracket: "narrow"`? I preferred the old, narrower style.

**Comment by properly-strawberry** [comment]
Hm, to me the wider angle brackets do feel more natural, the old ones seem very squashed in comparison. Agreeing with shytikov - it feels more aligned with the condensed nature of the font.

Could still be a variant with default new ones.

**Comment by aaronmbos** [comment]
Really enjoy the new, wider shape of the less-than and greater-than signs 🙌!
