### ISSUE TITLE
javascript ligations triple equal

### ISSUE THREAD

**Issue by svipas** [be5invis/Iosevka#1546]
Previously `javascript` ligations contained thicker triple equal (`===`) and triple not equal (`!==`). Even in customizer it marks them as different, but still build and web preview produces them the same as it was.

<img width="914" alt="SCR-20230211-q5b" src="https://user-images.githubusercontent.com/10441177/218270399-c72b5fd2-97b5-448e-b07f-418725179f2d.png">
<img width="909" alt="SCR-20230211-q5n" src="https://user-images.githubusercontent.com/10441177/218270402-5a0c1f2b-79c3-4c3a-8483-84112d8e0e67.png">

**Comment by be5invis** [comment]
Already fixed in dev
