### ISSUE TITLE
Preview Text Area in Iosevka Customizer

### ISSUE THREAD

**Issue by ANK-dev** [be5invis/Iosevka#1551]
I'd like try out some customizations in the Iosevka Customizer page by being able to type some text in a `<textarea>` and have it render with customizations applied.

At the moment it's only possible to preview the selected character variants in the small sample on the right side of the page. The problem with this is that it can be difficult to visualize how well some character customizations can go along with other sequences of characters.

For example, trying the different variations in height of the underscore and seeing how it looks next to alphanumeric characters (`snake_case`). Or checking the height of the caret next to tildes as is frequent in gcc messages (`~~~~~^~~~~~`). At the moment these only appear in isolation with other special symbols.

**Comment by ANK-dev** [comment]
Bump

**Comment by lcnbr** [comment]
I would love this as well. Currently, it is hard to iterate on font builds.
