### ISSUE TITLE
[Windows Terminal] Long sequences of repeating characters are misaligned

### ISSUE THREAD

**Issue by ANK-dev** [be5invis/Iosevka#1553]
* Your font version: 19.0.1 (Release or git, version)
* Your font variant: Iosevka Term
* Your operating system (name and version): Windows 11 22H2 [Version 10.0.22621.1265]
* Your application using Iosevka: Windows Terminal Preview 1.17.1023

---

Typing long sequences of repeating characters like `------` or `!!!!!!!!!` on the Windows Terminal causes them to get misaligned within the grid, such that the cursor position no longer corresponds to location where typed characters appear. I don't know if this bug is related to Iosevka or the Windows Terminal. If the latter, let me know and I will forward it to the Windows Terminal issue tracker.

https://user-images.githubusercontent.com/40664661/219903123-a46ce393-3c76-4ef5-b57e-856121d62366.mp4

**Comment by be5invis** [comment]
`-------` don't ligate in default settings for Term. Should be a WT bug.

**Comment by lhecker** [comment]
I work on Windows Terminal and I'm pretty confident to say that this is indeed an issue on our side. I've opened a PR to fix the issue.
