### ISSUE TITLE
C/C++ ligature false positives. 

### ISSUE THREAD

**Issue by oshaboy** [be5invis/Iosevka#1555]
In C++ you can put constant parameters in templates. So `MyTemplate<-1>` is valid syntax. But even with the "C-like" ligations enabled it still misidentifies it as a left arrow. I don't know if any C like languages that use a `<-` for anything but if there is then please split C++ ligatures from ligatures from that language. It's also a problem with comparing variables to negative numbers (`x<-1`)

Similar problems exist for every ligature with either a C/C++ unary prefix operator on its right (besides `/*`), or a unary postfix operator on its left. So... 
```
Ligature | False Positive with
--------------------
<--      | x<--y;
<<-      | x<<-y; 
<-       | x<-y; x<-1;
-->      | x-->y;
<~       | x<~y;
<*       | x<*y;
<.       | x<.1;
.>       | 1.>x;
<!--     | x<!--y;
:-       | label:--x;  
:+       | label:++x;
```

**Comment by be5invis** [comment]
It could be interesting to define a ligation group that completely disables arrows...

**Comment by oshaboy** [comment]
But C and C++ use right arrow for member access

**Comment by be5invis** [comment]
Yes this adds a lot of complexity: we need to only disable *some* arrows, but allowing the other...
One thing that I could do is to add some "bypassing" rules that recognizes certain glyph patterns and replacing them into doppelganger glyphs, so they will no longer participate ligation.

**Comment by be5invis** [comment]
Or, perhaps, enhance the editor wo they will not shape two different tokens together (so `<-` will be treated as `<` and `-`, never ligates).

**Comment by oshaboy** [comment]
I had a look at the "C-like" ligations and you could easily remove about half of them without affecting any C-like language I am aware of. 

Also I found more C false positives and even some Perl false positives.

**Comment by jmcwilliams403** [comment]
You could also make it sensitive to whether or not there's a space between the token and the variable

**Comment by be5invis** [comment]
Now C-like languages' ligation set will only enable a very limited set of ligations (for example, it even disables left-pointing arrows).
Resolve as fixed

**Comment by oshaboy** [comment]
By the way, the website still shows the old ligatures.

**Comment by oshaboy** [comment]
Doesn't matter, I assume it will be fixed when Iosevka 20 releases
