### ISSUE TITLE
How do I get the Nerd Font glyphs for the Term SS07 (Monaco) stylistic set?

### ISSUE THREAD

**Issue by j-rahman** [be5invis/Iosevka#1567]
I have downloaded and installed the `Iosevka Term SS07 (v19.0.1)` font from [this page](https://github.com/be5invis/Iosevka/blob/v19.0.1/doc/PACKAGE-LIST.md). I have also installed `font-iosevka-nerd-font (2.3.3)` using Homebrew.

It looks like some (Powerline) glyphs are not rendered properly with the `Iosevka Term SS07 (v19.0.1)` font as you can see in the screenshot below.
<img width="921" alt="Iosevka_SS07" src="https://user-images.githubusercontent.com/24459756/221286504-261b1bbc-e001-4156-b2f2-092ade9f75ed.png">
However, they render properly with `font-iosevka-nerd-font (2.3.3)` as shown below.
<img width="921" alt="Iosevka_NF" src="https://user-images.githubusercontent.com/24459756/221286729-ae9c5185-20c5-44f1-a75b-74d5f7afb2a3.png">
I am not familiar with the business of patching fonts. I would greatly appreciate if you could please point me in the right direction to obtain Iosevka SS07 Nerd Fonts. They seem to be unavailable on Homebrew or over here in this repository. Thank you.

**Comment by be5invis** [comment]
Iosevka doesn't have (and never planed to add) Nerd glyphs at all. Patch it yourself.
Resolve as out of scope.

**Comment by AndydeCleyre** [comment]
@j-rahman 

FWIW:

- if you're on Linux you don't need to patch fonts, you can tell fontconfig about a fallback procedure
- some terminal emulators will allow you to configure a font fallback procedure on their side (wezterm being a cross-platform example)
