### ISSUE TITLE
Tiny serif-like overshoot in glyph id 5171

### ISSUE THREAD

**Issue by mva** [be5invis/Iosevka#1571]
`iosevka-term-ss11-medium.ttf` from
`ttf-unhinted-iosevka-term-ss11-19.0.1.zip`:

glyph-id 5171 / not a code point? -- "19."

The horizontal line in the "9" on the right overshoots the curve
coming from below by a tiny amount.  At first I thought this looks
similar to the Hryvnia sign earlier, two segments trying but failing
to meet in a single point.  Unter magnification the lines' meet looks
more complicated, with an additional curve leading into the zero
width overshoot.

Btw, that's the last glyph id from my list.  It was a very short list
to begin with.  I'm impressed how clean Iosevka's geometry is.

![grafik](https://user-images.githubusercontent.com/225983/221409314-634d4b79-19e9-4182-a477-f2320821d972.png)

![grafik](https://user-images.githubusercontent.com/225983/221409394-522235db-499f-4fad-aa2c-6650ea2f2299.png)

**Comment by be5invis** [comment]
Perhaps, one suggestion, is you could improve your code's resiliance to "pathelogical" geometry (TT spec DO allow that). I could do some fixes, but do not assume EVERYONE will do that (especially for recent variable fonts).
