### ISSUE TITLE
Latin Extended C/D: Four characters (or two letters + casing) with descender

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1572]
- The requested character is...
  - [x] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [ ] Symbol
- [x] Some other monospace/programming fonts supported this character. Provide images below.

------

U+2C67..U+2C68, U+A790..U+A791
Julia Mono:
![image](https://user-images.githubusercontent.com/37010132/222168321-0ddad47d-ee11-4f87-b6cc-cb93c7447468.png)

**Comment by Logo121** [comment]
this can be closed now?
