### ISSUE TITLE
CV94 has no effect on U+00A6

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1575]
`bar = "force-upright"`
![image](https://user-images.githubusercontent.com/37010132/222965111-0e30a4c4-ec75-4fe7-88b3-b3a1cfb3655a.png)
only the ASCII bar is affected, not the Latin-1 Broken Bar.

**Comment by be5invis** [comment]
This is intentional (otherwise, we need to apply it to all kinds of "bar" or "slash" characters).
Resolve as by design.
