### ISSUE TITLE
Bigger and Pointier Caret

### ISSUE THREAD

**Issue by ANK-dev** [be5invis/Iosevka#1576]
- [X] The requested variant shape does not go too far away from Iosevka's design.
- [X] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

I'd like to suggest a variant for a bigger and pointier caret, with a shape more akin to a `>` rotated 90 degrees or an upside down `v`.

I feel that the current one is too small and flat and can be hard to read at smaller font sizes. 

Iosevka Term Custom:
![Iosevka Term Custom](https://user-images.githubusercontent.com/40664661/222986524-87862bb4-5801-4d6c-845a-52a79f78937d.png) 
![image](https://user-images.githubusercontent.com/40664661/222987075-4eb4ae15-be20-40a1-9467-c0588323c319.png)

Compared to other fonts. I especially like Plex's design, which is highly legible.:

IBM Plex Mono:
![IBM Plex Mono](https://user-images.githubusercontent.com/40664661/222986429-9e2b4f7e-f6b3-49aa-84d9-579cae67a7f2.png)
![image](https://user-images.githubusercontent.com/40664661/222987279-86aa81e9-017a-4445-b248-75a9128b1e30.png)

<br>

Consolas:
![Consolas](https://user-images.githubusercontent.com/40664661/222986350-d054665e-d3c7-4550-b0bd-f0455e876b6c.png)
![image](https://user-images.githubusercontent.com/40664661/222987353-8443485a-1a66-42f7-a592-1a57838f5fe6.png)

<br>

Fira Code:
![Fira Code](https://user-images.githubusercontent.com/40664661/222986482-c2f9f3eb-5faa-47fc-9e33-40d4b7c118bd.png)
![image](https://user-images.githubusercontent.com/40664661/222987299-21d9dcfc-01ec-4162-b860-db157ddc91eb.png)

**Comment by be5invis** [comment]
I'd rather simply enlarge the shapes.
