### ISSUE TITLE
Cedilla is disconnected from serifed italic glyphs on heavier weights

### ISSUE THREAD

**Issue by pv4** [be5invis/Iosevka#1579]
Below are what I found. There can be other affected glyphs.

![image](https://user-images.githubusercontent.com/2502094/222989419-0a894550-36ed-4179-b0e0-87bfaec56920.png)

**Comment by pv4** [comment]
U+1E08 and U+1E09 are still unfixed as of 21.0.0

**Comment by be5invis** [comment]
Fixed in dev.
