### ISSUE TITLE
regular vs medium: same weight or not?

### ISSUE THREAD

**Issue by t184256** [be5invis/Iosevka#158]
Are regular and medium meant to be the same width or not?

The README states:
> The typeface contains seven weights (thin, extra-light, light, regular, medium, bold and heavy)

But for me, regular and medium have the same weight (tested on two debian stretch systems, both with release ttf and a custom variant built from git. apps: gnome-terminal, xfce4-terminal, gnome-specimen).

**Comment by be5invis** [comment]
No, they are not.
![image](https://cloud.githubusercontent.com/assets/240091/23601160/0d909e44-0285-11e7-8cfd-b9df8e0dce66.png)
Perhaps your app cannot distinguish them.
Closed as external.
