### ISSUE TITLE
Heavy-weight serifed Latin C With Hook and similar have cornered shapes instead of rounded ones

### ISSUE THREAD

**Issue by pv4** [be5invis/Iosevka#1580]
I suppose the glyphs mentioned in the issue title should have rounded shapes in some cases, whereas in the current version having cornered shapes. I mean the inner connecting "corner" between some arc of a glyph and a serif.

I found the following (there can be other ones):
U+0187 all
U+0188 all
U+025B (?)
U+025C slab-italic
U+025D slab-italic
U+0437 slab-italic
U+046F slab-italic
U+04DF slab-italic
U+1D08 slab
U+1D4B slab
U+1D4C slab
U+A731 all
U+AB67 slab-italic (so indistinguishable so I'm not sure this glyph has the issue)

Some examples:

U+0187
![image](https://user-images.githubusercontent.com/2502094/223498841-f8cf8cd8-c0fd-40f2-87ba-24f92b472fc2.png)

U+025B, U+025C, U+025D, 

![image](https://user-images.githubusercontent.com/2502094/223499881-bffedca6-11d1-4a27-9892-bae607857c6b.png)

U+04DE (correct), U+04DF (buggy)
![image](https://user-images.githubusercontent.com/2502094/223500740-814816cd-18cc-42bc-aeb4-fca05d900a0c.png)

**Comment by pv4** [comment]
Still an issue in U+A731.

![image](https://user-images.githubusercontent.com/2502094/226293763-e1191db4-411e-4ea4-9c46-847d2bab2046.png)

**Comment by be5invis** [comment]
@pv4 Next time when you find similar "remaining" issues, file a new bug instead of replying.
