### ISSUE TITLE
Serifed U+0480 and U+0481 should have bottom serif

### ISSUE THREAD

**Issue by pv4** [be5invis/Iosevka#1584]
First of all, I have never seen this letter before and never used it so I might be wrong. But I accidently found that its slab variants should probably have bottom serifs.

![image](https://user-images.githubusercontent.com/2502094/223517010-998bf9d3-89cf-4b12-9916-cec6e5a80268.png)

See also:

https://www.unicode.org/charts/PDF/U0400.pdf
![image](https://user-images.githubusercontent.com/2502094/223517750-e6028f1a-0359-4261-95d3-82ed19365066.png)

https://unicode.scarfboy.com/?s=U%2B0480
![image](https://user-images.githubusercontent.com/2502094/223517903-2d34b32d-c993-4db6-a2d3-876141ea17c9.png)

**Comment by pv4** [comment]
Thanks!

Shouldn't cv28=1 be serifless?

![image](https://user-images.githubusercontent.com/2502094/224584897-0d4f83e0-900c-4824-9212-7de9a29a5d60.png)

**Comment by be5invis** [comment]
Fixed
