### ISSUE TITLE
Heavy-weight Rs (U+20A8) multiple issues

### ISSUE THREAD

**Issue by pv4** [be5invis/Iosevka#1585]
The "Rs" glyphs looks like there is no enough room for its components. Please look through the whole Rs variant table yourself as it's too huge to place it here with enough details visible:

![image](https://user-images.githubusercontent.com/2502094/223522152-2e8e02ae-0b0d-42e0-9e0c-ddcfc05b9d19.png)

But I found that they generally have two kinds of issues:
1. cv17=4,5,10,11 have issues near the point where the leg connects to the arc (the higher red mark at the attached picture),
2. slab variants have leg endings outside of the bottom serif (the lower red mark at the attached picture).

![image](https://user-images.githubusercontent.com/2502094/223521611-7021aae5-f3f4-46ed-b355-a69f66dffde3.png)

**Comment by pv4** [comment]
Thanks!

The issue is mostly fixed. But it's still exists in slab (but not sans), upright/italic with cv17=10 only.

![image](https://user-images.githubusercontent.com/2502094/224865432-099c8e3e-e495-468c-a824-b02cbe560a8f.png)

**Comment by be5invis** [comment]
Fixed
