### ISSUE TITLE
A collection of characters derivable from existing characters under rigid motion(?)

### ISSUE THREAD

**Issue by Logo121** [be5invis/Iosevka#1597]
- The requested character is...
  - [x] Latin
  - [x] Cyrillic
  - [ ] Greek
  - [x] Punctuation
  - [x] Symbol
- Some other monospace/programming fonts supported this character (eh they probably do)

------

Here is a list of characters I could find that can be probably derived by performing some non-distorting transformation on existing characters.

### Reversed (Horizontally flipped)

| Status | Derived | Base |
| --- | --- | --- |
| ✓ | `⦣` U+29A3 REVERSED ANGLE | `∠` U+2220 ANGLE |
| ✓ | `⦰` U+29B0 REVERSED EMPTY SET | `∅` U+2205 EMPTY SET |
| ✓ | `⫮` U+2AEE DOES NOT DIVIDE WITH REVERSED NEGATION SLASH | `∤` U+2224 DOES NOT DIVIDE |
| ✓ | `⯾` U+2BFE REVERSED RIGHT ANGLE | `∟` U+221F RIGHT ANGLE |
| ✓ | `Ꙅ` U+A644 CYRILLIC CAPITAL LETTER REVERSED DZE | `Ѕ` U+0405 CYRILLIC CAPITAL LETTER DZE |
| ✓ | `ꙅ` U+A645 CYRILLIC SMALL LETTER REVERSED DZE | `ѕ` U+0455 CYRILLIC SMALL LETTER DZE |
| ✓ | `Ꙕ` U+A654 CYRILLIC CAPITAL LETTER REVERSED YU | `Ю` U+042E CYRILLIC CAPITAL LETTER YU |
| ✓ | `ꙕ` U+A655 CYRILLIC SMALL LETTER REVERSED YU | `ю` U+044E CYRILLIC SMALL LETTER YU |
| ✓ | `Ꙡ` U+A660 CYRILLIC CAPITAL LETTER REVERSED TSE | `Ц` U+0426 CYRILLIC CAPITAL LETTER TSE |
| ✓ | `ꙡ` U+A661 CYRILLIC SMALL LETTER REVERSED TSE | `ц` U+0446 CYRILLIC SMALL LETTER TSE |
| ✓ | `ꟻ` U+A7FB LATIN EPIGRAPHIC LETTER REVERSED F | `F` U+0046 LATIN CAPITAL LETTER F |
| ✓ | `ꟼ` U+A7FC LATIN EPIGRAPHIC LETTER REVERSED P | `P` U+0050 LATIN CAPITAL LETTER P |
|  | `𝼁` U+1DF01 LATIN SMALL LETTER REVERSED SCRIPT G | `ɡ` U+0261 LATIN SMALL LETTER SCRIPT G |
|  | `𝼃` U+1DF03 LATIN SMALL LETTER REVERSED K | `k` U+006B LATIN SMALL LETTER K|
|  | `𝼇` U+1DF07 LATIN SMALL LETTER REVERSED ENG |`ŋ` U+014B LATIN SMALL LETTER ENG |
| ✓ | `⅃` U+2143 REVERSED SANS-SERIF CAPITAL L | `𝖫` U+1D5AB MATHEMATICAL SANS-SERIF CAPITAL L (?) |

### [Complete] Turned

| Derived | Base |
| --- | --- |
| `⦢` U+29A2 TURNED ANGLE | `∠` U+2220 ANGLE |
| `⸲` U+2E32 TURNED COMMA | `,` U+002C COMMA |
| `⸵` U+2E35 TURNED SEMICOLON | `;` U+003B SEMICOLON |
| `⸸` U+2E38 TURNED DAGGER | `†` U+2020 DAGGER |
| `𝼂` U+1DF02 LATIN LETTER SMALL CAPITAL TURNED G | `ɢ` U+0262 LATIN LETTER SMALL CAPITAL G |
| `𝼐` U+1DF10 LATIN LETTER SMALL CAPITAL TURNED K | `ᴋ` U+1D0B LATIN LETTER SMALL CAPITAL K|

### Inverted (vertically flipped)

| Status | Derived | Base |
| --- | --- | --- |
|  | `ꟽ` U+A7FD LATIN EPIGRAPHIC LETTER INVERTED M | `M` U+004D LATIN CAPITAL LETTER M |
| ✓ | `ꭀ` U+AB40 LATIN SMALL LETTER INVERTED OE | `œ` U+0153 LATIN SMALL LIGATURE OE |

(There's also `ꬱ` where only the right part `e` is inverted. "Inverted e" does not exist as a standalone character.)

### [Complete] "Raised" (Translated up around half x-height)

| Derived | Base |
| --- | --- |
| `⸳` U+2E33 RAISED DOT | `.` U+002E FULL STOP |
| `⸴` U+2E34 RAISED COMMA | `,` U+002C COMMA |

From the [proposal document](https://www.unicode.org/wg2/docs/n3873.pdf), these should be aligned with the middle dot in U+2056 `⁖`.

### Above/Below counterparts of combining characters:

| Status | Derived | Base |
| --- | --- | --- |
| ✓ | U+1AC7 COMBINING INVERTED DOUBLE ARCH ABOVE | U+032B COMBINING INVERTED DOUBLE ARCH BELOW |
| ✓ | U+1DCF COMBINING ZIGZAG BELOW | U+035B COMBINING ZIGZAG ABOVE |
| ✓ | U+1DF5 COMBINING UP TACK ABOVE | U+031D COMBINING UP TACK BELOW |
|  | U+1DF8 COMBINING DOT ABOVE LEFT | U+0358 COMBINING DOT ABOVE RIGHT |
|  | U+1DFA COMBINING DOT BELOW LEFT | U+0358 COMBINING DOT ABOVE RIGHT |
| ✓ | U+1DFC COMBINING DOUBLE INVERTED BREVE BELOW | U+0361 COMBINING DOUBLE INVERTED BREVE |
| ✓ | U+1DFD COMBINING ALMOST EQUAL TO BELOW | U+034C COMBINING ALMOST EQUAL TO ABOVE |
| ✓ | U+1AC8 COMBINING PLUS SIGN ABOVE | U+031F COMBINING PLUS SIGN BELOW |

There's also U+20F0 COMBINING ASTERISK ABOVE vs U+0359 COMBINING ASTERISK BELOW (complete), but it seems like the former is usually rendered as a full-sized `*` while the latter (existing) is a smaller one.

EDIT: Updated up to commit 0dad840

**Comment by be5invis** [comment]
Flipping, is, much much harder than what you are imagineing , because a lot of tiny adjustments...

**Comment by Logo121** [comment]
Are the others (turned and translations) easier? Should I separate them into a different issue?

**Comment by be5invis** [comment]
I currently do not see any fonts placing U+2E33 and 2E34 at the halfway of the colon... Here is Brill:
![image](https://user-images.githubusercontent.com/240091/224963645-383c498f-9780-46ff-ae86-a8f405fd2cf3.png)

**Comment by Logo121** [comment]
That does seem to be the more common case? From what I have in my computer, I can find Everson Mono and JuliaMono (sorta) that aligns the two in the middle:
![image](https://user-images.githubusercontent.com/21302803/224982374-c206a2c3-96ec-49bf-89e0-4e8fa491af79.png)
There's also the odd case of Fairfax (non-HD, not pictured), which cannot align to half x-height (due to x-height being 5 pixels), and ended up putting its raised dot slightly above half x-height (or just above the period).  
This alignment is "reflected" in the HD version:
![image](https://user-images.githubusercontent.com/21302803/224985720-43d6cc14-e485-4a46-992b-c48f1663511e.png)
I don't know if this counts as aligning to half x-height in this case.

Other fonts just lift it up a bit like the ones you've demonstrated (e.g. Noto Serif), and/or doesn't even align the 3-dot punctuation with colon.

(Btw is it just me or is Brill's raised comma raised a bit more than the raised dot?)

[This followup note](https://www.unicode.org/wg2/docs/n3984.pdf) for the two characters also touched on the use of the term "raised" and how different fonts interpret them differently. Though the document also mentions several times that the proposal places the punctuation "at half x-height", which is what I referenced when writing this issue.

**Comment by jmcwilliams403** [comment]
More characters in the scope of this issue were added in #1697
Also you should mention COMBINING PLUS SIGN ABOVE (`U+1AC8`) which was also added.
