### ISSUE TITLE
Some characters got lower height in 21.0.0

### ISSUE THREAD

**Issue by pv4** [be5invis/Iosevka#1599]
Most special characters (e.g. "tilde", "greater", "less") became higher in 21.0.0 compared to 18.0.0. But the attached ones became lower (the middle column is 18.0.0, the right one is 21.0.0):

U+22F4
![u22f4 diff](https://user-images.githubusercontent.com/2502094/224520371-c10dce20-43da-488e-aad6-b70b992c0c07.png)

U+22F7
![u22f7 diff](https://user-images.githubusercontent.com/2502094/224520375-c8bf937f-908a-4f02-899b-96ea1405a648.png)

U+22FC
![u22fc diff](https://user-images.githubusercontent.com/2502094/224520379-ad2ab73f-f9d8-4cae-9f41-653514228985.png)

U+22FE
![u22fe diff](https://user-images.githubusercontent.com/2502094/224520381-36bcc026-db5f-42e4-a546-1db22e6b0af8.png)

U+2377
![u2377 diff](https://user-images.githubusercontent.com/2502094/224520348-e9baf326-3fca-4b84-8e93-e9d69b006f6a.png)

Is it an intended change?

**Comment by pv4** [comment]
Sorry, some more characters:

U+1DC4
![u1dc4 diff](https://user-images.githubusercontent.com/2502094/224520598-7696df36-db4f-420c-afdd-fe2771a90e38.png)

U+1DC5
![u1dc5 diff](https://user-images.githubusercontent.com/2502094/224520602-baf10a54-dd49-4e67-996d-7f644dbf53d9.png)

U+1DC6
![u1dc6 diff](https://user-images.githubusercontent.com/2502094/224520605-fd13ce5d-b9a4-4b03-b2f6-238191f3cf36.png)

U+1DC7
![u1dc7 diff](https://user-images.githubusercontent.com/2502094/224520610-319af7a0-685f-4997-910a-f4faa80628b7.png)

**Comment by be5invis** [comment]
This is intensional.
Resolve as by design.

**Comment by be5invis** [comment]
I can choose a wider symbol for  APL (2377) though
