### ISSUE TITLE
Box-drawing glyphs are scaled to 1em in CJK build with Inziu; Request for partial generation and different flavors

### ISSUE THREAD

**Issue by Arthur2e5** [be5invis/Iosevka#16]
制表符在 Inziu Iosevka 中宽度为 1em，会造成一些问题。作为编程字体，我甚至觉得很大一片宽度不确定的那些都该是半角。

以下内容在 Consolas 和 Iosevka 正常，对无制表符支持发生 Fallback 的 Tsentsiu Mono 和有 1em 制表符的 Inziu Iosevka 失去对齐：

```
┌──────────────────────────────────────────────────────────────────────────────┐
|*AOSC OS                                                                      |
| Advanced options for AOSC OS                                                 |
| AOSC OS (3.0.4) (on /dev/sda3)                                               | *DUPLICATE!*
| Advanced options for AOSC OS (3.0.4) (on /dev/sda3)                          | *DUPLICATE!*
└──────────────────────────────────────────────────────────────────────────────┘
```

关于 CJK 编程字体内的部分字符：
以下内容在 Iosevka（Chrome，自动回落）标定位置符合预期，即 emDash 也认为只有 1/2em 宽，且弯引号为 1/2em;

```
“啊——‘baz’输了……”，foo bar 说道。
^1211^111^1212^^^1 111 111 1212^^
```

考虑到存在一些用户对 Glyph 形状有不同意见（#8 和 [bitserf](https://github.com/bitserf/Iosevka/commit/fd193e841b6778fd1ae6fa0117a3bd2fce923527)，还有各种 0 形状教派），如果能够部分构建（`$$include` 抽出去？），那么让 fontforge 出来复制一下对着 sfd 换几个字再造 Collection 大概会是件好事吧。Inziu Iosevka 我目前要不同 HW 取舍的变体选择就好……

**Comment by be5invis** [comment]
Well Inziu Iosevka is designed to be compatible with traditional CJK typefaces, where all box drawing glyphs are full-width, identical to Iosevka CC. Maybe I should provide a Inziu Iosevka HW where symbols remain half-width, just like the original Iosevka.

**Comment by Arthur2e5** [comment]
@be5invis GitHub's Releases may be ideal for huge binaries. You can add attachments to tags there. I think ~80M is fine for that.

**Comment by Arthur2e5** [comment]
As some kind of abuse, I attached a 215M LibreOffice Installer to https://github.com/AOSC-Dev/autobuild3/releases/tag/v0.1.4.3. And it still accepted it…

**Comment by be5invis** [comment]
The current Inziu Iosevka's box-drawing characters are half width now. Closed.
