### ISSUE TITLE
Looking for color scheme used in preview pictures.

### ISSUE THREAD

**Issue by Probotect0r** [be5invis/Iosevka#160]
Sorry, not really an issue, just loved the color schemes used in the preview pictures in the Readme. If someone could point me to them, that would be great, thanks.

**Comment by be5invis** [comment]
You can read the CSS...
It is a custom-made.
Closed.

**Comment by Probotect0r** [comment]
It's an image. I guess I will just grab the colours from it. Thanks.

**Comment by robertgzr** [comment]
The colors are here:

https://github.com/be5invis/Iosevka/blob/master/snapshot/index.styl

**Comment by Probotect0r** [comment]
Ah I didn't look in the folder. Thanks.
