### ISSUE TITLE
Mathematical alphanumeric characters should not be affected by the font's italicization or weight

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1609]
The point of the mathematical alphanumeric characters is to have a hard-baked italicization and weight that is independent of the actual font's italicization and weight.

However, selecting an italic or bold form of Iosevka should should not change these characters further; Mathematical italic characters should not get even more italic, and Mathematical bold characters should not get even more bold.

Additionally, mathematical alphanumeric characters which are either not italic or not bold to begin with should not then become italic or bold when selecting a font italicization or weight.

**Comment by be5invis** [comment]
I used to consider this, but, well, there's no "math roman" characters in Unicode, so I decided to make the math bold/italic/sans-serifs to "follow" the main style. Actually, some math fonts with weights (like Minion Math) do the similar.

Resolve as by design.
