### ISSUE TITLE
Wrong prompt character

### ISSUE THREAD

**Issue by vbauerster** [be5invis/Iosevka#161]
* Your font version: (Release or git, version)
1.11.3
* Your font variant: term
* Your operating system (name and version): macOS Sierra v 10.12.3
* Your application using Iosevka: (some Java applications may have problem in showing Iosevka properly. It is a bug in Java's GUI components.)
iTerm2 v3.0.15, Terminal.app

After I have upgraded from v1.10.5. to v1.11.3, my prompt character turned to opposite character:

[![Screen Shot 2017-03-11 at 17.57.23.png](https://s25.postimg.org/85wqcfuj3/Screen_Shot_2017_03_11_at_17_57_23.png)](https://postimg.org/image/rnrdsdrgr/)

It is [pure](https://github.com/sindresorhus/pure) prompt theme for zsh.
Before it was ok:
![how it was](https://github.com/vbauerster/mpb/raw/master/example/gifs/single.gif)

**Comment by be5invis** [comment]
Will be fixed in next release

**Comment by vbauerster** [comment]
Thank you for great font!
