### ISSUE TITLE
qp Ligature U+0239 shape inconsistent with q and p

### ISSUE THREAD

**Issue by Logo121** [be5invis/Iosevka#1610]
![image](https://user-images.githubusercontent.com/21302803/225966577-2c44239c-3916-4178-b845-061708fecc1f.png)
As shown.

Same for db (U+0238)

Looking through the code, these two glyph seems to have been here since forever (as far as I'm willing to dig backwards), and it seems to have always been implemented in this "oo + ascender/descender" way.

This causes a small inconsistency between the dbqp shape (which uses the shapes from `obarleft`) with their ligature forms. Which is at least different from how most font does it (merging the d and b shapes):
![image](https://user-images.githubusercontent.com/21302803/225962771-e368b23d-81bd-4cab-a235-a90dfecce7e5.png)

As for the stem, the usual implementation (as observed from the above set) is:
1. The ligature uses the same stem length as the separate characters (which includes the small jut beyond the o shape). The only exception here is Noto.
2. The stroke endings are merged if they are compatible, or with the serifs removed if they are not. The ascender/descender part looks fine, it's just the other side that's missing.

There's also something about variants I suppose, but the other ligatures like ae doesn't seem to contain all variant shapes anyway.

**Comment by be5invis** [comment]
Keeping that little jut above the opposite of the center stem will make the letter look really ... ugly.
![image](https://user-images.githubusercontent.com/240091/226086164-3626bee0-71be-4f3a-845d-5f93bfb06595.png)![image](https://user-images.githubusercontent.com/240091/226086165-ec43fdd1-8e11-4dc2-acc3-b7d9c3313969.png)

I could make a little optimization though
![image](https://user-images.githubusercontent.com/240091/226087311-33f36452-589a-4dc2-ba94-85170c3ffbfd.png)![image](https://user-images.githubusercontent.com/240091/226087312-4c8a8ab7-b703-4adb-b46d-ef4ad7101be3.png)
