### ISSUE TITLE
Inconsistent rightside K/k alignment

### ISSUE THREAD

**Issue by pv4** [be5invis/Iosevka#1611]
Latin uppercase and lowercase k (and derived) have inconsistent alignment of most-right elements. There are 3 cases (colored differently on the images attached):
- (green) both the leg and the hand are right-aligned, i.e. have the same rightmost point, if a vertical line is painted right to the glyph, the leg and the hand have the same distance from it,
- (red) the hand is "shorter" than the leg (including serifs on both), the distance between the vertical line and the hand is greater than the one between the line and the leg
  - curly uppercase and lowercase K with bottom serif only or without serifs. But straight uppercase K's don't have such an issue, they are rightmost vertically aligned being sans-serifed, both-serifed or bottom-serifed
- (yellow) the hand is "longer" than the leg (including serifs on both), the distance between the vertical line and the hand is less than the one between the line and the leg
  - straight k's with bottom serifs only. The strange thing is that curly k's with the same serifs beheave exactly the opposite way: shorter hand and longer leg
  - cursive k's, as it seems for me, have too short bottom serif. Is it by design? Anyway, sans-serif cursive k is rightside aligned while serifed cursive k is not, which is strange
- (blue) just look like #1591 is not fully fixed

I don't say these all should be rightside aligned, there are probably reasons why they are not. But it's strange that misalignmentness depends on curlyness/symmetricness.

Feel free to only fix what is not by design and leave the remaining as is.

Could you also please write here what is expected design decision related to the rightside alignment? Should they be all alighed? Should they have, e.g., shorter hand if the glyph has the bottom serif only? Other "inconsistencies"?

![image](https://user-images.githubusercontent.com/2502094/226064780-d1b1ed4d-a19f-47ee-a330-be2953aecec7.png)
![image](https://user-images.githubusercontent.com/2502094/226064803-b70005f0-0879-4eb0-a1e8-5fbaa8f6862b.png)

**Comment by be5invis** [comment]
For curly, the top-right leg is INTENSIONALLY shorter than bottom-right. Why? Because it doesn't have "corners" at the end of the legs, so it follows different rule of alignment. See [Overshoot](https://en.wikipedia.org/wiki/Overshoot_(typography)).

Your blue and yellow circles applied to Cursives are bugs. I will fix them.

**Comment by pv4** [comment]
Thanks for the explanation! I guessed some variants are overshoot-related but I decided to report to be sure.
