### ISSUE TITLE
(Website) Pressing variants for some Enclosed Alphanumeric Supplement glyphs crashes the Specimen page

### ISSUE THREAD

**Issue by Logo121** [be5invis/Iosevka#1616]
The numbers of variants for each character stacks for those enclosed glyphs, which will cause heavy slowdowns or even crashes if one tries to view the variant of them (or accidentally clicked on the variant thing).

If my calculations are correct:
* UHD: 10 * 4 * 6 * 2 (Half/Fullwidth) = 480 Variants
* HDR: 4 * 6 * 12 * 2 = 576 Variants
* 120P: 9 * 2 * 14 * 4 * 2 = 2016 Variants
* HI-RES: 4 * 3 * 12 * 3 * 5 * 2 = 4320 Variants
* 2NDSCR: 4 * 4 * 6 * 5 * 5 * 12 * 2 = 57600 Variants (!)

etc.

**Comment by be5invis** [comment]
May need a new UX for multi-component chars...

**Comment by monicfenga** [comment]
and U+1F1A9(SQUARED LOSSLESS)
it has 8 Characters

**Comment by Logo121** [comment]
The overhaul seems to handle this pretty well, close as resolved
![image](https://github.com/be5invis/Iosevka/assets/21302803/7cde3530-08ec-4db9-b9eb-7a203d2c0ea7)
