### ISSUE TITLE
Unicode errors for angle quotation mark ornaments

### ISSUE THREAD

**Issue by nick-s-b** [be5invis/Iosevka#162]
* Your font version: Latest AUR version
* Your font variant: Affects ttf-iosevka-term  ttf-iosevka-term-zshaped ttf-iosevka-term-hooky
* Your operating system (name and version): Arch
* Your application using Iosevka: Any terminal

---
These unicode characters are swapped:
heavy right-pointing angle quotation mark ornament (U+276F)
and
heavy left-pointing angle quotation mark ornament (U+276E)

medium right-pointing angle bracket ornament (U+276D)
and
medium left-pointing angle bracket ornament (U+276C)

heavy left-pointing angle bracket ornament (U+2770)
and
heavy right-pointing angle bracket ornament (U+2771)

This is recent change. Noticed it after updating AUR package yesterday since I use these characters in my PS1. It can be confirmed with FontForge:

![https://i.imgur.com/eLpEm1C.png](https://i.imgur.com/eLpEm1C.png)

**Comment by be5invis** [comment]
Dup of #161. Closed.

**Comment by be5invis** [comment]
Already fixed in Master
