### ISSUE TITLE
Shouldn't LATIN CAPITAL/SMALL LETTER TONE FIVE depend on DIGIT FIVE cv's?

### ISSUE THREAD

**Issue by pv4** [be5invis/Iosevka#1621]
Currently DIGIT FIVE have two variants.

LATIN CAPITAL/SMALL LETTER TONE FIVE has similar look and similar name but not similar variants (it has no variants at all). Is it intented? Shouldn't it depend on DIGIT FIVE variants? The LATIN LETTER TWO WITH STROKE has the same variants as DIGIT TWO.

The only obvious reason I see why the glyph in question has no variants is because it has top-left serif in slab variant while DIGIT FIVE doesn't.

![image](https://user-images.githubusercontent.com/2502094/226219005-b93cef11-c5e6-4f9c-b730-37d8f690b81d.png)

**Comment by be5invis** [comment]
This letter is unique to old Zhuang alphabet, so I splited it from `5` **ON PURPOSE**.
Resolve as by design
