### ISSUE TITLE
Ability to select variants for Micro Sign «U+00B5» separately from real Greek Mu «U+03BC»

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1629]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------
From Left to Right: Latin small letter u, micro sign, greek small letter mu<br>
Noto Sans:
![image](https://user-images.githubusercontent.com/37010132/227578226-ca296948-7feb-44d6-b1d8-9110b6ce9871.png)
Rubik:
![image](https://user-images.githubusercontent.com/37010132/227578857-ada8093c-8457-4a55-935f-0fb87afa2303.png)
Lucida Sans Unicode:
![image](https://user-images.githubusercontent.com/37010132/227579687-284ede08-4e1c-4822-9ae9-a8a668159db6.png)
Roboto Flex:
![image](https://user-images.githubusercontent.com/37010132/227578688-fb6766b6-fdf7-40bb-9993-d5a16c37a1e2.png)
Code 2000:
![image](https://user-images.githubusercontent.com/37010132/227579223-ca7a5cb3-dd39-4b33-bbce-4044e349c086.png)

**Comment by pv4** [comment]
Probably related to #1220?
