### ISSUE TITLE
Lower a hook length inconsistent between ligatures

### ISSUE THREAD

**Issue by Logo121** [be5invis/Iosevka#1631]
![image](https://user-images.githubusercontent.com/21302803/227726417-a4da5160-5db7-456b-8186-fc281b51d73a.png)

As pictured. At least the aeAPart shape is probably really outdated and can just be updated to refer directly to the a-shape.

Though since aa is based on a-shape, is the discrepancy between a and aa inevitable?

**Comment by be5invis** [comment]
I don't think it is a good idea to unify hook depth between normal `a` and `aa` ligature.
Though, for these "double" letters, unification is valid.
