### ISSUE TITLE
Serif stroke width

### ISSUE THREAD

**Issue by Logo121** [be5invis/Iosevka#1634]
when going through the code, I realized that for some characters (especially those having their own shape functions) use `df.mvs` for serif stroke widths but some doesn't. An example is this:
![image](https://user-images.githubusercontent.com/21302803/228318401-d335a617-ba9a-4c96-91fe-ea242555a71e.png)
Where both have the same kind of divFrame but have different serif thickness.

Are there any reasoning/patterns behind these?

**Comment by Logo121** [comment]
well that's not exactly what i mean

There are probably more cases of serifs not following the main shape stroke width. I realized this issue while trying to make the glyph for iotified a (WIP):
![image](https://user-images.githubusercontent.com/21302803/228581606-facabc1e-9b08-4d58-a4d5-79a2c50ac7f7.png)
Where A and a have thicker serifs that does not depend on the `sw` parameter.

(btw I'm pretty sure `Ѥ` is an Iotified E and not Iotified Es, not sure why that function is named like that)

**Comment by be5invis** [comment]
@Logo121 Well currently all the "iotified" glyphs are not built using a general method. Thay are currently case by case.
You could try utilize `SerifFrame` (and especially `SerifFrame.fromDf`) to build the "serif frame" and then add the serifs.

**Comment by Logo121** [comment]
Yeah I was trying to "unify" the iotified shapes, and realized that if I fix the serifs for the iota part, the serifs for the other shape will still look thicker.

But by this change I suppose it's the serifs of `A` and `a` that should be changed?
