### ISSUE TITLE
Capital Cyrillic U whose tail extends below the baseline

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1641]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [ ] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------
Below is an image of cyrillic small u followed by latin small v followed by cyrillic capital U followed by latin capital V.
Oswald:
![image](https://user-images.githubusercontent.com/37010132/229306906-84b179d9-2b0a-4e2f-92a2-99db936d59d8.png)

**Comment by be5invis** [comment]
This looks really strange to me. Do you have more evidence that such design existed in the history of Cyrillic typefaces? AFAIK in Cyrillic, the turn of У must be placed above the baseline.

**Comment by jmcwilliams403** [comment]
It's mainly a thing from handwriting
![image](https://user-images.githubusercontent.com/37010132/229320145-6776c784-078c-4c6e-96e6-69886f9749a3.png)
![image](https://user-images.githubusercontent.com/37010132/229320661-ecb1c088-2243-49ec-ab2f-6bfb8d4ceb91.png)

**Comment by VladWinner** [comment]
> Oswald

Font experts noted the following about Oswald font:
_'Peculiar, very unexpected form of У, which goes below the baseline (that would be logical, if the same happened to J)'
‹…›
'Despite the strong historical prototype and the popular type genre, the Cyrillic of Oswald has way too many problems to ignore. Sadly, it’s not worth using.'_
Source: https://type.today/en/journal/neo#Oswald

I'm sure that this variant of У will be redundant for Iosevka or any other font.

**Comment by jmcwilliams403** [comment]
Closing because this variant is unnecessary and too niche.
