### ISSUE TITLE
'cv19' does not apply to U+04B4, U+04B5, U+A68A, and U+A68B

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#1646]
U+04B4 CYRILLIC CAPITAL LIGATURE TE TSE, U+04B5 CYRILLIC SMALL LIGATURE TE TSE, U+A68A CYRILLIC CAPITAL LETTER TE WITH MIDDLE HOOK, and U+A68B CYRILLIC SMALL LETTER TE WITH MIDDLE HOOK are unaffected by 'cv19'.

---

* Your font version: 22.0.0
* Your font variant: Iosevka Slab Extended
* Your operating system: macOS Ventura 13.2.1
* Your application using Iosevka: hb-view

**Comment by Logo121** [comment]
just asking,

since I based the code for U+A68A, U+A68B on Dje (U+0402), should that (and Tshe (U+040B)) follow cv19 as well?

**Comment by be5invis** [comment]
@Logo121  Dje and Tshe are not considered as derivatives of T (while U+A68A/A68B are).
These are more like `h` with a top bar. I did not add variant selectors for them.
