### ISSUE TITLE
Provide a variant of digit 5 with open hook (horizontal/slightly diagonal ending)

### ISSUE THREAD

**Issue by cousteaulecommandant** [be5invis/Iosevka#1647]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

The current options for digit 5 make it a bit hard to tell it apart from a digit 6 at a first glance (or at least what digit 6 looks in other fonts; the default in this font is clearly different) because the bottom hook is a bit too closed.  Overall, I feel like this makes it a bit harder to immediately identify as a 5.

I think it would be interesting to give an option for an "open hook" that kind of looks like a bass clef: instead of having the hook end curling upwards, it has a horizontal ending, or even pointing slightly diagonally downwards (or curling upwards less aggressively, leaving more "clearance" on the opening).

This is clearly done in OCR-B:
![OCR-B](https://i.imgur.com/CvHXWHW.gif)
and, to a lesser degree, Consolas:
![Consolas](https://i.imgur.com/Ln36NJY.gif)
Other fonts such as DejaVu Sans Mono, while not doing this exactly, have a digit 5 with a very open hook; the problem I see with this font is that the hook is too closed.

(In particular, I think OCR-B does a good job at making digits easily distinguishable.  I noticed that Iosevka uses a similar style for digits 1, 6, 8, 9; so I'd say it's "in the same spirit".)

What do you think?  Would this clash too much with the overall font style?

**Comment by cousteaulecommandant** [comment]
This issue might be related to (or maybe even a duplicate of) #1287 (_More open “5” and “c”_), which also mentions lowercase "c" which has a similar problem.

**Comment by be5invis** [comment]
Resolve as duplicate.
