### ISSUE TITLE
Square ligatures from CJK Compatibility Chararters

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1650]
- The requested character is...
  - [x] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [x] Symbol
- [x] Some other monospace/programming fonts supported this character. Provide images below.
------
A continuation of #1649 
U+3371..U+337A, U+3380..U+33DF, U+33FF
Julia Mono:
![image](https://user-images.githubusercontent.com/37010132/229853391-6509697b-92e5-477c-9fc1-8527b09f70e8.png)

**Comment by be5invis** [comment]
See comment in #1651.
Resolve as out of scope.
