### ISSUE TITLE
Yijing Hexagram Symbols

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1653]
- The requested character is...
  - [ ] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [x] Symbol
- [x] Some other monospace/programming fonts supported this character. Provide images below.

------
U+4DC0..U+4DFF
Julia Mono:
![image](https://user-images.githubusercontent.com/37010132/230632130-a4144d8d-3ba9-4730-b37b-3f7afdb895a1.png)
It should be worth mentioning that this block has the "Common" script property, and is technically not CJK.
It should also be worth mentioning that Iosevka currently supports the digram and trigram characters found in the Miscellaneous Symbols block, which compose these characters' glyphs.

**Comment by Logo121** [comment]
closable?
