### ISSUE TITLE
Forced-Upright Latin-1 Broken Bar under italics

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1660]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

The Latin-1 Broken Bar character has historically been used as a vertical version of two consecutive minus signs as a sort of rudimentary box drawing character,<br>
```
-¦-----------¦-
 ¦ Like this ¦
-¦-----------¦-
 ```
 Example in Liberation Mono under italics:
 
![image](https://user-images.githubusercontent.com/37010132/231182859-6193b516-b3a4-4b52-a04d-231ad1bd44e2.png)

Also, it should be noted that the Liberation Mono style set for Iosevka is the chief user of this feature for the ASCII pipe character.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/231715263-2ffccfdc-2ea7-4118-a7a5-9b4b746677cd.png)
I think we already have it?

**Comment by be5invis** [comment]
Liberation Mono Style also already set this variant.

Resolve as not repro.

**Comment by jmcwilliams403** [comment]
Your response to this seems inconsistent with your response for #1575 . Something is clearly not working in the customizer if this is the case.
