### ISSUE TITLE
Website: Specimen's fallback font under Etoile should be serifed

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1665]
Current behavior:
![image](https://user-images.githubusercontent.com/37010132/232095152-0db4d2af-c8c1-4357-9a1f-5c91eb40d500.png)
Behavior if Etoile fell back to a serif font:
![image](https://user-images.githubusercontent.com/37010132/232098499-28abff06-32e3-4b43-9289-21c6749f4ed7.png)

**Comment by be5invis** [comment]
Fixed locally. Next release will reflect this.
