### ISSUE TITLE
Weierstrass P (`U+2118`)

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1668]
- The requested character is...
  - [x] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [x] Symbol
- [x] Some other monospace/programming fonts supported this character. Provide images below.

------

The original name in Unicode, before they added the alias "Weierstrass Elliptic Function", was "Script Capital P", which is erroneous, as it is actually lowercase and also completely unrelated to the script P in the Mathematical Alphanumeric Symbols block, and even looks different. The Weierstrass P has its own html tag, `&wp;`.

Below is an example of Script Small L next to Script Capital P in Noto Sans mono:
![image](https://user-images.githubusercontent.com/37010132/232239241-f4b30f28-7d90-4950-a43d-d375d28c931a.png)
and here in Julia Mono:
![image](https://user-images.githubusercontent.com/37010132/232239337-b1c2b20c-c088-4d22-b58b-d7c728b5d870.png)

**Comment by be5invis** [comment]
added in dev

**Comment by be5invis** [comment]
O, please do not open another bug to add every "script" letters -- that's another topic. I know that. And it should already have an issue I think.

**Comment by jmcwilliams403** [comment]
> O, please do not open another bug to add every "script" letters -- that's another topic. I know that. And it should already have an issue I think.

I wasn't going to. I cherry picked the other one that wasn't related to the math alphanumeric block besides small L
