### ISSUE TITLE
Taixuanjing Symbols

### ISSUE THREAD

**Issue by Logo121** [be5invis/Iosevka#1670]
- The requested character is...
  - [ ] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [x] Symbol
- [x] Some other monospace/programming fonts supported this character. Provide images below.

------

Sorta a logical "next step" to #1653. Basically Yijing symbols but ternary.
![image](https://user-images.githubusercontent.com/21302803/232322199-c03be184-85ab-4e01-82e5-6eb8ce66d1c3.png)

Unicode unifies Yijing with Taixuanjing symbols, so the monograms and digrams part excludes those with just with `⚊` and `⚋`.  

Fortunately the Tetragrams are actually in lexicographical (?) order this time, just that it's ternary so bitmasking is not possible.

Supported by Everson Mono and JuliaMono (only 4 shown but most fonts either support all or none of them anyway):
![image](https://user-images.githubusercontent.com/21302803/232322742-2f1b810d-eb77-418c-a9db-b09f72b18fb9.png)

**Comment by be5invis** [comment]
Wait there are programming fonts even do this? That's interesting...
