### ISSUE TITLE
Latin Ext-E: Three versions of small L with overlaid diacritics (+ 1 superscript & 1 combining form)

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1673]
- The requested character is...
  - [x] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [ ] Symbol
- [x] Some other monospace/programming fonts supported this character. Provide images below.

------
U+AB37..U+AB39, U+AB5D, U+1DEC
Noto Sans Mono:
![image](https://user-images.githubusercontent.com/37010132/232813762-b5952c5d-66e1-4566-8f24-bb2d88d13a41.png)
Fairfax HD:
![image](https://user-images.githubusercontent.com/37010132/232814057-131da5f0-ad9e-474b-a4e7-6a45420b55a4.png)

**Comment by jmcwilliams403** [comment]
Additionally, but completely optionally, there is also Combining Parentheses Overlay (`U+1ABE`), which is like an additional overlaid diacritic that augments other overlaid diacritics with parentheses, similarly to combining parentheses above (`U+1ABB`):
![image](https://user-images.githubusercontent.com/37010132/232833262-4f6447f2-1fef-4fd7-b023-94d02302fe60.png)

**Comment by Logo121** [comment]
Just a note, the combining parentheses as proposed [have some really funky behavior](https://www.unicode.org/wg2/docs/n4106.pdf) when used with other diacritics:
![image](https://user-images.githubusercontent.com/21302803/232844749-2597de1a-5500-489a-8781-4d0fda1b337a.png)
Which makes it sorta a diacritic for diacritics.

Here's a related issue over at noto fonts: https://github.com/notofonts/latin-greek-cyrillic/issues/146

It's probably better to put those combined parentheses into a different issue altogether.

**Comment by jmcwilliams403** [comment]
BTW the combining character in the title is just for the combining version of the letter L with middle double tilde. Let's just agree that the parentheses does indeed belong in another issue. I just figured to mention it since they were related.
