### ISSUE TITLE
Novel zero variant: Zero with broken vertical middle bar

### ISSUE THREAD

**Issue by Lieutenant-L-T-Smash** [be5invis/Iosevka#1678]
- [X] The requested variant shape does not go too far away from Iosevka's design.
- [X] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [ ] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

This is a request for a novel variant of zero, with a broken vertical bar through the middle, as shown in the attached image. The primary justification is a matter of accessibility.

I'm unfortunately finding that my vision is getting worse with age. When looking at large quantities of numbers, such as in long lists, tables, or frequently changing counters, especially under poor conditions such as glancing over at a monitor from a distance or at an angle, a common problem arises: A typical slashed or dotted zero is confusable with the digit eight. Both appear as rounded shapes with a weighty middle. An ordinary hollow zero is of course  confusable with a capital O. I needed a zero shape that minimized confusability with any other common letter or digit.

I came up with this solution myself, and have already built Iosevka with it (diffs are attached), though I rather bumbled my way through adding the changes I needed and it's probably not the ideal way to implement it in code. I've been using it for over a month and I find this zero very easy to distinguish at a glance from other digits while still looking presentable up close. I hope this zero variant may be included in the official source to benefit others who must rely on their poor vision. 

![Screenshot1](https://user-images.githubusercontent.com/81892452/233215692-576ea516-2f33-4df5-a814-0b52641977d8.png)

[variants.toml.diff.txt](https://github.com/be5invis/Iosevka/files/11278089/variants.toml.diff.txt)
[0.ptl.diff.txt](https://github.com/be5invis/Iosevka/files/11278095/0.ptl.diff.txt)

**Comment by be5invis** [comment]
This is interesting. Do you know other fonts doing this?

**Comment by Logo121** [comment]
Not vertical, but Fixedsys's 0 is sometimes described as a "broken slash", though not exactly
![](https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Fixedsysfontpreview.svg/220px-Fixedsysfontpreview.svg.png)

Might not be a justification to this variant, but I think this alternative also tackles the problem OP has?

**Comment by Lieutenant-L-T-Smash** [comment]
> This is interesting. Do you know other fonts doing this?

No, I believe this is truly novel, as in "new". I went looking for other fonts designed for low vision and there are several strategies they use, but those wouldn't work with a compact monospace like Iosevka (e.g. making capital O very wide, almost fully circular) and they focus more on alphabetic characters than digits. I did notice that where they use a slashed zero, the slash is a lot more vertical (making this issue vaguely related to https://github.com/be5invis/Iosevka/issues/1509) but taking it to the extreme and putting a fully vertical unbroken bar would result in something close to a phi Φ or that weird Roman thousand ↀ.

> Might not be a justification to this variant, but I think this alternative also tackles the problem OP has?

Actually, no, not at all. This example is awful for legibility and the zero looks even more like an 8 than most slashed zeroes I've seen. There is only a few pixels difference in the construction.

It's difficult to get across the effect of particular vision defects. For me, sharp corners at the extremes of a figure help a lot, so I have no problem telling a B from an 8 even though they might seem very similar (and they are! but their differences are at salient locations) whereas figures that differ mostly in their interior/middle become easily muddled as the internal details shadow and smear together.

My solution keeps the very middle of the figure empty, but adds weight at the top and bottom precisely where an 8 has its empty space. It's weighted differently to an O. It's still recognizable as a zero.

I can't offer any more justification at this time. I can only attest that it works very well for me. I'll understand if that's not enough. I have my Iosevka flavor already built, so this would be for everyone else, and that audience may be very small.

**Comment by Logo121** [comment]
> Actually, no, not at all. This example is awful for legibility and the zero looks even more like an 8 than most slashed zeroes I've seen. There is only a few pixels difference in the construction.

Well, there is only a few pixels difference because there's only a few pixels wiggle room in that glyph in the first place.

That's not my point tho, I'm just wondering if the same effect can be achieved with a broken slash (with a more significant slope) instead of a vertical bar. Something like this:
![image](https://user-images.githubusercontent.com/21302803/233653692-db92f737-b14f-4671-8647-adba44e47ed9.png)
(Note: This is just some sloppy editing over the stroke O/empty set because the current slashed 0 doesn't not have a slanted enough slash to achieve this effect)  
For me it checks the boxes you described: It adds weight where 8 has empty space, it is empty in the middle, and is probably more recognizable as a zero. So I thought it would be a reasonable alternative.

The example I gave is kinda a justification for that variation. Because to be honest, to me the suggested variant suggested _does_ look quite far from the existing design of 0 (not that I'm the one to judge), and Fixedsys is the only version that I know of is sorta close to this.

If the low-res kinda butchered my point though, sorry about that.

**Comment by Lieutenant-L-T-Smash** [comment]
Yeah I appreciate the effort. The failure is mine in not being able to describe the peculiarities of vision problems. I have both astigmatism and myopia among other difficulties. It's not just a blur effect, but a kind of repeated afterimage. An exaggerated and still not wholly accurate example, but hopefully getting the idea across, is figure 11e here:
https://www.researchgate.net/figure/Astigmatism-Myopia-Comparison-for-combined-blur-of-1D-of-myopia-and-25D-of_fig7_276458773

The low-res of your example actually supports the use case. One can use assistive tools like magnifier widgets, but that inherently means focused interaction with the screen. For large amounts of data to be visible at a glance, the text _will_ be low-res, and that is exactly the point.

The problem with a diagonal stroke is that its angle is similar to portion of the 8-curve at about the same height. In the example you gave the gap in the stroke is also too small so the middle of the zero still has "stuff" in it and doesn't read as empty, but expanding the gap would remove the noticeability of the stroke entirely.

Regardless of whether this gets accepted, I heartily +1 to increasing the angle of the stroke in the existing zero variants. It _does_ help.

**Comment by Logo121** [comment]
Well, having tried to simulate the effect like from the paper (and the use case), I do see your point of the vertical broken line being way more distinctive than the alternatives.

But I'll just leave this issue as is now (again, not that I have a say on this), since outright accessibility features aren't usually in the scope for Iosevka (#1268).  
Just see if the above exchange has been good enough justification.

**Comment by Lieutenant-L-T-Smash** [comment]
That is certainly _better_ and if it had been in Iosevka to start with I might not have gone through the trouble of making my own. That said, I still consider my own to be the optimal solution - for me.

I'll also leave this to the decision of the main developer. I'm happy to answer more questions, but I think I've offered everything I have in terms of justification.

**Comment by be5invis** [comment]
It will be added in version 24. Resolve as fixed.

**Comment by Lieutenant-L-T-Smash** [comment]
I appreciate that my suggestion was taken in. However I find one detail unfortunate: The gap/break in the vertical bar has been reduced from my original implementation. The original break was 4/15 (26.7%) of the vertical bar. It has been reduced to 1/8 (12.5%). The break was important to legibility for my use case. In fact I considered expanding it, definitely not reducing it.

To obtain the original design, one can modify `0.ptl` as so:

```
  define [BrokenVerticalBar top] : difference
    VBar.m Middle (0 + O) (top - O) [Math.min (CircleInnerWidth * 0.375) OverlayStroke]
    intersection
-      MaskAbove (top * (1/2 - 1/16))
-      MaskBelow (top * (1/2 + 1/16))
+      MaskAbove (top * (11/30))
+      MaskBelow (top * (1 - (11/30)) )
```
