### ISSUE TITLE
Rhotic hook modifier on modifiers

### ISSUE THREAD

**Issue by Logo121** [be5invis/Iosevka#1681]
(the other diacritics here are just for testing. it's honestly amazing how well it worked in all other cases)
![image](https://user-images.githubusercontent.com/21302803/233475242-96554fa5-babb-44e6-82d7-347f2adf7d37.png)

The modifier rhotic hook acts like half a combining character. Since superscript versions of `ɚ` and `ɝ` are not encoded, the [proposed alternative](https://www.unicode.org/L2/L2020/20252r-mod-ipa-a.pdf) is to use the rhotic modifier on the superscript letters. Currently only SIL fonts (i think) support this.

This behavior would apply to at least the superscript vowels, but there's no restriction on what happens in cases with other characters (since rhotic hook is not expected after any non-vowels anyway).  
For SIL fonts, they only apply to vowels, but I think it's fine to make it apply to any modifier character.

And, as demonstrated, rhotics can stack (though extremely rare in natural languages), and the stacked hooks will be on the same level.

**Comment by Logo121** [comment]
Stacked rhotics doesn't work yet:
![image](https://user-images.githubusercontent.com/21302803/233835900-337f980c-ccb1-469b-8a1f-ebdc2869eea4.png)

**Comment by be5invis** [comment]
@Logo121 Fixed in Dev.
