### ISSUE TITLE
Trying to recreate my custom options

### ISSUE THREAD

**Issue by kaykhan** [be5invis/Iosevka#1686]
A while ago i used the custom builder to customise the Iosevka font and unfortunately im not able to find what settings i originally used to recreate it ( or preferably the name of the release asset).

**old version** ( i prefer this one)
![image](https://user-images.githubusercontent.com/5202527/233789505-e936fae9-6e01-4692-9aee-a19b3e27c671.png)

**new version**
![image](https://user-images.githubusercontent.com/5202527/233789501-53ae28c4-1e3d-4e07-ba4f-0130330c1a9b.png)

Can someone tell me what the difference is, i don't know what to call it but i prefer the look of the old version .
What is noticable:

1. The character "L" in "lazy" is different.
2. The characters look longer.

Is there a released asset version of the old one, i can download and use?

**Comment by alexeyten** [comment]
This looks like Ubuntu Mono style (ss12)

You could try it https://typeof.net/Iosevka/customizer

**Comment by kaykhan** [comment]
It is thank you
