### ISSUE TITLE
Insular D (`U+A779` & `U+A77A`)

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1688]
- The requested character is...
  - [x] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [ ] Symbol
- [x] Some other monospace/programming fonts supported this character. Provide images below.

------
The combining version (`U+1DD8`) is already supported by the font using a homoglyph from Cyrillic.
below is a rendering under Code 2000 with lowercase insular D followed by lowercase eth:
![image](https://user-images.githubusercontent.com/37010132/233860645-08c5f7b3-47f4-40a0-8eae-5f5fa801f4bf.png)
Here is the capital form compared to capital O under Noto Sans mono:
![image](https://user-images.githubusercontent.com/37010132/233860716-af3d1e4a-34aa-4e89-bec8-af0912ed3c53.png)

**Comment by Logo121** [comment]
Note that the way Insular D is rendered varies quite a bit.

Unicode's version looks like this ![image](https://user-images.githubusercontent.com/21302803/234021380-07e6138e-f1df-42ca-a504-5f70d0164a92.png)

Which is a bit ambiguous, and spawned several variants of the glyph:
* Some make the ascender(?) bend like eth without stroke as shown above.
* Some make the ascender straighter (a bit like the "reverse 6" in iosevka) or bend slightly to the other way:
![image](https://user-images.githubusercontent.com/21302803/234020402-a315eca4-672d-4dc9-bdbf-7e7688aaf1af.png)
![image](https://user-images.githubusercontent.com/21302803/234020136-a8962b4f-9dcf-4705-8550-558e34af541e.png)
* Some have the ascender start from the top, out of an O shape, like EversonMono: ![image](https://user-images.githubusercontent.com/21302803/234017741-fb4b1f8a-01c3-4941-bfea-b0c4bce5892c.png)
and Arimo: ![image](https://user-images.githubusercontent.com/21302803/234019863-d5be8cdb-0a34-47cf-af75-eb9a716cd443.png)
* Some have the ascender slant further to the left, making it closer to the "horizontal", reverse-sigma-like form: 
![image](https://user-images.githubusercontent.com/21302803/234022924-a8bfa474-f102-4a4c-aac3-67c3b7b9f069.png) vs this form in Wiki ![](https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Insular-d.svg/105px-Insular-d.svg.png)

As for the capital, most fonts agree it's the horizontal form (as does the Unicode chart version), though a select few (Code2000, Roboto) has it as a "bigger version" of lower insular D: 
![image](https://user-images.githubusercontent.com/21302803/234025342-9d3b2ea4-2cbd-484b-9137-dc7c71fe0ab3.png)


For Brill, it only supports (lower) Insular D as the combining character, though it looks like it also borrowed from Cyrillic: 
![image](https://user-images.githubusercontent.com/21302803/234027397-70d5d448-88f4-4201-991a-c30254ac8fe3.png)
