### ISSUE TITLE
Website: Combining Dialytika Tonos still shows old glyph in specimen

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1690]
Specimen:
![image](https://user-images.githubusercontent.com/37010132/234342877-83267f21-02b2-4180-8dd1-50ddca15add8.png)
It's correct in character map though:
![image](https://user-images.githubusercontent.com/37010132/234343129-9687e5a4-8560-40ca-914b-a4682eb52be1.png)

**Comment by be5invis** [comment]
Resolve as external.
The font and HTML data ARE correct. Should be a bug in the browser.
