### ISSUE TITLE
Enable Book weight for release builds

### ISSUE THREAD

**Issue by up-to-you** [be5invis/Iosevka#1691]
**Is your feature request related to a problem? Please describe.**
All modern fonts (IBM Plex Mono, Fira Code, Jetbrains Mono [regular is emboldened by default] etc.) provide Retina/Book weights as part of distribution.

**Describe the solution you'd like**
Enable Book weight (450) by default.

**Describe alternatives you've considered**
Unfortunately, alternative was gone many years ago when 2k/4k displays wasn't popular.

**Additional context**
The Community appreciate your work for the most accurate fonts ever !

**Comment by be5invis** [comment]
I don't see "book" (`wght` = 450) defined in standard CSS' font weight.
Maybe you want something mote like [grade](https://fonts.google.com/knowledge/glossary/grade)? If so then we may need a new *series* of fonts that has a different shape to represent grade changes...

**Comment by up-to-you** [comment]
I mean this: https://github.com/black-black-cat/Iosevka/commit/77a14b6961d20a1d081c57ff820916ae6854e720

**Comment by be5invis** [comment]
> All modern fonts (**IBM Plex Mono**, ...... ) provide Retina/Book weights as part of distribution.

I downloaded IBM Plex's latest version and its Mono doesn't have a Book/Retina weight grade. It has a Medium though.

Iosevka's current weight grade is mostly equally spaced. Inserting a "Book" in the middle will make it look strange.

**Comment by up-to-you** [comment]
It's called Text in Plex Mono. Different name doesn't make sense technically.

**Comment by up-to-you** [comment]
Also found old issue https://github.com/be5invis/Iosevka/issues/424.
425 instead of 450 weight just also attractive option. I observe 450 has a little bit distorted shapes (while 425 not) on screens with low ppi, like 4k 27" display (163 ppi).
