### ISSUE TITLE
Variants for i and l with long tails

### ISSUE THREAD

**Issue by mybearworld** [be5invis/Iosevka#1692]
- [X] The requested variant shape does not go too far away from Iosevka's design.
- [X] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [ ] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

You can see in fontview that the `tailed` variation of `i` has a bit of margin on the left (default settings except for `i` and `l` being `tailed`):
![image](https://user-images.githubusercontent.com/130385691/234601659-9331665e-4f6b-43b8-a60a-c21a590dc9ee.png)
The same problem applies to `l`, but I can't show that because in fontview, it's at the beginning of a word, and I can't use the font anywhere else because I can't figure out how to install it locally.

So, my suggestion is to have a variation of the `tail` variation of these letters where the tail is a bit longer, so that it doesn't have this awkward margin.

------

I could only find one font that does this, admittedly, but it seems a logical thing for any font using tailed `i` and `l`, which I also couldn't really find any of (tailed-serif is very widely used instead).

![Nova Mono using this variation of i and l](https://user-images.githubusercontent.com/130385691/234602891-071cdc95-c848-47cc-8ddc-57b653c8bad8.png)

**Comment by jmcwilliams403** [comment]
Full tails are used under italics when the font uses tails in that mode. Maybe it wouldn't be too hard to make these selectable in an upright mode?

**Comment by monicfenga** [comment]
Looks like a flipped capital J 🤣

**Comment by mybearworld** [comment]
> Looks like a flipped capital J 🤣

Because it is.

**Comment by mybearworld** [comment]
no

**Comment by Logo121** [comment]
I *guess* it can be seen as parity with the asymmetric `t` variants (or even the hooked one per the given example)?  
It is already possible in some other variants:
![image](https://github.com/be5invis/Iosevka/assets/21302803/9d73f3da-d520-47f8-ae16-0b3904b1bfb8)
