### ISSUE TITLE
Four human index pointer characters in Miscellanious Symbols block whose glyphs are already made, in pieces

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1696]
- The requested character is...
  - [ ] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [x] Symbol
- [x] Some other monospace/programming fonts supported this character. Provide images below.

------
U+261C..U+261F
Julia mono:
![image](https://user-images.githubusercontent.com/37010132/235364882-542f9987-d1d6-4291-a7bf-58c2338444da.png)
Comparison with U+1FBC1..U+1FBC3 under Iosevka:
![image](https://user-images.githubusercontent.com/37010132/235364923-a1a0d8b1-9097-48d6-8931-0f16c5c5adba.png)

**Comment by Logo121** [comment]
216C...? ![image](https://user-images.githubusercontent.com/21302803/235377313-66072224-4f39-436e-9f98-dddec3082735.png)

Just curious tho, are there even any fonts that even unify the legacy pointer with the dingbat one? Fairfax HD doesn't seem to do so, and I already can't think of any other fonts that supports the legacy block.

**Comment by be5invis** [comment]
261C ... 261F
