### ISSUE TITLE
Switch between variants cv20/21

### ISSUE THREAD

**Issue by robertgzr** [be5invis/Iosevka#170]
Is there a switch for the character variant of `_`?

As far as I can see it's the only character with variants that I have no control over during build.
There should be `v-underscore-low` and `v-underscore-high`.

**Comment by be5invis** [comment]
Using `v-underscore-low` and `v-underscore-high` during build WILL be applied to the results, while `cv20` and `cv21` will switch your default setting INTO a low/high configuration.
I just need to add them in the README...

**Comment by robertgzr** [comment]
Oh I didn't try that. Thanks

**Comment by robertgzr** [comment]
Oh I didn't try that. Thanks
