### ISSUE TITLE
Sideways I and Q

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1704]
- The requested character is...
  - [x] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [ ] Symbol
- [x] Some other monospace/programming fonts supported this character. Provide images below.

------

Below is a rendering of Small Capitals I and Q (`U+026A`, `U+A7AF`) followed by Sideways I and Q (`U+A7F7`, `U+213A`) under Fairfax HD:
![image](https://user-images.githubusercontent.com/37010132/236636378-f4475251-8ddb-4eb2-9e21-db8dc65c01a9.png)
It should be worth pointing out that sideways I is only really taking advantage of the x-heightedness of small capital I and doesn't specifically require the hard-serifed form that small capital I unconditionally requires.

**Comment by Logo121** [comment]
rotated Q seems to overlap with adjacent characters?
![image](https://user-images.githubusercontent.com/21302803/236674928-3d47dad5-ae5b-41c9-805d-60523306c68d.png)

**Comment by be5invis** [comment]
@Logo121 This is considered as by design since we don't have very good ways to deal with descenders.
