### ISSUE TITLE
Specimen doesn't show up in Safari versions without fetch

### ISSUE THREAD

**Issue by tbodt** [be5invis/Iosevka#171]
I'd suggest adding the polyfill

**Comment by be5invis** [comment]
![image](https://cloud.githubusercontent.com/assets/240091/24575595/20202a36-16dd-11e7-8ecf-f90d5d0f3fe9.png)

Hmmm latest Safari supports it.

**Comment by tbodt** [comment]
I'm on safari 10.0.1. Guess it's time to update...

**Comment by tbodt** [comment]
also congrats on making hacker news

**Comment by be5invis** [comment]
Closed as external.
@tbodt Reopen or comment if you find further problems.
