### ISSUE TITLE
Website: Specimen fallback font under monospace slab should try for monospace first, then serif

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1724]
The new behavior for Etoile is fine, but the behavior of monospace slab could be fine tuned a bit further.

Current behavior:
![image](https://github.com/be5invis/Iosevka/assets/37010132/a0795993-247c-489e-81d5-23e1ec1b355f)

Behavior if the fallback font first tried for monospace, then serif:
![image](https://github.com/be5invis/Iosevka/assets/37010132/e2087fd2-ff68-4f1c-8ef5-8ba56545cb6b)

**Comment by be5invis** [comment]
Next release will fix this.
