### ISSUE TITLE
[Character variant request] New cool `0` variant from TX-24 Houston Mono from Berkeley Graphics

### ISSUE THREAD

**Issue by haunt98** [be5invis/Iosevka#1727]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [ ] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

Come across TX-24 Houston Mono from Berkeley Graphics in Twitter and I saw their `0` variant.
It's look good! I wish Iosevka would support this variant.

<img width="599" alt="image" src="https://github.com/be5invis/Iosevka/assets/5424272/c7ca8f5b-b1f9-4bd4-aeb7-6bc25f2e8f7f">

[Source](https://twitter.com/berkeleygfx/status/1643217682874130432)

**Comment by be5invis** [comment]
Square or diamond?

**Comment by haunt98** [comment]
Hi @be5invis, I think diamond is way cooler 💯

**Comment by Logo121** [comment]
For the diamond shape, I *guess* PragmataPro does something similar? Basically the OCR-A approach to differentiating O and 0 (though OCR-A uses this shape for O)

**Comment by arpangreat** [comment]
I'm sorry to ask this here , but anyhow can we use cv77 or diamond shape 0 render in terminal?

**Comment by Roundlay** [comment]
Sorry to ping a closed issue. Can anyone detail how to revert to the original rounded `0` with the latest version of the font?

**Comment by arpangreat** [comment]
@Roundlay If you are using any terminal that supports harfbuzz eg kitty or wezterm , you can use font features and set cv77=(to your liking) , here is all of them: https://github.com/be5invis/Iosevka/blob/main/doc/character-variants.md
