### ISSUE TITLE
`VXSF` should be about Icelandic Eth first and mention Partial Derivative second

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1746]
Icelandic Eth is the older character in Unicode.

Also it should be curly by default to not disrupt the current style, as most fonts from the stylistic sets supported use the curly style except for the three I mentioned in  #1738

I just figured since there are character variants being renamed for the next update, now's the best time to make this change too.

**Comment by Logo121** [comment]
The idea of Eth and Partial d sharing the same variant sounds a bit weird to me in the first place tho

They aren't directly derived from each other (which the current description kinda implies so), only sharing a similar shape by coincidence as they both came from `d`.

And not to mentioned there are forms of partial d (the old, math font variant ![image](https://github.com/be5invis/Iosevka/assets/21302803/c8fc2140-94d4-498d-90da-d3c61d393c6c)) that definitely don't look natural for Eth too

But ignoring that, I guess a solution would be just to describe the variant as for "rounded d shapes" or something similar

**Comment by jmcwilliams403** [comment]
To my understanding, partial differential is more closely related to a script greek delta than a script latin d. My first ever commit attempted to unify it with italic cyrillic de due to the common greek lineage.

**Comment by be5invis** [comment]
Eth now controlled by VXAA
