### ISSUE TITLE
Improvements requests for some russian symbols

### ISSUE THREAD

**Issue by chelovechishko** [be5invis/Iosevka#175]
* Your font version: 1.11.3
* Your font variant: Slab
* Your operating system (name and version): Gentoo
* Your application using Iosevka: gnome-terminal

---

`ы` `U+044B` and `ю` `U+044E` has vertical stems too close to circle i think (both big and small versions). Compare with [PT Mono](https://fonts.google.com/specimen/PT+Mono)

`л` `U+043B` is poorly distinguishable from `п` `U+043F` (both big and small versions).

Small `ф` `U+0444` is poorly distinguishable from big `Ф` `U+0424`.

**Comment by be5invis** [comment]
@chelovechishko 

I do not think that `ф` need to be changed...
![image](https://cloud.githubusercontent.com/assets/240091/24579730/51620bf0-172d-11e7-9edb-b28a106da09b.png)

**Comment by be5invis** [comment]
@chelovechishko Text: 
![image](https://cloud.githubusercontent.com/assets/240091/24579735/73ff3340-172d-11e7-8704-c5eb587bcdd6.png)

**Comment by chelovechishko** [comment]
Hm, i still think that `л`'s tail is weakly stand out.

Also, `ъ`'s upper left tail is too short.

**Comment by be5invis** [comment]
@chelovechishko What do you mean, "weakly".
Could you please provide some images?

**Comment by chelovechishko** [comment]
I mean that tail should be longer. Like in Cousine 
![cousine](https://cloud.githubusercontent.com/assets/14850730/24586340/3830cdb8-17d9-11e7-8bec-aa1b23fe680c.png)

**Comment by d125q** [comment]
If modifying `л` (which I somewhat agree with), don't forget to mimic the changes for `љ`, too.

**Comment by DmitriyK-CPKIO** [comment]
If someone could give me a link with explanations how to program letters with this project, i will do some input (Slab is AWESOME font, but **ж** and _ж_ need some finetuning), i've made some sketches already.

**Comment by DmitriyK-CPKIO** [comment]
See this «ж» variant for Slab Light:
![Letter «ж»](http://i89.fastpic.ru/big/2017/0425/7a/c9d486a57c723f7e106977823df4487a.png)

Can this be added?

**Comment by be5invis** [comment]
Reactivate.
