### ISSUE TITLE
Quadruple Stem Arrows

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1756]
- The requested character is...
  - [ ] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [x] Symbol
- [x] Some other monospace/programming fonts supported this character. Provide images below.

------

`U+27F0`..`U+27F1`, `U+2B45`..`U+2B46`

These arrows are used in tuning theory. The up/down arrows are more commonly supported but the left/right arrows are the obvious remaining directional forms for completion.

Pragmata pro (screencapped from their specimen image; I don't own it):
![image](https://github.com/be5invis/Iosevka/assets/37010132/01257bde-dd03-43cf-b809-415a938144d1)

Julia Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/53d3a218-8251-4c84-b1d8-8d65ebcfea28)

My attempt under Iosevka under Thin weight — I can't quite figure out how to eliminate this seam circled:
![image](https://github.com/be5invis/Iosevka/assets/37010132/dffdef4b-46f4-453f-a72b-f8759d510388)

**Comment by Logo121** [comment]
Looks like it's a problem that exists for other arrows anyway: 
![image](https://github.com/be5invis/Iosevka/assets/21302803/ca915456-d77e-4a76-92d8-cf215a4b3597)

The arrowhead shape has a varying width that makes it very hard to find an exact starting point of the bar, such that no seams would appear in all weight settings.

This is my best attempt it still has a barely noticeable seam in some cases:
![image](https://github.com/be5invis/Iosevka/assets/21302803/8f7edada-d4f8-4109-ae29-b7aa96794935)

**Comment by be5invis** [comment]
@jmcwilliams403 I may refactor the way making the arrowhead later. For now you can just submit your PR.
