### ISSUE TITLE
Cyrillic Zhe italic shape

### ISSUE THREAD

**Issue by Logo121** [be5invis/Iosevka#1762]
Some fonts show lower zhe with a rounded, c-like leg in italic:
![image](https://github.com/be5invis/Iosevka/assets/21302803/2dd64ad8-2e9a-41ac-a157-5ad4f46a3802)
For monospace font, I can only find Ubuntu Mono having this shape.

There's also a more cursive, handwriting-like form with diagonal strokes instead of horizontal connecting strokes: 
![image](https://github.com/be5invis/Iosevka/assets/21302803/aa72382f-00a9-4c9a-954a-2a282dd10036)
(more examples are found in [fileformat.info](https://www.fileformat.info/info/unicode/char/0436/fontsupport.htm))

Though I cannot find any monospace font having this form.

**Comment by Logo121** [comment]
I'll say I probably don't have any strong justification for this; it is just something that I stumbled upon while trying (quite unsuccessfully) to implement Cyrillic Dzzhe and Zhwe, two characters that involve the Zhe shape.

For example:
![image](https://github.com/be5invis/Iosevka/assets/21302803/6e9f73fd-3ffc-48a1-8290-9c3c4fc54238)
The italic form of Dzzhe uses the cursive form of zhe. This is the only attested italic form of Dzzhe I think. (only Gentium Plus does this however)

Though I suppose it is not strictly required, as there are implementations that make do without the curved shape:
![image](https://github.com/be5invis/Iosevka/assets/21302803/2509c3f6-114d-4a46-9623-1203bbd64e05)
(okay there are like a total of 3 fonts I could find that cared enough to implement an italic form for this character but still)

It's probably more of a roman type font thing, but since the same fonts that show italics for Dzzhe and Zhwe always show Zhe with the round shape as well, I just figured to put it out here to see if this is important enough.

**Comment by be5invis** [comment]
I think we could just combine the italic shape of De and (right half of) existing Zhe to make the italic Dzzhe.

**Comment by Logo121** [comment]
Will try.

Then for now this is probably just the "cyrillic" equivalent for the handwriting forms request like #620.

Because even after Dzzhe, there are Dche and Dzze whose italic uses the handwriting forms of other cyrillic characters (Che and Ze)
![image](https://github.com/be5invis/Iosevka/assets/21302803/ac5887c7-8fa7-4a63-b37d-11e680a64737)
(I guess this handwriting Ze is the Bulgarian variant but Che looks like the one mentioned in the above issue)

Oh and btw, Cascadia Mono also has these for italic (not the cursive mode):
![image](https://github.com/be5invis/Iosevka/assets/21302803/44fe66cd-59cb-4a5a-90f7-9eb85e49204f)

**Comment by Logo121** [comment]
Did some searching and turns out a few more fonts use the curved zhe shape:
* Inconsolata LGC: ![image](https://github.com/be5invis/Iosevka/assets/21302803/ae696de4-0462-466e-847f-8dfe4293947d)
* IBM Plex Mono: ![image](https://github.com/be5invis/Iosevka/assets/21302803/1bf6a53e-2fa3-49db-8b6b-b100f18c66ce)
* Fantasque Sans Mono (though it is more casual): ![image](https://github.com/be5invis/Iosevka/assets/21302803/ded0cdd7-d0ae-4b65-af0a-e687627807c6)
* Victor Mono (has an aggressively cursive italic in general): ![image](https://github.com/be5invis/Iosevka/assets/21302803/990dde01-609d-4ba8-9eb6-236109886f3f)

**Comment by Logo121** [comment]
I guess the full cursive one can be disregarded for now (maybe as a part of #620?), but I do think the normal "c-like" one is common enough as a variant?

It is used in 2 fonts supported as stylistic sets. (Ubuntu Mono, IBM Plex Mono)
