### ISSUE TITLE
Question: How to include stylistic alternates in custom build?

### ISSUE THREAD

**Issue by Lieutenant-L-T-Smash** [be5invis/Iosevka#1767]
The compiled Iosevka font available for download has a whole lot of stylistic alternates included within the font (such as every possible variant of lowercase i). When I build a custom Iosevka, these are missing, and I only get the one variant that I picked in custom-build-plans.

Is there a way to include alternates in the build?

(Sorry if this has been answered, but I skimmed through the docs and couldn't find it or any example of how to do it. Perhaps I didn't look for the right keywords.)

**Comment by Logo121** [comment]
You mean this option?
![image](https://github.com/be5invis/Iosevka/assets/21302803/d6882ddc-90ff-4eff-accc-d6faadd95177)

(equivalently, `no-cv-ss = false`)

**Comment by Lieutenant-L-T-Smash** [comment]
I suppose that's it. I can't be sure because when I try that option the build fails with "Error null", after working for an hour.

**Comment by Lieutenant-L-T-Smash** [comment]
I just confirmed this is the correct option.

Apparently my build was crashing due to insufficient memory (though it sure would've been nice if the error message had said that). I was able to complete the build after _tripling_ my swapfile size. It also took about ten times as long, which is fair enough as it's building many more glyphs.

Thanks for the answer, @Logo121.
