### ISSUE TITLE
[Feature Request] Add a 'clean' target 

### ISSUE THREAD

**Issue by leonbreedt** [be5invis/Iosevka#178]
It would be good if there was a `clean` target that removes all of the generated files, dist folder, etc.

In the past I have had issues that were resolved by doing a Git clone again, and starting from scratch, if there was a clean target I could make sure I'm doing a fresh build every time.

**Comment by be5invis** [comment]
DONE.

**Comment by leonbreedt** [comment]
Wow, ok. I opened this while cloning, it's still cloning, and you've already fixed it :) 

Thanks, will try when it's finished cloning.

**Comment by leonbreedt** [comment]
```shell
$ make clean
make: *** No rule to make target `cleanscrcipts', needed by `clean'.  Stop.
```

Looks like there is maybe a target missing?

**Comment by be5invis** [comment]
@leonbreedt checkout and try again. it is typo
