### ISSUE TITLE
Make U+274C (cross mark) match typical rendering

### ISSUE THREAD

**Issue by tedyoung** [be5invis/Iosevka#1781]
- The requested character is...
  - [X] Symbol

------

Currently, the Cross Mark character (U+274C) is displayed as a small black cross (like a vertically-centered lowercase `x`), while most operating systems and fonts show it as colored red, with a larger, more bold cross that extends to the edge of its area: ❌ 

This character is often used as the "opposite" of a ✅ character, but its current look doesn't make it stand out enough for that use case.

**Comment by Logo121** [comment]
> fonts show it as colored red, with a larger, more bold cross

This is known as a color font, which is definitely out of scope for this font.

Chances are, the "rendering" you see is just a default Emoji font that the OS ships with, which overrides the actual font used if the glyph is typically (or explicitly) rendered as an emoji.

**Comment by be5invis** [comment]
You can try to use `exclude-chars` in your build plan to knock this character out.
In general, Iosevka is NOT an Emoji font so we won't support color.
Resolve as out of scope.
