### ISSUE TITLE
Autobuilt diagraphs don't have a proper MarkSet set

### ISSUE THREAD

**Issue by Logo121** [be5invis/Iosevka#1783]
Followup from #1777. Might do a thorough search to fix more mark placement problems that I can find, but here's a specific class that probably needs more effort:
![image](https://github.com/be5invis/Iosevka/assets/21302803/2f37b0bd-0be8-4859-8d55-2551d1604d82)
(Diacritics are added to test the placement)

Maybe this is a regression, seeing this works properly for the version I have installed (22.0.0?) 
![image](https://github.com/be5invis/Iosevka/assets/21302803/d6f0c203-1ba4-4976-a1cb-1d59b5d19dd1)

**Comment by be5invis** [comment]
Do we even need them?

**Comment by be5invis** [comment]
Also, some of the digraphs are built as "conventional" ligatures while the others are "phonetic" ligatures. Currently only phonetic ligatures have anchors. Other ligatures do not have anchors at all.

**Comment by Logo121** [comment]
feng with caron below is in extIPA, so I guess yes for at least the ones in IPA/Phonetic blocks:
![image](https://github.com/be5invis/Iosevka/assets/21302803/b1e75c5e-40e2-4937-a44d-fad72b173063)

The placement of the caron there is not necessary though, as SIL fonts and Noto fonts just place the caron in the center:
![image](https://github.com/be5invis/Iosevka/assets/21302803/d0497c39-7d56-4625-836e-0280a1be09a0)
![image](https://github.com/be5invis/Iosevka/assets/21302803/3ce0ccb7-8181-408f-9ce6-f05a9cd42fc8)

**Comment by be5invis** [comment]
@Logo121 Fixed that for phonetics. I do not see any practical use of these for conventional ligatures so the support for these are resolved as out of scope.
