### ISSUE TITLE
Bilateral serifs for U+0055 LATIN CAPITAL LETTER U

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#1788]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

The default (non-motion) serifs on ⟨U⟩ in the slab fonts since version 24.0.0 are unlike the serifs on other capital letters’ glyphs. The old glyph looked better and should be the default glyph. Compare to the serifs on ⟨H⟩:
![UH](https://github.com/be5invis/Iosevka/assets/1124347/3c5c446b-ba60-458c-81ff-97d6461672c2)

FreeMono:
![U](https://github.com/be5invis/Iosevka/assets/1124347/e1643dcb-89ce-42d4-a125-3c2b23214752)

Iosevka Slab Extended version 23.0.0:
![U](https://github.com/be5invis/Iosevka/assets/1124347/6ef607f2-7cf1-456e-81a7-42c31d95b928)

Libertinus Mono:
![U](https://github.com/be5invis/Iosevka/assets/1124347/65ccb08b-a310-4569-90a2-596592b473e3)

**Comment by Logo121** [comment]
Feels the serif change is just a mistake, considering the code for the original serifed `U` is still here, during the variant overhaul:

https://github.com/be5invis/Iosevka/blob/0b1846712698f33b578666ada39d1b8d633b28d4/font-src/glyphs/letter/latin/u.ptl#L129-L131
