### ISSUE TITLE
Consolidation of Anchor Placement Issues

### ISSUE THREAD

**Issue by Logo121** [be5invis/Iosevka#1793]
Ref: #1792. Some are problems that I don't know how to fix, and some I'm not sure if they need changing at all.

## 1. "ExtendBelowBaseAnchors" problems
In some cases, the base anchor is shifted down using `ExtendBelowBaseAnchors` instead of using the preset ones.

For example, those that use "PalatalHook" (i.e. those with "WITH PALATAL HOOK" in its name) will all extend down using that method, but those with a regular VerticalHook (most likely) use the preset `p` or `if`, making these combinations of essentially identical shapes slightly different:
![image](https://github.com/be5invis/Iosevka/assets/21302803/2493c3a3-f871-4c88-8798-63c2f601edce)

So this leaves the following questions:
1. Do we need to fix the consistency problem above, or how far do we need to enforce it? Or do we make all palatal hook below anchor like that instead, and unify `ɲ` (or even `ԩ`) with those characters?
2. For other cases, when is extendBelow preferred over using `p` or `if` (or `capDesc`)?  
E.g. `ȥ`, which uses `.p` now (forgot to mention in the PR), does not extend down to descender height. Should it use extendBelow instead, like Cyrillic De?
3. Since the phonetic ligatures requires the preset MarkSets, how do we handle those characters that uses extendBelow?  
Not just about consistency, there are cases like `𝼙𝼜` (not supported yet) which would need to extend below descender.

## 2. "ExtendAbove..." equivalent
Currently any characters that extends above Ascender or CAP line uses their own MarkSet (e.g. Ukrainian Ge, Polish O), which has the top anchor for the lowercase forms set to `XH + AccentStackOffset / 2` by hardcoding.

But it looks like there are a separate class of characters that has an extension above the cap line, i.e. the "implosive" consonants in IPA:
- `Ƈ` U+0187
- `ƈ` U+0188
- `Ɠ` U+0193
- `ƥ` U+01A5
- `ɠ` U+0260
- `ʛ` U+029B
- `ʠ` U+02A0
All of them has the hook overlapping with above diacritics (and even if not, their superscript equivalent do), but they are not fixed yet.

These characters also have the hook but do not have the problem:
- `ɓɗƭƙ` (Modifies stem without extension)
- `ʄ` (Uses `if`)

Then do we create an ExtendAbove equivalent for shifting the above anchor (which would create the consistency problem again)? or do we follow `ʄ` which uses the existing ascender height for the above anchor? (if so, what about `ƇƓ`?)

(On an not-completely-unrelated note, there is another character that also needs to extend above CAP line, but not because of any diacritic: I Longa: `ꟾ`)

## 3. Retroflex Hooks
Currently retroflex hooks (using `RetroflexHook`) don't shift the below anchor at all, probably because in many cases they are placed too far right to affect the below diacritics.

However, these causes some glyphs that place the retroflex hook on the left/near the center to overlap with below diacritics. And there are also letters with retroflex hooks (e.g. `ɽɳ`) that do uses the descender line for below anchor anyway.

These definitely overlap:
- `Ʈ` U+01AE (the lowercase version uses `.if`)
- `ʂ` U+0282
- `Ʂ` U+A7C5

These don't overlap as badly, but in most other fonts (Noto) they are shifted down anyway:
- `ɖ` U+0256
- `ʐ` U+0290
- `ᶑ` U+1D91
- `ᶖ` U+1D96 (depends on variant, they may also belong to the first category)

These usually don't overlap:
- `ᶒ` U+1D92
- `ᶐ` U+1D90
- `ᶓ` U+1D93
- `ᶕ` U+1D95
- `ᶙ` U+1D99

Then do we:
- Use `p/if/capDesc` for all of the above cases (or except the last category),
- Follow the PalatalHook and shift it down by `Hook` instead, or
- Also change the below anchor for non-problematic retroflex letters (`ɽɳ`)?

There is also the problem with phonetic ligatures, which do use `.if` for `ʂʐ` ligatures already.

## 4. K with attachments
This definitely is an issue that needs some fixing, I just don't know how:

If any anchor shifts are included by the attached shapes themselves (`CyrDescender`, `PalatalHook`), they are ignored in the creation of `Kk` glyphs.
- `Қ` U+049A
- `қ` U+049B
- `Ⱪ` U+2C69
- `ⱪ` U+2C6A
- `ᶄ` U+1D84

## 5. Other less important issues (or non-issues):
Some other inconsistencies I found, but I have no strong justification that they should be unified. No actions are probably needed and are here just for documentation.

### 5.1. Currencies
Save for [some weird cases](https://en.wikipedia.org/wiki/Turkmen_alphabet), currencies are usually not used as letters, but since many currencies are just letters with strokes, some of them share the metrics as the base letter:
- `¢` U+00A2
- `₡` U+20A1
- `₣` U+20A3
- `₥` U+20A5
- `₩` U+20A9 (etc: `₫€₭₮₱₲₳₴₵₽`)
- `₸` U+20B8 and `⃀` are given MarkSets even though they do not directly use the original shape

while some don't, even if they base form is a letter:
- `$` U+0024 (Though "smaller" variants exist)
- `£` U+00A3 ("Base letter" is not a letter)
- `฿` U+0E3F
- `₤` U+20A4 (Same as pound)
- `₦` U+20A6
- `₧` U+20A7, `₨` U+20A8 and `₯` U+20AE, implemented as compatibility ligatures.
- `₹` U+20B9
- `₿` U+20BF

Similarly, there are these inconsistent symbol/letter treatments also without very good justification:
1. The compatibility Roman Numerals are not given MarkSets, but the "old forms" do:
![image](https://github.com/be5invis/Iosevka/assets/21302803/0077e01c-cebc-4da6-a0d2-92355fa09c9a)
While diacritics (above) do have attested usages on these to represented higher numbers, they are compatibility letters anyway.
2. A few math symbols are given MarkSets, while other don't, even if they are clearly based on letters:
![image](https://github.com/be5invis/Iosevka/assets/21302803/0d54762d-b5b9-49c1-adde-661e099bae0d)
These are not very thoroughly checked, though I suppose math people sometimes like putting diacritic on symbols (e.g. tilde above infinity for "complex infinity", or like a large portion of the math block), so there is a non-zero chance that MarkSets are needed for them too. I'm not sure, however.

### 5.2. Modifiers
In general, one of these three things happen:
1. If the modifier is a super/subscript letter, the MarkSet depends on the base letter.
2. If the modifier is a standalone form of a diacritic, the MarkSet is same as as if the diacritic is added to a XH-high character.
3. Otherwise, no MarkSet are set.

However, there are some unexpected cases where a modifier is a standalone form of a diacritic, but the combining/modifier forms are implemented differently (e.g. difference in size), causing some characters that look like they should belong in case 2 but are actually in case 3:
- `ʻ` U+02BB vs U+0312
- `ʼ` U+02BC vs U+0313
- `ʽ` U+02BD vs U+0314
- `ʾ` U+02BE vs U+0357
- `ʿ` U+02BF vs U+0351
- `ˈ` U+02C8 and `ˌ` U+02CC vs U+030D and U+0329 (technically), although those have their own usages independent of the combining characters
- ``` U+1FEF and `´` U+1FFD with their combining form identified with grave and acute

Though I don't know of any case where these modifiers (not the super/subscript letter ones) need a combining character.

### 5.3. Combining Hooks
In general, they are considered bottom-right combining characters and do not stack with lower glyphs.

However, they will definitely overlap with other lower combining characters, especially for the palatalized hook below which bends towards the center.

Since there are no known ways to stack different mark classes yet (#1789), we can probably ignore this issue for now.

### 5.4. Others
Because of IPA symbols, there are some specific symbols (not based on any letters) that are given MarkSets. e.g.:
- `!` has a MarkSet but `?` doesn't
- Similarly, `|` and `‖` have MarkSet but `¦` doesn't.

Not that these need any serious action tho, imo.

**Comment by be5invis** [comment]
Perhaps we should use `ExtendBelowBaseAnchors` for **ALL** glyphs with descending hook or legs (including Eng, etc.). And make a `ExtendAboveBaseAnchors` for above (upward) hooks, etc. And cover these extensions to Retroflex Hooks and K glyphs.

For marks around Currency / Roman numbers / modifiers / punctuations...... Are there any use case for these?
Including mark information will increase file footprint. Iosevka is already a HUGE font.

**Comment by Logo121** [comment]
The ones starting from Currency are just for documentation and completeness sake. They are not needed (unless someone else finds a use case, then just open a new issue for those).

The problem with `k` glyphs are, even though the descenders (palatalhook and cyrdescender) themselves shift the Below anchors down
https://github.com/be5invis/Iosevka/blob/b6d27c3a60e6ed6829c4d537edc28e755ad585d2/font-src/glyphs/letter/shared.ptl#L809-L811
these are ignored probably because they are not included directly, but are passed through boolean operations:
https://github.com/be5invis/Iosevka/blob/b6d27c3a60e6ed6829c4d537edc28e755ad585d2/font-src/glyphs/letter/latin/k.ptl#L221-L227

So the shifted anchor does not work:
![image](https://github.com/be5invis/Iosevka/assets/21302803/ff237fb7-06bb-46ec-95ef-f83ea5d00786)

**Comment by be5invis** [comment]
We can just add back the adjustments...
![image](https://github.com/be5invis/Iosevka/assets/240091/15ef5c41-f74b-4ab9-a212-85b94776d18d)

**Comment by be5invis** [comment]
![image](https://github.com/be5invis/Iosevka/assets/240091/fba3846a-6c4d-4925-8d01-3641a585f9de)

**Comment by be5invis** [comment]
Hmm I think lowercase Eng should be considered separately since it in most cases are treated as a separate letter. I may let its leg to be extended to reach baseline though.

**Comment by Logo121** [comment]
> Hmm I think lowercase Eng should be considered separately since it in most cases are treated as a separate letter. I may let its leg to be extended to reach baseline though.

That's the annoying part tho...

Most fonts are pretty consistent with how they handle these "n with hook" characters : `ŋɲɳ`, but the letter two (palatal n, retroflex n) are described as "n with hook" unlike eng.

If we say "ŋ" comes from the digraph `ng`, we can also say "ɲ" comes from `gn` (see Italian). Then is the difference just that `ŋ` is popular enough to have a name and `ɲ` not? And where should we draw the line between a "separate letter" and a "letter with augmented/attached shape"?

**Comment by be5invis** [comment]
@Logo121  I think maybe we could just prefer unicode names, i.e., if it is "specially named" then we treated it as a separate letter.

**Comment by be5invis** [comment]
Also, I detached the dimensions of "primary" vs "attachment" hooks, so the hooks considered primary will be slightly larger.

![image](https://github.com/be5invis/Iosevka/assets/240091/869bf111-1440-4f4f-9e33-64839caf488d)

**Comment by Logo121** [comment]
I've done a primitive search on the Unicode names for "specially named" (i.e. those that don't contain the word "with") Latin and Cyrillic characters 

In terms of hook characters, it seems like it really singles out "Eng" as the sole exception. The others are:
* dje `ђ` (Not based on `h` or Eng, but djerv `Ꙉ`. The "hook" stroke is rendered differently in Serif fonts)
* heng `ꜧ` (Ligature of `h` and Eng)

(and Greek "kai Symbol" but tbf the hook is actually longer in other fonts anyway)

But at the same time, does this mean the upturn stroke of `Ꚁ` ("Dwe" in unicode) should be treated differently from that of Ukrainian Ge `Ґ` ("Ghe with upturn" in unicode)? Should Khakassian Che `Ӌ` be considered a unique character and Che with Descender `Ҷ` not?

I don't like the justification by Unicode name, as I fear that it just "favors" characters that are encoded earlier (when naming conventions aren't that established and quite erroneous), or ones that have a more readily usable, historical name (e.g. all those contractions `ꝱꝲꝳꝴꝵꝶ` that are easily considered as derived characters).

Later characters are mostly named as "character with attachment" for the language neutrality, and I don't think there's any character variation of `ŋ` that sets it apart from any other characters with a lower hook. Those n-hook characters are almost always treated as the same in other fonts (or always down to the same height, at least)
![image](https://github.com/be5invis/Iosevka/assets/21302803/c9cacb66-3c63-4ad3-9db4-8292e7a06c7b)

**Comment by be5invis** [comment]
**OK I GIVE UP. LET US UNIFY EVERY HOOK TO DESCENDER AND THAT IS IT.**

**Comment by be5invis** [comment]
I'd like to resolve this now. I've validated all the letters listed in the issue and they now have marks.
For non-letter characters (like currency, letter-like symbols, etc.), we'd like to do it in a case-by-case manner, i.e., until we find a practical use of adding anchors, they will be left as the status quo.

Resolve as fixed.
