### ISSUE TITLE
Wrong shape of "Latin Small Letter L" in Monaco style (ss07)

### ISSUE THREAD

**Issue by kytta** [be5invis/Iosevka#1796]
In ss07, the shape of the "l" (U+006C Latin Small Letter L) is wrong. It should be "zshaped" ([source](https://en.wikipedia.org/wiki/Monaco_(typeface))), like the letter "i" (U+0069 Latin Small Letter I)

<table>
<thead>
<th> Monaco specimen
<th> Iosevka SS07
<tbody>
<tr>
 <td> 

![Monaco specimen](https://github.com/be5invis/Iosevka/assets/6566248/7c635057-7603-43d9-995d-2b1895efcd35)

 <td> 

![Iosevka SS07](https://github.com/be5invis/Iosevka/assets/6566248/4e682b84-cf3b-4f08-aae4-4f7fea2b92b7)

</table>

---

* Your font version: 24.1.3
* Your font variant: ss07
* Your operating system (name and version): Fedora Linux 38
* Your application using Iosevka: GNOME Font Viewer

**Comment by alexeyten** [comment]
Also `f`, `j` and `t` probably should be flat-hooked.

**Comment by kytta** [comment]
> Also `f`, `j` and `t` probably should be flat-hooked.

Yeah, I thought that too! But then I noticed that these letters aren't really flat in Monaco, but have very subtle curves. Thus, I consider Iosevka SS07 to be a close recreation: I'd rather the letters look good in combination with other symbols and have that "Iosevka vibe"

But the "l" is clearly flat

**Comment by be5invis** [comment]
Fixed `l`.
For hooks, Monaco have inward shape so they do not fall into the "flat hook" category.
