### ISSUE TITLE
能否生成一个字面更宽（如1.5倍半角宽度）的版本呢~

### ISSUE THREAD

**Issue by MadMaxChow** [be5invis/Iosevka#18]
现在的版本是严格以全角中文半宽来制作，但这对于日常程序代码显示相对会有点过窄，影响可读性。
能否像其它等宽字体那样字面更宽一些（如MENLO等），谢谢！

**Comment by be5invis** [comment]
Sorry, but Iosevka is designed to be a narrow typeface. You can edit the `parameters.patel` to enlarge the `width` parameter, but the results are not guranteed.
