### ISSUE TITLE
Less condensed versions of Iosevka

### ISSUE THREAD

**Issue by freak4pc** [be5invis/Iosevka#180]
* Your font version: Release 1.12.2
* Your font variant: Medium / Bold
* Your operating system (name and version): macOS Sierra
* Your application using Iosevka: Xcode

This seems like a really great font, but the level of condensation between the characters seems very high for daily use. Any way we would be able to see some less-condensed versions ?

Iosevka Medium:
![image](https://cloud.githubusercontent.com/assets/605076/24599706/1ccf581a-185a-11e7-85f3-791f896948bb.png)

Menlo Bold: 
![image](https://cloud.githubusercontent.com/assets/605076/24599790/83c9e10c-185a-11e7-8fe3-1c4cc95af567.png)

**Comment by be5invis** [comment]
I've added an `expanded` style into Master that... expands every character by a 15% percentage. However some glyphs **may be broken** due to that Iosevka is designed under current width.

Build with this:
```bash
make custom-config poststyle='expanded'
make custom
```

**Comment by freak4pc** [comment]
I'll give it a try and report my findings :) Thanks !

**Comment by be5invis** [comment]
@freak4pc I've found that some derived glyphs of `s` is broken under bold weights.
And, **expanded versions are not a design target of Iosevka**. Fixing breaks in it would be in a low priority.

**Comment by firedev** [comment]
I'd love even more condensed version. How do I do that?

**Comment by be5invis** [comment]
@firedev 
The latest `master` has a `compressed` either...

**Comment by firedev** [comment]
Great, thanks! I can compress in iTerm but not system-wide, now this should be solved.

**Comment by robertgzr** [comment]
Is there a way to build them as separate fonts with their own name?

I want something like Iosevka, Iosevka Term, Iosevka Condensed, Iosevka Expanded.

Basically a way to give my `custom-config` it's own name so it doesn't replace the default.

**Comment by be5invis** [comment]
@freak4pc @firedev @robertgzr 
The next version will have `expanded` and `compressed` as usable building style, but they are highly unstable and **will not be documented**.

**Comment by marcelkorpel** [comment]
In my experience (and by looking at the code) the command should be

    make custom-config prestyle='expanded'

**Comment by be5invis** [comment]
@marcelkorpel The current code has merged `expanded` and `compressed` into `design`, simply use `design` would work.

**Comment by be5invis** [comment]
Move to #196.
