### ISSUE TITLE
Incorrect ligature for `:)`

### ISSUE THREAD

**Issue by BYK** [be5invis/Iosevka#1801]
The regular simple smiley (`:)`) incorrectly turns into a weird version of `})`

![image](https://github.com/be5invis/Iosevka/assets/126780/c7d0dcd4-c67a-42f6-b7b3-cc86187aa09b)

---

* Your font version: 24.1.3
* Your font variant: SS08
* Your operating system (name and version): Windows 10 Version	10.0.19044 Build 19044
* Your application using Iosevka: Firefox Developer Edition

**Comment by BYK** [comment]
This is quite new. I think I was using `24.1.1` before this without the issue.

**Comment by be5invis** [comment]
![image](https://github.com/be5invis/Iosevka/assets/240091/83c2c359-32e4-4c14-9163-f19363861cf0)
I cannot repro using Firefox (the font version is the latest `dev`). Maybe you should try uninstall the font, restart computer, then reinstall. Caching may sometimes cause weird results.

**Comment by BYK** [comment]
Strangely enough, I also could not reproduce now that I installed the latest version again.

Closing but will keep an eye if it occurs again and document more specific repro steps. Thanks a lot for Iosevka and sorry for the noise! :)

**Comment by alexeyten** [comment]
I guess, you've installed new font files over older ones and did not restart firefox.
I see something like this almost every time I build a new version of font and it replaces older one.

**Comment by BYK** [comment]
>I guess, you've installed new font files over older ones and did not restart firefox.

That's quite possible as I don't recall restarting Firefox when the issue occured. 😅
