### ISSUE TITLE
Iosevka web font files are rejected by sanitizer

### ISSUE THREAD

**Issue by corviraptor** [be5invis/Iosevka#1803]
Hello! Apologies if this is the wrong place to ask about this, but I'm having an issue where it appears that there is something wrong with the Iosevka Slab .woff2 and .ttf files. I'm not familiar with webdev at all, so I apologize if the problem is user error instead of an actual bug with Iosevka. I'm trying to make a web app, but whenever I run the app I get these errors in the Page Inspector for every @font-face declaration in my CSS file (which are all Iosevka Slab):
`downloadable font: rejected by sanitizer (font-family: "Iosevka Slab Web" style:normal weight:500 stretch:100 src index:0) source: http://.../woff2/iosevka-slab-medium.woff2`
I tried the previous release as well, but it didn't change anything. I also tried changing the font family name to "iosevka-slab" but that didn't change anything either.

Thank you!

---

* Your font version: Release 24.1.3
* Your font variant: Iosevka Slab
* Your operating system (name and version): Windows 10, Version 10.0.19044 Build 19044
* Your application using Iosevka: Website (WebAssembly & Yew)

**Comment by Logo121** [comment]
How does the `@font-face` declaration look like? Where does it grab the fonts from?

**Comment by corviraptor** [comment]
Here is what the declarations look like (multiple versions are declared in the file)

`@font-face {
    font-family: 'iosevka-slab';
    font-display: swap;
    font-weight: 500;
    font-stretch: normal;
    font-style: normal;
    src: url('woff2/iosevka-slab-medium.woff2') format('woff2'),
    url('ttf/iosevka-slab-medium.ttf') format('truetype');
}`

and the woff2 and ttf folders are on the same level as the style sheet, like so:
![image](https://github.com/be5invis/Iosevka/assets/105324977/192aff0c-031c-4034-acf6-8f8b10b5e4f1)

**Comment by Logo121** [comment]
Seems to work using just a web browser (locally, on Firefox, at least)

Probably an external problem, though I have no experience in Yew to tell. Maybe check out [this SO post about importing local fonts](https://stackoverflow.com/questions/74764502/how-to-render-a-font-using-yew-rust), or just consider using some webhosted builds [like this one](https://github.com/iosevka-webfonts) (not hosted by us tho)

**Comment by corviraptor** [comment]
The webhosted build works for sure, thank you. I'll probably look into fixing it locally so I don't have to depend on that staying up, but for now this will do. Thank you very much!
