### ISSUE TITLE
In Enclosed Alphanumeric symbols, Enclosed Q's are shifted up by their descenders

### ISSUE THREAD

**Issue by Logo121** [be5invis/Iosevka#1812]
These:
![image](https://github.com/be5invis/Iosevka/assets/21302803/92f98d7c-8afa-4463-907e-fcd3852d7a64)
Or these:
![image](https://github.com/be5invis/Iosevka/assets/21302803/f98aed0b-ef1c-4085-8d75-251ffe4c1cca)

**Comment by jmcwilliams403** [comment]
I always thought this was deliberate as there are some characters which would nearly clip out of the enclosing circle otherwise.

**Comment by Logo121** [comment]
I see. Considering [this](https://github.com/be5invis/Iosevka/issues/751) is the first related issue I find, I suppose this *is* intended. I'm closing this.

Does the parenthesized one really need shifting tho?
