### ISSUE TITLE
Serif of U+1D12 LATIN SMALL LETTER SIDEWAYS OPEN O is on the wrong side

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#1814]
U+1D12 LATIN SMALL LETTER SIDEWAYS OPEN O should look like U+0254 LATIN SMALL LETTER OPEN O rotated 90° counterclockwise. The serif is on the wrong side.
![ᴒɔ](https://github.com/be5invis/Iosevka/assets/1124347/f7be9c9e-2eec-4984-b68a-0a68877873eb)

---

* Your font version: 24.1.4
* Your font variant: Iosevka Slab Extended
* Your application using Iosevka: hb-view

**Comment by Logo121** [comment]
ok who called the glyph "revSmallCSideways" then? ☹

**Comment by jmcwilliams403** [comment]
> ok who called the glyph "revSmallCSideways" then? ☹

Open O is typographically a turned C as that's how they were able to save money on wooden or cast-metal typefaces for the early IPA. All they needed for a large amount of new letters was to turn existing ones upside down.

Reversed C is literally a horizontally mirrored C as the glyph was conceived when typefaces were still handwritten;<br>It's [basically the Latin equivalent of the Greek Lunate Sigma/Antisigma](https://en.wikipedia.org/wiki/Claudian_letters).

**Comment by Logo121** [comment]
I know what Open O should look like, I was just confused by the preexisting naming in the code and [messed the glyph up when trying to fix it](https://github.com/be5invis/Iosevka/pull/1792/files#diff-54b08ad0eb1a10d822aa3131394434ff833d307e91648b9de21a6303a06aa76c).
