### ISSUE TITLE
Add support for Small Caps (smcp) feature in Iosevka

### ISSUE THREAD

**Issue by ryanlo713** [be5invis/Iosevka#1815]
**Is your feature request related to a problem? Please describe.**

Iosevka currently does not support the Small Caps feature (smcp), which I need to implement specific HTML typography.

**Describe the solution you'd like**

I would like to request support for the Small Caps (smcp) OpenType feature in the Iosevka project. This feature would transform lowercase characters into small capitals. Iosevka currently supports all Small Caps characters according to Unicode specifications, except for Small Cap X, e.g. **ᴀʙᴄᴅᴇꜰɢʜɪᴊᴋʟᴍɴᴏᴘꞯʀsᴛᴜᴠᴡXʏᴢ**. It is suggested that an existing glyph could potentially be used to implement the Small Caps feature.

**Describe alternatives you've considered**
There don't seem to be any alternative solutions or features that have been considered at this time.

**Additional context**
I would appreciate it if the Iosevka font project could consider adding support for Small Caps (smcp) feature. This would greatly benefit my use case. Here is an example of how this feature could be utilized: 

![example image showcasing Small Caps feature](https://github.com/be5invis/Iosevka/assets/12672523/54cd8762-57d3-4a4f-8126-ff07863b573c)

**Comment by be5invis** [comment]
This may introduce TOO MANY new glyphs, while Iosevka already have >30000 glyphs (which is already larger than many CJK fonts).
In addition I see low necessarity for a programming font to support `smcp`/`c2sc`.
Mark as Needs Justification.

**Comment by Logo121** [comment]
There is `font-variant-caps: small-caps;` that provides a fallback solution by scaling the caps, if that suits your use case.
