### ISSUE TITLE
Customizable line heights

### ISSUE THREAD

**Issue by stlee42** [be5invis/Iosevka#1821]
Setting `leading` in `parameters.toml` results in clipping.

Setting `leading` to `1000` got me to Consolas level, whereas I wanted to go all the way down to DejaVu Sans Mono level.

Since `parameters.toml` says `Default line height times 1000.`, I guess 1000 is as low as that goes.

However, the generated font does clip under macOS Terminal.app most noticeably on lowercase g. 
Please see [this comment](https://github.com/be5invis/Iosevka/issues/103#issuecomment-310202544). FWIW, I am using ss03 stylistic set.

It would be great if Iosevka had a way of achieving DejaVu Sans Mono level line spacing.

<img width="173" src="https://github.com/be5invis/Iosevka/assets/42285007/f74de521-fec4-43f3-ac66-fa0dbdb57a9a">

**Comment by stlee42** [comment]
One thing to note is that in macOS Terminal, there is a line spacing parameter I can set in font selection menu, and I can actually get it to any size that suits me. I can set it really low and font shapes will overlap each other instead of clipping like above.

I think something like that would be very desirable.

<img width="173" src="https://github.com/be5invis/Iosevka/assets/42285007/520bc7a5-52c1-4c55-94e8-04a02d63bd99">

**Comment by Logo121** [comment]
You can definitely set leading to below 1000 I think, not sure about the clipping tho. Check #343 or other issues linked to that.
