### ISSUE TITLE
Rounder/Circular Empty Set

### ISSUE THREAD

**Issue by Logo121** [be5invis/Iosevka#1822]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

Also affects: `⦰⦱⦲⦳⦴`.

Justification:
1. Empty set being non-circular is pretty rare in monospace fonts, even narrow ones like PragmataPro.
I guess this form is based on an old version of PragmataPro (as seen in Fileformat): ![image](https://github.com/be5invis/Iosevka/assets/21302803/b179eea9-6d86-4bb1-8317-850dc12927fc)
But even they have changed the shape into a circular one since then. All other fonts I found uses a slashed circle.  
If the current shape is instead based on the stroked zero (like TeX), then
2. The stroked zero form is SVS (see #1535), so having a base variant that is unlike the zero form would be preferable.  
(Though it doesn't seem like the current shape is affected by `0` cvs either anyway)
3. The symbol is also used in linguistics as a "Null morpheme", so it might be confused with the almost-identical looking Slash-O `Ø` (though probably not *that* likely) 
![image](https://github.com/be5invis/Iosevka/assets/21302803/fe53657c-98ca-44ca-b56f-1d44c10b01a3)

Some design considerations:
* The circle can be aligned with either the APL or the Math Circles (for some reason they are different?).
* The slope can either be at a 45deg angle, or a bit steeper than that (e.g. PramgataPro).

Here's a comparison of O-plus, Empty Set, O-slash, Diameter (not in Iosevka), APL circle-backslash, and the two Latin Slash-O's (`⊕∅⊘⌀⍉øØ`):
![image](https://github.com/be5invis/Iosevka/assets/21302803/3bb4f784-79aa-42d8-86dc-4ef36e3470b6)

**Comment by be5invis** [comment]
It may not have a CV/SS feature but be done using SVS

**Comment by be5invis** [comment]
I'd like to use the oval shape to distinguish with O-slashes.
![image](https://github.com/be5invis/Iosevka/assets/240091/82745485-55c7-4aff-8f10-9891d48c32c1)

For the purely rounded shape I do not think it is a very good choice -- since the empty sets are _values_ instead of _operators_, I'd like to make it look more like a letter/digit instead of an operator.
