### ISSUE TITLE
Serifs for Latin Lambda with Stroke? (U+019B)

### ISSUE THREAD

**Issue by Logo121** [be5invis/Iosevka#1826]
Unsure about this again, but you know the thing with Latinized Greek letters having Latin-like serifs.

Latin Lambda is probably another case for that, but as of now only the "with stroke" version is encoded as U+019B (`ƛ`). The no-stroke version is [proposed](https://www.unicode.org/L2/L2021/21206-add-latin.pdf) and deemed "acceptable", but are blocked by some problems with another letter in the same proposal (latin theta).

In the proposal, they have serifs for the lambda letters, making them look like an inverted (straight) y:  
![image](https://github.com/be5invis/Iosevka/assets/21302803/7ae47fa5-6f88-4327-8a3d-5c87d8abfd21)
And they did the same for lambda with stroke: ![image](https://github.com/be5invis/Iosevka/assets/21302803/5e78a689-5741-4920-8324-0652a65f71ad)

However, since the Unicode sample still shows the glyph as a Greek lambda with stroke, which is how most fonts render it.  
The exception is Brill: ![image](https://github.com/be5invis/Iosevka/assets/21302803/309b5fd9-bef0-44bb-abb7-5d85e3ecc09f)
and this very old ["Languagegeek font"](https://www.languagegeek.com/font/fontdownload.html#Full_Unicode), kinda, which has a top serif for some reason: ![image](https://github.com/be5invis/Iosevka/assets/21302803/dfa374c0-622e-4b72-a1d7-6904fbee4955) (the left one is Latin Lambda in its PUA)

Nishiki-Teki also kinda differentiates between Latin and Greek lambda (by having the Latin one straighter), though it is a san-serif font anyway: ![image](https://github.com/be5invis/Iosevka/assets/21302803/525bb018-940e-44b9-a20d-b8a41e36b379)
It also encodes the no-stroke version in PUA, again differentiated from Greek:
![image](https://github.com/be5invis/Iosevka/assets/21302803/d1663db0-f91d-4eae-a2f4-4d725a4031d1)

Btw, for italic, both of the 2 serif fonts above agree that it looks like this: ![image](https://github.com/be5invis/Iosevka/assets/21302803/5e053847-a438-4415-82d4-ab5285f07769)
I don't know what it would look like when translated to Iosevka's style, but fyi.

**Comment by Logo121** [comment]
(btw, I'm actually not quite sure what template/tag to use when I raise issues on glyph shapes. If I think the existing one is also "valid" but the proposed one is "better", I'll use Variant Request.)

**Comment by jmcwilliams403** [comment]
I'd like to also add that Latin Beta and Latin Phi are currently configured to have independent serif forms from the Greek letters, and that Latin Lambda with stroke would be another letter that behaves like that.

**Comment by Logo121** [comment]
Some update on the Latin Lambda:

A revised proposal for the Latin Lambda has been submitted and tentatively approved by the Unicode committee, which has the following description for the Latinized form: (https://www.unicode.org/L2/L2023/23191-three-latin-additions.pdf)
![image](https://github.com/be5invis/Iosevka/assets/21302803/06518701-4080-4b44-854b-03b546a7ef73)

Basically:
* Both forms are "recognized" by the users of these letters. However, they chose the Greek form in the proposal this time for consistency with the existing Unicode representation of `ƛ`.
* The "latin variant" they used is the LanguageGeek "serifed ascender" form instead (though the "inverted y" form appears later in the document). They did not explain the variation between these 2 forms, but I assume they aren't considered that different anyway.
* Not related to this issue, but the Capital Latin Lambda also has 2 variants (note the top serif): ![image](https://github.com/be5invis/Iosevka/assets/21302803/a096baf2-3c1e-4677-b35b-7810a0f3d2dd) ![image](https://github.com/be5invis/Iosevka/assets/21302803/df8f1fb5-f0e3-41c1-a454-bf90011d8989)

Since the author opted for the non-latinized version in the proposal, I suppose it's not that important. Still my (weak) justifications are:
1. For Latinization of the glyph (and possibly the upcoming Latin Lambda) like Latin Phi/Beta/Chi (like jmcwilliams said)
2. As possible (but not necessary) differentiation from Greek Lambda
3. I don't think the Greek-like form is really "required" for NAPA anyway, so the character can just be changed to the Latinized version.

**Comment by jmcwilliams403** [comment]
Alternatively another idea is to make latin lambda follow non-cursive y like turned y does
