### ISSUE TITLE
Capital Schwa (`U+018F`) serifed form following capital C

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1829]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

This is a common form when used in a natural-language context like in e.g. Azerbaijani.

`cCƏəe`

Courier New:
![image](https://github.com/be5invis/Iosevka/assets/37010132/c130fc53-7083-4566-959b-e5088cb11007)

Liberation Serif:
![image](https://github.com/be5invis/Iosevka/assets/37010132/e1e2345a-d97b-4d81-8df0-2bc74c28eec3)

Source Serif, here using Cyrillic schwa:
![image](https://github.com/be5invis/Iosevka/assets/37010132/8c369a50-a33d-481b-b7e0-2edba6b0c67a)

Cambria, which also serifs the lowercase form:
![image](https://github.com/be5invis/Iosevka/assets/37010132/a868e006-8a8f-41bb-806e-316d4eac1cdf)

Code 2000:
![image](https://github.com/be5invis/Iosevka/assets/37010132/5768d669-4328-4e57-9872-875518aff1b0)

Times New Roman:
![image](https://github.com/be5invis/Iosevka/assets/37010132/bf3dd034-c9aa-46b6-8ddd-0b4ff987333e)

**Comment by be5invis** [comment]
_Maybe_ we will need it to be influenced by both `C` and `e`'s settings
