### ISSUE TITLE
 有没有可能把中文版神秀的思源黑改成思源宋呢。 推出了 ，我觉得很好看，但不知用来编程是什么效果。

### ISSUE THREAD

**Issue by Smallthing** [be5invis/Iosevka#183]
* Your font version: (Release or git, version)
* Your font variant:
* Your operating system (name and version):
* Your application using Iosevka: (some Java applications may have problem in showing Iosevka properly. It is a bug in Java's GUI components.)

If you have problem when building Iosevka, please provide these informations:

* Your Node.js version:
* Your _otfcc_ version:
* Your `make` version:
* Your results of `npm list`:
```
paste here
```
* Your `parameters.toml`:
```
paste here
```
* Your results of `make -d --no-builtin-rules`:
```
paste here
```
---

Describe your problem here. Provide pictures and files if necessary.

**Comment by be5invis** [comment]
No.
Iosevka is a **sans-serif**.

**Comment by rushcheyo** [comment]
@be5invis 
But Iosevka Slab is a **serif**.

**Comment by be5invis** [comment]
@rushcheyo Iosekva Slab’s Serif ≠ Source Serif Pro’s Serif
You can compare their contrast
