### ISSUE TITLE
Thinning alternative to slab serifs

### ISSUE THREAD

**Issue by Pararanta** [be5invis/Iosevka#1831]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [ ] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

Hi, I would like to request/create something similar to simplified Oldstyle serifs, especially horizontal ones.
Some monospace fonts have something similar, but it is not a popular choice.
That said, I think it would suit Iosevka's narrowness well.
Century Schoolbook Monospace Regular does something alike with its vertical serifs
![image](https://github.com/be5invis/Iosevka/assets/54844502/ecc28702-9bef-478f-a362-2b2673c19a6b)

If this kind of change is unfeasible, I will be grateful for any pointers on how to achieve it on my own.
I managed to find where HSerif is generated and hope there is an option to create this effect there, but I have no clue on how to change stroke thickness, not to mention vary it across serifs.

**Comment by Pararanta** [comment]
A short compilation of what I managed to tinker with, all thanks to @Logo121

I will show it on the left top serif since it is the first one.

Base code
```
define HSerif : namespace
		export : define [lt x y length _sw _swRef] : glyph-proc
			local sw : fallback _sw Stroke
			local swRef : fallback _swRef sw
			include : dispiro
				flat (x + 0.5 * HVContrast * swRef) y [widths.heading sw 0 Leftward]
				curl (x - length - TanSlope * (sw * DesignParameters.serifShiftX)) y
```
![image](https://github.com/be5invis/Iosevka/assets/54844502/6ef0cfa0-d1e8-4816-a020-abc278931d7a)


Code proposed by Logo121, with slight mod, first sw * kThin does not seem necessary.
```
flat (x + 0.5 * HVContrast * swRef) y [widths.heading sw 0 Leftward]
curl (x - length - TanSlope * (sw * DesignParameters.serifShiftX)) y [widths.heading 0 (sw * kThin) Leftward]
```
![image](https://github.com/be5invis/Iosevka/assets/54844502/4072d82a-0188-447e-82cc-69e35b453ef5)


We may multiply by kThin first expression to get the following effect
```
flat (x + 0.5 * HVContrast * swRef) y [widths.heading (sw * kThin) 0 Leftward]
curl (x - length - TanSlope * (sw * DesignParameters.serifShiftX)) y [widths.heading sw 0 Leftward]
```
![image](https://github.com/be5invis/Iosevka/assets/54844502/5f0db0ed-2a51-423a-a619-bfc2a08fc4ef)


I managed to arrive at my original objective using Your corner trick and moving the whole thing one sw down
corner is necessary to avoid *floating* serifs on curved letters
```
flat (x + 0.5 * HVContrast * swRef) (y - sw) [widths.heading 0 sw Leftward]
corner x y [widths.heading sw 0 Leftward]
curl (x - length - TanSlope * (sw * DesignParameters.serifShiftX)) (y - sw) [widths.heading 0 (sw * kThin) Leftward]
```
It is more or less what I imagined, I would prefer it to temper across the whole top of the letter,
but I did not manage to do that due to the issue mentioned later.
![image](https://github.com/be5invis/Iosevka/assets/54844502/3f9d9168-5f68-4eb6-b48a-395cb36cd9c8)


There are some more interesting serifs I have encountered, ex.
```
flat (x + 0.5 * HVContrast * swRef) y [widths.heading sw 0 Leftward]
curl (x - length - TanSlope * (sw * DesignParameters.serifShiftX)) y [widths.heading 0 (sw * kThin) Leftward]
```
![image](https://github.com/be5invis/Iosevka/assets/54844502/f690e165-0420-47dc-8730-7106fff91c3a)


The overall main issue I have encountered was inconsistent anchor across *long* and *short* serifs (without moving it down)
'j's serif is to the right while most of them are in the middle
```
flat (x + 0.5 * HVContrast * swRef) y [widths.heading 0 sw Leftward]
curl (x - length - TanSlope * (sw * DesignParameters.serifShiftX)) y [widths.heading 0 (sw * kThin) Leftward]
```
![image](https://github.com/be5invis/Iosevka/assets/54844502/eedadf37-c3b9-4756-9f76-f75aa91325d9)


At this point, I do have what I was looking for.
If there is any incentive to develop it further, I am available to help in my free time.
Considering I did that using trial and error, I will need guidance if the above is decided.

**Comment by Pararanta** [comment]
I was able to fix my issues by editing the glyphs themselves
![image](https://github.com/be5invis/Iosevka/assets/54844502/56eefa78-654b-492a-9950-887d755691e0)

in 'j'
```
	define Serifs : namespace
		export : define [Long df top xMiddle] : HSerif.lt xMiddle top (LongJut * df.div)
```
changed to
```
	define Serifs : namespace
		export : define [Long df top xMiddle] : HSerif.lt (xMiddle - HalfStroke * HVContrast) top (LongJut * df.div)
```

in 'il'
```
	define Serifs : namespace
		export : define [Hooky        df top xMiddle] : HSerif.lt xMiddle top (LongJut * df.div)                                         Stroke df.mvs
		export : define [Serifed      df top xMiddle] : HSerif.lt xMiddle top ((LongJut * df.div) - (xMiddle - df.middle))               Stroke df.mvs
		export : define [SerifedShort df top xMiddle] : HSerif.lt xMiddle top [mix Jut ((LongJut * df.div) - (xMiddle - df.middle)) 0.5] Stroke df.mvs

```
changed to
```
	define Serifs : namespace
		export : define [Hooky        df top xMiddle] : HSerif.lt (xMiddle - HalfStroke * HVContrast) top (LongJut * df.div)                                         Stroke df.mvs
		export : define [Serifed      df top xMiddle] : HSerif.lt (xMiddle - HalfStroke * HVContrast) top ((LongJut * df.div) - (xMiddle - df.middle))               Stroke df.mvs
		export : define [SerifedShort df top xMiddle] : HSerif.lt (xMiddle - HalfStroke * HVContrast) top [mix Jut ((LongJut * df.div) - (xMiddle - df.middle)) 0.5] Stroke df.mvs
```

I do not expect it to be considered as change. Just typing my botch.

**Comment by be5invis** [comment]
Doing this will require changing a lot of things... This is not creating a new variant but creating a new *style*.

**Comment by Pararanta** [comment]
I am making this since I need to physically print some documents with code embedded, and slab serifs do not match the main font.

I doubt there is a large audience for it, so feel free to close it.
I will try to make at least one working font and post diff here in case someone is in a similar situation.

**Comment by Logo121** [comment]
> I managed to arrive at my original objective using Your corner trick and moving the whole thing one sw down
> corner is necessary to avoid _floating_ serifs on curved letters

The "corner trick" is only applied in my case for serifs jutting both sides (`HSerif.mt` or `HSerif.mb`), like those in `n` or `v`.

But seeing that you want serifs that thin towards the other way round like this (Garamond):
![image](https://github.com/be5invis/Iosevka/assets/21302803/8ec8d848-ac7f-45ed-9a42-0172b419e255)
Then there's quite a bit more work you need to put on. You might want to shift the end of the stem down (instead of the serif placement up), and having more types of HSerifs (for the topleft of `D` and `u` respectively, for example)

Though at this point it's probably better to just fork your own version since a lot of tiny adjustments are likely needed.

**Comment by be5invis** [comment]
Maybe we could mimic Didot/Bodoni, just make serifs slightly thinner?

**Comment by TimurGerasimov250** [comment]
Please reopen this and consider this idea and talk more. Needs more explanation 
And remove stale label
