### ISSUE TITLE
Cyrillic Small Yer (hard sign) (`U+044C`) with wavy bar like IBM Plex Mono

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1833]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [ ] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

`ZЪЬzъь`

IBM Plex Mono Regular:
![image](https://github.com/be5invis/Iosevka/assets/37010132/7402ba4e-358b-4ea8-a344-ccb7747e93d3)

IBM Plex Mono Italic:
![image](https://github.com/be5invis/Iosevka/assets/37010132/eb3d3218-3625-492c-9dfa-0dc38d3b5cb4)

DejaVu Serif Book:
![image](https://github.com/be5invis/Iosevka/assets/37010132/b0777a4b-568d-4452-b42b-47eddf4de846)

DejaVu Serif Italic:
![image](https://github.com/be5invis/Iosevka/assets/37010132/ad37a4b6-2b14-4447-8ddc-f72d5a79b630)

**Comment by Logo121** [comment]
DejaVu Serif is not a monospace font tho?

(Not monospace either, but apparently Brill has this too, which applies to Back Yer Yery `ꙑ`: 
![image](https://github.com/be5invis/Iosevka/assets/21302803/e0446ce5-c6ba-4503-be3d-3c86b185fcc3))

**Comment by jmcwilliams403** [comment]
> DejaVu Serif is not a monospace font tho?

I showed DejaVu Serif because Iosevka supports Menlo which is basically just an older version of DejaVu Sans Mono. It's just the closest thing to a DejaVu Serif Mono that actually exists.

**Comment by be5invis** [comment]
Let's just modify the curisve variant of Yer since, well, it is already named as "cursive"...

**Comment by jmcwilliams403** [comment]
That might work, but maybe change the name of the variant selector to be about Yer since it shows more information, because the soft sign is basically the hard sign minus the bar.

**Comment by jmcwilliams403** [comment]
Closing because this could just be a handwriting quirk and may be considered be out of scope. Plus, only one SS as justification isn't enough anymore as the font is getting way too complex.
