### ISSUE TITLE
Playing Cards (`U+1F0A0`..`U+1F0F5`)

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1835]
- The requested character is...
  - [ ] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [x] Symbol
- [x] Some other monospace/programming fonts supported this character. Provide images below.

------

Pragmata Pro, representing Knight as C for Cavalier, which is the french word for Knight (I prefer using this label for this card):
![image](https://github.com/be5invis/Iosevka/assets/37010132/76b1be29-12a7-411d-bd5a-7b9621189736)

Fairfax HD, representing Knight as N for K[n]ight, and also representing the 0 thru 21 trump cards as Roman Numerals (this is actually how these trump cards are labeled in real life to contrast with the normal arabic 1 or 2 thru 10):
![image](https://github.com/be5invis/Iosevka/assets/37010132/2b816df0-dab2-4547-ae56-ceb298bc81d7)

Additionally, if the complete block is supported, it's common for Ace to be labeled as 1 instead of A in the complete real-life French Tarot deck which this block represents, but it's up to you if you care about going that far.

**Comment by Logo121** [comment]
related: #495

though I guess another set of characters (#1418) in that issue got put into backlog too so

**Comment by jmcwilliams403** [comment]
I made a rough mockup using the boxed enclosure functions.
Not sure if I'm all that happy with it yet but here's what it looks like so far:
![image](https://github.com/be5invis/Iosevka/assets/37010132/fdfd47a6-65b9-4f8a-ae5e-4492377ad61c)
