### ISSUE TITLE
Lowercase t with right-sided crossbar and tail

### ISSUE THREAD

**Issue by Siphercase** [be5invis/Iosevka#1836]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------
Though I have not found a monospace / coding font that includes this design, quite a large number of typefaces have adopted it as an stylistic option (Ubuntu, YouTube Sans, Accord, Earthbound _etc._).

Iosevka also has 3 "hookless-asymmetric" variants of ⟨t⟩. Maybe better with "hooked-asymmetric" variants. Since Iosevka differs "standard" "flat" and "diagonal" tails of ⟨t⟩, there might be 9 new variants or so.

Anyway I love Iosevka and appreciate all the work you have done :3 Best regards!

**Comment by be5invis** [comment]
Any image?

**Comment by Logo121** [comment]
I'm guessing he meant the ability to mix the existing "asymmetric" variant with those variants that has a tail, like the letter `t` in the old(?) twitter logo
![image](https://upload.wikimedia.org/wikipedia/commons/8/8b/Twitter_logo_initial.svg)

Going off the programmingfonts.org list I find:
![image](https://github.com/be5invis/Iosevka/assets/21302803/53815bb7-f1a7-4ba2-8843-801dc31ec465)
and
![image](https://github.com/be5invis/Iosevka/assets/21302803/1ef823c2-28be-4566-bda0-023429037ea1)
with this variant of `t`.

So this either requests an "asymmetric flat hook" variant, or to split "asymmetric crossbar" into its own buildup component I guess?

**Comment by Siphercase** [comment]
Thanks @Logo121 for clarifying my statement. My bad.
So the requested variant now meets all 3 requirements now? *chuckle*

My scribbles below:
!["Standard"](https://github.com/be5invis/Iosevka/assets/107249801/e788826e-7330-4d30-81d5-83ca661096bb)
!["Flat"](https://github.com/be5invis/Iosevka/assets/107249801/d4aeba0f-64c7-478f-9244-fc220605c928)
!["Diagonal"](https://github.com/be5invis/Iosevka/assets/107249801/354eb7de-dfe4-45d8-b0c1-e25eefad6a8a)

**Comment by be5invis** [comment]
Oh, fine, we will need to reorder the variants of `t` again.
Ah let's just trating reordering of CVs non-breaking...
