### ISSUE TITLE
U+A666 and U+A667 have off-center serifs

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#1838]
U+A666 CYRILLIC CAPITAL LETTER SOFT EM and U+A667 CYRILLIC SMALL LETTER SOFT EM have off-center serifs. This might be necessary for some variants as in #1795, but not when the middle isn’t aligned to the baseline.
![Ꙧꙧ](https://github.com/be5invis/Iosevka/assets/1124347/04138dc0-fe62-4bb6-829a-ba33446ceabf)

---

* Your font version: 25.0.0
* Your font variant: Iosevka Slab Extended
* Your operating system: macOS 13.4.1
* Your application using Iosevka: hb-view

**Comment by Logo121** [comment]
Might be also worthy to mention that the baseline variant differs in Sans and Slab even with the same Serif setting:
![image](https://github.com/be5invis/Iosevka/assets/21302803/5a250d93-d209-4398-823a-6688fd00f2a2) (sans) vs (slab) ![image](https://github.com/be5invis/Iosevka/assets/21302803/2a3d9586-c8cd-4c07-be45-525c967606a8)

The middle is shifted up in Slab before the overhaul probably to prevent the mentioned overlap, but this change still depends on the SLAB variable, causing this discrepancy.
