### ISSUE TITLE
Cyrillic capital Z and number three are the same

### ISSUE THREAD

**Issue by jozsefk9** [be5invis/Iosevka#184]
* Your font version: (Release 1.12.2)
* Your font variant: Type
* Your operating system (name and version): Windows 10 64bit
* Your application using Iosevka: Notepad++
---

This font is amazingly beautiful. There is only one problem I see about it right now: Cyrillic capital Z and number three are the same: https://s.mail.ru/KaE8/tpS5QbiNT
![img-2017-04-04-14-46-16](https://cloud.githubusercontent.com/assets/1645288/24653118/8972f288-1945-11e7-920f-97c93d638d78.png)

**Comment by be5invis** [comment]
Well... they look the same in SCP either...
![image](https://cloud.githubusercontent.com/assets/240091/24653227/86439d7a-1967-11e7-85e4-ef11f09cf0d5.png)
the left is `3` and the right is `З`.

**Comment by be5invis** [comment]
Consolas:
![image](https://cloud.githubusercontent.com/assets/240091/24653372/274baef6-1968-11e7-88a5-51e91cc520e5.png)

**Comment by jozsefk9** [comment]
![img-2017-04-04-14-54-57](https://cloud.githubusercontent.com/assets/1645288/24653411/bf4e6d78-1946-11e7-829d-9400276d630a.png)
![img-2017-04-04-14-54-15](https://cloud.githubusercontent.com/assets/1645288/24653410/bf4c1730-1946-11e7-8a62-c7921f04253c.png)
![img-2017-04-04-14-53-12](https://cloud.githubusercontent.com/assets/1645288/24653409/bf4bd68a-1946-11e7-8859-b02938ef3d5b.png)

**Comment by be5invis** [comment]
Pragmata Pro
![image](https://cloud.githubusercontent.com/assets/240091/24653464/83c4cbd6-1968-11e7-93b9-c4b4f8d89149.png)
![image](https://cloud.githubusercontent.com/assets/240091/24653469/88ad3c14-1968-11e7-806d-1acfb798a0d5.png)

**Comment by jozsefk9** [comment]
![img-2017-04-04-15-12-51](https://cloud.githubusercontent.com/assets/1645288/24654094/58b159ce-1949-11e7-8186-de806d16555a.png)

**Comment by be5invis** [comment]
@jozsefk9 
Geez, examples for “same” and “different” ends up in a tie...
However are there situations that a number will be mistakenly replaced by a Cyrillic? or vice versa?

**Comment by jozsefk9** [comment]
There could be situations. You would never know which one is which if typing in Cyrillic.

**Comment by firedev** [comment]
I guess it's the same as in latin, if you're often using `O` and `0` or `I` and `l` and `1` and `|`  in the same context then it's might be a problem. Like `IOI` vs `l0l`

**Comment by be5invis** [comment]
@jozsefk9 @firedev 
Latin is extremely common in programming, however Cyrillics rarely occur in source code.

**Comment by firedev** [comment]
Exactly, I wouldn't bother.

**Comment by jozsefk9** [comment]
It's not in the code, definitely, but in the text of web page let's say. I don't know about the way to have the text displayed in different font from the code :)

**Comment by chelovechishko** [comment]
Yep, it's not about code, it's about everyday usage. I, for example, use this font for reading books (it does not matter in a terminal or in a application).

**Comment by robertgzr** [comment]
How would you change it @jozsefk9 @chelovechishko ?

@firedev I don't think this is a question of being bothered. To me that's one of the core reasons why I like Iosevka - it's users can help shape the font to be better for everybody.

**Comment by jozsefk9** [comment]
@robertgzr Well, to me personally, it looks like the simplest way to do it is to leave the capital Z as it is and to change the number three to something similar to Monoid or PT Mono, for example. I could think about more ways if you give me some time, but it would always be some sort of modification of number three character. Capital Z is fine, in my opinion.

**Comment by leiserfg** [comment]
There are more 3 users than Ze users so if one need to be changed is the cirilic one.

**Comment by jozsefk9** [comment]
@leiserfg Maybe but the problem is that Cyrillic Z is as it is, there is no much things you can do about it if you want it to look like Cyrillic Z :) and in the same time to have your fonts still being Iosevka style.

**Comment by jdw1996** [comment]
Perhaps there could be an alternative glyph for `3` that uses a flat top. That way you could have the distinction between the Cyrillic Z and the number three but Iosevka users who don't use Cyrillic could keep using the existing `3` without disruption.

**Comment by jozsefk9** [comment]
@jdw1996 The only problem with that is that I don't know how to do those changes. All I know is to download one of the 12 versions of Iosevka and use it. But I see you have more options than that. I just can't figure out how to do those changes in text editor or operating system.

**Comment by jdw1996** [comment]
@jozsefk9 I'm not sure of an easy way to make such a change given only a font file; if I decide I want a different glyph variant, I rebuild the font myself. I realize that may not be an option for everyone, but that's my process.

**Comment by jozsefk9** [comment]
@jdw1996 How difficult is that process? Any manual for it?

**Comment by be5invis** [comment]
@jozsefk9 Process about what?
Currently there are also many fonts (especially narrow ones, like Pragmata Pro; also PF Din) that the Ze and `3` shares same or very similar shape.

**Comment by jozsefk9** [comment]
@be5invis Process of rebuilding the font with different glyphs.

**Comment by be5invis** [comment]
@jozsefk9 You can follow the instructions in README. Mainly
```bash
... prepare dependencies
make custom-config design="styles you want"
make custom
```

**Comment by jozsefk9** [comment]
@be5invis OK. Thanks. I will have to study about that. Can it be done on Windows machine?

**Comment by be5invis** [comment]
@jozsefk9 I am building the official on Windows (I WORK FOR MS currently)

**Comment by chelovechishko** [comment]
May be make the Cyrillic Ze for Slab like in PT Mono. 
And may be add a glyph variant with a flat top 3 as a number.
Also [wiki](https://en.wikipedia.org/wiki/File:Cyrillic_letter_Ze_-_uppercase_and_lowercase.svg) has the Ze with changing thickness.

**Comment by be5invis** [comment]
@chelovechishko I'd like to choose path II, making an alternative `3` glyph.
`thres.flattop` vs `three.twoarcs`

**Comment by be5invis** [comment]
![image](https://cloud.githubusercontent.com/assets/240091/24700499/ee4b6f8e-1a29-11e7-8213-9a5f6c7ed88c.png)

**Comment by jozsefk9** [comment]
@be5invis if that could be pre-built as an option among the 12 current options that would be fantastic and it would save me lots of time :) Anyway, if not I will have to spend some time and learn how to build fonts by myself. Thanks!

**Comment by be5invis** [comment]
@jozsefk9 
There are already a lot of combinations in the pre-built now :(
Closed as fixed.
