### ISSUE TITLE
Add U+271D ✝ (Latin Cross)

### ISSUE THREAD

**Issue by MithicSpirit** [be5invis/Iosevka#1841]
- The requested character is...
  - [ ] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [x] Symbol
- [ ] Some other monospace/programming fonts supported this character. Provide images below.

------

This symbol is used by [Lean4](https://github.com/leanprover/lean4) to represent variables whose name is irrelevant (no clue why, but the abbreviation for it `\textdied`). Since Iosevka doesn't currently support this character, my editor falls back to using it as an emoji, which looks very out of place, so adding this would be greatly appreciated.

**Comment by Logo121** [comment]
> but the abbreviation for it `\textdied`

This usage of "denoting death/extinction/etc" is usually represented with the dagger (U+2020) `†`.

Do you know if there's a specific reason Lean4 doesn't use that instead (e.g. if `†` is reserved for something else)?  
Do we need to distinguish † and ✝ graphically in this case?

**Comment by MithicSpirit** [comment]
Grepping through the source code for "standard" library for lean ([mathlib4](https://github.com/leanprover-community/mathlib4)) shows that the `†` is occasionally used but only privately (i.e., in internal code that is not user-facing), although I presume users may want to also use it since it seems like relatively common notation for [star rings](https://leanprover-community.github.io/mathlib4_docs/Mathlib/Algebra/Star/Basic.html#Star-monoids-rings-and-modules) (N.B.: not as cool as it sounds).

That said, it's probably fine to make it look relatively similar since it is difficult to encounter both at the same time and it'll usually be easy to distinguish from context. Additionally, lean has much bigger issues than that with using very similar characters in similar contexts (e.g.: `⊥` ([least element](https://en.wikipedia.org/wiki/Greatest_element_and_least_element); U+22A5) and `⟂` (orthogonal; U+27C2) or `‖` (norm; U+2016) and `∥` (parallel; U+2225)), so as far as things go, dagger vs. latin cross isn't really a problem.
