### ISSUE TITLE
Customize Iosevka Aile

### ISSUE THREAD

**Issue by caseyredisatwork** [be5invis/Iosevka#1842]
As a few others have noted (e.g., #1367), capital I and lowercase l are indistinguishable. I understand the reasons why the related issues are closed but would like to use a customized version of the Aile style and don't understand how to accomplish this using a private-build-plans.toml (my attempt attached). I took what I thought was the "definition" of Aile from the bundle-plans.toml, put it in the [customizer](https://typeof.net/Iosevka/customizer) and made the modifications to those two characters and ran the build (which took multple retries to complete due to memory issues). The result looked like "plain old" Iosevka with the character modifications I made instead of looking like the Aile variant.

Did I go about this the wrong way? Any pointers on how I can accomplish what I want (basically, I like the slightly additional spacing between the characters in Aile vs the base, it makes it easier for me at least to read the code I work on -- C#, TS/JS, HTML mostly -- but the I vs l is tough for me because one of the systems I work on, someone accidentally and somewhat randomly named a bunch of tables/columns "BIll*" and it drives me nuts not being able to tell which is which in the code I'm looking at)

Thanks in advance!
[private-build-plans.toml.txt](https://github.com/be5invis/Iosevka/files/12039943/private-build-plans.toml.txt)

**Comment by jmcwilliams403** [comment]
The build plans for Aile are in the normal `build-plans.toml` at [line 675](https://github.com/be5invis/Iosevka/blob/da27c8963091706880ce8e96a5922babc73f02c6/build-plans.toml#L675) downwards. It's basically defined here in the same manner as anyone's own custom build, but non-private.

From here, what you can do is copy and paste the character variants it uses into your custom variant in `private-build-plans.toml` to make your own derivative.

**Comment by caseyredisatwork** [comment]
Thanks, that's basically what I did but in just quickly comparing on the phone now, I'm thinking I got the results I did because I'm missing the snapshot family in the toml I created. Aside from that, is what I attached what you think should result in the same spacing etc as the official Aile with the character specific updates I want?

Jul 16, 2023 10:00:42 AM John McWilliams ***@***.***>:

**Comment by jmcwilliams403** [comment]
I'm pretty sure all Snapshot Family does is include it in a release build.
