### ISSUE TITLE
verda: command not found

### ISSUE THREAD

**Issue by IvayloHrTonev** [be5invis/Iosevka#1848]
Hello,

Suddenly I started getting this build error:
```

 npm run build -- contents::ji2023 && cp dist/ji2023 ~/.fonts/ -r && fc-cache -vf


> iosevka@25.0.1 build
> verda -f verdafile.mjs

/tmp/build-12bbeabe.sh: line 1: verda: command not found
```

My local copy of the repo is up to date.

How I can fix this ?

**Comment by jmcwilliams403** [comment]
Occasionally, whenever Iosevka's external dependencies are updated, the user may have to re-type `npm install` again before proceeding to ensure everything external on _their_ end is up to date as well, not just the local repo itself.

**Comment by IvayloHrTonev** [comment]
@jmcwilliams403 Thank you it works now :)
