### ISSUE TITLE
Request for percentage character with rings

### ISSUE THREAD

**Issue by eproxus** [be5invis/Iosevka#185]
* Your font version: Release
* Your font variant: Any
* Your operating system (name and version): macOS 10.12.4
* Your application using Iosevka: Sublime Text 3, iTerm2 3.0, Chrome 57

It would be nice to have an alternative of the percentage character with rings instead of boxes. The boxes aren't very legible at small sizes, and personally I don't think the blocky style fits with the rest of the font. [Source Code Pro](http://adobe-fonts.github.io/source-code-pro/) is an example with more legible percentage characters.

**Comment by be5invis** [comment]
Moved into #81.
