### ISSUE TITLE
Clock Faces (`U+1F550`..`U+1F567`)

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1850]
- The requested character is...
  - [ ] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [x] Symbol
- [x] Some other monospace/programming fonts supported this character. Provide images below.

------

Could be useful for additional loading icons and GUI stuff etc.

```
🕐 🕑 🕒 🕓 🕔 🕕 🕖 🕗
🕘 🕙 🕚 🕛 🕜 🕝 🕞 🕟
🕠 🕡 🕢 🕣 🕤 🕥 🕦 🕧
```

Fairfax HD:
![image](https://github.com/be5invis/Iosevka/assets/37010132/17f8288a-02ea-48a7-a6dc-4ba8d00b7d8d)

**Comment by aricaldeira** [comment]
Those shapes are simple enough, but I have no idea how to create
new symbols, I tried to understand former commits, but didn’t get
how to do it.

If someone could point out one example of a character create from
scratch, it would help create not only those simple clock faces,
but other characters aswell.

Thanks!

**Comment by Logo121** [comment]
> Those shapes are simple enough, but I have no idea how to create new symbols, I tried to understand former commits, but didn’t get how to do it.
> 
> If someone could point out one example of a character create from scratch, it would help create not only those simple clock faces, but other characters aswell.
> 
> Thanks!

The closest thing you can reference for these is probably `stars.ptl` given how geometrically defined these symbols are

That said most glyphs usually aren't this regular that they can be implemented with loops and such, so maybe check out the math symbols if you want a simpler example?

**Comment by jmcwilliams403** [comment]
Closable?

**Comment by Logo121** [comment]
Just saying... since it's your own issue you can definitely close it yourself when you feel like the issue has been resolved.
