### ISSUE TITLE
Icelandic thorn variants (`U+00DE`, `U+00FE`).

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1854]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

This is an ISO 8859-1 / Latin-1 character, meaning it's present in common default single-byte encoding schemes.

Some fonts may partially or fully serif the thorn independently of the fonts serifedness:

`þbp`

PT Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/7aae566d-15e3-440b-9a60-0296025c0a13)

Courier New:
![image](https://github.com/be5invis/Iosevka/assets/37010132/adea5b6c-c4db-4b39-ac94-1cc5a74f3cdc)

Capital thorn sees variation too. Some fonts draw the bowl higher than normal:

`Þ`

PT Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/ccd5dbb3-5cec-45ca-855f-58cf19520484)

Oxygen Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/b941aad3-3a83-4948-a7c2-2b640c2425af)

Some fonts have a broken bowl like one of Iosevka's P variants:

`PÞ`

Gentium Plus:
![image](https://github.com/be5invis/Iosevka/assets/37010132/5f2d9864-8c93-42a8-97f9-8ac4a82d8653)

**Comment by be5invis** [comment]
Lowercase Thorn could simply follow `p`

**Comment by jmcwilliams403** [comment]
Not exactly. If `p` takes on an earless shape and `b` has a serif on the ascender, then it might look better to select a variant for `þ` that's still in harmony with both. Plus, adding a variant for `þ` might solve the problem with the orphaned latin phi variant selector.

**Comment by jmcwilliams403** [comment]
By the way, these are the last two characters of the ISO 8859-1 character set that makes up `U+0000`..`U+00FF`.

**Comment by be5invis** [comment]
**OK SATISIFY YOU**
I am tired. Really.

**Comment by be5invis** [comment]
For capital, I don't think it worth adding variants... The open variant is NOT seen in any programming fonts. The placement of bowl could be simpliy modified to the raw glyph.
