### ISSUE TITLE
Latin Ext. D: Volapük AE, OE, and UE (`U+A79A`..`U+A79F`)

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1865]
- The requested character is...
  - [x] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [ ] Symbol
- [x] Some other monospace/programming fonts supported this character. Provide images below.

------

These letters are used as typographic substitutes for Ää/Öö/Üü in the Volapük language and also see some use in phonetic transcription of Germanic dialects.

`Ꞛꞛ Ꞝꞝ Ꞟꞟ`

Noto Sans Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/e6532c27-3eb1-49e4-bc19-4353d4d8e376)

Fairfax HD:
![image](https://github.com/be5invis/Iosevka/assets/37010132/dcee166b-0ed3-4111-8b80-5ad6e6b96482)

Everson Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/eb3f0158-afa0-409e-a6f6-578c3db2fc9e)

**Comment by jmcwilliams403** [comment]
Is this closable?

**Comment by Logo121** [comment]
if there are no problems with the implementation, yeah
