### ISSUE TITLE
Website: Etoile Oblique appears much more slanted than Italic in specimen.

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1875]
Etoile Italic:
![image](https://github.com/be5invis/Iosevka/assets/37010132/46708391-8bb8-436e-bbe6-72e3744b730a)
Etoile Oblique:
![image](https://github.com/be5invis/Iosevka/assets/37010132/5c538f79-5e66-4c46-b0c2-af7e041ff860)

Ctrl+F5 doesn't fix it.
This is only a bug on the website. The actual released font itself is fine on my machine.

Offline Etoile Italic ttf/ttc:
![image](https://github.com/be5invis/Iosevka/assets/37010132/4b8632bc-b339-49f7-a45e-a8a122e2d354)
Offline Etoile Oblique ttf/ttc:
![image](https://github.com/be5invis/Iosevka/assets/37010132/0fadffec-2d43-44ca-a234-16e4d0ebbe4f)
(The only difference in these two screenshots is how I imperfectly hand-cropped the images each time)

**Comment by jmcwilliams403** [comment]
I also just noticed that the upright vertical bar variation selector is fighting against it but can't overcome it:
![image](https://github.com/be5invis/Iosevka/assets/37010132/0cf5f598-d9fd-4842-b8a9-033205175fa0)

**Comment by Logo121** [comment]
Can confirm, looks like `font-style: oblique` is applied on top of the Oblique-only font, making it extra slanted. For other styles (Sans Oblique etc), `font-style: normal` is applied to override the property but that is missing for Etoile.

**Comment by be5invis** [comment]
Fixed.
