### ISSUE TITLE
`<>`  empty diamond tag for C-Likes, for Java.

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1878]
- [x] A programming language requires this ligation. Provide the information below.
- [x] This ligation is implemented in other programming fonts. Provide samples below.

------

Java is a C-based programming language that uses `Object<Cast>` format for generics, as well as empty angle brackets in e.g.
`List<String> list = new ArrayList<>();`

Fira Code:
![image](https://github.com/be5invis/Iosevka/assets/37010132/9186e40d-27d7-400a-a85a-6975531577ae)

**Comment by jmcwilliams403** [comment]
it should be `'ltgt-diamond-tag',` and also you forgot the comma.

**Comment by be5invis** [comment]
`ltgt-diamond-tag` is only for JSX' "fragment" tags (JSX use `<> </>` for fragment). For operator we use `ltgt-diamond`.
