### ISSUE TITLE
mathematical sans-serif small m (U+1D5C6) is too wide in iosevka-term

### ISSUE THREAD

**Issue by globau** [be5invis/Iosevka#188]
* iosevka-term-1.12.1
* MacOS 10.12.4
* iTerm2 3.0.15

in iosevka-term the "mathematical sans-serif small m (U+1D5C6)" is wider than the monospace width.

math 'm' with a normal 'm':
<img width="73" alt="screenshot 2017-04-08 14 10 01" src="https://cloud.githubusercontent.com/assets/872825/24826304/2d620fc4-1c65-11e7-92a1-6d650747a9bb.png">

cursor over math 'm':
<img width="77" alt="screenshot 2017-04-08 14 10 12" src="https://cloud.githubusercontent.com/assets/872825/24826305/3671fa34-1c65-11e7-9b9f-17b82eaa0199.png">

cursor over normal 'm':
<img width="77" alt="screenshot 2017-04-08 14 10 17" src="https://cloud.githubusercontent.com/assets/872825/24826307/3ad384e4-1c65-11e7-9857-210c9f74f252.png">

**Comment by be5invis** [comment]
Math glyphs are not supported now.

发自我的 iPhone

在 2017年4月8日，14:13，byron jones <notifications@github.com<mailto:notifications@github.com>> 写道：


  *   iosevka-term-1.12.1
  *   MacOS 10.12.4
  *   iTerm2 3.0.15

in iosevka-term the "mathematical sans-serif small m (U+1D5C6)" is wider than the monospace width.

math 'm' with a normal 'm':
[screenshot 2017-04-08 14 10 01]<https://cloud.githubusercontent.com/assets/872825/24826304/2d620fc4-1c65-11e7-92a1-6d650747a9bb.png>

cursor over math 'm':
[screenshot 2017-04-08 14 10 12]<https://cloud.githubusercontent.com/assets/872825/24826305/3671fa34-1c65-11e7-9b9f-17b82eaa0199.png>

cursor over normal 'm':
[screenshot 2017-04-08 14 10 17]<https://cloud.githubusercontent.com/assets/872825/24826307/3ad384e4-1c65-11e7-9857-210c9f74f252.png>

**Comment by be5invis** [comment]
Moved into #81. Closed.

**Comment by globau** [comment]
thanks - sorry i didn't realise it wasn't a supported symbol.
