### ISSUE TITLE
Sampler specimen improvement

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1885]
Instead of this:
![image](https://github.com/be5invis/Iosevka/assets/37010132/e01c9b99-902c-4152-a747-cfcef1e27bba)
maybe consider this:
![image](https://github.com/be5invis/Iosevka/assets/37010132/6c91a3f0-03f3-46fa-8125-3d04e1705479)
Because then the Greek section would match up with the Cyrillic section, and the extended Latin section would be in order of appearance of variants.
All this does is move the position of the space character (` `) and thorn (`þ`)

**Comment by be5invis** [comment]
Next version will use `¢ ſß ΓΛΔ αδιλμξ`.
Resolve as fixed.
