### ISSUE TITLE
Rendering of equal sign is blurred

### ISSUE THREAD

**Issue by jlanzarotta** [be5invis/Iosevka#1886]
The issue I am observing is odd rendering of 14 point equal sign characters.  As you can see from these screenshots, the 13 and 15 point size looks fairly good, while the 14 point looks blurred..  Any idea on how to resolve this?  Thanks.

13 Point
![13_point](https://github.com/be5invis/Iosevka/assets/5437686/137de890-1c20-4ce0-b232-72ee6faedad4)

14 Point
![14_point](https://github.com/be5invis/Iosevka/assets/5437686/dfe15b1e-3610-41ea-85f0-9c933ef8c534)

15 Point
![15_point](https://github.com/be5invis/Iosevka/assets/5437686/4f6c8529-5cc6-48cc-b626-1cd45be96108)

---

* Your font version: v25.1.1
* Your font variant: Default
* Your operating system:  Windows 10 Version 10.0.19045 Build 19045
* Your application using Iosevka: IntelliJ version 2023.2, Build #IC-232.8660.185, built on July 26, 2023

**Comment by be5invis** [comment]
_ttfautohint_ issue (it doesn't support symbols well).
Not something I can fix.
Resolve as external.
