### ISSUE TITLE
Script g (`U+0261`) should have the same "script cut" ear as latin alpha (`U+0251`)

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1887]
This would also help more easily distinguish `g` from script g under the default configuration.

Unicode block PDF:
![image](https://github.com/be5invis/Iosevka/assets/37010132/b30bbd85-4f19-4240-8fd7-f8ac307139c3)

**Comment by be5invis** [comment]
Then we will remove the variants for top-right corner (as we are forcing using that corner)
