### ISSUE TITLE
According to the Unicode charts, Small schwa (`ə`) can have a serif too.

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1892]
It's shown here in the Cyrillic block:
![image](https://github.com/be5invis/Iosevka/assets/37010132/f5f77c8d-8939-4a4e-853f-11cc49d0600f)
However these fonts serif the Latin version (`ə`) too:
![image](https://github.com/be5invis/Iosevka/assets/37010132/2e6c78a1-7f8f-4414-901a-9048516034f8)
![image](https://github.com/be5invis/Iosevka/assets/37010132/8c07bd1a-e5d1-45b2-85bc-5b9e728c4ded)
![image](https://github.com/be5invis/Iosevka/assets/37010132/35177406-200e-41ed-bf42-c526be9c403a)

However, the unrelated "turned e" character (`U+01DD`) should not be unified with schwa when serifed, as it is literally a turned ascii `e`:
![image](https://github.com/be5invis/Iosevka/assets/37010132/bb60a070-90e4-4ab9-b7ad-465dfdf02708)

**Comment by jmcwilliams403** [comment]
small schwa would actually follow the serifs of lowercase `c`.

**Comment by be5invis** [comment]
FIXED
