### ISSUE TITLE
Three Extended Cyrillic slab/variant issues

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1896]
Cyrillic omega (`U+0460`..`U+0461`) has been missing its top-right serif:
![image](https://github.com/be5invis/Iosevka/assets/37010132/ffc208f0-f9d8-43bb-9e47-7d862b664daa)
Capital Komi Sje (`U+050C`) should follow the serifs of capital `C`, not lowercase `c`:
![image](https://github.com/be5invis/Iosevka/assets/37010132/4093173c-3f45-414a-b204-010a48e4c8dd)
The variants of `Z`/`z` with a strikethrough should not be available to Cyrillic Zemlya (`U+A640`..`U+A641`) so that it's not confused with Dzelo (`U+A642`..`U+A643`):
![image](https://github.com/be5invis/Iosevka/assets/37010132/7e660916-9a7a-4f82-8570-7ee2bc06841a)

**Comment by be5invis** [comment]
> Cyrillic omega (U+0460..U+0461) has been missing its top-right serif

This is by design (Brill)
![image](https://github.com/be5invis/Iosevka/assets/240091/0ba89cb8-118b-4a3c-aead-0ee644458672)

**Comment by be5invis** [comment]
> The variants of Z/z with a strikethrough should not be available to Cyrillic Zemlya (U+A640..U+A641) so that it's not confused with Dzelo (U+A642..U+A643):

I follow `Z`/`z`'s converntion that allows overstrikes. For `Z`/`z` we also have `Ƶ`/`ƶ` in parallel.
