### ISSUE TITLE
Cyrillic Dche (`U+052C`..`U+052D`)

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1897]
- The requested characters are ...
  - [ ] Latin
  - [x] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [ ] Diacritic / Mark
  - [ ] Symbol
- The requested characters are used in ...
  - [x] The alphabet / character set of a natural language.
  - [ ] The alphabet / character set of a constructed language.
  - [ ] The alphabet / character set of a transliteration or notation system.
  - [ ] Mathematical or other professional use in documents.
  - [ ] The symbol set of a programming language.
  - [ ] The symbol set of a command-line program.
- [x] Some other monospace/programming fonts supported this character. Provide images below.

------

This is the last of the letters associated with the Komi language in the Cyrillic Supplement block.

`Ԭԭ`

Consolas:
![image](https://github.com/be5invis/Iosevka/assets/37010132/aaae04ce-a273-4272-bcf8-3736ff54abf3)

Courier New:
![image](https://github.com/be5invis/Iosevka/assets/37010132/9dbe5c60-d4ec-498d-9410-e5f3368bc7d1)

Noto Sans Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/a746372f-14ea-439e-9666-021df4bf0ab4)

Julia Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/503d7f1d-3fc3-42ac-88fd-f8fc6663fa09)

Everson Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/ccb77e8b-bb3c-46e3-b35a-3473ad4867b9)

Fairfax HD:
![image](https://github.com/be5invis/Iosevka/assets/37010132/b24e2ec1-efe5-4802-bf5c-e00fcfe0420b)

Italic form:
![image](https://github.com/be5invis/Iosevka/assets/37010132/0db3c3f3-a359-4ca4-8ee8-192e7a0e0286)

**Comment by Logo121** [comment]
Seems to break below regular:
![image](https://github.com/be5invis/Iosevka/assets/21302803/a170a3e6-bc20-42e7-b7be-823086b331cf)

**Comment by be5invis** [comment]
@Logo121 fixed
