### ISSUE TITLE
Cyrillic Abkhasian Che (`U+04BC`..`U+04BF`) with bottom serif following `C`/`c`

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1898]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

This letter's resemblance to lowercase Latin `e` is entirely coincidental. It's more helpful to think of this letter as a standalone letter of the Abkhaz language with a retroactive relation to both Latin `e` and Cyrillic Es.

`ҼҽCc`

Cambria:
![image](https://github.com/be5invis/Iosevka/assets/37010132/aa117187-b096-4ad3-b1fd-ba42cd9dd7b6)

Liberation Serif:
![image](https://github.com/be5invis/Iosevka/assets/37010132/e28f1598-63ae-4513-9183-b93f1a9ae981)

Tinos:
![image](https://github.com/be5invis/Iosevka/assets/37010132/6e3135c4-bae0-4ccb-a8d0-a61cf8db9bc5)

**Comment by be5invis** [comment]
@dscorbett Is this letter really come from *Es* rather than *E*?

**Comment by jmcwilliams403** [comment]
It's neither. It just resembles both.

**Comment by dscorbett** [comment]
I assume it comes from a cursive [Latin-script Abkhaz che](https://commons.wikimedia.org/wiki/File:Abkhaz_latin_alpabet_from_1930_ABC_book.png) (not encoded, but [proposed as LATIN CAPITAL/SMALL LETTER CAUCASIAN CHE](https://unicode.org/L2/L2012/12045-soviet-latin.pdf)) which looks like it was derived from Cyrillic che ⟨ч⟩. Regardless, it is its own letter unrelated to ⟨с⟩ or ⟨е⟩, except by convergent evolution.

**Comment by jmcwilliams403** [comment]
> Regardless, it is its own letter unrelated to ⟨с⟩ or ⟨е⟩, except by convergent evolution.

Exactly what I'm trying to say.
