### ISSUE TITLE
Straight «Guillemets» (`U+00AB`, `U+00BB`, `U+2039`, `U+203A`)

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1899]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

Both the current curly style and a straight style should be available. I like both.

Below are a list of fonts for comparison. For any of the ones with a tapering stroke width, they may still use the curly style as a closest analogue. For ones with a constant stroke width, a straight style would make more sense.

`«»‹›`

Andale:
![image](https://github.com/be5invis/Iosevka/assets/37010132/4c292a22-0ab5-467c-ad5c-dbf0eecf31d6)

Anonymous Pro:
![image](https://github.com/be5invis/Iosevka/assets/37010132/25f73523-3ff3-4b7d-9a8c-306f332e7234)

Consolas:
![image](https://github.com/be5invis/Iosevka/assets/37010132/c35790ce-851e-4bde-8383-f7fa4d49621b)

Courier Prime:
![image](https://github.com/be5invis/Iosevka/assets/37010132/928a4f46-0b3a-4830-ab0b-3d261bf29d0d)

Cascida Code:
![image](https://github.com/be5invis/Iosevka/assets/37010132/b81b8120-9a1e-4bd0-b29c-03dee8964c63)

DejaVu Sans Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/f9390815-633f-40fb-86f3-34162f3f3b91)

Liberation Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/29308414-b156-48c7-8995-1fd3129d6d61)

Fira Code:
![image](https://github.com/be5invis/Iosevka/assets/37010132/f69c5db8-d4cf-488e-8a86-0f3acc1ad3fc)

Monaco:
![image](https://github.com/be5invis/Iosevka/assets/37010132/6015194a-477b-4a7e-8d53-479cd975c6b9)

Fixed:
![image](https://github.com/be5invis/Iosevka/assets/37010132/cdd5e8b2-6c26-475c-ae29-26d959348e60)

Pragmata Pro:
![image](https://github.com/be5invis/Iosevka/assets/37010132/38f606f3-88b3-437a-bf26-620daf090414)
![image](https://github.com/be5invis/Iosevka/assets/37010132/24ea39c4-d0f9-498a-ac5e-dcf4b15f4844)

Envy Code R:
![image](https://github.com/be5invis/Iosevka/assets/37010132/1765494e-144a-4c3e-876d-767b0048e3ff)

Ubuntu Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/4c386814-f6b2-4d5a-92fb-e586932a5f43)

Source Code Pro:
![image](https://github.com/be5invis/Iosevka/assets/37010132/5ed8724c-8866-46d8-bde1-32be6191f7fc)

Jetbrains Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/41a9d180-684b-41b7-9b19-81f15dd6319d)

IBM Plex Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/1b7acb61-3ad6-4f53-9ef5-04460c79f892)

PT Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/dbcf021e-3c11-4551-9bbb-af7a63605b19)

Recursive Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/63f1013a-39c4-47c0-87f1-5c01af58eb00)

Input Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/528b4791-61a8-43d2-aca1-b6174765f8a0)

Inconsolata:
![image](https://github.com/be5invis/Iosevka/assets/37010132/8c894310-7db4-42d3-bd6f-b0a84394195a)

Noto Sans Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/e8e6c9b2-2833-4b1a-937a-d37caa13497c)

Roboto Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/19d11633-bcfb-4517-bc20-bdaaec2e63cc)

Julia Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/471d2547-6f11-4c3b-93fd-69e1b4d60dc9)

Everson Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/c94275af-6ebe-42de-8ba2-326b62b32647)

Fairfax HD:
![image](https://github.com/be5invis/Iosevka/assets/37010132/d8fac826-a576-416b-8e56-26f9faced2a1)

**Comment by be5invis** [comment]
Guillemets are the earliest batch of symbols I made. Maybe worth adding...

**Comment by be5invis** [comment]
I will only distinguish the straightness. The tips' and angle shape will not be distinguished.

**Comment by mfocko** [comment]
Did you intend to use straight guillemets for the slab and curly for sans? :thinking: at least the custom-build says so
