### ISSUE TITLE
Characters do not have the same width

### ISSUE THREAD

**Issue by eiszfuchs** [be5invis/Iosevka#19]
It might be intentional and I missed that completely, but I was trying out some colour schemes in my terminal and noticed that my text layout was off for some lines:

![](http://i.imgur.com/lvoZ7In.png)

I noticed a similar effect with programs like `top`.
For comparison, this is what it looked like when I still used *Input* for my terminal font:

![](http://i.imgur.com/9tniS5J.png)

ConEmu has an option to "fix" that, actually, but this makes Iosevka look even more compressed.

![](http://i.imgur.com/mdlj0E6.png)

This doesn't look quite nice.
Again, it might be intentional, I just wanted to be sure about that, because Iosevka was supposed to be a monospaced font, wasn't it?

---

PS Please don't ever change the `ß` character. I'm in love with it!

**Comment by be5invis** [comment]
Could you please copy the comsole output for me? I have to figure out what character is missing.

**Comment by be5invis** [comment]
@lemzwerg
Is it hinting related? Maybe ttfautohint can include a feature which preserves monospaceness.

**Comment by lemzwerg** [comment]
ttfautohint doesn't hint along the horizontal axis; it doesn't touch the horizontal metrics.

**Comment by be5invis** [comment]
@lemzwerg yeah, i know, therefore @eiszfuchs 's situation looks weird.

**Comment by lemzwerg** [comment]
Maybe a comparison of the hinted vs unhinted version using `ttx` gives more information.  However, I don't have time to do that.

**Comment by be5invis** [comment]
@lemzwerg I need more information from @eiszfuchs .

**Comment by eiszfuchs** [comment]
I'm on the go, sorry! Will provide you with more information as I sit in front of my desk again! 🙊
Am 19.09.2015 09:45 schrieb Belleve Invis <notifications@github.com>:@lemzwerg I need more information from @eiszfuchs .

**Comment by be5invis** [comment]
@eiszfuchs Please provide me more information about the problem you encountered. It is important for me to fix Iosevka.

**Comment by eiszfuchs** [comment]
Sorry it took so long!
I'm using cmder[1] v1.1.14, which is a package that includes ConEmu[2], the nicest terminal emulator you could possibly use in Windows 7 and 8.

I tried different font sizes this time, and as you can see, the problem actually *does* depend on it.

Font size "14"
![](http://i.imgur.com/qjBeg7c.png)

Font size "16" (that's what I'm used to)
![](http://i.imgur.com/25gOZd4.png)

Font size "18"
![](http://i.imgur.com/OkVhrMJ.png)

All sizes larger than 18 seem to render just fine. 12 is an issue again, 11 renders fine (but is almost unreadable).

I've been using this script to generate the output: https://gist.github.com/eiszfuchs/587915d7d1a9372f625b
I'd post a `.txt` file, but GitHub replaces my escape characters.

---
[1] https://github.com/cmderdev/cmder/
[2] https://github.com/Maximus5/ConEmu

**Comment by be5invis** [comment]
@eiszfuchs Did you tried using the default Windows console instead of conemu? The method of adding new fonts is described [here](http://www.techrepublic.com/blog/windows-and-office/quick-tip-add-fonts-to-the-command-prompt/).

**Comment by be5invis** [comment]
I cannot reproduce your problem.

![](http://ww4.sinaimg.cn/large/798f7769gw1ewdmbtklxzj20p80el780.jpg)

![](http://ww1.sinaimg.cn/large/798f7769gw1ewdmc255v7j20zj0p9n6l.jpg)

**Comment by eiszfuchs** [comment]
I'm not using the default `cmd.exe` for a reason. I'll check out ConsoleZ.

**Comment by be5invis** [comment]
I found what happened: The actual text size being displayed is actually 15ppem instead of 16 due to some weird unit conversion (maybe related to some metrics metadata in the OS/2 table). And Conemu miscalculated the width of spaces under 15ppem, makes it a bit shorter.

The newer version of Conemu (MUCH newer than the version included in Cmder v1.1.4) includes an option to use actual text size. You can check out the settings in the figure 3.

![](http://ww4.sinaimg.cn/large/798f7769gw1ewdmn2hbgnj20xg0q3jwx.jpg)
*Figure 1. 15ppem display*

![](http://ww4.sinaimg.cn/large/798f7769gw1ewdmnfy2g5j20xg0q3wk7.jpg)
*Figure 2. 16ppem display*

![](http://ww4.sinaimg.cn/large/798f7769gw1ewdmnkrxsxj20zj0p9n78.jpg)
*Figure 3. 16ppem settings*

**Comment by Maximus5** [comment]
ConEmu creates fonts using [CreateFont](https://msdn.microsoft.com/en-us/library/dd183499.aspx) function.

Old versions were using only positive nHeight values which let users to specify cell height in pixels.

New versions have an option, and by default they pass negative nHeight to use "device units" and character heights.

ConEmu does not "calculate" cell widths, it queries widths from WinApi. And several fonts has problems with "positive" heights. Consolas is one of them. In fact, it's not a ConEmu problem, but the behavior of Windows fonts API.

**Comment by be5invis** [comment]
@Maximus5 The width of spaces under 15ppem is one pixel narrower than other glyphs under some odd ppems like 15ppem. Maybe related to rounding?

**Comment by Maximus5** [comment]
May be. But WinApi uses integer values for font dimensions. ConEmu do not do rounding at all.

**Comment by be5invis** [comment]
@Maximus5 Does `GetTextExtendPoint` returns different horizontal width for `" "` and `"a"` when the current font is Iosevka and the size is 15ppem (-15)?
