### ISSUE TITLE
{Left|Right|Left Right} Arrow through small circle (`U+21F4`, `U+2B30`, `U+2948`)

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1900]
- The requested characters are ...
  - [ ] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [ ] Diacritic / Mark
  - [x] Symbol
- The requested characters are used in ...
  - [ ] The alphabet / character set of a natural language.
  - [ ] The alphabet / character set of a constructed language.
  - [ ] The alphabet / character set of a transliteration or notation system.
  - [x] Mathematical or other professional use in documents.
  - [x] The symbol set of a programming language.
  - [ ] The symbol set of a command-line program.
- [x] Some other monospace/programming fonts supported this character. Provide images below.

------

These arrows are used for denoting execution of a partially defined function. They may also be used in languages like Swift which allow overloading arbitrary Unicode math operators.

`A⇴B`, `A⬰B`, `A⥈B`

Noto Sans Math:
![image](https://github.com/be5invis/Iosevka/assets/37010132/9a68d8a7-5814-4d90-8b79-c7bf335b7085)

Deja Vu Sans Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/73a7987a-e340-48a9-b0ad-64601b8558bc)

Julia Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/71e20994-7952-4d97-9855-135399617a84)

Everson Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/0bf1e565-ade5-4345-9ad2-7b14f1386686)

Fairfax HD:
![image](https://github.com/be5invis/Iosevka/assets/37010132/b09fa6dd-31f8-4bf5-977c-2a4ddc431e48)

**Comment by cormullion** [comment]
(off topic - @jmcwilliams403 Not sure why you're seeing U+FFFD for JuliaMono here: 🤔

<img width="686" alt="Screenshot 2023-08-09 at 18 43 52" src="https://github.com/be5invis/Iosevka/assets/52289/71673356-1b06-4f07-8989-bd6f12fa7f84">

What app are you using to generate your samples?

Is Noto Sans Math monospaced/programming on your system?

)

**Comment by jmcwilliams403** [comment]
I saw the glyph in JuliaMono didn't match the others and mistakenly thought "yeah this is probably using fallback" even though mismatching unicode glyphs is characteristic for Julia and I should have known better.

**Comment by jmcwilliams403** [comment]
Noto Sans Math isn't programming but it's an example of a font where all three are present and match each other so I showed it first as an example. Plus, Noto Sans Mono exists, so it's the closest thing to that.
