### ISSUE TITLE
Separate Eszet (`ß`) middle(-xh)/double(-xh) serifed variants

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1904]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

The middle/double serif Eszet (`ß`) variants that are currently used in stylistic sets don't match their respective middle/double _non‑xh_ serifed long S (`ſ`). I believe both the xh and non-xh serif variants should be present for parity with long s variants, per #1881.

`ss16` currently:
![image](https://github.com/be5invis/Iosevka/assets/37010132/db0973a8-1247-4def-855f-332cc50bba12)

Original PT Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/d984f957-9914-44f3-a1e6-4635c3d62562)

**Comment by be5invis** [comment]
Non-XH height for traditional bodies doesn't make sense. Only non-traditional will have them.
