### ISSUE TITLE
Duplicate variants of t with retroflex hook (`U+0288`, `U+1DF09`) and with curl (`U+0236`)

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1909]
Distinguishing the types of tail on each of these when the tail gets replaced with an attachment anyway makes these variants either identical or nearly-identical.
![image](https://github.com/be5invis/Iosevka/assets/37010132/755a9500-49b1-42b1-8e8b-4bdd3c23a61a)
![image](https://github.com/be5invis/Iosevka/assets/37010132/7c6d7ccc-7953-44c6-9135-e9f9b543bada)
![image](https://github.com/be5invis/Iosevka/assets/37010132/bc2e092a-fb8d-4b9f-8add-30b22a5b6aed)

**Comment by be5invis** [comment]
Their X position is different (because in `t`, the position of the vertical bar is different), so keeping these variants is intentional.
Resolve as by design.

**Comment by be5invis** [comment]
Hmm only U+0236 distinguishes X position, for retroflex hooks they are identical.
