### ISSUE TITLE
Request for fullwidth improvements

### ISSUE THREAD

**Issue by wdhwg001** [be5invis/Iosevka#191]
As discussed in #121 , Iosevka currently doesn't contain any fullwidth punctuation glyphs. Therefore, in released version except `Term`, Iosevka simply use halfwidth glyphs in fullwidth characters.

However, it might not be a proper idea, because fullwidth punctuation characters are meant to be together with fullwidth latin characters and ideographs. Which means, some of them should be different with halfwidth punctuation marks.

* For brackets, hyphens, underlines and other marks like `＆`, they should be widen and centered.
   e.g. `（Ｐ＆Ｇ＿Ａｋａ＿保洁）` from here we can see in 12px, `Ｐ` and `Ｇ` are about 12px in width, `洁` is about 23px in width, but `（` is only about 10px in width. Therefore, the FW brackets might need to en-widen so that they might not look that narrow.
   (IMO, FW brackets should en-widen more in CC version, even though they will be slightly wider than FW latin characters.)

* For comma, semicolon, period and so on, they should be bigger or centered.
   e.g. `Ｂ．Ｂ．Ｑ，Ｙｅａｈ！` and `B.B.Q, Yeah!`, they should be centered, but in fact it could be complicated. In Chinese standard, most punctuation should be located on the right-bottom 1/4 of the FW space. So my suggestion is either we just ignore the standard as M$ does, or we put them at about 35% - 40% of the width space in CC version.

And at least, fullwidth punctuation should look different with halfwidth punctuation followed by a halfwidth space.

**Comment by be5invis** [comment]
FWID glyphs are now REMOVED by default, since Inziu is no longer maintained.
Closing this as invalid.
