### ISSUE TITLE
"Tall" Te, Yat and Back Yer

### ISSUE THREAD

**Issue by Logo121** [be5invis/Iosevka#1911]
- The requested characters are ...
  - [ ] Latin
  - [x] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [ ] Diacritic / Mark
  - [ ] Symbol
- The requested characters are used in ...
  - [x] The alphabet / character set of a natural language.
  - [ ] The alphabet / character set of a constructed language.
  - [ ] The alphabet / character set of a transliteration or notation system.
  - [ ] Mathematical or other professional use in documents.
  - [ ] The symbol set of a programming language.
  - [ ] The symbol set of a command-line program.
- [x] Some other monospace/programming fonts supported this character. Provide images below.

------

These three glyphs (`ᲄᲇᲆ`) are "tall" variants of existing Cyrillic characters (`тѣъ`), but have the crossbar extend above the preceding letter, e.g. (from [proposal](https://www.unicode.org/wg2/docs/n4607.pdf)): ![image](https://github.com/be5invis/Iosevka/assets/21302803/5be99373-d773-4ce5-8771-ba3115ce5707)

These are (more or less) faithfully recreated in the Slavicist fonts I've been referencing:
![image](https://github.com/be5invis/Iosevka/assets/21302803/c6e1871e-3396-4d0f-ba73-7069012ca5ca)
but are (more often than not) ignored in monospace fonts, the exception being FairfaxHD with Tall Te:
![image](https://github.com/be5invis/Iosevka/assets/21302803/2c88f71d-7508-4cb8-9bf2-715231e3d44f)

Notes:
* All of these are technically lowercase (as they appear in non-initial position), hence the bowls aligning with the lowercase glyph.
* The squiggly bar (and/or the slant) of Tall Te is due to the Ustav-style handwriting glyph being "Romanized" directly (see: #1833) to the Unicode standard. I believe RomanCyrillic's version is more appropriate.
* Given how Noto Sans (proportional) also has the crossbar of Tall Te poke to the left of its bounding box but Mono doesn't, I suppose it's just another case of Noto ignoring all width-based variations (ref: #1517)

**Comment by jmcwilliams403** [comment]
Tall Te looks like it can be created by taking the Latin turned `L` glyph and making it follow the serifs of capital `T`.

**Comment by be5invis** [comment]
@dscorbett Should `CYRILLIC SMALL LETTER TALL HARD SIGN` and `CYRILLIC SMALL LETTER TALL YAT` extend to above the ascender?

**Comment by Logo121** [comment]
imo they don't need to be, Tall Yat does in some cases mostly so that the crossbar can properly go above the previous letter

**Comment by Logo121** [comment]
ok
![image](https://github.com/be5invis/Iosevka/assets/21302803/e55b3ed5-2126-46cf-86ca-92da605875da)

`CYRILLIC SMALL LETTER TALL HARD SIGN` should have a small bowl tho (as you did for yat)
