### ISSUE TITLE
Ligation request: >>, ++, <>, ><, {-, {-#, #-}, -} for Haskell

### ISSUE THREAD

**Issue by fmthoma** [be5invis/Iosevka#192]
These are used quite often in Haskell:
* `>>`, `<<` – This is similar to `>>=` and could be two `>`s pushed together (like `\gg`, `\ll` in [LaTeX](https://www.rpi.edu/dept/arc/training/latex/LaTeX_symbols.pdf), or the `>>` in your `>>=` ligation).
* `++` – List concatenation. Canonically typeset as two pushed-together `+` symbols like [here](https://tex.stackexchange.com/questions/272752/concatenation-of-strings-symbols).
* `<>` – For monoidal append. In papers usually represented as the `\diamond` LaTeX symbol.
* `><` – Concatenation of `Data.Sequence`, mnemonically `|>` + `<|`. Often represented by the `\bowtie` symbol. (I'm not so sure about this one though. The `\bowtie` could as well be a ligation for `|><|`, which is not so often – if ever – used.)
* `{-` `-}`, `{-#` `#-}` – Haskell multi-line comment and language-pragma syntax, respectively. There is no »canonical« ligature for these like for the symbols above, but I have the feeling there may be some beautiful way to ligate them :-)

And by the way: Thank you so much for this font! I particularly enjoy the Expanded variant!

**Comment by be5invis** [comment]
- `++`, `>>` and `<<` are already in. Use the `XHS0` tag.
- Others: Moved to #56.

**Comment by fmthoma** [comment]
Right, sorry, I didn't see these ligatures in the overview, and didn't look closely enough to recognize them in Atom (I did use the `XHS0` tag).
Any chance to get the `++`s not just connected, but also a bit closer to each other? (Would this break the infinite `+++…` ligations? I see that e.g. `>>>` currently ligates as one groups of `>>>` and one extra `>`.)
