### ISSUE TITLE
Italic lowercase Komi Tje (`U+050F`)

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1920]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

`ԏ`

Liberation Sans Regular:
![image](https://github.com/be5invis/Iosevka/assets/37010132/323b3cd5-5438-4fc5-bf87-76dc75a29946)
Liberation Sans Italic:
![image](https://github.com/be5invis/Iosevka/assets/37010132/ead9acbf-932c-42d1-b51d-4b3091ab04c6)
Arimo Regular:
![image](https://github.com/be5invis/Iosevka/assets/37010132/97151e64-1d47-48f8-a7ea-6e965121f8bb)
Arimo Italic:
![image](https://github.com/be5invis/Iosevka/assets/37010132/6c88a2f0-b032-42f4-b4ea-90d82d956b28)

**Comment by Logo121** [comment]
oh yeah, I've seen this form from the Komi book list, didn't know there are actual fonts supporting that tho

will do something about it
