### ISSUE TITLE
Diameter Sign (`U+2300`)

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1923]
- The requested characters are ...
  - [ ] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [ ] Diacritic / Mark
  - [x] Symbol
- The requested characters are used in ...
  - [ ] The alphabet / character set of a natural language.
  - [ ] The alphabet / character set of a constructed language.
  - [ ] The alphabet / character set of a transliteration or notation system.
  - [x] Mathematical or other professional use in documents.
  - [ ] The symbol set of a programming language. For the languages that support using arbitrary symbols, please provide usages in well-known components or libraries.
  - [ ] The symbol set of a command-line program.
- [x] Some other monospace/programming fonts supported this character. Provide images below.

------

This symbol is typable on Unix/Linux systems via XCompose using the key sequence <kbd>⎄ Compose</kbd> <kbd>d</kbd> <kbd>i</kbd> : "⌀"

It is also the only non-APL character in the Miscellaneous Technical block with a defined compose sequence in the standard XOrg Compose file.

This character is used in specification of optical lenses. I've probably thrown it around a couple of times when making raycasting engines due to it having an easy compose sequence and also it being indirectly related to the idea of a virtual camera.

`⌀`

DejaVu Sans Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/f5d4c4d8-c62f-4861-b83a-640fffb8500d)

Julia Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/a402c518-3dcb-462a-9140-1dd6d4c0baeb)

Everson Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/1a811cc0-178d-4085-8084-3ae6695e4295)

Fairfax HD:
![image](https://github.com/be5invis/Iosevka/assets/37010132/3f75887e-3904-4ed6-90a2-d3c7e32458c0)

This character may also be narrow by default, like the nearby HOUSE (`U+2302`).

**Comment by Logo121** [comment]
related: #1822

just to add that, if distinction between this and the empty set symbol is needed, this character is sometimes aligned with the baseline, like FairfaxHD does
