### ISSUE TITLE
Cyrillic lower Em (`м`) with left tail

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1932]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [ ] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

The fact that Consolas supports it means that this variant would go into immediate use for `ss03`.

`Мм`

Consolas:
![image](https://github.com/be5invis/Iosevka/assets/37010132/b90db1ce-3995-4487-a789-ee30834d0cc5)

Consolas Italic:
![image](https://github.com/be5invis/Iosevka/assets/37010132/6d4733fb-5f91-40ca-ac96-948a0f0589af)

DejaVu Serif:
![image](https://github.com/be5invis/Iosevka/assets/37010132/4b292a20-a5a6-4a3e-b38a-cf00fc38c6ca)

DejaVu Serif Italic:
![image](https://github.com/be5invis/Iosevka/assets/37010132/e2189443-e612-4a07-b0fa-e95af0c24aec)

Liberation Serif:
![image](https://github.com/be5invis/Iosevka/assets/37010132/ac2447f3-58fe-40d7-bc2c-e666ae80940c)

Liberation Serif Italic:
![image](https://github.com/be5invis/Iosevka/assets/37010132/b49cf906-01fe-4779-b9da-6bede6d61a4a)

**Comment by be5invis** [comment]
Only one monospace font have this (yes I know it is one of the SSes).

**Comment by chelovechishko** [comment]
Why to do it from only one side? In cursive every leg (intermediate included) slanted(?).

**Comment by jmcwilliams403** [comment]
I'm going to close this if only one SS isn't enough justification.
