### ISSUE TITLE
Cyrillic lower El (`л`) with rounded top-left corner

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1933]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [ ] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

The fact that Consolas supports it means that this variant would go into immediate use for `ss03`.

`Лл`

Consolas:
![image](https://github.com/be5invis/Iosevka/assets/37010132/01b32d46-bce9-44fc-b966-134da0e9544f)

Consolas Italic:
![image](https://github.com/be5invis/Iosevka/assets/37010132/4f731902-39b8-4bd6-a5be-a4045ce9ba6d)

DejaVu Serif:
![image](https://github.com/be5invis/Iosevka/assets/37010132/dc02a745-0f9b-4c8c-9cd0-bb3e467dc880)

DejaVu Serif Italic:
![image](https://github.com/be5invis/Iosevka/assets/37010132/56b0380b-1eec-43b3-8cbd-496cda258103)

Liberation Serif:
![image](https://github.com/be5invis/Iosevka/assets/37010132/335e3e55-671c-4aed-9574-1b5ae1a10647)

Liberation Serif Italic:
![image](https://github.com/be5invis/Iosevka/assets/37010132/f420ee04-f45e-4e3e-82de-ae7359946fa1)

**Comment by be5invis** [comment]
Only one monospace font have this (yes I know it is one of the SSes).

**Comment by chelovechishko** [comment]
In [cyrillic] cursive `л` is commonly both sides slanted (to the center) as in `Λ` (big greek lamda) (as opposite of a `П` form). Only left such leg is strange, as for me.

**Comment by jmcwilliams403** [comment]
I'm going to close this if only one SS isn't enough justification.
