### ISSUE TITLE
making the webfonts

### ISSUE THREAD

**Issue by parjanya** [be5invis/Iosevka#194]
I’ve just cloned the master branch and compiled the fonts using `make`. After some problems with yargs, and solving it by uninstalling and installing again (I’m on up-to-date Arch) I had to install a missing program using `npm otfcc-ttcize` (perhaps it should be mentioned in the readme?). Everything went well after that, as far as I know.

How can I compile the webfonts? Just `make web` doesn’t work, and I don’t have a `webfont/` subdirectory.

BTW, this font is gorgeous, thank you.

**Comment by be5invis** [comment]
@parjanya `otfcc-ttcize` is **only** for building fonts for releases, as the "pack" download option.
