### ISSUE TITLE
Cyrillic Yat and Tall Yat (`U+0463`, `U+1C67`) bowl height inconsistency

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1945]
`ъᲆᲇѣ`

Default Sans:
![image](https://github.com/be5invis/Iosevka/assets/37010132/ac823e9e-879a-4154-bca7-383122b871e8)
Default Slab:
![image](https://github.com/be5invis/Iosevka/assets/37010132/0aa6e800-c2cf-4dc0-abe5-5ae43ae18975)

**Comment by be5invis** [comment]
Will not do that for capitals as Yat has extra top details.
