### ISSUE TITLE
{Normal|Wide} Latin-1 Macron (`U+00AF`), {High|Mid|Low} height

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1948]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

Below are examples of Latin-1 Macron (`U+00AF`) compared to Spacing Modifier Macron (`U+02C7`) and Overline (`U+203E`).

Height variants are labeled as either low (the height of a combining mark on a lowercase character), mid (roughly around cap height) or high (the height of a combining mark on a capital character).

Width variants are labeled as either narrow (the normal width of a combining macron) or wide (the same width as an overline)

For simplicity sake, I believe that Overline could simply inherit the height variants of Macron but remain wide, and spacing modifier macron could remain a custom decomposition of whitespace + combining macron. There does not need to be more than one variant selector for this.

`X¯ˉ‾x`

Andale, high and wide:
![image](https://github.com/be5invis/Iosevka/assets/37010132/3dadf130-edb0-48c4-94d1-54d1a0a4f4f7)
Anonymous Pro, low and narrow:
![image](https://github.com/be5invis/Iosevka/assets/37010132/6de8aefc-94f0-4df8-bf69-10fd8c4ed79a)
Consolas, low and narrow:
![image](https://github.com/be5invis/Iosevka/assets/37010132/24cbbe71-621c-4a8a-8597-f2510d742fff)
Menlo, low and wide:
![image](https://github.com/be5invis/Iosevka/assets/37010132/871f1874-d9ab-44e4-92a8-72d6b420257a)
Fira Code, high and narrow:
![image](https://github.com/be5invis/Iosevka/assets/37010132/48ad5adb-2c74-4190-8a68-c44355467128)
Liberation Mono, high and wide:
![image](https://github.com/be5invis/Iosevka/assets/37010132/e03d0887-b5d6-4760-b240-53a6d9052465)
Monaco, low and narrow:
![image](https://github.com/be5invis/Iosevka/assets/37010132/896bbc2f-3072-4e7d-9427-eb656c17289a)
Source Code Pro, low and narrow:
![image](https://github.com/be5invis/Iosevka/assets/37010132/ef6aed8a-d551-4f20-9694-48200c2a4525)
Envy Code R, mid and narrow:
![image](https://github.com/be5invis/Iosevka/assets/37010132/6970f590-82e1-4469-a27c-0a1cc75ffbc7)
Ubuntu Mono, low and narrow:
![image](https://github.com/be5invis/Iosevka/assets/37010132/3b15bbc0-be5e-4fe4-be63-60da148acf45)
PT Mono, low and narrow:
![image](https://github.com/be5invis/Iosevka/assets/37010132/b52315bd-5519-4864-b878-50551e94633c)
IBM Plex Mono, low and narrow:
![image](https://github.com/be5invis/Iosevka/assets/37010132/5a7ad3aa-6b22-4f74-a4b4-bd20551f0856)
Jetbrains Mono, high and narrow:
![image](https://github.com/be5invis/Iosevka/assets/37010132/5e0bcc61-1591-426b-b738-29aa3fa5376b)
Recursive Mono Linear, low and narrow:
![image](https://github.com/be5invis/Iosevka/assets/37010132/04025e5f-2635-49a5-b3b4-9350d7dd9794)
Input Mono, low and narrow:
![image](https://github.com/be5invis/Iosevka/assets/37010132/6faabc07-14d1-4ee5-9635-dda86e649d7c)

**Comment by be5invis** [comment]
Do we really need to go this far?
Iosevka is already, from my aspect, **overcomplicated**. I want to keep it away from further bloating.

**Comment by jmcwilliams403** [comment]
> Iosevka is already, from my aspect, **overcomplicated**. I want to keep it away from further bloating.

For this reason, I'll close this issue for now.
You're right. Now is not the time to add yet more variant selectors and further push limits.
