### ISSUE TITLE
='s are overlapping other characters

### ISSUE THREAD

**Issue by vyasgiridhar** [be5invis/Iosevka#195]
* Your font version: (Release or git, version)
Iosevka 1.12.5-1
* Your font variant:
All
* Your operating system (name and version):
Arch Linux
* Your application using Iosevka: (some Java applications may have problem in showing Iosevka properly. It is a bug in Java's GUI components.)
Gnome-Terminal
If you have problem when building Iosevka, please provide these informations:

* Your Node.js version:
* Your _otfcc_ version:
* Your `make` version:
* Your results of `npm list`:
```
paste here
```
* Your `parameters.toml`:
```
paste here
```
* Your results of `make -d --no-builtin-rules`:
```
paste here
```
---

Describe your problem here. Provide pictures and files if necessary.
![screenshot from 2017-05-01 17-24-16](https://cloud.githubusercontent.com/assets/3121343/25579177/08f28be2-2e93-11e7-8986-274922b57b44.png)

The ='s are overlapping other characters near them

**Comment by be5invis** [comment]
As the Release Notes pointed out, some Linux environments cannot handle ligation correctly causing equal symbol become stretched. Switch to Iosevka Term would solve this problem.

**Comment by vyasgiridhar** [comment]
That worked :) Thanks. Closing this now.
