### ISSUE TITLE
Alternative to #1833 : Possible merger of Yery/Yeri (`ь`/`ы`) variant selectors?

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1950]
Potential area of reduction, where Yer/Yeri responds to only the variants of Yery which differ by the lefthand part.
I am not aware of a font which uses different variants of these characters from each other.

**Comment by jmcwilliams403** [comment]
ref: #1833

**Comment by be5invis** [comment]
Seperating Yeri is necessary as it has a tailed variant which alters the right half.
Resolve as by design.

**Comment by jmcwilliams403** [comment]
I am aware, but as for soft/hard sign, the tail on yery doesn't affect them. For example, straight + tailed would apply a straight variant to soft/hard sign and also the tailedness to yery, and straight + untailed would still apply a straight variant to soft/hard sign and untailed shape to yery.
