### ISSUE TITLE
Capital A with Ring (`U+00C5`) Glyph adjustment

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1955]
The ring is physically attached on many fonts, removing a top serif if there was any.

This would affect `U+00C5`, `U+01FA`, and `U+212B`.

`AÅ`

Andale:
![image](https://github.com/be5invis/Iosevka/assets/37010132/5e91ac8b-3189-4c46-92a4-ee21baaae2a9)
Anonymous Pro:
![image](https://github.com/be5invis/Iosevka/assets/37010132/8ea75686-1795-44b8-ba3c-39d227d3c98e)
Menlo:
![image](https://github.com/be5invis/Iosevka/assets/37010132/b19848e1-8796-4c90-8fbf-ef1e273f4102)
Liberation Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/ad266b06-60b8-417d-9730-a8d9bdbfbecd)
Monaco:
![image](https://github.com/be5invis/Iosevka/assets/37010132/6a80fdb1-244b-4e50-8477-360df1bff648)
Envy Code R:
![image](https://github.com/be5invis/Iosevka/assets/37010132/7eda3049-d223-43bf-aefe-31a17dd88fdb)
Ubuntu Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/072624f5-0e09-4bd9-b117-e4e35d40fb6f)
Lucida Console:
![image](https://github.com/be5invis/Iosevka/assets/37010132/ed052170-e0eb-4ee4-9dae-2917bdc2b820)
PT Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/ea16c2af-9fb1-4d2d-8cea-e9b3ca67a9f5)
Recursive Sans Mono Linear:
![image](https://github.com/be5invis/Iosevka/assets/37010132/46bce250-265d-4209-9607-56c249c17dc2)

**Comment by jmcwilliams403** [comment]
The Unicode charts are inconsistent about it:
![image](https://github.com/be5invis/Iosevka/assets/37010132/18c07f2a-4983-43a2-8a40-cce8554a29a8)
...but it is occasionally a style they use:
![image](https://github.com/be5invis/Iosevka/assets/37010132/d798fa4f-e752-43bb-a0d6-3fd68b1097d3)
![image](https://github.com/be5invis/Iosevka/assets/37010132/adfa5ee8-c45c-4df7-8bcb-7db3ceceaa2c)

**Comment by be5invis** [comment]
I think this is only a style choice. I'd like to keep the current separated design for consistency.
