### ISSUE TITLE
Widths.

### ISSUE THREAD

**Issue by be5invis** [be5invis/Iosevka#196]
Proposal:

- [X] Width style selectors, `expanded` and `compressed`.
- [ ] Export WWS name assignments.
- [ ] Outline correctness fix, esp. `s`-related.

**Comment by be5invis** [comment]
![image](https://cloud.githubusercontent.com/assets/240091/25774173/117a170c-32bd-11e7-9886-8c4ed17416c6.png)

**Comment by glebd** [comment]
Looks very nice too me. Is it the "expanded" style?

**Comment by dok42** [comment]
Hello,
Is there an "expanded"style ? 
I'm actually building my own ss04 style with width = 530 in parameter.toml to achieve a less narrow width.

**Comment by robertgzr** [comment]
`expanded` and `compressed` are styles that can be used as described [here](https://github.com/be5invis/Iosevka#build-your-own-style)

**Comment by dok42** [comment]
Found nothing about expanded and compressed on that page, but tried anyway and worked.
However, I don't like how the resulting font looks, like my customization better because it keeps the characaters slanted.
Thanks ;)

**Comment by be5invis** [comment]
Reactivate this.

**Comment by goodmind** [comment]
Reactivate this.

**Comment by blahgeek** [comment]
Hi, could you please be more specific about the problems of the expanded style?
