### ISSUE TITLE
Certain letters look shorter than others in the ss14 variant

### ISSUE THREAD

**Issue by slashdevslashurandom** [be5invis/Iosevka#1963]
Some letters in the "JetBrains Mono" variant of the font (ss14) visually look like they're not as high as the other letters, when viewed on certain font sizes.

Here's an example: whereas all the other lowercase letters touch the x-height lines, the letters "a", "d", "e", "g", "i", "j", "k", "t", "u", "w" and "y" don't.
![Example image: the lowercase alphabet with two horizontal lines drawn at the baseline and 1px above the x-height, written in Iosevka Term with the ss14 variant enabled.](https://github.com/be5invis/Iosevka/assets/53902042/66e15024-047a-498b-a62b-ee358a344377)

For comparison, here is the same text in the actual JetBrains Mono font, which doesn't exhibit the same issues.
![Example image: the lowercase alphabet with two horizontal lines drawn at the baseline and 1px above the x-height, written in JetBrains Mono.](https://github.com/be5invis/Iosevka/assets/53902042/4f7a5ddd-86c9-4843-af87-a594c7a4b72b)

And here it is in the regular format of the Iosevka Term font, which also looks fine.
![Example image: the lowercase alphabet with two horizontal lines drawn at the baseline and 1px above the x-height, written in Iosevka Term with no variants enabled.](https://github.com/be5invis/Iosevka/assets/53902042/ce7b325f-85ea-45fc-aeba-d6fc8f67874f)

---

* Your font version: v22.1.2 (also applies to v26.2.2)
* Your font variant: Iosevka Term
* Your operating system (name and version): Alpine Linux v3.18
* Your application using Iosevka: Kitty

**Comment by be5invis** [comment]
TTFA issue? You can try the unhinted version I think.
cc @lemzwerg

**Comment by lemzwerg** [comment]
Yes, probably a TTFA issue – the `ss14` table is not evaluated automatically as being part of latin characters, IIRC.  I think you have to add its glyphs manually (I think 'style adjustments' in the control instructions file will do).

**Comment by be5invis** [comment]
@lemzwerg For your "Style Adjustments" setting are there something that aligns glyphs to a script's "default feature"? For Iosevka when `ss14` applied to conventional letters they shall make them behave like... well, just normal letters.

In addition do we need to put letters with different alignment (like `H` vs `g`) into different statements? Or we can simply use one statement?

**Comment by be5invis** [comment]
OK now I have the mechanism to generate control files. Here are some example of subscripts under SS14

Before:
![image](https://github.com/be5invis/Iosevka/assets/240091/d329335d-199b-4875-a000-5e039bd45b48)


After: 
![image](https://github.com/be5invis/Iosevka/assets/240091/cd5e3244-f427-4174-bea9-d02425d205ec)

**Comment by lemzwerg** [comment]
Glad that it worked!

**Comment by slashdevslashurandom** [comment]
While I'm waiting for a new version of the fonts, there does seem to be a workaround: the fonts with the SS14 variant pre-applied seem to have correct hinting, at least on the two other machines I tested them with.
