### ISSUE TITLE
Selectable serifed variants of digits

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#1965]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

One of the fonts below is supported by a stylistic set (`ss02`).

`0123456789`

Anonymous Pro:
![image](https://github.com/be5invis/Iosevka/assets/37010132/f10d9184-e505-4158-896e-160b64405e1a)
Courier New:
![image](https://github.com/be5invis/Iosevka/assets/37010132/5e43db57-60a0-4ef8-b7f6-4293a16da20b)
FreeMono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/2a59dc09-7891-4d7d-8d27-473418217ba6)

**Comment by Logo121** [comment]
cf. #2085 For some more serifed digit variants

**Comment by fabiorug** [comment]
Courier New:
