### ISSUE TITLE
Italic serifed `U` and `u` do not have bilateral serifs

### ISSUE THREAD

**Issue by CuboManco** [be5invis/Iosevka#1967]
The italic variants for non-motion serifed `U` (`U+0055`) and `u` (`U+0075`) do not have an upper right serif like their normal counterparts. This makes `tailed-serifed` and `tailed-motion-serifed` identical, as well as `toothed-serifed` and `toothed-motion-serifed`.
![image](https://github.com/be5invis/Iosevka/assets/36080551/f7a4eaef-f6e6-4411-87d3-f2967cc1e098)
![image](https://github.com/be5invis/Iosevka/assets/36080551/08d52218-fe1e-4c13-bb3a-d50a0b171404)

This isn't the case with the `toothless` variants, nor the oblique version. It also seems to affect similar characters, such as lowercase mu (`μ`). If this by design, I would suggest removing the duplicates if possible.

---

* Your font version: 26.2.2
* Your font variant: Iosevka Slab

**Comment by jmcwilliams403** [comment]
As far as I've seen when contributing to the source code, this appears to be by-design.
