### ISSUE TITLE
Automatic configuration migration

### ISSUE THREAD

**Issue by beojan** [be5invis/Iosevka#1970]
I have a `private-build-plans.toml` with a number of customizations that I occasionally use to rebuild Iosevka. Every time I do this, various variant and ligature names will have changed, and I have to fix all these errors. It would be nice to have a script that can automatically migrate these files to build the latest version of Iosevka.

**Comment by beojan** [comment]
Comment to stop issue being automatically removed.

**Comment by be5invis** [comment]
Variant names usually doesn't have a very obvious updating pattern, but I think starting from version 28 there won't be variant name changes... At least not a lot.

**Comment by be5invis** [comment]
@beojan I will do that in future releases (v28 which WILL include a lot of variant renames).
