### ISSUE TITLE
Please Add Toothed-motion-serifed `u`

### ISSUE THREAD

**Issue by pkj-l** [be5invis/Iosevka#1973]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [ ] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

Just like this:
![toothed-motion-serifed lowercase u](https://github.com/be5invis/Iosevka/assets/43498546/5602253b-4779-4b27-9ffa-f00d96aae651)
**THANKS!**

**Comment by Logo121** [comment]
Out of the lowercase letters (that can have a top-left serif of some sort), `u` is the only one without a top-left serif only variant (in the standard style) I think.

Not sure how much of a justification it makes tho

(Also by symmetry, `µ` would need the same variant, and `hmn` may also need bottom-right only variants.)
