### ISSUE TITLE
U+0320 combining minus below shape

### ISSUE THREAD

**Issue by Logo121** [be5invis/Iosevka#1979]
What are these vertical bars on the ends of the minus sign? I don't think I see any other fonts doing this.
![image](https://github.com/be5invis/Iosevka/assets/21302803/f34a65c4-1c35-4007-a639-da8633a7616a)

Brill: ![image](https://github.com/be5invis/Iosevka/assets/21302803/1749ef83-ac12-445e-a0d3-90560aad3f17)

**Comment by jmcwilliams403** [comment]
The vertical bars are optional serifs and they exist on certain fonts to distinguish them from e.g. a macron below or an underline.

**Comment by jmcwilliams403** [comment]
Ref: https://www.unicode.org/charts/PDF/U0300.pdf
![image](https://github.com/be5invis/Iosevka/assets/37010132/ebf94389-b98b-4723-a1de-faa26b679bbc)

**Comment by Logo121** [comment]
That is a very rare variant though (2 fonts and 0 monospace fonts as far as I can find)

I don't think this should be the default option; the character is supposed to be a counterpart to the combining plus sign (e.g. in IPA), but here the serif is as big as the vertical stroke in the plus sign (while actually making the glyph wider). Doesn't seem to be optional either as Sans has it.

**Comment by be5invis** [comment]
![image](https://github.com/be5invis/Iosevka/assets/240091/ac4c4455-fdfa-4cab-a24d-69027e66ba91)
They now only distingush in size, but is good enough

**Comment by jmcwilliams403** [comment]
Modifier letter minus sign (`U+02D7`) should match too. It's used in IPA for whenever the combining character would render too low in some typesetting contexts.

**Comment by be5invis** [comment]
@jmcwilliams403 done
