### ISSUE TITLE
Give some way to configure default ligation set.

### ISSUE THREAD

**Issue by ChinaXing** [be5invis/Iosevka#198]
I want to use feature of Haskell Design,  build as following

make  custom-config design="XHS0"
make custom

then, install the font in dist/isoevka-custom, but open the OSX terminal, ->- sign already keep un-ligatured, but others like <=> works.

so, how to customize your font for Haskell Design enabled ?

thanks !

**Comment by be5invis** [comment]
It is in master now, build custom variant with `make custom-config design='ligset-haskell'`
