### ISSUE TITLE
Font ligatures break on different sizes and font types

### ISSUE THREAD

**Issue by MrSltun** [be5invis/Iosevka#1984]
Describe your problem here. Provide pictures and files if necessary.

### Description
I've been facing this issue for quite some time, and I believe that it gets fixed every now and then breaks again (with every update from brew)

The ligatures breaks with different languages and different font sizes (I use Ruby, JS & JSON)

### Screenshots & Video

| | with `Iosevka` | with `Iosevka-Term` |
|---|---|-
| Ruby | ![image](https://github.com/be5invis/Iosevka/assets/20655703/78ad65a1-3e9f-4262-9651-d42efe499cfd) | ![image](https://github.com/be5invis/Iosevka/assets/20655703/93f28361-9208-4b5f-b1cf-67f11a533877) |

With JSON:
<video src="https://github.com/be5invis/Iosevka/assets/20655703/8740436c-0f91-4c46-9fd6-7fb5fcc10ff3" />

[JSON Video link](https://www.github.com/be5invis/Iosevka/assets/20655703/8740436c-0f91-4c46-9fd6-7fb5fcc10ff3)

---

* Your font version: 26.3.2 (installed from Brew) (Release or git, version)
* Your font variant: Sans
* Your operating system (name and version): MacOS Ventura 13.5
* Your application using Iosevka: VSCode

If you have problem when building Iosevka, please provide these information:

* Your Node.js version:
* Your `params/parameters.toml`, paste if modified:
  ```
  paste here
  ```
* Your `build-plans.toml`, paste if modified:
  ```
  paste here
  ```
* Your `private-build-plans.toml`, if present:
  ```
  paste here
  ```
* The detailed error log:
  ```
  paste here
  ```

**Comment by MrSltun** [comment]
@be5invis Just re-uploaded it in MP4 but it's still not playing 🤷

**Comment by be5invis** [comment]
It looks like it is cachng related. Never seen this before.
You can try uninstall the fonts, reboot your computer, then reinstall it.
