### ISSUE TITLE
Provide easily downloadable webfonts

### ISSUE THREAD

**Issue by nathanbirrell** [be5invis/Iosevka#199]
As part of releasing a new version of the font, would it make sense to release a downloadable package of the .woff and .woff2 webfont files? 

This would save having to build from source for people who want to use the font on the web.

**Comment by scorcher24** [comment]
Could this be added to Google Fonts? Would be the most simple way. Not sure how the process there is..

**Comment by be5invis** [comment]
@scorcher24 → google/fonts#559. @davelab6, Your turn.

**Comment by be5invis** [comment]
The build script has been updated to automatically build webfonts when releasing. Would include in next release.

**Comment by be5invis** [comment]
Fixed in 1.13.0.
@davelab6 You are so slow :(
