### ISSUE TITLE
shell script to download all packages of given release

### ISSUE THREAD

**Issue by frhack** [be5invis/Iosevka#1994]
To simplify setup in Debian-based Linux distributions, a shell script that downloads all packages from the latest release or a specific release would be very useful.

**Comment by be5invis** [comment]
I have no experience in Bash programming. I think you could use the [GitHub REST APIs](https://docs.github.com/en/rest/releases?apiVersion=2022-11-28) to get the list of assets.

**Comment by be5invis** [comment]
Asset listing API should be what you need: https://docs.github.com/en/free-pro-team@latest/rest/releases/assets?apiVersion=2022-11-28#list-release-assets

**Comment by alexeyten** [comment]
Actually, there is the list of assets in the release object:
```
curl -s 'https://api.github.com/repos/be5invis/Iosevka/releases/tags/v26.3.3' | jq -r ".assets[] | .browser_download_url"
https://github.com/be5invis/Iosevka/releases/download/v26.3.3/super-ttc-iosevka-26.3.3.zip
https://github.com/be5invis/Iosevka/releases/download/v26.3.3/super-ttc-iosevka-aile-26.3.3.zip
https://github.com/be5invis/Iosevka/releases/download/v26.3.3/super-ttc-iosevka-curly-26.3.3.zip
https://github.com/be5invis/Iosevka/releases/download/v26.3.3/super-ttc-iosevka-curly-slab-26.3.3.zip
https://github.com/be5invis/Iosevka/releases/download/v26.3.3/super-ttc-iosevka-etoile-26.3.3.zip
...
```

**Comment by frhack** [comment]
thanks to all I wrote this command to download the latest release fonts  in order to install in debian

```shell
curl -s 'https://api.github.com/repos/be5invis/Iosevka/releases/latest' | jq -r ".assets[] | .browser_download_url" | grep ttf-iosevka | xargs -n 1 curl -L -O --fail --silent --show-error
```
is it correct to download only the files that contain the string  _ttf-iosevka_  in the name ?

thanks

**Comment by Logo121** [comment]
well that depends on what you want i suppose?

if you are fine with .ttc fonts (which are collections of .ttf fonts) you can just download the `super-ttc-iosevka-*` files.  
but if you specifically need all ttf files (hinted), then `ttf-iosevka` is correct.

**Comment by frhack** [comment]
Hi, in order to close this issue I suggest to add this command in the documentation in the "installation/manual installation/linux" section.
Manual downloading is tedious and error-prone.

Thanks

**Comment by be5invis** [comment]
@frhack This?
```bash
curl -s 'https://api.github.com/repos/be5invis/Iosevka/releases/latest' | jq -r ".assets[] | .browser_download_url" | grep ttf-iosevka | xargs -n 1 curl -L -O --fail --silent --show-error
```

**Comment by frhack** [comment]
> @frhack This?

yes

> 
> ```shell
> curl -s 'https://api.github.com/repos/be5invis/Iosevka/releases/latest' | jq -r ".assets[] | .browser_download_url" | grep ttf-iosevka | xargs -n 1 curl -L -O --fail --silent --show-error
> ```
> 
> Does this really list everything? I heard that the API is paginated (i.e., only 30 items per query).

Yes it list everything as you can see:

[https://api.github.com/repos/be5invis/Iosevka/releases/latest](https://api.github.com/repos/be5invis/Iosevka/releases/latest)
