### ISSUE TITLE
Variant for number five

### ISSUE THREAD

**Issue by Morpheus2077** [be5invis/Iosevka#1995]
Could create a more symmetrical Variant of 5?

Jetbrains Mono
![jetbrains-mono_five2](https://github.com/be5invis/Iosevka/assets/57775700/9ee16f1b-e941-458c-9061-a98bd82a8533)

Pragmata Pro
![pragmata-pro_five2](https://github.com/be5invis/Iosevka/assets/57775700/95760a75-20db-417d-a6a4-651681441017)

**Comment by be5invis** [comment]
Could you explain what differs your requested shape from the defualt shape?
![image](https://github.com/be5invis/Iosevka/assets/240091/aa10f59a-7ffa-450a-98fd-b63e3c0c0d4a)

**Comment by Morpheus2077** [comment]
Look, it doesn't match my build…
![construction](https://github.com/be5invis/Iosevka/assets/57775700/8a34f2d5-05a2-4f4e-9496-cf5cd6aaef60)

**Comment by be5invis** [comment]
Could you spot out the shape feature you'd like to request? And what it differentiates from the existing glyph?

**Comment by Morpheus2077** [comment]
I would like the glyph less serifed and more flat/symmetric
![serif_to_flat](https://github.com/be5invis/Iosevka/assets/57775700/096639b6-bc21-422e-b0c2-68fdd9b7b110)

**Comment by Logo121** [comment]
![image](https://github.com/be5invis/Iosevka/assets/21302803/41e847b6-6c53-4188-a951-05fd7a937709)

closable?

**Comment by Morpheus2077** [comment]
Perfect, thanks @be5invis

**Comment by Morpheus2077** [comment]
I think the design of all the number 5s are a little to the left (middle-top), it's a small detail that makes a big difference 😅
![five_centered](https://github.com/be5invis/Iosevka/assets/57775700/f04f74f3-4114-4ecb-bea4-d6788173b08a)
