### ISSUE TITLE
Thin Variant

### ISSUE THREAD

**Issue by joshvickerson** [be5invis/Iosevka#2]
How difficult would it be to add a 'thin' weight variant? I prefer thinner fonts.

Would be happy to help if someone can give me a little direction on how to contribute!

**Comment by erwagasore** [comment]
+1

**Comment by be5invis** [comment]
@joshvickerson hmmm, maybe just change the parameters.patel (which compiles into parameters.js), add a new configuration and reduce the .stroke property to maybe 50 or 60. But I will focus on glyph coverage first.

**Comment by be5invis** [comment]
O I forgot I've completed all seven weights, so this one issue can be finally closed.
