### ISSUE TITLE
Contributing?

### ISSUE THREAD

**Issue by dieggsy** [be5invis/Iosevka#200]
I know you had talked about a contribution API earlier on - I don't know absolutely anything about glyph design and font building, but I was wondering what the easiest way to contribute is? Is there a methodology you could describe and/or a style guide or something?

I ask because given the sheer volume of unicode characters, it would be cool if people could add their preferred ones (approved by you of course).

**Comment by be5invis** [comment]
The problem is that... Iosevka, itself, is written in a special language, and I used a lot of black macro magic. I'd like to provide an API to make people able to contribute but I do not have much time now (I am working on a huge font project).
But I **promise** it would be there.

**Comment by cloudhan** [comment]
@therockmandolinist FYI,  the **huge font project** mentioned by be5invis is a project that build better font for Windows 10 (RS3 or later), Here is the spoiler:
![](https://pic3.zhimg.com/v2-1a8aa863a50f01a500dc735427013156_r.png)

**Comment by be5invis** [comment]
@cloudhan I have to delete your post.

**Comment by cloudhan** [comment]
LOL, you should delete that source, not my link.
BTW, when will we get it, optimistically?

**Comment by be5invis** [comment]
@cloudhan 无可奉告。
