### ISSUE TITLE
Documentation on affected characters by each `cvxx`

### ISSUE THREAD

**Issue by Logo121** [be5invis/Iosevka#2005]
Inspired by a recent comment [here](https://github.com/be5invis/Iosevka/issues/1981#issuecomment-1706186502) on the consequences adding a new variant (dimension), among other things

Is there a list on which `cvxx` (or other features like `WWID`) would affect which characters, or a simple enough tool for query such thing? Kinda like a reverse-lookup table for these in the specimen:
![image](https://github.com/be5invis/Iosevka/assets/21302803/b9432cba-6f30-452f-b51e-255e47fcc643)

Specifically, instead of checking from "character --> CVs that apply to it", I'm looking for something that does "CV --> characters affected by that setting". Previews of the variant effect is not necessary (but welcome).

This would be useful because:
* Some variant requests a while ago called for making some less common characters "follow the serifs/shapes" of some other characters with dedicated CVs (might discuss about that later).  
For some of these I would argue they are not directly intuitive/expected by regular users. It would definitely help if they are documented somewhere. 
Examples include:
   * #1892 
   * #1906 
   * #1908 
   * #1957
   * Even before these, there are cases like U+01BE `ƾ` (based on t, s for technically being a `ts` ligature)
 * Even excluding the above "character following a different character's cv" cases, there are some CVs that changes a "category" of characters (`cv93`, `cv94`, `WWID/NWID`), which an exact list thereof would be good to have regardless.
 * In case of new variant requests, it would be easier to gauge/visualize the impact of such a variant; or from a contributor's perspective, the exact characters one needs to handle when implementing that variant.

**Comment by be5invis** [comment]
> Previews of the variant effect
This will produce thousands of images...
And we already have thousands of them already (for the "custom build" doc).

**Comment by Logo121** [comment]
> > Previews of the variant effect
> 
> This will produce thousands of images... And we already have thousands of them already (for the "custom build" doc).

yeah, that's why I said that part is not really needed

(btw, I've heard comments that the custom-build page can't even be loaded properly in some environments due to the sheer amount of images, so something probably needs to done for that as well)
