### ISSUE TITLE
Request an OTF/TTF file as a result of default configuration

### ISSUE THREAD

**Issue by Guest-615695028** [be5invis/Iosevka#2013]
I cannot find where the TTF/OTF files are located. Could anyone find a route?

**Comment by alexeyten** [comment]
Have you looked in `dist/` folder?

**Comment by be5invis** [comment]
The `ttf-iosevka-<version>.zip` asset in the [releases](https://github.com/be5invis/Iosevka/releases) contains the exactly what you want. Open a release, find the corresponded file.
