### ISSUE TITLE
Mordvin Cyrillic letters (`U+0514`..`U+0519`)

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#2018]
- The requested characters are ...
  - [ ] Latin
  - [x] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [ ] Diacritic / Mark
  - [ ] Symbol
- The requested characters are used in ...
  - [x] The alphabet / character set of a natural language.
  - [ ] The alphabet / character set of a constructed language.
  - [ ] The alphabet / character set of a transliteration or notation system.
  - [ ] Mathematical or other professional use in documents.
  - [ ] The symbol set of a programming language. For the languages that support using arbitrary symbols, please provide usages in well-known components or libraries.
  - [ ] The symbol set of a command-line program.
- [x] Some other monospace/programming fonts supported this character. Provide images below.

------

Adding these characters will complete the Cyrillic supplement block and finally close #983

`ԔԕԖԗԘԙ`

Consolas:
![image](https://github.com/be5invis/Iosevka/assets/37010132/f7e4549f-8145-4166-b18e-da4f5034f285)
Courier New:
![image](https://github.com/be5invis/Iosevka/assets/37010132/cf12a578-63c9-44cb-97d9-4d26939b6b2c)
Fira Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/9adf936c-6cb5-4032-b393-f15e49123394)
Noto Sans Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/19647c3e-3265-42c7-84e9-fb7edb9b8557)
Everson Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/3be9a5c8-5f16-45e8-b87e-cb4ca2a6919e)
Fairfax HD:
![image](https://github.com/be5invis/Iosevka/assets/37010132/ac4984a3-c632-4aad-8c02-aa11a8969754)

**Comment by Logo121** [comment]
oh i have been staring at these letters for a long time

how would it look like when `х` is set to the cursive variant though, I can't find any fonts supporting `ԕԗ` with that cursive `х`

**Comment by be5invis** [comment]
@Logo121 Maybe...
`ԕ` -- just make the top-left part of the cursive stroke flat.
`ԗ` -- just keep the right half. May need to modify `XCursiveHalfShape` to support a "uniform" X-strand though.

**Comment by jmcwilliams403** [comment]
Not that it would entirely solve the issue of figuring out what this character would look like under a font that uses a cursive `x`, but [the final draft of the original Unicode proposal document](https://www.unicode.org/L2/L2007/07003r-n3194r-cyrillic.pdf#page=21) may have an unrelated (but useful) piece of info on this line of text:

![image](https://github.com/be5invis/Iosevka/assets/37010132/0bebcb10-090c-4e02-8803-80615ea5c97f)

**Comment by jmcwilliams403** [comment]
In any case, here's a couple examples that do something vaguely similar.
`лԕхрԗх`
Charis SIL:
![image](https://github.com/be5invis/Iosevka/assets/37010132/4a6b4d89-c5d5-49c4-a2c8-71689e6dbf30)
Gentium Plus:
![image](https://github.com/be5invis/Iosevka/assets/37010132/2c7fb2b1-f04f-48b8-99c1-62098c09d3b2)

**Comment by Logo121** [comment]
I tried to make the Rha glyphs and this is what i get for now
![image](https://github.com/be5invis/Iosevka/assets/21302803/b2e21e0a-162b-4ef8-9c51-2b0aae948592)

Font features: `"cv15" 05, "cv23" 05, "cv48" 07, "cv81" 10`

Implementing these requires modifying so many functions (the biggest reason why I didn't try making Yae earlier),  
I'm not sure if I accidentally broke anything, especially the cursive `x` (I have no idea how that works)

I don't want to imagine how capital Rha would work with a cursive big `X`, thank god #1819 didn't happen lol

**Comment by Logo121** [comment]
Current draft:
![image](https://github.com/be5invis/Iosevka/assets/21302803/aeb5e035-7c68-4366-8460-382115bae220)
