### ISSUE TITLE
Emacs里汉字显示不了

### ISSUE THREAD

**Issue by bhuztez** [be5invis/Iosevka#202]
* Your font version: 1.12.5
* Your operating system: Fedora 24
* Your application using Iosevka: Emacs 25.1

设置了 (set-frame-font "IosevkaCC") 之后 ，英文字母都用你这个字体了，但是汉字却没有。用 C-u C-x = 可以看出是用了别的什么字体。但是，比如AR PL UMing CN之类的字体就没这个问题。

同样的 (set-fontset-font t 'han (font-spec :family "AR PL UMing CN")) 没问题，(set-fontset-font t 'han (font-spec :family "IosevkaCC")) 就完全没有作用

**Comment by be5invis** [comment]
Iosevka CC does **NOT** have ideographs.
You should use Inziu Iosevka linked in the README.
Closed.

**Comment by be5invis** [comment]
https://be5invis.github.io/Iosevka/inziu.html
