### ISSUE TITLE
Countersink U+2335

### ISSUE THREAD

**Issue by gifti258** [be5invis/Iosevka#2020]
- The requested characters are ...
  - [ ] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [ ] Diacritic / Mark
  - [x] Symbol
- The requested characters are used in ...
  - [ ] The alphabet / character set of a natural language.
  - [ ] The alphabet / character set of a constructed language.
  - [ ] The alphabet / character set of a transliteration or notation system.
  - [ ] Mathematical or other professional use in documents.
  - [x] The symbol set of a programming language. For the languages that support using arbitrary symbols, please provide usages in well-known components or libraries.
  - [ ] The symbol set of a command-line program.
  - [ ] Some other monospace/programming fonts supported this character. Provide images below.

------

The symbol is used in the Uiua programming language.

**Comment by Logo121** [comment]
(btw, the other symbols used in that language and not supported by Iosevka yet are:
* U+2315 `⌕` TELEPHONE RECORDER
* U+238B `⎋` BROKEN CIRCLE WITH NORTHWEST ARROW
* U+29FB `⧻` TRIPLE PLUS)

**Comment by jmcwilliams403** [comment]
I found three/four examples off the top of my head for monospace/programming fonts that have all four symbols:

`⌵⌕⎋⧻`

DejaVu Sans Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/427c5198-43bf-49b0-8b11-25a8af0f6eae)
Julia Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/c53d4767-b2c9-4f8b-bc11-4b988dba1e10)
Fairfax HD:
![image](https://github.com/be5invis/Iosevka/assets/37010132/fba2fec4-0d2f-4130-ba53-e383eece00da)

There's also Pragmata Pro but I don't own it, so here's a sample from fonts(\.)com:
![image](https://github.com/be5invis/Iosevka/assets/37010132/66765571-1a74-4ce8-9c0d-344bafeac26f)
