### ISSUE TITLE
Iosevka Extended not getting recognised in Windows 11

### ISSUE THREAD

**Issue by lakshits11** [be5invis/Iosevka#2021]
Describe your problem here. Provide pictures and files if necessary.

I installed both iosevka and iosevka extended. So the name 'iosevka' in font family gives me standard iosevka but the name 'iosevka extended' is not getting recognised.
---

* Your font version: (Release or git, version) 27.1.0
* Your font variant: extended all
* Your operating system (name and version): windows 11
* Your application using Iosevka: vscode, ,chrome etc.

**Comment by mfocko** [comment]
IIRC on Windows it is `Expanded` instead of `Extended`

**Comment by be5invis** [comment]
It uses standard OT **width** parameter. VSCode does not support configuring font width yet.

**Comment by lakshits11** [comment]
Ok thank you. You can close it now.
