### ISSUE TITLE
Ability to compile custom font with a given locale's overridden letter forms as default

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#2025]
Basically if you could have additional arguments to set the custom font's default locale to e.g. Serbian at compile time and then the Serbian-specific italic letters would be what the font uses by default before the locale of the application has been configured.

This wouldn't use any additional GUI elements in the config page, just some new toml arguments and of course documentation for them, similarly to how you can enable APL forms or old-style numbers by default without there needing to be a GUI element for them.

**Comment by be5invis** [comment]
`locl` for `VIT` is specially implemented as it changes the marks, so we cannot simply "bake" glyphs.

**Comment by jmcwilliams403** [comment]
I actually did indeed mean that I wanted to enable Serbian Cyrillic by default. This isn't just me trying to sneak in Vietnamese diacritics by default.

There's a Cyrillic alphabet for Esperanto that I've been using that closely matches Serbian Cyrillic, but I don't want to completely set my VSCode to Serbian because I don't speak Serbian.

**Comment by jmcwilliams403** [comment]
The alphabet is almost a total subset of the Serbian alphabet except for the extra additions of `Һ`/`һ` and `Ў`/`ў`.
[Source](https://www.omniglot.com/conscripts/esperantocyrillic.htm)
![bildo](https://github.com/be5invis/Iosevka/assets/37010132/090c01e7-6897-423c-83fe-dfccbc61631e)

Having Serbian letterforms for this would be entirely my own preference and not strictly orthographic.

**Comment by be5invis** [comment]
I remember there are some tools from `fonttools` (or harfbuzz) could "bake" font features into fonts' `cmap`. For `locl @ cyrl/SRB` it could work for Iosevka.

**Comment by jmcwilliams403** [comment]
Maybe some documentation about that would suffice?

**Comment by be5invis** [comment]
The volume of requests for baking `locl` features is low I think.

**Comment by jmcwilliams403** [comment]
What about the collective volume of requests for everything that could be considered out of scope for customization?

**Comment by be5invis** [comment]
Added a new section for that in the docs. Will be in `main` in next release. Closing.

**Comment by be5invis** [comment]
The README in https://github.com/twardoch/fonttools-opentype-feature-freezer has a specialized command line for how to bake localized forms for `cyrl`/`BGR ` (note the trailing space in language tag):

```bash
pyftfeatfreeze -f 'locl' -s 'cyrl' -l 'BGR ' -S -U BG SomeFont.ttf SomeFontBG.ttf
```
