### ISSUE TITLE
Feedback, question and suggestions

### ISSUE THREAD

**Issue by Morpheus2077** [be5invis/Iosevka#2027]
1. Oval glyph shape like zero for O

2. Add width to customizer on website

3. What is the difference between;
r = "hookless-serifless" > r = "compact-serifless"
r = "hookless-top-serifed" > r = "compact-top-serifed"
r = "hookless-base-serifed" > r = "compact-base-serifed"

4. You can check the feedback for 5 in [#1995](https://github.com/be5invis/Iosevka/issues/1995#issuecomment-1751554466)

**Comment by be5invis** [comment]
Q1: It is already there.
Q2: Could you please clarify? Do you need a series of checkboxes to enable other (less-tested) widths?
Q3: `compact` variants will become narrower when built with quasi-proportional. In monospaced build they are indeed identical.
Q4. Please file a separate but more specific issue about this.

**Comment by Morpheus2077** [comment]
Q1. I mean the letter O "oh"

Q2. Example, Semi-Expanded would be something like 550 Shape…
  "ultra-condensed"
  "extra-condensed"
  "condensed"
  "semi-condensed"
  "normal"
  "semi-expanded"
  "expanded"
  "extra-expanded"
  "ultra-expanded"

Q4. Ok, I'll open a new Issue later

**Comment by be5invis** [comment]
@Morpheus2077 Then for Q1, please fire a separate, secific issue for it.
For widths, the build system could only produce widths from "Condensed" (unit width being 0.416em) to "Ultra-Expanded" (unit width being 0.720em). And widths beyong the "normal-expanded" range are NOT TESTED. I could add checkboxes but there will be no preview on the website.

Resolve as triaged.
