### ISSUE TITLE
Tailed Lower Lambda (`λ`)

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#2036]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

`yλ`

Andale Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/9ce8e060-d408-4da0-a5de-6fdd3bbd2372)
Consolas:
![image](https://github.com/be5invis/Iosevka/assets/37010132/d2e26a66-cb15-4330-8f72-38b60200f18f)
Cascadia Code:
![image](https://github.com/be5invis/Iosevka/assets/37010132/b071fd7c-2637-43af-be0d-12e457de0310)
Pragmata Pro:
![image](https://github.com/be5invis/Iosevka/assets/37010132/7484153f-b7b4-4568-909c-1ddbba95454c)
Noto Sans Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/a9f5a191-cc0c-461b-8605-c0af1ce4ce87)

**Comment by be5invis** [comment]
Do we need a "straight top but tailed" one too?

**Comment by jmcwilliams403** [comment]
I've not seen one yet, so likely not.
