### ISSUE TITLE
"Cursive" Lower Chi (`χ`)

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#2037]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

Only the top-left-to-bottom-right bar should be made cursive here, and as such would replace any serifs present on the bar.
`χ`
Consolas:
![image](https://github.com/be5invis/Iosevka/assets/37010132/5b87d211-c5c9-4d22-ab57-e703731a544f)
Cascadia Code:
![image](https://github.com/be5invis/Iosevka/assets/37010132/03fc14fd-950b-46a1-a6aa-6bf41fcdc1ca)
Menlo:
![image](https://github.com/be5invis/Iosevka/assets/37010132/9270a20f-c463-4843-9232-171c3a3b434a)
Pragmata Pro:
![image](https://github.com/be5invis/Iosevka/assets/37010132/d00b5c4c-1f4a-48b5-9f11-f77949cb27f5)

**Comment by be5invis** [comment]
Actually two, one with other leg straight and one with other leg curly (Pragmata Pro).

**Comment by be5invis** [comment]
Add Chancery and Semi-Chancery variants for lowercase `x` and Greek Chi (#2037).
