### ISSUE TITLE
Hinting problem with kana in Inziu

### ISSUE THREAD

**Issue by mxalbert1996** [be5invis/Iosevka#204]
* Your font version: 1.13.0
* Your font variant: Inziu Iosevka SC
* Your operating system (name and version): Windows 10 1703 with 200% DPI
* Your application using Iosevka: Programs using GDI such as Notepad

In some sizes, kana look awful in GDI programs. This problem didn't exist in 1.11.0.

1.11.0:
![1.11.0_1](https://user-images.githubusercontent.com/9391933/26842116-ac201da2-4b26-11e7-9063-216fb442b62a.png) ![1.11.0_2](https://user-images.githubusercontent.com/9391933/26842113-a9a9c672-4b26-11e7-9b69-5d4ab8ea7085.png)

1.13.0:
![1.13.0_1](https://user-images.githubusercontent.com/9391933/26842194-e4df0e64-4b26-11e7-8a38-2de8b05466b0.png) ![1.13.0_2](https://user-images.githubusercontent.com/9391933/26842239-102a065a-4b27-11e7-9647-7eaa65d7f0a7.png)

**Comment by be5invis** [comment]
You should file an issue to TTFAutohint, not Iosevka...
For non-Kanji I simply use TTFAutohint, because... VTT does not have any command-line interface.
**And do you know GDI supported Y-axis anti-aliasing in RS2?**

**Comment by mxalbert1996** [comment]
@be5invis I know. Is that relative to this?

**Comment by be5invis** [comment]
@mxalbert1996 
Maybe TTFA mis-applied the hints for Non-AA into an environment with AA and caused bugs.

**Comment by mxalbert1996** [comment]
@be5invis Did you change the version of TTFA after 1.11.0? Cause the screenshots are captured in the same environment.

**Comment by be5invis** [comment]
@mxalbert1996 
You know, I joined MS in Feb and I have to setup another building environment on the MS' server.
So YES, I changed the version of TTFA when setting it up.

**Comment by mxalbert1996** [comment]
@be5invis So could you please use the previous version of TTFA from next release before the problem is fixed in TTFA?

**Comment by be5invis** [comment]
@mxalbert1996 I'd like to investigate when I have time.

**Comment by mxalbert1996** [comment]
@be5invis Thanks.

**Comment by be5invis** [comment]
I think TTFA incorrectly detected Y-AA support: They use "fractional advance" rather than the real flag.

**Comment by be5invis** [comment]
I've reported to Werner and it would be fixed in the latest release. Closed.
