### ISSUE TITLE
Bitshift operator (`<<=`/`>>=`) ligature doesn't appear to do anything.

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#2042]
In any language's ligation set that uses it, enabling it appears to do absolutely nothing, except for _disabling_ whatever arrow ligation it had for that token, effectively making it anti-useful:
![image](https://github.com/be5invis/Iosevka/assets/37010132/6ba33e0f-7dab-4654-9008-85a2ea7392db)
![image](https://github.com/be5invis/Iosevka/assets/37010132/0a7632cd-f227-4836-b995-f000d37c2f42)
![image](https://github.com/be5invis/Iosevka/assets/37010132/f3c229e3-2a57-4d78-8036-f2039f74785b)
![image](https://github.com/be5invis/Iosevka/assets/37010132/8d936052-f903-46ae-b257-f5e8bcf357b4)
![image](https://github.com/be5invis/Iosevka/assets/37010132/6497838d-147d-4fb0-84a9-85f4054a501c)
![image](https://github.com/be5invis/Iosevka/assets/37010132/29dbc206-d46f-4e75-8d69-ae73b9aea9de)

**Comment by mfocko** [comment]
`>>` and `<<` are closer to each other… also full ligature including the equal sign is sometimes rather weird (especially with Haskell)

**Comment by jmcwilliams403** [comment]
> especially with Haskell

okay but Haskell is a defined ligation set that looks like this:
![image](https://github.com/be5invis/Iosevka/assets/37010132/a8cc3090-c562-448a-9fa2-8b476de1a759)

**Comment by mfocko** [comment]
it's a matter of preference IMO… if Iosevka switches to the Haskell variant, you'll have someone dissatisfied with that :shrug: :D I think you should be able to create a custom build with the ligature being set to what you want

**Comment by be5invis** [comment]
Yes these sets are used to **DISABLE** arrow- or ant-arrow-like `>>=` and `<<=` ligations. I enabled these in `calt` and sets of C-like laguages to avoid confusion with these arrows.
Resolve as by design.
