### ISSUE TITLE
Raised cap-height cent sign (`¢`) to go with `dollar = cap`

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#2044]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

Anonymous Pro:
![image](https://github.com/be5invis/Iosevka/assets/37010132/a50bd0e7-4142-4cbe-b659-4dad4c22f798)
Consolas:
![image](https://github.com/be5invis/Iosevka/assets/37010132/a06629a3-d24c-4bfb-b484-b1b04dc0d036)
Courier New:
![image](https://github.com/be5invis/Iosevka/assets/37010132/e0f3df3f-c869-4a80-8edc-a2c6a39bd703)
Liberation Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/8985e069-b9bb-401b-bf6c-b3c3809ff68d)
Monaco:
![image](https://github.com/be5invis/Iosevka/assets/37010132/8e9fe513-1f9d-40d3-b66b-8db6a732ab47)
Source Code Pro:
![image](https://github.com/be5invis/Iosevka/assets/37010132/9eeb8e20-b422-427b-9940-cdb6736920b1)
X Windows Fixed:
![image](https://github.com/be5invis/Iosevka/assets/37010132/9751de03-1914-48a3-a505-ddf4f41c0c97)
Lucida Console:
![image](https://github.com/be5invis/Iosevka/assets/37010132/4f24abf8-baf5-4672-972a-fe7f23da4b8c)
Recursive Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/e5d811ce-c471-4f01-86b8-01fedf450164)
Input Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/3091388d-d7db-45e1-9129-b2a8e545b336)

**Comment by be5invis** [comment]
We already have `VSAM`. Consider add new variants to that.
