### ISSUE TITLE
Cyrillic Yat (`ѣ`) should respond to Yeri variants (`cv79`).

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#2047]
`rьѣ`
Iosevka Aile Italic (as an example):
![image](https://github.com/be5invis/Iosevka/assets/37010132/d35c88fb-3e99-4bcc-98bb-ef5fadffa471)
Notice how the italic form is currently automatic instead of with respect `cv79`.

Compared to Liberation Sans Italic:
![image](https://github.com/be5invis/Iosevka/assets/37010132/06f7de6f-60d5-4a61-83ac-bd0ef213df60)

**Comment by be5invis** [comment]
@dscorbett Are Yat and Yeri semantically related?

**Comment by jmcwilliams403** [comment]
In particular I'm mainly talking about these corners:
![image](https://github.com/be5invis/Iosevka/assets/37010132/2b9346a0-8294-45be-bb5c-b1505eed74b4)

**Comment by jmcwilliams403** [comment]
Here's Ubuntu Mono, but for the record it's better that we not entertain its toothless corner variant for the left half:
![image](https://github.com/be5invis/Iosevka/assets/37010132/5256c9e7-a6b2-47a0-8cc1-260d3776e0b4)
