### ISSUE TITLE
Short-Tailed Lower Tau (`τ`)

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#2050]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

For the following three fonts, their lower tau (`τ`) takes on a form closer to a single-legged lower Pi (`π`)
`ιπτt`
Liberation mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/51e729bf-03fc-4ce6-bab3-63ca2563ee15)
Source Code Pro:
![image](https://github.com/be5invis/Iosevka/assets/37010132/b9dafa02-e0d6-4543-b78f-87a45effb9be)
Input Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/479da1d5-4bd1-4495-a5c4-8a61ae61c390)

------

Anonymous Pro also has a short-tailed lower Iota:
![image](https://github.com/be5invis/Iosevka/assets/37010132/42866102-39f2-4b77-8e54-41d638eeb3e1)

**Comment by be5invis** [comment]
Really, do you need *this* detailed difference?
It is lucky that `τ` will only introudce 1 new glyph.

**Comment by be5invis** [comment]
(I also added back the old tailed shape for `i`, `l`, iota and tau. Named as "semi-tailed".)
