### ISSUE TITLE
Bug in Specimen: The blocks Latin Extended-F, Latin Extended-G, Cyrillic Extended-D, and Symbols for Legacy Computing are each shown twice.

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#2051]
![image](https://github.com/be5invis/Iosevka/assets/37010132/036d6268-cad0-4eac-9709-c02a5d00c539)
![image](https://github.com/be5invis/Iosevka/assets/37010132/8113f4ec-6162-4989-840d-fbfa751af14b)
![image](https://github.com/be5invis/Iosevka/assets/37010132/cb753f80-874c-4b09-af8a-bba2c56f60f4)
![image](https://github.com/be5invis/Iosevka/assets/37010132/2dddb118-a54b-40f6-a2f9-a0d18f0c64ac)

**Comment by Logo121** [comment]
Probably this https://github.com/be5invis/Iosevka/blob/a82aa8f04211fccd07fb3e77321c729422da7b8f/utility/export-data/coverage-export/block-data.mjs#L7-L12

The UnicodeDataIndex probably got updated to contain these blocks now

**Comment by be5invis** [comment]
Next version of website will fix this.
