### ISSUE TITLE
Webfont does not work on iOS

### ISSUE THREAD

**Issue by cedws** [be5invis/Iosevka#2052]
* Your font version: [27.2.1 distributed via GitHub Pages](https://github.com/iosevka-webfonts/iosevka)
* Your font variant: Webfont
* Your operating system (name and version): iOS
* Your application using Iosevka: Webpage (tried in Safari + Firefox Focus)

I've been trying to use Iosevka for my website, but for some reason it does not display on iOS. The GitHub Pages link above distributes it in TTF and WOFF2 formats. I've also tried using `pyftsubset` to convert the TTFs to WOFF and included them in the CSS stylesheet, but it still doesn't work.

Stylesheet is [here](https://iosevka-webfonts.github.io/iosevka/iosevka.css).

**Comment by berrymot** [comment]
you have to apply them to something e.g.
```css
* {
	font-family: 'Iosevka Web';
}
```

**Comment by cedws** [comment]
Yes, of course 😃 I have set the font family in my own stylesheet as well.

**Comment by alexeyten** [comment]
Works perfectly https://codepen.io/alexeyten/pen/VwgZwQv

**Comment by cedws** [comment]
Very strange. Here is a screenshot. I'll try to investigate a bit more later.

![image](https://github.com/be5invis/Iosevka/assets/38229097/67f2c930-6667-404e-9593-24d416b053f4)

**Comment by cedws** [comment]
Sorry for wasting your time, as you have probably guessed, it's nothing to do with the font.

I used Web Inspector to see what was going on and saw that the TTF/WOFF2 sources were being blocked by a "Content Blocker." I didn't remember installing one, but apparently Firefox Focus installs one for you that *also* blocks stuff in Safari too. I'm not sure why it blocks custom fonts though.

Fix was to uncheck "Use Content Blockers on > All Websites"
