### ISSUE TITLE
Bug in specimen: Derived/reduced characters' selected variants are grouped seemingly in reverse order.

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#2057]
![image](https://github.com/be5invis/Iosevka/assets/37010132/a70195ef-4b32-42df-887d-c39042c4c0d6)
![image](https://github.com/be5invis/Iosevka/assets/37010132/2066d9dd-1f2a-4e44-91fd-d84962fedb45)

**Comment by be5invis** [comment]
Well it is about choosing the representative variant in a group of variants that produces the same glyph.
Next release will ensure that the one with least rank will be used.
