### ISSUE TITLE
Semi-Tailed lower `t` like the variants for `i`/`l`/`ι`/`τ`.

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#2058]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [ ] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

`ltι`

Liberation Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/b739da2c-cd45-4f75-b95f-dc7ea5c070c9)
Notice how the `t` is more tailed than `l` but less tailed than iota.

**Comment by be5invis** [comment]
Please add more evidences showing that there are other fonts leveraging the significantly different depths of hooks/tails.
I _really really really_ do not want to add more complications now.

**Comment by jmcwilliams403** [comment]
I'll just close this because it's highly unessential. I have more examples I could show but it's probably better that we just not entertain this variant regardless, as it could open up the door for adding this variant for all other hooked characters, which which is all just pure bloat now that I think more about it.
