### ISSUE TITLE
matlab中1.13.1乱码，1.12.5正常

### ISSUE THREAD

**Issue by daoxunchen** [be5invis/Iosevka#207]
* Your font version: (Release, 1.13.1)
* Your font variant: inziu-iosevkaCC-SC
* Your operating system (name and version): windows10-1703
* Your application using Iosevka: matlab

之前用的是1.12.5正常，更新到1.13.1（&rebuild font cache）后中文乱码。
恢复到1.12.5正常
![12](https://user-images.githubusercontent.com/3649350/27116822-e6c2c290-5105-11e7-8963-902bc5ee0ae8.PNG)

![13](https://user-images.githubusercontent.com/3649350/27116828-ed173018-5105-11e7-86fa-f5cf40022e77.PNG)
正常的是1.12.5，错误的是1.13.1，同样的文字
我还需要提交什么信息？

**Comment by be5invis** [comment]
你是不是覆盖安装了？
不要覆盖安装。
重启，删掉旧版，装新版

**Comment by daoxunchen** [comment]
刚才测试几遍，仿佛还是不行。
最复杂的一次操作：删旧的->重启->删除fontcache->重启->安装新版
删除fontcache的方法：https://www.tenforums.com/tutorials/54452-rebuild-font-cache-windows-10-a.html
---
1. c:\windows\fonts和控制面板里删除是一样的吧
2. 1.12.5直接覆盖1.13.1是没有问题的

**Comment by be5invis** [comment]
@daoxunchen 卸载完之后要开一个最高权限的 powershell 删掉留存的文件：
```powrshell
rm C:\Windows\Fonts\inziu*
```
然后重启
另外建议关掉 Windows Font Cache 服务

**Comment by daoxunchen** [comment]
666
禁用font cache服务 和 rm c:\Windows\Fonts\inziu* 后显示正常了
谢谢 @be5invis 大大
