### ISSUE TITLE
Support true space widths 

### ISSUE THREAD

**Issue by runxel** [be5invis/Iosevka#2076]
**Is your feature request related to a problem? Please describe.**
If you want to use Iosevka not only for coding but for typesetting in general it's missing control over its whitespace.
A normal space will be as wide as a thin space as wide as an em space...

**Describe the solution you'd like**
A character variant could be implemented where all spaces have their true typographic widths.

**Describe alternatives you've considered**
Not using Iosevka 😄

**Comment by be5invis** [comment]
Sorry I could not understand your request. Are you asking that certain space chars (like the quarter-EM) will be exactly 1/4 em rather than "one cell" (to enforce its monospace-ness)? I think Aile/Etoile are already doing that?

**Comment by runxel** [comment]
Sorry for not making it any clearer!
Yes, that is exactly my point. Aile also loses a lot of the typographic distinctives in it's default configuration that are important for me, like with the lower "L" which will gain similarity with the upper case "i".
I guess I just need to look at building Iosevka (or rather Aile) from source once again.
Btw on a related note: The docs make it look like you need Docker to build the font, but that is not actually the case, right?

**Comment by be5invis** [comment]
Docker is optional.
