### ISSUE TITLE
Linux package

### ISSUE THREAD

**Issue by firedev** [be5invis/Iosevka#208]
Just a suggestion, someone made a homebrew formula #174 would be great to be able to install it using `apt` on linux.

**Comment by be5invis** [comment]
@firedev 
I am not very familiar with Debian's publishing system.
There are someone are maintaining packages for various package managers (like Arch's). Maybe I should let some people to do that.

ps. that PR is `H e b r e w`, not `H o m e b r e w`...

**Comment by be5invis** [comment]
cc @robertgzr
ps. @robertgzr your tap script need some update...

**Comment by AndydeCleyre** [comment]
[pkgbuild on the AUR](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ttf-iosevka-custom-git), in case it's helpful for packagers.

**Comment by jpotier** [comment]
[nix derivation in nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/data/fonts/iosevka/default.nix), in case it helps too

**Comment by robertgzr** [comment]
Not sure if this is the right place to put it but my [Homebrew formula](https://github.com/robertgzr/homebrew-tap#iosevkarb) now supports all customization options listed [here](https://github.com/be5invis/iosevka#build-your-own-style), including support for building webfonts.

**Comment by alexmyczko** [comment]
http://aiei.ch/deb/
