### ISSUE TITLE
Noval variant for digit 6, 8 and 9

### ISSUE THREAD

**Issue by halftwo** [be5invis/Iosevka#2082]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [ ] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------
Now that we have zero with top-right-cutout, we can do this to digit 6, 8 and 9, like this: 
![0689](https://github.com/be5invis/Iosevka/assets/26536535/a7866304-6c61-47fe-94f4-d15bd503f7e9)
By doing this, all the digits [0-9] will have no enclosed space. This may be useful in some circumstances, like painting template, etc.

**Comment by Logo121** [comment]
Having stencil-like style isn't really what that zero variant is for though... (These don't exactly look easy to make either)

I don't think there's good justification unless there are more confusable pairs than can be resolved by these, or if there are other monospace fonts actually doing this (i.e. the third checkbox).

**Comment by halftwo** [comment]
One of the reasons that iosevka is loved by users is it's customizable. It attract users because it's unique, it has some features, some glyph variants that other fonts don't have. It should not be a decisive reason to accept or reject a variant that other fonts don't support some variants. It's usefulness which is important. If iosevka provides some features that other fonts don't have, it's a win for iosevka, which can be used in more circumstances, used by more users, appeared in more places.

Users need monospace/programming fonts, they also want the fonts to be attractive, to be cool. Digit 8 have only 3 variants, digit 6 and 9 are the same. There can be more styles chosen by users considering the occurrence frequency of digits in programming codes.

**Comment by Logo121** [comment]
"it looks cool" is not a usefulness. A line has to be drawn somewhere for the variants we accept since there *is* a limit of how many glyphs one can add to a single font (one new variant does not necessarily equal to one more glyph especially for ASCII characters).  

Under the current build mechanism*, *every variant* has to be built in the main font(s) (which means all the width variants, italic, weights, etc), which further adds a cost to supporting arbitrary variants that just "looks cool".

(*: At least that's what I assume, correct me if I'm wrong)

**Comment by halftwo** [comment]
It's to me and maybe some other users, what makes a font different than the others is the looking and feeling. If that's not the case, we only need one font for all the work.

But if it's a big burden to add some variants to the ASCII characters into the already huge code base of iosevka，I can understand it.

**Comment by fabiorug** [comment]
I agree to do a 56% less taller and 46% less wider variant

**Comment by fabiorug** [comment]
So do 2 variants.

**Comment by fabiorug** [comment]
Could be Made 60% smaller and 36% less curved
