### ISSUE TITLE
Serifed (or serif-like) inward hooks (at least for `a`)

### ISSUE THREAD

**Issue by Logo121** [be5invis/Iosevka#2085]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

Kind of a leftover request stemmed from #1489, but basically there are quite a number of serif fonts (especially slab-serif, though mostly non-monospace) that treats teardrops terminals or inward hooks as serifs
![image](https://github.com/be5invis/Iosevka/assets/21302803/40497a71-2a96-4704-9e94-091b67fa6d2a)
and sometimes even "hypercorrecting" them as outward serifs
![image](https://github.com/be5invis/Iosevka/assets/21302803/cd2fbd2f-6efb-4d86-b2b2-2eb763ccf59b)
though the latter is much rarer.

But this request is mostly motivated by the fresh and hot Monaspace font, which in its "slab serif" variant, seems to consistently have serifs for inner hooks (or even just consider inner hooks and serifs the "same shape")
![image](https://github.com/be5invis/Iosevka/assets/21302803/72a527d5-bc85-41c4-a0bb-f9cdf49220d8)
(in a more "normal" serif font, only `c` and `s` will be serifed)

I don't personally think that all of them are needed, some of them do seem common enough that they can reasonably be added as variants.

Going off the programmingfonts.org list again:
![image](https://github.com/be5invis/Iosevka/assets/21302803/c7070a59-bb2d-44f6-9935-7d2c4bc4862c)
~~It seems like that `r` is the most common character to have a sharp "cornered" bend on the hook, making it more like a serif. This particular variant appears across different styles.~~ `r` is already implemented.

This is followed by `f`, and then `aj23569` with a few fonts making all of them have serif-like.  
I suggest `a` over the rest because it seems to me that in slab-serif fonts, it is actually more common to see a serifed hook `a` than what's represented by that list. A quick glance through [some slab-serif font catalog](https://www.fontspring.com/tag/slab-serif/) will give you a good enough idea on that.

---
Here are some fonts from fontspring for further reference:
Myrma (`fjy`):
![image](https://github.com/be5invis/Iosevka/assets/21302803/f77c9259-b6e8-431d-92b1-43e33d69327e)
Colon Mono (`23`):
![image](https://github.com/be5invis/Iosevka/assets/21302803/35ee4a0f-54a7-4795-8a4b-3077e498d317)
Electrica (`235afjy`):
![image](https://github.com/be5invis/Iosevka/assets/21302803/49f53a79-b352-4c23-84aa-922eb00edbbf)
NK57 Monospace (`236af`):
![image](https://github.com/be5invis/Iosevka/assets/21302803/ce4d61e1-2519-4e30-9d69-bcf5a4c3b3eb)

Non-monospace:
Aargau Pro (`23569ae`):
![image](https://github.com/be5invis/Iosevka/assets/21302803/c92fda2b-0dae-4a03-a08c-df50eb957614)
Lev Serif (`235ae`):
![image](https://github.com/be5invis/Iosevka/assets/21302803/21cbcf00-4320-4a60-b06f-ed6439e38509)
Enschede Serial (`23569aefjt`):
![image](https://github.com/be5invis/Iosevka/assets/21302803/5072d0f4-230d-410f-a84f-d3aa32ac8749)

---
* My main request is a serifed-hook variant for `a`, and *maybe* `f`
* The rest of `j23569` or maybe even `eyJ` can be considered
* "Outward serifs" for inner hooks are not considered here (I can't find a monospace font with them yet) but I guess we technically have them thanks to those schwa changes:
![image](https://github.com/be5invis/Iosevka/assets/21302803/e750ca93-f60b-4e32-9c27-464ab49dbcbc)
* Some other characters outside ASCII might also be able to take such a shape (e.g. lambda ![image](https://github.com/be5invis/Iosevka/assets/21302803/9c5e4f4e-9b72-4dce-ad9f-552a78fea07d)) but those are not thoroughly searched. Ignore those for now.

**Comment by be5invis** [comment]
Aren't we already have tri-serifed `r`?

![image](https://github.com/be5invis/Iosevka/assets/240091/05dde220-9476-40c1-84fe-06c95142f8ad)

Perhaps only need to add for (double-storey) `a` and digits...

**Comment by Logo121** [comment]
> Aren't we already have tri-serifed `r`?

Oh shit I missed that. Forget about the `r` part.

**Comment by be5invis** [comment]
I will do `a`. Digits are other topic (will involving adding serif variants to all digits...)
