### ISSUE TITLE
Request to rename a section of lower `m` serif variants.

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#2087]
For eared variants:

`m = "top-left-and-bottom-right-serifed"` → `m = "motion-serifed"`.
`m = "tailed-top-left-serifed"` →  `m = "tailed-motion-serifed"`.

`m = "short-leg-top-left-and-bottom-right-serifed"` → `m = "short-leg-motion-serifed"`.
`m = "short-leg-tailed-top-left-serifed"` → `m = "short-leg-tailed-motion-serifed"`.

For earless variants:

`m = "earless-corner-double-arch-bottom-right-serifed"` → `m = "earless-corner-double-arch-motion-serifed"`.
`m = "earless-corner-double-arch-short-leg-bottom-right-serifed"` → `m = "earless-corner-double-arch-short-leg-motion-serifed"`.

`m = "earless-rounded-double-arch-bottom-right-serifed"` → `m = "earless-rounded-double-arch-motion-serifed"`.
`m = "earless-rounded-double-arch-short-leg-bottom-right-serifed"` → `m = "earless-rounded-double-arch-short-leg-motion-serifed"`.

`m = "earless-single-arch-bottom-right-serifed"` → `m = "earless-single-arch-motion-serifed"`.
`m = "earless-single-arch-short-leg-bottom-right-serifed"` → `m = "earless-single-arch-short-leg-motion-serifed"`.

**Comment by Logo121** [comment]
I have a question: What exactly *is* a motion serif anyway? Should it include both top-left and bottom-right serifs (where possible), or just the top left?

For example, at least, `x` has a "motion-serif" variant which is just the top left*, and there are a few cv descriptions that neither label top-left only nor top-left bottom-right serif forms as "motion serifs", and some variants that are described as "top-left and bottom-right serifs" but are internally "motion serifs".

(*: On that note, a "top-left bottom-right serif" form exists for `x` in code but it is not included in the variants.toml file?)

**Comment by jmcwilliams403** [comment]
> I have a question: What exactly _is_ a motion serif anyway? Should it include both top-left and bottom-right serifs (where possible), or just the top left?

I've always interpreted it to mean a sort of dynamic directional serif used primarily for italics to mimic the motion of handwriting, but that could be an overanalyzation.

> (*: On that note, a "top-left bottom-right serif" form exists for `x` in code but it is not included in the variants.toml file?)

Those are used for Greek Lower Chi.

**Comment by be5invis** [comment]
Actually I'd like something opposite: remove the "motion serif" name completely from the variant atlas, and use more specific (top-left serifed, bottom-right serifed, etc.) names.

**Comment by be5invis** [comment]
But for V28 I'd like to NOT rename variants -- I've broken too many things in this version.
