### ISSUE TITLE
Remaining bugs in Mordvin letters

### ISSUE THREAD

**Issue by Logo121** [be5invis/Iosevka#2089]
* Lha probably still needs width adjustments: 
![image](https://github.com/be5invis/Iosevka/assets/21302803/cc6b3fd9-8162-4547-8960-a6aee0b68698) ![image](https://github.com/be5invis/Iosevka/assets/21302803/c1a66683-9ab7-43cd-a226-c4d708ac26b9)
* Minor extrusion in small Rha in some settings:
![image](https://github.com/be5invis/Iosevka/assets/21302803/8d220697-ef18-4f7a-a3a2-0421f652b048)
* (optional?) E side of Yae on the narrowest setting has an extremely thin gap only visible when zoomed in:
![image](https://github.com/be5invis/Iosevka/assets/21302803/415b6681-8c4b-4521-9163-773c5e648c12)

Thanks for completing the rest of #2088 though

**Comment by be5invis** [comment]
I think I already fixed those in dev.
![image](https://github.com/be5invis/Iosevka/assets/240091/fb1d7c10-8343-4808-a4f6-6cecc621c628)
![image](https://github.com/be5invis/Iosevka/assets/240091/6be1e1ab-c52f-4f15-b287-35027d2c9fba)

Resolve as fixed.

**Comment by Logo121** [comment]
Huh. I tested that locally after syncing my fork with my computer, and those are the results I got.

 I wonder if some weird caching problem happened then, idk
