### ISSUE TITLE
Length of equal sign is too long?

### ISSUE THREAD

**Issue by lung-zijim** [be5invis/Iosevka#209]
OS: Ubuntu 16.04 LTS

When I "type ==  =1 ==.", then effect is below:
![screenshot from 2017-06-25 05-33-25](https://user-images.githubusercontent.com/3715588/27515033-597d957a-5968-11e7-90e4-7bf6707a8e8a.png)

**Comment by be5invis** [comment]
It is a **bug** in Ubuntu's terminal.
The terminal incorrectly handled ligatures.
Use Iosevka Term to avoid this problem.
Closed as external and duplicate.
