### ISSUE TITLE
Iosevka SS08 doesn't match PratmataPro with U+006C LATIN SMALL LETTER L symbol

### ISSUE THREAD

**Issue by vytenis-narusis-ns** [be5invis/Iosevka#2093]
Iosevka SS08 doesn't match PragmataPro on U+006C LATIN SMALL LETTER L character. On PragmataPro it has a serif at bottom left.

Iosevka SS08 
<img width="256" alt="Screenshot 2023-11-17 at 13 30 30" src="https://github.com/be5invis/Iosevka/assets/123733882/5e5bbaf3-e75e-4260-b79f-ab998492b080">

PragmataPro Essential (from Adobe Fonts), also matches screenshots in main page of font (https://fsd.it/shop/fonts/pragmatapro/)
<img width="240" alt="Screenshot 2023-11-17 at 13 30 39" src="https://github.com/be5invis/Iosevka/assets/123733882/043b5615-e26e-4072-996c-032f353637b0">

Seems like cv37 variant 6 would be a better match with shorter top and both serifs at the bottom.

---

* Your font version: (Release or git, version)
27.3.5
* Your font variant:
SS08
* Your operating system (name and version):
Mac OS 14.1.1
* Your application using Iosevka: 
Visual Studio Code

**Comment by jmcwilliams403** [comment]
You're using an older version of Pragmata Pro. The most recent version changes the `l`.

**Comment by vytenis-narusis-ns** [comment]
You are very right. Closing. Thanks!
