### ISSUE TITLE
使用pChart 2.0画饼图时，文字宽度不对

### ISSUE THREAD

**Issue by WanpengQian** [be5invis/Iosevka#21]
![2015-36-733-13-00373-cdr-pie](https://cloud.githubusercontent.com/assets/6359418/10428921/a69eb316-712f-11e5-9581-2aa2d345b987.png)
![2015-39-733-13-01174-sssr-pie](https://cloud.githubusercontent.com/assets/6359418/10428922/a7d8da22-712f-11e5-8106-a1711bb2996a.png)

上图是用Iosevka0.1.14画的图，下面是其他字体。发现宽度不对。
pChart是一个使用php来进行画图的工具。主页如下
http://www.pchart.net/

**Comment by be5invis** [comment]
Maybe a pChart issue. Perhaps it thinks every character is 1em wide because the widest characters are full width.

**Comment by WanpengQian** [comment]
for my understanding, it is a monospace font, should evey character has the same width?

**Comment by be5invis** [comment]
There are many monospaced typefaces contains double-width even triple-width glyphs, for CJK or ligatures.

**Comment by WanpengQian** [comment]
A monospaced font, also called a fixed-pitch, fixed-width, or non-proportional font, is a font whose letters and characters each occupy the same amount of horizontal space.

Quoted from wikipedia.

I know Iosevka is for western languages, not for CJK.
Am I correct?

**Comment by be5invis** [comment]
However there ARE some typefaces contain wider characters, for example, Fira Code, contains double-width and triple-width ligatures.
Perhaps I can release a derived version with only half-width glyphs.

**Comment by Arthur2e5** [comment]
Have you reported this problem to pChart yet?

**Comment by be5invis** [comment]
@WanpengQian I think fixing #34 may fix this issue either. Could you please update to the newest release (1.0.2) and test whether this version works?
