### ISSUE TITLE
Instructions for manually build inziu iosevka?

### ISSUE THREAD

**Issue by nightire** [be5invis/Iosevka#210]
* Your font version: 1.13.1
* Your font variant: Inziu Iosevka
* Your operating system (name and version): macOS 10.12
* Your application using Iosevka: emacs

It's nearly impossible to adjusting line spacing properly in emacs (doesn't matter what font you're using), one reasonable way is to use a customized font. Unfortunately, there's only an instruction for build Iosevka, but not for Inziu Iosevka. Can we have an instruction dedicate to how to build a customized version of Inziu Iosevka?

Besides, [input font has its own online customizing feature](http://input.fontbureau.com/preview/?size=14&language=python&theme=solarized-dark&family=InputSans&width=300&weight=300&line-height=1.2&a=0&g=0&i=0&l=0&zero=0&asterisk=0&braces=0&preset=default&customize=please) which I think is very convinent, it would be better if Iosevka will provide a similar feature, please? 😸

**Comment by be5invis** [comment]
Inziu's building sequence is a **total disaster**. I do not want to share that out.
I'd like to start another project *Sarasa* to give you ability to do that.
Closed as external.

ps. You should file a bug to Emacs to let them give you ability to adjust line height.

**Comment by nightire** [comment]
Nice, good to hear that.
