### ISSUE TITLE
Add Ꝡꝡ (a760, a761)

### ISSUE THREAD

**Issue by berrymot** [be5invis/Iosevka#2112]
- The requested characters are ...
  - [x] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [ ] Diacritic / Mark
  - [ ] Symbol
- The requested characters are used in ...
  - [ ] The alphabet / character set of a natural language.
  - [x] The alphabet / character set of a constructed language.
  - [ ] The alphabet / character set of a transliteration or notation system.
  - [ ] Mathematical or other professional use in documents.
  - [ ] The symbol set of a programming language. For the languages that support using arbitrary symbols, please provide usages in well-known components or libraries.
  - [ ] The symbol set of a command-line program.
- [x] Some other monospace/programming fonts supported this character. Provide images below.

------

Used in Toaq for /w~j/ and apparently also /y:/ in Old Norse.

Noto Sans Mono 
![image](https://github.com/be5invis/Iosevka/assets/50974538/159b2308-8557-407e-92e1-61dce11f81d5)

Everson Mono 
![image](https://github.com/be5invis/Iosevka/assets/50974538/26fd86f4-43b6-4a70-ba31-2609d4d418ea)

I'm leaning towards these being linked with the variants for *v* **and** *w* (middle height) **and** *y* - wdyt

**Comment by jmcwilliams403** [comment]
Subset of #1689

**Comment by be5invis** [comment]
Resolve as duplicate
