### ISSUE TITLE
Possible adjustment of length of serifs for `capital-j`=`serifed-both-sides` under monospace and `capital-j`=`serifed-symmetric` under quasi-proportional.

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#2113]
Below are four examples of `Ĳ` (`U+0132`):

1. `NWID`=`1`, `capital-i`=`serifed`, `capital-j`=`serifed-both-sides`.
2. `WWID`=`1`, `capital-i`=`serifed`, `capital-j`=`serifed-both-sides`.
3. `NWID`=`1`, `capital-i`=`short-serifed`, `capital-j`=`serifed-symmetric`.
4. `WWID`=`1`, `capital-i`=`short-serifed`, `capital-j`=`serifed-symmetric`.

Under monospace, notice how `J` has shorter serifs than `I` under examples 1 and 2, but examples 3 and 4 are fine:
![image](https://github.com/be5invis/Iosevka/assets/37010132/5adeeba8-399f-40ac-9aee-0c3a46997341)
Under quasi-proporitonal, notice how `J` has longer serifs than `I` under examples 3 and 4, but examples 1 and 2 are fine:
![image](https://github.com/be5invis/Iosevka/assets/37010132/f3ab6e2d-2d54-4897-b0a0-cccfd36d6478)

I think `capital-j`=`serifed-both-sides` should have slightly longer serifs under monospace to match `capital-i`=`serifed`, and `capital-j`=`serifed-symmetric` should have slightly shorter serifs under quasi-proportional to match `capital-i`=`short-serifed`.

**Comment by fabiorug** [comment]
First is the best but the 2 number isn't fine

**Comment by jmcwilliams403** [comment]
Closing because the behavior has been improved in 29.0.0 as a side effect of switching to a six width system.
