### ISSUE TITLE
Distinguishing ß and capital ẞ

### ISSUE THREAD

**Issue by Markus00000** [be5invis/Iosevka#212]
* Your font version: 1.13.1
* Your font variant: any

---

These two characters look identical:

U+00DF ß LATIN SMALL LETTER SHARP S
U+1E9E ẞ LATIN CAPITAL LETTER SHARP S

Quoting Wikipedia:

> In 2016, the Council for German Orthography proposed the introduction of optional use of ẞ in its ruleset (i.e. variants STRASSE vs. STRAẞE would be accepted as equally valid). The rule was officially adopted in 2017.

https://en.wikipedia.org/wiki/%C3%9F
https://en.wikipedia.org/wiki/Capital_%E1%BA%9E

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/27761733-677a64ce-5e94-11e7-9860-e5436891d538.png)
![image](https://user-images.githubusercontent.com/240091/27761734-703a80c6-5e94-11e7-919e-c3b41ae57e08.png)
What's your ideas about thancing them?
NOTE: eszet was designed as 
![image](https://user-images.githubusercontent.com/240091/27761737-9b568f48-5e94-11e7-8a10-3b5cb6d21e77.png)

**Comment by hastebrot** [comment]
The first one for U+00DF and the third one for U+1E9E would be nice. The second one looks strange to my eyes.

**Comment by Markus00000** [comment]
In addition to the straight line in the capital ẞ, most typefaces make it wider, similar to kK:

![screenshot_2017-07-02_09-33-14](https://user-images.githubusercontent.com/985977/27768045-750fe984-5f01-11e7-8e76-5bf6cac5b342.png)
![screenshot_2017-07-02_09-33-42](https://user-images.githubusercontent.com/985977/27768046-75343a32-5f01-11e7-8450-512ddc857d8c.png)
![screenshot_2017-07-02_09-35-10](https://user-images.githubusercontent.com/985977/27768048-7538338a-5f01-11e7-8e2f-b7ca6692a272.png)
![screenshot_2017-07-02_09-35-35](https://user-images.githubusercontent.com/985977/27768047-7536d2c4-5f01-11e7-8f9e-3381f463dbcb.png)

**Comment by be5invis** [comment]
@Markus00000 However Iosevka is a **narrow, monospace font**.
I'll try to make its top more flat to distinguish.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/27768156-8d983c52-5f3f-11e7-9b02-4e9343596af1.png)
Looks better, just need some proportion refinements

**Comment by Markus00000** [comment]
My examples weren’t well chosen to make my point. What I had in mind was to make the capital look larger within the constraints of narrow and monospace.

And you already achieved exactly that! The flatter top bar seems like an excellent solution to make the letters easier to distinguish and to make the capital look larger.
