### ISSUE TITLE
Modified uppercase letters in the SS14 variant appear to have incorrect height

### ISSUE THREAD

**Issue by slashdevslashurandom** [be5invis/Iosevka#2129]
Another possible hinting issue to investigate: when the SS14 variant is used, certain uppercase letters may appear taller than others. 

Here's a GIF displaying the uppercase Latin alphabet with the SS14 variant (above) and without it (below). Red lines have been added at the baseline and cap height. The characters G, J, K, Q and W all happen to go over the cap height in the SS14 variant.

![example](https://github.com/be5invis/Iosevka/assets/53902042/435c4ed4-083c-435f-becb-a10864ddf967)

* Your font version: 27.3.5
* Your font variant: Iosevka Term, with SS14 variant enabled
* Your operating system (name and version): Alpine Linux v3.19
* Your application using Iosevka: foot

**Comment by fabiorug** [comment]
The J is not ok

**Comment by be5invis** [comment]
Unable to repro... at least with built-in hints.

20ppem
![image](https://github.com/be5invis/Iosevka/assets/240091/e4073ebe-25ff-48a1-bf4e-c8e89d938fd1)

24ppem (which should be your size)
![image](https://github.com/be5invis/Iosevka/assets/240091/f31fa6d2-0611-42fd-ae57-6a87bfa4b913)

**Comment by slashdevslashurandom** [comment]
Note: I see the effect when I use the default Iosevka font with the SS14 variant enabled via font options(e.g. the `foot` terminal being set to `font=Iosevka Term:size=16:fontfeatures=ss14`), and don't see it if I use a font with the SS14 variant pre-applied (e.g. `font=Iosevka Term SS14:size=16`).

**Comment by be5invis** [comment]
@slashdevslashurandom I was testing using that method (normal Iosevka with SS14 applied).
If you are using freetype, you can maybe enable the "application hints" instead of autohinting -- which could get better results.
