### ISSUE TITLE
Using inziu in Microsoft visio 2007, when save as PDF, visio will stop working.

### ISSUE THREAD

**Issue by WanpengQian** [be5invis/Iosevka#213]
* Your font version: (inziu-iosevka-1.13.1)
* Your font variant: inziu-SC-regular.ttc
* Your operating system (Windows 7 Pro EN):
* Your application using Iosevka: (Visio 2007 with SP3)

Describe your problem here. Provide pictures and files if necessary.

I can use Inziu Iosevka SC in visio 2007 vsd file. 
after doing that. I save vsd file as pdf, and visio will stop working.
![image](https://user-images.githubusercontent.com/6359418/27893468-c133ef80-6240-11e7-8218-7eb3a3a9e1b8.png)

when I uninstall inziu-SC-regular from windows font directory, 
I can save same vsd file to pdf without problem.
(of course, missing inziu-SC-regular will fallback to simsun)

**Comment by WanpengQian** [comment]
Using inziu font will not always trigger this situation, but when this situation happens, I can workaround by uninstall font. 
I think there are some connections between inziu and visio 2007

**Comment by be5invis** [comment]
Office' PDF driver is always broken. It simply doesn't like me.
Anyway INZIU would be discontinued soon and moved into https://github.com/be5invis/Iosevka-Sarasa. I'd like to use a completely new building script to handle that.
