### ISSUE TITLE
Is it possible to get a bit wider version?

### ISSUE THREAD

**Issue by mmrath** [be5invis/Iosevka#214]
Is is possible to provide a download option for a bit wider version of characters? Feel free to close it if you don't have any plans to do this.

**Comment by robertgzr** [comment]
There are compressed and expanded versions. See #180 and #196 
You will need to build Iosevka with a `style selector`.

What platform are you on?

**Comment by be5invis** [comment]
Merged into #196. Closed.

**Comment by mmrath** [comment]
I'll try to build on Mac today

**Comment by robertgzr** [comment]
@mmrath you can use [this homebrew formula](https://github.com/robertgzr/homebrew-tap/blob/master/iosevka.rb). If you pass the `--with-experimental-expanded` flag it should do everything for you.
