### ISSUE TITLE
Inapproprate glyph for LATIN SMALL LETTER FENG DIGRAPH when `n`=`earless-corner-serifed` or `n`=`earless-rounded-serifed`

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#2143]
`ʩ`
Problem glyphs:
![image](https://github.com/be5invis/Iosevka/assets/37010132/1f146867-9e3f-404c-bbf0-0fad47b2facc)
I think it would be more consistent and stable if the `ŋ` part were always eared and had a permanent connecting bar that reached over to `f` instead of having a top-left serif that only sometimes closes the gap.
Simulation of that:
![image](https://github.com/be5invis/Iosevka/assets/37010132/0f69ab16-0613-438d-9161-8b05a610070f)

**Comment by be5invis** [comment]
Preserving the low-contrast shape is requested by #1085:

> It might not be appropriate for the earless variants to completely remove the right component’s ear, because the ear is part of the ligation stroke to the left component, but the earless variants can still apply to feng, because the earless variants have a low-contrast stroke at the top left instead of the default, relatively high-contrast stroke.
