### ISSUE TITLE
2nd, 3rd and 4th hyphens too thin when chained in 28.0.0+

### ISSUE THREAD

**Issue by rhenescu** [be5invis/Iosevka#2147]
In 28.0.0+ the 2nd, 3rd and 4th hyphens in a chain appear too thin vs the rest (3rd row and onwards, zoomed in 200%):

![image](https://github.com/be5invis/Iosevka/assets/6264315/7b6f3dd9-2966-45f6-b2db-4f2c118d1094)

Also, the 1st hyphen is slightly thinner than the 5th+ (visible in the image above when zooming in even more, without smoothing). Maybe it's related to the changes in #2100? 27.3.5 and lower are not affected by this.

---

* Your font version: 28.0.0+
* Your font variant: Iosevka Term Curly, `"editor.fontSize": 18,`
* Your operating system (name and version): Linux Mint 21.2
* Your application using Iosevka: Visual Studio Code

**Comment by rhenescu** [comment]
Also in xed:

![image](https://github.com/be5invis/Iosevka/assets/6264315/c266ddd4-d5f2-49a9-a997-b1ab9811e1df)

---

* Your font version: 28.0.0+
* Your font variant: Iosevka Term Curly 14
* Your operating system (name and version): Linux Mint 21.2
* Your application using Iosevka: xed

**Comment by be5invis** [comment]
You can try the unhinted version, which should be more consistent.

**Comment by be5invis** [comment]
I really hope @lemzwerg could allow defining **CUSTOM** scripts (with **CUSTOM(( alignment zones, and the glyph IDs to measure them) in TTFA, which will be very helpful for handling symbols.

**Comment by lemzwerg** [comment]
I would be glad if you could provide a patch.  Right now, I'm working on completely different projects, not taking any time for TTFautohint...
