### ISSUE TITLE
Adjustment of serifs for `cyrl-{yery|yeri}` = `corner` under Slab Italic.

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#2151]
`ъ ы ы ь`
Slab Upright for reference:
![image](https://github.com/be5invis/Iosevka/assets/37010132/1e0add38-9e4f-456f-986f-ceae2fe539cd)
Under italics, these serifs should be removed if they're still using `corner` or `corner-tailed`:
![image](https://github.com/be5invis/Iosevka/assets/37010132/09e78180-7a78-4ee2-b727-549f5de0a9d3)
However, the capitals should remain unchanged:
`Ъ Ы Ы Ь`
![image](https://github.com/be5invis/Iosevka/assets/37010132/b4875ed7-28b3-418c-9dca-bbfaf420a8ad)

**Comment by jmcwilliams403** [comment]
It seems like you've mistakenly enabled the italic serifs for yery under upright as well:
`ы`
![image](https://github.com/be5invis/Iosevka/assets/37010132/cbf3b30e-f1c3-4499-80a8-1602f04c329c)

**Comment by jmcwilliams403** [comment]
> It seems like you've mistakenly enabled the italic serifs for yery under upright as well: `ы`

I'm not sure if I'd know how to fix it myself if I were to attempt it.

**Comment by be5invis** [comment]
Fixed
