### ISSUE TITLE
Narrower glyphs without condensing character spacing

### ISSUE THREAD

**Issue by vicch** [be5invis/Iosevka#2156]
**Is your feature request related to a problem? Please describe.**
I'm trying to make a custom build with condensed widths for the glyphs but not the spacing. From what I understand and currently observe, with build plan like this:

```
[buildPlans.IosevkaCustom.widths.Condensed]
shape = 416           # Unit Width, measured in 1/1000 em. 
menu  = 3             # Width grade for the font's names.
css   = "condensed"   # "font-stretch' property of webfont CSS.
```

The glyph widths and spacing are condensed equally (if not the spacing actually being condensed more than the glyphs), and the result is not very satisfactory to me as the glyphs are rather squeezed together.

**Describe the solution you'd like**
Way to customize the build so the glyph widths and spacing can be scaled separately. There might be a way to do so already via the custom build parameters that I'm just missing, in which case I'd like to know how.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by vicch** [comment]
I think it's achieved with:

```
[buildPlans.Iosevka2024.metricOverride]
sb = 'default_sb * 1.25'
```

In combination with the width being as small as possible (416 atm).

**Comment by fabiorug** [comment]
Re opened This.

**Comment by fabiorug** [comment]
Closed
