### ISSUE TITLE
curl: no URL specified

### ISSUE THREAD

**Issue by D10f** [be5invis/Iosevka#2159]
Following the manual installation method for Linux, using the provided terminal command:
```
curl -s 'https://api.github.com/repos/be5invis/Iosevka/releases/latest' | jq -r ".assets[] | .browser_download_url" | grep ttf-iosevka | xargs -n 1 curl -L -O --fail --silent --show-error
```
results in the following error:
```
curl: no URL specified!
```
It seems that the releases pages doesn't contain any files matching the grep expression, as I don't get any results in the terminal after running that.

**Comment by Logo121** [comment]
this is because of the name convention change (#2029), so that command probably didn't get updated to reflect that yet.

it is probably enough to just change `grep ttf-iosevka` to `grep TTF-Iosevka`.

**Comment by D10f** [comment]
I read about that change and thought the same but I wasn't really sure. I've tried with the change you suggested but this results in a new error:
```
curl: (3) bad range in URL position 68:
https://github.com/be5invis/Iosevka/releases/download/v28.0.4/PkgTTF-IosevkaTermSS18-28.0.4.zip
                                                                   ^
```
This time the error message appears multiple times, I assume once per file.

**Comment by Logo121** [comment]
hmmmm. I can't seem to reproduce that. Trying to downloading just the one you mentioned (the last match from grep) with
```
curl -s 'https://api.github.com/repos/be5invis/Iosevka/releases/latest' | jq -r ".assets[] | .browser_download_url" | grep TTF-Iosevka | tail -n 1 | xargs -n 1 curl -L -O --fail --silent --show-error
```
it works normally here.

**Comment by logiczny** [comment]
i just did
`curl -s 'https://api.github.com/repos/be5invis/Iosevka/releases/latest' | jq -r ".assets[] | .browser_download_url" | grep -i ttf-iosevka | xargs -n 1 curl -L -O --fail --silent --show-error`
so, the only difference is using `-i` in a grep command.

**Comment by D10f** [comment]
Not sure what could be wrong then, with the commands above with or without the `-i` flag for `grep` I keep getting this error:

![iosevka](https://github.com/be5invis/Iosevka/assets/48509601/082bef17-f498-4f13-912b-393fc9b2e618)

Here's my version of `curl` and `jq` although I guess at this point it's clear the issue is on my end, so I'll mark this as closed. If someone has any insights please let me know, just curious now about what could be causing this:

```
curl --version

curl 7.88.1 (x86_64-pc-linux-gnu) libcurl/7.88.1 OpenSSL/3.0.11 zlib/1.2.13 brotli/1.0.9 zstd/1.5.4 libidn2/2.3.3 libpsl/0.21.2 (+libidn2/2.3.3) libssh2/1.10.0 nghttp2/1.52.0 librtmp/2.3 OpenLDAP/2.5.13
Release-Date: 2023-02-20, security patched: 7.88.1-10+deb12u5
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd
```
```
jq --version

jq-1.6
```

**Comment by Logo121** [comment]
looks like you have grep with coloring on? try using `grep --color=never TTF-Iosevka` instead.

**Comment by D10f** [comment]
That worked! Also with `grep --color=auto`. Although this brings so many questions for me, how would the color affect the ability to filter text? But thank you very much for the help!
