### ISSUE TITLE
Brackets only partly visible.

### ISSUE THREAD

**Issue by WestFlame** [be5invis/Iosevka#216]
* Your font version: 1.13.2
* Your font variant: Default
* Your operating system (name and version): Ubuntu 16.04
* Your application using Iosevka: Atom

In Atom, with font size set to 13 and line spacing 1.0 (or even 1.1), the brackets are rendered without top line. Other fonts (e.g. PragmataPro) are rendering fine.

line spacing 1.0:
![atom1](https://user-images.githubusercontent.com/1949300/28961877-283cb200-7904-11e7-84d8-419bbec939c3.png)

line spacing 1.2:
![atom2](https://user-images.githubusercontent.com/1949300/28961886-2d607cf8-7904-11e7-9c93-cf2771c5334a.png)

**Comment by be5invis** [comment]
Looks like a line-height-caused cropping.
Perhaps you need to ask Atom not to crop the text even if the line height is very narrow.

**Comment by WestFlame** [comment]
Thanks for reply. But is it really problem with Atom? I've tried several other fonts and they are rendering fine.

**Comment by be5invis** [comment]
@WestFlame You can try to reduce the line height into a very small quantity and see whether other fonts are clipped either.

**Comment by WestFlame** [comment]
Then yes, if I reduce the line height under 1.0, then other fonts are also rendering cropped. You then suggest to raise the issue at the Atom?

**Comment by be5invis** [comment]
Right.

发自我的 iPhone

在 2017年8月5日，05:27，Mikulas Krupicka <notifications@github.com<mailto:notifications@github.com>> 写道：


Then yes, if I reduce the line height under 1.0, then other fonts are also rendering cropped. You then suggest to raise the issue at the Atom?

**Comment by WestFlame** [comment]
OK, will do. Thanks.
