### ISSUE TITLE
编译文档中Docker方式编译方法过期了

### ISSUE THREAD

**Issue by nobk** [be5invis/Iosevka#2163]
文档中[Docker方式](https://github.com/be5invis/Iosevka/blob/main/doc/custom-build.md#using-a-docker-container)目前已经失效。
读了一下Dockerfile，还在用版本14的Node.js，最新版本字体无法编译。
建议项目提供自带Dockerfile而不是链接到第三方，方便用户构建定制字体。

**Comment by be5invis** [comment]
I do not know how to use Docker. I will remove that section.

**Comment by nobk** [comment]
那你接受PR吗？我今天把Dockerfile重新调通了，可以提交PR，就两个文件，用了nodejs官方的Dockerfile做模版，版本20LTS

**Comment by be5invis** [comment]
@nobk You can do it

**Comment by nobk** [comment]
> I do not know how to use Docker. I will remove that section.

Don't worry, there are tons of users who know how to use Docker. Compiling with Docker is for custom font users, not for developers.
Supports Docker compilation, which is very beneficial for promoting fonts.
