### ISSUE TITLE
endd

### ISSUE THREAD

**Issue by fabiorug** [be5invis/Iosevka#2169]
git Dev https://github.com/be5invis/Iosevka/commit/384a6fb10e67ed31f47360abeb3f8e333b41569d

Generating 96 font names for Iosevka variations would be extensive, but here are a few examples:

1. Iosevka-Regular
2. Iosevka-Bold
3. Iosevka-Italic
4. Iosevka-Light
5. Iosevka-Condensed
6. Iosevka-Expanded
7. Iosevka-Medium
8. Iosevka-Narrow
9. Iosevka-Wide
10. Iosevka-Thin

You can modify these names to create more specific variations based on weight, style, or other attributes.
Creating 96 specific font names can be quite extensive, but here are additional examples for Iosevka variations:

11. Iosevka-ExtraLight
12. Iosevka-SemiBold
13. Iosevka-UltraCondensed
14. Iosevka-UltraExpanded
15. Iosevka-Heavy
16. Iosevka-Oblique
17. Iosevka-Book
18. Iosevka-DemiBold
19. Iosevka-ExtraBold
20. Iosevka-UltraWide
21. Iosevka-Black
22. Iosevka-CondensedBold
23. Iosevka-ExpandedBold
24. Iosevka-ExtraCondensed
25. Iosevka-ExtraExpanded
26. Iosevka-LightItalic
27. Iosevka-MediumItalic
28. Iosevka-NarrowBold
29. Iosevka-NarrowItalic
30. Iosevka-RegularItalic

You can continue this pattern, combining different attributes to create a variety of font names.

31. Iosevka-ObliqueBold
32. Iosevka-ObliqueItalic
33. Iosevka-CondensedItalic
34. Iosevka-ExpandedItalic
35. Iosevka-ExtraLightBold
36. Iosevka-ExtraLightItalic
37. Iosevka-SemiBoldItalic
38. Iosevka-UltraCondensedBold
39. Iosevka-UltraExpandedBold
40. Iosevka-HeavyItalic
41. Iosevka-BookBold
42. Iosevka-BookItalic
43. Iosevka-DemiBoldItalic
44. Iosevka-ExtraBoldItalic
45. Iosevka-UltraWideBold
46. Iosevka-UltraWideItalic
47. Iosevka-BlackBold
48. Iosevka-BlackItalic
49. Iosevka-CondensedBoldItalic
50. Iosevka-ExpandedBoldItalic
51. Iosevka-ExtraCondensedBold
52. Iosevka-ExtraCondensedItalic
53. Iosevka-ExtraExpandedBold
54. Iosevka-ExtraExpandedItalic
55. Iosevka-LightBold
56. Iosevka-LightItalicBold
57. Iosevka-MediumBold
58. Iosevka-MediumItalicBold
59. Iosevka-NarrowBoldItalic
60. Iosevka-NarrowItalicBold

Feel free to customize and create more variations based on your preferences.

61. Iosevka-ObliqueBoldItalic
62. Iosevka-ObliqueItalicBold
63. Iosevka-CondensedItalicBold
64. Iosevka-ExpandedItalicBold
65. Iosevka-ExtraLightBoldItalic
66. Iosevka-ExtraLightItalicBold
67. Iosevka-SemiBoldItalicBold
68. Iosevka-UltraCondensedBoldItalic
69. Iosevka-UltraExpandedBoldItalic
70. Iosevka-HeavyItalicBold
71. Iosevka-BookBoldItalic
72. Iosevka-BookItalicBold
73. Iosevka-DemiBoldItalicBold
74. Iosevka-ExtraBoldItalicBold
75. Iosevka-UltraWideBoldItalic
76. Iosevka-UltraWideItalicBold
77. Iosevka-BlackBoldItalic
78. Iosevka-BlackItalicBold
79. Iosevka-CondensedBoldItalicBold
80. Iosevka-ExpandedBoldItalicBold
81. Iosevka-ExtraCondensedBoldItalic
82. Iosevka-ExtraCondensedItalicBold
83. Iosevka-ExtraExpandedBoldItalic
84. Iosevka-ExtraExpandedItalicBold
85. Iosevka-LightBoldItalic
86. Iosevka-LightItalicBoldItalic
87. Iosevka-MediumBoldItalic
88. Iosevka-MediumItalicBoldItalic
89. Iosevka-NarrowBoldItalicBold
90. Iosevka-NarrowItalicBoldItalic

Feel free to mix and match attributes to create even more diverse font names.

91. Iosevka-ExtraBoldItalicBoldItalic
92. Iosevka-UltraWideBoldItalicBold
93. Iosevka-CondensedItalicBoldItalic
94. Iosevka-ExpandedItalicBoldItalic
95. Iosevka-ExtraLightBoldItalicBold
96. Iosevka-ExtraLightItalicBoldItalic

These variations combine different styles and weights. Feel free to adapt or modify them further based on your preferences.

Great! Here are more Iosevka font name variations up to 128:

97. Iosevka-SuperLight
98. Iosevka-ExtraHeavy
99. Iosevka-DemiCondensed
100. Iosevka-DemiExpanded
101. Iosevka-UltraThin
102. Iosevka-UltraThick
103. Iosevka-ObliqueLight
104. Iosevka-ObliqueBoldHeavy
105. Iosevka-CondensedThin
106. Iosevka-ExpandedThick
107. Iosevka-ExtraCondensedMedium
108. Iosevka-ExtraExpandedThin
109. Iosevka-LightThin
110. Iosevka-MediumHeavy
111. Iosevka-NarrowThin
112. Iosevka-NarrowHeavy
113. Iosevka-ThinLight
114. Iosevka-BoldThin
115. Iosevka-UltraWideThin
116. Iosevka-UltraWideHeavy
117. Iosevka-BlackThin
118. Iosevka-BlackHeavy
119. Iosevka-CondensedThinItalic
120. Iosevka-ExpandedThickItalic
121. Iosevka-ExtraCondensedMediumItalic
122. Iosevka-ExtraExpandedThinItalic
123. Iosevka-LightThinItalic
124. Iosevka-MediumHeavyItalic
125. Iosevka-NarrowThinItalic
126. Iosevka-NarrowHeavyItalic
127. Iosevka-ThinLightItalic
128. Iosevka-BoldThinItalic

Feel free to continue customizing based on your needs!

**Comment by fabiorug** [comment]
Can You do this in an hour?

**Comment by fabiorug** [comment]
Iosevka-ExtraLight Could you do the 11 56,8% smaller?

**Comment by be5invis** [comment]
Sorry I could not understand your demands.
If you are going to make custom builds, please refer to https://github.com/be5invis/Iosevka/blob/main/doc/custom-build.md.
Resolve as out of scope.
