### ISSUE TITLE
Superscript/Subscript/Overscript Cyrillic characters should obey localization forms of base letters.

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#2177]
Solving this issue would also improve upon #2175 for superscript Greek Lower Chi/Beta for IPA usage.
`δб𞀱 в𞀲 г𞀳 ɡgд𞀴 жӝӂҗ𞀶 иӥйҋ𞀸 к𞀹 п𞀽 т𞁀 Фф𞁂 ч𞁅 ицшщ𞀸𞁆 ъыь𞁇 ю𞁉`
Some examples I've found under Serbian/Macedonian:
![image](https://github.com/be5invis/Iosevka/assets/37010132/aabefa50-a117-4831-8eed-8e143d3bc259)
compared to Gentium Plus:
![image](https://github.com/be5invis/Iosevka/assets/37010132/8fbe3dba-e75f-4274-ae71-191391d0c59a)
Compared to Charis SIL:
![image](https://github.com/be5invis/Iosevka/assets/37010132/749a2f68-bdb3-4b4f-96e5-28168f78ed4b)

**Comment by be5invis** [comment]
I will not do this for letters with diacritics -- as some localizations already introduce diacritics.
