### ISSUE TITLE
How to pronounce "Iosevka"?

### ISSUE THREAD

**Issue by lizy14** [be5invis/Iosevka#219]
Is there an "official" pronunciation? @be5invis

**Comment by be5invis** [comment]
[ˌjɔˈseβ.kʰa]

**Comment by lizy14** [comment]
I realized that this has already been answered at https://www.zhihu.com/question/41453771/answer/91168668

Thanks!

**Comment by ArunGovil** [comment]
🗣️  `yo-SEV-ka`
