### ISSUE TITLE
关于字体变种的建议

### ISSUE THREAD

**Issue by MadMaxChow** [be5invis/Iosevka#22]
目前的字宽是标准半角的宽度，这个在传统的WINDOWS界面等显示兼容性好。
但作为代码编辑器这类应用又显得太窄了，建议参考一些英文字体那样，现在的半角可作为COMPACT版本，然后做一个更宽的作为WIDE版本或是标准版本。

**Comment by be5invis** [comment]
You can simply change the WIDTH parameter to build your own variant. Closed.
