### ISSUE TITLE
Ligatures display failed in Visual Studio 2017

### ISSUE THREAD

**Issue by MaoKwen** [be5invis/Iosevka#220]
* font version: Inziu Iosevka SC 1.13.2 ttf version
* font variant: 
* operating system: Windows 10
* application using Iosevka: Visual Studio 2017
---
Iosevka:
![image](https://user-images.githubusercontent.com/18361388/29770200-6557dc30-8c20-11e7-8448-497e1ef2b850.png)

Fira Code:
![image](https://user-images.githubusercontent.com/18361388/29770219-77e6c672-8c20-11e7-9dc6-831b91829d90.png)

**Comment by be5invis** [comment]
I did not included a ligature for `<=`. Such "breaking" ligatures would be introduced in the future, but not now.
Closed.

**Comment by Connorelsea** [comment]
Yeah, the math-related ligatures in JavaScript are failing for me in VSCode. Is there any chance this can be added soon? Or how I could do a custom build that includes these ligatures for JavaScript? Such as those for "<=", ">=", "==", "!==", "===" etc. Currently I am only seeing the "=>" ligature in VSCode
