### ISSUE TITLE
Large Type Piece U+1CE3B is wrong

### ISSUE THREAD

**Issue by PhMajerus** [be5invis/Iosevka#2206]
* Your font version: 28.1.0; ttfautohint (v1.8.4) from PkgTTC-Iosevka-28.1.0.zip
* Your font variant: Regular
* Your operating system (name and version): Win11 Pro x64 en-us
* Your application using Iosevka: Windows Terminal

Good job on including the Large Type Pieces, I've been experimenting with them as well and read through Unicode and original HP 2640 Series reference manual.

I noticed one of the piece is wrong, `U+1CE3B` is supposed to be the _upper left_ diagonal piece:
![image](https://github.com/be5invis/Iosevka/assets/25664275/cdf6bcf8-f279-4bec-8dff-003770be60ca)
![image](https://github.com/be5invis/Iosevka/assets/25664275/346fdb33-b77f-459f-9302-cc141c0d6211)
(From Unicode's 21235r-terminals-supplement.pdf)

It is mirrored and top-aligned in your font.
You can easily create that character from your correct _upper left and lower left_ `U+1CE38`, as it contains both the _upper left_ (`U+1CE3B`) and _lower left_ (`U+1CE22`) diagonals combined.

Here's the original HP 2640 Series reference chart using your font:
![image](https://github.com/be5invis/Iosevka/assets/25664275/ba0902ea-2b7b-4f19-ba52-0cfb39863761)

Every other piece seems correct, only occurrences of `U+1CE3B` are breaking the large characters.

For comparison, you can see the same chart using my glyphs here: https://github.com/microsoft/cascadia-code/issues/709

**Comment by be5invis** [comment]
@PhMajerus What's the program you used to demonstrate?

**Comment by be5invis** [comment]
@Logo121 FYI
