### ISSUE TITLE
Adjust the dots of lowercase i and j in iosevka-ss04 font

### ISSUE THREAD

**Issue by Zenvie** [be5invis/Iosevka#2208]
**Is your feature request related to a problem? Please describe.**
I would like to suggest a minor aesthetic improvement for the iosevka-ss04 font. I noticed that the dot of the lowercase letter i is tilted to the right, while the dot of the lowercase letter j is tilted to the left. It may not be obvious as a screen display font, but it is especially noticeable when the font is enlarged. I think it would look better if the dots were adjusted slightly.

**Describe the solution you'd like**
I have provided screenshots and drawn auxiliary lines to show how to adjust.
1. Based on the left and right lines of the lower part of the lowercase letter i, draw the approximate left and right lines of the upper part of the dot of the lowercase letter i, but this will make the dot too small, and it needs to be corrected in step 2.
2. Take the midpoint of the original right line of the upper part of the dot of the lowercase letter i and the theoretical right line of the upper part of the dot of the lowercase letter i, and get the position of the right line of the upper part of the dot of the lowercase letter i that should be designed. Then, based on the center line of the lower part of the lowercase letter i, determine the position of the left line of the upper part of the dot of the lowercase letter i that should be designed. 
3. Based on the size of the upper part of the dot of the lowercase letter i that has been designed in step 2, determine the size of the upper part of the dot of the lowercase letter j that should be designed. Then, based on the center line of the lower part of the lowercase letter j, determine the position of the upper part of the dot of the lowercase letter j.

**Describe alternatives you've considered**
I have not considered any alternative solutions or features, as this is a minor aesthetic improvement.

**Additional context**
Here is the screenshot with the guidelines:
![original](https://github.com/be5invis/Iosevka/assets/134689569/db6b5b9c-e0d1-481e-b8b0-f3f78f460478)
![modified](https://github.com/be5invis/Iosevka/assets/134689569/e449b493-3919-46f6-bdff-909b5df02cf9)

**Comment by be5invis** [comment]
I currently align the center of the dot to the center of the bottom stem.
Do you want them to have a small offset?

**Comment by Zenvie** [comment]
Yes.

**Comment by Zenvie** [comment]
The dot above the lowercase i is visually tilted to the right unless the dot size is reduced.

**Comment by Zenvie** [comment]
Notice that the dots above these two lowercase letters in the Menlo font are rectangles rather than squares. Perhaps changing them to rectangles would be better?
![menlo](https://github.com/be5invis/Iosevka/assets/134689569/7b89b8e0-784b-478d-8ba3-e33ee7a4b5eb)

**Comment by Zenvie** [comment]
@be5invis If there are any plans to implement this request?

**Comment by be5invis** [comment]
@Zenvie Dots' alignment is mostly "optical". In many cases, geometrically aligning them may make it PERCEPTUALLY unaligned.

The current logic of dot alignment in `i` and `j` (as in v29) is, if there's top serif, then the dot is aligned to the center of the bar. Otherwise it will be slightly leaning leftward.

**Comment by be5invis** [comment]
@Zenvie Such will become another variant of "dots in diacritics". I estimate this will introduce about 800 glyphs...

**Comment by jmcwilliams403** [comment]
FWIW some fonts use square dots for i/j while using round dots for everything else (characters which decompose to letter+diacritic), like Envy Code R and Courier New.
