### ISSUE TITLE
add angular “t”

### ISSUE THREAD

**Issue by flying-sheep** [be5invis/Iosevka#221]
The default “t” is rounded, which doesn’t fit if you e.g. use “zshaped”.

I’d like to have a t with a straight slab serif to the right like the zshaped “i” (did i say that correctly?)

**Comment by be5invis** [comment]
You mean this?
![image](https://cloud.githubusercontent.com/assets/240091/24497113/ed269258-156c-11e7-8e30-b2366710462d.png)

**Comment by flying-sheep** [comment]
exactly! the existing “t” variants don’t include that one:

![grafik](https://user-images.githubusercontent.com/291575/29962750-88ead698-8f04-11e7-972d-a19cda779b67.png)

**Comment by be5invis** [comment]
But such a "t" is very strange...
Consolidated into #140. Closed.
