### ISSUE TITLE
Octants (U+1CD00...U+1CDE5) are not the complete octants set

### ISSUE THREAD

**Issue by PhMajerus** [be5invis/Iosevka#2210]
You added the octants group `U+1CD00` to `U+1CDE5`, but those are only 230 of the 256 characters needed to represent all octant mosaic pattern.

![image](https://github.com/be5invis/Iosevka/assets/25664275/03357be5-eb38-427e-ab17-4dc2277d5349)
(Test file: `curl https://raw.githubusercontent.com/PhMajerus/ANSI-art/main/Unicode/Blocks%20tables.txt`)

As with other pseudo-pixels patters, they do not duplicate patterns that already exist as part of another group, so they reuse the half blocks and quadrants: ` `, `▘`, `▝`, `▀`, `▖`, `▌`, `▞`, `▛`, `▗`, `▚`, `▐`, `▜`, `▄`, `▙`, `▟`, `█`, as well as some one quarter blocks: `▂`, `▆`, `🮅` , `🮂` (from `U+1FB82`…`U+1FB86`).
But they also require 6 extra characters hidden in other groups of the legacy computing supplement block:

![image](https://github.com/be5invis/Iosevka/assets/25664275/72d172ff-3c7e-4942-a959-7be2d1f74856) ![image](https://github.com/be5invis/Iosevka/assets/25664275/981216be-ddb3-4fd7-a72a-7e8f8d00fcc5) ![image](https://github.com/be5invis/Iosevka/assets/25664275/6be03872-3e28-4ef9-a288-76fe687e18bb) ![image](https://github.com/be5invis/Iosevka/assets/25664275/d147cfb9-3a79-4eab-a553-7bcf50eb91ce) ![image](https://github.com/be5invis/Iosevka/assets/25664275/c5fc2279-2afd-4de0-9b6d-77e1fd698a58) ![image](https://github.com/be5invis/Iosevka/assets/25664275/24299d3d-c896-41e6-b702-4b2865b02580)

So you should add `U+1FBE6`, `U+1FBE7`, `U+1CEA0`, `U+1CEA3`, `U+1CEA8`, and `U+1CEAB` to complete the octants set.

**Comment by jmcwilliams403** [comment]
I believe those are already added in the dev branch.

**Comment by be5invis** [comment]
FYI @Logo121

**Comment by be5invis** [comment]
I checked `dev` and they are added there. Resolve as fixed.
