### ISSUE TITLE
There is not information about some variant new names in the Changelog

### ISSUE THREAD

**Issue by dehghani-mehdi** [be5invis/Iosevka#2216]
I upgraded from v18.x to the latest version and I realized that some variant names changed since v18, but I could not find relevant information about some of them in the change logs, for example, I could not find what the new name of `m,earless-corner-double-arch` is.

I checked all of [change logs](https://github.com/be5invis/Iosevka/tree/main/changes), btw.

**Comment by Logo121** [comment]
In 24.0.0, characters with serif variants now have the serif style specified in the variant name. [Changelog here](https://github.com/be5invis/Iosevka/blob/main/changes/archives/24.x/24.0.0.md)

So the new name is probably `earless-corner-double-arch-serifless`, unless you have other serif changes.

**Comment by dehghani-mehdi** [comment]
Thank you, but I could not go with _probably_, is there any way to make sure what is the new name of the variants?

**Comment by Logo121** [comment]
If you just want to confirm the name of a few specific variants, you can check https://github.com/be5invis/Iosevka/blob/main/doc/custom-build.md

But otherwise variant renames aren't really documented until after v24 (because someone pointed it out in #1970).  
For the v24 changes, a lot of the variant name changes actually depend on your other settings (serif or sans serif), so the "probably" is the best I can give you without more information.

**Comment by dehghani-mehdi** [comment]
Can you (as a contributor) say the new name of any old one? I mean if you can, so there should be a formula to doing that, if so, please explain what is it, if not, I think I should look for the specific variants one by one, by eye.

**Comment by alexeyten** [comment]
@dehghani-mehdi you can just choose one from https://typeof.net/Iosevka/customizer

![image](https://github.com/be5invis/Iosevka/assets/44377/5359a103-fd6d-417b-921c-e8f2928c0e05)

**Comment by dehghani-mehdi** [comment]
@alexeyten I know, I did that before, it's the last option, is there any better option? I think either you should document this kind of change, or the customizer should handle it.

**Comment by be5invis** [comment]
@dehghani-mehdi I started enforcing such documentation since v28 (after #1970 was filed). You can see in the v29 changelist, **ALL** variant renames are listed.

**Comment by be5invis** [comment]
For historical variant name changes, you can find the list of every (current) variants at [custom-build.md](https://github.com/be5invis/Iosevka/blob/main/doc/custom-build.md). Searching your old variant name usually gets you the results. For your `m` case, `earless-corner-double-arch` is separated into `earless-corner-double-arch-serifless` and `earless-corner-double-arch-serifed`: the first one is used when building sans-serif, and the second one is used to build serif fonts.

**Comment by Logo121** [comment]
Well, seeing how there are multiple requests for this now, I've manually compiled a list of changes I could gather from v23 to v28.1.0 (v18 is probably not that different from v23 except for some new variants). I can't guarantee its correctness (especially with Slab serif on) but this should get you somewhere to start with.

Follow this procedure if a variant **does not exist anymore**:
- If the character has serif variants but is not indicated in the old variant name, add `-serifed` or `-serifless` according to whether your customization is serifed or not. Note these special cases:
	- For `m`, the `normal` variant is just either `serifed` or `serifless`.
	- For `turn-v`, rename the character name to `capital-lambda`, then add the suffixes.
	- For `q`: 
		- If it is earless AND tailed, add `-serifless`. (cannot be serifed)
		- If it is tailed but not earless, add `-moition-serifed` or `-serifless`.
		- If it is earless but not tailed, add `-straight` before adding the suffixes.
		- If it is neither, add the suffixes normally.
	- For `long-s`, `eszet`:
		- If it is `-descending` or `-tailed`, add `-serifless`. (cannot be serifed)
		- Otherwise, add `-bottom-serifed` or `-serifless`.
	- For `f`, add `-serifed` or `-serifless` before `-crossbar-at-x-height` (if any).
	- For `7`, add (or move) `-serifed` or `-serifless` before `-crossbar` (if any). 
	- For `g`: (its problematic variants do not have serifs, no need to add them)
		- Prepend `single-storey-` if it is not already there.
		- Move `-earless-corner` or `-earless-rounded` after `-flat-hook` (if any).
	- For `lower-mu`, `micro-sign`, replace `tailless` with `toothed` before adding the suffices. (might not be needed for `lower-mu`)
- If the variant has `motion-serifed` in its name:
	- For `b`, `w`, replace `-motion-serifed` with `-serifed`.
	- For `R`, replace `-motion-serifed` with `-top-left-serifed`.
	- For `N`, prepend `standard-`.
	- For `U`, `u`, prepend `toothed-`. (applies to `u = 'bottom-right-serifed'` as well)
	- For `p`, prepend `eared-`.
- These characters have variant (component) name changes:
	- `asterisk`: replace `flip` with `turn`.
	- `at`: `short` is now called `compact`.
	- `5`: replace `-upper-left-bar` with `-arched`. (name shortened for new variant component)
	- `lower-alpha`: `tailed-barred` is now called `barred-tailed`.
	- `t`: replace `cross` with `hookless`, `standard` with `bent-hook`.
	- `0`: remove `-oval` and move it to the front (prepend `oval-`).

**Comment by dehghani-mehdi** [comment]
Thank you, with the help of [custom-build.md](https://github.com/be5invis/Iosevka/blob/main/doc/custom-build.md) and the instructions posted by @Logo121 _and my lovely eyes_ I could build Iosevka once again. I'll double-check my new `private-build-plans.toml` once the changelist of v29 comes out.
