### ISSUE TITLE
U+1FB95..U+1FB97 have blank glyphs

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#2218]
U+1FB95 CHECKER BOARD FILL, U+1FB96 INVERSE CHECKER BOARD FILL, and U+1FB97 HEAVY HORIZONTAL FILL have blank glyphs.

---

* Your font version: 29.0.0-beta.1
* Your font variant: Iosevka Slab Extended
* Your operating system: macOS 14.3.1
* Your application using Iosevka: hb-view

**Comment by Logo121** [comment]
i noticed this, will push PR to fix later
