### ISSUE TITLE
"==" displayed not right in ubuntu terminal.

### ISSUE THREAD

**Issue by EdwinHu233** [be5invis/Iosevka#222]
Font version: 1.13.3 release (ttf)
OS: Ubuntu 16.04

"==" displayed not right in Ubuntu default terminal and Guake when using Inziu Iosevka SC Regular. But it works fine in other editors.

Default terminal:
![Default](http://ov3who0xb.bkt.clouddn.com/2.jpg)

Guake:
![Guake](http://ov3who0xb.bkt.clouddn.com/3.jpg)

It works fine in Pycharm:
![Pycharm](http://ov3who0xb.bkt.clouddn.com/1.jpg)

**Comment by be5invis** [comment]
Some Linux apps cannot properly handle the substituted glyphs used by ligatures. You can try Iosevka Term instead.

发自我的 iPhone

在 2017年9月1日，19:21，Edwin <notifications@github.com<mailto:notifications@github.com>> 写道：


Font version: 1.13.3 release (ttf)
OS: Ubuntu 16.04

"==" displayed not right in Ubuntu default terminal and Guake when using Inziu Iosevka SC Regular. But it works fine in other editors.

Default terminal:
[Default]<https://camo.githubusercontent.com/cdf7e92311be30add022b03db25e02d249eea456/687474703a2f2f6f763377686f3078622e626b742e636c6f7564646e2e636f6d2f322e6a7067>

Guake:
[Guake]<https://camo.githubusercontent.com/b71d842f16c0f1d70dd025f2ef07755df3c19a8a/687474703a2f2f6f763377686f3078622e626b742e636c6f7564646e2e636f6d2f332e6a7067>

It works fine in Pycharm:
[Pycharm]<https://camo.githubusercontent.com/1a6bd722d7e3930345c4a2ce0f877c60ed32e4b5/687474703a2f2f6f763377686f3078622e626b742e636c6f7564646e2e636f6d2f312e6a7067>

**Comment by EdwinHu233** [comment]
Solved. Thanks!
