### ISSUE TITLE
Glyph adjustment for ligations `!=` and `!===`.

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#2234]
It would be nice if the middle notch in the `=` parts in the glyphs for `!=` and `!===` was eliminated (specifically for an even number of character cells wide) since it only just barely peeks out from behind the slash and looks kind of awkward:
```
!=
!==
!===
```
![image](https://github.com/be5invis/Iosevka/assets/37010132/3a6c6645-29af-4cb2-ba77-09df753b8536)

**Comment by be5invis** [comment]
Could make `VLAC` to influence them.

**Comment by be5invis** [comment]
OK I checked, `VLAC` already control them, so such notches should be considered a manner for `VLAC`'s consistency.

Resolve as by design
