### ISSUE TITLE
Eszett and lowercase beta look similar

### ISSUE THREAD

**Issue by abhiramakella** [be5invis/Iosevka#2236]
Eszett and lowercase beta look similar

**Comment by AndydeCleyre** [comment]
I find `eszet` as `longs-s-lig-tailed-serifless` very good for differentiation, within the Sulzbacher styles.

![image](https://github.com/be5invis/Iosevka/assets/1787385/5d7936dd-f14e-4302-a5bd-52c5f4c75072)

**Comment by jmcwilliams403** [comment]
> I find `eszet` as `longs-s-lig-tailed-serifless` very good for differentiation, within the Sulzbacher styles.

That's the style I use in my personal builds too.
