### ISSUE TITLE
Documentation for Linux install is incorrect

### ISSUE THREAD

**Issue by hackerb9** [be5invis/Iosevka#2239]
The README for Iosevka states that one can install for Linux by running a certain pipeline, but it does not work as there is no longer any such file `ttf-iosevka`. It looks like the correct syntax should now be:

    curl -s 'https://api.github.com/repos/be5invis/Iosevka/releases/latest' |
    	jq -r ".assets[] | .browser_download_url" | 
    	grep -i superttc-iosevka- |
    	xargs -n 1 curl -L -O --fail --silent --show-error

(Note the `-` at the end of `superttc-iosevka-`. Without it, it will also download all 24 different styles: Aile, Curly, CurlySlab, Etoile,...)

**Comment by be5invis** [comment]
Well this command is used to download ALL packages with a certain format, so not adding `-` is correct.
I will update it on v29.0.2 release.
