### ISSUE TITLE
电源按钮“⏻”的设计需微调，以及“℮”“✔”等问题。

### ISSUE THREAD

**Issue by MY1L** [be5invis/Iosevka#2243]
Describe your problem here. Provide pictures and files if necessary.

如[统一码文档](https://www.unicode.org/charts/PDF/U2300.pdf)所示，
![image](https://github.com/be5invis/Iosevka/assets/58043328/9c97c58c-535f-4bf4-b0d6-36b8c3dca838)

⏻由⏽和打开的⭘组成，但Iosevka的⏽太长和突出，且⭘打开程度不够，与⏽的交叉处应超出⏽的宽度，看起来不像实际存在的⏻。![image](https://github.com/be5invis/Iosevka/assets/58043328/1580c1f6-c5cc-4f82-86a3-49ae07eaf35b)

理想的造型是⏻呈现在一个虚拟的按钮内部，比如[我的字体](https://github.com/MY1L/Monu)里的![image](https://github.com/be5invis/Iosevka/assets/58043328/6d6859ad-8f03-454b-aa0e-9ce6cb3efbb4)
以及实物照片：
![image](https://github.com/be5invis/Iosevka/assets/58043328/628f631f-ee31-45ea-b2e6-fc09c7d27c47)![image](https://github.com/be5invis/Iosevka/assets/58043328/24a78e1d-3e13-475c-9eaf-ffb1759d7c30)
顺带发现百度搜图的退出按钮也是类似造型😂
![image](https://github.com/be5invis/Iosevka/assets/58043328/a98e533a-d470-46cd-a846-dbe9466c87dc)

---

℮没有窄体形式，Term版不应当变窄。
考虑到“℮”不属于行文内的字符：它被规定了印刷大小，且欧盟不仅严格规定了设计、还禁止可能与“℮”混淆的标志，我倒觉得不如删除，任其fallback到系统里既有的标志字体。

> [也许你应该了解的德国系列-包装标识篇之℮](https://www.douban.com/note/799801842/)
它并不是简单套用了某一个电脑文字处理软件中的字体，而是一个经过精确设计的图案[3]，其设计要求是明确写在一项欧洲准则 Richtlinie 2009/34/EG [4] 的附件二中。同时，该标识在产品包装上的大小和位置都有着明确规定，比如高度不得低于3毫米；必须伴随在净重标识左右等。

---

“全角”的✔相比✓和它后面的4个叉而言太矮了。![image](https://github.com/be5invis/Iosevka/assets/58043328/0559ae72-db2c-47e2-a8ba-9027135298dc)

理想的造型……比如[我的字体](https://github.com/MY1L/Monu)里的是
![image](https://github.com/be5invis/Iosevka/assets/58043328/bc201d18-3125-4a00-8e0b-53bd7ab572e4)

---

目前单个字体压缩包挺大，我以为有可变字体节省文件体积，但寻不着，搜了下发现有人问过（其中两人删号了）：
https://github.com/be5invis/Iosevka/issues/1040
https://github.com/be5invis/Iosevka/issues/351
https://github.com/be5invis/Iosevka/issues/300

看上去字形由运算而成，没有通常概念上可变字体能用的曲线，也没有3次曲线，这是技术上无法解决的吗？

---

* Your font version: Term 29.0.2

**Comment by be5invis** [comment]
For building OTV: If someday OT gets built-in support for **Booleans**, then I could consider add that (like an `wght` axis). However it doesn't for now, so a lot of glyph geometry simply cannot be converted into OTV's. OTV is also known hard to represent some shapes, like punching a hole over another glyph.
