### ISSUE TITLE
Add lowercase beta and its character variants.

### ISSUE THREAD

**Issue by abhiramakella** [be5invis/Iosevka#2248]
- The requested characters are ...
  - [ ] Latin
  - [ ] Cyrillic
  - [x] Greek
  - [ ] Punctuation
  - [ ] Diacritic / Mark
  - [ ] Symbol
- The requested characters are used in ...
  - [x] The alphabet / character set of a natural language.
  - [ ] The alphabet / character set of a constructed language.
  - [ ] The alphabet / character set of a transliteration or notation system.
  - [ ] Mathematical or other professional use in documents.
  - [ ] The symbol set of a programming language. For the languages that support using arbitrary symbols, please provide usages in well-known components or libraries.
  - [ ] The symbol set of a command-line program.
- [ ] Some other monospace/programming fonts supported this character. Provide images below.

------

*Please provide justification here.*
I noticed that the lowercase beta is missing. Also, make sure to add character variants of the lowercase beta.

**Comment by jmcwilliams403** [comment]
Lowercase beta is in the font, however most fonts don't really deviate from the default form, with the exception of Consolas letting it share an italic form with Cyrillic Ve.
