### ISSUE TITLE
Angle brackets are very sharp

### ISSUE THREAD

**Issue by glebd** [be5invis/Iosevka#226]
* Your font version: (Release or git, version) 1.13.3
* Your font variant: Expanded
* Your operating system (name and version): macOS Sierra 10.12.6

Starting with a recent release the angle brackets ('<' and '>') became very sharp. Would it be possible to have a less sharp version as a stylistic option? If not, is there a way to adjust the angle of angle brackets? Very sharp angle brackets render poorly on Windows (low-DPI screens) and consequently result in the arrow ligations that aren't as nice as before.

Thanks for a great programming font!

**Comment by be5invis** [comment]
It is a change about unifying angles among all kinds of similar glyphs (about 20 of them). Simply changing its angle would ruin other glyphs.
Actually I am controlling the slope of the diagonal lines, not the angel.

发自我的 iPhone

在 2017年9月20日，23:47，Gleb Dolgich <notifications@github.com<mailto:notifications@github.com>> 写道：


  *   Your font version: (Release or git, version) 1.13.3
  *   Your font variant: Expanded
  *   Your operating system (name and version): macOS Sierra 10.12.6

Starting with a recent release the angle brackets ('<' and '>') became very sharp. Would it be possible to have a less sharp version as a stylistic option? If not, is there a way to adjust the angle of angle brackets? Very sharp angle brackets render poorly on Windows (low-DPI screens) and consequently result in the arrow ligations that aren't as nice as before.

Thanks for a great programming font!
