### ISSUE TITLE
Building process terminated when building a custom variant.

### ISSUE THREAD

**Issue by futuremotiondev** [be5invis/Iosevka#2261]
I created a custom `private-build-plans.toml` with these contents:

```
[buildPlans.IosevkaFm]
family = "Iosevka FM"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false
noLigation = true

[buildPlans.IosevkaFm.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.IosevkaFm.widths.Extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.IosevkaFm.widths.SemiExtended]
shape = 548
menu = 6
css = "semi-expanded"

[buildPlans.IosevkaFm.widths.ExtraExtended]
shape = 658
menu = 8
css = "extra-expanded"

[buildPlans.IosevkaFm.widths.UltraExtended]
shape = 720
menu = 9
css = "ultra-expanded"
```

I then ran `npm run build -- contents::IosevkaFm`

Everything seemed to be working fine and fonts were generating. But about 5 minutes into the process I got `Building process terminated.` with no error message. Only a subset of the fonts were generated, all of them un-hinted TTF's. I wish I could provide you with more information to repro, but it simply just terminated with no additional explanation.

---

* Your font version: I cloned [7335e17](https://github.com/be5invis/Iosevka/commit/7335e178486fca019b9a9b3c709333791c9b0e92).
* Your font variant: Outlined in the `private-build-plans.toml` above.
* Your operating system (name and version): Windows 10 Pro x64 22H2 (OS Build 19045.4170)
* Your application using Iosevka: None, I'm just building a custom variant.

If you have problem when building Iosevka, please provide these information:

* Your Node.js version: 21.6.2
* Your `params/parameters.toml`, paste if modified:
  ```
  paste here
  ```
* Your `build-plans.toml`, paste if modified:
  ```
  paste here
  ```
* Your `private-build-plans.toml`, if present:
  ```
  [buildPlans.IosevkaFm]
family = "Iosevka FM"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false
noLigation = true

[buildPlans.IosevkaFm.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.IosevkaFm.widths.Extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.IosevkaFm.widths.SemiExtended]
shape = 548
menu = 6
css = "semi-expanded"

[buildPlans.IosevkaFm.widths.ExtraExtended]
shape = 658
menu = 8
css = "extra-expanded"

[buildPlans.IosevkaFm.widths.UltraExtended]
shape = 720
menu = 9
css = "ultra-expanded"

  ```
* The detailed error log:
  ```
  None provided.
  ```

**Comment by be5invis** [comment]
No repro at my side.

**Comment by maths-lover** [comment]
I am getting this issue as well, my `private-build-plans.toml` file looks like following,

```toml
[buildPlans.IosevkaMathsLover]
family = "Iosevka MathsLover"
spacing = "quasi-proportional"
serifs = "slab"
noCvSs = true
exportGlyphNames = false

  [buildPlans.IosevkaMathsLover.variants]
  inherits = "ss08"
```

And I'm using docker to build the fonts with following command as per the docs,

`docker run -it --rm -v $PWD:/work fontcc ttf::IosevkaMathsLover`

And I get the following


```
<earlier output redacted>
...
♦ Create TTF dist/IosevkaMathsLover/TTF-Unhinted/IosevkaMathsLover-ExtendedExtraLightItalic.ttf 
♦ Create TTF dist/IosevkaMathsLover/TTF-Unhinted/IosevkaMathsLover-Light.ttf 
♦ Create TTF dist/IosevkaMathsLover/TTF-Unhinted/IosevkaMathsLover-ExtendedLight.ttf 
♦ Create TTF dist/IosevkaMathsLover/TTF-Unhinted/IosevkaMathsLover-LightOblique.ttf 
♦ Create TTF dist/IosevkaMathsLover/TTF-Unhinted/IosevkaMathsLover-ExtendedLightOblique.ttf 
♦ Create TTF dist/IosevkaMathsLover/TTF-Unhinted/IosevkaMathsLover-LightItalic.ttf 
♦ Create TTF dist/IosevkaMathsLover/TTF-Unhinted/IosevkaMathsLover-ExtendedLightItalic.ttf 
Building process terminated.
```

I'm not sure what's causing this issue because there are literally no meaningful logs for this termination.

Also wanted to know if lots of RAM consumption was normal or not (around 16gigs consumed per build)

**Comment by be5invis** [comment]
Well OOM *may* be a reason -- the builder do consume a lot of memory, and you can try add `--jCmd=<number of concurrent jobs>` to limit the processes in parallel.

**Comment by maths-lover** [comment]
@be5invis Yep, I was trying options including what you suggested. Also, I suspect it could be kernel halting the process because of high memory and cpu usage. I'll update once I have something solid here.

**Comment by maths-lover** [comment]
Alright so I was able to build all fonts, it was indeed high CPU usage and kernel would kill the process because of that.

I took @be5invis's advice and passed on the `--jCmd=8` and it did build fonts without issues.

Full command that worked for me,
```bash
docker run -it --rm --memory="12g" --cpus="8.0" -v $PWD:/work fontcc --jCmd=8 ttf::IosevkaMathsLover
```

@futuremotiondev I think you can just pass --jCmd according to your system's specs.

If you have around 8gb ram then --jCmd=4  or --jCmd=6 should do. i.e., in your case, `npm run build -- --jCmd=4 contents::IosevkaFm`
