### ISSUE TITLE
Python's __main__ ligation

### ISSUE THREAD

**Issue by jeffteixeira** [be5invis/Iosevka#2267]
- [x] A programming language requires this ligation. Provide the information below.
- [x] This ligation is implemented in other programming fonts. Provide samples below.

------

In Python, the bit of code below is very common.
![image](https://github.com/be5invis/Iosevka/assets/58240722/91125696-8c2c-42e2-b2c3-260768454046)

Other fonts has a ligation for `__main__`, like the examples below.

Victor Mono font
![image](https://github.com/be5invis/Iosevka/assets/58240722/28f005ef-cee3-49c8-90b1-2161eec43bfc)

JetBrains Mono font
![image](https://github.com/be5invis/Iosevka/assets/58240722/e0b8fd82-e5f4-408d-9b5d-fdaa0286a7ed)

**Comment by be5invis** [comment]
Just generic underscore combining. You can enable this with a custom build that has `underscore-underscore` ligation group enabled.

**Comment by jeffteixeira** [comment]
Are there plans to make this ligation standard?

**Comment by jeffteixeira** [comment]
Are there plans to make this ligature standard, as it is standard in many fonts @be5invis?
