### ISSUE TITLE
Enable underscore-underscore ligation group by default

### ISSUE THREAD

**Issue by jeffteixeira** [be5invis/Iosevka#2268]
**Is your feature request related to a problem? Please describe.**
I'm a Python developer and I really like the Iosevka font, but there's one thing that frustrates me, which is the disabled underscore-underscore ligation group by default.

**Describe the solution you'd like**
Enable underscore-underscore ligation group by default.

**Additional context**
Other fonts like JetBrains Mono, Victor Mono and Fira Code, for example, have a ligation enabled by default for `__main__`, making the code look more elegant.

[Related issue with images](https://github.com/be5invis/Iosevka/issues/2267#issue-2215913798)

**Comment by zero00072** [comment]
The default:

![code000](https://github.com/be5invis/Iosevka/assets/2072036/3a35ec39-dca1-4397-bcfd-06f96ba6513e)

From the VS Code tutor, change the setting:

![code001](https://github.com/be5invis/Iosevka/assets/2072036/0292cf71-7319-4d7a-aa3e-b76b60a7ed48)

It's fine:

![code002](https://github.com/be5invis/Iosevka/assets/2072036/7900f292-0a59-439c-a714-4289bdf60be8)

I think it may or may not to be a default. I love them be connected. But make them separated is good for default. Someone may like to know whether it is `_`, `__`, or `___`.

**Comment by jeffteixeira** [comment]
In vscode it's possible to do this, but in other editors/IDEs it's only possible to enable or disable ligatures.
