### ISSUE TITLE
Under QP, sequences of multiples of three `m`-width chars don't line up with ones of four `n`-width chars or eight `i`-width chars due to floating-point rounding error.

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#2273]
```
mmm
nnnn
iiiiiiii
```
![image](https://github.com/be5invis/Iosevka/assets/37010132/9f087537-cbb9-4c3c-8557-998624564518)

```
mmmmmm
nnnnnnnn
iiiiiiiiiiiiiiii
```
![image](https://github.com/be5invis/Iosevka/assets/37010132/bcccda3b-d622-480b-9409-aed9e7713d0e)

```
mmmmmmmmm
nnnnnnnnnnnn
iiiiiiiiiiiiiiiiiiiiiiii
```
![image](https://github.com/be5invis/Iosevka/assets/37010132/25384a56-76f3-4a15-bbf3-6d8c7a921251)

**Comment by be5invis** [comment]
Well...
![image](https://github.com/be5invis/Iosevka/assets/240091/0f227393-bea7-46f0-929c-b28b17ca287a)
It's the pixel metrics rounding error of the client. Not something fixable.
Resolve as external.
