### ISSUE TITLE
Big brackets are displayed incorrectly

### ISSUE THREAD

**Issue by Toufukun** [be5invis/Iosevka#228]
* Your font version: Inziu Iosevka 1.13.3
* Your font variant: Default
* Your operating system (name and version): macOS Sierra 10.12.6
* Your application using Iosevka: Bash in Terminal

The screenshots show GNU Octave with OctSymPy. When I use Iosevka, the big parentheses are overlapped with other text. It becomes normal with Menlo. It seems that Iosevka lacks support for big brackets (U+239B to U+23AE). Please consider adding these symbols.

Iosevka:
<img width="515" alt="2017-09-24 18 20 14" src="https://user-images.githubusercontent.com/6957041/30787388-3656c744-a155-11e7-873e-803dff405ab9.png">

Menlo:
<img width="502" alt="2017-09-24 18 21 08" src="https://user-images.githubusercontent.com/6957041/30787391-3b567848-a155-11e7-8661-ce947005c6b3.png">

**Comment by be5invis** [comment]
Consolidated into #81.
