### ISSUE TITLE
Character spacing is narrow

### ISSUE THREAD

**Issue by Wanguy** [be5invis/Iosevka#229]
* Your font version: (1.13.3)
* Your font variant:
* Your operating system (macOS 10.13):
* Your application using Iosevka: (XCode, Visual Studio for mac, iTerm 2.)

If you have problem when building Iosevka, please provide these informations:

* Your Node.js version:
* Your _otfcc_ version:
* Your `make` version:
* Your results of `npm list`:
```
paste here
```
* Your `parameters.toml`:
```
paste here
```
* Your results of `make -d --no-builtin-rules`:
```
paste here
```
---

Describe your problem here. Provide pictures and files if necessary.
这是我第一次使用这个字体，但在使用中觉得字符间距太窄了，请问这是故意这样子设计的吗？请问有方法可以增加字符间距吗

**Comment by be5invis** [comment]
Yes it is by design.
Perhaps you can follow #196.
Closed.
