### ISSUE TITLE
Repeated character as one extened character (ligature?) alignment is off in the singular case

### ISSUE THREAD

**Issue by 7v0lk0v** [be5invis/Iosevka#2290]
The character in question: `꜔` [Modifier Letter Mid Left-Stem Tone Bar (A714)](https://symbl.cc/en/A714/).

Here's the test case (the numbers indicate how many of those bars are next to each other):
```
0a
꜔1a
꜔1b
꜔꜔2a
꜔꜔꜔3a
꜔꜔꜔3b
꜔꜔2b
꜔1c
0b
```

Result:
![image](https://github.com/be5invis/Iosevka/assets/8690075/9664ce4a-1d3f-40a7-b93d-aa4162e6b294)

The alignment of the vertical bar is a bit off when there's only one char (more to the left) vs multiple (more to the right).

It would be great if they all aligned (preferably to the left) as it makes for a great indent guide/marker.

I thought it might be a terminal issue (kitty) but I see the same thing in my browser, so it must be the font itself:

![image](https://github.com/be5invis/Iosevka/assets/8690075/cead7a31-1fc1-485f-aebc-ccd55d8be395)

---

* Your font version: 03904382e7c1212695828c448bca375fa4d0f4c5
* Your font variant: custom
* Your operating system (name and version): Linux 6.8.4-zen1-1.1-zen 
* Your application using Iosevka: kitty, Firefox

**Comment by be5invis** [comment]
Well I am doing this for simpler implementation. Otherwise supporting long tone marks will be almost impossible.

**Comment by 7v0lk0v** [comment]
If I understand you correctly, you're saying that rendering the bar a bit closer to the left cannot be done for technical reasons?  If so, that's unfortunate, and I guess you can close the ticket then.

**Comment by be5invis** [comment]
@7v0lk0v It could but will be very tricky (and will introduce about 400 glyphs).

**Comment by 7v0lk0v** [comment]
Doesn't sound worth the effort.  Thanks for explaining.
