### ISSUE TITLE
Broken Geometry for ij(?) in some boundary cases

### ISSUE THREAD

**Issue by Logo121** [be5invis/Iosevka#2292]
Since #1882 I've been building with the boundary metric cases allowed in private build sample (along with the regular cases):
- Weight of 100 and 900
- Width of 434 and 664
- Slant of 0, 9.4 and 15

A few version ago I start getting these messages when building:
```
Detected broken geometry when processing .ligature-part.J@compatLigature1/0.8370763848151533/0/200.22867124778466
Detected broken geometry when processing .ligature-part.J.serifedSymmetric@compatLigature1/0.8370763848151533/0/200.22867124778466
Detected broken geometry when processing .ligature-part.J.serifedBothSides@compatLigature1/0.8370763848151533/0/200.22867124778466
Detected broken geometry when processing .ligature-part.J.serifless@compatLigature1/0.8370763848151533/0/200.22867124778466
```
Which I _think_ happens with Heavy (900), Extra Condensed (434) and max Slant (15). It could be the other cases though.

**Comment by be5invis** [comment]
Well currently broken geometries won't crash the build, instead it will leave a blank glyph.
Maybe you can try find it from some J-related ligatures (IJ or DJ)

**Comment by Logo121** [comment]
Well my guess is correct, IJ in Heavy Ultra Condensed and max Slant:
![image](https://github.com/be5invis/Iosevka/assets/21302803/1f5ccd4d-3ee9-4826-b02a-0f2283c6b753)

**Comment by jmcwilliams403** [comment]
I keep meaning to open an issue that Ĳ/ĳ should be no closer together than the vertical lines of U/u

**Comment by be5invis** [comment]
Hook lf J being too tight...

**Comment by Logo121** [comment]
Wait, I just built once on d6533065d and the broken geometry still exists, same message.
