### ISSUE TITLE
Some ligations can be elevated to the default ligation set, like `<<` and `>>`

### ISSUE THREAD

**Issue by eproxus** [be5invis/Iosevka#230]
* Your font version: 1.13.3
* Your font variant: Default
* Your operating system (name and version): macOS 10.12.6
* Your application using Iosevka: Sublime Text 3 Dev Build 1347, iTerm2 3.1.3

Does Iosevka have a ligature for `>>` and `<<`? It seems to have in iTerm, but not in Sublime Text. I'm asking here because it is not clear from the documentation if that ligature is actually included in the font.

**Comment by be5invis** [comment]
`>>` and `<<` are included, but Sublime Text has no ligation support.

**Comment by eproxus** [comment]
It does now since build 3146: https://www.sublimetext.com/3dev

It's probably a bug in Sublime Text's implementation then. I'll bring it up on the forum.

**Comment by be5invis** [comment]
Perhaps because `<<` and `>>` are not in the default ligation set?
Re-open.

**Comment by eproxus** [comment]
Default ligation set of Iosevka or of Sublime Text?

**Comment by eproxus** [comment]
Thanks! 🙇
