### ISSUE TITLE
Iosevka Customizer features no live example???

### ISSUE THREAD

**Issue by osakanone** [be5invis/Iosevka#2305]
There's no realtime demonstration of outcome. The only way to preview an outcome is to build the font, then test it, then go back.

This leads to an annoying pattern of going back and forth until diminishing returns against time investment emerge, then users fall back on older fonts despite the potential of Iosevka.

A realtime demonstration of the user's design decisions upon a text-field of their choosing which could be of a realistic and practical code scenario would be incredibly helpful for dialling in the font's design, instead of this "compile and see" methodology which is currently present.

**Comment by Logo121** [comment]
This?
![image](https://github.com/be5invis/Iosevka/assets/21302803/50054574-68e8-4adb-bb1c-a3a03451666c)

For the textarea thing, well, it's backlogged here: #1206

**Comment by SMUsamaShah** [comment]
Can this page also feature some actual code e.g. some sample code from https://www.codingfont.com/browse or https://monaspace.githubnext.com/ for example?
