### ISSUE TITLE
Variant selector distinguishing tittle dots in `i`/`j` from diacritic dots in e.g. `ä`/`ö`/`ü`/etc.

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#2308]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

Many fonts distinguish the squareness/roundness of the dots in `i`/`j` from the diacritical dot compositions in Unicode.
`ijäöü`
Envy Code R:
![image](https://github.com/be5invis/Iosevka/assets/37010132/6701acc4-f4fc-4628-848f-77a6d77d7dad)
Courier New:
![image](https://github.com/be5invis/Iosevka/assets/37010132/9b1f9ee4-9789-4902-845d-db589d61a8d1)
Free Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/5c60ff1d-8fd6-4d34-b6ac-b93527c96043)

By the way, if this is implemented, a Turkish locale should also be added, which replaces the tittle dot composition (for `i` but not for `j`) with a diacritical dot composition like how it is currently. An Azerbaijani locale should also copy the Turkish locale, similarly to how the Macedonian/Bosnian locale copies the Serbian locale.

**Comment by be5invis** [comment]
Do we really need this? Dots on `i` and `j` are also diacritics, and I do not think they also change the dot on things like a-dot (`ȧ`).

**Comment by jmcwilliams403** [comment]
> Do we really need this? Dots on `i` and `j` are also diacritics, and I do not think they also change the dot on things like a-dot (`ȧ`).

They _don't_ change them:
`ijėż`
Envy Code R:
![image](https://github.com/be5invis/Iosevka/assets/37010132/af73fe14-74a9-4e64-93ba-09189a2aa1d4)
Courier New:
![image](https://github.com/be5invis/Iosevka/assets/37010132/35640762-4198-444c-9d88-f02b6d5e70ad)
Free Mono:
![image](https://github.com/be5invis/Iosevka/assets/37010132/fc1f0ce6-b584-4db2-a0d6-e9d01b802a50)
