### ISSUE TITLE
Unable to use Iosevka as KDE fixed width font

### ISSUE THREAD

**Issue by MarcinOrlowski** [be5invis/Iosevka#231]
First, I am not sure I should report it here but you know the subject more so you are better to judge.

I am using Ubuntu 17.x with KDE 5 and got `Iosevka` installed as `System font` (`Font Management` shot):

![iosevka01](https://user-images.githubusercontent.com/8041294/31453538-ca756312-aeb2-11e7-8046-33fc299187cd.png)

other apps like IDEs can use it w/o problem. But I am unable to use as system wide "Fixed width" font as  "Font" simply do not list it:

![iosevka02](https://user-images.githubusercontent.com/8041294/31453542-cfb8008c-aeb2-11e7-87d7-d38e149a268d.png)

Is it KDE's problem or `Iosevka` by any chance is missing something that makes KDE think it's not fixed width font?

**Comment by be5invis** [comment]
You could try Iosevka Term. The (plain) Iosevka **is not** strictly fixed width.

**Comment by MarcinOrlowski** [comment]
Thank you.  Installing `Iosevka Term` solved my problem.
