### ISSUE TITLE
Inziu Iosevka SC doesn't make org table aligned with mixed Chinese and English characters

### ISSUE THREAD

**Issue by amosbird** [be5invis/Iosevka#232]
* Your font version: (Release or git, version)
inziu-iosevka-1.13.2
* Your font variant:
Inziu Iosevka SC
* Your operating system (name and version):
Archlinux
* Your application using Iosevka: (some Java applications may have problem in showing Iosevka properly. It is a bug in Java's GUI components.)
emacs

![image](https://user-images.githubusercontent.com/5085485/31701021-f3739d26-b392-11e7-9f77-e72d11e51064.png)

**Comment by be5invis** [comment]
What is the text size, in pixels?
Looks like a rounding issue.

**Comment by amosbird** [comment]
I don't know how to get the pixel size. Font size is 14.

**Comment by be5invis** [comment]
Looks like it is being an odd number or other rounding issue.
Anyway **Inziu is deprecated**, Please update to [Sarasa Mono](https://github.com/be5invis/Sarasa-Gothic). Closed.
