### ISSUE TITLE
Variant: colon vertically centered 

### ISSUE THREAD

**Issue by notpeter** [be5invis/Iosevka#2321]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [ ] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

The vertical placement of `:` (and related ligatures: `::`, `:::`, etc) varies depending on context:
1. Colon sits on the baseline or
2. Colon sits vertically centered on the median

Specifically typing `::<` character-by-character (used for the turbo fish operator in rust) results in the three distinct positions of the colon.  The horizontal movement when making the `::` (expected ligature behavior) and vertical movement when typing the subsequent character. I find the vertical movement extremely distracting. It occurs when a `:` is followed by any of `<>=-+` (not just `<`).

Depending on context, the colon(s) move up or down when the next character is typed.  Here is an animated example demonstrating these behaviors:

![colon-colon2](https://github.com/be5invis/Iosevka/assets/145113/e0b700b1-370e-4f9c-bbd0-ad5fdd1b8cf7)

Proposal: add variants for the colon character `:` so a vertically centered placement can be enabled as a default. This currently possible with the `*` character, but not for `:`.  Such a variant would also make it possible to avoid two successive `::` within a single call being displayed at different heights (see: `mem::size_of::<u8>` in the gif above.)      

I observed this behavior in the [Zed editor](https://zed.dev) which includes an Iosevka customization [Zed Mono](https://github.com/zed-industries/zed-fonts). Here is the associated [custom build config](https://github.com/zed-industries/zed-fonts/blob/main/private-build-plans.toml).

**Comment by glepnir** [comment]
I got same problem . reprocue can by simply a rust code like `std::O`

**Comment by notpeter** [comment]
Zed switched their default font from 'Zed Mono' (an Iosevka derivative) to 'Zed Plex Mono' (an IBM Plex Mono derivative) so this is not longer a major concern.

I really like all the other ligatures in Iosevka, but having dancing colons made it unsuitable for Rust programming so in the absence of this variant I've moved elsewhere.

**Comment by be5invis** [comment]
I think a better idea is to prohibit `:` from centering for certain languages (C-like, Rust, etc.).

**Comment by be5invis** [comment]
Well, well, in current C-like ligation set we already prohibit `:` from centering.

![image](https://github.com/user-attachments/assets/9accf9d1-ab96-466a-b997-1c798b894134)

I think maybe you can simply change your font feature settings to `CLIK` (and turn off `calt`)? In VSCode you could do this:

```json
    "[rust]": {
        "editor.fontLigatures": "'calt' 0, 'CLIK' 1"
    },
```
