### ISSUE TITLE
Add a way to update private build plans from previous versions

### ISSUE THREAD

**Issue by lynzrand** [be5invis/Iosevka#2325]
**Is your feature request related to a problem? Please describe.**

I have been maintaining a number of Iosevka variants used in my coding and design environments. I update my local repo to catch up with the official one once every few months, and at every rebuild there would be some compilation errors related to using legacy variant names, etc. in the build plan. 

The fixing process is somewhat time-consuming, requiring either digging into the changelog (and scanning through the variant lists) to find what variant names have changed, or recompiling multiple times to reveal which variant names are no longer used. This often takes more time than running the compilation itself.

**Describe the solution you'd like**

Ideally, I would like a script that reads `private-build-plans.toml` and the corresponding version, and does simple updates (e.g. change legacy variant names into new ones) automatically or interactively. Integration with Iosevka Customizer might also be considered.

A more simple solution might be a machine-readable log containing (breaking) changes that a machine could resolve, and how to apply them to the build plan. I can write the script myself :)

**Describe alternatives you've considered**

A breaking-change-only changelog should also make the update process easier.

Anyway, if things won't change, I can always go and dig into the raw changelog files like before :)

**Comment by be5invis** [comment]
Need something to check against the old variant atlas vs the new. Maybe we could compare the _description_ since they are mostly not changed...

**Comment by lynzrand** [comment]
Maybe we can start with a "check" script, that only verifies the build plan against the current variant atlas and reports errors it found? The rest of the fixing can be done by hand
