### ISSUE TITLE
Name change of "x.semi-chancery-{straight|curly}" to "x.semi-chancery-{straight|curly}-serifless" not yet implemented in website customizer

### ISSUE THREAD

**Issue by LtqxWYEG** [be5invis/Iosevka#2326]
v30.0.0 was updated to change the name of `x.semi-chancery-{straight|curly}` to `x.semi-chancery-{straight|curly}-serifless`
The website however still uses the old name and so the **.toml** produces this error when building Iosevka:

```
 Error: Error: Composite {user} cannot be resolved: x,semi-chancery-curly.
    at Composite.decompose (file:///C:/Users/xxx/Iosevka/packages/param/src/variant.mjs:266:19)
    at Composite.resolve (file:///C:/Users/xxx/Iosevka/packages/param/src/variant.mjs:281:39)
    at Module.apply (file:///C:/Users/xxx/Iosevka/packages/param/src/variant.mjs:19:17)
    at createParaImpl (file:///C:/Users/xxx/Iosevka/packages/font/src/index.mjs:68:15)
    at paraT (file:///C:/Users/xxx/Iosevka/packages/font/src/index.mjs:77:16)
    at main (file:///C:/Users/xxx/Iosevka/packages/font/src/index.mjs:22:15)
    at ChildProcess.<anonymous> (C:\Users\xxx\Iosevka\node_modules\verda\lib\actions\nodejs\command.js:53:31)
    at ChildProcess.emit (node:events:518:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Building process terminated.
```

Sorry, seems it is ok to be this short, as it is pretty clear what's wrong. (I think. ... I hope..)

**Comment by jmcwilliams403** [comment]
It's correct on my end:
![image](https://github.com/be5invis/Iosevka/assets/37010132/defcfbce-d323-44d4-b7d4-5aef756d9bbc)
Try refreshing the page.

**Comment by LtqxWYEG** [comment]
Ok, but just changing that in my toml (which should essentially be the same action, since I created the toml with the customizer a few hours ago, anyway) does not fix the issue. It is still looking for `"semi-chancery-curly"` somewhere, and I cant' find it.  
I found `semiChanceryCurlySerifless` in the `x.mjs` (.\Iosevka\packages\font-glyphs\src\letter\latin), so .. I

**Comment by jmcwilliams403** [comment]
>     * In the `.\Iosevka\params\variants.toml` were three `semiChanceryCurly` under the entry `4100:  [prime.x.variants-buildup.stages.body.semi-chancery-curly-serifless]`

This does not match the `variants.toml` file found in main. Have you been editing that instead of creating a `private-build-plans.toml` file?

**Comment by jmcwilliams403** [comment]
By the way I tested it using my `private-build-plans.toml` and it compiles for me just fine:

![image](https://github.com/be5invis/Iosevka/assets/37010132/567b8b5f-96a6-4b04-b54c-55858e3e525a)

**Comment by LtqxWYEG** [comment]
What... that works aswell on my end. Seems like something else is werid. Maybe somewhere there is a copy or configuration saved of my non-working toml and it wont update if the new one has the same name??  
idk

**Comment by jmcwilliams403** [comment]
> What... that works aswell on my end. Seems like something else is werid. Maybe somewhere there is a copy or configuration saved of my non-working toml and it wont update if the new one has the same name??
> 
> x = "semi-chancery-curly" is the only row that changed, why wouldn't it work then AFTER adding "serifless"
> 
> idk

I wouldn't recommend editing the `variants.toml` file for basic user configuration. The reason it seems to "magically" add the `-serifless` at the end is because of an extra step in the variant buildup tree that you're trying to add back yourself.

Simply leaving the `variants.toml` file alone (i.e. the same as it is in the main branch in the repo) and doing all your configuration in `private-build-plans.toml` makes everything work correctly.

**Comment by LtqxWYEG** [comment]
Yes, I found out that it was not the culprit and that it worked default..

I fixed it, though: After pasting the contents of this repository over everything again, my toml, where I added "serifless", is now also working. So there must have been some configuration saved from the time when there was no "serifless". Maybe look into that. :)

Anyway, I just had very bad timing. I created toml while the website was still old version, but the github download was newer. Or I took too long while making it and missed the update - keeping my local copy of the customizer old.

Well, thanks :)

**Comment by jmcwilliams403** [comment]
> Anyway, I just had very bad timing. I created toml while the website was still old version, but the github download was newer. Or I took too long while making it and missed the update - keeping my local copy of the customizer old.

It usually takes an hour (± a few minutes) for the release binaries to be uploaded to the actual releases tab after be5invis merges the original release commit into main, and then two or three minutes after that for the site to be updated. If you ever see that the version numbers in the release tab and the main repo don't match, then just wait a bit.

As for the discontinuity between your local files and the repo itself, that might be a cache issue, but don't quote me on that.
