### ISSUE TITLE
Word cannot find Sarasa Term SC Bold

### ISSUE THREAD

**Issue by sscco55** [be5invis/Iosevka#2339]
* Your font version: SarasaTermSC-TTF-1.0.12.7z
* Your operating system (name and version): Windows 10  22H2（19045.3996）
* Your application using Iosevka:  MS Word
* When I am using Word, I cannot find the font for Sarasa Term SC Bold, but I can find the other four fonts.Is it a problem with my own use or a font bug? How can I use BOLD font? thank you
![微信图片_20240523175551](https://github.com/be5invis/Iosevka/assets/79153496/7eaee88a-f69d-4fd1-bea5-6cf348cd4947)

**Comment by Logo121** [comment]
I can't say for sure, but my guess is Word just took those font to be the "Bold" and "Italic" version of the regular Sarasa Term font so they removed it from the list?

**Comment by be5invis** [comment]
Maybe, just click the <kbd>**B**</kbd> button on your toolbar?

**Comment by sscco55** [comment]
oh  I see ,thank you
