### ISSUE TITLE
bold chars are not the same width with the regular chars within the same mono font

### ISSUE THREAD

**Issue by glacjay** [be5invis/Iosevka#234]
* Your font version: sarasa gothic ttf v0.3.0
* Your font variant:
* Your operating system (name and version): win10
* Your application using Iosevka: Intellij IDEA, VS2010

---

Describe your problem here. Provide pictures and files if necessary.

Intellij IDEA screenshot:
![default](https://user-images.githubusercontent.com/292719/32373153-de726e5a-c0d2-11e7-90e5-fc1e54b9e96a.png)

VS2010 screenshot:
![default](https://user-images.githubusercontent.com/292719/32373203-1f64d07e-c0d3-11e7-90d4-fd72616e6475.png)

**Comment by be5invis** [comment]
Looks like faux bold being used.
Did you really installed all the weights?

**Comment by be5invis** [comment]
And please move this issue into https://github.com/be5invis/Sarasa-Gothic.

**Comment by glacjay** [comment]
I'm really sorry, I just installed the regular font. It works when I installed all of them. Thanks very much😂
