### ISSUE TITLE
brew install instructions are out of date

### ISSUE THREAD

**Issue by tillydray** [be5invis/Iosevka#2345]
Hi, came here from https://github.com/minad/org-modern/, the font looks great! 

## Problem
When running the `brew` command from the README

```
brew tap homebrew/cask-fonts
brew install font-iosevka
```

I got this output

```
Error: homebrew/cask-fonts was deprecated. This tap is now empty and all its contents were either deleted or migrated.
Warning: Formula homebrew/cask-fonts/font-iosevka was renamed to homebrew/cask/font-iosevka.
```

`brew` continued and downloaded the font just fine but I assume at some point it will stop working. The README should be updated to

```
brew tap homebrew/cask
brew install --cask font-iosevka
```

**Comment by be5invis** [comment]
@tillydray I saw you made a branch? If so then you could raise a PR to me (target `dev` please).

**Comment by tillydray** [comment]
Oops, I meant to create a PR but got distracted 😅 

https://github.com/be5invis/Iosevka/pull/2346
