### ISSUE TITLE
>>= Ligature not working in VSCode.

### ISSUE THREAD

**Issue by thewiru** [be5invis/Iosevka#2348]
Using `"editor.fontLigatures": "'HSKL'"`, `>>=` won't from a ligature, even though `=<<` and `>>==` will. I've also tested it with `ELMX`, to the same result, it might also happens with others, but I haven't tested them. 
A similar behavior [was previously documented in Fire Coda](https://github.com/tonsky/FiraCode/issues/1386), another font with ligatures, as a deliberate change that could be "solved" by simply adding a set to `"editor.fontLigatures" `. 
However, since I'm already using a stylistic set, I assume this shouldn't be happening.

---

* Font version: 30.1.1
* OS: Windows 10 22H2
* Application using Iosevka: VSCode

**Comment by be5invis** [comment]
This might work

```
"editor.fontLigatures": "'calt' off, 'HSKL'"
```

**Comment by thewiru** [comment]
That indeed solves it.
Sorry for the hassle, I am not well acquainted with the subject.
