### ISSUE TITLE
Character request: Left/Right white square bracket

### ISSUE THREAD

**Issue by ashton314** [be5invis/Iosevka#2350]
- The requested characters are ...
  - [ ] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [ ] Diacritic / Mark
  - [X] Symbol
- The requested characters are used in ...
  - [ ] The alphabet / character set of a natural language.
  - [ ] The alphabet / character set of a constructed language.
  - [ ] The alphabet / character set of a transliteration or notation system.
  - [X] Mathematical or other professional use in documents.
  - [ ] The symbol set of a programming language. For the languages that support using arbitrary symbols, please provide usages in well-known components or libraries.
  - [ ] The symbol set of a command-line program.
- [ ] Some other monospace/programming fonts supported this character. Provide images below.

------

The characters: 〚〛 (Unicode codepoints 12314, 12315)

I have read several papers (example [here](https://people.mpi-sws.org/~dg/papers/popl22-choreographies.pdf)) that use these symbols as part of their equations. I would love to have these symbols available when implementing programs from such papers or writing down notes about these papers.

**Comment by be5invis** [comment]
These are CJK specific characters.

![image](https://github.com/be5invis/Iosevka/assets/240091/ae6009c6-ba15-4ffd-8070-d337c5fb96cf)

Iosevka alrady had U+27E6 and U+27E7 (`⟦`, `⟧`) which are equivalent.

Resolve as by design.

**Comment by ashton314** [comment]
Perfect—thank you so much for the explanation.
