### ISSUE TITLE
Feature request: Narrow mark anchors for letters with ascender/descender.

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#2354]
Current behavior:
![image](https://github.com/be5invis/Iosevka/assets/37010132/923078f3-67c0-48b6-a301-74fc89214210)
Simulated possible improvement:
![image](https://github.com/be5invis/Iosevka/assets/37010132/1e0a6624-b072-4f56-827b-63eb790f6383)
This would be similar to the leaning anchor system but specifically for "narrow" marks, where it tucks them into the negative space where they may fit.
This would apply to other narrow marks too of course:
`b̍q̩d̍p̩h̍ɥ̩k̍ʞ̩þ̩̍β̩`
![image](https://github.com/be5invis/Iosevka/assets/37010132/5918238a-e139-4f29-b534-df609a8a0003)
![image](https://github.com/be5invis/Iosevka/assets/37010132/1b2f603e-0e5d-4320-8ad2-aaeb52473e09)

This wouldn't replace the existing leaning mark system for anything wider because characters like `ĥ` already look perfect as-is:
![image](https://github.com/be5invis/Iosevka/assets/37010132/631ff7c1-33fa-44dc-9ed2-219eb8cc4ef9)

**Comment by be5invis** [comment]
@dscorbett Is this acceptable for all letters with leaning negative space? Currently letters like `ḃ` are all special-cased.

**Comment by dscorbett** [comment]
This would be theoretically acceptable in the sense that it could be considered a valid design decision. Even if a certain case is unacceptable, it would still be clear what the characters are, so in the worst case it would still be legible.

In practice, I don’t know. The acceptability can depend on the language, the positions of other marks in documents these would often appear in, and maybe things like the optical size and leading. Different contexts have different conventions and they are not predictable from glyph shapes alone. For example, the positioning of U+0307 in Greek script in [Brill](https://brill.com/fileasset/Brill_version_4_00_for_non_commercial_use.pdf) depends on the language system. So I wouldn’t assume the proposed behavior is good _or_ that the current behavior is good until someone actually checks each letter–diacritic–context combination.

Alternatively, you could declare (implicitly, by implementing this) that Iosevka shall use narrow mark anchors wherever possible regardless of traditional positioning. (Assume for the sake of argument that the traditional positioning is sometimes different.) It’s okay to not follow tradition, but it’s a design decision, not a safe assumption.
