### ISSUE TITLE
Add configure letter-spacing

### ISSUE THREAD

**Issue by aplab** [be5invis/Iosevka#2357]
How to configure horizontal letter-spacing? 
To make text denser or sparser.
Like a CSS letter-spacing (in percent or float value)
example (img)
![2024-05-31_11-10](https://github.com/be5invis/Iosevka/assets/4007240/7ecb5542-aa55-44b2-8b07-38fa4af34544)

**Comment by be5invis** [comment]
You could use [`metricOverride`](https://github.com/be5invis/Iosevka/blob/main/doc/custom-build.md#metric-override) to change side bearings.

**Comment by be5invis** [comment]
Currently 1emu = 1/1000em.
`default_sb` is the current default sidebearing value. It varies in different weight/width.
Be very careful: changing `sb` will highly possibly create broken shapes.
