### ISSUE TITLE
Different comparison operators are not the same size, which looks strange

### ISSUE THREAD

**Issue by liangjingkanji** [be5invis/Iosevka#2363]
Different comparison operators are not the same size, which looks strange

<img width="82" alt="image" src="https://github.com/be5invis/Iosevka/assets/21078112/23ee6a13-1a8d-41f8-a32d-ce8c6c3b9d8e">

---

* Your font version: Release Version 30.1.2
* Your font variant: SS05
* Your operating system (name and version): Macos Ventura 13.6.7 (22G720)
* Your application using Iosevka:  GoLand

**Comment by be5invis** [comment]
If the latter is created by ligatures, then, well, this is by design. All fonts are doing this.
For Unicode comparison opertors they should have the same size.

**Comment by jmcwilliams403** [comment]
This could be considered a duplicate of #2176 possibly, although this one is categorized as a bug and not a variant/ligation request.

**Comment by AndydeCleyre** [comment]
I love Iosevka's ligatures. There are good arguments *against* ligatures, particularly when they make it difficult to see that they indicate more than one character. The fact that these two-character ligatures take the width of two characters is important and good, IMO.
