### ISSUE TITLE
Alphabetic characters following multiple CV tags, whose intended widths are wider/narrower than N, still use the character boundaries of N under Quasi-Proportional.

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#2366]
Monospace:
![image](https://github.com/be5invis/Iosevka/assets/37010132/faa9a659-0f7d-40f8-b8de-c31e070f81b2)
Quasi-Proportional:
![image](https://github.com/be5invis/Iosevka/assets/37010132/02f56bfb-60ee-4678-b314-d47e0b2f7e76)

**Comment by be5invis** [comment]
No it's there metrics being incorrect.
