### ISSUE TITLE
Superscript/Subscript/overscript characters with localized forms do not accept CV/SS features while localized.

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#2368]
Example in my offline test site under slab under bulgarian override with `ss12` enabled:
```
δб𞀱 в𞀲 гӷ𞀳 ɡgд𞀴 жӝӂҗ𞀶
иӥйҋ𞀸 кқ𞀹 пԥ𞀽 тҭ𞁀 Фф𞁂
ч𞁅 ицшщ𞀸𞁄𞁆◌ⷳ ьъыꙑꚝꚜ𞁇𞁬 ю𞁉
```
![image](https://github.com/be5invis/Iosevka/assets/37010132/33cc3cb3-9174-4493-a900-bb2914360dd3)

**Comment by be5invis** [comment]
Really? At least in DWrite (locale being `bg`, `ss12` enabled) it worked.
![image](https://github.com/be5invis/Iosevka/assets/240091/e4a77c0c-8313-46bf-9350-251f8376e763)
