### ISSUE TITLE
Could you provide a "latest" download link for an automated install script?

### ISSUE THREAD

**Issue by dh4nav** [be5invis/Iosevka#237]
I tend to install iosevka-pack on all my computers (running xubuntu usually), and I'm currently whipping up a small shell script that will let me install all my preferred software and tools and settings in one command when I (re)install a system. 

I noticed the latest Iosevka-pack has a version number in its file name. So my options at that point are to either clone the repo, compile and install (slow), or add the fixed version number link to my script and accept that I'm not getting the latest version on an install unless I update the install script manually (obviously what I'd like to avoid), or try and do some string extraction magic on the website which tries to extract the version number and construct the download link from that (prone to breaking). 

Would it be possible to provide a fixed download link which always redirects to the latest packaged download? Like, instead of having to go to "https://github.com/be5invis/Iosevka/releases/download/v1.13.3/iosevka-pack-1.13.3.zip" (which changes its version number with each release) for the current version, an additional link "https://github.com/be5invis/Iosevka/releases/download/latest/iosevka-pack-latest.zip" (or similar) with a fixed URL which always downloads the latest version. I could then simply add a wget to that link to my script and be set. 

That would make things tremendously simpler for me, script-wise.

Thank you for your consideration.

**Comment by be5invis** [comment]
I do not think it worth to change the building process.
You can follow the redirection of https://github.com/be5invis/Iosevka/releases/latest and find out the version number.

**Comment by be5invis** [comment]
According to https://stackoverflow.com/questions/3074288/get-url-after-curl-is-redirected
You can retreve the redirected URL and extract the version number from it.

**Comment by dh4nav** [comment]
Alright, that'll have to do then, thank you. I assume the name format of the download package (iosevka-pack-<version number>.zip) will not change in the near future?

**Comment by be5invis** [comment]
Yes.

**Comment by omgitsjoao** [comment]
You can also check in [this blog](https://blog.markvincze.com/download-artifacts-from-a-latest-github-release-in-sh-and-powershell/)  how to get the latest tag from a curl using some tricks on accept header, then request the artifact you want, combining the tag name with the default pattern on artifacts.
