### ISSUE TITLE
[Release Notes] The 3.2.0 release notes needs some clarification

### ISSUE THREAD

**Issue by AnrDaemon** [be5invis/Iosevka#2379]
The release notes mention addition of a ["STAR OF DAVID" (U+2721) glyph](https://www.fileformat.info/info/unicode/char/2721/index.htm), but the code [U+2720 accompanied the announce refers to so-called MALTESE CROSS](https://www.fileformat.info/info/unicode/char/2720/index.htm) ([which is, in fact, "cross pattée", according to pediwikia](https://en.wikipedia.org/wiki/Maltese_cross#:~:text=The%20Unicode%20Character%20%E2%80%9C%E2%9C%A0%E2%80%9D%20(U%2B2720)%20is%20called%20a%20Maltese%20Cross%2C%20but%20is%20in%20fact%20a%20cross%20patt%C3%A9e.)).

According to [commit](https://github.com/be5invis/Iosevka/commit/ccae326d016c3abfdbfe8b61eadaac1c56939ed9#diff-0e69cc87bb4504d6a9b0263359406514ff4ef92a54ff831790b829da1a392464R578), the symbol added is, indeed, U+2721.

**Comment by be5invis** [comment]
Ah just a typo.
