### ISSUE TITLE
Selectable Square vs. Round Braille dots.

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#2388]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

I believe these should go under a separate variant selector than punctuation dots since most fonts still use round braille dots when their punctuation uses square dots.

```
⠀⠁⠂⠃⠄⠅⠆⠇⠈⠉⠊⠋⠌⠍⠎⠏
⠐⠑⠒⠓⠔⠕⠖⠗⠘⠙⠚⠛⠜⠝⠞⠟
⠠⠡⠢⠣⠤⠥⠦⠧⠨⠩⠪⠫⠬⠭⠮⠯
⠰⠱⠲⠳⠴⠵⠶⠷⠸⠹⠺⠻⠼⠽⠾⠿
⡀⡁⡂⡃⡄⡅⡆⡇⡈⡉⡊⡋⡌⡍⡎⡏
⡐⡑⡒⡓⡔⡕⡖⡗⡘⡙⡚⡛⡜⡝⡞⡟
⡠⡡⡢⡣⡤⡥⡦⡧⡨⡩⡪⡫⡬⡭⡮⡯
⡰⡱⡲⡳⡴⡵⡶⡷⡸⡹⡺⡻⡼⡽⡾⡿
⢀⢁⢂⢃⢄⢅⢆⢇⢈⢉⢊⢋⢌⢍⢎⢏
⢐⢑⢒⢓⢔⢕⢖⢗⢘⢙⢚⢛⢜⢝⢞⢟
⢠⢡⢢⢣⢤⢥⢦⢧⢨⢩⢪⢫⢬⢭⢮⢯
⢰⢱⢲⢳⢴⢵⢶⢷⢸⢹⢺⢻⢼⢽⢾⢿
⣀⣁⣂⣃⣄⣅⣆⣇⣈⣉⣊⣋⣌⣍⣎⣏
⣐⣑⣒⣓⣔⣕⣖⣗⣘⣙⣚⣛⣜⣝⣞⣟
⣠⣡⣢⣣⣤⣥⣦⣧⣨⣩⣪⣫⣬⣭⣮⣯
⣰⣱⣲⣳⣴⣵⣶⣷⣸⣹⣺⣻⣼⣽⣾⣿
```
Example of square dots:
DejaVu Sans:
![image](https://github.com/be5invis/Iosevka/assets/37010132/be80f7df-3331-4c0c-b86f-ad5f6709d091)
Unifont:
![image](https://github.com/be5invis/Iosevka/assets/37010132/2104b310-706b-4d70-b829-edb6f509b211)

**Comment by be5invis** [comment]
GID quantity impact might be large

**Comment by jmcwilliams403** [comment]
> GID quantity impact might be large

Wouldn't it be exactly 255?

**Comment by jmcwilliams403** [comment]
Maybe cutting the characters up into two segments of 2×2 dots each would lessen the glyph impact?

**Comment by be5invis** [comment]
Well, glyph substitution doesn't "penetrate" into TT components...
