### ISSUE TITLE
Add support for variant family name for custom builds (e.g. Iosevka custom)

### ISSUE THREAD

**Issue by corelon** [be5invis/Iosevka#239]
Hi,

It would be interesting to have a variant family name (something like Iosevka Custom) in custom builds in order to be able to install side by side with the default installations in order to be able to try out without having to overwrite the installed fonts. Especially on Windows which likes to cache fonts this process can be quite cumbersome.

Thanks in advance.

**Comment by be5invis** [comment]
Actually I have some plan to get rid of things like `make`, but currently I am busy at dealing with company's work...

**Comment by corelon** [comment]
As an admirer of the work you have done, I can't wait to see what you are planning :)
Thanks for this awesome piece of work
