### ISSUE TITLE
Latin lower 'r' is a little too far right

### ISSUE THREAD

**Issue by pallaswept** [be5invis/Iosevka#2394]
* Your font version: 30.3.0 or git head
* Your font variant: All, especially Aile, SS13
* Your operating system (name and version): OpenSUSE Tumbleweed KDE 
* Your application using Iosevka: firefox, plasma, konsole

I have spent some time recently customising Iosevka for my needs. It's been really helpful with some eye trouble, so thank you!!

I did notice though, that sometimes, the 'r' character appears a little misaligned. I suspect that the stem of the character is intentionally moved toward the centre, to compensate for the lack of space below the hook on the opposing side. I like this, but I feel like maybe it's a little too far toward the centre, as sometimes, there's a rather visible space between a previous character and the 'r'. I can see this in the stock font, too, so I thought I should report it. It's not always extremely noticeable, but it has 'jumped out' at me a few times. 

It's definitely more noticeable (and measurably more extreme) on the SS13 style (the 'corner-hooked-' variants) because they are wider, but the stem does not move to compensate.

Here's an example: 

![image](https://github.com/be5invis/Iosevka/assets/132128962/c6530038-2e48-4b25-8827-aee10fef0572)

You can really notice it, after the 'i' and the 'W' here. Obviously, it is effected by choice of character, leading character, spacing, etc.

I know it's subtle, but after a while, I can't unsee it, and many of the 'r's look like they have a leading half-space. Perhaps we could find a slightly better way to select the stem position, or something? I know how I'd fix this with IRL lettering, but fonts are a mystery to me, so apologies for my inability to present a solution along with this! Am font noob :(

**Comment by be5invis** [comment]
It's a manner of visual balance -- maybe for the hooked case we could use a different metrics...

**Comment by pallaswept** [comment]
> It's a manner of visual balance

I probably used the wrong word when I said 'compensate', but this 'balance' is what I meant :) I think this technique works well.

> -- maybe for the hooked case we could use a different metrics...

That sounds like it could work :) The corner-hooked variant is the most effected here, specifically the serifless variant. 

I can see some evidence of it in other examples, though, for example this one [from the main readme](https://github.com/be5invis/Iosevka?tab=readme-ov-file#features). This one is a far less apparent example, but now that I know it's there, I see it. The effect is somewhat less apparent in "brown" because of the curve of the top-left of the 'o' making space on the right of the 'r', but when we look at "jumps_over(" it's far more obvious.

I think the serifing plays into this also. The serifed 'r' is more filled-in on the left, so appears more balanced.

It's sometimes more apparent in the quasi-proportional variants, since the letter spacing varies, we have even more opportunity to expose a problem like this, so I guess that makes sense.

So, I do think there's maybe potentially improvement to the original design form, but it seems like the variants exaggerate that situation, and would benefit from special treatment. 

I do understand that of course, we can never get spacing perfect for all usage, and the spacing like this is dependent of many many factors, so we can only approximate, and sometimes, the characters may seem a little bit off-centre. My usual rule of thumb (again, IRL, not with fonts, but I think this translates) is that if the character sometimes appears left- and sometimes right-of-centre, then it's probably good... But if it always appear off-centre to one side, I probably need to re-set it... and I never see this 'r' seeming too-far left, always right. It's not much though!

**Comment by pallaswept** [comment]
Thanks so much mate! Iosevka might be the first font I've ever actually liked. You're the best <3

**Comment by pallaswept** [comment]
I had a chance to build the full set, and wow. Such a huge change from such a tiny change. You have a very deft touch.
