### ISSUE TITLE
Lowercase l and the number 1, blurred.

### ISSUE THREAD

**Issue by lykex** [be5invis/Iosevka#24]
## Lowercase l and the number 1, blurred.

![iosevka](https://cloud.githubusercontent.com/assets/15267054/10869240/408e9fe0-80e4-11e5-940b-e6eeb5cc0b9f.png)

**Comment by be5invis** [comment]
Please clearify your problem: you mean `l` and `1` are hard to distinct, or they are rendered unclearly?

**Comment by lykex** [comment]
`l` and `1` are hard to distinct

**Comment by be5invis** [comment]
Well there is a "Z-shaped" `l` variant in the source code but I choose to use the current one.
You can edit the `parameters.toml`, add a variant selector like this:

```diff
#......
# Slant
[s-upright]
isItalic = false

+ [s-upright.variantSelector]
+ l = 'zshaped'

[s-italic]
isItalic = true
italicangle = 10
#......
```

then all `l`s (as well as its accented derivatives) in upright subfamilies will be reshaped.

**Comment by lykex** [comment]
Great, thank you!

**Comment by be5invis** [comment]
@lykex well i made some pre-built variants here: https://github.com/be5invis/Iosevka/releases/tag/v1.0-beta2
You can choose the `zshaped` version.

**Comment by lykex** [comment]
@be5invis 真是太帅了！我发现你还有维护一款中文字体：[`Inziu Iosevka`](http://pan.baidu.com/s/1hqwDUpY) ，这个还再更新吗？

如果更新的话，我希望以后可以在这里：https://github.com/be5invis/Iosevka/releases 附上中文字体的下载链接。

感谢你！
