### ISSUE TITLE
Missing ligatures in JavaScript

### ISSUE THREAD

**Issue by Connorelsea** [be5invis/Iosevka#240]
Is it possible to create a custom build of the font with ligatures for "<=", ">=", "===", "==", "!==", etc. in JavaScript? I currently have the most recent version of this repo cloned and building with make on my local machine, but can't quite figure out how to get these ligatures available in JavaScript.

Related to #220 but that issue is closed.

* Your font version: Latest cloned repo as of time of posting
* Your font variant: Iosevka
* Your operating system (name and version): MacOSHigh Sierra
* Your application using Iosevka: VSCode (latest version)

**Comment by be5invis** [comment]
Iosevka does NOT have ligatures for `<=`, `==`, `===`, `!=` and `>=`, since they are considered as "Breaking Ligatures".

**Comment by be5invis** [comment]
Move into #56. Closed.
