### ISSUE TITLE
Cyrillic U (У) vertical size bug

### ISSUE THREAD

**Issue by pv4** [be5invis/Iosevka#241]
Hello.

For fast report, just look at the gif attached. Two gif frames is what I get in ftview when pressing `<up>` and `<down>` sequentally to change font size. Something strange happens with cyrillic U (У) (marked with a red bar above the glyph). The glyph seems either to have a height slightly different from other glyphs, or to be positioned incorrectly (I cannot say for sure).

1. On the gif `ftview` has hinting turned off, but the similar issue happes with it turned on. So it isn't a hinting issue (not a run-time hinting at least, but maybe build-time hinting if iosevka uses ttfautohint when building ttfs, not sure here).
2. On the gif font size is huge, but I can visually(!) detect the similar issue when looking at iosevka in firefox on some site page where font-size is about 12pt. Moreover, I have hinting disabled system-wide, so this 12pt sized font is unhinted.
3. The gif shows `slab term regular` but `term regular` has the same issue.
4. I did not test non-regular variants (should I?).
5. I did not test `compressed` and `expanded` variants.

I built the font by myself with a patch applied (provided below), using the official build instructions, so I also provide build details.

---
* Your font version: 1.13.3
* Your font variant: term sans (regular?), term slab (regular?)
* Your operating system: Linux, freetype-2.8.1, ttfautohint-1.7
* Your application using Iosevka: firefox, ftview. Did not test others.

If you have problem when building Iosevka, please provide these informations:

* Your Node.js version: v8.2.1
* Your _otfcc_ version: 0.9.6
* Your `make` version: 4.2.1
* Build instructions:
```
Design="\
v-i-italic v-l-italic v-m-longleg v-q-taily v-t-standard \
v-zero-slashed \
v-asterisk-low v-at-short v-brace-curly v-caret-high v-dollar-open v-numbersign-upright v-tilde-low v-underscore-high \
v-eszet-traditional v-paragraph-high"

DesignRoman="\
v-a-doublestorey v-g-doublestorey \
v-three-flattop"

DesignItalic="\
v-a-singlestorey v-g-singlestorey \
v-three-twoarcs"

tar -xf Iosevka-1.13.3.tar.gz
cd Iosevka-1.13.3
patch -p1 -i ../Iosevka-1.13.3-wide.patch

npm install

make custom-config design="term sans $Design" upright="$DesignRoman" oblique="$DesignRoman" italic="$DesignItalic"
make custom
make custom-config design="term slab $Design" upright="$DesignRoman" oblique="$DesignRoman" italic="$DesignItalic"
make custom

# ... and similarly for `wide`, `compressed`, and `expanded` variants.

```
* Your results of `npm list`:
```
iosevka@1.13.3 /home/txz/src/main/grp/xorg/misc/fonts-misc/iosevka/Iosevka-1.13.3
+-- bezier-js@2.2.3
+-- caryll-shapeops@0.2.1
| +-- bezier-js@2.2.3 deduped
| `-- clipper-lib@1.0.0
+-- cubic2quad@1.1.1
+-- libspiro-js@0.3.1
+-- megaminx@0.3.3
| +-- child-process-promise@2.2.1
| | +-- cross-spawn@4.0.2
| | | +-- lru-cache@4.1.1
| | | | +-- pseudomap@1.0.2
| | | | `-- yallist@2.1.2
| | | `-- which@1.3.0 deduped
| | +-- node-version@1.1.0
| | `-- promise-polyfill@6.1.0
| +-- cubic2quad@1.1.1 deduped
| +-- fs-extra@3.0.1
| | +-- graceful-fs@4.1.11
| | +-- jsonfile@3.0.1
| | | `-- graceful-fs@4.1.11 deduped
| | `-- universalify@0.1.1
| +-- JSONStream@1.3.2
| | +-- jsonparse@1.3.1
| | `-- through@2.3.8
| `-- which@1.3.0
|   `-- isexe@2.0.0
+-- object-assign@4.1.1
+-- pad@1.2.1
| +-- coffee-script@1.12.7
| `-- wcwidth@1.0.1
|   `-- defaults@1.0.3
|     `-- clone@1.0.3
+-- patel@0.32.1
| +-- escodegen@1.9.0
| | +-- esprima@3.1.3
| | +-- estraverse@4.2.0
| | +-- esutils@2.0.2
| | +-- optionator@0.8.2
| | | +-- deep-is@0.1.3
| | | +-- fast-levenshtein@2.0.6
| | | +-- levn@0.3.0
| | | | +-- prelude-ls@1.1.2 deduped
| | | | `-- type-check@0.3.2 deduped
| | | +-- prelude-ls@1.1.2
| | | +-- type-check@0.3.2
| | | | `-- prelude-ls@1.1.2 deduped
| | | `-- wordwrap@1.0.0
| | `-- source-map@0.5.7
| +-- esmangle@1.0.1
| | +-- escodegen@1.3.3
| | | +-- esprima@1.1.1 deduped
| | | +-- estraverse@1.5.1 deduped
| | | +-- esutils@1.0.0 deduped
| | | `-- source-map@0.1.43 deduped
| | +-- escope@1.0.3
| | | `-- estraverse@2.0.0
| | +-- esprima@1.1.1
| | +-- esshorten@1.1.1
| | | +-- escope@1.0.3 deduped
| | | +-- estraverse@4.1.1
| | | `-- esutils@2.0.2 deduped
| | +-- estraverse@1.5.1
| | +-- esutils@1.0.0
| | +-- optionator@0.3.0
| | | +-- deep-is@0.1.3 deduped
| | | +-- fast-levenshtein@1.0.7
| | | +-- levn@0.2.5
| | | | +-- prelude-ls@1.1.2 deduped
| | | | `-- type-check@0.3.2 deduped
| | | +-- prelude-ls@1.1.2 deduped
| | | +-- type-check@0.3.2 deduped
| | | `-- wordwrap@0.0.3
| | `-- source-map@0.1.43
| |   `-- amdefine@1.0.1
| +-- patrisika@0.21.0
| | `-- patrisika-scopes@0.11.0
| +-- resumer@0.0.0
| | `-- through@2.3.8 deduped
| `-- yargs@6.6.0
|   +-- camelcase@3.0.0
|   +-- cliui@3.2.0 deduped
|   +-- decamelize@1.2.0 deduped
|   +-- get-caller-file@1.0.2 deduped
|   +-- os-locale@1.4.0
|   | `-- lcid@1.0.0 deduped
|   +-- read-pkg-up@1.0.1
|   | +-- find-up@1.1.2
|   | | +-- path-exists@2.1.0
|   | | | `-- pinkie-promise@2.0.1 deduped
|   | | `-- pinkie-promise@2.0.1
|   | |   `-- pinkie@2.0.4
|   | `-- read-pkg@1.1.0
|   |   +-- load-json-file@1.1.0
|   |   | +-- graceful-fs@4.1.11 deduped
|   |   | +-- parse-json@2.2.0 deduped
|   |   | +-- pify@2.3.0 deduped
|   |   | +-- pinkie-promise@2.0.1 deduped
|   |   | `-- strip-bom@2.0.0
|   |   |   `-- is-utf8@0.2.1
|   |   +-- normalize-package-data@2.4.0 deduped
|   |   `-- path-type@1.1.0
|   |     +-- graceful-fs@4.1.11 deduped
|   |     +-- pify@2.3.0 deduped
|   |     `-- pinkie-promise@2.0.1 deduped
|   +-- require-directory@2.1.1 deduped
|   +-- require-main-filename@1.0.1 deduped
|   +-- set-blocking@2.0.0 deduped
|   +-- string-width@1.0.2
|   | +-- code-point-at@1.1.0
|   | +-- is-fullwidth-code-point@1.0.0
|   | | `-- number-is-nan@1.0.1
|   | `-- strip-ansi@3.0.1 deduped
|   +-- which-module@1.0.0
|   +-- y18n@3.2.1 deduped
|   `-- yargs-parser@4.2.1
|     `-- camelcase@3.0.0 deduped
+-- toml@2.3.3
+-- topsort@0.0.2
+-- unorm@1.4.1
`-- yargs@8.0.2
  +-- camelcase@4.1.0
  +-- cliui@3.2.0
  | +-- string-width@1.0.2 deduped
  | +-- strip-ansi@3.0.1
  | | `-- ansi-regex@2.1.1
  | `-- wrap-ansi@2.1.0
  |   +-- string-width@1.0.2 deduped
  |   `-- strip-ansi@3.0.1 deduped
  +-- decamelize@1.2.0
  +-- get-caller-file@1.0.2
  +-- os-locale@2.1.0
  | +-- execa@0.7.0
  | | +-- cross-spawn@5.1.0
  | | | +-- lru-cache@4.1.1 deduped
  | | | +-- shebang-command@1.2.0
  | | | | `-- shebang-regex@1.0.0
  | | | `-- which@1.3.0 deduped
  | | +-- get-stream@3.0.0
  | | +-- is-stream@1.1.0
  | | +-- npm-run-path@2.0.2
  | | | `-- path-key@2.0.1
  | | +-- p-finally@1.0.0
  | | +-- signal-exit@3.0.2
  | | `-- strip-eof@1.0.0
  | +-- lcid@1.0.0
  | | `-- invert-kv@1.0.0
  | `-- mem@1.1.0
  |   `-- mimic-fn@1.1.0
  +-- read-pkg-up@2.0.0
  | +-- find-up@2.1.0
  | | `-- locate-path@2.0.0
  | |   +-- p-locate@2.0.0
  | |   | `-- p-limit@1.1.0
  | |   `-- path-exists@3.0.0
  | `-- read-pkg@2.0.0
  |   +-- load-json-file@2.0.0
  |   | +-- graceful-fs@4.1.11 deduped
  |   | +-- parse-json@2.2.0
  |   | | `-- error-ex@1.3.1
  |   | |   `-- is-arrayish@0.2.1
  |   | +-- pify@2.3.0
  |   | `-- strip-bom@3.0.0
  |   +-- normalize-package-data@2.4.0
  |   | +-- hosted-git-info@2.5.0
  |   | +-- is-builtin-module@1.0.0
  |   | | `-- builtin-modules@1.1.1
  |   | +-- semver@5.4.1
  |   | `-- validate-npm-package-license@3.0.1
  |   |   +-- spdx-correct@1.0.2
  |   |   | `-- spdx-license-ids@1.2.2
  |   |   `-- spdx-expression-parse@1.0.4
  |   `-- path-type@2.0.0
  |     `-- pify@2.3.0 deduped
  +-- require-directory@2.1.1
  +-- require-main-filename@1.0.1
  +-- set-blocking@2.0.0
  +-- string-width@2.1.1
  | +-- is-fullwidth-code-point@2.0.0
  | `-- strip-ansi@4.0.0
  |   `-- ansi-regex@3.0.0
  +-- which-module@2.0.0
  +-- y18n@3.2.1
  `-- yargs-parser@7.0.0
    `-- camelcase@4.1.0 deduped
```
* Your `parameters.toml`: the default one with the following patch applied. But the issue is related to the plain iosevka family, not the "wide" variant.
```
diff -Napur Iosevka-1.13.3.orig/parameters.toml Iosevka-1.13.3/parameters.toml
--- Iosevka-1.13.3.orig/parameters.toml 2017-08-27 11:37:47.134692704 +0300
+++ Iosevka-1.13.3/parameters.toml      2017-11-26 17:05:23.552101535 +0300
@@ -247,6 +247,14 @@ family = 'CC'
 
 ### Widths
 # Expanded : I heard someone want it being wider...
+[wd-wide.multiplies]
+width = 1.05
+sb = 1.05
+[wide]
+inherits = ['wd-wide']
+[wide.adds]
+family = ' Wide'
+
 [wd-expanded.multiplies]
 width = 1.15
 sb = 1.15
```

---
![a](https://user-images.githubusercontent.com/2502094/34280305-eebf55c8-e6c7-11e7-9d37-2e5c776bc4db.gif)

**Comment by be5invis** [comment]
The `uni0423` in Iosevka Slab (GID 913) contains an unique reference to GID 92 (which is, `y`), as they share the same outline and only differs in position. The offset is 205 which is also the correct number.
I think it may be an issue in Freetype that performed incorrect rounding.

**Comment by pv4** [comment]
> I think it may be an issue in Freetype that performed incorrect rounding.

Does not seem to. The attached screenshot is made on Windows 10 in Internet Explorer 11 (and the same happens on Windows 10 in Firefox ESR 45.4.0).

Besides, I tested freetype-2.6.4 and it has the same issue.

Btw, 02-iosevka-term-1.13.3.zip from https://github.com/be5invis/Iosevka/releases is affected as well (I'm sorry I was too stupid to test it before), so this is not an issue with my build environment.

![b](https://user-images.githubusercontent.com/2502094/34310832-c218d348-e76a-11e7-9f29-340793d148cd.png)

**Comment by be5invis** [comment]
Maybe I can try to remove the rounding tag in glyf references, but it damages the effect of hinting.

发自我的 iPhone

在 2017年12月23日，04:02，pv4 <notifications@github.com<mailto:notifications@github.com>> 写道：


I think it may be an issue in Freetype that performed incorrect rounding.

Does not seem to. The attached screenshot is made on Windows 10 in Internet Explorer 11 (and the same happens on Windows 10 in Firefox ESR 45.4.0).

Besides, I tested freetype-2.6.4 and it has the same issue.

Btw, 02-iosevka-term-1.13.3.zip from https://github.com/be5invis/Iosevka/releases<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbe5invis%2FIosevka%2Freleases&data=02%7C01%7C%7C232716bd44034d991bf408d54976fece%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636495697781665330&sdata=gRL3Gv6A%2BBRmAk7gKvMgUc5HVMdPXiLi0I5kcbm9eGI%3D&reserved=0> is affected as well (I'm sorry I was too stupid to test it before), so this is not an issue with my build environment.

[b]<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F2502094%2F34310832-c218d348-e76a-11e7-9f29-340793d148cd.png&data=02%7C01%7C%7C232716bd44034d991bf408d54976fece%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636495697781665330&sdata=HSKX%2Bzo03mxo2Xch%2B6s%2BM09hMoj23iDAsjL2J0FybhM%3D&reserved=0>

**Comment by pv4** [comment]
> The uni0423 in Iosevka Slab (GID 913) contains an unique component reference to GID 92

May the issue be caused by the fact GID 913 is uppercase while GID 92 is lowercase?

**Comment by be5invis** [comment]
There is a pass, called autoref, which replaces identical shapes among multiple glyphs into references to one glyph plus an offset vector.

发自我的 iPhone

在 2017年12月23日，04:15，pv4 <notifications@github.com<mailto:notifications@github.com>> 写道：


The uni0423 in Iosevka Slab (GID 913) contains an unique component reference to GID 92

May the issue be caused by the fact GID 913 is uppercase while GID 92 is lowercase?

**Comment by pv4** [comment]
> There is a pass, called autoref, which replaces identical shapes among multiple glyphs into references to one glyph plus an offset vector.

Wow, it's a graceful solution, really! I never thought the lowercase letter can have the same shape as an uppercase one :)

I just opened the original iosevka ttf in `fontforge` and "generated" a new font without changes (in otf format with .ttf extension). That fixed the uni0423 (in the generated font).

But the generated font differs from the original one. In the original ttf uni0423 is just a "reference" you speak about so I cannot edit it in fontforge. In the generated ttf uni0423 is a glyph itself (not a reference) with control points, curves, etc... and can be edited. The generated ttf is also larger in size (450KB vs. 380KB).

Why using "references" at all if they cause such issues? Why not just "inline" the "referenced" glyphs to the referencing positions, making uni0423 be not a reference to latin `y` but just a copy of it. I mean, in .ptl they can be kept as references, but in final ttf/woff they would appear as different independent glyphs.

What do you think?

By the way, many other "reference" glyphs (e.g. uin0422 and uni0425) seem to be rendered correctly (but maybe I just haven't met the situation where they don't).

**Comment by be5invis** [comment]
Actually in the building process all glyphs are contours. The autoref happens at very late stage.
I can add an restriction to autoref, which prevents unifying lowercase and uppercase letters. Hopefully it would fix your issue.

发自我的 iPhone

在 2017年12月23日，05:13，pv4 <notifications@github.com<mailto:notifications@github.com>> 写道：


There is a pass, called autoref, which replaces identical shapes among multiple glyphs into references to one glyph plus an offset vector.

Wow, it's a graceful solution, really! I never thought the lowercase letter can have the same shape as an uppercase one :)

I just opened the original iosevka ttf in fontforge and "generated" a new font without changes (in otf format with .ttf extension). That fixed the uni0423 (in the generated font).

But the generated font differs from the original one. In the original ttf uni0423 is just a "reference" you speak about so I cannot edit it in fontforge. In the generated ttf uni0423 is a glyph itself (not a reference) with control points, curves, etc... and can be edited. The generated ttf is also larger in size (450KB vs. 380KB).

Why using "references" at all if they cause such issues? Why not just "inline" the "referenced" glyphs to the referencing positions, making uni0423 be not a reference to latin y but just a copy of it. I mean, in .ptl they can be kept as references, but in final ttf/woff they would appear as different independent glyphs.

What do you think?

By the way, many other "reference" glyphs (e.g. uin0422 and uni0425) seem to be rendered correctly (but maybe I just haven't met the situation where they don't).

**Comment by pv4** [comment]
But why are you using autoref? Just to make font file size smaller?

> I can add an restriction to autoref, which prevents unifying lowercase and uppercase letters.

That would be great. But I'm not sure one can trust such a feature now. After such a situation wouldn't it be better to fully disable it to fix any similar issues in future (or at least have a build-time option to disable it fully)?

**Comment by be5invis** [comment]
Yes. To reduce the footprint.

发自我的 iPhone

在 2017年12月23日，05:25，pv4 <notifications@github.com<mailto:notifications@github.com>> 写道：


But why are you using autoref? Just to make font file size smaller?

I can add an restriction to autoref, which prevents unifying lowercase and uppercase letters.

That would be great. But I'm not sure one can trust such a feature now. After such a situation wouldn't it be better to fully disable it to fix any similar issues in future (or at least have a build-time option to disable it fully)?

**Comment by be5invis** [comment]
@pv4 I've provided a fix: A more strict `autoref` would no longer link `cyrU` to `y`.

**Comment by pv4** [comment]
5da7f90a79b856052a7a3560fc3db0e6468b0ffb fixes the bug. Thanks.
