### ISSUE TITLE
Rust Language Ligatures

### ISSUE THREAD

**Issue by vikky49** [be5invis/Iosevka#2411]
- [x] Rust language has this particular ligature
- [x] THis is implemented in JetBrains Mono and Fira Code

Please look at the following screen shot

------

<img width="302" alt="zed – fs rs 2024-07-10 10-38-01" src="https://github.com/be5invis/Iosevka/assets/180512/e30246ac-7745-4874-be38-3721bcc9ecd5">

**Comment by Rhelvetican** [comment]
bump.
