### ISSUE TITLE
Consider moving the digit `zero`‥`nine` CV feature tags in the next full/breaking version bump?

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#2427]
Digits `0`–`9` are currently almost at the back end of `cv01`–`cv99`. If any more CV features are added behind them, some or all of the digits may end up being pushed onto the more custom `VxAA`–`VxZZ` feature tags.

Perhaps it might be worth considering to move the range of CV features for digits `0`–`9` to a safe location in version 31 or thereabouts? Like either at the very beginning (at `cv01`–`cv10`) or alternatively right after the ASCII alphabetic characters (at `cv51`–`cv60`).

**Comment by be5invis** [comment]
Wait till they really went to VX.
Resolve as by design.

**Comment by be5invis** [comment]
OK I decide to do it now as it is a good time to do that.
