### ISSUE TITLE
A way to build only regular?

### ISSUE THREAD

**Issue by karambaq** [be5invis/Iosevka#243]
Hey, is there a way to build custom version with only regular?

**Comment by alexeyten** [comment]
I comment out styles and weights in https://github.com/be5invis/Iosevka/blob/master/maker.js#L6-L7

**Comment by karambaq** [comment]
@alexeyten Thank you!

**Comment by karambaq** [comment]
@alexeyten I can't find 'regular' in maker.js, is 'medium' the same?

**Comment by alexeyten** [comment]
@karambaq Book = Regular

**Comment by karambaq** [comment]
@alexeyten oh, thank you again.
