### ISSUE TITLE
Can't find ligatures glyphs using Glyph app

### ISSUE THREAD

**Issue by karambaq** [be5invis/Iosevka#244]
Where can I find .liga glyphs?

![image](https://user-images.githubusercontent.com/14233969/34651143-44a0cff4-f3dd-11e7-9e41-bd0168dcc22b.png)

**Comment by be5invis** [comment]
There's no "ligature" glyphs. In Iosevka, we are substituting the **parts** forming a ligation into something else. For example, the `->` ligature is implemented by replacing the hyphen into a longer bar.
Closed.
