### ISSUE TITLE
Intersecting contours

### ISSUE THREAD

**Issue by m4rc1e** [be5invis/Iosevka#245]
* Your font version: (Release or git, version)
1.13.3

* Your font variant:
Regular

* Your operating system (name and version):
Mac OS X

* Your application using Iosevka: (some Java applications may have problem in showing Iosevka properly. It is a bug in Java's GUI components.)
OT Master, FL

I'll try and get this pushed to Google Fonts soon. I thought I'd just take a quick look this morning.

Things look pretty good when I run the fonts through MS Font Val. However, there are a few contour issues.

![screen shot 2018-01-12 at 09 12 32](https://user-images.githubusercontent.com/7525512/34867783-51639fce-f779-11e7-9d8c-4c8acdec0456.png)
![screen shot 2018-01-12 at 09 12 07](https://user-images.githubusercontent.com/7525512/34867784-5183e09a-f779-11e7-8bfa-a7ffe521a17b.png)

I've attached the report as well. Change the extension to .html (github can't attach html)

[iosevka-regular.ttf.report.txt](https://github.com/be5invis/Iosevka/files/1625498/iosevka-regular.ttf.report.txt)

**Comment by be5invis** [comment]
@m4rc1e Have you tried to rebuild the entire family with the code in `master`?
Recently I made some updates in the code and the supporting libraries, however the prebuilt fonts are not updated.

**Comment by be5invis** [comment]
@m4rc1e Could you please verify this one attached below? ↓
[iosevka-regular.zip](https://github.com/be5invis/Iosevka/files/1625579/iosevka-regular.zip)

**Comment by m4rc1e** [comment]
thanks, I'll take a quick look now.

I see your build is using Node :-). I've got a dodgy npm so I can't build it right now. I will fix this and try again another time.

In the new ttf, we have a few new intersection issues (I don't care about dup knots or yellow issues).

![screen shot 2018-01-12 at 09 56 48](https://user-images.githubusercontent.com/7525512/34869479-f0dd275a-f77e-11e7-9e84-48d6540ac608.png)

The infinity GID 1931 still has an intersecting contour. If I delete the main contour, a smaller one is left behind.

![screen shot 2018-01-12 at 10 00 14](https://user-images.githubusercontent.com/7525512/34869626-677b4af4-f77f-11e7-8dbc-ecf70e114d90.png)


---

I apologise for uploads taking so long at Google Fonts. We're working hard to make the process easier. Atm, we have the tools to QA, we're just wrapping them so any font developers can use them and do this themselves.

**Comment by be5invis** [comment]
@m4rc1e 
I added an extra cleanup pass so that degenerated contours would be removed.
[iosevka-regular.zip](https://github.com/be5invis/Iosevka/files/1625709/iosevka-regular.zip)

**Comment by m4rc1e** [comment]
Thanks!

Apologies but I have to drop this for the time being. I will talk to @davelab6 so we can get this added.

There's a few things which don't fit our spec but I'm sure its nothing a bit of Shell and fontTools can't fix.

**Comment by be5invis** [comment]
@m4rc1e Please note that, Iosevka intensively uses OpenType features (you can see the complex things in `GSUB`). Please handle with care.

**Comment by m4rc1e** [comment]
@be5invis I have faith in you sir :-)

**Comment by be5invis** [comment]
@m4rc1e Also, please tell Dave that, Iosevka is a huge family with millions of possible variants...
It is preferred that, you publish these subfamilies only:

 - Iosevka
 - Iosevka Slab
 - Iosevka Term
 - Iosevka Slab Term

The "Type" and "CC" subfamily is made for special purposes (like "Type" is originally made for CoqIDE), for a general website providing webfonts, they are not needed to be provided.

**Comment by m4rc1e** [comment]
Thanks for the info

**Comment by be5invis** [comment]
@m4rc1e 
Iosevka 1.13.4 and above would also exclude all CJK-specific glyphs (they are used originally in Inziu).
I'd like to publish it during the weekend.

**Comment by be5invis** [comment]
I think most of them are fixed in v1.13.4. Closed.
