### ISSUE TITLE
iosevka-pack doesn't contain iosevka-term

### ISSUE THREAD

**Issue by kazufukurou** [be5invis/Iosevka#246]
* Your font version: 1.13.3

Release page says :
>The bundled iosevka-pack-#.#.# option contains all packages from 01.iosevka-#.#.# to 08.iosevka-cc-slab-#.#.#.

I assume 02-iosevka-term-#.#.# would be in that range, but there is no iosevka-term-* files in the iosevka-pack-1.13.3.zip.

**Comment by be5invis** [comment]
@kazufukurou Iosevka-pack is a distribution with only TTC files. In the TTCs you can have the fonts called Iosevka Term. If the TTC does not work you can use the separated TTFs intead.
Closed.
