### ISSUE TITLE
1.13.4 does not work correctly in Windows Command Prompt

### ISSUE THREAD

**Issue by aphoria** [be5invis/Iosevka#247]
* Your font version: (Release or git, version) 1.13.4
* Your font variant: Default and Term
* Your operating system (name and version): Windows 7
* Your application using Iosevka: (some Java applications may have problem in showing Iosevka properly. It is a bug in Java's GUI components.) Windows Command Prompt (CMD.EXE)

Describe your problem here. Provide pictures and files if necessary.
I am using 1.13.3 in my command prompt, but when I update to the 1.13.4, I can only get italics in the command prompt. Re-installing 1.13.3 fixes it.

**Comment by be5invis** [comment]
Have you tried to CLEAN INSTALL?
I do not have any legacy environments to test them.
The metadata are correct for them.

**Comment by be5invis** [comment]
Also if you are using Iosevka for CJK codepages and **please remember that such behavior is no longer supported by Iosevka itself. Please use [Sarasa](https://github.com/be5invis/Sarasa-Gothic) instead.**

**Comment by aphoria** [comment]
If by CLEAN INSTALL, you mean to remove the existing fonts before installing the new ones, then yes I have. I don't know anything about CJK codepages. I just know 1.13.3 works and 1.13.4 does not. What else should I look at?

**Comment by be5invis** [comment]
After removing existing versions, RESTART PC and delete all files named as "Iosevka*" under `C:\Windows\Fonts`. This is the "clean install", since font caching may cause problems.
If you are installing the "pack" version (TTC files) you can try to install the TTF version instead.

**Comment by aphoria** [comment]
Ok, I did not restart after deleting the fonts. I'll try that and report back. I am using the TTF files.

**Comment by be5invis** [comment]
That's strange. Maybe your font cache is messed up.

**Comment by aphoria** [comment]
After deleting the fonts, restarting my PC, and then installing 1.13.4, everything looks right and seems to be working correctly. Sorry for the false alarm.
