### ISSUE TITLE
Faster way to preview glyph changes

### ISSUE THREAD

**Issue by lynn** [be5invis/Iosevka#2476]
I am trying to add some characters to Iosevka.

Currently, if I edit a file in Iosevka's glyph code, I have to run `npm run build` and wait for about a minute to get a TTF file and see the changes. This makes it difficult to iterate on a glyph, especially when I'm still at the stage where I don't quite understand how the ptl files work.

And this is after configuring the build to produce just one weight and width of the font — otherwise it seems to take more like 10 minutes.

Is there some quick way to preview individual glyphs? What does your workflow look like, @be5invis?

Thank you for making such a cool font and software :)

**Comment by be5invis** [comment]
Well Iosevka glyphs could have a lot of dependency so it is really hard to create "on-demand" builds or incremental updates.

You could try disabling CV/SS (`noCvSs = true`) which could remove almost 60% of the glyphs, and the result will be must faster.

**Comment by lynn** [comment]
Thank you, that speeds things up significantly.

I also tried playing with `excludeChars` but I'm not sure if it's making the build faster, perhaps because of the dependencies you mention.

How do you deal with this when you add a new glyph to Iosevka? Maybe I am impatient, or my laptop is showing its age? 🙂

It could be interesting to profile which steps of the build take the longest.

**Comment by alexeyten** [comment]
`excludeChars` will not make build faster, see #607

Hinting runs ttfautohint program, that runs for several seconds on my computer. So excluding hinting should reduce build time.

**Comment by be5invis** [comment]
> How do you deal with this when you add a new glyph to Iosevka?

I am using a workstation so it is not horribly slow.
In the past it was so I added the geometry cache which already speed up build time by... 3X.
