### ISSUE TITLE
Monospace with ligation/ligature

### ISSUE THREAD

**Issue by jpotier** [be5invis/Iosevka#248]
Right now, we can either use/build Iosevka Term that is considered as monospace by fontconfig (spacing: 100) but without any ligations/ligatures *or* use/build Iosevka, considered to be a dual-spaced font by fontconfig (spacing: 90) and use ligations/ligatures.

Is there any way to have a mono font *with* ligations/ligatures? (fyi that's working for fira code).

**Comment by be5invis** [comment]
You can try to comment line 232 of `parameters.toml`.

https://github.com/be5invis/Iosevka/blob/master/parameters.toml#L232

I am not sure whether the ligations work in Term-spacing, and some since Linux applications have problems handling ligations, I added this line.

**Comment by jpotier** [comment]
👍 lemme try this

**Comment by be5invis** [comment]
Adding this into `parameters.toml`

```toml
[termlig]
spacing = 0

[termlig.adds]
family = ' Term'
```

and build a `termlig` variant following [BYOS](https://github.com/be5invis/Iosevka#build-your-own-style) is another solution.

**Comment by jpotier** [comment]
https://github.com/jpotier/Iosevka/releases/tag/v1.13.41 I'm going there for now, almost done building

**Comment by jpotier** [comment]
https://github.com/jpotier/Iosevka/tree/v1.13.42 Should be the second solution. However kitty is not picking up the ligatures. :/

**Comment by jpotier** [comment]
Also, test:

    [nix-shell:~]$ hb-shape --cluster-level=1 --show-extents /nix/store/7h1pcvcwhfb8fpkl1n25l5khjrslla7g-iosevka-hskl-1.13.42/share/fonts/iosevka-hskl/iosevka-hskl-regular.ttf '<|'
    [gid31=0+512<61,625,410,-502>|gid95=1+512<215,920,82,-1092>]

**Comment by be5invis** [comment]
@jpotier How dis you built that?
The config should be `design='termlig ligset-haskell'`
Also could you please provide the TTF generated?

**Comment by jpotier** [comment]
I used `design='ss08 termlig haskell'`. Here's the regular termlig TTF: https://framadrop.org/r/QM9weOcON2#jzr4gqbFtFDlc754GJFkhzdG0dO6SNpiBiZm+39wrQ0=

**Comment by be5invis** [comment]
@jpotier I see what's wrong. Hold on.

**Comment by be5invis** [comment]
In `features.ptl` it sill uses `spacing > 0` to detect whether ligations are enabled.

**Comment by jpotier** [comment]
Ah! Ok, I'll remove this test.

**Comment by be5invis** [comment]
@jpotier I've commited an update to `master` that should work. The `termlig` style directive is also included.

**Comment by jpotier** [comment]
Ok, building and testing it now

**Comment by jpotier** [comment]
Maybe this comes from my VTE (kitty). What do you think?

**Comment by be5invis** [comment]
The file is correct and the ligations are working, but your terminal **shrinked** the glyphs with its ink box wider than 1/2em.
**I think you should file a bug to Kitty.**

**Comment by jpotier** [comment]
Yeah, I'm also talking to the kitty team :D

**Comment by Janiczek** [comment]
Given the conversation in the Kitty repo:

> That's not going to work in kitty. There are two types of ligatures that will work, either substitute a single glyph for '<-' that is two chars wide or a dummy glyph + single glyph that is two chars wide with a negative left bearing.

Is there a plan to implement ligatures in one of these two styles?

**Comment by be5invis** [comment]
No. Such methods are not strong enough to hold all the existing ligations, and may cause unexpected problems.

A proper terminal should be able to handle all valid OT GSUB features, rather than assuming the typeface’s GSUB is written in a specific format.

发自我的 iPhone

在 2018年7月16日，05:34，Martin Janiczek <notifications@github.com<mailto:notifications@github.com>> 写道：


Given the conversation in the Kitty repo:

That's not going to work in kitty. There are two types of ligatures that will work, either substitute a single glyph for '<-' that is two chars wide or a dummy glyph + single glyph that is two chars wide with a negative left bearing.

Is there a plan to implement ligatures in one of these two styles?

**Comment by thenewvu** [comment]
Hey guys, I used [Ligaturizer](https://github.com/ToxicFrog/Ligaturizer) to patch **Iosevka Term** fonts with [Fira Code](https://github.com/tonsky/FiraCode) ligatures. If someone had been struggling with [Kitty](https://github.com/kovidgoyal/kitty) couldn't render **Iosevka**'s ligatures correctly, I believe this solution can solve your problem. To save some time for the rest of the world, I uploaded those patched fonts below.

[iosevka-term-with-fira-code-ligatures.zip](https://github.com/be5invis/Iosevka/files/2300381/iosevka-term-with-fira-code-ligatures.zip)

Thanks to makers of **Iosevka** and **Fira Code** for great works.

**Comment by thenewvu** [comment]
I'm just the guy who uses the tool, so I'm not sure what happens internally when building the variant.

**Comment by blueyed** [comment]
@thenewvu 
But how did you use Ligaturizer?  I'm just asking for steps to reproduce the output, so it could be turned into a PKGBUILD.

**Comment by thenewvu** [comment]
@blueyed  Oh .. I just followed its readme, I only did 2 steps to get the variant as remember:

1. Clone the https://github.com/ToxicFrog/Ligaturizer to /path/to/ligaturizer
2. Put Iosevka fonts into the /path/to/ligaturizer/input-fonts
3. Run `make`.
4. Get patched fonts in /path/to/ligaturizer/fonts/output-fonts

The tool may changes the font face name with the prefix `Liga`, but with Iosevka, I didn't see that. It may depend on something.

**Comment by mustaqimM** [comment]
@thenewvu How did you get the spacing to be `100` in the patched fonts?

**Comment by blueyed** [comment]
Note that Kitty currently does not handle "auto" for bold etc with the fonts from @thenewvu, but https://github.com/kovidgoyal/kitty/pull/1191 fixes this for me.

**Comment by alvivi** [comment]
Here it is  @thenewvu's patched font with [nerd-fonts](https://github.com/ryanoasis/nerd-fonts) glyphs:

[iosevka-term-nerd-single.zip](https://github.com/be5invis/Iosevka/files/3210460/iosevka-term-nerd-single.zip)

**Comment by sterpe** [comment]
Adding liga-iosevka-2.2.1, which is another Fira Code build with Ligaturizer, but has a distinct name (Liga Iosevka) so it doesn't clash with genuine Iosevka Term, if installed.

[liga-iosevka-2.2.1.zip](https://github.com/be5invis/Iosevka/files/3388580/liga-iosevka-2.2.1.zip)

**Comment by esn89** [comment]
@alvivi 

Can you show me how you managed to patch iosevka with ligatures and with working nerd fonts?

**Comment by dynamotn** [comment]
I rewrite another script and fixed some case, add (0xFF and 1920x1080) from FiraCode 3.1. Anyone can have a look and download at https://github.com/dynamotn/font-collection/tree/master/files/DIY/Iosevka
