### ISSUE TITLE
Ability to rename existing weights/widths/slopes in custom build.

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#2488]
In my custom build I've wanted to rename "Heavy" weight to "Black" and "Extended" width to "Expanded".
Currently if I try doing this, it generates the ttf/etc. files with the desired _file_ name, but it still says "Heavy" and "Extended" in the Windows fonts menu.

**Comment by be5invis** [comment]
You mean customizing the names in `packages/font/src/naming/index.mjs`?

**Comment by jmcwilliams403** [comment]
> You mean customizing the names in `packages/font/src/naming/index.mjs`?

Yes, assuming the names listed in this file are the reason that compiled fonts always show the same names in the fonts menu.

**Comment by jmcwilliams403** [comment]
Is this able to be put in backlog?
