### ISSUE TITLE
Git tag 1.14.0 points to same commit as 1.13.4

### ISSUE THREAD

**Issue by undu** [be5invis/Iosevka#250]
Right now, the tag of the release 1.14 points to commit f414e11ae959941a30f3fd4802d1a215306a5c8c, which is the same commit as the tag 1.13.4

The oldest commit that could be tagged as 1.14.0 is 171951ffad14713cfc6c6b816f385ca6e4324d68, which reflects the change of version.

**Comment by be5invis** [comment]
fixed
