### ISSUE TITLE
Further diacritics on Ü are truncated out of line

### ISSUE THREAD

**Issue by Artoria2e5** [be5invis/Iosevka#251]
* Your font version: 1.13.3
* Your font variant: "Iosevka", just Iosevka
* Your operating system (name and version): Windows 10
* Your application using Iosevka: notepad, notepad++, mintty

Variations of Ü with more diacritics (Ǖ Ǘ Ǚ Ǜ) show up as Ü in software as the secondary discritics are truncated. This problem may lead to problems with displaying all-uppercase pinyin text (permitted for special nouns). Perhaps some space in between can be squeezed away?

**Comment by be5invis** [comment]
Any images?

**Comment by Artoria2e5** [comment]
Iosevka, notepad

![image](https://user-images.githubusercontent.com/6459309/36637706-fa10f448-19af-11e8-9e33-4e6299dcbeae.png)
