### ISSUE TITLE
Latin Epigraphic Letter Archaic M (`U+A7FF`) (ExtIPA Voice Quality Symbol)

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#2517]
- The requested characters are ...
  - [x] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [ ] Diacritic / Mark
  - [ ] Symbol
- The requested characters are used in ...
  - [ ] The alphabet / character set of a natural language.
  - [ ] The alphabet / character set of a constructed language.
  - [x] The alphabet / character set of a transliteration or notation system.
  - [ ] Mathematical or other professional use in documents.
  - [ ] The symbol set of a programming language. For the languages that support using arbitrary symbols, please provide usages in well-known components or libraries.
  - [ ] The symbol set of a command-line program.
- [x] For each character you requested, there is at least a monospace/programming font supports this character. Provide images below.

------

`ꟿ`
Noto Sans Mono:
![image](https://github.com/user-attachments/assets/28beded1-dd49-4353-9dd6-30f3ac0bfd98)
Fairfax HD:
![image](https://github.com/user-attachments/assets/c6bdc5cc-10a5-4138-b56f-ee82debd9aa8)
Everson Mono:
![image](https://github.com/user-attachments/assets/fc9acddb-5ce4-4604-8cf1-cbf18af78eee)
Julia Mono:
![image](https://github.com/user-attachments/assets/1e548d90-b989-472a-b784-aefea3ce991e)
DejaVu Serif:
![image](https://github.com/user-attachments/assets/8c6a06ca-f82e-4bdb-b82b-a7b13c8f683e)
Gentium Plus:
![image](https://github.com/user-attachments/assets/e7e9b983-3025-4099-a4b5-fd1deb169e68)
Doulos SIL:
![image](https://github.com/user-attachments/assets/f6da1ed3-9eb5-4572-bb50-3c6ebb32e5b0)
Charis SIL:
![image](https://github.com/user-attachments/assets/42f6da94-f21a-4e3f-a762-88afa7a60ece)

See:
* https://en.wikipedia.org/wiki/Voice_Quality_Symbols#Phonation_types
* https://en.wikipedia.org/wiki/Spasmodic_dysphonia#Voice_quality_symbol
* https://en.wiktionary.org/wiki/%EA%9F%BF#Translingual

On a side note, this is also the last of the non-casing epigraphic letters in Latin Extended-D:
![image](https://github.com/user-attachments/assets/dde9aaa6-c20f-4d1f-bdc4-dcc8384b5494)

**Comment by be5invis** [comment]
I am wondering which variant selector should this follow... Or just not following anything (as it being so unique)?

**Comment by jmcwilliams403** [comment]
> I am wondering which variant selector should this follow... Or just not following anything (as it being so unique)?

I was thinking just have it follow nothing except for whether the font is `SLAB`.
