### ISSUE TITLE
Possible glyph adjustment for combining breve when used with Cyrillic characters.

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#2518]
```
Ӑӑ Ӗӗ Йй Ўў
Ăă Ŭŭ
```
Liberation Serif:
![image](https://github.com/user-attachments/assets/a61a119d-1b2d-49a5-a56f-93eea8b8f689)
PT Serif:
![image](https://github.com/user-attachments/assets/8724a242-d958-47fa-b2fe-feed19707832)
IBM Plex Serif:
![image](https://github.com/user-attachments/assets/e0b3b58a-fe2b-4606-a572-3580e695fe6c)
Noto Serif:
![image](https://github.com/user-attachments/assets/2b89224e-78de-4257-b7fc-f7f99566d946)
Vollkorn:
![image](https://github.com/user-attachments/assets/45d32229-99ee-46c2-8862-5966daf15439)
Gentium Plus:
![image](https://github.com/user-attachments/assets/9e661fa2-7b76-4b36-9117-07cd0bed7ad1)
Charis SIL:
![image](https://github.com/user-attachments/assets/fb21f4ea-31d8-4fb1-9da2-111c9041ad62)

**Comment by jmcwilliams403** [comment]
The effect also exists for sans-serif but is often much subtler:
`йŭ`
Consolas:
![image](https://github.com/user-attachments/assets/f7657bd6-514c-402a-b43d-37966b62cd63)
Liberation Mono:
![image](https://github.com/user-attachments/assets/2ac806de-0547-49a9-b862-f01765ec6fb4)
Source Code Pro:
![image](https://github.com/user-attachments/assets/fa8500dd-6e18-4059-bc22-52eb50621110)

**Comment by be5invis** [comment]
I don't think making two highly similar Breve glyphs is necessary.
Ef, OTOH, is valid.

**Comment by jmcwilliams403** [comment]
What about if it were treated as a sort of "serifed breve" and only changed under slab?

**Comment by be5invis** [comment]
I don't see slab serif fonts using significantly different design for this mark.
