### ISSUE TITLE
Saltire part in HEAVY CIRCLED SALTIRE (`U+2B59`) is off-center (i.e. effectively broken) under Quasi-Proportional.

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#2528]
`⭙`
Monospace for comparison:
![image](https://github.com/user-attachments/assets/fcd63ad9-a733-40f9-97d4-bcace21a676f)
Aile:
![image](https://github.com/user-attachments/assets/c6a22be7-fbce-4c20-a673-8e15456f5d60)
It also appears broken in the website specimen:
![image](https://github.com/user-attachments/assets/b1679812-ef37-4e5d-8eaf-dbedacf2f2e2)

**Comment by Logo121** [comment]
i don't have time to make a pr, but looks like this is the problem:
https://github.com/be5invis/Iosevka/blob/d319ad2c283ec23c1cc8db81c82010a730160475/packages/font-glyphs/src/symbol/pictograph/iec-power-and-playback.ptl#L30-L31

i guess `leftFW` and `rightFW` are not the correct variables for these (replace with `(df.middle - sqaureRadiusFW)` and `(df.middle + sqaureRadiusFW)`), but considering it is defined as
https://github.com/be5invis/Iosevka/blob/d319ad2c283ec23c1cc8db81c82010a730160475/packages/font-glyphs/src/symbol/pictograph/iec-power-and-playback.ptl#L11-L12

but i would assume that even if it is not orthogonal, it would be centered at least.

in my local build: (Aile/Etoile is extended so it looks like the middle cases)
![image](https://github.com/user-attachments/assets/47d68f5b-95e0-418d-849c-e2ac4e8e0657)
is the `MosaicWidth` value not accurate for extended/condensed versions?
