### ISSUE TITLE
Asking for permission to patch Iosevka variants with Nerd Fonts in another repository

### ISSUE THREAD

**Issue by asperan** [be5invis/Iosevka#2531]
Hi! First of all, thanks for designing this awesome font and all of its variants!

I'd want to use one of the variants in a configuration which requires Nerd Font glyphs, but Iosevka is provided Nerd-Font-patched only in the main styles.

As this may not be of your interest, Do you mind me running a repository in which the Iosevka variants are patched with Nerd Font?

**Comment by be5invis** [comment]
Iosevka is licensed under OFL, so you do not need my "approval" for derivatives or composites. Just go for it.
