### ISSUE TITLE
`e` with rather straight lower part

### ISSUE THREAD

**Issue by casinca** [be5invis/Iosevka#2533]
- [✔ ] The requested variant shape **does not go too far away from Iosevka's design**.
- [✔] The requested variant **does not conflict with any characters in Unicode that Iosevka currently supports**.
- [✔] For each variant you requested, there are at least **two monospace/programming fonts created by different designers supported the requested variant**. Provide images below.

------
It would be nice to have a slight variation for one of the most used character, atm there are only 2 variants for  `e`.

My variant request is inspired by the Consolas font (there are other fonts with that specificity like Menlo/Monaco, it's not uncommon) where the lower part of the `e` do not rise at the end (unlike the 2 current available variants), but remains relatively straight.

See the comparison below and a quick edit of what i believe it would look like
Thank you.

![image](https://github.com/user-attachments/assets/16bbd6b2-3aa0-4c36-be76-5ca2c35fb39c)

**Comment by be5invis** [comment]
This is a style change I think -- changing to "humanist" style.

**Comment by jmcwilliams403** [comment]
Related: #1287

**Comment by Logo121** [comment]
this is related to #1287, another request for a more open hook to improve readability(?). Someone there even pointed out `e` having the same issue

the alternative is to have a _completely_ flat hook, like `fgjty` or even `il` (these have "slightly curly" tail variants too for some reason)

**Comment by be5invis** [comment]
Merge into #1287. Close.
