### ISSUE TITLE
Left and right square brackets not aligned vertically

### ISSUE THREAD

**Issue by shniubobo** [be5invis/Iosevka#2545]
Right brackets can be one pixel shorter than left ones, when used with a certain font size, weight or style. This can be reproduced in several applications, as well as in the preview function provided by Windows Settings.

This may be related to #266, but is not duplicate of that issue.

# Screenshots

### Reproducible with font size 11

![](https://github.com/user-attachments/assets/234b8e17-f1b8-485b-afd2-e2534d452adb)

### NOT reproducible with font size 12

![](https://github.com/user-attachments/assets/7807f4d0-1ada-4726-b074-107639e7bc28)

### Reproducible with font size 14

![](https://github.com/user-attachments/assets/f5b4028f-6b6f-43d8-b795-793a3c1120dc)

### Reproducible with font size 15

![](https://github.com/user-attachments/assets/fcde6756-b1d5-4f62-ba2d-7d3faf13c542)

### NOT reproducible with font size 16

![](https://github.com/user-attachments/assets/ebac1220-c1c0-4c20-a805-a740838815bb)

### Reproducible with font size 11

![](https://github.com/user-attachments/assets/31ba1a38-33fc-460a-86bc-3a032a6bc230)

### NOT reproducible with font size 12

![](https://github.com/user-attachments/assets/3d0a3703-268a-427b-ac5d-be0baff914b5)

However, when taking this screenshot, I noticed that the left bracket is horizontally one pixel longer than the right one.

---

* Your font version: v31.8.0
* Your font variant: Default and SS03 (these two are what I have tried; probably also reproducible with other variants)
* Your operating system (name and version): Windows 22631.4317
* Your application using Iosevka: VS Code and Windows Terminal

**Comment by Logo121** [comment]
Well, it *is* the same issue as #266 (same cause, at least).

**Comment by shniubobo** [comment]
> Well, it _is_ the same issue as #266 (same cause, at least).

They are *similar* since they both have something to do with hinting, but they are not the *same* because they need different solutions. In #266, the misalignment was caused by FreeType's autohinting, and the solution was to disable that and use Iosevka's built-in hinting. Here the situation is the opposite - I have to use the unhinted fonts to work around this issue, that is, the issue is caused by the built-in hinting.
