### ISSUE TITLE
How to enable ligatures in Gvim?

### ISSUE THREAD

**Issue by kshenoy** [be5invis/Iosevka#255]
* Your font version: 1.14.1
* Your font variant: Default
* Your operating system (name and version): RHEL 6
* Your application using Iosevka: Gvim

How do I enable ligatures in Gvim? Do I need to download and install anything else apart from the Default pack?

**Comment by Baldrs** [comment]
You need patched gvim, see this [thread](https://github.com/vim/vim/issues/418)

**Comment by kshenoy** [comment]
Oh, ok. Thanks for the great font and all your work on it :)
