### ISSUE TITLE
Serifs of U+0284 and U+10798 are inconsistent with the variants of U+006A LATIN SMALL LETTER J

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#2569]
U+0284 LATIN SMALL LETTER DOTLESS J WITH STROKE AND HOOK and U+10798 MODIFIER LETTER SMALL DOTLESS J WITH STROKE AND HOOK always have serifs in Iosevka Slab and never have serifs in Iosevka, even when a character variant is enabled that removes or adds the serif of U+006A LATIN SMALL LETTER J. The serif of U+0284 and U+10798 should follow the variants of U+006A.

Here are U+006A, U+0284, and U+10798 ⟨jʄ𐞘⟩ in Iosevka Slab with 'cv45' set to 1, 3, 5, and 7:
![jjjj ʄʄʄʄ 𐞘𐞘𐞘𐞘](https://github.com/user-attachments/assets/b8273f13-ee99-4f97-8651-733bb3a9b7b6)

Here are U+006A, U+0284, and U+10798 ⟨jʄ𐞘⟩ in Iosevka with 'cv45' set to 2, 4, 6, and 8:
![jjjj ʄʄʄʄ 𐞘𐞘𐞘𐞘](https://github.com/user-attachments/assets/9d3a78bf-a6c2-4315-b1b4-195446497399)

---

* Your font version: 32.0.0
* Your font variants: Iosevka Extended and Iosevka Slab Extended

**Comment by be5invis** [comment]
Regression (?) by #2562.
