### ISSUE TITLE
A better design for `!==` ?

### ISSUE THREAD

**Issue by w9** [be5invis/Iosevka#257]
First of all great work on Iosevka! I have been using it as my default font for terminal and coding for about a year now and I absolutely appreciate its attention to detail.

In my humble opinion, the very reason why ligatures improve readability of the code is *not* because they emulate hand-written symbols, but that they make a multi-character symbol more "united", visually "grouped", and thus more easily made out when sitting tightly among other characters.

A ligature that completely changes the morphology of the original combination creates unnecessary mental hurdles when edited. Ligating `!==` as `=≠=` surprises programmers subliminally (if only for a fraction of a second) when they try to e.g. change `!==` to `==`. In an editor that doesn't break the ligature when cursor is on top of it (like the JetBrain suite, or any webkit-rendered editior), I could see someone putting their cursor on top of the middle `≠` trying to delete it, only to find out that it results `!=` instead of `==`.

That's why I think ligatures should be "subtle", and as much as possible maintained the character shape in each grid. I very much like your design for the ligature `<!--`, which unites the four characters without obliterating their original shape. In fact, most of other ligatures comply the above rule beautifully (`<|>`, `(*)`, `=>=`, to name a few). I was wondering if you are interested in making a similar design for `!==` and `!=`.

**Comment by w9** [comment]
Huh ... I just discovered the lengthy discussion in #56 and I now understood the history of this decision. I saw that you were on my side to begin with but eventually convinced by others. In any case, I stand by my opinion, so I guess in this case a variant for this ligature would be appreciated.

**Comment by brandondees** [comment]
I'd be happy to have variant ligature options, but I really like the font having the signs for things like 'not equal to' etc. as used in mathematics, for what it's worth.

**Comment by be5invis** [comment]
How about an option to disable "breaking ligatures" under `ccmp`?

**Comment by w9** [comment]
@be5invis That would be great. BTW I think you may call them "aggressive ligatures" or "advanced ligatures".

I know that we might be the minority here, but would you consider making it the default? Since the non-aggressive ligatures are less controversial and setting it as the default makes the font more approachable to new users.

**Comment by maximbaz** [comment]
@w9 I agree on the issue, however I believe a different approach should be taken to solve it. In my mind, the application should not render ligatures for the characters under cursor, but render "raw characters" instead. That way, it doesn't matter how "aggressive" the ligature is, as long as it's meaning is clear.

Qterminal and Konsole terminals reportedly have this behavior, I created [a request](https://github.com/kovidgoyal/kitty/issues/461) for kitty terminal to implement the same.

Desired behavior:

![ligatures_off](https://cloud.githubusercontent.com/assets/20362502/22620945/a7e15214-eb0f-11e6-8f01-de7c4256f9b4.png)

**Comment by eproxus** [comment]
I'm in the camp of the least surprise principle of making the ligatures resemble their character counter parts, but one thing I find particularly irritating with Iosevka is that `!==` and `!=` renders to  `=≠=` and `≠` but `=/=` and `/=` doesn't even have a ligature.

**Comment by be5invis** [comment]
@eproxus 
`/=` has ambiguity so it is not enabled by default (unless you are under Haskell feature tag).
`=/=` could be moved to default. However, a problem is that there are reports that some IDEs crashed when dealing with `!===`, so I have to remove some of the long ligatures.

**Comment by eproxus** [comment]
@be5invis Tried the Haskell feature tag. `/=` now works, but there seems to be no ligature for `=/=` (the last two characters get's the ligature for `/=` instead).

**Comment by eproxus** [comment]
@be5invis Is there a plan for supporting `=/=` as well? It's used in Erlang, so it would be real handy to have 🙂

**Comment by chetzof** [comment]
Is it possible to disable the =/= and leave the others? This specific ligature is just too different from the original symbols and distracts me from the process.

I'm in love with this beautiful font, thanks you very much for your work, I will recommend it to all my colleagues!

**Comment by be5invis** [comment]
reactivate

**Comment by be5invis** [comment]
@w9 @chetzof @eproxus @maximbaz @brandondees 
I added the control in the `dev` branch. You can checkout `calt-*` style sets and custom your ligation sets.
To disable ligation for `!=`, just exclude `calt-exeq`.

**Comment by be5invis** [comment]
The current `calt` set is:
```js
["calt-center-ops", "calt-arrow", "calt-html-comment", "calt-trig", "calt-llgg",
 "calt-eqeq", "calt-ineq", "calt-exeq", "calt-plusplus", "calt-colons"]
```

**Comment by eproxus** [comment]
@be5invis So if I understand this correctly, enabling both `calt-exeq` and `calt-slasheq` would enable the respective ligatures for their character equivalents?

**Comment by eproxus** [comment]
@be5invis Would it also be possible to add ligation for `=/=`?
