### ISSUE TITLE
Iosevka font results in the fixed version instead of the default version

### ISSUE THREAD

**Issue by ukiran03** [be5invis/Iosevka#2575]
Every method I use to install the Iosevka font results in the fixed version instead of the default one. This issue started with the 32.0.1 release
---

* Your font version: 32.0.1
* Your font variant: Iosevka Default
* Your operating system (name and version): Linux
* Your application using Iosevka: Emacs, Alacritty

```

**Comment by be5invis** [comment]
Not repro on my system. And we did not modify the metdata in v32.
Maybe you can try completely unisntall existing version, restart your system and then reinstall?

**Comment by ukiran03** [comment]
Sorry to bother you, but I am unable to download the default Iosevka font on my machine. Every time, I end up with the fixed variant of Iosevka.
---
* Your operating system (name and version): Arch Linux

**Comment by Logo121** [comment]
You're going to need more information than that. If you're using Arch Linux, which package are you using to install this font?

**Comment by AndydeCleyre** [comment]
How exactly are you determining that it's the fixed variant?

**Comment by be5invis** [comment]
Are you downloading from releases, or from package manager?
The AUR package is not maintained by me but by @Markus00000.

**Comment by ukiran03** [comment]
I installed **extra/ttc-iosevka** through pacman, which brought Iosevka-{ExtraLight,Heavy,Thin...}.ttc of 9 files to my system
dir: /usr/share/fonts/TTF/
Additionally,
I installed from the releases [Iosevka v32.0.1](https://github.com/be5invis/Iosevka/releases/download/v32.0.1/SuperTTC-Iosevka-32.0.1.zip), the latest SuperTTC package

**Both only resulted showing Iosevka Fixed variants**

# How I test:
## In emacs:
```
(set-frame-font "Iosevka 12" nil t)
(error "Font not available" #<font-spec nil nil Iosevka nil nil nil nil nil 12.0 nil nil nil ((:name . "Iosevka 12") (:user-spec . "Iosevka 12"))>)
```
```
(set-frame-font "Iosevka Extended 12" nil t)
(error "Font not available" #<font-spec nil nil Iosevka\ Extended nil nil nil nil nil 12.0 nil nil nil ((:name . "Iosevka Extended 12") (:user-spec . "Iosevka Extended 12"))>)
```
```
(set-frame-font "Iosevka Fixed Extended 12" nil t)
nil ;; no error and sets the font
```
## fc-list
```
[ ~ 0 ] $ fc-list ':' file | grep -v 'IosevkaNerd' | grep Iosevka
/usr/share/fonts/TTF/Iosevka-Regular.ttc:                        
/usr/share/fonts/TTF/Iosevka-ExtraLight.ttc:                     
/usr/share/fonts/TTF/Iosevka-Heavy.ttc:                          
/usr/share/fonts/TTF/Iosevka-Thin.ttc:                           
/usr/share/fonts/TTF/Iosevka-SemiBold.ttc:                       
/home/ukiran/.local/share/fonts/Iosevka.ttc:                     
/usr/share/fonts/TTF/Iosevka-Light.ttc:                          
/usr/share/fonts/TTF/Iosevka-ExtraBold.ttc:                      
/usr/share/fonts/TTF/Iosevka-Medium.ttc:                         
/usr/share/fonts/TTF/Iosevka-Bold.ttc:                               
```
## alacritty, xterm
same problem as in emacs

**Comment by Logo121** [comment]
I'm not familiar with Emacs, but I think some of these applications do not support "non-fixed" fonts where a glyph can occupy either 1 or 2 spaces.

Did you test it on other applications like GUI text editors or web browser?

**Comment by ukiran03** [comment]
I also tested with Gedit (gnome text editor)
The listed Iosevka font variants are fixed variants only.

**Comment by be5invis** [comment]
Could you try uninstall the package from pacman and manually clean install the fonts from releases?
Or maybe you can try the TTF version?
I checked the TTC's metadata, it is completely valid.

**Comment by ukiran03** [comment]
I will try it. I am fine with my situation, and I think there must be
an issue on my side. I'll figure it out once I have the time. If I
find anything, I will post it here. Thank you for your time and
patience.
