### ISSUE TITLE
Missing pseudographics

### ISSUE THREAD

**Issue by sergeevabc** [be5invis/Iosevka#258]
There is a Windows console emulator called ConEmu. it allows you to [set fonts][1] for general output and for pseudographics. In case Iosevka is used for pseudographics, I see a missing glyph (arrow). Why?

| Iosevka 1.14.1  | Consolas |
| ------------- | ------------- |
| ![](https://pli.io/4289n.png)   | ![](https://pli.io/421JO.png)  |

[1]: https://conemu.github.io/en/SettingsMain.html

**Comment by be5invis** [comment]
Iosevka does not have that "thin triangle" character. Maybe you should raise a request under #81.
(I am very busy currently for some CJK project, so very sorry for not able to include that fast).
Closed.
