### ISSUE TITLE
Unmodified build gets stuck

### ISSUE THREAD

**Issue by lunik1** [be5invis/Iosevka#2580]
An unmodified iosevka build is getting stuck on my system.

Steps to reproduce:
- `git clone https://github.com/be5invis/Iosevka.git --depth=1`
- `cd Iosevka`
- `npm install`
- `npm run build ttf::Iosevka`

This build never completes, but does not crash/fail either. I have left a system overnight with no progress.

---

* Your font version: 32.0.1 (9df6364)
* Your font variant: Standard
* Your operating system (name and version): NixOS unstable
* Your application using Iosevka: n/a

If you have problem when building Iosevka, please provide these information:

* Your Node.js version: v20.18.0
* Your `params/parameters.toml`, paste if modified:
  ```
  Not modified
  ```
* Your `build-plans.toml`, paste if modified:
  ```
  Not modified
  ```
* Your `private-build-plans.toml`, if present:
  ```
  Not present
  ```
* The detailed error log:
Build log (with `--jCmd=1`):
https://gist.github.com/lunik1/a4ce2770dd7af715dd7961554552a069

**Comment by be5invis** [comment]
What is your hardware spec?

Also maybe you can try build again to see if it is a real hang or it is just very slow.

**Comment by lunik1** [comment]
I've tried a few times and observed it on two different machines.

**Comment by jmcwilliams403** [comment]
> I've tried a few times and observed it on two different machines.

Both NixOS?

**Comment by lunik1** [comment]
Yes

**Comment by lunik1** [comment]
This is a kernel bug (!), lkml thread with details: https://lore.kernel.org/io-uring/2024110620-stretch-custodian-0e7d@gregkh/T/#e57570b5f8f2fc00d5a17cfe18ffeeba9fc23a43d

Anyone encountering this needs to update to 6.6.50 or 6.1.116
