### ISSUE TITLE
Iosevka Fixed/Term: Letter m is too dense, causes heavy contrast to other characters

### ISSUE THREAD

**Issue by lf94** [be5invis/Iosevka#2581]
**Is your feature request related to a problem? Please describe.**
I find the letter m is particularly squished. Visually I find it sticks out from every other english glyph in text. It kind of ruins visual contrast.

**Describe the solution you'd like**
I'd like to see the letter m be less contrasting in words and sentences. How font designers do this is up to them. Maybe it's as simple as giving more space between the stems of the m.

**Describe alternatives you've considered**
I've looked at the variants with the middle stem cut. It kind of helps, but something is off about it meshing with the rest of the font when making the variant change.

**Additional context**

**Comment by lf94** [comment]
Here's a screenshot to demonstrate this:

![out](https://github.com/user-attachments/assets/8e720c54-5a62-497d-b99b-ad2e6c5e2716)

**Comment by AndydeCleyre** [comment]
Regarding the short stem variants, can you elaborate on

> . . . something is off about it meshing with the rest of the font when making the variant change.

?

**Comment by Logo121** [comment]
> How font designers do this is up to them.

This is really vague too. While Iosevka already thins the stroke of more crowded glyphs like `m` (more visible on higher weights), over doing it risks making them stick out in a different way.

Do you have examples of this problem being handled well in other fonts?

And while also not a perfect solution either, have you tried the "texture healing" feature in #2081?

**Comment by lf94** [comment]
I'm not a font designer so I'm unable to suggest anything useful.

> Regarding the short stem variants, can you elaborate on

Simply put the m feels like it loses its relationship with n. Additionally opting for the short stem feels like normal/default m is being left as too dense and will never be adjusted.

> over doing it risks making them stick out in a different way.

Yes super fair. I was hoping the font designers would come together and solve this hard problem.

> Do you have examples of this problem being handled well in other fonts?

I don't. Quickly looking at various fonts I've used in the past, Source Code Pro seems to render m pretty nicely ( https://fonts.google.com/specimen/Source+Code+Pro look at the 400 16px example).

> And while also not a perfect solution either, have you tried the "texture healing" feature in https://github.com/be5invis/Iosevka/issues/2081?

This is a feature I've really wanted to use but the terminal I used does not support it and in general it seems like an advanced font rendering feature I'd rather not rely on and instead have the font itself be designed as perfect :) (Which by the way Iosevka pretty much is!)

Thank you both very, very much for the responses. I really appreciate your time and efforts. Let me know if I can get back to you with anything else.

**Comment by danarnold** [comment]
I'll add my opinion here: not to be "that guy", but I actually preferred the old rendering to the new thinner rendering on the m. I think the new m renders too thin at smaller point sizes, especially with colored text. Here's a comparison at size 10:

new rendering (iosevka fixed extended 32.1.0)
![Screenshot 2024-11-29 160329](https://github.com/user-attachments/assets/5c876af6-6662-4dc0-bc79-dcb89f125744)
old rendering (iosevka fixed ss04 extended 31.9.1) (ss04, but that doesn't affect the m)
![Screenshot 2024-11-29 160347](https://github.com/user-attachments/assets/030f8cbc-bff0-414c-b857-44775542b5f2)

This is rendered on Windows 11 in Windows Terminal.

To me, the old version matches the thickness of the other strokes much better than the new, lighter thickness.

**Comment by sergv** [comment]
This is a kind of problem that contextual alternatives (aka texture healing) can help with by giving monospace `m` more breathing space when it's surrounded by 'narrow' glyphs, cf https://github.com/be5invis/Iosevka/issues/2081.
