### ISSUE TITLE
mac os : case sensitive file system

### ISSUE THREAD

**Issue by pavelrevak** [be5invis/Iosevka#2582]
Describe your problem here. Provide pictures and files if necessary.
can not install on mac os with case sensitive file system

npm install not see Package.json, because there is package.json

---

* Your font version: (Release or git, version) 
* Your font variant:
* Your operating system (name and version):
* Your application using Iosevka: 

If you have problem when building Iosevka, please provide these information:

* Your Node.js version: 23
* Your `params/parameters.toml`, paste if modified:
  ```
  paste here
  ```
* Your `build-plans.toml`, paste if modified:
  ```
  paste here
  ```
* Your `private-build-plans.toml`, if present:
  ```
  paste here
  ```
* The detailed error log:
  ```
  paste here
  ```

**Comment by be5invis** [comment]
There is no mention of `Package.json` anywhere in Iosevka codebase. Maybe you shall contact the owner of your font package.

**Comment by pavelrevak** [comment]
it's a coincidence that I saw somewhere that the name should be `Package.json` (even though it is `package.json` in the documentation) and after renaming it started to install, until then `npm install .` pretended that no package existed. probably the problem will be on the `node` side. thank you for your time.
