### ISSUE TITLE
Monospace in plasma

### ISSUE THREAD

**Issue by JackalopeGit** [be5invis/Iosevka#259]
Last font version from the arch-linux package. 

Plasma font manager not shows iosevka in the monospace families, so it cant selected as font for any monospace-font-plasma usage.

**Comment by be5invis** [comment]
Perhaps you could try Iosevka Term. The TTF version, not TTC.

发自我的 iPhone

在 2018年3月24日，04:08，Damir <notifications@github.com<mailto:notifications@github.com>> 写道：


Last font version from the arch-linux package.

Plasma font manager not shows iosevka in the monospace families, so it cant selected as font for any monospace-font-plasma usage.

**Comment by nivaca** [comment]
Same problem here! I3wm on Arch linux.

**Comment by AndydeCleyre** [comment]
@JackalopeGit @nivaca 

Please check out the AUR packages `ttf-iosevka-term-custom-git` and `ttf-iosevka-termlig-custom-git`. You can choose your variants by editing the pkgbuild or setting the `IOSEVKA_DESIGN` environment variable (defaults to `v-l-tailed v-i-hooky v-g-opendoublestorey v-m-shortleg v-zero-dotted` for now).

**Comment by u-ra** [comment]
Overriding the spacing attribute in fonts.conf makes the fonts appear in the monospace list here. Doesn't seem to break anything with regard to rendering.

        <match target="scan">
                <test compare="eq" name="family">
                        <string>Iosevka</string>
                </test>
                <edit name="spacing" mode="assign_replace">
                        <int>100</int>
                </edit>
        </match>

        <match target="scan">
                <test compare="eq" name="family">
                        <string>Iosevka Slab</string>
                </test>
                <edit name="spacing" mode="assign_replace">
                        <int>100</int>
                </edit>
        </match>
