### ISSUE TITLE
Fonts appear stretched out

### ISSUE THREAD

**Issue by kshenoy** [be5invis/Iosevka#261]
* Your font version: (1.14.1)
* Your font variant:  regular
* Your operating system (name and version): RHEL6
* Your application using Iosevka: Emacs 25.1.1

If you have problem when building Iosevka, please provide these informations:

* Your Node.js version:
* Your _otfcc_ version:
* Your `make` version:
* Your results of `npm list`:
```
paste here
```
* Your `parameters.toml`:
```
paste here
```
* Your results of `make -d --no-builtin-rules`:
```
paste here
```
---

When I launch emacs from one terminal, my font looks all stretched out as shown [here](https://imgur.com/UyvLe3r) while when I launch emacs from another terminal it looks [fine](https://imgur.com/jc1Mgju). 

If I switch to another font, it looks fine. Only Iosevka seems to be having this issue on one specific terminal. I'm not able to narrow down what is causing this behavior. Any help that you can provide is appreciated.

**Comment by be5invis** [comment]
Have you tried Iosevka Term?

**Comment by kshenoy** [comment]
I'm using emacs in gui mode so I'm not sure how the terminal comes into the picture in this case but I'll give Iosevka Term a try.

**Comment by be5invis** [comment]
@kshenoy Update?

**Comment by kshenoy** [comment]
Oops, forgot to respond. Iosevka Term works great with XTerm. Thanks!
