### ISSUE TITLE
Variants of 1

### ISSUE THREAD

**Issue by moosotc** [be5invis/Iosevka#262]
* Your font version: (Release or git, version)
https://www.reddit.com/r/aww/comments/88dczn/i_recently_adopted_a_cat_ive_been_struggling_to/

* Your font variant:
https://github.com/moosotc/snippets/blob/master/bin/doiosevka

* Your operating system (name and version):
https://github.com/moosotc/snippets/blob/master/bin/doiosevka

* Your application using Iosevka: (some Java applications may have problem in showing Iosevka properly. It is a bug in Java's GUI components.)
Any

Describe your problem here. Provide pictures and files if necessary.
While one can modify the look of 'l' and 'i' it does not seem possible to do the same with '1' and the "arm"(?) in '1' is too subtle making the letter hard to immediately tell apart from certain variants of 'i' and/or 'l'

**Comment by be5invis** [comment]
Move to #140. Closed.
