### ISSUE TITLE
Underline rendering issue in Mac iTerm2 (broken) vs Mac Terminal (correct)

### ISSUE THREAD

**Issue by bluz71** [be5invis/Iosevka#264]
Hello,

Firstly I want to thank you for creating such a beautiful font.

Interesting quirk on Mac when comparing iTerm2 vs Terminal. Underlines in iTerm2 are rendered badly whilst in Terminal there is no issue. Quite likely this is an issue with iTerm2, but before I raise an item over at the iTerm2 issue tracker I will raise it here first and gather details. Heck, maybe someone can provide an easy tweak to fix this?

Font: 02-iosevka-term-1.14.1

Image, the terminal on the left is iTerm2 whilst the terminal on the right is Terminal. Look at line 24 and the underlined `(`, in iTerm2 it is only partially rendered. Line heights and spacings are the same between both terminals.

<img width="1172" alt="iterm_left_terminal_right" src="https://user-images.githubusercontent.com/11382509/39103556-d3da11a8-46ee-11e8-8fac-94f2a1f37589.png">

Click on the image above to expand to full resolution.

I am fine with this being immediately closed with **iTerm2** has a bug.

**Comment by be5invis** [comment]
I think it is a terminal problem. ITERM2 draws the underline below the letters while Terminal is above.
Closed.

**Comment by bluz71** [comment]
I am now learning that underlines are rendered & placed by the application. It is less to do with the font and more to do with the terminal or editor application.

iTerm2, with this font, places the underline lower and renders it thinner than the standard Mac Terminal application.

There is an existing support item at the iTerm2 issue tracker [requesting a new setting for thinner cursor underlines](https://gitlab.com/gnachman/iterm2/issues/6389), I've requested in that issue a thicken option for underlines in general.

This is an iTerm specific issue.

Thanks for the comment, and thanks for the font.
