### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by ChengCat** [be5invis/Iosevka#265]
Are the font files of Inziu Iosevka found [here](https://be5invis.github.io/Iosevka/inziu.html) licensed under SIL Open Font License 1.1?

Could you include a LICENSE file in the release .7z file?

**Comment by be5invis** [comment]
Inziu, Sarasa, and Iosevka are all licensed in the same manner: font files and glyph data are SIL, building scripts are BSD.
Closed.

**Comment by ChengCat** [comment]
Hi, I've set up a GitHub-based mirror here: https://github.com/ChengCat/Inziu-Iosevka. I've included a formal license text of SIL Open Font License 1.1 for clarity. Can you please review [the license](https://github.com/ChengCat/Inziu-Iosevka/blob/master/LICENSE), and give me permission for inclusion of the license file? Thanks.

**Comment by ChengCat** [comment]
I just found that the LICENSE was problematic. Inziu Iosevka uses Source Han Sans by Adobe Systems Incorporated, but that LICENSE file did not contain proper attribution. To prevent further legal issues, I've decided to take down the mirror and remove Inziu Iosevka from nixpkgs. Sorry for disappointment.

**Comment by be5invis** [comment]
You can modify the License to include that.

发自我的 iPhone

在 2018年4月27日，23:45，ChengCat <notifications@github.com<mailto:notifications@github.com>> 写道：


I just found that the LICENSE was problematic. Inziu Iosevka uses Source Han Sans by Adobe Systems Incorporated, but that LICENSE file did not contain proper attribution. To prevent further legal issues, I've decided to take down the mirror and remove Inziu Iosevka from nixpkgs. Sorry for disappointment.
