### ISSUE TITLE
Bracket alignment issue

### ISSUE THREAD

**Issue by TonCherAmi** [be5invis/Iosevka#266]
* Font version: `1.14.1`
* Font variant: `Iosevka` with `cv37` enabled
* Operating system (name and version): `Gentoo Linux ~amd64`
* Applications using Iosevka: **GNU/Emacs 26.1, [st 0.8.1](https://st.suckless.org/)**

---

### There appears to be an issue with vertical bracket alignment when using Iosevka with certain character heights.

Namely, when using **GNU Emacs** with character height of 14 (set by evaluating expression `(set-frame-font "Iosevka:pixelsize=14")`):

![emacs iosevka 100](https://user-images.githubusercontent.com/13941584/39244538-962b87f4-4899-11e8-9dae-fc76dfd77af3.png)

As well as **st** with the same character height:

![st iosevka 14 5](https://user-images.githubusercontent.com/13941584/39245112-73889d84-489b-11e8-9622-180e9b1ebc16.png)

### The issue seems to disappear if the character height is increased to 16:

In Emacs:

![emacs iosevka 115](https://user-images.githubusercontent.com/13941584/39245232-cd8c3354-489b-11e8-90bf-e41847667311.png)

As well as st:

![st iosevka 16](https://user-images.githubusercontent.com/13941584/39245239-d4b17b8a-489b-11e8-89d4-3f6387a5a122.png)

### I have also not encountered this problem in any other font I tried:

e.g, `Pragmata Pro Mono` in Emacs, character height of 14:

![emacs pragmata 100](https://user-images.githubusercontent.com/13941584/39245460-8ea6b8c0-489c-11e8-8923-26385df54624.png)

`Monaco` in Emacs, same character height:

![emacs monaco 100](https://user-images.githubusercontent.com/13941584/39245489-9d53c9d0-489c-11e8-816e-87d1c086402c.png)

---

Hopefully this can be fixed, as it is quite an eyesore and makes working with certain languages a rather unpleasant experience.

**Comment by be5invis** [comment]
I think it is something with TTFAutohint. Perhaps you could use this tool (again!) to re-calculate or remove the hints and try out.
I do not want to do manual hint (though I wrote IDH), it is horrible.

**Comment by be5invis** [comment]
cc. @lemzwerg

**Comment by lemzwerg** [comment]
Yes, chances are high that this is a hinting issue.  Reason is that `{}` and `[]` are not aligned to any blue zone; if there are slight differences in height and/or depth rounding might cause alignment to different vertical pixels.  I suggest to use a control instructions file for fixing this.

**Comment by be5invis** [comment]
@lemzwerg 
Does TTFA support defining custom alignment zones? All the brackets are aligned to two zones (`parenTop` and `parenBot`).
You know Iosevka is created in an automatic manner and I cannot make sure that point indexes are preserved across versions.

**Comment by be5invis** [comment]
@lemzwerg 
Wait I read the docs of TTFA... It does *not* calculate any alignment zones for punctuations?

**Comment by be5invis** [comment]
@lemzwerg 
Brackets `()[]{}` and some blob punctuations (like `+`) are symmetric so we could round its halfway-height virtual line first, then round its extrema.

**Comment by lemzwerg** [comment]
There are ideas to add 'character knowledge' to FreeType's auto-hinter (and thus to ttfautohint), for example that 'i' has a dot which must be always separated, or '~' which needs a wiggle at least two pixels high, etc., etc.

The symmetry properties of brackets might also be part of that knowledge database.

I won't work on such a feature in the near future; I would be glad if anyone could help...

**Comment by be5invis** [comment]
@TonCherAmi 
For now, I'd like to add an unhinted build in the package (prebuilt) as a workaround for this problem.
Fixing this need a lot of long-term work with @lemzwerg.

**Comment by TonCherAmi** [comment]
@be5invis sounds good, I'd be glad to test it out.

**Comment by TonCherAmi** [comment]
@be5invis hey, I've tried the unhinted build and it doesn't appear to make a difference. However if I switch `Xft.hintstyle` from `hintslight` to `hintnone` the alignment seems to be in order (though it looks atrocious overall), this is true for the unhinted build as well as the normal one. Not quite sure what to make of all this.

**Comment by TonCherAmi** [comment]
@be5invis, well, I'm not really sure, I have `Xft.autohint` disabled and `Xft.hinting` enabled.

**Comment by be5invis** [comment]
@TonCherAmi Your image is inconsistent with my results (taken from VTT). So maybe Freetype affected your hints.

**Comment by TonCherAmi** [comment]
@be5invis so is Iosevka supposed to be used with all Freetype hinting disabled? It looks really blurry that way (both hinted and unhinted builds).

**Comment by be5invis** [comment]
@TonCherAmi 
Iosevka is designed to use its built-in hints. Not sure what option controls whether Freetype should read the built-in hints.
