### ISSUE TITLE
Can't build slab with open $

### ISSUE THREAD

**Issue by lshoravi** [be5invis/Iosevka#268]
* Your font version: Custom built Nigasa-2
* Your font variant: Slab
* Your operating system (name and version): KDE Neon 12.3
* Your application using Iosevka: None

If you have problem when building Iosevka, please provide these informations:

* Your Node.js version: v8.11.1
* Your _otfcc_ version:
* Your `make` version: 4.1
* Your results of `npm list`:
```
iosevka@1.14.2 /home/linus/Downloads/Iosevka-master
├── bezier-js@2.2.5
├─┬ caryll-shapeops@0.3.1
│ ├── bezier-js@2.2.5 deduped
│ └── clipper-lib@1.0.0
├── libspiro-js@0.3.1
├─┬ megaminx@0.3.3
│ ├─┬ child-process-promise@2.2.1
│ │ ├─┬ cross-spawn@4.0.2
│ │ │ ├─┬ lru-cache@4.1.2
│ │ │ │ ├── pseudomap@1.0.2
│ │ │ │ └── yallist@2.1.2
│ │ │ └── which@1.3.0 deduped
│ │ ├── node-version@1.1.3
│ │ └── promise-polyfill@6.1.0
│ ├── cubic2quad@1.1.1
│ ├─┬ fs-extra@3.0.1
│ │ ├── graceful-fs@4.1.11
│ │ ├─┬ jsonfile@3.0.1
│ │ │ └── graceful-fs@4.1.11 deduped
│ │ └── universalify@0.1.1
│ ├─┬ JSONStream@1.3.2
│ │ ├── jsonparse@1.3.1
│ │ └── through@2.3.8
│ └─┬ which@1.3.0
│   └── isexe@2.0.0
├── object-assign@4.1.1
├─┬ pad@1.2.1
│ ├── coffee-script@1.12.7
│ └─┬ wcwidth@1.0.1
│   └─┬ defaults@1.0.3
│     └── clone@1.0.4
├─┬ patel@0.32.1
│ ├─┬ escodegen@1.9.1
│ │ ├── esprima@3.1.3
│ │ ├── estraverse@4.2.0
│ │ ├── esutils@2.0.2
│ │ ├─┬ optionator@0.8.2
│ │ │ ├── deep-is@0.1.3
│ │ │ ├── fast-levenshtein@2.0.6
│ │ │ ├─┬ levn@0.3.0
│ │ │ │ ├── prelude-ls@1.1.2 deduped
│ │ │ │ └── type-check@0.3.2 deduped
│ │ │ ├── prelude-ls@1.1.2
│ │ │ ├─┬ type-check@0.3.2
│ │ │ │ └── prelude-ls@1.1.2 deduped
│ │ │ └── wordwrap@1.0.0
│ │ └── source-map@0.6.1
│ ├─┬ esmangle@1.0.1
│ │ ├─┬ escodegen@1.3.3
│ │ │ ├── esprima@1.1.1 deduped
│ │ │ ├── estraverse@1.5.1 deduped
│ │ │ ├── esutils@1.0.0 deduped
│ │ │ └── source-map@0.1.43 deduped
│ │ ├─┬ escope@1.0.3
│ │ │ └── estraverse@2.0.0
│ │ ├── esprima@1.1.1
│ │ ├─┬ esshorten@1.1.1
│ │ │ ├── escope@1.0.3 deduped
│ │ │ ├── estraverse@4.1.1
│ │ │ └── esutils@2.0.2 deduped
│ │ ├── estraverse@1.5.1
│ │ ├── esutils@1.0.0
│ │ ├─┬ optionator@0.3.0
│ │ │ ├── deep-is@0.1.3 deduped
│ │ │ ├── fast-levenshtein@1.0.7
│ │ │ ├─┬ levn@0.2.5
│ │ │ │ ├── prelude-ls@1.1.2 deduped
│ │ │ │ └── type-check@0.3.2 deduped
│ │ │ ├── prelude-ls@1.1.2 deduped
│ │ │ ├── type-check@0.3.2 deduped
│ │ │ └── wordwrap@0.0.3
│ │ └─┬ source-map@0.1.43
│ │   └── amdefine@1.0.1
│ ├─┬ patrisika@0.21.0
│ │ └── patrisika-scopes@0.11.0
│ ├─┬ resumer@0.0.0
│ │ └── through@2.3.8 deduped
│ └─┬ yargs@6.6.0
│   ├── camelcase@3.0.0
│   ├── cliui@3.2.0 deduped
│   ├── decamelize@1.2.0 deduped
│   ├── get-caller-file@1.0.2 deduped
│   ├─┬ os-locale@1.4.0
│   │ └── lcid@1.0.0 deduped
│   ├─┬ read-pkg-up@1.0.1
│   │ ├─┬ find-up@1.1.2
│   │ │ ├─┬ path-exists@2.1.0
│   │ │ │ └── pinkie-promise@2.0.1 deduped
│   │ │ └─┬ pinkie-promise@2.0.1
│   │ │   └── pinkie@2.0.4
│   │ └─┬ read-pkg@1.1.0
│   │   ├─┬ load-json-file@1.1.0
│   │   │ ├── graceful-fs@4.1.11 deduped
│   │   │ ├── parse-json@2.2.0 deduped
│   │   │ ├── pify@2.3.0 deduped
│   │   │ ├── pinkie-promise@2.0.1 deduped
│   │   │ └─┬ strip-bom@2.0.0
│   │   │   └── is-utf8@0.2.1
│   │   ├── normalize-package-data@2.4.0 deduped
│   │   └─┬ path-type@1.1.0
│   │     ├── graceful-fs@4.1.11 deduped
│   │     ├── pify@2.3.0 deduped
│   │     └── pinkie-promise@2.0.1 deduped
│   ├── require-directory@2.1.1 deduped
│   ├── require-main-filename@1.0.1 deduped
│   ├── set-blocking@2.0.0 deduped
│   ├─┬ string-width@1.0.2
│   │ ├── code-point-at@1.1.0
│   │ ├─┬ is-fullwidth-code-point@1.0.0
│   │ │ └── number-is-nan@1.0.1
│   │ └── strip-ansi@3.0.1 deduped
│   ├── which-module@1.0.0
│   ├── y18n@3.2.1 deduped
│   └─┬ yargs-parser@4.2.1
│     └── camelcase@3.0.0 deduped
├── toml@2.3.3
├── topsort@0.0.2
├── unorm@1.4.1
└─┬ yargs@8.0.2
  ├── camelcase@4.1.0
  ├─┬ cliui@3.2.0
  │ ├── string-width@1.0.2 deduped
  │ ├─┬ strip-ansi@3.0.1
  │ │ └── ansi-regex@2.1.1
  │ └─┬ wrap-ansi@2.1.0
  │   ├── string-width@1.0.2 deduped
  │   └── strip-ansi@3.0.1 deduped
  ├── decamelize@1.2.0
  ├── get-caller-file@1.0.2
  ├─┬ os-locale@2.1.0
  │ ├─┬ execa@0.7.0
  │ │ ├─┬ cross-spawn@5.1.0
  │ │ │ ├── lru-cache@4.1.2 deduped
  │ │ │ ├─┬ shebang-command@1.2.0
  │ │ │ │ └── shebang-regex@1.0.0
  │ │ │ └── which@1.3.0 deduped
  │ │ ├── get-stream@3.0.0
  │ │ ├── is-stream@1.1.0
  │ │ ├─┬ npm-run-path@2.0.2
  │ │ │ └── path-key@2.0.1
  │ │ ├── p-finally@1.0.0
  │ │ ├── signal-exit@3.0.2
  │ │ └── strip-eof@1.0.0
  │ ├─┬ lcid@1.0.0
  │ │ └── invert-kv@1.0.0
  │ └─┬ mem@1.1.0
  │   └── mimic-fn@1.2.0
  ├─┬ read-pkg-up@2.0.0
  │ ├─┬ find-up@2.1.0
  │ │ └─┬ locate-path@2.0.0
  │ │   ├─┬ p-locate@2.0.0
  │ │   │ └─┬ p-limit@1.2.0
  │ │   │   └── p-try@1.0.0
  │ │   └── path-exists@3.0.0
  │ └─┬ read-pkg@2.0.0
  │   ├─┬ load-json-file@2.0.0
  │   │ ├── graceful-fs@4.1.11 deduped
  │   │ ├─┬ parse-json@2.2.0
  │   │ │ └─┬ error-ex@1.3.1
  │   │ │   └── is-arrayish@0.2.1
  │   │ ├── pify@2.3.0
  │   │ └── strip-bom@3.0.0
  │   ├─┬ normalize-package-data@2.4.0
  │   │ ├── hosted-git-info@2.6.0
  │   │ ├─┬ is-builtin-module@1.0.0
  │   │ │ └── builtin-modules@1.1.1
  │   │ ├── semver@5.5.0
  │   │ └─┬ validate-npm-package-license@3.0.3
  │   │   ├─┬ spdx-correct@3.0.0
  │   │   │ ├── spdx-expression-parse@3.0.0 deduped
  │   │   │ └── spdx-license-ids@3.0.0
  │   │   └─┬ spdx-expression-parse@3.0.0
  │   │     ├── spdx-exceptions@2.1.0
  │   │     └── spdx-license-ids@3.0.0 deduped
  │   └─┬ path-type@2.0.0
  │     └── pify@2.3.0 deduped
  ├── require-directory@2.1.1
  ├── require-main-filename@1.0.1
  ├── set-blocking@2.0.0
  ├─┬ string-width@2.1.1
  │ ├── is-fullwidth-code-point@2.0.0
  │ └─┬ strip-ansi@4.0.0
  │   └── ansi-regex@3.0.0
  ├── which-module@2.0.0
  ├── y18n@3.2.1
  └─┬ yargs-parser@7.0.0
    └── camelcase@4.1.0 deduped

```
* Your `parameters.toml`:
```
[iosevka]
family = 'Iosevka'
version = '1.14.2'
codename = 'Nagisa'
copyright = 'Copyright (c) 2015-2017 Belleve Invis.'
licence = '''This font software is licenced under the SIL Open Font Licence, Version 1.1. This is licence is avaliable with a FAQ at: http://scripts.sil.org/OFL. This font software is distributes on an 'AS IS' basis, without warranties or conditions of any kind, either express or implied. See the SIL Open Font licence fot the specific language, premissions and limitations governing your use of this font software.'''
manufacturer = 'Belleve Invis'
designer = 'Belleve Invis'
description = 'Spatial efficient monospace font family for programming. Built from code. http://be5invis.github.io/Iosevka'

leading = 1250     # Default line height times 1000.
descenderPad = 0   # Additional line height, added to descender.
width = 500        # Character width. Increase this if you think that Iosevka is too narrow.
cap = 735          # Cap height (as well as ascender).
xheight = 530      # X-height.
#descender = -205  # Depth of descender. Currently unused.

ideoMid  = 365
parenMid = 365

contrast = 1.11111 # Stroke width contrast.
essx = 1.12        # Contrast of the middle of 'S'.

slantAngle = 0     # Slant angle, in degrees.

accent = 155       # Height of accent marks.
accentx = 200      # Width of accent marks.
overshoot = -8     # Vertical overshoot for arcs.
overshootx = -8    # Horizontal overshoot for arcs.
oxhook = -5        # Horizontal overshoot for hook tips.
fovershoot = -40   # Overshoot of the top end of italic `f`.

longjut = 175      # Length of long serifs, like that in `i`.
jut = 85           # Length of short serifs, used in Slab only.
vjut = 145         # Length of vertical serifs, used in Slab only.

smooth = 195       # Vertical arc size in capital letters.
smallsmooth = 220  # Vertical arc size in lowercase letters.
smoothadjust = 120 # Parameter to balance arcs in slanted shapes.
superness = 2.2    # Superness of arcs.

barpos = 0.525     # Position of the middle bar in most letters, like `E`.
overlaypos = 0.52  # Position of the overlay mark.
ebarpos = 0.50     # Position of the middle bar in `e`.
gbarpos = 0.42
pbarpos = 0.53
fivebarpos = 0.64

hook  = 155        # Hook depth in most letters.
ahook = 130
shook = 110
jhook = 135
fhook = 120
rhook = 90
hookx = 170

tbalance = 50
tbalance2 = 30
rbalance = 60
rbalance2 = 15
jbalance = 63
fbalance = 6
onebalance = 30

isBold = false     # Mark the font as bold?
isItalic = false   # Use italic shapes?

lllcrowdedness = 3.33333333

spacing = 1 # Spacing indicator

# Powerline-specific parameters
powerlineScaleY = 1 # Vertical scale
powerlineScaleX = 1 # Horizontal scale
powerlineShiftY = 0 # Vertical shift
powerlineShiftX = 0 # Horizontal shift

# Full-width codes
fullwidth_codes = []

# Comment the line below to enable CJKV glyph generation
noCJKV = true

[verbose]
verbose = true

### Weights

[w-book]
isBold = false
weight = 400       # "Weight" metadata.
style = ''

sb = 60            # Side bearing.
stroke = 72        # Stroke width of horizontal strokes.
dotsize = 125      # "Visual" size of dots in /i.
periodsize = 140   # "Visual" size of period.

[w-thin]
weight = 100
style = 'Thin'

stroke = 18
sb = 72
dotsize = 53
periodsize = 55

cthin = 0.9
cthinb = 0.9
vtipfine = 1
shoulderfine = 0.8
pbarpos = 0.5

[w-extralight]
weight = 200
style = 'Extralight'

stroke = 36
sb = 68
dotsize = 70
periodsize = 77

cthin = 0.75
cthinb = 0.75
vtipfine = 1
pbarpos = 0.5

[w-light]
weight = 300
style = 'Light'

stroke = 56
sb = 64
dotsize = 100
periodsize = 115

vtipfine = 0.9
pbarpos = 0.51

[w-medium]
weight = 500
style = 'Medium'

sb = 54
stroke = 90
dotsize = 140
periodsize = 165
essx = 1.07

rbalance = 55
rbalance2 = 20
smooth = 203

[w-bold]
isBold = true
weight = 700
style = 'Bold'

sb = 45
stroke = 108
dotsize = 160
periodsize = 180
essx = 1.05
essxq = 1.15
jut = 90
vjut = 165

barpos = 0.51
fivebarpos = 0.64
rbalance = 50
rbalance2 = 25
rhook = 95
smooth = 210

[w-heavy]
isBold = true
weight = 900
style = 'Heavy'

sb = 42
stroke = 126
dotsize = 180
periodsize = 200
essx = 1.03
essxq = 1.15
jut = 100
vjut = 175

barpos = 0.51
fivebarpos = 0.64
rbalance = 50
rbalance2 = 25
rhook = 105
smooth = 215

### Slantness
[s-upright]
isItalic = false

[s-italic]
isItalic = true
slantAngle = 10
jhook = 120

[s-italic.adds]
style = " Italic"

[s-oblique]
isOblique = true
isItalic = false
slantAngle = 10
jhook = 120

[s-oblique.adds]
style = " Oblique"


### Slab variant
[slab]
slab = true
onebalance = 10
overshootx = -16
[slab.multiplies]
sb = 1.1
[slab.adds]
family = " Slab"

### Spacings

[term]
spacing = 0
disableLigation = true

[term.adds]
family = ' Term'

# Term variant with ligations
[termlig]
spacing = 0

[termlig.adds]
family = ' Term-Lig'

[type]
inherits = ["xx-type"]
spacing = 2

[type.adds]
family = " Type"

[cc]
inherits = ["xx-cc"]
spacing = 3

[cc.adds]
family = 'CC'

### Widths
# Expanded : I heard someone want it being wider...
[wd-expanded.multiplies]
width = 1.15
sb = 1.15
[expanded]
inherits = ['wd-expanded']
[expanded.adds]
family = ' Expanded'

# Compressed : And someone else want it being narrower
[wd-compressed.multiplies]
width = 0.9
sb = 0.9
[compressed]
inherits = ['wd-compressed']
[compressed.adds]
family = ' Compressed'

###### Full-width codes
[xx-type]
spacing = 2
[xx-type.appends]
fullwidth_codes = [
	164, #¤
	177, #±
	215, #×
	247, #÷
	711, #ˇ
	713, #ˉ
	8212, #—
	8214, #‖
	8251, #※
	8451, #℃
	8712, #∈
	8719, #∏
	8720,
	8721, #∑
	8733, #∝
	8734, #∞
	8736, #∠
	8741, #∥
	8743, #∧
	8744, #∨
	8745, #∩
	8746, #∪
	8747, #∫
	8750, #∮
	8756, #∴
	8757, #∵
	8758, #∶
	8759, #∷
	8765, #∽
	8776, #≈
	8780, #≌
	8800, #≠
	8801, #≡
	8804, #≤
	8805, #≥
	8814, #≮
	8815, #≯
	8816,8817,8834,8835,8836,8837,
	8853, #⊕
	8854,
	8857, #⊙
	8866, 
	8867, 
	8868, 
	8869, #⊥
	8978, #⌒
	8896,8897,8898,8899
]

[xx-cc]
inherits = ["xx-type"]
spacing = 3
[xx-cc.appends]
fullwidth_codes = [
	167, #§
	8242, #′
	8243, #″
]

# stress-fw : force distinguish full-widths
[stress-fw]
stressFW = true
[stress-fw.adds]
family = " StFW"

# Default ligation set configuration
[ligset-haskell]
defLigSet = "XHS0"

[ligset-idris]
defLigSet = "XIDR"

[ligset-elm]
defLigSet = "XELM"

[ligset-ml]
defLigSet = "XML0"

[ligset-fs]
defLigSet = "XFS0"

[ligset-fstar]
defLigSet = "XFST"

[ligset-swift]
defLigSet = "SWFT"

[ligset-purescript]
defLigSet = "PURS"

[ligset-coq]
defLigSet = "XV00"

# Compatibility PUA ligature sample
# [[iosevka.compLig]]
# unicode = 57600 # 0xE100
# featureTag = 'XV00'
# sequence = '<*>'

```
---
Building a custom Iosevka Slab with `cv38`, i.e the open dollar-sign doesnt actually do anything; it still assigns the filled dollar sign.

Custom config is: 

```
design='slab termlig ligset-haskell' upright='cv01 cv03 cv07 cv11 cv13 cv17 cv19 cv20 cv22 cv25 cv30 cv33 cv35 cv37 cv38 cv40 cv42 cv44 cv46 cv48 cv51 cv52' italic='cv01 cv03 cv07 cv11 cv13 cv17 cv19 cv20 cv22 cv25 cv30 cv33 cv35 cv37 cv38 cv40 cv42 cv44 cv46 cv48 cv51 cv52'
```

**Comment by be5invis** [comment]
Have you tried the raw style (v-dollar-)?

发自我的 iPhone

在 2018年5月6日，04:00，lshoravi <notifications@github.com<mailto:notifications@github.com>> 写道：


  *   Your font version: Custom built Nigasa-2
  *   Your font variant: Slab
  *   Your operating system (name and version): KDE Neon 12.3
  *   Your application using Iosevka: None

If you have problem when building Iosevka, please provide these informations:

  *   Your Node.js version: v8.11.1
  *   Your otfcc version:
  *   Your make version: 4.1
  *   Your results of npm list:

iosevka@1.14.2 /home/linus/Downloads/Iosevka-master
├── bezier-js@2.2.5
├─┬ caryll-shapeops@0.3.1
│ ├── bezier-js@2.2.5 deduped
│ └── clipper-lib@1.0.0
├── libspiro-js@0.3.1
├─┬ megaminx@0.3.3
│ ├─┬ child-process-promise@2.2.1
│ │ ├─┬ cross-spawn@4.0.2
│ │ │ ├─┬ lru-cache@4.1.2
│ │ │ │ ├── pseudomap@1.0.2
│ │ │ │ └── yallist@2.1.2
│ │ │ └── which@1.3.0 deduped
│ │ ├── node-version@1.1.3
│ │ └── promise-polyfill@6.1.0
│ ├── cubic2quad@1.1.1
│ ├─┬ fs-extra@3.0.1
│ │ ├── graceful-fs@4.1.11
│ │ ├─┬ jsonfile@3.0.1
│ │ │ └── graceful-fs@4.1.11 deduped
│ │ └── universalify@0.1.1
│ ├─┬ JSONStream@1.3.2
│ │ ├── jsonparse@1.3.1
│ │ └── through@2.3.8
│ └─┬ which@1.3.0
│   └── isexe@2.0.0
├── object-assign@4.1.1
├─┬ pad@1.2.1
│ ├── coffee-script@1.12.7
│ └─┬ wcwidth@1.0.1
│   └─┬ defaults@1.0.3
│     └── clone@1.0.4
├─┬ patel@0.32.1
│ ├─┬ escodegen@1.9.1
│ │ ├── esprima@3.1.3
│ │ ├── estraverse@4.2.0
│ │ ├── esutils@2.0.2
│ │ ├─┬ optionator@0.8.2
│ │ │ ├── deep-is@0.1.3
│ │ │ ├── fast-levenshtein@2.0.6
│ │ │ ├─┬ levn@0.3.0
│ │ │ │ ├── prelude-ls@1.1.2 deduped
│ │ │ │ └── type-check@0.3.2 deduped
│ │ │ ├── prelude-ls@1.1.2
│ │ │ ├─┬ type-check@0.3.2
│ │ │ │ └── prelude-ls@1.1.2 deduped
│ │ │ └── wordwrap@1.0.0
│ │ └── source-map@0.6.1
│ ├─┬ esmangle@1.0.1
│ │ ├─┬ escodegen@1.3.3
│ │ │ ├── esprima@1.1.1 deduped
│ │ │ ├── estraverse@1.5.1 deduped
│ │ │ ├── esutils@1.0.0 deduped
│ │ │ └── source-map@0.1.43 deduped
│ │ ├─┬ escope@1.0.3
│ │ │ └── estraverse@2.0.0
│ │ ├── esprima@1.1.1
│ │ ├─┬ esshorten@1.1.1
│ │ │ ├── escope@1.0.3 deduped
│ │ │ ├── estraverse@4.1.1
│ │ │ └── esutils@2.0.2 deduped
│ │ ├── estraverse@1.5.1
│ │ ├── esutils@1.0.0
│ │ ├─┬ optionator@0.3.0
│ │ │ ├── deep-is@0.1.3 deduped
│ │ │ ├── fast-levenshtein@1.0.7
│ │ │ ├─┬ levn@0.2.5
│ │ │ │ ├── prelude-ls@1.1.2 deduped
│ │ │ │ └── type-check@0.3.2 deduped
│ │ │ ├── prelude-ls@1.1.2 deduped
│ │ │ ├── type-check@0.3.2 deduped
│ │ │ └── wordwrap@0.0.3
│ │ └─┬ source-map@0.1.43
│ │   └── amdefine@1.0.1
│ ├─┬ patrisika@0.21.0
│ │ └── patrisika-scopes@0.11.0
│ ├─┬ resumer@0.0.0
│ │ └── through@2.3.8 deduped
│ └─┬ yargs@6.6.0
│   ├── camelcase@3.0.0
│   ├── cliui@3.2.0 deduped
│   ├── decamelize@1.2.0 deduped
│   ├── get-caller-file@1.0.2 deduped
│   ├─┬ os-locale@1.4.0
│   │ └── lcid@1.0.0 deduped
│   ├─┬ read-pkg-up@1.0.1
│   │ ├─┬ find-up@1.1.2
│   │ │ ├─┬ path-exists@2.1.0
│   │ │ │ └── pinkie-promise@2.0.1 deduped
│   │ │ └─┬ pinkie-promise@2.0.1
│   │ │   └── pinkie@2.0.4
│   │ └─┬ read-pkg@1.1.0
│   │   ├─┬ load-json-file@1.1.0
│   │   │ ├── graceful-fs@4.1.11 deduped
│   │   │ ├── parse-json@2.2.0 deduped
│   │   │ ├── pify@2.3.0 deduped
│   │   │ ├── pinkie-promise@2.0.1 deduped
│   │   │ └─┬ strip-bom@2.0.0
│   │   │   └── is-utf8@0.2.1
│   │   ├── normalize-package-data@2.4.0 deduped
│   │   └─┬ path-type@1.1.0
│   │     ├── graceful-fs@4.1.11 deduped
│   │     ├── pify@2.3.0 deduped
│   │     └── pinkie-promise@2.0.1 deduped
│   ├── require-directory@2.1.1 deduped
│   ├── require-main-filename@1.0.1 deduped
│   ├── set-blocking@2.0.0 deduped
│   ├─┬ string-width@1.0.2
│   │ ├── code-point-at@1.1.0
│   │ ├─┬ is-fullwidth-code-point@1.0.0
│   │ │ └── number-is-nan@1.0.1
│   │ └── strip-ansi@3.0.1 deduped
│   ├── which-module@1.0.0
│   ├── y18n@3.2.1 deduped
│   └─┬ yargs-parser@4.2.1
│     └── camelcase@3.0.0 deduped
├── toml@2.3.3
├── topsort@0.0.2
├── unorm@1.4.1
└─┬ yargs@8.0.2
  ├── camelcase@4.1.0
  ├─┬ cliui@3.2.0
  │ ├── string-width@1.0.2 deduped
  │ ├─┬ strip-ansi@3.0.1
  │ │ └── ansi-regex@2.1.1
  │ └─┬ wrap-ansi@2.1.0
  │   ├── string-width@1.0.2 deduped
  │   └── strip-ansi@3.0.1 deduped
  ├── decamelize@1.2.0
  ├── get-caller-file@1.0.2
  ├─┬ os-locale@2.1.0
  │ ├─┬ execa@0.7.0
  │ │ ├─┬ cross-spawn@5.1.0
  │ │ │ ├── lru-cache@4.1.2 deduped
  │ │ │ ├─┬ shebang-command@1.2.0
  │ │ │ │ └── shebang-regex@1.0.0
  │ │ │ └── which@1.3.0 deduped
  │ │ ├── get-stream@3.0.0
  │ │ ├── is-stream@1.1.0
  │ │ ├─┬ npm-run-path@2.0.2
  │ │ │ └── path-key@2.0.1
  │ │ ├── p-finally@1.0.0
  │ │ ├── signal-exit@3.0.2
  │ │ └── strip-eof@1.0.0
  │ ├─┬ lcid@1.0.0
  │ │ └── invert-kv@1.0.0
  │ └─┬ mem@1.1.0
  │   └── mimic-fn@1.2.0
  ├─┬ read-pkg-up@2.0.0
  │ ├─┬ find-up@2.1.0
  │ │ └─┬ locate-path@2.0.0
  │ │   ├─┬ p-locate@2.0.0
  │ │   │ └─┬ p-limit@1.2.0
  │ │   │   └── p-try@1.0.0
  │ │   └── path-exists@3.0.0
  │ └─┬ read-pkg@2.0.0
  │   ├─┬ load-json-file@2.0.0
  │   │ ├── graceful-fs@4.1.11 deduped
  │   │ ├─┬ parse-json@2.2.0
  │   │ │ └─┬ error-ex@1.3.1
  │   │ │   └── is-arrayish@0.2.1
  │   │ ├── pify@2.3.0
  │   │ └── strip-bom@3.0.0
  │   ├─┬ normalize-package-data@2.4.0
  │   │ ├── hosted-git-info@2.6.0
  │   │ ├─┬ is-builtin-module@1.0.0
  │   │ │ └── builtin-modules@1.1.1
  │   │ ├── semver@5.5.0
  │   │ └─┬ validate-npm-package-license@3.0.3
  │   │   ├─┬ spdx-correct@3.0.0
  │   │   │ ├── spdx-expression-parse@3.0.0 deduped
  │   │   │ └── spdx-license-ids@3.0.0
  │   │   └─┬ spdx-expression-parse@3.0.0
  │   │     ├── spdx-exceptions@2.1.0
  │   │     └── spdx-license-ids@3.0.0 deduped
  │   └─┬ path-type@2.0.0
  │     └── pify@2.3.0 deduped
  ├── require-directory@2.1.1
  ├── require-main-filename@1.0.1
  ├── set-blocking@2.0.0
  ├─┬ string-width@2.1.1
  │ ├── is-fullwidth-code-point@2.0.0
  │ └─┬ strip-ansi@4.0.0
  │   └── ansi-regex@3.0.0
  ├── which-module@2.0.0
  ├── y18n@3.2.1
  └─┬ yargs-parser@7.0.0
    └── camelcase@4.1.0 deduped



  *   Your parameters.toml:

paste here


  *   Your results of make -d --no-builtin-rules:

paste here


________________________________

Building a custom Iosevka Slab with cv38, i.e the open dollar-sign doesnt actually do anything; it still assigns the filled dollar sign.

Custom config is:

design='slab termlig ligset-haskell' upright='cv01 cv03 cv07 cv11 cv13 cv17 cv19 cv20 cv22 cv25 cv30 cv33 cv35 cv37 cv38 cv40 cv42 cv44 cv46 cv48 cv51 cv52' italic='cv01 cv03 cv07 cv11 cv13 cv17 cv19 cv20 cv22 cv25 cv30 cv33 cv35 cv37 cv38 cv40 cv42 cv44 cv46 cv48 cv51 cv52'

**Comment by lshoravi** [comment]
As I investigate, other things like medium-height caret and star doesn't work either. String is a sans built with the config in the OP, other is slab built with config in OP.
![image](https://user-images.githubusercontent.com/33871500/39667160-263f9b64-50b0-11e8-9986-46854077b21d.png)

**Comment by lshoravi** [comment]
Nay, I'll try it. Reporting back soon.

**Comment by be5invis** [comment]
Only in Slab? Looks like a priority issue when applying styles...
Internally Slab has a style set to change some of the symbols (like “y”). Will investigate tomorrow.

发自我的 iPhone

在 2018年5月6日，04:04，lshoravi <notifications@github.com<mailto:notifications@github.com>> 写道：


Nay, I'll try it. Reporting back soon.

**Comment by lshoravi** [comment]
Tried building with v-dollar-open, as well as v-asterisk-low and v-caret-low, no change.

**Comment by be5invis** [comment]
I see why. Current code prioritizes style assignments in “design” so your upright- and italic-specific sets are overwritten by “slab”.
One solution is, move the common terms in “upright “ and “italic” into “design”, and keep the differences only.

**Comment by lshoravi** [comment]
Alright, I'll check it out. Want me to close this if it works?

**Comment by lshoravi** [comment]
Tried building with commons in design instead of upright and italic, now it builds correctly :) Closing this.
