### ISSUE TITLE
Question about shape of "t"

### ISSUE THREAD

**Issue by AmerM137** [be5invis/Iosevka#269]
Hello,

This is not an issue but more of a question, so forgive me if this is out of place.

I just figured out how to build Iosevka from the source code (had to figure out a few things as I am a beginner still). I think this is a beautiful font for programming and I have been using it for a few months now. The only thing that I would like to change for my personal taste is the shape of the letter "t". I would like the bottom part of the letter not be curved so much. Something like the "t" in the font "Cousine" would be perfect.

Is this change possible by modifying some parameters in "parameters.toml" file? I tried playing with "tbalance" and "overshootx" but that wasn't it. Any guidance would be appreciated!

Thanks,

Amer

**Comment by be5invis** [comment]
The depth of `t`'s hook is controlled by `hook`. But I suggest you move to #140 to ask a variant for `t`.
Closed.
