### ISSUE TITLE
Microsoft Store

### ISSUE THREAD

**Issue by WangZishi** [be5invis/Iosevka#271]
Would you consider putting this awesome into the Microsoft Store? It's already supported by Windows 10 to download and install fonts from the Microsoft Stores directly. It looks very convenient to distribute.

![image](https://user-images.githubusercontent.com/8288105/40100492-a80e6da0-5916-11e8-9a0b-d6359ec0232c.png)

**Comment by be5invis** [comment]
The store is not open to third-party yet.
Closed.

**Comment by hl2guide** [comment]
> 
The store is not open to third-party yet.
Closed.

@be5invis has this changed since?
