### ISSUE TITLE
Better style for greater and less than sign

### ISSUE THREAD

**Issue by mustaqimM** [be5invis/Iosevka#272]
Currently I find the greater than and less than signs don't match the style of Iosevka

![iosevka](https://user-images.githubusercontent.com/24436622/40214737-bd5b2594-5a5c-11e8-8465-be3ce4c4d443.png)

The Fira Code style seems to match better
![fira code](https://user-images.githubusercontent.com/24436622/40214757-d6c2e9c2-5a5c-11e8-9b79-84effc1c05e8.png)

**Comment by be5invis** [comment]
So you want `<=` look like `⩽` rather than `≤`?

**Comment by lshoravi** [comment]
I agree, personally. Left is Pragmata Pro, right is Iosevka. Both look great, but ``⩽`` 'feels' better imo.

![image](https://user-images.githubusercontent.com/33871500/40167953-ab0eedc0-59c2-11e8-99f0-b31f7adb8fed.png)

**Comment by rileyinman** [comment]
+1 on this change, commenting instead of reacting because of closure by stale bot.
