### ISSUE TITLE
Glyph variants for cyrillic (russian) letters (especially cyrEs)

### ISSUE THREAD

**Issue by alexeyten** [be5invis/Iosevka#274]
* Your font version: (Release or git, version)
1.14.3
* Your font variant:
Default
* Your operating system (name and version):
Ubuntu 16.04
* Your application using Iosevka:
Pantheon Terminal, Firefox, any
---

I would like to have variant for different shapes of latin `c` and cyrillic `с` (cyrEs U+0421). It's the most troublesome letter because these letters are on the same key in latin and russian keyboard layouts.

Different shapes for `y` and `у` (cyrU U+0423) and `p` and `р` (cyrEr U+0420) also would be great.
For `y` it would be good enough to choose between `cv48` and `cv49` independenly for latin and cyrillic glyphs.

**Comment by be5invis** [comment]
Could you please have some images of candidate variants?
From a type designer's perspective, I should **NOT** do that.
