### ISSUE TITLE
Font is taller (or thinner) than in screenshot

### ISSUE THREAD

**Issue by huyvohcmc** [be5invis/Iosevka#277]
* Your font version: 1.14.3
* Your font variant: iosevka
* Your operating system (name and version): osx 10.13.4
* Your application using Iosevka: iterm2 (3.1.6)

<img width="1503" alt="screen shot 2018-05-25 at 12 05 35 am" src="https://user-images.githubusercontent.com/17645203/40500718-d56dce5e-5faf-11e8-9c64-d996e1a58003.png">

Above is the picture of regular Iosevka 17 pt in neovim (iTerm2). It looks like the height of the font is higher than usual, or the width of the font is less than usual (I'm not sure which). In general, the font just looks taller and thinner. I go to the text setting in iTerm2 and saw that the character spacing (horizontal and vertical) are both set to 100%, which is normal.

I just can't explain if this is the true shape of the fonts or did I mess up something in iTerm2 settings that cause the issue...

**Comment by lshoravi** [comment]
Could you provide a comparison screenshot?

**Comment by huyvohcmc** [comment]
There are a few issues that similar to this one, so I'm going to close it.

**Comment by be5invis** [comment]
The font IS designed to be narrow.
There are experiments a bout providing a wider variant. You could find them in earlier issues.
