### ISSUE TITLE
Console frames not beautiful as Iosevka deserves

### ISSUE THREAD

**Issue by JCKodel** [be5invis/Iosevka#278]
* Your font version: 1.14.3
* Your font variant: normal
* Your operating system (name and version): Windows 10 Pro (1803)
* Your application using Iosevka: Everywhere ^^, but this issue in on cmdlr console (or any console):

---

![image](https://user-images.githubusercontent.com/379339/40579758-b36c9a72-6105-11e8-92fe-c35ae29b7287.png)

Those corner chars are ugly as hell on console (or any program that uses Iosevka). The image above is from a NPM "dialog".

```
╭─────────────────────────╮
|                         |
╰─────────────────────────╯
```

**Comment by be5invis** [comment]
Have you tried the unhinted version?

**Comment by be5invis** [comment]
I am not sure what Conemu did... Box drawing glyphs are well-aligned.
@maximus5

**Comment by JCKodel** [comment]
Indeed... Is not an Iosevka issue, sorry for that:

Visual Studio 2017 renders it quite well:

![image](https://user-images.githubusercontent.com/379339/40580149-6cadfefa-610f-11e8-8448-c6fee2aa7d12.png)

**Comment by JCKodel** [comment]
Found it: those chars are recognized as alternative fonts for cmdemu (and it was configurated to use Lucida Sans for those). Either disable or configure it to use the same font:

![image](https://user-images.githubusercontent.com/379339/40580172-de38589a-610f-11e8-81aa-1dedd66a1f2a.png)
