### ISSUE TITLE
Package for Linux distros

### ISSUE THREAD

**Issue by stokito** [be5invis/Iosevka#279]
* Your operating system (name and version): Ubuntu Mate 18.04

I can easily install Fiara Code by typing `sudo apt install fonts-firacode` on my Ubuntu but to install Iosevka I have to make some manual steps. Also there no any instructions in README about this steps and I googled them. And especially I was confused about which type should I use: OpenFont, TrueType etc.
Can you distribute your font with package managers?

**Comment by be5invis** [comment]
There should already be a package for Debian: https://launchpad.net/~laurent-boulard/+archive/ubuntu/fonts

**Comment by blucell** [comment]
The package is not updated since then.

**Comment by alexmyczko** [comment]
http://phd-sid.ethz.ch/debian/fonts-iosevka/

**Comment by mbana** [comment]
> http://phd-sid.ethz.ch/debian/fonts-iosevka/

Seems to be down.

Has anyone looked at packaging this font into Ubuntu?

**Comment by alexmyczko** [comment]
@mbana new url https://github.com/be5invis/Iosevka/issues/715

**Comment by mbana** [comment]
> [@mbana](https://github.com/mbana) new url [#715](https://github.com/be5invis/Iosevka/issues/715)

I'm not a Ubuntu maintainer so I don't know what it takes to get the package into main-line. Could someone else possibly do it, please?

**Comment by alexmyczko** [comment]
@mbana I'm neither. Here's explained what's needed: https://github.com/be5invis/Iosevka/issues/2873#issuecomment-3610526652
