### ISSUE TITLE
Make Iosevka bold letters a bit less thick/heavy?

### ISSUE THREAD

**Issue by b0rski** [be5invis/Iosevka#281]
* Your font version: (Release or git, version)
1.14.3
* Your font variant:
ss07 - Iosevka Regular
* Your operating system (name and version):
Windows 10
* Your application using Iosevka:
IntelliJ 2018
---

In my personal opinion the font looks a bit too heavy/thick for bold characters. Normal (non-bold) chars look perfect.

Iosevka
![image](https://user-images.githubusercontent.com/11145838/41817915-a24763e8-77a4-11e8-8b4a-c1752bae964e.png)

Consolas
![image](https://user-images.githubusercontent.com/11145838/41817926-c80ad632-77a4-11e8-9e8b-1fb8d04e8af9.png)

How do I make bold chars less thicker? Like the ones from Consolas? The thin version of Iosevka is way too thin :)

Kind regards
b0rski

**Comment by be5invis** [comment]
How about change the current `bold` into `extrabold`, and add `semibold` and a new `bold` to Iosevka?

**Comment by leonbreedt** [comment]
FYI, `bold` does not render that bold on macOS Mojave Beta, since they removed subpixel rendering for next release `10.14`.

Example screenshot: 

![hyper](https://user-images.githubusercontent.com/167841/42667943-3805627a-86a2-11e8-8e42-b0df72d05de0.png)

Must be hard to balance all these features across different OS's :)

**Comment by leonbreedt** [comment]
To be clear, I love the way it renders now on Mojave, the shapes are so pleasing, not complaining!

**Comment by dieggsy** [comment]
FWIW, I'm happy with how bold looks in arch linux

**Comment by be5invis** [comment]
There is the current "Bold", and the "Extrabold" in the future:

![image](https://user-images.githubusercontent.com/240091/42676065-2b2ff838-86a9-11e8-9226-3a91990ef364.png)

And, the new "Bold":

![image](https://user-images.githubusercontent.com/240091/42676054-21915d58-86a9-11e8-930a-701e80e7d95e.png)
