### ISSUE TITLE
Could vertical align of selected special characters be patched for Powerline?

### ISSUE THREAD

**Issue by b0rski** [be5invis/Iosevka#283]
* Your font version: 1.14.3
* Your font variant: ss07 - Iosevka Term
* Your operating system (name and version): MacOS X
* Your application using Iosevka: [Powerline](https://github.com/powerline/powerline) in iTerm2 on MacOS and wslterminal on Windows

<img width="689" alt="screen shot 2018-07-14 at 09 08 10" src="https://user-images.githubusercontent.com/11145838/42722090-4360ac34-8746-11e8-8422-e5f3dd0f9fef.png">

You can see this very well with font size 12pt. The special "arrow" character should sit a bit higher. And actually the letters, like "j" could be moved a bit higher in size 12pt as well (versus the coloured background).

**Comment by be5invis** [comment]
There are parameters to control the line height. You may need some experiments to find out.



发自我的 iPhone

在 2018年7月14日，15:18，Maciej Raciborski <notifications@github.com<mailto:notifications@github.com>> 写道：


  *   Your font version: 1.14.3
  *   Your font variant: ss07 - Iosevka Term
  *   Your operating system (name and version): Windows & MacOS X
  *   Your application using Iosevka: iTerm2 on MacOS and wslterminal on Windows

[screen shot 2018-07-14 at 09 08 10]<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F11145838%2F42722090-4360ac34-8746-11e8-8422-e5f3dd0f9fef.png&data=02%7C01%7C%7Cbbabdb64be7d46d3ca9e08d5e959ece4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636671494794048694&sdata=swfryV8WbfxdYiUc5403hsVouvTJyTQd%2B3SrG8978Z8%3D&reserved=0>

You can see this very well with font size 12. The special "arrow" character should sit a bit higher.

**Comment by b0rski** [comment]
Wouldn't the line height just shrink the height without changing the position of ">" against other characters?

**Comment by be5invis** [comment]
There should be an “ascender” and “descender” value in the Parameters.toml. However how apps handle line height may vary, and you can check out the app’s settings first.

发自我的 iPhone

在 2018年7月14日，15:50，Maciej Raciborski <notifications@github.com<mailto:notifications@github.com>> 写道：


Wouldn't the line height just shrink the height without changing the position of ">" against other characters?

**Comment by b0rski** [comment]
The app allows to change the vertical character spacing, it helped a bit but not 100% to change the position of ">" against other characters. It seems that ">" has less height than the whole line. I'll try the parameters you mentioned.

**Comment by b0rski** [comment]
UPDATE: I observe this behavior on MacOS X only. Windows 10 is good.

**Comment by HansPinckaers** [comment]
At least for the powerline characters you could try the configurations options here: https://github.com/be5invis/Iosevka/blob/bae8c1c6c0362b4358c63b4a53f3e2ebb2274484/parameters.toml#L69

I had to tweak them like this (but note: I'm on Ubuntu, you probably need other values):
```
# Powerline-specific parameters
powerlineScaleY = 0.91 # Vertical scale
powerlineScaleX = 1 # Horizontal scale
powerlineShiftY = 50 # Vertical shift
powerlineShiftX = -20 # Horizontal shift
```
