### ISSUE TITLE
Font family name

### ISSUE THREAD

**Issue by manuel-uberti** [be5invis/Iosevka#284]
* Your font version: `version 2.0.0, codename Olivida`
* Your font variant: ss08 (Pragmata Pro)
* Your operating system (name and version): Ubuntu 18.04
* Your application using Iosevka: gnome-terminal, GNU Emacs

First of all, thanks for this awesome font. Been using it for a while now, and it is by far my favourite monospace font.

This is a question, more than an actual problem. I just downloaded the latest version. As usual, I put the files from the `ttf` directory in my `~/.fonts` directory and run `fc-cache -fv`.

Upon selecting the font in gnome-terminal, I see that the font name is now `Iosevka SS08 Regular Semibold` instead of `Iosevka Regular Semibold` like it was before. Is this intended?

**Comment by be5invis** [comment]
Yes. The `SSxx` variants are now renamed so it could be co-existed with existing fonts.
That is why I changed the major version.

**Comment by manuel-uberti** [comment]
Awesome, thanks.
