### ISSUE TITLE
APL symbol set is inconsistent

### ISSUE THREAD

**Issue by roman-kashitsyn** [be5invis/Iosevka#286]
* Your font version: 1.14.3
* Your font variant: Iosevka Term
* Your operating system (name and version): Ubuntu 16.04
* Your application using Iosevka: Emacs
---

APL symbol set looks extremely inconsistent. A similar issue was recently fixed in v.0.826 of PragmataPro: 
https://github.com/fabrizioschiavi/pragmatapro/issues/64

This is the difference between "Iosevka Term" and "APL385 Unicode" on my machine:
![iosevka_vs_apl385](https://user-images.githubusercontent.com/847968/43080438-098b66ba-8e90-11e8-944e-e0108dcd8e21.png)

Actual text:
```
          stars: *⍣⍟
        circles: ⍥○⍟⌽⍉⊖⍜⊙
        slashes: /⌿⍁%
    backslashes: \⍀⍂
        uptacks: ⍊⍎⊥
      downtacks: ⍡⍑⍕⊤
       epsilons: ∉∊⍷
           jots: ∘⍤⍛¤⍝
         commas: ,⍪;⍮
       diamonds: ⋄⌺⍚
           dels: ⍫∇⍢⍒
         stiles: ⍒⍋∥⍭|⍦
         deltas: ∆⍙⍋
      up arrows: ↑⍐⍏
    down arrows: ⍖⍗↓
```

Top issues:

  1. Number of edges and styling of the stars don't match.
  1. Circles have very inconsistent sizes and different line thickness, length of the lines in ⌽ and ⍉ are different.
  1. Epsilons are extremely inconsistent.
  1. All the diamonds have different sizes.
  1. Dots in ⍡ aren't centered properly, same with ⍢, ⍣ and ⍤.

**Comment by be5invis** [comment]
I really do not have any experience of APL.
Thank you for classifying these symbols.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/44220636-bbfcf280-a1b1-11e8-8d7c-2bd8e328c401.png)

Still some questions: 

- `⍷`: Should it be aligend with Greek letters, or the `∈` symbol?
- `⍝`: Is the simplification shown in your image really correct?
- Boxed operators (like `⍐⍗`): Arrows in Iosevka are really tall so is squashing the arrows acceptable?

**Comment by be5invis** [comment]
O logicals and cup/caps.
`∪∩∧∨` <- I admit these are a little too tall.

**Comment by abrudz** [comment]
1. `⍎⍕` seem to be composed of thin stretched `⊥⊤` and a `○` even though they should be composed of normal `⊥⊤` and a `∘`.
2. `⍉⌽` are too thin.
3. The symbols `⌺` and `⍝` are actually supposed to look like overstrikes (one symbol printed on top of another symbol), so having the inner symbol's line overlap with the out symbol is fine.
4. I'm a bit confused about the state of overstrikes like `⌿` and `⍋`. In @be5invis screenshot it looks like they have hairline white gaps between parts. In @roman-kashitsyn it looks like it doesn't. Either way, it should be consistent across glyphs. If there is a hairline gap, is it the primary or the secondary glyph which is "on top"?

**Comment by roman-kashitsyn** [comment]
> In @be5invis screenshot it looks like they have hairline white gaps between parts. In @roman-kashitsyn it looks like it doesn't. 

@be5invis used the version of the font built from head, mine is one of the latest released.

**Comment by be5invis** [comment]
reactivate

**Comment by abrudz** [comment]
How does the current set look?

**Comment by jxy** [comment]
```
          stars: *⍣⍟
        circles: ⍥○⍟⌽⍉⊖⍜⊙
        slashes: /⌿⍁%
    backslashes: \⍀⍂
        uptacks: ⍊⍎⊥
      downtacks: ⍡⍑⍕⊤
       epsilons: ∉∊⍷
           jots: ∘⍤⍛¤⍝
         commas: ,⍪;⍮
       diamonds: ⋄⌺⍚
           dels: ⍫∇⍢⍒
         stiles: ⍒⍋∥⍭|⍦
         deltas: ∆⍙⍋
      up arrows: ↑⍐⍏
    down arrows: ⍖⍗↓
          shoes: ⊂⊆⊃∪∩⍝∘
       diaresis: ¨⍨⍣⍤∘
    comparisons: <≤>≥∧⍲∨⍱
     equalities: =⌸≠≡≢
          tacks: ⊢⊣⊥⊤⍎⍕
   line heights: ⌿⍀⍖/\⍉↓⌽⍁⍂⍗
       (s)quads: ⍠⌸⌹⌺⎕⍁⍂⍐⎕⌷
```

<img width="547" alt="Screen Shot 2019-04-10 at 11 31 48 PM" src="https://user-images.githubusercontent.com/89739/55930847-d4aa9480-5be8-11e9-87ac-90441d5af177.png">

This is Iosevka 2.2.0 on the left versus APL385 on the right.  It's much better over all.  The following could be improved.

1. the alignment of stars: align `*` (it is aligned in some variants such as SS09)
2. the length of tacks: make them shorter
3. the height of shoes: make them shorter
4. the width of Squad `⌷`: make it narrower to distinguish it from Quad `⎕`
5. I seem to lost the semicolon underbar `⍮` (it exists in the Term variant), but I think it is not used in any major APLs

**Comment by abrudz** [comment]
Adding to @jxy 's list:
4. Squad `⌷` looks like a smaller version of `⎕`. In APL385, it is even *taller* than `⎕` to make the destinction even clearer. In fact, it is meant to be as if `[` and `]` were printed on top of each other.
5. `⍮` is used in dzaima/APL and in Extended Dyalog APL.
6. The epsilons `∉∊⍷` look very inconsistent. The last one should be lunate, as it is also a form of membership.

**Comment by abrudz** [comment]
Any development happening on this?

**Comment by abrudz** [comment]
Nothing happening, I guess?

**Comment by AlsoScratch** [comment]
@be5invis Do you think this should be pinned?

**Comment by be5invis** [comment]
@jxy @AlsoScratch 
I am a little curious about the current user base of APL.
Note that many APL symbols are shared with common mathematical symbols. It is a hard task to balance both.
I can add an OTL tag though.

**Comment by be5invis** [comment]
Also @jxy @AlsoScratch @abrudz 
For tack symbols `⍊⍎⊥⍡⍑⍕⊤` are they binary, unary or nullary?
The `⊥⊤` are used in logics to describe "false" and "true", and are nullary.

**Comment by be5invis** [comment]
This is the current `dev`
![image](https://user-images.githubusercontent.com/240091/71541343-4c9e2380-290c-11ea-9a55-026a8d447437.png)

**Comment by abrudz** [comment]
It is getting much better now. I still think the vertical cups, caps, tacks and logics `⊥⍊⍎⊤⍑⍡⍕⍝∩∪⍦∧⍲∨⍱` are too tall — they should rather have the same height as the width of their horizontal peers. `⊢⊣⊂⊃<>≤≥`. @be5invis Most APL symbols can be used with one or two arguments.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/71550792-3e441c00-298d-11ea-9373-0dc602a0d894.png)
Latest Dev

**Comment by abrudz** [comment]
This is quite nice. Which variant is this?

**Comment by AlsoScratch** [comment]
The _'is an element of'_ symbol still looks inconsistent with the _'not an element of'_ symbol.

**Comment by abrudz** [comment]
Is there a rule for the layering of composite symbols?

Composite, Modifier, Base:
* `⌿` is `-` in front of `/`
* `⍀` is `-` in front of `\`
* `⌽` is `|` in front of `○`
* `⍉` is `\` in front of `○`
* `⍫` is `~` in front of `∇`
* `⍭` is `~` in front of `|`
* `⍲` is `~` in front of `∧`
* `⍱` is `~` in front of `∨`

Composite, Modifier, Base:
* `⍏` is `-` behind `↑`
* `⍖` is `-` behind `↓`
* `⍋` is `|` behind `∆`
* `⍒` is `|` behind `∇`
* `⍮` is `_` behind `;`
* `⍦` is `|` behind `∪`

Composite, Modifier, Base:
* `⍎` is `∘` merged with `⊥`
* `⍕` is `∘` merged with `⊤`
* `∉` is ` /` merged with `∊`
* `≠` is `/` merged with `=`
* `≢` is `/` merged with `≡`

**Comment by abrudz** [comment]
The squish quad `⌷` is actually not connected with the quads `⎕` but rather with square brackets: `[]` maybe it should be less tall?

**Comment by be5invis** [comment]
@AlsoScratch The problem around `∉∊⍷` is that APL is using U+200A “SMALL ELEMENT OF” rather than U+2208 “ELEMENT OF”. I am curious about why APL choose the small variant.

**Comment by abrudz** [comment]
@be5invis Because it is seen as a mathematical operator which normally has about the same base dimensions as `×` and +` while floating in the middle of the line. `∈` and therefore `∉` are supposedly "full height" characters like `E`, while `∊` is more like `⊂` with a bar. That being said, some APLs allow either. (And no APL I know of uses `∉`). See https://aplwiki.com/wiki/Unicode

**Comment by be5invis** [comment]
@abrudz Does APL use a specialized variant of U+2209 `NOT AN ELEMENT OF`?

Current Dev ↓
![image](https://user-images.githubusercontent.com/240091/71562600-448ed280-2a37-11ea-9996-20f5fca5289e.png)

**Comment by abrudz** [comment]
@be5invis No, `~` is NOT so `~∊` is ["not a member of"](https://tryapl.org/?a=1%202%203%28%7E%u220A%293%201%204%201%205&run).

Oh, and I didn't mean `⌷` should _be_ `[]`, just that it should have the same height as the brackets. It isn't a problem if that happens to line up with `⎕`. It was fine before.

The new `∊` is much nicer. Thank you for that and all your hard work. It has really paid off. I'll now begin recommending Iosevka to APLers. Could you tell me which style this is?

**Comment by be5invis** [comment]
@abrudz Just `v-asterisk-low` activated, or normal Iosevka with `cv19` enabled if you are in an editor that supports enabling custom OpenType tags, such as VSCode.

Current Dev:
![image](https://user-images.githubusercontent.com/240091/71562917-6474c500-2a3c-11ea-9cc5-c4418eb5adba.png)

**Comment by AlsoScratch** [comment]
Wait, you can use OpenType in Visual Studio Code? I tried searching for it but could not find anything about it.

**Comment by be5invis** [comment]
@AlsoScratch https://code.visualstudio.com/updates/v1_40#_font-feature-settings

**Comment by AlsoScratch** [comment]
@be5invis Shouldn't the first character in the 'circles' category also be in the 'diaresis' category as well?

**Comment by abrudz** [comment]
@AlsoScratch @be5invis `⍥` indeed has a diaeresis and so do `⍡` and `⍢`.
Also `⌽` belongs in the stiles too, `⍦` should be added to the shoes, `⍎` and `⍕` to the jots, etc. etc.

I've added what I could find to the table below:

```apl
          stars: *⍣⍟⋆
        circles: ⍥○⍟⌽⍉⊖⍜⊙⌾⌼
        slashes: /⌿⍁%≠≢
    backslashes: \⍀⍂
        uptacks: ⍊⍎⊥
      downtacks: ⍡⍑⍕⊤
       epsilons: ∉∊⍷∍
           jots: ∘⍤⍛⍎⍕¤⍝⌻⌾
         commas: ,⍪;⍮
       diamonds: ⋄⌺⍚
           dels: ⍫∇⍢⍒
         stiles: ⍒⍋∥⍭|⍦⍧⍅⍆
         deltas: ∆⍙⍋
      up arrows: ↑⍐⍏
    down arrows: ↓⍗⍖
   right arrows: →⍈⍆
    left arrows: ←⍇⍅
          shoes: ⊂⊆⊇⊃∪∩⍝⍦⋔⍧
      diaeresis: ¨⍡⍢⍨⍣⍤⍩
    comparisons: <≤>≥⍩⍃⍄
         wedges: ∧⍲∨⍱⍓⍌
     equalities: =⌸≠≡≢
          tacks: ⊢⊣⊥⌶⊤⍎⍕
          quads: ⍠⌹⌸⍯⌺⎕⍁⍂⌼⌻⍃⍄⍓⍌⍔⍍⍞⍰⍐⍗⍇⍈
      underbars: ⊆⊇⍊⍘⍙⍚⍛⍜⍮⍶⍷⍸⍹⍷
         alphas: ⍺⍶
         omegas: ⍵⍹
           bars: -⌿⍀⍪⊖÷
       overbars: ¯⍑
         tildes: ~⍲⍱⍬⍫⍭⍨
         colons: ⍠:⌹÷
       brackets: ⌷[]
   line heights: ⌿⍀⍖/\⍉↓⌽⍁⍂⍗
```

**Comment by AlsoScratch** [comment]
I think the `⍷` is repeated in underbars.

**Comment by AlsoScratch** [comment]
@be5invis Does the dev already have `∍`?

**Comment by abrudz** [comment]
Removed duplicated `⍷`
To be clear, `∍` isn't actually used by any APL (and lots of the symbols are not). I just put it there for comparison.

**Comment by AlsoScratch** [comment]
I only have the latest official version; we'll have to refer to @be5invis to know which of those characters are and aren't currently supported in the latest dev.

**Comment by AlsoScratch** [comment]
> @AlsoScratch @be5invis `⍥` indeed has a diaeresis and so do `⍡` and `⍢`.
> Also `⌽` belongs in the stiles too, `⍦` should be added to the shoes, `⍎` and `⍕` to the jots, etc. etc.
> 
> I've added what I could find to the table below:
> 
> ```apl
>           stars: *⍣⍟⋆
>         circles: ⍥○⍟⌽⍉⊖⍜⊙⌾⌼
>         slashes: /⌿⍁%≠≢
>     backslashes: \⍀⍂
>         uptacks: ⍊⍎⊥
>       downtacks: ⍡⍑⍕⊤
>        epsilons: ∉∊⍷∍
>            jots: ∘⍤⍛⍎⍕¤⍝⌻⌾
>          commas: ,⍪;⍮
>        diamonds: ⋄⌺⍚
>            dels: ⍫∇⍢⍒
>          stiles: ⍒⍋∥⍭|⍦⍧⍅⍆
>          deltas: ∆⍙⍋
>       up arrows: ↑⍐⍏
>     down arrows: ↓⍗⍖
>    right arrows: →⍈⍆
>     left arrows: ←⍇⍅
>           shoes: ⊂⊆⊇⊃∪∩⍝⍦⋔⍧
>       diaeresis: ¨⍡⍢⍨⍣⍤⍩
>     comparisons: <≤>≥⍩⍃⍄
>          wedges: ∧⍲∨⍱⍓⍌
>      equalities: =⌸≠≡≢
>           tacks: ⊢⊣⊥⌶⊤⍎⍕
>           quads: ⍠⌹⌸⍯⌺⎕⍁⍂⌼⌻⍃⍄⍓⍌⍔⍍⍞⍰⍐⍗⍇⍈
>       underbars: ⊆⊇⍊⍘⍙⍚⍛⍜⍮⍶⍷⍸⍹
>          alphas: ⍺⍶
>          omegas: ⍵⍹
>            bars: -⌿⍀⍪⊖÷
>        overbars: ¯⍑
>          tildes: ~⍲⍱⍬⍫⍭⍨
>          colons: ⍠:⌹÷
>        brackets: ⌷[]
>    line heights: ⌿⍀⍖/\⍉↓⌽⍁⍂⍗
> ```

@be5invis I hope you don’t mind showing how this looks like in the current dev.

**Comment by AlsoScratch** [comment]
> @AlsoScratch @be5invis `⍥` indeed has a diaeresis and so do `⍡` and `⍢`.
> Also `⌽` belongs in the stiles too, `⍦` should be added to the shoes, `⍎` and `⍕` to the jots, etc. etc.
> 
> I've added what I could find to the table below:
> 
> ```apl
>           stars: *⍣⍟⋆
>         circles: ⍥○⍟⌽⍉⊖⍜⊙⌾⌼
>         slashes: /⌿⍁%≠≢
>     backslashes: \⍀⍂
>         uptacks: ⍊⍎⊥
>       downtacks: ⍡⍑⍕⊤
>        epsilons: ∉∊⍷∍
>            jots: ∘⍤⍛⍎⍕¤⍝⌻⌾
>          commas: ,⍪;⍮
>        diamonds: ⋄⌺⍚
>            dels: ⍫∇⍢⍒
>          stiles: ⍒⍋∥⍭|⍦⍧⍅⍆
>          deltas: ∆⍙⍋
>       up arrows: ↑⍐⍏
>     down arrows: ↓⍗⍖
>    right arrows: →⍈⍆
>     left arrows: ←⍇⍅
>           shoes: ⊂⊆⊇⊃∪∩⍝⍦⋔⍧
>       diaeresis: ¨⍡⍢⍨⍣⍤⍩
>     comparisons: <≤>≥⍩⍃⍄
>          wedges: ∧⍲∨⍱⍓⍌
>      equalities: =⌸≠≡≢
>           tacks: ⊢⊣⊥⌶⊤⍎⍕
>           quads: ⍠⌹⌸⍯⌺⎕⍁⍂⌼⌻⍃⍄⍓⍌⍔⍍⍞⍰⍐⍗⍇⍈
>       underbars: ⊆⊇⍊⍘⍙⍚⍛⍜⍮⍶⍷⍸⍹
>          alphas: ⍺⍶
>          omegas: ⍵⍹
>            bars: -⌿⍀⍪⊖÷
>        overbars: ¯⍑
>          tildes: ~⍲⍱⍬⍫⍭⍨
>          colons: ⍠:⌹÷
>        brackets: ⌷[]
>    line heights: ⌿⍀⍖/\⍉↓⌽⍁⍂⍗
> ```

@be5invis Can we see what this looks like now?

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/72048238-32036d00-3271-11ea-87a3-2174b78a9c28.png)
@AlsoScratch @abrudz 
Note: I cannot synchronize everything specially for APL, especially these symbols shared with other symbol blocks.

**Comment by AlsoScratch** [comment]
`∍` is missing, but I guess that's OK since it's not used in APL.

**Comment by AlsoScratch** [comment]
Also, quick reference to #395 where you suggest of a much-needed improvement of the `~` shape. Has it been implemented in the picture above?

**Comment by be5invis** [comment]
Well I choose another way to implement the wave arrows so the tildes are kept as-is.

**Comment by AlsoScratch** [comment]
I thought you were changing the shape of the tilde to look similar to the arrows.

**Comment by abrudz** [comment]
@be5invis This looks really good. When can we expect a release?

P.S. I call them *base* and *number* because they are APL keyboard layouts have them on <kbd>b</kbd> and <kbd>n</kbd> and *base* is mnemonic for the shape `⊥`. I guess *base* and *nexus* would work and still be mnemonic.

**Comment by arknjl** [comment]
> P.S. I call them _base_ and _number_ because they are APL keyboard layouts have them on b and n because base in mnemonic for the shape 

i particularly like bottom and top
1. visually represent the shapes as well (dash is on bottom, dash is on top)
2. if you really forget, the T shape could mean Top or True (their well-known meaning)
3. type theory and other math calls them bottom and top too

**Comment by be5invis** [comment]
Mark as closed. Please raise new issue if really needed.
