### ISSUE TITLE
Glyph Request: Flat Tail for 't'

### ISSUE THREAD

**Issue by tylerchamberland** [be5invis/Iosevka#289]
* Your font version: 2.0.0
* Your font variant: Custom Build Slab
* Your operating system (name and version): Mac and Windows

I have a couple different custom builds that I use in different situations.  One thing that I feel is missing is a flat-tailed 't' similar to the flat tail in the 'v-i-zshaped' and 'v-l-zshaped'.  Currently I am using the curved tail t in my sans builds and the cross-style in my slab builds, but I would prefer to have a flat-tailed t glyph for my slab builds.

Thanks for reading :)

**Comment by be5invis** [comment]
Move to #140.
