### ISSUE TITLE
missing small triangle characters

### ISSUE THREAD

**Issue by cstrahan** [be5invis/Iosevka#29]
It looks like the following characters are not supported:

Unicode character|Oct|Dec|Hex|HTML
---|---|---|---|---
black right-pointing small triangle|022670|9656|0x25B8|&#9656;
black down-pointing small triangle|022676|9662|0x25BE|&#9662;

It would be awesome to have those so file system trees like [NERDTree](https://github.com/scrooloose/nerdtree) render properly.

Thanks!

**Comment by Zhichao-Hong** [comment]
Hmm, I can see both arrows in the beta9 release using NERDTree in either MacVim or Neovim.  See  the attached image.
<img width="220" alt="screen shot 2015-11-25 at 6 21 24 pm" src="https://cloud.githubusercontent.com/assets/7292212/11412355/6d68da56-93a1-11e5-90dd-d702c148dabd.png">

**Comment by be5invis** [comment]
@Zhichao-Hong No, the small triangles are not included in Iosevka... yet.
![image](https://cloud.githubusercontent.com/assets/240091/11439970/ba8aa8fc-9539-11e5-9e50-59c9d3d75f1a.png)

**Comment by be5invis** [comment]
@cstrahan So, how about this?
![image](https://cloud.githubusercontent.com/assets/240091/11443451/5148bde2-9558-11e5-9f6e-01c385cd7931.png)

**Comment by be5invis** [comment]
Triangles are included in version 1.0.0. Closed.

**Comment by cstrahan** [comment]
@be5invis Awesome - thanks a ton!
