### ISSUE TITLE
Consolidation of Ligation Requests

### ISSUE THREAD

**Issue by be5invis** [be5invis/Iosevka#290]

**Comment by HarrisonB** [comment]
Fira Code has a thin backslash for escape sequences. Would this be possible in Iosevka?

![thin-backslash](https://user-images.githubusercontent.com/8454804/43809551-accbb4aa-9a67-11e8-823f-304888c43565.png)

**Comment by lshoravi** [comment]
What's the possibility of getting to choose one ligature over another? I.e slanted lower line vs straight lower line in greater-than-or-equal, and 'joined' /= instead of the current one?

**Comment by be5invis** [comment]
@lshoravi It could have.
@HarrisonB I may add some style sets to enable/disable parts of the ligation sets for default (`calt`) feature, rather than aliasing to another existing ligation set (like Haskell).

**Comment by NuckChorris** [comment]
@be5invis Should this issue be `pinned` to prevent stale-closing?

Because I have a ligation request: Git conflict markers (which look like this currently)

<img width="427" alt="screen shot 2019-01-27 at 8 03 05 pm" src="https://user-images.githubusercontent.com/430411/51814473-3c9b4100-2270-11e9-84e9-1b77e0b10b46.png">

So it's just 7 `<`, `=`, or `>` signs in a row

**Comment by eproxus** [comment]
I'd like to request a ligation for `||`. It's used in list comprehensions in Erlang:

```erl
[N + 1 || N <- [1,2,3]].
```

A slightly tighter grouping of the two bars would be nice.

**Comment by be5invis** [comment]
@NuckChorris Fixed in latest release `=` will be correctly chained.

**Comment by jbaum98** [comment]
I would like to request a ligation for `(**`, which is used to open `coqdoc` comments in Coq, kind of like how `/**` is used for `javadoc` comments. Right now, the `(*` has a nice ligature, but the second asterisk is left behind way above the first:
![image](https://user-images.githubusercontent.com/5283991/57004516-91b35f80-6b9d-11e9-8cb2-d722652a1c18.png)

**Comment by eproxus** [comment]
Another request: `=:=` for _exactly equal_ in Erlang.

**Comment by RoyTinker** [comment]
Another request: `===` and `!==` are difficult to distinguish from `==` and `!=` -- the only ligature differences are that they vary in width.

Fira Code solves this by adding a third horizontal line:
![image](https://user-images.githubusercontent.com/984080/64386683-a6da4800-cfee-11e9-96a8-1175eb77fa1d.png)

**Comment by wookiee** [comment]
I'd like to request left-arrow (**<-**) and double-headed arrow (**<->**), the latter currently renders like this: 
<img width="79" alt="image" src="https://user-images.githubusercontent.com/1214535/64717232-821c1f80-d489-11e9-9020-8c0f9d6c43fb.png">

**Comment by wookiee** [comment]
> I'd like to request left-arrow (**<-**) and double-headed arrow (**<->**), the latter currently renders like this:
> <img alt="image" width="79" src="https://user-images.githubusercontent.com/1214535/64717232-821c1f80-d489-11e9-9020-8c0f9d6c43fb.png">

Nevermind, it looks like this is already in, but I need to enable it somehow? I'll give the readme a more thorough look-through and figure it out. Thanks!

**Comment by stone-zeng** [comment]
Could you please add the double brackets?

![image](https://user-images.githubusercontent.com/18233088/65367568-e13a1b00-dc65-11e9-91c6-f49151bc71c7.png)

They should be identical to uni27E6/uni27EC as well, and can be used in Wolfram Language/Mathematica, for example.

**Comment by be5invis** [comment]
@wookiee Looks more like a text segmentation problem, i.e., your editor is thinking `<` and `->` are two tokens.
@stone-zeng Shouldn’t Mathematica’s editor do this job?

**Comment by stone-zeng** [comment]
@be5invis There are some other languages use double brackets, e.g. R, bash and the Polymer library.

**Comment by t532** [comment]
@stone-zeng There's a problem though, some languages use `[|` `|]` and many fonts also has their ligatures identical to uni27E6/uni27EC.

**Comment by t532** [comment]
Ligature Request - `<>` in Haskell and similar language is an operator for `mappend`, the operator equipped with a monoid. It is rendered as a diamond in Fira Code.

**Comment by be5invis** [comment]
@t532 There's ligation set configurations that produces different ligation for them. `calt-ltgt`, which is the ligation set Coq enabled, will turn `<>` into `≠`. For the haskell variant, it may be another ligation set called `calt-ltgt-diamond`...

**Comment by be5invis** [comment]
@t532 Landed in `dev`.

**Comment by be5invis** [comment]
I'd like to close this issue now.
For further ligation requests, please open separate issues.
