### ISSUE TITLE
Missing iosevka-pack in 2.0.0 release

### ISSUE THREAD

**Issue by jandudulski** [be5invis/Iosevka#291]
From the release description:

> The bundled `iosevka-pack-#.#.#` option contains all packages from `01.iosevka-#.#.#` to `08.iosevka-cc-slab-#.#.#`.

But unfortunately, it hasn't been added to the 2.0.0 release.

**Comment by be5invis** [comment]
They are now the TTC packages

**Comment by jandudulski** [comment]
Outdated documentation is worse than lack of documentation :dancer:
