### ISSUE TITLE
Strange alignment ligatures "=>", "->", "<-"

### ISSUE THREAD

**Issue by Lucky-Loek** [be5invis/Iosevka#293]
* Your font version: version 2.0.0
* Your font variant: default settings (`01-iosevka-2.0.0`), TrueType
* Your operating system: Windows 10 Enterprise, build 1803
* Your application using Iosevka: Visual Studio Code 1.26.1

---

As I was just typing some code, I noticed the ligatures for double arrow (`=>`), single arrow (`<-` and `->`) and all of the derivatives (longer lines, like `-->` or `==>`) were not well vertically aligned.

This might be a VS Code thing, since I never saw it happening before the 1.26.1 update, but I never really looked at the ligatures earlier either. It can also be my screen, as it is a 13.3" 1366x768 screen. Earlier I used to work with 1080p screens, where the aligment never looked out of place to me.

It happens at all font sizes and line heights (tested from 8px to 24px and turns up everywhere). 

![code](https://user-images.githubusercontent.com/9716643/44401119-d3d7cc00-a54d-11e8-857b-6d2715291209.png)

**Comment by be5invis** [comment]
The `-` and `>` in a `->` ligation are **two glyphs** rather than one, so rounding may distort them.
You can try to uninstall the existing version and install the unhinted version instead.

**Comment by Lucky-Loek** [comment]
First, thanks for the blazing fast reply!

Did as you suggested and it seems to be much better now. Still looks a tiny bit unaligned, but not as annoyingly as earlier. In the screenshot it seems to be completely fixed, so the rest is probably my screen.

![code](https://user-images.githubusercontent.com/9716643/44401657-970cd480-a54f-11e8-8c6d-0acf71407879.png)

**Comment by codehz** [comment]
@Lucky-Loek I think it is [Optical illusion](https://en.wikipedia.org/wiki/Optical_illusion)
![image](https://user-images.githubusercontent.com/13158903/44406679-cf7fd300-a58e-11e8-80bf-333fe3d8d947.png)

**Comment by Lucky-Loek** [comment]
Might very well be indeed.. Never noticed it before though.

Anyway, thanks again for the super fast help :)
