### ISSUE TITLE
Ligatures do not work on Terminal.app for macOS

### ISSUE THREAD

**Issue by HarrisonB** [be5invis/Iosevka#294]
* Your font version: v2.0.0
* Your font variant: ss05
* Your operating system (name and version): macOS 10.13.4 (High Sierra)
* Your application using Iosevka: Terminal.app (built-in macOS terminal)

---

Ligatures are not working in Terminal.app. Ligatures, from other fonts such as Fira Code, function as expected. I understand this isn't really the fault of Iosevka (seems to be more of a Terminal.app ligature support issue) but I didn't know if it would be a simple change to fix.

According to [this chat](https://spectrum.chat/thread/170c5aac-33f3-46a3-ac58-89b558471bcc?m=MTUyNjI1NDI2Nzg1Nw==) about a font which faced similar problems, it appears Terminal.app doesn't support `liga` or `dlig` ligatures and only support `calt`.

Thanks for all of your work on this great font!

**Comment by be5invis** [comment]
I do not think it is simple.
Iosevka used a very unique way to support ligation (yes, ligation, not ligature, because I am not merging multiple glyphs into one). Supporting it requires the software to have full, proper support of OpenType.
Iosevka used `calt`.

**Comment by HarrisonB** [comment]
Gotcha. Thanks for clarifying!
