### ISSUE TITLE
Symbols are not being scaled properly when using "leading-1000"

### ISSUE THREAD

**Issue by maximbaz** [be5invis/Iosevka#295]
* Your font version: (Release or git, version) git, https://github.com/be5invis/Iosevka/commit/88a45b825c8eb43ae3fc8ed96cd616f4eab86675
* Your font variant: custom
* Your operating system (name and version): Arch Linux
* Your application using Iosevka: (some Java applications may have problem in showing Iosevka properly. It is a bug in Java's GUI components.) kitty terminal

* Your `parameters.toml`:
```
[buildPlans.iosevka-custom]
family = "Iosevka Custom"
design = [
  "cv05", # i
  "cv08", # l
  "cv17", # ~
  "cv19", # *
  "cv21", # _
  "cv24", # g
  "cv26", # m
  "cv38", # $
  "cv45", # #
  "cv51", # 1

  "term",
  "leading-1000",
]
```

-----

See how brackets are not being scaled and are cut-off:

![image](https://user-images.githubusercontent.com/1177900/45249064-ec9bfc00-b319-11e8-9991-fc027927b5ff.png)

**Comment by maximbaz** [comment]
Slash and vertical bar seem to be too high as well:

**Comment by be5invis** [comment]
@maximbaz 
The `css` property should be kept to 400. If you change that the font name would be changed to "Iosevka Light".

**Comment by be5invis** [comment]
https://github.com/be5invis/Iosevka/blob/master/meta/aesthetics.ptl#L17
Size of parens are defined with fixed params (not affected by `leading`.
Hmmm...

**Comment by be5invis** [comment]
Here is the story:

- Brackets' center is set to the `parenMid` parameter (0.365em currently)
- Brackets' size is defined by the metrics of ascender/descender;
- Brackets' size would affect many other metrics.

Changing `parenMid`, `xheight` and `cap` in parameter files **will** affect the size of brackets but would cause many other problems (like letters being distorted).

If you accept maybe I can add a separate parameter to adjust brackets' size...

**Comment by maximbaz** [comment]
> The css property should be kept to 400

Got it, thanks for the tip 👍 

> Changing parenMid, xheight and cap in parameter files will affect the size of brackets but would cause many other problems (like letters being distorted).

Just curious, can we selectively choose which symbols need to depend on `leading`? On the last gif, letters for example look quite all right to me, the vertical space between e.g. "real" is large enough for the text to be readable. Digits are questionable (there's less vertical space between two lines, but at least they don't overlap), but all the symbols are too large that they overlap with the previous line.

**Comment by be5invis** [comment]
@maximbaz Maybe I can add a new series of parameters that adjusts parens...

**Comment by maximbaz** [comment]
Not only parens, I would say all symbols that are taller than `!` will touch previous line, so at the very least these should be smaller:

![image](https://user-images.githubusercontent.com/1177900/45254050-509ddf00-b371-11e8-8739-ccbefa052e04.png)

Click on the image, there's one-pixel line above all symbols.

What do you think?

**Comment by maximbaz** [comment]
This issue is also visible when terminal starts underlining text, `g` I understand, but I don't think slash should intersect with underline...

![image](https://user-images.githubusercontent.com/1177900/45254148-9d82b500-b373-11e8-894c-d7fa28b17d05.png)

**Comment by be5invis** [comment]
@maximbaz 
`g` should have descender I think.
Slashes, `#` symbols and many other symbols share same metrics and they should be affected with one parameter.

**Comment by maximbaz** [comment]
I think we both agree on `g`, yes 😉 

Great, one parameter to rule them all sounds perfect, I would be happy to test when you have a prototype or fix for this 😉 Thanks for your quick replies, by the way 😉

**Comment by be5invis** [comment]
@maximbaz I've made a commit that you can alter these parameters:

- `parenSize`: Size of brackets, slashes, etc.
- `operSize`: Size of most math operators
- `tackSize`: Size of tack operators.

**Comment by maximbaz** [comment]
Great, I think this will work! I quickly tested by setting intentionally small value for all 3 parameter, I noticed that `$` is not affected by them and is now the only symbol that has almost no vertical space left — just to make sure, did you leave out dollar intentionally or by accident?

![image](https://user-images.githubusercontent.com/1177900/45254625-c0b16280-b37b-11e8-93a8-4038a811bef5.png)

**Comment by be5invis** [comment]
`$` shares metrics with `S` and it is not considered as a "symbol".

**Comment by maximbaz** [comment]
Can it be made into a symbol, or there is a reason you want to keep it being considered a letter?

`S` itself looks quite good, by the way:

![image](https://user-images.githubusercontent.com/1177900/45254706-df642900-b37c-11e8-834d-1df36e683538.png)

**Comment by be5invis** [comment]
Added `v-dollar-opencap` (`cv54`) and `v-dollar-throughcap` (`cv55`). Hope you like it.

**Comment by be5invis** [comment]
@maximbaz 
Added `v-dollar-opencap` (`cv54`) and `v-dollar-throughcap` (`cv55`) into a new commit. Hope you like it.

**Comment by maximbaz** [comment]
Thanks, yeah I think the two new `cvXX` are a good idea 👍 

I'll close the issue since my use-case seems to be solved. Thanks again.

**Comment by llitz** [comment]
It can be really complex to align all the parameters when compiling the fonts. Considering most uses for leading-1000 would be people wanting a tighter 
 I will leave this here in case other people are also using leading-1000.

on parameters.toml change or comment the original values before using these:
```
cap = 700
xheight = 510
ideoMid  = 350
symbolMid = 300
parenSize = 900
operSize = 700
tackSize = 700
```
There is still room for improvement on this configuration, but it is a start.

**Comment by tomas-chrastina** [comment]
I have similar problem with building custom font with `leading-1000` on Windows. It's cut-off from top on all characters on sizes 6 and 9 (sure I don't care for size 6, but some might). Othes sizes looks fine.

`private-build-plan.toml`
```
design  =   [   "term",
                "expanded",
                "leading-1000


",
                "cvXX", # few custom cvs follow
]

![Iosevka leading-1000](https://user-images.githubusercontent.com/14962885/61954042-333d2800-afb8-11e9-9b1f-d9157b214d7d.png)
