### ISSUE TITLE
how to use the new version font for Visual Studio Code 

### ISSUE THREAD

**Issue by huangcan5421** [be5invis/Iosevka#297]
* Your font version:  1.3.2/2.0.0
* Your font variant: CC Slab
* Your operating system (name and version):windows 10
* Your application using Iosevka: (some Java applications may have problem in showing Iosevka properly. It is a bug in Java's GUI components.)

If you have problem when building Iosevka, please provide these informations:

* Your Node.js version:Unimportance
* Your _otfcc_ version:Unimportance
* Your `make` version:Unimportance
* Your results of `npm list`:
```
Unimportance
```
* Your `parameters.toml`:
```
Unimportance
```
* Your results of `make -d --no-builtin-rules`:
```
Unimportance
```
---

i was installed all *.ttc in 08-iosevka-cc-slab-2.0.0.zip But
i cant set  {"editor.fontFamily": "IosevkaCC Slab"} in Visual Studio Code 
the font virsion is 2.0.0
errMsg:'终端只支持等宽字体' 
google translation ”The terminal only supports monospaced fonts”

before 
i used {"editor.fontFamily": "inziu iosevkaCC Slab SC"}  in Visual Studio Code 
the font virsion is 1.3.2 
i was installed inziu-SC-bold.ttc，inziu-SC-bolditalic.ttc，inziu-SC-italic.ttc，inziu-SC-regular.ttc
its good 

im sorry to my prooly english 
i want update my font virsion ,how to do it? thanks

**Comment by be5invis** [comment]
VSCode's Terminal Font is controlled by `terminal.integrated.fontFamily` settings.
Also, have you tried [this](https://github.com/be5invis/sarasa-gothic), especially Sarasa Term?
