### ISSUE TITLE
Build on Linux failed with segmentation fault

### ISSUE THREAD

**Issue by Zhichao-Hong** [be5invis/Iosevka#30]
Trying to build the latest from Linux Mint using node 5.1.0 and latest patel-c, I got segementation fault following the instructions in readme.

Below is the console dump:
*** Done recursive build for eight,rotetedpropto in Iosevka Bold Italic 1.0 (Tabris)
    Iosevka Bold Italic 1.0 (Tabris) : Done Letter-like Mathematical Symbols
    Iosevka Bold Italic 1.0 (Tabris) : Done Mathematical Operators
    Iosevka Bold Italic 1.0 (Tabris) : Done Negative Operators
    Iosevka Bold Italic 1.0 (Tabris) : Done Large Operators
    Iosevka Bold Italic 1.0 (Tabris) : Done Other Mathematical Operators
    Iosevka Bold Italic 1.0 (Tabris) : Done Currency
    Iosevka Bold Italic 1.0 (Tabris) : Done Letterlike Symbols
    Iosevka Bold Italic 1.0 (Tabris) : Done compatibility ligatures
    Iosevka Bold Italic 1.0 (Tabris) : Done Arrows
    Iosevka Bold Italic 1.0 (Tabris) : Done Geometric
    Iosevka Bold Italic 1.0 (Tabris) : Done Block Shapes
    Iosevka Bold Italic 1.0 (Tabris) : Done Box-Drawing
    Iosevka Bold Italic 1.0 (Tabris) : Done Powerline
    Iosevka Bold Italic 1.0 (Tabris) : Done Phonetic Symbols
    Iosevka Bold Italic 1.0 (Tabris) : Done Suit Cards
    Iosevka Bold Italic 1.0 (Tabris) : Done Planets
    Iosevka Bold Italic 1.0 (Tabris) : Done Planets
    Iosevka Bold Italic 1.0 (Tabris) : Done Musical
make[1]: *** [build/.pass0-iosevka-bolditalic.fdt] Segmentation fault

**Comment by be5invis** [comment]
@Zhichao-Hong Perhaps a Node bug, see nodejs/Node#4017
I thought it is Windows-specific... Increasing `--max_executable_size=4096` will help.

**Comment by be5invis** [comment]
@Zhichao-Hong You can checkout the newest snapshot in master.

**Comment by Zhichao-Hong** [comment]
@be5invis, thank you for pointing this out.  I have sync'ed up with the latest snapshot and saw the --max_executable_size=4096 was integrated.  However, it is strange, the problem does not happen if I ran the individual node command such as: 
```sh
node --max_executable_size=8192 extract --feature build/.pass0-iosevka-bolditalic.ab.fea build/.pass0-iosevka-bolditalic.fdt
```

The problem only appears if I ran the command via make.  A few the mk files are having the windows line endings, so I changed them to be unix compatible (i.e. "\n instead of \r\n").  However, I still cannot make the make happen.

**Comment by be5invis** [comment]
@Zhichao-Hong The SEGFAULT (or Access Violation) is not reproducable every time. The retrying script in `makefile` will retry building for about 16 times.

**Comment by Zhichao-Hong** [comment]
@be5invis.  Hmm.  I agree that  it may be a node issue.  I tried to increase the stack_size as well for the node and nothing helped.  It consistently failed to build on linux while 16 retries all exhausted.  I am wondering if anybody else has tried on linux?

**Comment by be5invis** [comment]
The recent update will force Node to GC to avoid memory corruption. It may solve the elusive crashes.

**Comment by Zhichao-Hong** [comment]
@be5invis, the recent update does not fix the memory issue.  Great work!
Now I can build all the fonts with a little fix.  What I need to change is probably due to the version difference of ttx and fontforge.  I have to remove -quite command line option from fontforge.  And I need to remove -q from ttx command.  After the build, everythings looks great except the Iosevka(CC and slab) bold O.  There is a cut on the top. Please see attached image.
<img width="49" alt="screen shot 2015-11-27 at 10 45 51 pm" src="https://cloud.githubusercontent.com/assets/7292212/11450150/24cbb2fa-9559-11e5-90e9-dede26b81bf4.png">

**Comment by be5invis** [comment]
I think you are suffering some point loss from the old version of Fontforge.
Here is my result (in pass 1):
![image](https://cloud.githubusercontent.com/assets/240091/11451035/6c31fde6-95f1-11e5-82d9-0901f2d88f1f.png)

**Comment by Zhichao-Hong** [comment]
@be5invis, Thank you so much for the instructions!  All problems are gone after updated fontforge and ttx to the latest and the build is smooth with no modification needed.
