### ISSUE TITLE
OpenType Variations build?

### ISSUE THREAD

**Issue by davelab6** [be5invis/Iosevka#300]
As I start the process of onboarding these families into Google Fonts, I'd like to ask if/when you plan to offer a OpenType 1.8 Variable Fonts version, with a Weight axis? :)

**Comment by be5invis** [comment]
Sorry but no. OTVar is too weak to support Iosevka.

**Comment by be5invis** [comment]
Iosevka has

- Algebraic curves
- Boolean operations

They cannot be simply supported by existing system.

**Comment by davelab6** [comment]
I'm confused. The ttfs also do not have those things?

**Comment by be5invis** [comment]
Existing system of variation.
They could be recorded in static fonts, but for variation, current OTSPEC is not strong enough.

**Comment by davelab6** [comment]
I'm sorry I just don't understand. You have a wide set of static fonts. A
subset of that set can be lined up as a set of static fonts to form a "web
font family" which can only have 18 styles, 9 roman and 9 italic. Any 'web
font family' can therefore be turned into 2 VFs, 1 roman and 1 italic, with
a Weight axis. Additionally, if a set of web font families form a series of
width variations, they can be turned into 2 VFs, 1 roman and 1 italic, with
a Width and a Weight axis.

It is a pure compression play on the non-variations web font families.

That's what I'm asking for :)

**Comment by rben01** [comment]
+1. To my uneducated mind it seems like there's no reason Iosevka couldn't be made to have a WGHT variable axis (in two distinct fonts, upright and italic), but if it's really not possible with OpenType fonts, it would be great for users to understand why not.
