### ISSUE TITLE
新的字体无法下载

### ISSUE THREAD

**Issue by nuoyan001** [be5invis/Iosevka#301]
https://be5invis.github.io/Iosevka/inziu.html

这个页面的连接已经失效无法下载

**Comment by be5invis** [comment]
Inziu has been deprecated. Use Sarasa Gothic instead please.

**Comment by nuoyan001** [comment]
新字体命名在系统下是不同名的,找起来不方便,我安装的所有简体字体里,在某个IDE下错位,应该是双引号,或是) 之前的Inziu 一直是正常的,我重新做了系统忘了保存了
