### ISSUE TITLE
Same font looks very different in two different workareas

### ISSUE THREAD

**Issue by kshenoy** [be5invis/Iosevka#302]
* Your font version: 2.0.0
* Your font variant: off (default)
* Your operating system (name and version): Red Hat Enterprise Linux Workstation release 6.7 (Santiago)
* Your application using Iosevka: gvim

If you have problem when building Iosevka, please provide these informations:

* Your Node.js version:
* Your _otfcc_ version:
* Your `make` version:
* Your results of `npm list`:
```
Not building Iosevka; using the release version.
```
* Your `parameters.toml`:
```
(Not sure how to generate this)
```
* Your results of `make -d --no-builtin-rules`:
```
GNU Make 4.2.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Reading makefiles...
Updating makefiles....
 Considering target file 'GNUmakefile'.
  File 'GNUmakefile' does not exist.
  Looking for an implicit rule for 'GNUmakefile'.
  No implicit rule found for 'GNUmakefile'.
  Finished prerequisites of target file 'GNUmakefile'.
 Must remake target 'GNUmakefile'.
 Failed to remake target file 'GNUmakefile'.
 Considering target file 'makefile'.
  File 'makefile' does not exist.
  Looking for an implicit rule for 'makefile'.
  No implicit rule found for 'makefile'.
  Finished prerequisites of target file 'makefile'.
 Must remake target 'makefile'.
 Failed to remake target file 'makefile'.
 Considering target file 'Makefile'.
  File 'Makefile' does not exist.
  Looking for an implicit rule for 'Makefile'.
  No implicit rule found for 'Makefile'.
  Finished prerequisites of target file 'Makefile'.
 Must remake target 'Makefile'.
 Failed to remake target file 'Makefile'.
make: *** No targets specified and no makefile found.  Stop.
```
---

I have two different workareas and the same font looks very different in gvim/emacs launched from these two workareas. Let's call the workareas good and bad. Here's what the font looks like in gvim and emacs in both of these workareas:

gvim good:
![iosevka_gvim_good](https://user-images.githubusercontent.com/1559554/46764706-6c5f1280-cc9a-11e8-86a7-c5bdc57afe32.png)

gvim bad:
![iosevka_gvim_bad](https://user-images.githubusercontent.com/1559554/46765223-b5639680-cc9b-11e8-90ec-5958b2492f25.png)

As you can see, it's the same font in both cases (guifont=Iosevka Medium 9) but in the bad case it looks squashed. This difference is even worse in emacs:

emacs good:
![iosevka_emacs_good](https://user-images.githubusercontent.com/1559554/46765209-ae3c8880-cc9b-11e8-911d-1d97ea710c4e.png)

emacs bad:
![iosevka_emacs_bad](https://user-images.githubusercontent.com/1559554/46765229-bb597780-cc9b-11e8-9c0a-8974622ae4ca.png)

In the bad case, the font looks horribly stretched. This is how I set my fonts in emacs:

```elisp
(defun my/set-font-if-exists (font)
    " Check if FONT exists and set if it does"
    (when (and (display-graphic-p)(x-list-fonts font))
      (set-face-attribute 'default        nil :font font)
      (set-face-attribute 'variable-pitch nil :font font)
      (set-face-attribute 'fixed-pitch    nil :font font)
      t))  ; This is required so that we can use this function in a cond block below

  (defun my/select-and-set-font ()
    " Select the font based on OS, hostname etc."
    (cond ((eq system-type 'gnu/linux) (my/set-font-if-exists "Iosevka-9"))
          ((eq system-type 'windows-nt) (my/set-font-if-exists "Iosevka-9"))))

  (if (daemonp)
      (add-hook 'after-make-frame-functions
                (lambda (frame)
                  (select-frame frame)
                  (my/select-and-set-font)))
    (my/select-and-set-font))
```

Can you please help me figure out the reason behind this discrepancy?

**Comment by be5invis** [comment]
It looks like more a fontconfig issue. Have you tried Iosevka-term?

**Comment by stereokai** [comment]
Interesting

**Comment by stereokai** [comment]
@kshenoy?

**Comment by kshenoy** [comment]
Sorry guys, forgot to check back in; things have been crazy at work. There has also been an environment update making it difficult to reproduce the issue at my end.

I agree that it could be a fontconfig issue as I see a very slight difference between terminal vim and gvim even when both use the same font eg.

![Iosevka](https://user-images.githubusercontent.com/1559554/69437463-96d62880-0d00-11ea-8572-f614159ccf82.png)

I see similar differences when using emacs with and without a daemon. However, both are small enough and I think we can close the issue (technically it's already closed but oh well)
