### ISSUE TITLE
Hide parens and semicolons

### ISSUE THREAD

**Issue by streamich** [be5invis/Iosevka#303]
Feature request: would be nice if there was an option to make parens and semi-colons semi transparent. This way code in some languages would look more functional.

For example, take a look at this JavaScript:

```js
const fib = (n) => n > 2 ? fib(n - 1) + fib(n - 2) : 1;
```

With semi-transparent characters it would look like:

```
const fib =  n  => n > 2 ? fib n - 1  + fib n - 2  : 1 
```

**Comment by be5invis** [comment]
OpenType does not support transparency.
Closed.

**Comment by streamich** [comment]
@be5invis Maybe those symbols could be reduced in size, to appear as semi transparent?
