### ISSUE TITLE
Braille patterns are flipped vertically in 2.0.1

### ISSUE THREAD

**Issue by thepheer** [be5invis/Iosevka#304]
* Your font version:
2.0.1
* Your font variant:
01-iosevka-2.0.1
* Your operating system:
Windows 10, Chrome 70, Firefox 60
* Your application using Iosevka:
Webfonts

`⠁` is displayed as `⡀`, `⠛` as `⣤`, etc. 
The issue appears only when using latest version of the font in web.
So it can be witnessed here: http://typeof.net/Iosevka/specimen.html

**Comment by be5invis** [comment]
I did not notice this...
https://github.com/be5invis/Iosevka/commit/87079903bed3f19e1b9ee155998322b4f4af5cfc#diff-40d1f8cc0be75dd43a418c06c81a0b35L16
In @sprang's original code the offsetY is **negative**.

**Comment by be5invis** [comment]
I will fix that in 2.0.2.

**Comment by thepheer** [comment]
Whoa, that was fast! 👍

**Comment by thepheer** [comment]
Btw 2.0.2 still slightly differs from 2.0.0. I was able to achieve perfect dots alignment at 11px/12px (font size/line height), now it seems to be at 12px/12px. So not really an issue and it seems the change is intended, but I still wanted to make sure you're also aware of this.

http://jsfiddle.net/kns1c6eL/ (worth looking at: 7/8, 8/8, 11/12, 12/12, also near 18, 24, 36, etc.)

**Comment by be5invis** [comment]
@thepheer 
It is related with hinting which is not a simple thing. Currently I just used TTFA.
You can try the unhinted version, but would be less clear for letters.

**Comment by thepheer** [comment]
Yeah, unhinted 2.0.2 looks better (and more correct I guess) than unhinted 2.0.0 indeed. As I said, I'm happy even with the hinted ones, just wanted to make sure it's not some another subtle math error.
