### ISSUE TITLE
[Feature Request] Armenian and Georgian glyphs

### ISSUE THREAD

**Issue by gusbemacbe** [be5invis/Iosevka#306]
* Your font version: latest
* Your font variant: ss08, cv02, cv04, XV00
* Your operating system (name and version): Manjaro Linux 18.0
* Your application using Iosevka: Any text editor - Atom, Emacs, Kate, Neovim, Sublime Text and VSCode, and any terminal. 

It is cool that you are not only creator of Iosevka, of vscode-custom-css too.

Actually it is not an issue. It is a feature request.

Is it possible that you will add Armenian and Georgian glyphs in the future?

**Comment by be5invis** [comment]
I have no such plan in recent future.

**Comment by gusbemacbe** [comment]
Too bad, thank you, as it is open source, I will try to make Iosevka-like glyphs and to create pull request.

**Comment by be5invis** [comment]
@gusbemacbe Actually I do not think I can design those languages well, since I have zero background on them.

**Comment by be5invis** [comment]
@gusbemacbe If you want to create PRs, you can just use vector graphs, instead of writing code like me...

**Comment by gusbemacbe** [comment]
Hello @be5invis 

Georgian Unicode:
[Goegrian Mkhreduli Unicode table](https://en.wikipedia.org/wiki/Georgian_scripts#Modern_Georgian_alphabet)

Similar to Iosevka, you can check:

* [BPG Tech](https://bpgfonts.wordpress.com/2018/12/16/bpg-tech-11-1/)
* [BPG Square](https://bpgfonts.wordpress.com/2018/10/18/bpg-square-37-cond/)
* [BPG 111](https://bpgfonts.wordpress.com/2018/06/16/bpg-111/)

> If you want to create PRs, you can just use vector graphs, instead of writing code like me...

OK, can I send in SVG?
