### ISSUE TITLE
How to create rasterized version of font?

### ISSUE THREAD

**Issue by seletskiy** [be5invis/Iosevka#308]
Hey, @be5invis.

Thanks for great font.

I've noticed, that you automatically generate an images with font samples that you put in the README.md.

I have similar task, but I need to generate PNG image with all glyphs in the font on a transparent background.

Given, that you already done it, can you point me in the direction about:

a) how to retrieve all glyph codes from font,
b) how to render them into rectangular PNG image?

**Comment by be5invis** [comment]
Well I just used Electron to take snapshots.
To rasterize, ImageMagick is a good option (though not sure whether it supports shaping).

**Comment by seletskiy** [comment]
@be5invis: I've tried ImageMagick, but unfortunately it produces very ugly results. It seems it doesn't support font hinting.

Any ideas on how to retrieve list of glyphs available in font to produce HTML programmatically?

Regarding Electron: can you share relevant commands?

**Comment by be5invis** [comment]
There are some code under `snapshot/`
