### ISSUE TITLE
specimen.html: Chrome displays oblique whether I select "Oblique" or "Italic"

### ISSUE THREAD

**Issue by cben** [be5invis/Iosevka#309]
* Your font version: whatever http://typeof.net/Iosevka/specimen.html shows
* Your font variant: italic, italic slab
* Your operating system (name and version): Linux (Fedora 29)
* Your application using Iosevka: Google Chrome 70.0.3538.102 

I wanted to understand the difference between italic and oblique, so went to 
http://typeof.net/Iosevka/specimen.html, but in my Chrome they render the same:
![iosevka-slab-italic](https://user-images.githubusercontent.com/273688/50560860-8d6d5780-0d0d-11e9-8fc9-80ed9021728b.png)
![iosevka-slab-oblique](https://user-images.githubusercontent.com/273688/50560861-8d6d5780-0d0d-11e9-9823-8b912cd9dc38.png)

Chrome dev tools "Rendered Fonts" says it's using Iosevka Slab Oblique in both cases.
(same for non-slab Italic vs Oblique — both render using Iosevka Oblique)

CSS for `.italic` vs `.oblique` classes does say `font-style: italic;` vs `font-style: oblique;` but under computed properties both show font-style italic.

---

Firefox does show Italic specimen:
![captura de pantalla de 2018-12-31 15-14-32](https://user-images.githubusercontent.com/273688/50560999-01f4c600-0d0f-11e9-91ed-35b1909dab29.png)

**Comment by be5invis** [comment]
Are there anything shown in the F12?

**Comment by cben** [comment]
as I wrote above:
> Chrome dev tools "Rendered Fonts" says it's using Iosevka Slab Oblique in both cases.
(same for non-slab Italic vs Oblique — both render using Iosevka Oblique)
>
> CSS for .italic vs .oblique classes does say font-style: italic; vs font-style: oblique; but under computed properties both show font-style italic.

**Comment by be5invis** [comment]
I mean the console.log window. Are there any error (like format incorrectness or download failure)?


________________________________
收件人: Beni Cherniavsky-Paskin <notifications@github.com>
发送时间: 星期一, 十二月 31, 2018 23:53
收件人: be5invis/Iosevka
抄送: Belleve Invis; Comment
主题: Re: [be5invis/Iosevka] specimen.html: Chrome displays oblique whether I select "Oblique" or "Italic" (#309)


as I wrote above:

Chrome dev tools "Rendered Fonts" says it's using Iosevka Slab Oblique in both cases.
(same for non-slab Italic vs Oblique ― both render using Iosevka Oblique)

CSS for .italic vs .oblique classes does say font-style: italic; vs font-style: oblique; but under computed properties both show font-style italic.

―

**Comment by cben** [comment]
## Firefox for comparison:
console:
```
Ready to show up. specimen.js:576:3 
```

-----

Network shows it's loading both regular, `-oblique` and `-italic` files (and each name in the dropdown gets re-styled independently as they come in):
![captura de pantalla de 2019-01-01 10-31-52](https://user-images.githubusercontent.com/273688/50571335-7895d000-0db0-11e9-93df-7e65a9126148.png)

**Comment by cben** [comment]
I'd guess the core problem is Chrome just doesn't distinguish font-style: italic vs oblique in CSS?  At least for `@font-face` web fonts?  Or possibly it doesn't understand the 2 `@font-face` declarations as distinct?

https://developer.mozilla.org/en-US/docs/Web/CSS/font-style:
- "If no italic version of the face is available, one classified as oblique is used instead"
  and vice versa:
- "If no oblique version of the face is available, one classified as italic is used instead"
- compat table doesn't mention this problem for chrome, it only says "* Before Firefox 44, oblique was not distinguished from italic."

no compat details in Caniuse (just says font-style has basically universal support).

no relevant compat details in https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face.

**Comment by be5invis** [comment]
I inspected in Edge and it does not have such problem too. Italic and Oblique are correctly distinguished.
I think it may be a chromium issue?

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/50585958-68feb000-0eb2-11e9-9764-2672b940d33b.png)

**Comment by be5invis** [comment]
I filed https://bugs.chromium.org/p/chromium/issues/detail?id=918475, and it should be a regression (this page was developed using Chrome).

**Comment by be5invis** [comment]
@cben 
It is really a Chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=918475#c1
