### ISSUE TITLE
U+027B has the hook in the wrong place

### ISSUE THREAD

**Issue by MathSquared** [be5invis/Iosevka#310]
* Your font version: 2.0.2 (Arch package)
* Your font variant: default
* Your operating system (name and version): Arch Linux, rolling release
* Your application using Iosevka: gVim
---

The glyph U+027B ɻ LATIN SMALL LETTER TURNED R WITH HOOK should be rendered with a rightward-facing hook at the bottom-right, as it is depicted in this image from the [Unicode 11.0 chart](http://www.unicode.org/charts/PDF/U0250.pdf): ![U+027B as it is depicted in the Unicode chart, with a rightward-curling hook extending from the bottom end of the stem](https://user-images.githubusercontent.com/7842810/50577053-a563da80-0de4-11e9-9eb7-364fab56030b.png).

Instead, Iosevka shows a leftward-facing hook at the top-right: ![U+027B incorrectly rendered in Iosevka](https://user-images.githubusercontent.com/7842810/50577068-f673ce80-0de4-11e9-9a42-12c12cb4142d.png).

This character is in the IPA Extensions block of Unicode, represents a voiced retroflex flap in the International Phonetic Alphabet, and thus has a very specifically prescribed appearance. That appearance is reflected in the IPA chart, the Unicode chart, and most other fonts. The shape of U+027B in Iosevka should be changed to match.

**Comment by be5invis** [comment]
Fixed in Dev. Closed
