### ISSUE TITLE
Scaling issue

### ISSUE THREAD

**Issue by Keoma-github** [be5invis/Iosevka#315]
* Your font version: 2.10
* Your font variant: Iosevka Regular
* Your operating system (name and version): Linux 4.14.83-gentoo
* Your application using Iosevka: Both gVim and Eclipse.

![ft](https://user-images.githubusercontent.com/47359020/52283192-57517200-2962-11e9-9122-e04f65e58589.png)

As you can see in the screenshot, the horizontal lines in the f and t don't line up. I have this issue with various font sizes, starting at 11.

**Comment by Keoma-github** [comment]
I just did. Same issue.

**Comment by be5invis** [comment]
Or you can try to turn off “autohinting” on your system.

**Comment by Keoma-github** [comment]
Tried that too just now. The issue persists.

**Comment by be5invis** [comment]
No idea what happened, but should be related with hinting. AFAIK Freetype have “autohinting” or “light hinting” that would round strokes so small differences of stroke position would be exaggerated.
Linux’ text display environments varies too much and everyone can have their own configuration...

**Comment by Keoma-github** [comment]
Thanks for the hint about hinting. I'm fiddling around with the configuration right now. No success yet, though.

**Comment by Keoma-github** [comment]
With no hinting it looks like this, which is not any better:

![unhinted](https://user-images.githubusercontent.com/47359020/52324747-d71f2100-29e2-11e9-84d5-967e36c492bd.png)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/52836083-2a504c80-3124-11e9-9d5c-5e3cf624873e.png)
They are intentionally not at the same height: the `f`'s bar is lower to balance the hook above it.
I added two parameters in `parameters.toml` to control it and you can set it if needed.
Closed.

**Comment by Keoma-github** [comment]
Could you maybe make a character variant for that?
