### ISSUE TITLE
The bottom of letter W looks thin in heavy weights

### ISSUE THREAD

**Issue by 01010101lzy** [be5invis/Iosevka#317]
* Your font version: 2.1.0
* Your font variant: Default
* Your operating system (name and version): Windows 10 18334
* Your application using Iosevka: Affinity Designer

It might be a bit subjective, but the bottom bits of upper case letter `W` looks too thin in heavy weights, and makes it inconsistent with other letters. The image shown below is Iosevka 2.1.0, Default variant, Heavy weight.

![default](https://user-images.githubusercontent.com/10259119/52908721-4dab0100-32b6-11e9-87f8-6f85ceb56ae0.png)

I wonder if the bottom of `W` could be widened a little bit as shown below, pretty much like what's done with the letter `M`:

![default](https://user-images.githubusercontent.com/10259119/52908792-a8912800-32b7-11e9-8517-f0d80715cff7.png)

![default](https://user-images.githubusercontent.com/10259119/52908760-17ba4c80-32b7-11e9-8dfe-2eee1da4ede0.png)

![default](https://user-images.githubusercontent.com/10259119/52908776-4e906280-32b7-11e9-8425-44bf862d45a7.png)

The same issue is also present in lower case letter `w`:

![default](https://user-images.githubusercontent.com/10259119/52908822-3c62f400-32b8-11e9-9edd-dde912ec7a64.png)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/53332772-18925480-392f-11e9-8edf-18d88cbd6ec6.png)
This is now in `dev`. Closed.

**Comment by 01010101lzy** [comment]
Thanks for fixing!

**Comment by Yevgnen** [comment]
The `W`s looks a bit compressed, makes the color of the text a bit unbalanced. For example,

Left: `Iosevka Term SS04`, right:`Inconsolata`
<img width="1280" alt="Screen Shot 2019-05-24 at 16 19 29" src="https://user-images.githubusercontent.com/16749790/58313337-e87c2400-7e3f-11e9-86d4-d5c89125a46b.png">
