### ISSUE TITLE
关于全角字符

### ISSUE THREAD

**Issue by yutuo** [be5invis/Iosevka#318]
你好，最近想自己编译一个Sarasa Gothic版本，使用的是Iosevka_cc，但是还是有一些全角字符显示为半角，比如：
※
≤
≥

请问，应该如何设置或者修改代码才能把这些字符编译成全角。
谢谢

**Comment by be5invis** [comment]
`parameters.toml`, section `xx-cc.appends`, add entries into `fullwidth_codes`, list all your Unicode code points into it.

**Comment by be5invis** [comment]
PRs are welcome.
