### ISSUE TITLE
[Feature request] Iosevka in bitmap format

### ISSUE THREAD

**Issue by Izorkin** [be5invis/Iosevka#324]
Is it possible to create a bitmap font like Terminus font? To keep the lines clear without using hinting.

**Comment by be5invis** [comment]
I don't think it is a simple task. Iosevka is made entirely using algebraic curves.

**Comment by Izorkin** [comment]
Is it also hard to manually?

**Comment by be5invis** [comment]
There are around 4,000 glyphs.

**Comment by alexeyten** [comment]
There are number of ttf to bitmap tools as well as font editors (like font forge) that are capable to create bitmap fonts. But I guess you’ll have to “hint” result manually in any case

**Comment by Izorkin** [comment]
I generally need it to use with SSH console (putty). I need better readability when I use small font sizes."

**Comment by AnrDaemon** [comment]
The projects like [Anti-Grain Geometry Library](https://sourceforge.net/projects/agg/) exist that may help rendering the glyphs.
