### ISSUE TITLE
Add built termlig variant to releases

### ISSUE THREAD

**Issue by Trollwut** [be5invis/Iosevka#325]
* Your font version: 2.2.0
* Your font variant: unfortunately not termlig
* Your operating system (name and version): Arch / Manjaro
* Your application using Iosevka: terminals in general

Is it possible to get already built files of the `termlig` variant into releases?

I'd like to have a self-updating AUR package for this, as the other variants have it, too. :)

*obligatory praise of this awesome font!*

**Comment by Trollwut** [comment]
Still keen on seeing this. :)

**Comment by Trollwut** [comment]
Hi bot!

**Comment by Trollwut** [comment]
May I get an answer to the problem?

Or is a termlig variant already shipped and I missed it?

**Comment by be5invis** [comment]
Next release will have it.

________________________________
发件人: Trollwut <notifications@github.com>
发送时间: Friday, October 11, 2019 12:48:35 AM
收件人: be5invis/Iosevka <Iosevka@noreply.github.com>
抄送: Belleve Invis <be5invis@outlook.com>; State change <state_change@noreply.github.com>
主题: Re: [be5invis/Iosevka] Add built termlig variant to releases (#325)


May I get an answer to the problem?

Or is a termlig variant already shipped and I missed it?

―

**Comment by Trollwut** [comment]
Ooh these are good news! Thanks for your great work! :)

**Comment by Trollwut** [comment]
So there has been new releases, but I can't see a TermLig variant for me.

Is this still worked on? Or any way I can test I don't have a TermLig variant installed?

**Comment by be5invis** [comment]
@Trollwut Next major release (3.0)
This is a breaking change so I'd like to defer.

**Comment by Trollwut** [comment]
Ah ok, thanks for the clarification!

Keen on seeing termlig. Thanks for all your work!
