### ISSUE TITLE
there is no  character U+EE01

### ISSUE THREAD

**Issue by hingbong** [be5invis/Iosevka#329]
in my use,i found a character lack which is U+EE01,which is a colon

**Comment by alexeyten** [comment]
https://www.fileformat.info/info/unicode/char/ee01/index.htm

> U+EE01 is not a valid unicode character.

**Comment by be5invis** [comment]
Closed as by design.
U+EE01 is a PUA character, and is not  Iosevka's goal.
(Currently the only “goal” PUA characters are Powerline.)
