### ISSUE TITLE
Support for ligatures

### ISSUE THREAD

**Issue by IceMan81** [be5invis/Iosevka#33]
Are you planning to add support for ligatures similar to PragmataPro?

**Comment by be5invis** [comment]
Considering the different denotion of symbols, I do not think supporting ligatures is a good idea... Just think about `/=` in JavaScript and Haskell.

**Comment by IceMan81** [comment]
I don't think I know what /= deontes in JavaScript, but I like the way PragmataPro has done it. I find that it works for me in Java as well.

**Comment by be5invis** [comment]
In JavaScript, `a /= b` means `a = a / b`, which is significantly different from its Haskell meaning. I am curious about if editors can provide support for, well `locl` features for programming languages.

**Comment by IceMan81** [comment]
Sorry, so stupid of me not to recognize `/=`.

**Comment by dbordak** [comment]
What about making a variant with these ligatures? I'm not a Haskell programmer, but most of the existing ligature fonts I've seen are variants of existing fonts anyway.

**Comment by be5invis** [comment]
@dbordak Well you can actually make a variant and perform features like

```fea
feature liga {
    sub ampersand ampersand by ampersand_ampersand;
    sub hyphen greater by arrowright.ligature;
    //......
} liga;
```
