### ISSUE TITLE
Can't find specimen.html to fix typo

### ISSUE THREAD

**Issue by vikdotdev** [be5invis/Iosevka#331]
There's a small typo on `https://typeof.net/Iosevka/specimen.html` at the start of the page in langs class - Ukrainian is spelled Ukranian which I'm pretty sure is a typo.

I'd be glad to fix and submit this but `specimen.html` is nowhere to be found in this repo, although `index.html` is present. Where can I find `specimen.html`?

**Comment by chelovechishko** [comment]
Branch `gh-pages`

https://github.com/be5invis/Iosevka/blob/gh-pages/specimen.js#L269

**Comment by vikdotdev** [comment]
Whoops, silly me 😅. Closing.
