### ISSUE TITLE
Better design for arrow

### ISSUE THREAD

**Issue by ilajosmanov** [be5invis/Iosevka#333]
* Your font version: (Release or git, version)
2.2.1
* Your font variant:
Regular
* Your operating system (name and version):
Linux
* Your application using Iosevka: (some Java applications may have problem in showing Iosevka properly. It is a bug in Java's GUI components.)
VsCode

I think could create a better design for the arrow. Because of the current font have mistake line height inside `=` and `>`.

Look example via your font and Pragmata Pro

![Ioveska](https://user-images.githubusercontent.com/18512404/58543935-0fa07000-8209-11e9-9639-e5273aecd6fe.png)
![Pragmata Pro](https://user-images.githubusercontent.com/18512404/58543938-116a3380-8209-11e9-85fa-ae15a7fa5a0d.png)

Your font is awesome, thanks! But the arrow on the top should be improved. It's my opinion.
Again, thanks for your job. It's awesome font for coding

**Comment by cata0309** [comment]
Bad bot, no closing

**Comment by rileyinman** [comment]
I think this issue should be reopened, the design in still the same and the suggested one is much more readable

**Comment by ilajosmanov** [comment]
Why?

**Comment by rileyinman** [comment]
@ilajosmanov When I commented the bot removed the stale label, that's what I was talking about 😊

**Comment by Gang-Yang** [comment]
Another problem of current arrows is the bad hinting.
![capture](https://user-images.githubusercontent.com/29451722/68844094-3180a700-0704-11ea-94e2-153df6e45c8b.JPG)
The ttfautohint tool performs not well on these characters when the font size is small. Hope to re-design the arrows. Thanks.

**Comment by ilajosmanov** [comment]
@Gang-Yang the same problem for me

**Comment by shytikov** [comment]
Check my bug: https://github.com/be5invis/Iosevka/issues/349

Recommendation to use `unhinted` font variation solved this issue for me.

**Comment by cata0309** [comment]
> Check my bug: #349
> 
> Recommendation to use `unhinted` font variation solved this issue for me.

So how do I use `unhinted` font variation ? Where can I found it ? Is it a setting I should enable/disable ?

**Comment by shytikov** [comment]
You can check files in release package. It's one of font variations. File will have `unhinted` word in it's name.

**Comment by cata0309** [comment]
Thank you @shytikov

**Comment by cata0309** [comment]
I used the unhinted version but it didn't help much.
![image](https://user-images.githubusercontent.com/35623921/68880975-f5a20d80-0714-11ea-8dc5-f1496ca4a9fb.png)

Look at the arrow

**Comment by shytikov** [comment]
I understand... It's not ideal, but already at least not as ugly as it was before...

**Comment by cata0309** [comment]
Actually I don't see any difference between hinted and unhinted variations.

**Comment by shytikov** [comment]
Have you restarted your system?

**Comment by cata0309** [comment]
Yes, multiple times, and the results are the same, bad rendering of arrow ligature

**Comment by shytikov** [comment]
Let me reach my laptop and I will show you my picture. Maybe it's indeed very important issue which needs to be addressed NOW.

**Comment by shytikov** [comment]
Sorry for delay, here is now it looks for me:
![image](https://user-images.githubusercontent.com/1185905/68933090-3ab95480-0794-11ea-9d6c-585ed5239236.png)
![image](https://user-images.githubusercontent.com/1185905/68932967-faf26d00-0793-11ea-88ae-f8a0a25969c5.png)
![image](https://user-images.githubusercontent.com/1185905/68933037-1b222c00-0794-11ea-9614-d04c0c875604.png)
Not the best, comparing to `Pragmata Pro`, but OKish...

**Comment by cata0309** [comment]
I noticed too the difference between `Pragmata Pro` arrow and `Iosevka` but I really don't know why `Iosevka` behaves like that. I tried even changing my antialising level and hinting on my global settings(for fu system) and rebooted some times but nothing changed. Not even the `unhinted` variant could do any better.
No problem for late reply

**Comment by be5invis** [comment]
@cata0309 @shytikov 
How Iosevka implemented ligation is that, for example for `=` `>`, it will replace the `=` into the arrow bar and `>` into the arrow head. I will not change this implementation since it is better for building more complex ligations.
About rounding, the `dev` branch reduced the bar distance so it would improve at small size (I verified 12ppe).

**Comment by cata0309** [comment]
Do you mind building the `dev` branch for me ? (I do not have a beast of computer and the build process would take a lot of time) Only if you want

**Comment by cata0309** [comment]
> Sorry for delay, here is now it looks for me:
> ![image](https://user-images.githubusercontent.com/1185905/68933090-3ab95480-0794-11ea-9d6c-585ed5239236.png)
> ![image](https://user-images.githubusercontent.com/1185905/68932967-faf26d00-0793-11ea-88ae-f8a0a25969c5.png)
> ![image](https://user-images.githubusercontent.com/1185905/68933037-1b222c00-0794-11ea-9614-d04c0c875604.png)
> Not the best, comparing to `Pragmata Pro`, but OKish... But I care mostly about symmetric on horizontal axis. Hinted option was unbearably ugly.

Where is the screenshot from? What environment ? Maybe is the app's fault

**Comment by shytikov** [comment]
It's VSCode on Windows 10, color scheme is [Nord](https://www.nordtheme.com/).

**Comment by be5invis** [comment]
[iosevka-3.0-alpha.0.zip](https://github.com/be5invis/Iosevka/files/3853859/iosevka-3.0-alpha.0.zip)
@cata0309 @shytikov You can try this

**Comment by cata0309** [comment]
![image](https://user-images.githubusercontent.com/35623921/69004634-5e5cd600-091f-11ea-88c9-12591f40fdf5.png)
A little bit better than the normal version

**Comment by be5invis** [comment]
@cata0309 
I may draw some special arrowheads in 3.0 for `=>` case. That is expected to look better.

**Comment by ilajosmanov** [comment]
@be5invis thanks)

**Comment by Fihtangolz** [comment]
Can we are just borrow arrow from Pragmata Pro?

**Comment by be5invis** [comment]
@Fihtangolz Pragmata's arrows are full-width by default, which is not a good choice for Iosevka (Well Iosevka's arrows have both single-width and double-width).
![image](https://user-images.githubusercontent.com/240091/74619741-6af1f580-50eb-11ea-9e8e-b53be5485a68.png)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/74621967-e8b9ff00-50f3-11ea-949d-bcccc60f150e.png)
![image](https://user-images.githubusercontent.com/240091/74622002-0edf9f00-50f4-11ea-89c7-953f8f87b7ba.png)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/74622259-ff148a80-50f4-11ea-8de7-da2bb31addbd.png)

![image](https://user-images.githubusercontent.com/240091/74622250-f91ea980-50f4-11ea-9e51-df8410bb6c21.png)

**Comment by lshoravi** [comment]
Looks fantastic, looking forward to it!
