### ISSUE TITLE
Feature request: turnstile |- and doc comment (** support

### ISSUE THREAD

**Issue by cpitclaudel** [be5invis/Iosevka#335]
* Your font version: 2.2.1
* Your font variant: XV00 (Coq)
* Your operating system (name and version): GNU/Linux Mint 19.1 Tessa
* Your application using Iosevka: Source cod edisplay in Firefox & Chromium

Thanks for your hard work on Iosevka! The Coq variant is especially nice. I'd like to suggest three additions:

- Turnstile: `|-`, displayed as ⊢
- Alternative: `||`, displayed as ‖
- `(**` and `**)`, displayed with centered stars; it's common in Coq to use `(**` to indicate documentation comments (additionally, lines of `(*****************)` are used as delimiters and to make comment boxes).

I think the last point is also applicable to OCaml; see e.g. https://github.com/ocaml/ocaml/blob/trunk/lambda/lambda.mli

Thanks again for your work.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/61671365-2ceb3b00-ac9c-11e9-8665-00744b5a1a1b.png)

About `||`: do we really need this? You may break long `|||||||||||` series.

**Comment by cpitclaudel** [comment]
Neat! Thanks a lot (I'm not sure if I'm reading the screenshot right; I think ⊢ is typically rendered without a gap)

I'm not sure about `||`, and it's always better to be conservative, especially since users can define notations with more than two pipes.  Let's do without it.

Thanks again!

**Comment by be5invis** [comment]
@cpitclaudel 
I really dislike making a ligature that _looks identical_ to another symbol, espeically for languages like Coq which already supports unicode operators. Leaving a small gap might be helpful for distinction.

**Comment by cpitclaudel** [comment]
Quite reasonable. I'm sold ^^

**Comment by be5invis** [comment]
Close as resolved for now. Feel free to reopen or open another issue with additional requests 🙂

**Comment by cpitclaudel** [comment]
Thanks a lot!
