### ISSUE TITLE
A glyph isn't rendered right at 12pt, 30pt and other bigger sizes

### ISSUE THREAD

**Issue by cpkio** [be5invis/Iosevka#338]
* Your font version: Latest release 
* Your font variant: Non-slabs are affected
* Your operating system (name and version): Windows 7
* Your application using Iosevka: Sublime, BabelMap

---

The image shows that a lower bar of cyrillic letter `ш` renders wrong on 12pt, 30pt and some bigger font sizes.

![iosevka](https://i.ibb.co/2YQLXrv/2019-06-13-100155.jpg)

**Comment by be5invis** [comment]
A minor change by adding a Boolean can fix this
![image](https://user-images.githubusercontent.com/240091/59412317-fef80a00-8d71-11e9-91b9-41ff98defa54.png)
