### ISSUE TITLE
Iosevka not considered monospace by Freetype

### ISSUE THREAD

**Issue by gber** [be5invis/Iosevka#34]
For some reason fontconfig/Freetype consider Iosevka spacing as "dual-width" rather than "monospace":

    $ fc-list -v Iosevka | grep spacing
            spacing: 90(i)(s)

I don't know where this is coming from though, there are no fontconfig rules applying here and the "bProportion" PANOSE value seems correctly set to 9. This just makes Iosevka unusable for terminal emulators.

**Comment by be5invis** [comment]
Is is caused by the double-width characters and Latin ligatures in it? They are designed to provide CJK compatibility.
What's the result if you manually delete them?

**Comment by be5invis** [comment]
@gber I have checked the source of libfontconfig, and it is really caused by full-width characters included within it. In the next release I will separate Iosevka into three variants:

* Iosevka — Single-width only.
* Variant Iosevka CJK — Iosevka and full-width characters.
* IosevkaCC — Contains full-width characters and enwiden symbols.

**Comment by gber** [comment]
Yep, I tried with only the Latin Extended subset and that is indeed then recognized as monospace.

**Comment by be5invis** [comment]
@gber Could you please try to build the newest snapshot in `master` and checkout whether the ttf files in `build` is recognized as monospaced?

**Comment by be5invis** [comment]
![image](https://cloud.githubusercontent.com/assets/240091/11516243/115a66f0-98bd-11e5-8b10-dddded311b2c.png)
This is the result from my friend's test.

**Comment by gber** [comment]
I can't get it to build and don't know enough about node (might be the outdated distro-provided fontforge version). Could you upload the built font somewhere?

**Comment by gber** [comment]
The above looks right, 100 means mono, so it should be OK.

**Comment by be5invis** [comment]
@gber http://pan.baidu.com/s/1i38SZ5r
You can download and test it.

**Comment by gber** [comment]
Thanks, fontconfig/Freetype indeed now considers it monospace and it is also rendered correctly via Xft. Awesome, thanks for the quick response!

**Comment by be5invis** [comment]
@gber Okay, the fix will be published in the next release. Closed.
