### ISSUE TITLE
Symbols and characters cut-off from top when using 'leading-1000'

### ISSUE THREAD

**Issue by tomas-chrastina** [be5invis/Iosevka#343]
* Your font version: git [2c01916](https://github.com/be5invis/Iosevka/commit/2c01916de190676882212f73dc9b687e2eeb334b)
* Your font variant: Custom
* Your operating system (name and version): Windows 7 x64
* Your application using Iosevka: Notepad++, ...
* Your Node.js version: 12.7.0
* Your _otfcc_ version: 0.9.6
* Your _TTFautohint_ version: 1.8.3
* Your `private-build-plans.toml`:
<details>

```
[buildPlans.my-iosevka-1000]
family  =   "myIosevka 1000"
design  =   [   "term",
                "expanded",
                "leading-1000",
                "cv01",     #   a
                "cv03",     #   i
                "cv07",     #   l
                "cv11",     #   g
                "cv13",     #   0
                "cv17",     #   ~
                "cv21",     #   _
                "cv25",     #   m
                "cv29",     #   ^
                "cv32",     #   @
                "cv36",     #   {
                "cv39",     #   $
                "cv40",     #   t
                "cv42",     #   Q
                "cv45",     #   #
                "cv47",     #   3
                "cv49",     #   y
                "cv50",     #   1
                "cv52",     #   f
                "cv61",     #   *
                "cv63"      #   %
            ]
```
</details>

---

When I have tried to build custom set with `leading-1000`, symbols are cut-off all the time. And at some sizes also characters are cut-off from top. It is noticeble at size 9 (I'm using in code editors), and also at 6 (kind of doesn't matter to me, just so you know).

`[(< UpPeR cHaRaCtErS aRe CuT-oFf ! >)]`

![Iosevka](https://user-images.githubusercontent.com/14962885/61982874-699d9600-affe-11e9-9795-6d7c5ab44a5b.png)

I have also tried to use settings mentioned here -> [comment](https://github.com/be5invis/Iosevka/issues/295#issuecomment-473463781)

Modified parameters `parameters.toml`:
```
cap = 700
xheight = 510
ideoMid  = 350
symbolMid = 300
parenSize = 900
operSize = 700
tackSize = 700
```

But with this settings my build has been stucked for hours while building `heavyitalic` and `heavyoblique`. So, no much luck.

**Update:**
I was able to build at least basic font set (bold, bolditalic, italic, regular) with customized parameters. Still this way there's problem with font size 9.

**Comment by be5invis** [comment]
Clipping is caused by "Win" metrics.
I added a config `winMetricPad` in the latest "dev" branch to pad Win metrics only while keeping Typo metrics correct. However there **are** legacy application will ignore the Typo metrics and use Win metrics only so in these applications the line  height would be larger.

**Comment by be5invis** [comment]
Styles are `win-metric-pad-0`, `win-metric-pad-50`, ..., `win-metric-pad-300`

**Comment by tomas-chrastina** [comment]
Thank you very much for very fast update.

I have tried dev release with some combinations of parameter `win-metric-pad`, but unfortunately not came to working ideal solution. I have still had some problems on smaller sizes.

But come to the another working solution. But only by using customized parameters (from mentioned [comment](https://github.com/be5invis/Iosevka/issues/295#issuecomment-473463781)).

But to make it work also on size 9 and in general, some small additional adjustment need to be done.

**A. Decreasing of parameter `parenSize` to `825`.**

So final custom `parameters.toml` settings are:

```
cap         =   700  # GitHub #295
xheight     =   510  # GitHub #295
ideoMid     =   350  # GitHub #295
symbolMid   =   300  # GitHub #295
parenSize   =   825  # my
operSize    =   700  # GitHub #295
tackSize    =   700  # GitHub #295
```

This way it is working even with `leading-1000`.

**B. By using higher custom `leading`** while letting parameter `parenSize` at `900`.

For this purpose I put additional precision for `leading` value (to `parameters.toml`):

```
[leading-1050]
leading = 1050
[leading-1100]
leading = 1100
[leading-1150]
leading = 1150
[leading-1200]
leading = 1200
```

Then starting at `leading-1050` is looks OK. And after few tests a bit higher leading than 1000 works better for me.
