### ISSUE TITLE
Question : mapping of ligatures

### ISSUE THREAD

**Issue by gagbo** [be5invis/Iosevka#345]
Hello,

I just have a quick question. In order to use ligatures in emacs we have to go through some hoops (basically defining an association table between strings and glyphs).

# Is there a location where I can see where ligature glyphs are located ?

I assumed they were in the private zone (as suggested in [doom emacs config](https://github.com/hlissner/doom-emacs/blob/straight/modules/ui/pretty-code/%2Biosevka.el), although it's made to work with a custom patched font - ping @ar1a 

But looking at the [specimen](https://typeof.net/Iosevka/specimen.html) I didn't find any ligature.

# Are the ligatures always in the same position even with different ligsets ?

This would help tremendously to use the same associations for multiple ligsets currently.

Thanks for the answers !

**Comment by ar1a** [comment]
just to clear it up, i think op is also referring to [this gist](https://gist.github.com/mrkgnao/49c7480e1df42405a36b7ab09fe87f3d)

**Comment by be5invis** [comment]
There isn't ”ligature glyphs“ in Iosevka. The way Iosevka implements ligatures are replacing its components into some other shapes that joins together, which is somehow like many Arabic fonts. Therefore to properly display Iosevka the software **must properly support OpenType layout**. Checkout https://github.com/kovidgoyal/kitty/issues/298 for more details.

However you **can** configure Iosevka to produce ”ligature glyphs“ using the `compLig` stuff mentioned here: https://gist.github.com/mrkgnao/49c7480e1df42405a36b7ab09fe87f3d.

**Comment by gagbo** [comment]
Thanks, a lot of stuff is clearer in my head now. Sorry for the noise !
