### ISSUE TITLE
Subpar hinting of small sizes and lower weights

### ISSUE THREAD

**Issue by whtyger** [be5invis/Iosevka#347]
* Your font version: Release 2.2.1, Term variation
* Your font variant: Regular and Semi-Bold
* Your operating system (name and version): Ubuntu 16.04
* Your application using Iosevka: gedit, kate

First of all thanks for the great font.
I'm using full hinting and RGB subpixel rendering in my system. I noticed that hinting of Iosevka at small font sizes isn't good. For example, I made a comparison with Liberation Mono:

![Iosevka-Liberation](https://user-images.githubusercontent.com/54144747/63099626-1de76800-bf7e-11e9-8e89-ed2c96014ea5.png)

Some Regular weight symbols' hinting is better, some is worse. I mean '=', '-', 'E' (letter's top and bottom bar), square brackets and some other. Their horizontal elements are blurry, vertical elements look better. Liberation Mono of the same weight is drawn very distinctly. Situation improves if we take Semi-Bold or Bold weight of Iosevka. Also hinting improves if we begin to increase font size.
Strangely enough, if I look at the [example](https://cloud.githubusercontent.com/assets/240091/21964541/a7eccc3e-db88-11e6-9753-c21dc475c278.png) posted here earlier the letters in it look pretty hinted. Or they have increased size?

Can this hinting situation be improved? Maybe some `ttfautohint` settings may be used to produce better result? I searched through the source code but haven't found settings of `ttfautohint`. Or it is called with the default settings?

**Comment by whtyger** [comment]
As no one answered yet, I'll share the results of my experiments. Digging in [ttfautohint manual](https://freetype.org/ttfautohint/doc/ttfautohint.html) I found `--stem-width-mode` option which impacts hinting progress. You can take the unhinted font of the desired build located in **ttf-unhinted/** folder and perform its hinting with the command (change font names and folders as needed):

    ttfautohint -a sss iosevka-semibold.ttf ../ttf-hinted/iosevka-semibold.ttf

The default value of `--stem-width-mode` (or `-a`) option is `qsq`. `sss` value enables using of "strong" algorithm for all three types of rendering (check the manual for more details).
The result of this "strong" hinting can be seen in comparison:

![HintingCompare](https://user-images.githubusercontent.com/54144747/64113940-5cf62580-cd94-11e9-9cfd-52b5ab757377.png)
The situation isn't perfect (`_`,`-`,`=` in the Regular font are still blurry), but letters and symbols look much more clear.
Caveat: this algorithm _may_ cause some glyph shape distortion to a greater degree than the default algorithm.

**Comment by be5invis** [comment]
Added options to customizing TTFA parameters in custom build.
Closed.
