### ISSUE TITLE
=> ligature  renders poorly in VS and VSCode when certain font sizes are used

### ISSUE THREAD

**Issue by shytikov** [be5invis/Iosevka#349]
* Your font version: Iosevka 2.2.1
* Your font variant: SS03
* Your operating system (name and version): Windows 10
* Your application using Iosevka: Visual Studio 2019, Visual Studio Code
---

I don't know why but on certain sizes Iosevka start messing with ligatures. Here is an example in Visual Studio 2019 with size 9:

![image](https://user-images.githubusercontent.com/1185905/63354514-dc333480-c364-11e9-9e4b-a9f29a5caec8.png)

Here is an example in Visual Studio Code with size 14:

![image](https://user-images.githubusercontent.com/1185905/63354633-14d30e00-c365-11e9-8a2d-d638007abe24.png)

It's not centered and looks just ugly. Other sizes tend to work better and don't have such issue.

Is there any workaround? Sadly this is my most used ligature and I also can work with this sizes only...

**Comment by be5invis** [comment]
You can try the unhinted variant.

________________________________
发件人: Alexey Shytikov <notifications@github.com>
发送时间: Tuesday, August 20, 2019 7:13:27 AM
收件人: be5invis/Iosevka <Iosevka@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [be5invis/Iosevka] => ligature renders poorly in VS and VSCode when certain font sizes are used (#349)


  *   Your font version: Iosevka 2.2.1
  *   Your font variant: SS03
  *   Your operating system (name and version): Windows 10
  *   Your application using Iosevka: Visual Studio 2019, Visual Studio Code

________________________________

I don't know why but on certain sizes Iosevka start messing with ligatures. Here is an example in Visual Studio 2019 with size 9:

[image]<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F1185905%2F63354514-dc333480-c364-11e9-9e4b-a9f29a5caec8.png&data=02%7C01%7C%7C787719edcf344e00c74708d7257892bf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637019072095279127&sdata=Wneln8rCKbvlVIzQafhfBWsns5yweSzvZO4IdtHZ9OQ%3D&reserved=0>

Here is an example in Visual Studio Code with size 14:

[image]<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F1185905%2F63354633-14d30e00-c365-11e9-8a2d-d638007abe24.png&data=02%7C01%7C%7C787719edcf344e00c74708d7257892bf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637019072095299144&sdata=I7zhCobBZ4l4H4%2F3P2OzBMuMWiyxzn1gOXCckChgoT8%3D&reserved=0>

It's not centered and looks just ugly. Other sizes tend to work better and don't have such issue.

Is there any workaround? Sadly this is my most used ligature and I also can work with this sizes only...

―

**Comment by shytikov** [comment]
Thanks! Unhinted fonts seems to be working.

However I have failed to import SS03 style. Windows said that format is incorrect. I will investigate and maybe create another bug for that.

Thank you for your help! You literally saved my day! If I knew that it's so easy to fix, I would ask this question at least one year earlier! 👍 👍 👍

**Comment by be5invis** [comment]
You can try to run a TTX roundtrip to fix “corruptions”.

________________________________
发件人: Alexey Shytikov <notifications@github.com>
发送时间: Tuesday, August 20, 2019 12:44:08 PM
收件人: be5invis/Iosevka <Iosevka@noreply.github.com>
抄送: Belleve Invis <be5invis@outlook.com>; Comment <comment@noreply.github.com>
主题: Re: [be5invis/Iosevka] => ligature renders poorly in VS and VSCode when certain font sizes are used (#349)


Closed #349<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbe5invis%2FIosevka%2Fissues%2F349&data=02%7C01%7C%7C63748e22cf5840eef58a08d725a6c4e1%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637019270510506705&sdata=Mope4llmNGtkkeo%2Bsh0v8Sdrg%2FRPwtNi%2BH2hxetaunU%3D&reserved=0>.

―
