### ISSUE TITLE
"@" gets cuts when you underline it

### ISSUE THREAD

**Issue by IceMan81** [be5invis/Iosevka#35]
Sorry if my title does not clearly describe the issue. See my attached screenshot.
![_gets_cut](https://cloud.githubusercontent.com/assets/1093778/11537048/26b9e9c2-98d0-11e5-8a38-f67de2858f2f.png)

**Comment by be5invis** [comment]
Well I do not think that there is any problem about the `/at`, since it is designed to have descender. This image looks just normal.
