### ISSUE TITLE
Variable Width Variant?

### ISSUE THREAD

**Issue by BilLOPGVkPPn8z0JGJhgiAGNo9YAqpk5ruChl0F** [be5invis/Iosevka#351]
Couldn't find anywhere else to ask so I'll ask here.

Is there any interest or support at all for generating a variable width, non-monospace version of Iosevka? Like Source Sans Pro or DeJaVu Sans.

**Comment by reli-msft** [comment]
Try out _Aile_ and _Etoile_ in version 2.3.
Note: they are experimental so it may have _many bugs_. Report if you find any.

**Comment by be5invis** [comment]
Try out Aile and Etoile in version 2.3.
Note: they are experimental so it may have many bugs. Report if you find any.
