### ISSUE TITLE
[Feature Request] Digit 7 with downward pointing bit (But first, easier way to make own sets)

### ISSUE THREAD

**Issue by AlsoScratch** [be5invis/Iosevka#352]
It would be nice if you could include a style where the digit 7 has a downward pointing bit like in Anonymous Pro or IBM Plex Mono.

But first, I feel there needs to be an easier way to create my own stylistic sets.

**Comment by alexeyten** [comment]
> I also wish for the digit 3 with a sharp angle
There is a flat top 3

**Comment by AlsoScratch** [comment]
How do I build my own set?

**Comment by AlsoScratch** [comment]
I will probably need a tutorial on that. In the meantime, my suggestion is the digit 7 having a bit pointing downwards.

**Comment by be5invis** [comment]
@AlsoScratch 
To support that you need to port many C/C++ programs to JS -- which is still hard even if you have webassembly.
Also building one family of Iosevka takes about 30 minutes with one thread.

**Comment by be5invis** [comment]
Consolidate to #140. Closed.

**Comment by AlsoScratch** [comment]
Are there any video tutorials on this I can find?

**Comment by AlsoScratch** [comment]
> Consolidate to #140. Closed.

I still don't see it there.

**Comment by AlsoScratch** [comment]
> @AlsoScratch
> To support that you need to port many C/C++ dependencies to JS -- which is still hard even if you have webassembly. Also building one family of Iosevka takes about 30 minutes with one thread.
> (How do I build the release packages? A workstation with 24 cores.)

I am very new to building from source, so I wanted a method that would be quick and intuitive, but apparently, creating one isn't as straightforward...🙁
