### ISSUE TITLE
Perverse "shape" of 'm' and such letters in Slab

### ISSUE THREAD

**Issue by chelovechishko** [be5invis/Iosevka#356]
* Your font version: latest git
* Your font variant: custom slab

`m` (even with short leg) and such has "line" instead of "separated underscores".
As readme first image (bottom half) also has such shape, i guess it is not fault of my build.

It is `m` and two `U+0448` `(cyrsha) ш` (slab variant): ![m_cyrsha](https://user-images.githubusercontent.com/14850730/65688438-a74c8880-e05a-11e9-9f17-c19c40413f43.png)

**Comment by cata0309** [comment]
Use other words like "visual bug", how can a font be perverse ?!?
Also a tip for the future issues: write the version number with actual numbers so other people would not have to be Sherlock Holmes and check what "latest git" really mean !

**Comment by chelovechishko** [comment]
> how can a font be perverse ?!?

Oh, i dunno... Maybe when it made for some existing language with certain shapes (more or less), but all symbols are mostly (or totally) different from what some (read as "all viewers") would expect?
I did not expect such shape from these letters, so i used such word.

> Also a tip for the future issues: write the version number with actual numbers so other people would not have to be Sherlock Holmes and check what "latest git" really mean !

What is wrong with referring to latest git commit at moment of writing issue? Don't see commits for a month at the moment of writing. I thought you have not to be a Holmes to figure it out. Also, i think that author knows better at what time he made latest picture with font example (which i referred).
