### ISSUE TITLE
[Feature Request] Pre-built variant in Ubuntu Mono Style

### ISSUE THREAD

**Issue by michaeldurland** [be5invis/Iosevka#358]
* Your font version: 2.3.0
* Your font variant: currently using Menlo Style
* Your operating system (name and version): Linux RedHat 6, SUSE 11, SUSE 12, Windows 10
* Your application using Iosevka: konsole, emacs

Please consider providing a pre-built variant like Ubuntu Mono. I believe Iosevka already has all the variant characters, so I think it is possible to package this by picking out the matching character variants, similar to how has been done for other pre-built variants.

Thanks for an awesome font!

**Comment by cata0309** [comment]
I would love to have an Ubuntu variant of Iosevka !

**Comment by be5invis** [comment]
PRs are welcome 🙂.
The prebuilt styles are defined in `variants.toml`

**Comment by nero1st** [comment]
+1 for this.

**Comment by be5invis** [comment]
We already have this. Closed.
