### ISSUE TITLE
"/\" and "\/" ligatures not working on MacOS

### ISSUE THREAD

**Issue by Tom1206** [be5invis/Iosevka#359]
* Your font version: Release
* Your font variant: Regular
* Your operating system (name and version): MacOS Mojave
* Your application using Iosevka: all of the MacOS system and apps

Describe your problem here. Provide pictures and files if necessary.

The AND and OR "/\" "\/" ligatures are not working on MacOS.

This is how it looks in safari browser, and all my coding apps:
<img width="137" alt="Screenshot 2019-10-01 at 17 16 15" src="https://user-images.githubusercontent.com/10849079/65975945-b1fa8980-e46f-11e9-97a9-a8712f4453d6.png">

This is how it's supposed to look (it works with a chromium based browser):
<img width="131" alt="Screenshot 2019-10-01 at 17 16 51" src="https://user-images.githubusercontent.com/10849079/65975954-b6bf3d80-e46f-11e9-9fed-fd640a1e1e38.png">

**Comment by be5invis** [comment]
Some software may not support non-standard feature tags.
To make them default in `calt` you need a custom build. See README for details.
