### ISSUE TITLE
Font proportion changes from 2.2.1 to 2.3.1

### ISSUE THREAD

**Issue by nickpodkopaev** [be5invis/Iosevka#360]
Dear be5invis!

I found some issue after changing from 2.2.1 to 2.3.1 version.
The font proportions has been changed as well as horizonal spacing (on horizontal lines)
Please see attached pictures (the fort size is 22).

![2 2 1](https://user-images.githubusercontent.com/54263656/65983056-5b984580-e485-11e9-9c6a-8c9161a93e2a.jpg)
![2 3 1](https://user-images.githubusercontent.com/54263656/65983062-5fc46300-e485-11e9-9de8-1eb711ab1ad7.jpg)

* Your font version: 2.2.1 (upper pic) and 2.3.1 (lower pic)
* Your font variant: Term Slab
* Your operating system (name and version): Windows 10 x64 1903
* Your application using Iosevka: FAR Manager x64 3.0.5454

Is it expected issue?

Regards,
Nick

**Comment by be5invis** [comment]
Version 2.3 changed how line height works, so you may need to adjust your font size / line height.
cc. @chuling

**Comment by nickpodkopaev** [comment]
Thanks a lot!
Unfortunately I use this font in console app and I can change only font size.

Regards,
Nick
