### ISSUE TITLE
Error: Cask 'iosevka-slab' is unavailable: No Cask with this name exists.

### ISSUE THREAD

**Issue by StormKhan** [be5invis/Iosevka#369]
![image](https://user-images.githubusercontent.com/13731831/67079577-0880fb00-f1c6-11e9-872b-2edae1e2f860.png)

> Standard distribution in Homebrew: brew tap homebrew/cask-fonts && brew cask install font-iosevka && brew cask install iosevka-slab

I followed above instruction then appear the error.
Are you change the brew repository name?

**Comment by be5invis** [comment]
I do not own the Brew thing. (Actually I do not have Macintosh.)
Please report to https://github.com/robertgzr/homebrew-tap.
Closed as external.
