### ISSUE TITLE
Symbol being cut off in ZSH using Agnoster theme

### ISSUE THREAD

**Issue by IceMan81** [be5invis/Iosevka#37]
On ZSH, when using the agnoster theme, the symbol is getting cut off. See the screenshot.
![zsh_shell_cut_off](https://cloud.githubusercontent.com/assets/1093778/11723132/78f5c330-9f21-11e5-9228-7ad41556cfb5.png)

It should look like
![zsh_shell_not_cut_off](https://cloud.githubusercontent.com/assets/1093778/11723163/adfb73cc-9f21-11e5-9d0e-3c4e7bebc6fd.png)

**Comment by be5invis** [comment]
The “cross” symbol is not included in Iosevka. Including it will resolve this.

**Comment by be5invis** [comment]
@IceMan81 Could you please tell me the Unicode of this cross? And, providing more symbols used in these themes will be better.

**Comment by IceMan81** [comment]
@be5invis This is the list of some of the symbols that are used.
https://cloud.githubusercontent.com/assets/2618447/8370414/8f0f313e-1b95-11e5-957e-5a9c8e2d0a21.png

**Comment by be5invis** [comment]
@IceMan81 wait... Emoji ?

**Comment by IceMan81** [comment]
@be5invis I think you can skip "U+2B80". Take a look at what is listed on the Agnoster theme's github 
https://gist.github.com/agnoster/3712874

This is on my zsh with PragmataPro

<img width="690" alt="screen shot 2015-12-11 at 6 46 23 am" src="https://cloud.githubusercontent.com/assets/1093778/11746438/05f6b7ec-9fd3-11e5-9f8d-bbd1f47b884c.png">

**Comment by be5invis** [comment]
Maybe Pragmata Pro contains such symbols I think.
Considering drawing these icons may be difficult for the `dispiro` mechanism, perhaps I will do the 3rd-party glyphs API first.

**Comment by Arthur2e5** [comment]
A list of Pragmata Pro coverage is available at https://github.com/fabrizioschiavi/pragmatapro.

**Comment by chenjuntong** [comment]
I have the same problem.
![](http://ww3.sinaimg.cn/large/6ccda21fjw1f3ft6zinz9j205901ct8k.jpg)

**Comment by be5invis** [comment]
Consolidated to #81. Closed
