### ISSUE TITLE
Incorrect font name when changing the weight value

### ISSUE THREAD

**Issue by gexplorer** [be5invis/Iosevka#371]
When trying to build my own variant of the font besides some stylistic changes I wanted to change the weight of the **bold** variant, because I prefer the semibold weight in my current setup and since the build method seemed pretty straightforward I added the expected _weights.bold_ section within my configuration and I changed the value from the default 700 to 600.

After building the font I noticed that while the configuration section is called **bold** and the resulting file is called _iosevka-bug-bold.ttf_, as espected, the metadata of the font says **semibold**. When trying to install the font the displayed font name is **Iosevka Bug Semibold**, and after installing it, when trying to use it I only see the **semibold** variant.

After taking a look into the code I noticed that even though the configuration parameter is named **bold**, the name of the variant is generated mapping the value itself, according to the file **meta/naming.ptl**. So even though the configuration makes possible to change the value of the weight of any of the variants, the resulting font doesn't reflect the configuration.

---
* Here's the minimum `parameters.toml` to test this:
```
[buildPlans.iosevka-bug]
family = "Iosevka Bug"

[buildPlans.iosevka-bug.weights.bold]
shape = 600
menu  = 600
css   = 600

[buildPlans.iosevka-bug.slants]
upright = "normal"

**Comment by be5invis** [comment]
The font menu name is decided by the `menu` entry under `buildPlans.<family>.weights.<weight>`. In your case. you should write like this:

```toml
[buildPlans.iosevka-bug.weights.bold]
shape = 600
menu  = 700
css   = 700
```
