### ISSUE TITLE
Consider implementing a fully-proportional variant of Iosevka Aile

### ISSUE THREAD

**Issue by cssobral2013** [be5invis/Iosevka#373]
So, it would be useful to use this font in body copy.

**Comment by cssobral2013** [comment]
I

**Comment by lshoravi** [comment]
Is it possible for you to share how you did that?

**Comment by cssobral2013** [comment]
Basically, I used a tool on FontLab that tightens spacing.

Em sex, 24 de jan de 2020 11:13 AM, lshoravi <notifications@github.com>
escreveu:
