### ISSUE TITLE
Downward arrow is mispositioned in xfce4-terminal

### ISSUE THREAD

**Issue by StreetStrider** [be5invis/Iosevka#374]
Hello,

* Your font version: 2.3.2 and several previous
* Your font variant: iosevka-term-ss10, Ubuntu repo Iosevka, Void Linux repo Iosevka
* Your operating system (name and version): Void Linux, Ubuntu Linux 18.04
* Your application using Iosevka: xfce4-terminal

I'm using Iosevka for terminal, exclusively in xfce4-terminal. Previously when using Iosevka on Ubuntu I got arrow's vertical line perfectly aligned with pipe symbol. Later, using Void Linux I got alignment as well. But after some upgrade or some reconfiguration I got misposition as on pic.

![img](https://user-images.githubusercontent.com/2124761/67599979-d9482c00-f779-11e9-88e2-c23a53ec157b.png)
I think this is not a Iosevka issue, but maybe someone can help me where to dig for issue and what configs to look?
I got this issue with the version of font which previously work ok, so I believe this is not a font issue. But I haven't expertise to localize issue.

I've tried terminal version specially, but issue happens with the stock repo's version of the font as well.

**Comment by be5invis** [comment]
This arrow is not designed to be connected with box drawing characters

**Comment by be5invis** [comment]
Close as by design

**Comment by StreetStrider** [comment]
Understood.
Have you ever make changes to the positioning of that arrow?

**Comment by be5invis** [comment]
No. I added it maybe several months ago, and it always worked like that.
If you want _connected_ angle arrow, use a box-drawing character (like `└`) and a normal arrow (`→`)

**Comment by StreetStrider** [comment]
Ok, copy that. So that was totally rendering issue on my side (most likely xfce4-terminal). Thanks for clarifications. :+1: 
Yes, I've already switched to the box-drawing angle you mention.
