### ISSUE TITLE
Powerline glyphs for bottomRight and topRight are identical

### ISSUE THREAD

**Issue by gexplorer** [be5invis/Iosevka#379]
* Your font version: 2.3.2
* Your font variant: All
---
In the latest version of the font and in the one shown in the specimen in the web, both **pwlCornerBottomRight** and **pwlSlashBottomRight** are identical to their **top** counterparts.

It is possible to create a tab effect with the top glyphs, but not with the bottom ones.

![Powerline corners and slashes example](https://user-images.githubusercontent.com/1837971/68463403-d4ba5380-020e-11ea-8841-59c1ddec0494.png)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/68463863-62248600-01c4-11ea-807a-6e133a4ea564.png)
