### ISSUE TITLE
Minus is blurred on windows

### ISSUE THREAD

**Issue by habamax** [be5invis/Iosevka#381]
* Your font version: (2.3.3)
* Your font variant: default
* Your operating system (Windows 10.0.18362):

Minus is quite blurred compared to other chars/symbols with 14pt size.

Notepad:
![image](https://user-images.githubusercontent.com/234774/69874848-16e62a80-12cd-11ea-8e22-49145e3981bc.png)

Neovim-qt
![image](https://user-images.githubusercontent.com/234774/69874866-2796a080-12cd-11ea-935a-13c2428df293.png)

Gvim
![image](https://user-images.githubusercontent.com/234774/69874882-31200880-12cd-11ea-92a6-73ad6a5568ad.png)

Not sure if this is a bug or just windows rendering issue (depending on font size either _ is blurred or - is blurred)

**Comment by be5invis** [comment]
Fixed in dev.
