### ISSUE TITLE
Stylistic sets for >= and <= ligatures

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [be5invis/Iosevka#382]
* Your font version: 2.3.3
* Your font variant: Iosevka
* Your operating system (name and version): macOS 10.14
* Your application using Iosevka: iTerm

`>=` and `<=` have ligatures that make them one character. These do their job okay, but I've been comparing PragmataPro Liga with Iosevka and the former has an quite pretty way to render them:

Iosevka:
<img width="58" alt="Screenshot 2019-12-02 at 16 50 44" src="https://user-images.githubusercontent.com/121531/69973542-f532b080-1523-11ea-9779-6401f05dfd1a.png">

PragmataPro:
<img width="60" alt="Screenshot 2019-12-02 at 16 49 36" src="https://user-images.githubusercontent.com/121531/69973562-febc1880-1523-11ea-81c5-6edf55a0d05e.png">

I think it would be nice if there was a similar option for Iosevka as well.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/71581943-aa716d80-2abc-11ea-8d76-3daa41de0149.png)
It's now in `cv67`.
