### ISSUE TITLE
Build took a long time (12+ hours) and the end result looks badly damaged

### ISSUE THREAD

**Issue by notsukamto** [be5invis/Iosevka#383]
* Your font version: git latest master
* Your font variant: Iosevka default customized
* Your operating system (name and version): macOS Catalina ver 10.15.1
* Your application using Iosevka: Font Book

If you have problem when building Iosevka, please provide these information:

* Your Node.js version: v12.11.1
* Your _otfcc_ version: 0.9.6
* Your `private-build-plans.toml`, if present:
```
[buildPlans.iosevka-edge]            # <iosevka-edge> is your plan name
family = "Iosevka Edge"              # Font menu family name
design = [                           # Customize styles
  "v-a-doublestorey",
  "v-f-straight",
  "v-g-doublestorey",
  "v-i-line",
  "v-l-zshaped",
  "v-q-straight",
  "v-t-cross",
  "v-y-straight",
  "v-asterisk-hexhigh",
  "v-at-fourfold",
  "v-percent-dots"
  ]
```
---

The build will take as long as 12+ hours although with no errors in the process. The end result is the main problem. It looks badly damaged:
![image](https://user-images.githubusercontent.com/33288305/70253698-435ee280-17b6-11ea-90b9-f05324749002.png)

**Comment by be5invis** [comment]
It's a bug in the dep. Just fixed and it will work now
