### ISSUE TITLE
caret (^) is very small almost impossible to see

### ISSUE THREAD

**Issue by IceMan81** [be5invis/Iosevka#39]
Its hard to see when used in code.

**Comment by be5invis** [comment]
Well I think i will zoom in the marks in ASCII and Latin-1 in the next release, since they are composites of  a spance and a combining mark.

**Comment by IceMan81** [comment]
@be5invis I tried a build of the latest code. Yes it is a bit bigger now, but I still feel its too small. Especially a problem when you write bit manipulation code like :
`a = b ^ c`

**Comment by be5invis** [comment]
@IceMan81 you can change this in `autobuilds.ptl`:
```patel
local MarkZoom : glyph-construction
		apply-transform : Upright
		apply-transform : Translate (-MIDDLE) (-XH - ACCENT)
		apply-transform : Scale ((RIGHTSB - SB) / (markExtend * 3)) # ← change this
		apply-transform : Translate (MIDDLE) (XH + ACCENT)
		apply-transform : Italify 
```

**Comment by IceMan81** [comment]
@be5invis  modifying the above increases the thickness of caret & tilde (and possibly other glyphs) but does not make the symbol larger. For example, I feel caret is more visible if its a bit longer in size. I feel it helps a lot if symbols like colon, semi-colon, period, caret etc that are used extensively in code (these are generally easy to miss) stands out a bit.

**Comment by be5invis** [comment]
Increasing the number after Scale actually incrceases BOTH thickness and size.

**Comment by IceMan81** [comment]
@be5invis Are you referring to
`apply-transform : Scale ((RIGHTSB - SB) / (markExtend * 3)) # ← change this'

changing the `3` above to a smaller value

**Comment by be5invis** [comment]
@IceMan81 Well you should change the whole `((RIGHTSB - SB) / (markExtend * 3))`, for example, change it into `(1.1 * (RIGHTSB - SB) / (markExtend * 3))`

**Comment by IceMan81** [comment]
@be5invis that worked well for me. Thanks! 

Off topic, could you point me to where the hinting parameters for ttfautohint are set?

**Comment by be5invis** [comment]
@IceMan81 `onegroup.mk`, change the line containing `ttfautohint` to whatever you like. Currently I use the default parameters.
