### ISSUE TITLE
[Symbol Request] flesh out letter-like symbols block

### ISSUE THREAD

**Issue by arknjl** [be5invis/Iosevka#392]
this is primarily a programming font, but since you have such broad support for mathematical symbols, why not pull out all the stops?

the double struck letters would be nice for set theory and such:
- `ℕ` natural numbers
- `ℚ` rational numbers
- `ℝ` real numbers
- `ℤ` integers

as would the "par" operator from linear logic to complete the collection:
- [ ] `⅋` multiplicative disjunction
- [x] `&` additive conjunction
- [x] `⊗` multiplicative conjunction
- [x] `⊕` additive disjunction
- [x] `⊤` conjunctive unit
- [x] `⊥` disjunctive unit

aleph, and i _suppose_ bet, for anyone working with cardinals:
- `ℵ` letter aleph
- `ℶ` letter bet

**Comment by be5invis** [comment]
As your pleasure.
(I'd not like to fill the math letter block yet -- they may be done in another postprocessing script).
![image](https://user-images.githubusercontent.com/240091/71567994-77a58600-2a78-11ea-9774-b7d71471987c.png)
