### ISSUE TITLE
Variant tag for k?

### ISSUE THREAD

**Issue by AlsoScratch** [be5invis/Iosevka#393]
Will there be a variant tag for switching between cursive and standard `k` in version 3.0? (Like what `f` has right now)
If so, I suggest that they are called `standard` and `cursive`.

**Comment by be5invis** [comment]
There are now `v-k-standard` and `v-k-cursive` selector.
However I'd like **not** to assign OT tags to them since `v-k-cursive` is designed for italics only.

**Comment by AlsoScratch** [comment]
I can use OT tags to get the oblique `a`, `f` and `g` and wish to do the same for `k`.

**Comment by be5invis** [comment]
The cursive `k` under upright will get broken shape since it is _only_ designed for italics.

**Comment by be5invis** [comment]
Done in Dev. Now the italics will have `cv68` for straight `k`, and `cv69` for cursive `k`. Upright and Oblique will not be affected.
