### ISSUE TITLE
Variant name suggestions (3.0)

### ISSUE THREAD

**Issue by AlsoScratch** [be5invis/Iosevka#394]
These are my suggestions for renaming certain variant names for version 3.0 to make them less vague.

- `v-m-longleg` sounds to me like the middle leg is longer than the rest. Another possible name would be `v-m-same-length-legs`.

- `v-one-hooky` would become `v-one-nobase`.
As such, `v-one-serifed` becomes `v-one-base`.

- For `i` and `l`, the `hooky` variants should be called `hookytop`, and the `italic` variants should be called `cursive`.

- `v-seven-normal` becomes `v-seven-noserif`

**Comment by be5invis** [comment]
I'd like to keep the names for `i` and `l`, and for others:

 * `v-m-longleg` → `v-m-normal`
 * `v-one-hooky` → `v-one-nobase`
 * `v-one-serifed` → `v-one-base`
 * `v-seven-normal` → `v-seven-noserif`
 * `v-seven-force-serifed` → `v-seven-serifed`
