### ISSUE TITLE
[Ligation Request] the big one.

### ISSUE THREAD

**Issue by ghost** [be5invis/Iosevka#395]
whew. i don't expect you to implement all of these but instead of making 100 new issues i'm just going to rapid-fire all of them here. cheers.

PRETTY IMPORTANT TO ME:
- `|->`: maplet; `↦` (U+21A6)
- `~>`: squiggly arrows and all their variants (`~~>`, `<~`, etc., `~>>` if you wanna go that far)

MEH:
- ligatures with `>=`/`=<` in them e.g. `>>=` and `>=>`: open a hole between the angle and `=` so it looks like a funnel rather than just the glyphs smushed together
- `-|`: like turnstile but just reversed. just for symmetry's sake.
- `===` and `!==`: triple bars for differentiation between double-length counterparts (`==` and `!=`)
- `[|` and `|]`: squish 'em together but still leave a gap so they aren't just thin rectangles

YOU REALLY DON'T HAVE TO DO THIS:
- `/=`: inequals [haskell]; for an equality operator i don't think the slash should be as tall as it is; it's not division. also maybe bars of equals should extend to the side of the slash.
- `<$`/`<$>`/`$>`: fancy haskell ligature where the ends of the S curve connect to the angle brackets. adjust for stylistic `$` sets
- `<+`/`<+>`/`+>`: more haskell. squish everything together and emphasize the `+` a tad so that it feels more operator-y
- `(|` and `|)`: similar to `[|` and `|]`

**Comment by be5invis** [comment]
> `~>`: squiggly arrows and all their variants (`~~>`, `<~`, etc., `~>>` if you wanna go that far)

Ah, wave, the most hated shape that I implemented. Time to rewrite `[TildeShape]`...

**Comment by be5invis** [comment]
But anyway, here it is:
![image](https://user-images.githubusercontent.com/240091/71640958-1254bf00-2c49-11ea-99d7-597d86de2b0f.png)

**Comment by arknjl** [comment]
looks nice! any word of what you’re going to do with the others?

**Comment by MetroWind** [comment]
Sounds like you are well on your way to implement Feynman diagrams in a font.

**Comment by AlsoScratch** [comment]
> > `~>`: squiggly arrows and all their variants (`~~>`, `<~`, etc., `~>>` if you wanna go that far)
> 
> Ah, wave, the most hated shape that I implemented. Time to rewrite `[TildeShape]`...

So the new version will have a new `~` shape?

**Comment by be5invis** [comment]
@AlsoScratch It is in the dev branch currently, you need to build it at your own

**Comment by arknjl** [comment]
@be5invis any word of what you’re planning to do with the rest of the list?

**Comment by be5invis** [comment]
I will at least implement `|->`. Just hold on :)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/72120565-37ae9080-330d-11ea-81f5-52184d99e107.png)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/72120708-b9062300-330d-11ea-9148-5dc0222e3703.png)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/72121398-c58b7b00-330f-11ea-8829-c2ff9cdac894.png)

**Comment by AlsoScratch** [comment]
> 
> Ah, wave, the most hated shape that I implemented. Time to rewrite `[TildeShape]`...

See, because the latest official release currently does not have squiggly arrows, I thought this meant that the shape of the `~` character might have been a bit controversial when it first came out.

I have felt that the curves are a bit too sharp, especially as a diacritic on letters like Ñ or Õ and I took this as an indication that the `~` was being redesigned to look a lot more like the squiggly arrows in the picture above.

**Comment by be5invis** [comment]
I'd like to close this now wince the ligations are included.
