### ISSUE TITLE
[Feature Request] Old-style Figures

### ISSUE THREAD

**Issue by limingjie** [be5invis/Iosevka#397]
* Your font version: 3.0.0-alpha.2
* Your font variant: Iosevka Curly
* Your operating system: macOS Catalina, macOS Mojave, Windows 7 (sometimes)
* Your application using Iosevka: VSCode, Kitty, and any IDE or terminal the font can be customized.

---
Could you create the old-style figures like Fira Code has? I've been using Iosevka for years, I tried the Fira Code recently and quickly switched back. The old-style figures seems to be an awesome feature, it makes programming a little be more fun.

Now, I enabled the 3 digit variants, but it cannot mimic the feeling of "ups and downs".
- cv51 - 1 - v-one-serifed
- cv46 - 3 - v-three-flattop
- cv65 - 7 - v-seven-force-serifed

It is probably required to create the following new variants.
- The shorter version of 0, 1, and 2.
- The lower version of 3, 4, 5, 7, and 9.

Fira Code Old-Style Figures
![image](https://user-images.githubusercontent.com/6889308/71659398-66af8a00-2d82-11ea-967f-1bfb0d1af850.png)

Or [this one](https://underware.nl/fonts/zeitung/features/OpenType_features/)
![image](https://user-images.githubusercontent.com/6889308/71659796-d2462700-2d83-11ea-9578-71bf7d84d224.png)

**Comment by zero00072** [comment]
Old-style is nice! Recently, I have known that from "Alegreya". The style made me comfortable.

Maybe I also want two fonts make more consistently. But I think that source code styles are still more fit for lnum.

**Comment by limingjie** [comment]
I tried to modify the font with FontForge, not too bad. It will be great if there is a programmable way. I looked into the glyphs/numbers.ptl, but cannot find an idea.

![image](https://user-images.githubusercontent.com/6889308/71718985-d5124c00-2e57-11ea-9a39-713852304bf1.png)

**Comment by be5invis** [comment]
Interesting, Fira Code has old-style figures.
![](https://github.com/tonsky/FiraCode/raw/master/showcases/stylistic_sets.png)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/71769599-219d6c00-2ed8-11ea-8f5d-207217e23cdc.png)
Landed in Dev. Closed.

**Comment by limingjie** [comment]
Thank you @be5invis !

**Comment by wimstefan** [comment]
Nice 👍🏼
How do we address this in private-build-plans.toml? Simply with `"onum"` or with `"v-{one,two,three,four,five,six,seven,eight,nine,zero}-onum"` ?

**Comment by be5invis** [comment]
@wimstefan You want old-style numbers **by default**? 
I think it is a really bad idea for a programming font. And it will interfere with existing variant selectors.
Modern editors including VSCode support calling up OpenType features, so you can use it in a more proper way.

**Comment by zero00072** [comment]
I have tried it by edited `glyphs/numbers.ptl` to set default to `onum`. It's really a bad idea in terminal and editors. Finally, I roll it back to `lnum`.

**Comment by wimstefan** [comment]
Thanks for your swift response guys! (In opposition to my slouch answer ;-) )
It was more out of interest that I asked and also because adding `"onum"` in `private-build-plans.toml` didn't  make a difference. But if you guys tell me it's a bad idea I'll let it go immediately :)

**Comment by akarzim** [comment]
> @wimstefan You want old-style numbers **by default**?
> I think it is a really bad idea for a programming font. And it will interfere with existing variant selectors.
>  Modern editors including VSCode support calling up OpenType features, so you can use it in a more proper way.

@be5invis is it possible to enable `onum` for italic only in `private-build-plans.toml`? How can I do that?  
I think it could have a good looking in comments. (PS: my _modern_ editor is Vim in a terminal ^^)

**Comment by dixius99** [comment]
I understand that having old-style figures for a programming font might not be a good idea, but I wonder about somehow allowing an easy default for the Aile, Etoile, and Sparkle variants, which are made for documentation and writing, where old-style figures are a little more common.

**Comment by pv4** [comment]
@akarzim @dixius99 @wimstefan @be5invis

The attached patch adds a possibility to have old-style digits by default for ascii digits 0-9 (only). I looked at the Iosevka source code shortly and found that there are many other glyphs where a reference to `lnum` is hardcoded, and I'm unsure whether my change should influence them as well.

The patch adds `v-digits-uppercase` (default) and `v-digits-lowercase` variants that influence all the ascii digits at once. The variants are to be used along with other `v-<digit>-` variants. E.g. my own build has `v-zero-long-dotted v-four-semi-open-non-crossing v-digits-lowercase`. As with other variants, it's possible to use different variants for upright/italic/oblique styles.

The patch also reduces the height of 0/1/2 digits back to `x-height` (logically, it reverts the commit related to #402). It's my own preference. If you like the current Iosevka behavior, just edit the patch in an editor and replace the line `+ define OnumHeight XH` at the beginning of the patch by `+ define OnumHeight : mix XH CAP 0.4`.

The patch is done and tested against `dev` branch commit 9f2dc4595e82c4aa1db7e31301fbd0939fbd6d30 (the `dev` head at the moment of writing the patch). I believe it can be applied to releases 3.4.7+.

@be5invis , please feel free to commit the patch if you wish. I personally haven't yet decided whether I like `onum` digits or not. I prefer small font sizes where 0/1/2 look too small (at `x-height`) and I'm going to live with it a few days/weeks to make a final decision. Making them higher than `x-height` makes them slightly untidy and visually unpleasant for me.

[Iosevka-dev-digitscase-6.patch.gz](https://github.com/be5invis/Iosevka/files/5252306/Iosevka-dev-digitscase-6.patch.gz)

**Comment by be5invis** [comment]
@pv4 Well digits doesn't have "upper case" or "lower case". They are called "lining" and "old style". I don't think defaulting digits to old-style is necessary, especially for text variants — modern word-processing software have the ability to easily enable them.

**Comment by pv4** [comment]
> Well digits doesn't have "upper case" or "lower case". They are called "lining" and "old style".

Thanks for the information. I didn't know why `lnum` started with 'l', now I do and I'll rename the variants in my local patch version :)

> modern word-processing software have the ability to easily enable them

My 4 primary software where I use Iosevka is `uxterm` (and macOS `Terminal` app), `firefox` (I setup it to force Iosevka instead of any other fonts on sites), `phpstorm` and `i3` window manager. Generally, you might be right and choosing `onum` feature is the right way. But what to me, I just generate ttfs without hinting, make and install a package with them in /usr/share/fonts/TTF/ and I even don't know whether my environment supports choosing features like `onum` or not.

From this thread, there are more people like me.

I'm personally a bird of old flight and I prefer the way of maximum portability/compatibility where possible. Iosevka itself is just a font and works in a much wider set of environments than "modern word-processing software". I see no reason in limiting its usage in such a way (i.e. disabling the ability to have `onum` digits by default). I even see some conflict between having 20(!) variants of `m` glyph and not having an ability to make `onum` glyphs default. But that's just my Humble Opinion.

> I don't think defaulting digits to old-style is necessary

It's up to you to decide whether to merge the patch to the repository. Whatever you decide, Iosevka is a great font and is a PLEASURE to use for me. It's beautiful, supports many special glyphs, languages, weights, has upright/italic/oblique and sans/slab variants, and is monospace (so can be used for coding). It's ideal!

I made the patch by myself for myself and place it here for those who'd like to have this feature.

**Comment by be5invis** [comment]
@pv4 I just added options to default digits to old-style. Note that they are not following the variant-selector system, since `lnum`/`onum` are applied in a different stage.
