### ISSUE TITLE
New straight version not in releases?

### ISSUE THREAD

**Issue by AlsoScratch** [be5invis/Iosevka#398]
* Your font version: 3.0.0 alpha 2
* Your font variant: 02 (term)
* Your operating system (name and version): macOS 10.15.2
* Your application using Iosevka: Font book

It does not even appear that the new variants are in the releases, at least, I did not see the new straight characters. Also, the unique name still showed 2.3.3.

**Comment by be5invis** [comment]
It's a pre-release for now.
You can see them here: https://github.com/be5invis/Iosevka/releases

**Comment by AlsoScratch** [comment]
> It's a pre-release for now.
> You can see them here: https://github.com/be5invis/Iosevka/releases

Are you referring to the pictures?
