### ISSUE TITLE
Help with modifying parameters

### ISSUE THREAD

**Issue by IceMan81** [be5invis/Iosevka#40]
@be5invis I'm trying to modifying some of the parameters for my own build of the font. 

**Reducing linegap**: What is the correct range for linegap? I tried setting it to -1 but it didn't have any impact.

**Increasing weight of regular**: I would like to increase the weight of the font slightly and see how it looks. What do I modify for this?

**Comment by be5invis** [comment]
* **Recuding linegap**: Lower the `leading` value.
* **Increasing weight of regular**: Increase the `stroke` under `[w-book]`

**Comment by IceMan81** [comment]
@be5invis thanks
