### ISSUE TITLE
cv33 "@" character variant too small in Iosevka 3.0.0

### ISSUE THREAD

**Issue by p-e-w** [be5invis/Iosevka#400]
I just had a look at Iosevka 3.0.0-alpha.2 and noticed that the cv33 "@" character variant has dramatically shrunk since Iosevka 2.3.3. This can be seen by comparing the ss05 stylistic set between [3.0.0-alpha.2](https://raw.githubusercontent.com/be5invis/Iosevka/v3-alpha/images/stylesets.png) and [2.3.3](https://raw.githubusercontent.com/be5invis/Iosevka/master/images/stylesets.png).

The previous shape was perhaps not ideal but the new one is just way too small and cramped. I noticed that brackets have become smaller as well, and while I'm not a big fan of that either I can see why you made that change because it does improve visual alignment with lowercase letters.

In general though, I continue to be amazed by how this font evolves and what it can do. Iosevka truly is one of a kind!

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/71951204-1d4ea880-318f-11ea-9f53-0892bdd276ba.png)
Fixed in Dev. Closed.

**Comment by p-e-w** [comment]
The speed at which you respond to requests blows my mind... Thank you!
