### ISSUE TITLE
Option for old style numbers 0, 1, 2 that are taller than x-height

### ISSUE THREAD

**Issue by AlsoScratch** [be5invis/Iosevka#402]
This is personal taste, but there could be an option where the old-style numbers 0, 1 and 2 are a bit taller than the x-height. (x-height refers to the height of the lowercase a, e, o, u, x, etc.)

**Comment by akarzim** [comment]
I like the idea. I'll really appreciate to use old-style numbers for my italic style :)
Here is an example extract from the italian Wikipedia :

![image](https://user-images.githubusercontent.com/130560/84574502-20396f00-ada7-11ea-9e08-155ffd841e1a.png)

>  Text figures, showing baseline, x-height, ascent, and descent lines. Rendered in Hoefler Text, Corbel and monofur font.

**Note**: Old-style numbers get along better with lowercase letters. However, old-style numbers can break the flow of upper case text.

sources:
- https://it.wikipedia.org/wiki/File:Hoefler_Text_-_Corbel_-_monofur_-_Text_figures.svg
- https://en.wikipedia.org/wiki/Text_figures
- https://design.tutsplus.com/articles/using-numeral-styles--cms-23710

**Comment by AlsoScratch** [comment]
To clarify, I made this suggestion because I felt the current old-style figures didn't stand out from the lowercase letters enough.

**Comment by be5invis** [comment]
Interesting about this. In monospace fonts having old-style figures, the numbers are _taller_ than X-height, and the descender are also shorter.

Source Code Pro:
![image](https://user-images.githubusercontent.com/240091/91625747-c9334700-e95e-11ea-828d-09c4e3eb3853.png)

Consolas:
![image](https://user-images.githubusercontent.com/240091/91625754-d18b8200-e95e-11ea-8b8f-43c528447e0c.png)

Fira Code
![image](https://user-images.githubusercontent.com/240091/91625758-d7816300-e95e-11ea-8f4a-9d9bb4d3f154.png)

**Comment by be5invis** [comment]
Did a balance so it will now look better.
![image](https://user-images.githubusercontent.com/240091/91626826-3fd44280-e967-11ea-95a0-97934c7ec7dd.png)

**Comment by pv4** [comment]
@akarzim 

> I'll really appreciate to use old-style numbers for my italic style :)

How do you do that? Is there a build variant? I was unable to find anything like that.

**Comment by akarzim** [comment]
@pv4 
> How do you do that? Is there a build variant? I was unable to find anything like that.

I don't know, its a wish :) I've just asked on #397
