### ISSUE TITLE
Style linking in Extended width is not properly working

### ISSUE THREAD

**Issue by habamax** [be5invis/Iosevka#403]
* Your font version: (3.0.0 alpha3)
* Your font variant: Curly Extended and Curly Slab Extended
* Your operating system (name and version): Win10
* Your application using Iosevka: gVim

Note the @ sign is unreadable

![image](https://user-images.githubusercontent.com/234774/72216840-7031b280-3537-11ea-854b-3767b7877adf.png)

**Comment by habamax** [comment]
Not extended Iosevka looks good:

![image](https://user-images.githubusercontent.com/234774/72216891-1978a880-3538-11ea-92b4-eab014cba7b2.png)

**Comment by be5invis** [comment]
It looks like gvim is using faux bold when you use the extended version. Looks like a naming issue.

**Comment by habamax** [comment]
Non curly extended works ok:
![image](https://user-images.githubusercontent.com/234774/72217011-e9caa000-3539-11ea-9a9a-742c4d93f3c1.png)

**Comment by be5invis** [comment]
They are not working. gVim is using faux bold. You can compare the shape of letters, esp. horizontal strokes.

**Comment by be5invis** [comment]
Latest `dev` should work. Closed.

**Comment by habamax** [comment]
Not sure (I have selected bold extended in notepad to compare):

![image](https://user-images.githubusercontent.com/234774/72217151-c1dc3c00-353b-11ea-8d3e-d447021fbc40.png)

But I believe you :)

**Comment by habamax** [comment]
Thx, I have just checked alpha 4 -- looks good!
