### ISSUE TITLE
Slab 1 and l too similar?

### ISSUE THREAD

**Issue by habamax** [be5invis/Iosevka#404]
* Your font version: (3.0.0 alpha3)
* Your font variant: Sla
* Your operating system (name and version): Win10
* Your application using Iosevka: Gvim

Letter `l` and number `1` looks too similar:

![image](https://user-images.githubusercontent.com/234774/72216939-d66b0500-3538-11ea-92eb-c7c38024c1df.png)

Compare it with non slab variant(clearly distinct):

![image](https://user-images.githubusercontent.com/234774/72216954-ee428900-3538-11ea-9f1b-d1c045110946.png)

Could either `l` or `1` of slab be tinkered to improve readability?

**Comment by be5invis** [comment]
This is some sort by design.
**If you do not have serifs, why call it Slab?**

**Comment by habamax** [comment]
> This is some sort by design.
> **If you do not have serifs, why call it Slab?**

Yeah I kind of agree here, was just wondering if there is known (font designer style) solution to this kind of issues. Like different serifs or smth.

**Comment by habamax** [comment]
Looks like in alpha4 you have fixed it

![image](https://user-images.githubusercontent.com/234774/72319612-ae061680-36b0-11ea-8d6f-ab58b391419a.png)


Thx a lot!

**Comment by be5invis** [comment]
@habamax It's a bug unfortunately, composite variant selectors are not overriding each other properly.
I suggest that you do a custom build with `design = ['slab', 'v-one-nobase']` to get your desired variant.

**Comment by habamax** [comment]
Ahh, ok. Anyway I can live with that `1l` similarity.
