### ISSUE TITLE
Bulgarian letter

### ISSUE THREAD

**Issue by AlsoScratch** [be5invis/Iosevka#406]
In Bulgarian writing, this letter should look different as well:
<img width="144" alt="Screenshot 2020-01-14 at 5 30 22 PM" src="https://user-images.githubusercontent.com/48752273/72331890-f2ff6c80-36f3-11ea-8b1e-ecfd4e2377ad.png">

_(Source: [Wikipedia](https://en.wikipedia.org/wiki/Bulgarian_alphabet#/media/File:Bulgarian_cursive_alphabet.png))_

**Comment by be5invis** [comment]
Fixed in Dev.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/72419531-df72f680-3731-11ea-9fac-0ee97853096e.png)

**Comment by AlsoScratch** [comment]
What application are you using? Looks like it's useful for checking local forms.

**Comment by be5invis** [comment]
DTL OTMaster.
