### ISSUE TITLE
Curlies are not curly

### ISSUE THREAD

**Issue by dayfuaim** [be5invis/Iosevka#407]
* Your font version: 3.0.0-alpha4
* Your font variant: TermLig Curly (both Slab not Normal)
* Your operating system (name and version): macOS 10.13.6
* Your application using Iosevka: iTerm

Describe your problem here. Provide pictures and files if necessary.
![Снимок экрана 2020-01-14 в 17 14 03](https://user-images.githubusercontent.com/1274699/72351583-ad41a480-36f1-11ea-8a05-a4399d1a46a7.png)
(see the "k" italic)
This behavior just appeared in alpha4. alpha3 was correct ("curly" is curly)

**Comment by be5invis** [comment]
Should be a regression I fixed yesterday night :)

**Comment by dayfuaim** [comment]
- Your font version: 3.0.0-alpha**5**
- Your font variant: TermLig Curly (both Slab not Normal)
- Your operating system (name and version): macOS 10.13.6
- Your application using Iosevka: iTerm, Fonts

![Снимок экрана 2020-01-19 в 19 03 21](https://user-images.githubusercontent.com/1274699/72684087-908cde80-3aee-11ea-9489-138d378b12ef.png)

Curly "k" is _still_ not curly.

Re-opening the issue.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/72689979-60344880-3acc-11ea-9671-c5d86caadda3.png)
This is the `k` in `iosevka-term-lig-curly-slab-italic.ttf`.
![image](https://user-images.githubusercontent.com/240091/72689995-82c66180-3acc-11ea-9072-7a2b71c92492.png)
This is the corresponded straight form.

**Comment by be5invis** [comment]
The two letterforms of `k` looks pretty similar if you have serifs. This was pretty a by-design and comes form the very first version that adds Slab.

**Comment by be5invis** [comment]
I'd like to make them look like this.
Left: Straight
Right: Curly
![image](https://user-images.githubusercontent.com/240091/72690212-0f721f00-3acf-11ea-85ab-23c239ff8ecb.png)

**Comment by dayfuaim** [comment]
Curly here looks better.
But at small sizes (..16pt) straight and curly forms look almost indistinguishable. :(
