### ISSUE TITLE
Slab numbers '1' and '7' are not slab.

### ISSUE THREAD

**Issue by dayfuaim** [be5invis/Iosevka#408]
* Your font version: 3.0.0-alpha4
* Your font variant: TermLig Curly (both Slab not Normal)
* Your operating system (name and version): macOS 10.13.6
* Your application using Iosevka: iTerm

Describe your problem here. Provide pictures and files if necessary.
![Снимок экрана 2020-01-14 в 17 12 42](https://user-images.githubusercontent.com/1274699/72351808-1b866700-36f2-11ea-8235-e77090afddf9.png)
See "1" and "7".
This is only in alpha4. alpha3 (and all previous versions) was correct.

**Comment by be5invis** [comment]
Should be a regression I fixed yesterday night :)
