### ISSUE TITLE
Russian Z (З) is indistinguishable from number 3

### ISSUE THREAD

**Issue by habamax** [be5invis/Iosevka#411]
* Your font version: 3.0.0 alpha 5
* Your font variant: Iosevka, Iosevka Extended
* Your operating system (name and version): Win10
* Your application using Iosevka: Gvim, vim

Is it possible to change either number 3 or russian Z (З) to be sure they are different?

![image](https://user-images.githubusercontent.com/234774/73049039-3c864f00-3e8c-11ea-8e7e-4871bbbd7579.png)

This is Consolas, for example:

![image](https://user-images.githubusercontent.com/234774/73049118-8e2ed980-3e8c-11ea-9e80-db40d208c0e3.png)

And this is PT Mono:

![image](https://user-images.githubusercontent.com/234774/73049169-b9b1c400-3e8c-11ea-8d4e-a8b954fdd973.png)

Thank you!

**Comment by chelovechishko** [comment]
As per https://github.com/be5invis/Iosevka/issues/184 you could use
`v-three-flattop` selector.

**Comment by habamax** [comment]
thx @chelovechishko I have missed it (although tried to search first)

**Comment by habamax** [comment]
So now I have to find a way to build the font myself :)

**Comment by alexeyten** [comment]
You could use ss11 variant or build your own

**Comment by habamax** [comment]
> You could use ss11 variant or build your own

It has non slashed 0 unfortunately.

**Comment by alexeyten** [comment]
In that case you have only one option left 😊

https://github.com/be5invis/Iosevka/blob/master/README.md#building-from-source

Well, actually you could try to use opentype stylistic set, but I'm not sure how to do this in gvim and/or in windows

**Comment by habamax** [comment]
> In that case you have only one option left 😊

yep, already cloned, reading now :)

**Comment by habamax** [comment]
It wasn't hard:

![image](https://user-images.githubusercontent.com/234774/73055148-2e8cfa00-3e9d-11ea-8774-2d4f93c24517.png)


Love it!
