### ISSUE TITLE
Iosevka Extended is not recognized in Windows Terminal Preview

### ISSUE THREAD

**Issue by habamax** [be5invis/Iosevka#412]
* Your font version: (Current Alpha, and Current Git)
* Your font variant: Default
* Your operating system (name and version): Windows 10
* Your application using Iosevka: Windows Terminal Preview

![image](https://user-images.githubusercontent.com/234774/73120422-ca426700-3f7e-11ea-9a6b-33fa64d12056.png)
 
Regular Iosevka works, but if you put "Iosevka Extended" it fallbacks to Consolas (which is default for the terminal)

![iosevka-extended-win-terminal](https://user-images.githubusercontent.com/234774/73120473-58b6e880-3f7f-11ea-8818-1f4ed25bce6e.gif)

**Comment by be5invis** [comment]
Should be a WT problem. Iosevka use standard WWS font selection while WT does not support specifying width.
Closed as external.
