### ISSUE TITLE
Difference between Aile and Sparkle

### ISSUE THREAD

**Issue by IceMan81** [be5invis/Iosevka#413]
Could you add a write up about the difference between Aile and Sparkle? It looks like it got some stylistic differences in additional to being a proportional variant.

**Comment by be5invis** [comment]
Shape of `r`, `f` are different. They grow serif in Sparkle to mimick iA Writer's fonts.

**Comment by IceMan81** [comment]
@be5invis Thank  you, noticed that after I asked the question. 
Also noticed that the spacing is different,Sparkle is similar to Etoile.
