### ISSUE TITLE
ơ with diacritics *still* has the gap

### ISSUE THREAD

**Issue by AlsoScratch** [be5invis/Iosevka#414]
* Your font version: 3.0.0 beta 1
* Your font variant: 02 term
* Your operating system (name and version): macOS 10.15.2

<img width="425" alt="Screenshot 2020-01-27 at 7 01 56 PM" src="https://user-images.githubusercontent.com/48752273/73169712-ab3b0500-4137-11ea-9e10-815e1d1cae28.png">

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/73235396-31a91400-4143-11ea-9ba2-b850f66c7e2a.png)
Should be a problem in automatic accent generation. Here is the fixed version.
