### ISSUE TITLE
Ḑḑ diacritic should look like a comma

### ISSUE THREAD

**Issue by AlsoScratch** [be5invis/Iosevka#417]
It should look like a comma just like `ķ`, `ļ`, `ņ`, etc. (That's what I've heard at least)

**Comment by be5invis** [comment]
These letters are named `Latin Capital Letter D with Cedilla` and `Latin Small Letter D with Cedilla`, so using cedilla is conformal to Unicode.
Per wikipedia, this should only become "D-comma" in Livonian, but [there isn't any OpenType language tags for Livonian](https://docs.microsoft.com/en-us/typography/opentype/spec/languagetags).

**Comment by AlsoScratch** [comment]
Not the case with `ķ`, `ļ`, `ņ`, etc. apparently.

**Comment by AlsoScratch** [comment]
Here's [Wikipedia](https://en.wikipedia.org/wiki/%E1%B8%90):

> Ḑ (minuscule ḑ) or D-cedilla is a letter of the Latin alphabet, consists of the letter "D" with the cedilla under it. The letter stands for the voiced palatal plosive [ɟ] in the Livonian alphabet. The cedilla traditionally looks like a comma below in Livonian use. In other use, like UNGEGN romanizations, the cedilla is like a regular cedilla.

**Comment by AlsoScratch** [comment]
Well, what else is this letter used for other than the Livonian language?

**Comment by AlsoScratch** [comment]
> so using cedilla is conformal to Unicode.

Could you provide me a reference to this?

**Comment by be5invis** [comment]
https://en.wikipedia.org/wiki/%E1%B8%90

**Comment by AlsoScratch** [comment]
The only other thing it mentions is UNGEGN romanizations but I haven't been able to find any that use this letter.

**Comment by AlsoScratch** [comment]
Pretty sure a lot of fonts use a comma shape as this letter's use in Livonian is (probably) more important than its other uses.

**Comment by AlsoScratch** [comment]
> These letters are named `Latin Capital Letter D with Cedilla` and `Latin Small Letter D with Cedilla`, so using cedilla is conformal to Unicode.
> Per wikipedia, this should only become "D-comma" in Livonian, but [there isn't any OpenType language tags for Livonian](https://docs.microsoft.com/en-us/typography/opentype/spec/languagetags).

In my opinion, even if there was a tag for Livonian, not all apps have an easy way to use OpenType tags so we can't always depend on OpenType.
For this reason, even though there are tags for Latvian many fonts still have the diacritics in `ģ`, `ķ`, `ļ`, `ņ` appear as a comma by default.

You say it's "conformal to **Unicode**", but does Unicode themselves _actually_ state that the d-cedilla shape should be the way it looks in your font?

**Comment by AlsoScratch** [comment]
Could you please provide me a source where _**Unicode**_ actually said this?

**Comment by be5invis** [comment]
@AlsoScratch 
Interesting things are found.
In Unicode 2.0's code chart, this letter is indeed using cedilla:
![image](https://user-images.githubusercontent.com/240091/76156982-4f10bc80-60b7-11ea-8135-69e43d031699.png)
There's no online archives of code charts for 3.0 but for 4.0, it is changed to D-comma in the sample.
