### ISSUE TITLE
Can you make new style like this font?

### ISSUE THREAD

**Issue by nobk** [be5invis/Iosevka#418]
This font non-free but very good.
![nf](https://user-images.githubusercontent.com/4659870/74052868-ad457380-4a15-11ea-86c4-ec92731df98b.PNG)

**Comment by nsemrau** [comment]
It would be helpful to know the name of this font.

**Comment by nobk** [comment]
LucidaTypewriterStd.otf

**Comment by nobk** [comment]
LucidaSansTypewriterStd.otf

**Comment by zero00072** [comment]
It's just like this:
design = ["cv05", "cv09", "cv14", "cv21", "cv30", "cv45"]

**Comment by nobk** [comment]
Thanks, but number '1' and Lowercase 'l' become indistinguishable, please make a lucida style number '1'.

**Comment by nobk** [comment]
Version 3.0.0-beta.3 preview picture update with "cv51" number '1' v-one-base.
But download font s13 zip and install, the number '1' still "cv50" v-one-nobase like previous version.

**Comment by be5invis** [comment]
@nobk preview images are from master branch, which has the update.
