### ISSUE TITLE
Line jumps up and down in eclipse

### ISSUE THREAD

**Issue by alankila** [be5invis/Iosevka#42]
The issue appears to be related to Eclipse's syntax highlighting choosing to render text in a bold font.

E.g. if I type a line of Java code like this:

   intxxx;

then it's written near the top of the row. When I change it like this:

   int xxx;

the syntax highlighting kicks in, bolds the "int", and the xxx jumps couple of pixels down on the row. I do not know enough about typography to hint for the cause. I have seen the problem on both Iosevka and Iosevka Slab 1.4.3. This issue was not present in 1.2.0 version of the font.

**Comment by be5invis** [comment]
Looks related to Java's rasterizer. I do not see such problem in Windows GDI, DirectWrite and Freetype.

**Comment by alankila** [comment]
The story is somehow more complicated. Eclipse does not use Java's rasterizer, but some kind of native toolkit rendering technology called SWT. The issue is probably somewhere there, or in the way the fonts now define metadata which indicates the sizes of the bounding boxes for the glyphs or whatever. As I said, I don't know what is going on, only that it worked before and no longer does.

For the record, I am using OS X 10.11.2 and have Iosevka family added into various programs. Unfortunately, so far it is only Eclipse that shows any problems.

**Comment by be5invis** [comment]
Many Java programs cannot handle TrueType references / hints well. Maybe I should create a un-referenced un-hinted version in 1.5.0.

**Comment by alankila** [comment]
I fixed the issue, after a fashion.

I noticed that in the Apple's Font Viewer, not all fonts in this family appeared to be of the exactly same size. Basically the viewer maximizes the font somehow into the view area, and I noticed as I scrolled through the  various fonts that some of them did not render in the same positions, suggesting that in some sense these fonts or some of their glyphs had different dimensions. After identifying this as a possible cause, I deleted all fonts which did not render at exactly the same coordinates. I was left with these:

iosevka-extralight.ttf
iosevka-extralightitalic.ttf
iosevka-extralightoblique.ttf
iosevka-italic.ttf
iosevka-light.ttf
iosevka-lightitalic.ttf
iosevka-lightoblique.ttf
iosevka-mediumitalic.ttf
iosevka-mediumoblique.ttf
iosevka-oblique.ttf
iosevka-regular.ttf
iosevka-thin.ttf
iosevka-thinitalic.ttf
iosevka-thinoblique.ttf

I had to delete most of the bolder fonts, but the issue in Eclipse is now gone. I mostly use the "Light" variant of the font, and Eclipse uses some algorithm and still finds a bold font it can use, possibly it uses the "regular" as the bold font in this case. (I do not know how this is chosen.)

**Comment by be5invis** [comment]
Iosevka's metrics are identical acrlss all weights. Perhaps some Mac-only behavior?

**Comment by alankila** [comment]
Hmm yes, and in above I meant to write "medium" and not the "regular" as the font which I suspected Eclipse chose, because according to my testing the regular variant renders consistently with the lighter fonts.

In any case, it does appear that the Iosevka and Iosevka Slab families are not completely compatible with OS X, and the issue is probably not related to Java.

**Comment by be5invis** [comment]
@alankila Does [this version](http://7xpe0v.com1.z0.glb.clouddn.com/iosevka-20151224c.7z) solve the problem?
I and @clerkma find out that OSX actually cares about the descender, maybe related to the "broken underline" feature introduced recently.

**Comment by alankila** [comment]
Almost! I think Iosevka Slab is now perfect, with every glyph keeping their exact positions in this family. However, the Iosevka family still has slightly increasing sizes as the font weight increases, but that increase is quite subtle -- in order of few % at most -- and in practice I can't see any actual rendering issue anymore in Eclipse (or any other application).

As far as I am concerned, this issue is now solved, though for completeness it would still be good idea to try to work out why there is still a slight difference between the fonts in that family. The font sizes, as I can see them, look like this:

- extralight, light, light, thin, regular, oblique, italic are all the same size
- medium, bold, heavy are the same size, though bit larger than the former set.

I am a bit confused about the existence of the medium weight font. It seems to be a loner, as it is slightly heavier than regular, and I think the oblique and italic are the same weight as regular. Therefore, I don't think this particular font has corresponding slanted/oblique versions.

**Comment by alankila** [comment]
I'm sorry that I had to update the prior comment.

**Comment by be5invis** [comment]
@alankila The sidebearings of glyphs is consistently reducing form thin to heavy to keep shapes "looks like in the same size". However I think the particular issue you opened is solved by the latest push.

**Comment by be5invis** [comment]
@alankila Have you tried to clean re-install the version I provided in the previous comment and see whether it is fixed?

**Comment by alankila** [comment]
Hey, uninstalling the font completely and reinstalling them really did appear to help. I'm very confused now as to why that might be. I also had to restart the font viewer before it apparently loaded the most recent version of the font -- maybe it cached it by family name and wasn't expecting me to install multiple versions of it. Going to check this a bit later, something came up right now.

**Comment by alankila** [comment]
Yeah, I think it looks good now. The glyphs seem the same size now. The only minor potential issue is that the stroke of the font pushes the glyph outline downwards in the glyph box because the stroke is not centered to the outline, but merely starts on the same height and extends downwards to make the glyph heavier, e.g. extralight would appear to be higher in the glyph box than, say, heavy, because the top of the outline stays the same. I don't know if that is a problem though.

**Comment by be5invis** [comment]
Hmmm maybe Java-specific rendering issue.
Closed.
