### ISSUE TITLE
Unicode 13.0 support

### ISSUE THREAD

**Issue by ChiefMikeK** [be5invis/Iosevka#420]
[Unicode 13.0.0](https://www.unicode.org/versions/Unicode13.0.0/) `¯\_(ツ)_/¯`

## The _final_ draft is out as of early February and will be released on March 10, 2020
Symbols for Legacy Computing Range: **1FB00–1FBFF**   
Additional **215** new characters from historic _terminal_ programs.   
Chart U130-1FB0.pdf is available 
> IMHO this block should be added at a minimum to this and other terminal/tech minded Monospace-font$ :neckbeard:
***
![Image](https://github.com/ChiefMikeK/feedback/raw/master/img/U130-1FB00.png)

**Comment by be5invis** [comment]
I plan to have full support. Well there's already a lot 😃

**Comment by ChiefMikeK** [comment]
### Mind the pairings `ʕ •́؈•̀ ₎ `   
![Image](https://github.com/ChiefMikeK/feedback/raw/37dad62c16d18f024d1912ac55634e75cb4716ae/img/1fb00-seqnce.png)
- 1FBB2 🮲 LEFT HALF RUNNING MAN paired with
- 1FBB3 🮳 RIGHT HALF RUNNING MAN, faces to the right   
the Apple II documentation refers to these characters as “Running Man” →1F3C3 🏃 runner.  
:neckbeard:

**Comment by be5invis** [comment]
WIP:
![image](https://user-images.githubusercontent.com/240091/74112798-598d7400-4b54-11ea-9e3e-48b115e75120.png)

**Comment by be5invis** [comment]
Landed in beta 3. Closed.
