### ISSUE TITLE
Different widths for both italic and oblique bold weights in private-build-plans.toml

### ISSUE THREAD

**Issue by wimstefan** [be5invis/Iosevka#425]
* Your font version: git dev branch commit 0150b80c53cdc21fc7fa83bd60c4d71f8059770f
* Your font variant: Iosevka Slab
* Your operating system (name and version): Gentoo ~amd64
* Your application using Iosevka: kitty, awesome

If you have problem when building Iosevka, please provide these information:

* Your Node.js version: 13.9.0
* Your _otfcc_ version: git latest commit
* Your `parameters.toml`, paste if modified:
```
cap = 755
xheight = 550
```
* Your `private-build-plans.toml`, if present:
```
[buildPlans.iosevka-slab]
family = "Iosevka Slab"
design = [ "term", "slab", "shape-curly-bar", "v-f-tailed", "v-g-opendoublestorey", "v-k-curly", "v-m-shortleg", "v-q-taily", "v-r-serifed", "v-capital-r-curly", "v-eszet-traditional", "v-v-curly", "v-w-curly", "v-y-cursive", "v-capital-y-curly", "v-x-cursive", "v-three-flattop", "v-tilde-high", "v-asterisk-high", "v-paragraph-high", "v-caret-high" ]

[buildPlans.iosevka-slab.s-italic]
width = 1.152

[buildPlans.iosevka-slab.s-oblique]
width = 1.152

```
---

With my private Iosevka Slab build the regular and bold weight look really very nice but in italic and oblique variants (bold weight) some characters are cut off in the width: `g`, `p`, `M` and I may have forgotten some ...
Is it possible to make bold weights of italic and oblique a bit wider?

**Comment by wimstefan** [comment]
Testing it in alacritty the problem is not present ... so it seems there's more an issue with kitty.
Sorry for the noise :-/

**Comment by Sleepful** [comment]
I'm also using [kitty](https://github.com/kovidgoyal/kitty) and bolds get cut-off

**Comment by wimstefan** [comment]
You could try 
```config
adjust_column_width 105%
```
in your kitty.conf and see if that makes a difference ...

**Comment by Sleepful** [comment]
maybe related to https://github.com/be5invis/Iosevka/issues/1262#issuecomment-990300095
I had to set the bold font separately because it doesn't come in the same "family"
```
font_family Iosevka Medium
bold_font Iosevka Extrabold
```
Otherwise kitty doesn't find "Bold" for "Medium"
