### ISSUE TITLE
Usage in Visual Studio Code?

### ISSUE THREAD

**Issue by hl2guide** [be5invis/Iosevka#426]
* Your font version: beta 3
* Your font variant: 01-iosevka-3.0.0-beta.3.zip, iosevka-ss03-3.0.0-beta.3.zip
* Your operating system (name and version): Windows 10
* Your application using Iosevka: Visual Studio Code

I'm no font pro, but what variant type should I use in Visual Studio Code? Hinted or unhinted?

I've tried: 01-iosevka-3.0.0-beta.3.zip, iosevka-ss03-3.0.0-beta.3.zip

Neither worked in Visual Studio Code but did show in Notepad.

**Comment by cata0309** [comment]
Just enter the settings and type the name of the font 'Iosevka' should work without problems or you can open the settings.json and enter the editor.fontFamily option to be Iosevka Medium or any weight you want !

**Comment by hl2guide** [comment]
For me I have:
![1](https://user-images.githubusercontent.com/17044982/75281870-280aed00-5864-11ea-9c79-fd75796e77ad.PNG)
![2](https://user-images.githubusercontent.com/17044982/75281875-293c1a00-5864-11ea-923f-5c8bdd3a5c21.PNG)
Resulting in:
![3](https://user-images.githubusercontent.com/17044982/75281877-2a6d4700-5864-11ea-94b4-fdbee7b52674.PNG)

**Comment by cata0309** [comment]
Just insert the name of the font without single quotes

**Comment by hl2guide** [comment]
I've tried that too,:
![4](https://user-images.githubusercontent.com/17044982/75282100-8e900b00-5864-11ea-90d9-a3c5b3889a32.PNG)
same result.

**Comment by cata0309** [comment]
Could you share your settings.json ?

**Comment by hl2guide** [comment]
sure: https://gist.githubusercontent.com/hl2guide/5c9b7975bcfbb67d10638d77d89f2f82/raw/2920a22982aadbec36e8067507139c436d6b0ac0/settings.json

**Comment by cata0309** [comment]
Try to delete both families of Iosevka and reinstall them and try again

**Comment by be5invis** [comment]
Iosevka should have only 54 styles in one family, but I saw 60 in your screenshot, so it may be a mis-installation or something.
To do a full delete:
 * Remove all the fonts from **control panel**.
 * Under the following registry keys, delete all items starting with `iosevka`/`Iosevka`:
   * `HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\Fonts`
   * `HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Fonts`
 * Delete all the font files starting with `iosevka`/`Iosevka` under the following location (you may need CLI to do this):
   * `%userprofile%\appdata\local\microsoft\windows\fonts`
   * `%windir\fonts`
 * Restart PC and reinstall the fonts.

**Comment by hl2guide** [comment]
thanks for replies, I'll try that out soon 👍

**Comment by mashwell** [comment]
Also, by default Visual Studio Code does not display ligatures -- you might want to add `"editor.fontLigatures": true` to your settings.json. Optional, of course, but I quite enjoy Iosevka's extensive ligature support and I find it enhances readability.
The latest v3 .ttc-format font works fine on my machine with VS Code, fwiw.

**Comment by AnrDaemon** [comment]
Answering question directly, you should use whatever you like more.

As to "what to enter as font name", it's simple: Open control panel - fonts, locate the group for your Iosevka font and ENTER THE FONT NAME LITERAL AS YOU SEE IT THERE.
F.e. in my case it is `Iosevka Term Curly Slab`.
![image](https://user-images.githubusercontent.com/6532485/76970759-649aa780-693d-11ea-8076-02fba4033aa1.png)

Though, my actual font configuration is a bit more involved.
![image](https://user-images.githubusercontent.com/6532485/76970985-aa577000-693d-11ea-9dc5-76b2f67245a5.png)

**Comment by sharpjs** [comment]
I've been meaning to report that the `Extended` variants do not work in VS Code.  Once I append `Extended` to the font family name, VS Code starts using the next font in the list.

![image](https://user-images.githubusercontent.com/708461/80781045-d3b31080-8b25-11ea-852b-1a6d8e5db6d2.png)

![image](https://user-images.githubusercontent.com/708461/80780971-9d759100-8b25-11ea-8e5a-32f89e554058.png)

Should I post this in a separate issue?

**Comment by AnrDaemon** [comment]
@sharpjs which file did you download/install ?

**Comment by be5invis** [comment]
@sharpjs It's a dupe of #479

**Comment by sharpjs** [comment]
Ah, thanks @be5invis.  Nothing to see here then.  I'll submit the issue to VS Code.

@AnrDaemon it was `iosevka-term-ss04-3.0.0-rc.8.zip`

**Comment by be5invis** [comment]
@sharpjs There's already an issue there (vscode#95493).

**Comment by AnrDaemon** [comment]
So, this is probably why I can't see how "extended" it is? Because as it is, the font is unintelligible. I very much like the overall font design, it is close to my preferred "Hellfont Cyr" raster font, but it is way too narrow. My eyes are getting weary too fast when using it.

**Comment by whyboris** [comment]
I had the same issue. On my Mac I checked the `Font Book` application to see that the font was installed. Turned out it was named `Iosevka Fixed`. I updated VS Code with the full name (in single quotes) and it worked 🎉

**Comment by chmielcode** [comment]
> 
> 
> @sharpjs There's already an issue there (vscode#95493).

@be5invis The iosevka extended font variant is called "expanded" in build-plans, so "Iosevka ... Expanded" works in vscode, but "Iosevka ... Extended" doesn't, which is confusing.

**Comment by AnrDaemon** [comment]
Doesn't look like it changes anything. Same font look with and without "Expanded". (I mean, it works, the right font selected, but it's still too condensed.)

**Comment by sharpjs** [comment]
> Doesn't look like it changes anything.

🤷 Works for me.

![image](https://user-images.githubusercontent.com/708461/84577101-3971f980-ad6e-11ea-8ae9-ed15379de3f7.png)

![image](https://user-images.githubusercontent.com/708461/84577134-8bb31a80-ad6e-11ea-8701-e8d5e216e55a.png)

> it works, the right font selected, but it's still too condensed.

Have you considered that you might not like Iosevka?  Plenty of other fonts out there.  IMO, JetBrains Mono is similar, but less condensed and a bit heavier.

**Comment by AnrDaemon** [comment]
> Works for me.

Thanks for the images, I think I understand, what's happening. I only have Extended variant installed. So that `Iosevka Fixed Curly Slab` and `Iosevka Fixed Curly Slab Expanded` choose same font variant.

> Have you considered that you might not like Iosevka? Plenty of other fonts out there. IMO, JetBrains Mono is similar, but less condensed and a bit heavier.

Sans serif is extremely taxing on the human eye. 
Iosevka is the only high quality slabbed monospaced font I have found. But it's too condensed even if I use 1px letter spacing. I can't imagine how anybody could consider these barcodes readable. Expanded looks a little bit better. But just a little.
