### ISSUE TITLE
JetBrains Mono variant

### ISSUE THREAD

**Issue by cata0309** [be5invis/Iosevka#434]
Hello !
I know that Iosevka has a lot of variants, would a JetBrains Mono variant be hard to implement ?
The letter 'u' should be the only one to be reimplemented.
![image](https://user-images.githubusercontent.com/35623921/76076203-0c5fbf00-5fa7-11ea-88ba-ebe01a21a63d.png)
Thank you !

**Comment by AndydeCleyre** [comment]
I think this is a "duplicate" of #140, where you can request a `u` and `U` variant.
