### ISSUE TITLE
New website is not responsive and displays poorly on mobile

### ISSUE THREAD

**Issue by Elarcis** [be5invis/Iosevka#438]
Opening the website on my smartphone gives a very poor UX. Without creating a mobile version of the customisation tool, it’d be nice that the rest of the page adapts to smaller resolutions.

![image](https://user-images.githubusercontent.com/990841/76226174-c82a2400-621d-11ea-8ccc-64da45a8b19c.png)

![image](https://user-images.githubusercontent.com/990841/76226353-0aebfc00-621e-11ea-9538-3e715a3fd29e.png)

![image](https://user-images.githubusercontent.com/990841/76226415-20f9bc80-621e-11ea-89c4-3a868a4e926f.png)

**Comment by be5invis** [comment]
@Elarcis I made some updates to the website so it should work (much) better now.
