### ISSUE TITLE
Circled numbers clip

### ISSUE THREAD

**Issue by paolobolzoni** [be5invis/Iosevka#440]
![Circled Numbers](https://user-images.githubusercontent.com/1133562/76371823-e6f3fc00-637e-11ea-94cf-35add29c47d6.png)

Yet, in the [https://typeof.net/Iosevka/|official page] it shows the Ⓨ character correctly spaced or compressed to stay in its space.

**Comment by be5invis** [comment]
Use Iosevka Term. Its circled alphanumerics are narrow.
In the new packaging model Iosevka Term is designed for terminals.

**Comment by paolobolzoni** [comment]
I am using my own [variant (see private build toml)](https://github.com/paolobolzoni/useful-conf/raw/master/iosevka/private-build-plans.toml.normal), should I replace `no-ligation` with `sp-fixed`?

**Comment by be5invis** [comment]
You can use `sp-term` if you want ligation and your terminal emulator can use it, or `sp-fixed` if not.
`sp-term` will change these characters' width.
`sp-fixed` will further remove ligation and all the "wide" glyphs. Why remove wide glyphs? Because fontconfig needs that to treat it as "monospace" font.

**Comment by paolobolzoni** [comment]
I don't understand, I am using the following private build toml and the result is the same. I changed the font name to be sure it is not some kind of caching.
What's wrong?

```
[buildPlans.iosevka-test]
family = "Iosevka test"

design = [ "sp-fixed", "cv01", "cv13", "cv17", "cv19", "cv20", "cv23",
"cv24", "cv26", "cv27", "cv29", "cv33", "cv35", "cv37", "cv38", "cv41", "cv43",
"cv44", "cv46", "cv49", "cv51", "cv52", "cv56", "cv58", "cv62", "cv65",
"cv66", "cv69", "cv71", "cv74", "cv76", "cv78", "cv81", "cv83", "cv87" ]

italic = [ "italic-only", "cv02", "cv04", "cv34", "cv40", "cv42", "cv53",
"cv70" ]

hintParams = ["-a", "sss"]


[buildPlans.iosevka-test.weights.light]
shape = 200
menu  = 300
css   = 300

[buildPlans.iosevka-test.weights.regular]
shape = 500
menu  = 400
css   = 400

[buildPlans.iosevka-test.weights.bold]
shape = 700
menu  = 700
css   = 700

[buildPlans.iosevka-test.slants]
upright = "normal"
italic = "italic"
```

**Comment by be5invis** [comment]
@paolobolzoni This config should work.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/76378132-ea996b80-6309-11ea-9640-cd8d1ec4857f.png)
These are the results.

**Comment by paolobolzoni** [comment]
What font viewer are you using?

**Comment by paolobolzoni** [comment]
It seems I had to update my git code copy. Thanks
