### ISSUE TITLE
Add Bashkir ҡ

### ISSUE THREAD

**Issue by AlsoScratch** [be5invis/Iosevka#441]

**Comment by AlsoScratch** [comment]
Pretty sure all we need is uppercase and lowercase of this letter and it supports Bashkir. Is it difficult to add?

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/78105097-3d17f600-73a5-11ea-88df-c6837f231e02.png)
![image](https://user-images.githubusercontent.com/240091/78105511-2a51f100-73a6-11ea-8f45-e50a856834de.png)

**Comment by AlsoScratch** [comment]
On the bottom row, the 8th character from the left is not curly.

**Comment by be5invis** [comment]
@AlsoScratch Fixed in dev.
