### ISSUE TITLE
[website] R should come before Y

### ISSUE THREAD

**Issue by AlsoScratch** [be5invis/Iosevka#445]
<img width="276" alt="Screenshot 2020-03-13 at 4 04 05 PM" src="https://user-images.githubusercontent.com/48752273/76601668-59fa9f80-6544-11ea-9c90-e11d2aff374c.png">
Not trying to sound overly picky, but all the others are in alphabetical order.

**Comment by be5invis** [comment]
Ahh it is fixed in the latest commit.
Will be published in the next version.
