### ISSUE TITLE
About custom feature tags

### ISSUE THREAD

**Issue by AlsoScratch** [be5invis/Iosevka#446]
So I went to check on [OpenType feature tags](https://docs.microsoft.com/en-us/typography/opentype/spec/featuretags) and read the part on custom feature tags, described as 'vendor tags':

> The tag space of tags consisting of **_four uppercase letters_ (A-Z) with _no punctuation, spaces, or numbers_**, is reserved as a vendor space. Font vendors may use such tags to identify private features. For example, the feature tag PKRN might designate a private feature that may be used to kern punctuation marks. Interoperability of private features is not guaranteed.

Unless tags that begin with `X` (and perhaps do not contain punctuation or spaces) are actually reserved even if they contain numbers, I'm afraid `XJS0`, `XFS0` etc. may be breaking the rules.

**Comment by alexeyten** [comment]
> By convention, registered feature tags use four lowercase letters

So `XFS0` in a gray zone. Neither registered nor private. I doubt there would be any problem.

**Comment by AlsoScratch** [comment]
@alexeyten [Language tags](https://docs.microsoft.com/en-us/typography/opentype/spec/languagetags) use capital letters; I'm not sure if that's a separate system or not.

**Comment by AlsoScratch** [comment]
@be5invis Are language tags a separate system from feature tags? If so, then the current ligation tags can stay.

**Comment by be5invis** [comment]
@AlsoScratch Language tags are different from script/feature tags and they are using three capital letters for most cases. Like Turkish is described in `TRK `.
I'd like to change the padding to letter "X" and use more descriptive language names.

**Comment by AlsoScratch** [comment]
Some contain numbers like `KAB0`. None of them start with `X`, but I wish to know if that's because tags that begin with `X` and (possibly) only contain letters and/or numbers also fall under this so-called "vendor space".

**Comment by be5invis** [comment]
@AlsoScratch Language tags are very differen from feature tags.
I will follow this section: 

> The tag space of tags consisting of four uppercase letters (A-Z) with no punctuation, spaces, or numbers, is reserved as a vendor space. Font vendors may use such tags to identify private features. For example, the feature tag PKRN might designate a private feature that may be used to kern punctuation marks. Interoperability of private features is not guaranteed.

**Comment by AlsoScratch** [comment]
So now what are we going to start calling the character variant tags if we exceed 99 character variants?

**Comment by be5invis** [comment]
@AlsoScratch Maybe `CVAA`, `CVAB`, ..., `CVZZ`.
