### ISSUE TITLE
Sources of specific version?

### ISSUE THREAD

**Issue by van-de-bugger** [be5invis/Iosevka#45]
Sorry for probably stupid question, but how to get *sources* of specific version? For example, 1.5.4?

Let me explain:

    $ git clone https://github.com/be5invis/Iosevka.git
    $ cd Iosevka
    # Ok, I have the latest sources.
    $ git tag
    ...
    v1.5.3
    v1.5.4
    v1.5.5
    # Ok, I see bunch of tags.
    # Let me checkout version 1.5.4:
    $ git checkout v1.5.4
    # Oops, now I have prebuilt ttf files in working directory but NO sources.

**Comment by be5invis** [comment]
All tagged commits are in the `release` branch, which contain the TTF files only.
You should check the commits in `master` branch, find out the commit that `parameters.toml` changes version number.
Closed.

**Comment by van-de-bugger** [comment]
> You should check the commits in master branch, find out the commit that parameters.toml changes version number.

Such a way cannot be automated (at least, easily). Could you please also tags master branch?

**Comment by be5invis** [comment]
@van-de-bugger Perhaps I will include source in release branch in 1.7.
