### ISSUE TITLE
Peseta sign

### ISSUE THREAD

**Issue by throwaway571** [be5invis/Iosevka#451]
The glyph for the peseta sign U+20A7 in Iosevka 3.0.0-rc1 is a horizontally squashed `Ps`. The Spanish peseta never had a standardized symbol, but Spanish typewriters often had a `Pts` monogram, and that was the reference glyph used in the video card ROM for the IBM PC, which eventually became IBM’s codepage 437. I know that forcing three characters into the space of one can get unreadable, so I don’t know if this was by design, or if it was just an oversight.

**Comment by be5invis** [comment]
It is by design, and using `Ps` is also because that Iosevka is not wide enough, and an old font (cannot remember what it is I was using is designed it like `Ps`.

**Comment by ChiefMikeK** [comment]
## Mockup with metrics - combine peseta sign with subscript t
![Image]( https://github.com/ChiefMikeK/feedback/raw/master/img/PESETA_SIGN(mockup).png)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/85217804-4e8bf100-b349-11ea-9ec6-c511bd86a76a.png)

**Comment by throwaway571** [comment]
@be5invis Just a heads up: the P with crossbar glyph is a deprecated form based on a mistaken identification with the Philippine peso sign. https://www.unicode.org/L2/L2000/00013-n2156.pdf

You honestly may want to make the peseta sign a double-wide Pts monogram instead.

**Comment by dscorbett** [comment]
@throwaway571, if the peso glyph is wrong for the peseta, I think you should open a new issue, to make sure this gets fixed.

**Comment by ChiefMikeK** [comment]
`¯\_(ツ)_/¯` Personally as in my previous image, I would have gone with the subscript ₜ between the P + s maybe with lesser weight of the t versus heavier  P and s .  
# ₧ₜ Ps + ₜ _overstrike_
