### ISSUE TITLE
Request: alternate glyph for the lowercase eszett

### ISSUE THREAD

**Issue by throwaway571** [be5invis/Iosevka#455]
I’d like to request a third eszett variant, with an s-shaped right half like the one in Consolas, Ubuntu Mono and Source Code Pro.

**Comment by be5invis** [comment]
Could you have a sample image?

**Comment by throwaway571** [comment]
Consolas:
![image](https://user-images.githubusercontent.com/62322214/77231565-06e2a700-6b59-11ea-9701-7daf1a902302.png)

Ubuntu Mono:
![image](https://user-images.githubusercontent.com/62322214/77231488-8328ba80-6b58-11ea-9b2c-6b414301f0a7.png)

Source Code Pro:
![image](https://user-images.githubusercontent.com/62322214/77231501-9a67a800-6b58-11ea-87c9-dd64df7871de.png)

**Comment by AlsoScratch** [comment]
Could we have this now?

**Comment by AlsoScratch** [comment]
I think this would be a nice addition.

**Comment by be5invis** [comment]
This curly shape might be pretty hard to build. The current code for `S` is already very complicated.

**Comment by AlsoScratch** [comment]
What if they join at an angle, like this?
<img width="42" alt="Screenshot 2020-05-24 at 1 29 47 PM" src="https://user-images.githubusercontent.com/48752273/82746487-e20de880-9dc2-11ea-902a-ead34e2421ff.png">

**Comment by be5invis** [comment]
@AlsoScratch This might be more doable.

**Comment by throwaway571** [comment]
It’s also possible to have variants with and without descenders for all three forms, but I’m not sure if it’s worth it.

It looks like the curly ſs-ligature glyph seems to be the most common in monospace fonts, followed by the more angular ſs-ligature from AlsoScratch’s post (as in DejaVu Sans Mono or Menlo). Out of the fonts I have access to, only Courier, Inconsolata and Latin Modern Mono use the Sulzbacher form (cv35), and only IBM Plex Mono uses the blackletter form (cv34).

**Comment by be5invis** [comment]
I think I can add this in (as `CVAC` feature).
![image](https://user-images.githubusercontent.com/240091/82750147-076b0a00-9d63-11ea-9a96-205a9ad51db4.png)

**Comment by AlsoScratch** [comment]
Looks great!

**Comment by throwaway571** [comment]
@be5invis Could I see it in context, preferably next to an `s`? Try _Maßtab_.

**Comment by throwaway571** [comment]
@be5invis I just built the font from the `dev` branch, and I really like the new eszett glyph, but I have a few things to criticize.

1) It looks a bit too light in the bold and black. Right now, the counterspace in the lower bowl is bigger than that of any other letter in the font, even the capital Omega. Don't be afraid to make the slope of the s-curve steeper in bolder faces to accommodate a thicker stroke. 

2) I think it should have a descender in the italic to mirror the existing Sulzbacher glyph.

**Comment by be5invis** [comment]
@throwaway571 @AlsoScratch 
How about this
![image](https://user-images.githubusercontent.com/240091/82769169-324b7180-9de8-11ea-9b32-e2e3edb804f9.png)
![image](https://user-images.githubusercontent.com/240091/82769171-35def880-9de8-11ea-83b5-70ee50e5529c.png)
![image](https://user-images.githubusercontent.com/240091/82769269-a423bb00-9de8-11ea-85bb-0dc7369ca631.png)
![image](https://user-images.githubusercontent.com/240091/82769270-a84fd880-9de8-11ea-8dbd-f7e35b7af0e0.png)

**Comment by throwaway571** [comment]
@be5invis Looks so much better. Thanks!

**Comment by be5invis** [comment]
Close as fixed.
