### ISSUE TITLE
ASK for Request : More slashed zero variant ? 

### ISSUE THREAD

**Issue by GulajavaMinistudio** [be5invis/Iosevka#457]
Thank you for making great font with good readibility. And I have some request and asking some font style. I'm browsing in a blog named **[Alligator IO](https://alligator.io/nodejs/jwt-expressjs/)** , and found that some font is interesting. Especially in their code preview or screenshot.  

Here i provide screenshot for code preview.
![Screenshot_2020-03-24_07-00-23](https://user-images.githubusercontent.com/11639412/77375106-223ef380-6d9f-11ea-98ac-906e2a486ea5.png)

I'm checking with Chrome Devtools, it's like some combination from these fonts : 
Recursive,'DejaVu Sans Mono', 'Bitstream Vera Sans Mono' . 

But after some analyze, it looks like Iosevka Font SS09, that based on Source Code Pro. But the different is, Iosevka SS09 using dotted zero, not slashed zero.

![code](https://user-images.githubusercontent.com/11639412/77375512-4fd86c80-6da0-11ea-8e40-80440534a9a0.png)

And for that, are there any Iosevka font variant that based on source code pro, but using slashed zero ? If no , can you make this variant ? or any step to build it myself ?

**Comment by be5invis** [comment]
Are you requesting a new _stylistic set_ which is SS09 with slashed zero?

**Comment by GulajavaMinistudio** [comment]
Yes , based on SS09 with slashed zero, to make it more readable, i think.

**Comment by be5invis** [comment]
Well it is hard to justify adding stylistic set that matches _your_ need.
I now only have 9 slots available. Perhaps you could try to create a private build.

**Comment by GulajavaMinistudio** [comment]
Thanks, dont worry if you cannot add that. I will try to build that myself.

**Comment by wimstefan** [comment]
I only can confirm that it's much easier to have your own private build at the end of the day.
Thank you so much for this wonderful & incredibly customizable font @be5invis ! 🏽

**Comment by GulajavaMinistudio** [comment]
I got tutorial to build custom iosevka font , from this blog
[https://adam.kruszewski.name/articles/2019-10-27-build-custom-iosevka-font](https://adam.kruszewski.name/articles/2019-10-27-build-custom-iosevka-font/) 

If anyone have other reference, let me know about that. Thanks :)
