### ISSUE TITLE
Reversed slashed zero variant

### ISSUE THREAD

**Issue by lihaoyu1234** [be5invis/Iosevka#458]
希望添加带反斜杠的零（Reversed Slash Zero），就像这个样子：
![image](https://user-images.githubusercontent.com/50037056/77380389-d8d8af00-6d72-11ea-81e5-8816652616b4.png)

**Comment by be5invis** [comment]
Are there any existing fonts using this style?

**Comment by lihaoyu1234** [comment]
I don't know…

But I'm using "Source Code Pro:zero" font in LibreOffice.

**Comment by be5invis** [comment]
SCP with `zero` feature on seems have that.
This is simple though.
