### ISSUE TITLE
Ligatures to emphasize important messages (INFO, WARN, FATAL, NOTE etc)

### ISSUE THREAD

**Issue by IceMan81** [be5invis/Iosevka#461]
I copied the below from the change log for PragmataPro.

all weights: added ligatures to emphasize important message in command line
[INFO] [WARNING] [FATAL] [ERROR] [TRACE] [DEBUG] [WARN] [ERR]

It would be really nice to have similar ligatures, really useful in IDEs if they are available as default.

example:
![image](https://user-images.githubusercontent.com/1093778/77589467-f445d600-6ea8-11ea-9449-e90dd8cc790e.png)

**Comment by iruoy** [comment]
This is from the latest (2019-08-02) PragmataPro changelog:
![image](https://user-images.githubusercontent.com/5859352/78083536-0b5b5b00-73b6-11ea-9b33-12027ec26952.png)

**Comment by IceMan81** [comment]
I think there are more keywords, for example, my screenshot in my previous comment shows NOTE as well. Couldn't find a complete list in the PragmataPro change logs. 
Both # Note and [Note] works!

**Comment by be5invis** [comment]
The `# TOKEN` ligature will cause massive metric change which is not what I like very much. I think it should be under `nalt` umbrella?
Mark as post-3.0.

**Comment by AndydeCleyre** [comment]
IMO, the implementation in those screenshots is sinfully misleading.

Maybe I can get on board with `[ERROR]` looking like a block, but I wouldn't want the edges to be essentially `(` and `)` shaped if they actually represent `[` and `]`.

Having `# ERROR` look like `<ERROR>` is much worse; there's no indication of the `#`, and a deceptive indication of both `<` and `>`.

I think having eye-popping presentations for these is a cool idea, I just hope they can better (more honestly) convey the actual characters underneath.

**Comment by IceMan81** [comment]
@AndydeCleyre I think you are suggesting that the presentation of the ligature should match or atleast give some indication of the actual characters used instead of a completely new representation. If so, I think that makes sense, thought I'm not sure how you would make that a reality. 

The way I think about these ligatures are that they are meant to present _intent_. So if intent is clear from the presentation, then it has achieved its goal! There are typography purists who would argue that ligatures in programming fonts are a bad idea, because ligature substitution is dumb and do not take semantic context into consideration. We are beyond that here!

**Comment by AndydeCleyre** [comment]
Yeah I'm not sure if it's something that belongs *in* the font rather than the editor/displayer, but either way the best form of it I can think of is simple inversion (AKA "reverse" or "standout"):

![image](https://user-images.githubusercontent.com/1787385/78462129-30451c00-769d-11ea-90ff-be9c5a701f89.png)

```console
$ print -P '%S[TODO]%s live your life\n%S[ERROR]%s to live a life of others\nTo forget love is %S[FATAL]%s\n%S# TODO%s live your life\n%S# ERROR%s to live a life of others\nTo forget love is %S# FATAL%s'
```

For extra fanciness, a little corner-rounding of the bg could be fine.

**Comment by al2me6** [comment]
I can see this leading to odd situations when used in an editor that already highlights these tokens.

**Comment by IceMan81** [comment]
@al2me6 Do you have some examples of editors or terminals that highlight tokens like this?

**Comment by mustaqimM** [comment]
@IceMan81 Doom Emacs can do this:
![image](https://user-images.githubusercontent.com/24436622/81034020-3b9a8b80-8e85-11ea-9f48-44335aef0345.png)
I feel highlighting should be dealt with by the editor, only maybe the shape could be set by the font

**Comment by al2me6** [comment]
@IceMan81 Apologies for the delay.

In addition to what @mustaqimM mentioned, Visual Studio Code (at least certain themes) and Jetbrains IDEs do similar things.

There is also a rather popular [Vscode extension](https://marketplace.visualstudio.com/items?itemName=wayou.vscode-todo-highlight) that does block highlighting in the style proposed above.

**Comment by IceMan81** [comment]
@al2me6 These highlights are in the editor, right? I use the TODO/FIXME highlighting in the Jetbrains IDEs, but what about the console? 

Where I've found these ligatures useful are in scenarios where rich text formatting is not available like the console/terminal, where its useful when looking at logs and other similar text. I believe that was the motivation for PragmataPro.
