### ISSUE TITLE
[Glyph Request] Variants to differentiate: d,b,q,p

### ISSUE THREAD

**Issue by AndydeCleyre** [be5invis/Iosevka#462]
* Your font version: r1461.43a8ca6d
* Your font variants: default, fixed, term
* Your operating system (name and version): Arch Linux
* Your application using Iosevka: konsole, sublime text, firefox

---

For folks with dyslexia or other difficulties, it can make a big difference in legibility to use different shapes (not just different orientations) for each character. `d`, `b`, `q`, and `p` all seem to be identical shapes, and it would be great to have to option to change that -- especially for differentiating `d` from `b` and `q` from `p`, but ideally all from each other.

So the small version of this request is:

- a new variant of any kind for *either* `d` or `b`, *and*
- a new variant of any kind for *either* `q` or `p`

and the big version of this request is:

- a new *uniquely shaped* variant for each of any three of `d`, `b`, `q`, and `p`

Current state:

![image](https://user-images.githubusercontent.com/1787385/77608165-ce452380-6ef2-11ea-8ca9-970296aca910.png)

Rotated 180°:

![image](https://user-images.githubusercontent.com/1787385/77608181-def59980-6ef2-11ea-82ba-4fa09c1975f8.png)

Mirrored Horizontally:

![image](https://user-images.githubusercontent.com/1787385/77608256-0ba9b100-6ef3-11ea-860c-bf94d7605315.png)

Mirrored Vertically:

![image](https://user-images.githubusercontent.com/1787385/77608278-195f3680-6ef3-11ea-8760-396512fc987c.png)

The idea is to make the letters identifiable regardless of orientation.

**Comment by be5invis** [comment]
Just a reminder, identical `b` `d` `q` `p` is considered as a design feature of Iosevka.

**Comment by AndydeCleyre** [comment]
Two updates:

1. Progress has been made (thank you!) with release 3.2.0 implementing #595, which brings us a unique "tailed" `q` shape. That only leaves `d`, `b`, and `p` as identical.
2. You've added the `Needs Justification` label here, so I'll restate the primary justification:

> For folks with dyslexia or other difficulties, it can make a big difference in legibility to use different shapes (not just different orientations) for each character.

But your personal justification for implementing the tailed `q` might have been its chemistry with the tailed `l` already available. With that in mind, maybe a slight tail on the `d` would offer a similar chemistry without introducing stylistic disharmony.

Adding a tailed `d` variant would AFAIU finish addressing the most likely legibility difficulties. According to [the internet](https://www.understood.org/en/learning-thinking-differences/child-learning-disabilities/dyslexia/faqs-about-reversing-letters-writing-letters-backwards-and-dyslexia),

> The most common letter reversal is b and d, when the child writes a b for a d or vice versa. Another common reversal is p and q. An example of an upside-down reversal is m for w.

Here's the current state of Iosevka with the lovely new `q`:

![image](https://user-images.githubusercontent.com/1787385/86274457-b7703600-bb9f-11ea-9f53-5c0b74226d1e.png)

I don't know a good way to maintain this style while further differentiating `p` and `b`, but I'll take another look at what some other fonts do, and the older issue that this one came out of.

**Comment by AndydeCleyre** [comment]
After a quick view of other fonts, it looks like a common strategy of differentiating `b` from both `p` and `d` is to diminish the back-tail of the `b`, either:

- making it smaller
- straighter
- removing it altogether. 

This is seen across a wide variety of type styles. Here's a diverse sampling to demonstrate:

[bp_fonts.pdf](https://github.com/be5invis/Iosevka/files/4860655/bp_fonts.pdf)

And a small subset that is maybe not *too* far off from Iosevka's style:

![image](https://user-images.githubusercontent.com/1787385/86294087-e3041800-bbc1-11ea-955c-bba5c2628222.png)

So this issue might be fully addressed by creating both:

- a slightly tailed `d` (like the new `q`)
- a tail-less/toothless `b` (like the toothless `G`)

**Comment by be5invis** [comment]
Add this first 🤔 
![image](https://user-images.githubusercontent.com/240091/86314717-333ca380-bbdd-11ea-8891-3b965903e96a.png)

**Comment by AndydeCleyre** [comment]
Beautiful!

**Comment by be5invis** [comment]
And if you want more rounded, there is choice.
![image](https://user-images.githubusercontent.com/240091/86318769-bb27ab00-bbe7-11ea-9c51-75d2a5950d6b.png)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/86321273-86b6ed80-bbed-11ea-9ddd-e560b9601000.png)

**Comment by AndydeCleyre** [comment]
I really like the toothless `b`, but still think a lightly tailed `d`, like the new `q`, would be much better and more recognizable as the correct character than those new `d`s. Just a little outward angle or curl to its tooth.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/86324110-e237aa00-bbf2-11ea-94c3-afc40d5fa033.png)

**Comment by be5invis** [comment]
Close as fixed

**Comment by AndydeCleyre** [comment]
Wonderful, thank you.
