### ISSUE TITLE
How to enable all calt ligatures in custom build?

### ISSUE THREAD

**Issue by IceMan81** [be5invis/Iosevka#463]
@be5invis what is the best way to enable all the ligatures shown in the screenshot below as part of the default calt set? I couldn't find a design set that would enable all of them in the build? Do I need to add each of the calt-* one by one?

Maybe I need to set all default + haskel ligs - thought not sure what I would need to add to the `design` build parameter to do this.

![image](https://user-images.githubusercontent.com/1093778/77805782-0017d080-7040-11ea-9627-846ddbef0d84.png)

**Comment by be5invis** [comment]
Should be now usable with

```
design  = […………, "ligset-dlig"]
```

**Comment by IceMan81** [comment]
Too good! Will try it out once dev gets merged into master!

**Comment by IceMan81** [comment]
@be5invis btw, this is the first time I tried various combinations of the character variants and ligatures I like as part of the custom build and I love the results. I was using custom build to the book variant/get a slightly thicker regular variant (414 instead of 400). I really like the results on the Mac. Great work!! 

Here's a screen shot from my hyper terminal! 
![image](https://user-images.githubusercontent.com/1093778/77830169-ea5be700-70e3-11ea-9bf7-202b8b33263b.png)

**Comment by IceMan81** [comment]
@be5invis I think I did not describe this issue properly. I see that ligset-dlig is now available which would add all the ligatures to the `dlig` set. I was asking how I could enable all the ligatures by default under `calt`. I was looking to have a way to enable all the ligatures in my first screenshot as part of the default `calt` set. Right now its a subset of the screenshot that is enabled by default.

**Comment by be5invis** [comment]
Add `ligset-dlig` into your custom build configuration's `design` field, and create your variant.

**Comment by IceMan81** [comment]
Understood.
