### ISSUE TITLE
 Is there a limit on the `leading` value?

### ISSUE THREAD

**Issue by xvrdm** [be5invis/Iosevka#466]
* Your font version: git
* Your operating system (name and version): built on MacOS 10.14
* Your application using Iosevka: built for Emacs modeline

If you have problem when building Iosevka, please provide these information:

* Your Node.js version: v13.11.0

I tried to modify `leading`/`descenderPad` twice: once with a modified `parameters.toml`, once with a modified `private-build-plans.toml`

* Your `parameters.toml`, paste if modified:

```
...default...

leading = 4450     
descenderPad = 65   

...default...
```

* Your `private-build-plans.toml`, if present:

```
[buildPlans.iosevka-custom]                         
family = "Iosevka Custom"               # Unchanged           
design = ["v-i-hooky", "v-l-hooky"] # Removed "leading-***"
hintParams = ["-a", "sss"]                 # Unchanged                    
leading = 4450
descenderPad = 65
...default...
```

---

Is there a limit on the `leading` value? I tried to build a custom Iosevka with a massive leading for the Emacs modeline (in the hope of making the bar height larger). It "worked" and the custom version definitely has a bigger height, but wether I put `leading` to 2000 or 5000, I get the same result.

Thanks a lot for the awesome project!

Below is the look of default / custom in a text editor.

<img width="748" alt="image" src="https://user-images.githubusercontent.com/3109069/77823453-9957ed00-70fb-11ea-99cc-bfaa7701f796.png">

**Comment by be5invis** [comment]
The relationship between `leading` and the real line height in text editors are complicated. I know some editors may limit the maximum line height.

**Comment by xvrdm** [comment]
Thanks for the input! Not sure if it adds anything, but I noticed that even if I look at the custom font in Mac OS Font Book, it still doesn't reflect a large line height.

**Comment by be5invis** [comment]
I think you should raise a bug to Emacs Modeline to make it able to configure its height?
Fonts' built-in line height is _very unreliable_, there are three sets of built-in line height, and different software interpret them differently.
I'd like to close this as external.

**Comment by be5invis** [comment]
This is one modeline with configurable height, hope it works for you: https://github.com/seagle0128/doom-modeline

**Comment by xvrdm** [comment]
Thanks a lot for the hint. This is actually the modeline I am currently using and was trying to get away from :)
I will try to just extract the little hack they use of inserting an image to control the height. At least this pushed me to compile fonts for the first time: thanks again for making Iosevka so open!
