### ISSUE TITLE
Greek lambda has no straight variant

### ISSUE THREAD

**Issue by AlsoScratch** [be5invis/Iosevka#467]
<img width="55" alt="Screenshot 2020-03-31 at 2 08 04 PM" src="https://user-images.githubusercontent.com/48752273/77992666-1af88680-7359-11ea-934c-2f791a96c12f.png">
Only problem is which character variant to sort it under. Or we could give it its own.

**Comment by be5invis** [comment]
Maybe under the `y` umbrella, but well it is more complicated.

**Comment by AlsoScratch** [comment]
I guess `y` is appropriate...

**Comment by AlsoScratch** [comment]
`y` is a problem because of `cv49`. Maybe `cv49` could have no effect on lambda, or we could give it its own OpenType variant.

**Comment by be5invis** [comment]
`cv49` will set `lambda` to straight.

**Comment by AlsoScratch** [comment]
What about giving it its own tag?

**Comment by be5invis** [comment]
I do not have many tags to waste. Sorry.

**Comment by AlsoScratch** [comment]
But those who want curly lambda but `cv49` `y` will have a problem since `cv49` will set lambda to straight. Right now, making it have no effect on lambda seems best.

**Comment by be5invis** [comment]
... Add `v-lambda-straight` (`cv94`) and `v-lambda-curly` (`cv95`)

![image](https://user-images.githubusercontent.com/240091/77996294-35434d80-72e2-11ea-9c69-42c98703aac0.png)
![image](https://user-images.githubusercontent.com/240091/77996302-38d6d480-72e2-11ea-96a8-88c93d49c209.png)

**Comment by throwaway571** [comment]
@be5invis 

Is it possible to consolidate all the curly variants into one tag? I can’t imagine someone preferring to use straight `y` but curly `v`, for example.

If this is too radical, you could save one tag by making the straight/curly and roman/cursive axes for `y` independent. In that case, `cv49` would override the shape selector for `y` and only apply to `λ`.

`cv48`, `cv94`: straight `y` and `λ`
`cv48`, `cv49`: straight `λ`, cursive `y`
`cv79`, `cv94`: curly `y` and `λ`
`cv79`, `cv49`: curly `λ`, cursive `y`

**Comment by be5invis** [comment]
@throwaway571 There's already `ss20` which will turn all letters to curly.
`cv##` tags is used for cherry picking, so I'd like to leave it as-is.

**Comment by throwaway571** [comment]
@be5invis I edited my last post while you were responding to add something about the design of the lambda-bar glyph.

**Comment by be5invis** [comment]
@throwaway571 Move up a little :)
![image](https://user-images.githubusercontent.com/240091/78205103-32666b00-7450-11ea-95fe-f48e428b8c3f.png)

**Comment by throwaway571** [comment]
@be5invis Yeah, I think that looks better. By the way, does Latin gamma have curly and straight variants as well? If not, I’d recommend adding them to the `v`, `V` tag.

**Comment by be5invis** [comment]
@throwaway571 
Currently no plan for 3.0. You can open a new issue for post-3.0.
