### ISSUE TITLE
Support for a taller variant

### ISSUE THREAD

**Issue by cdlscpmv** [be5invis/Iosevka#47]
I haven't updated fonts for a while, but today I've tried to switch to a newer version of Iosevka. I've noticed that characters have become shorter for the same width. Is there a way to use the old taller variant of the font (as in the version 0.1.8) in the current version?

**Comment by be5invis** [comment]
@cdlscpmv You can increase the `cap` and `xheight` in `parameters.toml` and build your own variant.

**Comment by cdlscpmv** [comment]
Thanks!
