### ISSUE TITLE
specimen.html link broken

### ISSUE THREAD

**Issue by bluz71** [be5invis/Iosevka#470]
Hello,

The README markdown file for this repo contains the following section:

> All versions include the same ranges of characters: Latin letters, Greek letters (including Polytonic), some Cyrillic letters, IPA symbols and common punctuations and some symbols. You can check out the full list here.

The `full list here` links to https://typeof.net/Iosevka/specimen.html, but that is now broken.

I often referred to that specimen page with regards to the available symbols such as arrows and shapes. A **very** useful page.

Can you fix the link and restore the specimen page.

Many thanks for producing a superb font.

**Comment by be5invis** [comment]
Ah, I need to recreate that page...
This time with more Unicode data display so you could inspect :)

**Comment by bluz71** [comment]
Excellent, looking forward to the updated version. The specimen page is a genuinely informative resource for this font.

**Comment by be5invis** [comment]
Closed as fixed.
It is now https://typeof.net/Iosevka/specimen

**Comment by bluz71** [comment]
Thank you.
