### ISSUE TITLE
Improving the middle stem of small "m"

### ISSUE THREAD

**Issue by IceMan81** [be5invis/Iosevka#471]
* Your font version: 3.0.0_rc.5
* Your font variant: standard and Ubuntu Mono variant
---
This is not a bug, more like a suggestion to see if the middle stem of m can be made more visible and distinctive especially at small sizes. Many times I've found that the middle stem is  not clearly distinguishable because the gap between the middle stem and side stems are too small. I've checked on multiple app like Sublime, Intellij, terminal mostly at size 14 on macOS. 

I think if the gap can be increased a little bit somehow, it will be more readable. The same for the Ubuntu variant of 'm' with shorter middle stem. I find this variant a bit more readable but even this one could benefit from more breathing space between the stems. 

Pardon me, if I'm asking for too much!

**Comment by be5invis** [comment]
Macintosh is always blurry /sigh.
The stroke widt is chosen to balance darkness between letters.
Changing them only for more clarity is not a very good justification.
Mark as post-3.0 enhancement.

**Comment by IceMan81** [comment]
@be5invis understood. 
What about raising the middle stroke of `m` for the Ubuntu Mono variant to more closely match Ubuntu Mono? I think that would improve clarity. Would that change the balance of darkness?

**Comment by be5invis** [comment]
@IceMan81 There's already `cv26` doing that.

**Comment by IceMan81** [comment]
@be5invis I was referring to the stroke length of `cv26`

**Comment by be5invis** [comment]
@IceMan81 
![image](https://user-images.githubusercontent.com/240091/78343737-23ff7880-7550-11ea-89ff-7dad8a5fe15a.png)
Like this?

**Comment by wimstefan** [comment]
Very nice! Now the middle stem is on the same height as the middle center line from "e" and "a" ... that looks very nice indeed.
Thank you for that :)

**Comment by wimstefan** [comment]
I have to add though that the bold version is noticeably lighter in comparison to other glyphs ...

![screen-2020-04-03-17-50](https://user-images.githubusercontent.com/4605934/78380289-e9d7ba80-75d3-11ea-9555-be00015403bb.png)

**Comment by IceMan81** [comment]
@be5invis Yes, I think this looks a lot better than 
![image](https://user-images.githubusercontent.com/1093778/78380989-904a9e00-7589-11ea-95b0-f9e4c4bd964f.png)


@wimstefan Good observation!!

**Comment by IceMan81** [comment]
@wimstefan First time I really noticed the beauty of the back-slashed zero when I saw it in your screenshot. Using a back-slashed zero makes a clear distinction for a null set character as well. I think I'm going to use that going forward!

**Comment by be5invis** [comment]
@IceMan81 I think @wimstefan extra-narrowed the width (or increased sidebearings...)?
Close this issue as fixed.

**Comment by wimstefan** [comment]
> @IceMan81 I think @wimstefan extra-narrowed the width (or increased sidebearings...)?
> Close this issue as fixed.

That's the case indeed @be5invis ...
I'm using
```toml
sb = 0.9
width = 0.9
```
which comes down to `condensed` I guess. I'd just prefer the more narrow looks if that's possible without compromising the thickness of `m` too much ...

**Comment by be5invis** [comment]
@wimstefan Please file another issue about this — though it will be definently be a post-3.0 thing.

**Comment by wimstefan** [comment]
> @wimstefan Please file another issue about this — though it will be definently be a post-3.0 thing.

Sure - if you prefer to have an extra issue for that ...

**Comment by be5invis** [comment]
@wimstefan This is a different story and only happens on extra-condensed situations. Please file another issue.
