### ISSUE TITLE
How to download/build specific font version

### ISSUE THREAD

**Issue by narukeh** [be5invis/Iosevka#472]
[HERE](https://imgur.com/a/SqdX275) is the version how i like it.
i read [THIS](https://github.com/be5invis/Iosevka#build-your-own-style) but it does not mention how to write the cv##
it isnt really clear what i have to do, where do i have to place the private-build-plans.toml , in the root of 'git clone' , then what? is there a tool to generate?
im on arch linux

**Comment by IceMan81** [comment]
@narukeh Here is an example from my private-build-plans.toml

```
[buildPlans.iosevka-custom-curly]
family  = "Iosevka Custom Curly"
design  = ["cv11", "cv21", "cv26", "cv38", "cv45", "cv61", "cv67", "cv69", "cv72", "cv74", "cv76", "cv78", "cv79", "cv81", "cv83","ligset-dlig"]
italic = ["cv12","cv21", "cv26", "cv38", "cv45", "cv61", "cv67", "cv72", "cv74", "cv76", "cv78", "cv79", "cv81", "cv83"]
hintParams = ["-c", "-a", "nnn"]
```
You can use different hintparams, in my case I'm setting ttfautohint to use its natural stem-width-mode. Search for `stem-width-mode` [here](https://www.freetype.org/ttfautohint/doc/ttfautohint.html). The `-c` option is to hint composite glyphs. 

To build with the above settings, run `npm run build -- contents::iosevka-custom-curly`.
Before this you would need ensure all the dependencies mentioned in the build documentation is satisfied and also run `npm install` to pull down all npm dependencies.

Hope this helps!

**Comment by narukeh** [comment]
thanks for replying
i left EVERYthing default, since i want vanilla iosevka with my cv versions. I only changed line 3 and added, now looks like this
`design = ["cv02" "cv04" "cv08" "cv19" "cv23" "cv24" "cv26" "cv32" "cv51" "cv69" "cv72" "cv74" "cv76" "cv78" "cv79" "cv81" "cv83" "cv92" "leading-1500", "v-i-hooky", "v-l-hooky"]`

`upright = ["cv02" "cv04" "cv08" "cv19" "cv23" "cv24" "cv26" "cv32" "cv51" "cv69" "cv72" "cv74" "cv76" "cv78" "cv79" "cv81" "cv83" "cv92" "leading-1500", "v-i-hooky", "v-l-hooky"]`

`italic = ["cv02" "cv04" "cv08" "cv19" "cv23" "cv24" "cv26" "cv32" "cv51" "cv69" "cv72" "cv74" "cv76" "cv78" "cv79" "cv81" "cv83" "cv92" "leading-1500", "v-i-hooky", "v-l-hooky"]`

`oblique = ["cv02" "cv04" "cv08" "cv19" "cv23" "cv24" "cv26" "cv32" "cv51" "cv69" "cv72" "cv74" "cv76" "cv78" "cv79" "cv81" "cv83" "cv92" "leading-1500", "v-i-hooky", "v-l-hooky"]`

will this give me all the fonts like [here](https://imgur.com/a/c1Sz3Yo)
if not, what will i need to do, to have all of them?

**Comment by be5invis** [comment]
This should be enough if you do not want separate styles for italic/oblique:

```toml
[buildPlans.iosevka-custom-curly]
family  = "Iosevka Custom Curly"
design = ["cv02", "cv04", "cv08", "cv19", "cv23", "cv24", "cv26", "cv32", "cv51", "cv69", "cv72", "cv74", "cv76", "cv78", "cv79", "cv81", "cv83", "cv92", "leading-1500"]
```

After that run ```npm run build -- contents::iosevka-custom-curly```.

**Comment by narukeh** [comment]
i installed afdko with python pip, and other dep. though pacman, but i still get an error when i build. [Here](https://pastebin.com/raw/hZerBBML) is the output.

**Comment by be5invis** [comment]
@narukeh What is your contents of your `private-build-plans.toml`? And is it placed in the same directory with `build-plans.toml`?

**Comment by narukeh** [comment]
[This](https://pastebin.com/bBFQe6xw) is how private-build-plans.toml looks, just like u told me.
i didnt move ANYthing, i only edited that file.
Yes, `private-build-plans.toml` and `build-plans.toml` are in the same dir , aka root of local repository

**Comment by be5invis** [comment]
@narukeh 
I cannot repro that failure.
Is the file name really `private-build-plans.toml`, not `private-build-plans.sample.toml`.

**Comment by narukeh** [comment]
😅Yes it was sample. Thanks a lot.
