### ISSUE TITLE
Ruby Squiggly Heredoc

### ISSUE THREAD

**Issue by akarzim** [be5invis/Iosevka#475]
* Your font version: git master branch (ca995d7)
* Your font variant: custom sp-term with dlig on
* Your operating system (name and version): macOS 10.15.3
* Your application using Iosevka: iTerm + Neovim

---

Introduced in Ruby 2.3, the squiggly heredoc `<<~` removes extra indentation for you.

```ruby
page = <<~TXT
  Heredocs are cool & useful
TXT
```

I notice that the litagure for this operator could have a better rendering.

<img width="140" alt="image" src="https://user-images.githubusercontent.com/130560/78453155-2f59bd80-7690-11ea-826a-97baa237273d.png">

Thank you for this delightful font!

**Comment by be5invis** [comment]
This should work well.
![image](https://user-images.githubusercontent.com/240091/78463101-ed2f7c80-768d-11ea-8ea0-85a61255ffb5.png)
