### ISSUE TITLE
Dot related operators ligatures

### ISSUE THREAD

**Issue by akarzim** [be5invis/Iosevka#476]
* Your font version: git master branch (ca995d7)
* Your font variant: custom sp-term with dlig on
* Your operating system (name and version): macOS 10.15.3
* Your application using Iosevka: iTerm + Neovim

---

The dot related operators should be aligned with the square colon operator `::`

![colon](https://user-images.githubusercontent.com/130560/78454901-4ce05480-769b-11ea-8502-54bf73187f27.png)

Here are some details about the operators in this example:

```
Ruby        !!    Bang Bang Operator
Ruby        ..    Flip-Flop Operator
Raku        .?    Safe Navigation Operator
Ruby        ::    Scope Resolution Operator
Clojure     ;;    Comments
Kotlin      ?.    Safe Navigation Operator
Javascript  ?:    Elvis Operator
C#          ??    Null Coalescing Operator
```

```
Regex       (?!   Negative Lookahead
Regex       (?:   Non-capturing Group
Ruby        ...   Half-open Range Ellipsis
Swift       ..<   Closed Range Ellipsis
Rust        ..=   Inclusive Range Ellipsis
Scala       .?.   Safe Navigation Operator
Prolog      =..   Univ Operator
PHP         ??=   Null Coalescing Operator
```

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/78460297-83ef3f80-7674-11ea-9e0f-8a2a27bc647c.png)

Note: two-char operators are aligned differently with three-char operators.
