### ISSUE TITLE
Extended in VSCODE?

### ISSUE THREAD

**Issue by JameEnder** [be5invis/Iosevka#479]
* Your font version: 01-iosevka-3.0.0-rc.5
* Your font variant: Iosevka Extended
* Your operating system : Windows 10
* Your application using Iosevka:  VSCODE

Hi, i was trying to use Iosevka Extended in VSCODE, but for some reason it just wouldnt work, i tried reinstalling many times. The only thing that works in vscode is Iosevka, but Iosevka Extended doesnt load.
![2020 duben 265](https://user-images.githubusercontent.com/47925045/78497570-950a8000-774a-11ea-913b-a909f3269a21.png)
![2020 duben 266](https://user-images.githubusercontent.com/47925045/78497607-989e0700-774a-11ea-85e9-0dd530d6aae7.png)

**Comment by be5invis** [comment]
Iosevka Extended is a _width_ of Iosevka family. It looks like VSCode doesn't have proper font-width support.
Closed as external.

**Comment by sharpjs** [comment]
Please upvote microsoft/vscode/issues/95493 if you want this fixed.  They need 20 votes in 60 days.  At time of writing they have 3 votes.

**Comment by ItoldU** [comment]
Change to "Iosevka Expanded". No idea why, but it works.

**Comment by kimael-code** [comment]
> Change to "Iosevka Expanded". No idea why, but it works.

OMG... I even changed to Fira Code because... and now I tried this and it works... LOL

**Comment by sharpjs** [comment]
FWIW, you can also just build a custom Iosevka with only the width you want.

**Comment by zanedp** [comment]
It might be worth adding to documentation that to use "Extended" in VS Code, you have to spell it as "Expanded." I didn't know until I found this issue.

**Comment by mvrikxix** [comment]
> It might be worth adding to documentation that to use "Extended" in VS Code, you have to spell it as "Expanded." I didn't know until I found this issue.

Using `Iosevka Extended` worked for me.
```
  "editor.fontFamily": "Iosevka Extended",
  "editor.fontLigatures": true,
```

**Comment by zanedp** [comment]
On Windows 11 and VS Code 1.95.3, I have to use `Iosevka Expanded` instead of `Iosevka Extended`. I installed from `SuperTTC-Iosevka-32.2.0.zip`. (I haven't tried any other OSes.)

**Comment by feketegy** [comment]
Encoding can be different if you compile the font yourself. What worked for me:

1. Visit https://fontdrop.info/
2. Upload the extended/expanded font file on the page
3. Go to the "Data" tab to see the encoded font family name

I'm using the "Semi-Extended" version of the font that I compiled myself. The encoded font family was `Iosevka Custom SmEx` which worked in VSCode.
