### ISSUE TITLE
Add atom/rss feed to Inziu Iosevka variation.

### ISSUE THREAD

**Issue by happlebao** [be5invis/Iosevka#48]
Please add atom/rss feed to http://be5invis.github.io/Iosevka/inziu.html.
请在 http://be5invis.github.io/Iosevka/inziu.html 加个 atom/rss？

**Comment by be5invis** [comment]
@happlebao 
Inziu Iosevka 的更新和 Iosevka 是同步的，直接跟踪 Iosevka 更新即可。
