### ISSUE TITLE
Arrows appear to be broken

### ISSUE THREAD

**Issue by akarzim** [be5invis/Iosevka#480]
This should work well.
![image](https://user-images.githubusercontent.com/240091/78463101-ed2f7c80-768d-11ea-8ea0-85a61255ffb5.png)

_Originally posted by @be5invis in https://github.com/be5invis/Iosevka/issues/475#issuecomment-609101495_

---

* Your font version: git dev branch (59d49f026aa5e3ea7cc26c9c9ab4712dd1a2ed2d)
* Your font variant: custom sp-term with dlig on
* Your operating system (name and version): macOS 10.15.3
* Your application using Iosevka: iTerm + Neovim ; FontForge ; Boxy SVG

---

Arrow ligatures appear to be broken 🤔

![arrows](https://user-images.githubusercontent.com/130560/78498881-90939680-774d-11ea-8f7a-76a413e0fbb0.png)

The same from master branch: 

![arrows-master](https://user-images.githubusercontent.com/130560/78499001-45c64e80-774e-11ea-9c64-756977baccf7.png)

Did I miss something ?

**Comment by be5invis** [comment]
This is my `dlig` results shaped with Harfbuzz:
![image](https://user-images.githubusercontent.com/240091/78499951-9b780800-7708-11ea-9b14-9da4e6cb8d6d.png)

This is the same results shaped with DWrite:
![image](https://user-images.githubusercontent.com/240091/78500001-e5f98480-7708-11ea-946d-9dce7d77711a.png)

Nothing bad happened. Maybe it is a font caching issue. Or, Apple's shaping thing cannot properly handle a fully valid font.

Closed as external.

**Comment by akarzim** [comment]
I rebuilt the font from the freshly merged master branch and it's ok now !  
Thank you for this great work @be5invis! I love the new wavy arrows :)

I pushed my arrow experiments a bit further and it looks really good in many cases... but not all ;) Some atypical arrows are used in Clojure or Javascript for example:

```
Clojure     -<> -<>> -<>< -<><: -<< -<<: -< -<:
Javascript  >>>=
PostGIS     <<->> |>> |&> &<|
PostgreSQL  #> ##>
Rust <_>
```

![Capture d’écran 2020-04-05 à 21 54 19](https://user-images.githubusercontent.com/130560/78508609-64e1d200-7788-11ea-842d-6aad69c69552.png)

Here are my experiments.
![Capture d’écran 2020-04-05 à 21 39 15](https://user-images.githubusercontent.com/130560/78508605-63b0a500-7788-11ea-95a7-0dd5152d0b09.png)
![Capture d’écran 2020-04-05 à 21 41 00](https://user-images.githubusercontent.com/130560/78508607-64493b80-7788-11ea-92ae-131afe9502f5.png)
![Capture d’écran 2020-04-05 à 21 41 50](https://user-images.githubusercontent.com/130560/78508608-64493b80-7788-11ea-948b-822b18aa22c8.png)



source:

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Assignment_Operators#Unsigned_right_shift_assignment
- https://github.com/rplevy/swiss-arrows
- https://doc.rust-lang.org/book/appendix-02-operators.html
