### ISSUE TITLE
Support for Git tree ligatures

### ISSUE THREAD

**Issue by akarzim** [be5invis/Iosevka#481]
How about Git tree ligatures? I'm thinking of kind of curly forks  (`|/` `|\` `\|` `/|` `|/|` `|\|`) and centered pipes and stars (`* |` `| *` `| |` `\ \` `/ /`).

```git
*
|
*
|\
| *
| |
|/
|
*
|\
| *
|/
|
*
|\
| |
| *
| |\
| | |
* | |
|\ \ \
| | | |
| * | |
|/ / /
| | |
* | |
| | |
| | | *
| | | |\
| | | |/
| | |/|
| | | |
| | * |
| |/ /
|/| |
| | *
| | |
| | *
```

**Comment by be5invis** [comment]
I to not think it is implementable even with OT features.
This should be the responsibility of the software that displays it.

**Comment by juarezr** [comment]
Using console program `tig`:

![tig-screenshot-2020-04-15_11-24-38](https://user-images.githubusercontent.com/576780/79348861-f03b3000-7f0b-11ea-88ba-580a6081282d.png)

**Comment by plgruener** [comment]
To do this properly, you'd need ligatures in two dimensions, and support coloring parts of the ligature in different colors. Plus: you're screwed if git someday changes the output.
`tig` (see above) supports using the Unicode box drawing characters for git graph, but even in the image above you can see where this reaches its limits (in the middle where all the colors overlap).
