### ISSUE TITLE
[Character Request] Pitman duodecimal digits

### ISSUE THREAD

**Issue by throwaway571** [be5invis/Iosevka#483]
I'd like to request U+218A ↊ and U+218B ↋. These were proposed by Isaac Pitman for the digits ten and eleven in base 12, and are currently actively used by the two Dozenal Societies.

**Comment by be5invis** [comment]
Iosevka is currently feature locked for 3.0. Mark as post-3.0.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/82183837-82cc4780-989b-11ea-87c2-ae582649838f.png)
Done

**Comment by throwaway571** [comment]
@be5invis Is U+218B affected by `cv46`?

**Comment by be5invis** [comment]
@throwaway571 No.

**Comment by throwaway571** [comment]
@be5invis I haven’t come across an old-style form yet, but that may be by design. In the issues of the Duodecimal Bulletin prior to July 11↋↋ (decimal 2015), old-style numerals were used contrastively to represent decimal numbers, but I’m not sure what the current policy is. Let me confirm with the current editor and I’ll get back to you.

In any case, the flat bottomed eleven is definitely attested.
![image](https://user-images.githubusercontent.com/62322214/82280653-3557e500-9944-11ea-9532-a61b45a4912e.png)

**Comment by be5invis** [comment]
@throwaway571 OK I will add that back so `cv46` can influence both `3` and `↋`.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/82281980-9634ec80-9947-11ea-9a33-d050b4038376.png)
