### ISSUE TITLE
Installing oblique and italic variants together?

### ISSUE THREAD

**Issue by IceMan81** [be5invis/Iosevka#484]
* Your font version: (Release or git, version)
3.0.0.rc6
* Your font variant: Oblique, Italic
* Your operating system (name and version): macOS Catalina 10.15.4
* Your application using Iosevka: (some Java applications may have problem in showing Iosevka properly. It is a bug in Java's GUI components.)
Intellij
---

I noticed that Intellij has issues identifying Oblique and Italic variants correctly. For italics in the editor, it's using the Oblique variant. If you delete the installed Oblique variant, then it correctly picks up the Italic variant. This could very well be a problem with the JDK and how it identifies font variants. This may not be an issue specific to Iosevka and how it advertises the different variants. But thought it worthwhile to ask if others have observed similar issues in other applications. For example, I've not observed any issues with Pages.

**Comment by be5invis** [comment]
It is possible to use custom builds to remove Oblique from the results. However for prebuilts I will _never_ workaround this for Java — you should raise an issue to JetBrains and let them to fix their software.

**Comment by IceMan81** [comment]
I agree, I don't think you should make any changes esp if there is a problem with how the Java JDK identifies font variants - which I think might be the issue, maybe not even be Jetbrains specific. 
Here I was wondering aloud if others are noticing a similar problem in other apps.

**Comment by be5invis** [comment]
@IceMan81 Doc PRs are welcome.

**Comment by IceMan81** [comment]
@be5invis Doc PRs?

**Comment by be5invis** [comment]
@IceMan81 Well I mean you can raise a PR and update README.

**Comment by IceMan81** [comment]
@be5invis Will do

**Comment by sleepiejohn** [comment]
@IceMan81 You could also open a [Jetbrains Runtime bug report](https://youtrack.jetbrains.com/issues/JRE), since they are shipping their products with their own custom patched JDK, specifically because of font problems on the main JDK

**Comment by IceMan81** [comment]
@sleepiejohn https://youtrack.jetbrains.com/issue/IDEA-236770
They are linking it to another issue and it looks like it will not get addressed this year!

**Comment by sleepiejohn** [comment]
Oh thanks for sending! Yea unfortunately we will have to wait for it then.

**Comment by be5invis** [comment]
I'd like to close this as external.
Please follow up the JetBrains issue.
