### ISSUE TITLE
U+E0A0 Metrics possible problem

### ISSUE THREAD

**Issue by ChiefMikeK** [be5invis/Iosevka#487]
* Your font version: iosevka-fixed-ss07
* Your font variant: rc4 ?
* Your operating system (name and version): Android 6.0.1
* Your application using Iosevka: UnicodePad  
* Out of bounds on right side (_slight over lap_)
* Sample string of Private-Use Characters ``
IIRC-(simular have cause a system to crash on rare occasions in the past)
![Image](https://github.com/ChiefMikeK/feedback/raw/master/img/U%2BE0A0(git-merge).png)

**Comment by be5invis** [comment]
This is by design. If a font rasterizer crashes when the contour goes outside the metric limits, then they should fix the rasterizer.

**Comment by ChiefMikeK** [comment]
ok
