### ISSUE TITLE
Wrong glyphs for phonetic ligatures U+02A3 through U+02AB

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#488]
* Your font version: 3.0.0-rc.6
* Your font variant: all
* Your operating system (name and version): macOS 10.14.6
* Your application using Iosevka: hb-view

---

U+02A3 through U+02AB are rendered as digraphs, but they are supposed to be ligatures. For example, U+02A3 LATIN SMALL LETTER DZ DIGRAPH should not look like ǳ U+01F3 LATIN SMALL LETTER DZ. (The Unicode names are misleading.) Here they are in Iosevka Extended:
![ʣʤʥʦʧʨʩʪʫ](https://user-images.githubusercontent.com/1124347/79029066-bf9c7480-7b60-11ea-91a5-09c717a6460d.png)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/79031752-eef9b400-7b55-11ea-9b75-1c97abbaa650.png)
How about this?

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/79031965-a642fa80-7b57-11ea-8b5c-3e761f779c0e.png)
t-esh is also modified to look connected.

**Comment by dscorbett** [comment]
In the new glyph of U+02A8 LATIN SMALL LETTER TC DIGRAPH WITH CURL, the bottom right end of the ⟨t⟩ protrudes slightly beyond the curl of the ⟨ɕ⟩. Was that intentional?

**Comment by be5invis** [comment]
@dscorbett These phonetic ligatures are built from the two parts so they may collide. Fixing that is too costy.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/79033934-2de43580-7b67-11ea-9171-61fed440b4a5.png)
By repeatedly knocking the second part this is now avoidable.

**Comment by throwaway571** [comment]
Glyph Design note: In the phonetic fonts I’ve come across, it’s the crossbar of the /t that reaches out and attaches to the /esh, not the exit stroke. The exit stroke _may_ actually collide with the /esh, but only in proportional fonts when the spacing is too narrow.

Character Request note: There were two more IPA phonetic ligatures added in Unicode 12.0, U+AB66 and U+AB67. These are retroflex affricates attested in Chinese dialectology.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/79083868-a2dd7980-7ce5-11ea-844b-5a05d3232a82.png)

**Comment by throwaway571** [comment]
@be5invis Because the exit stroke of the /t in /tesh isn’t touching the /esh anymore, you might consider adding an upward terminal to it to mirror /t itself.
