### ISSUE TITLE
Wrong glyphs for three Latin alphas

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#489]
* Your font version: 3.0.0-rc.6
* Your font variant: all
* Your operating system (name and version): macOS 10.14.6
* Your application using Iosevka: hb-view

---

U+AB30 LATIN SMALL LETTER BARRED ALPHA, U+AB64 LATIN SMALL LETTER INVERTED ALPHA, and U+1DE7 COMBINING LATIN SMALL LETTER ALPHA are based on the Greek alpha. They should be based on the Latin alpha.
![ꬰꭤᷧ](https://user-images.githubusercontent.com/1124347/79050352-79462480-7bf7-11ea-9fba-1c6e98658955.png)

**Comment by be5invis** [comment]
Fixed
![image](https://user-images.githubusercontent.com/240091/79055917-b31e2780-7c05-11ea-8cbc-b80f8ccaa693.png)
