### ISSUE TITLE
Not sign ¬ appears wrong

### ISSUE THREAD

**Issue by geraldus** [be5invis/Iosevka#49]
I've downloaded hooky **Iosevka** version **1.6.2** and not sign `¬` now appears as dash.  Currently I'm on OS X, but on my linux machine which have Iosevka-1.5 installed it appears as expected.
![2016-01-10 16 05 10](https://cloud.githubusercontent.com/assets/744471/12221241/fe503cea-b7b3-11e5-8a26-17c88e070947.png)

**Comment by be5invis** [comment]
Will be fixed in 1.6.3.
