### ISSUE TITLE
Broken ligatures on Linux

### ISSUE THREAD

**Issue by alexeyten** [be5invis/Iosevka#490]
* Your font version: commit https://github.com/be5invis/Iosevka/commit/52d0cc43d90f27e0988eb4ed75b3afeaddcc4f95
* Your font variant: Iosevka Term
* Your operating system (name and version): Elementary OS 5 (based on Ubuntu 18.04)
* Your application using Iosevka: Any, including Firefox, Chromium, VS Code, etc.

Builded with:
* Your Node.js version: v12.16.1
* Your _otfcc_ version: 0.9.5.

* Your `private-build-plans.toml`, if present: Just renamed Iosevka Term with only regular and bold weights
```
[buildPlans.iosevka-dev]
family = "Iosevka Dev"
design = ["sp-term"]


[buildPlans.iosevka-dev.weights.regular]
shape = 400  # Weight for glyph shapes.
menu  = 400  # Weight for the font's names.
css   = 400  # Weight for webfont CSS.

[buildPlans.iosevka-dev.weights.bold]
shape = 700
menu  = 700
css   = 700

[buildPlans.iosevka-dev.slants]
upright = "normal"
italic = "italic"

[buildPlans.iosevka-dev.widths.normal]
shape = 5          # Width of glyph shapes.
menu  = 5          # Width for the font's names.
css   = "normal"   # "font-stretch' property of webfont CSS.

```

Ligatures went wrong after in commit https://github.com/be5invis/Iosevka/commit/0bb02b925ce98d9949db3cfe0bde5e2400aa56bd

Test page: https://result.dabblet.com/gist/50617a712ba980fc373395fac5bca7a5

52d0cc43d90f27e0988eb4ed75b3afeaddcc4f95
![image](https://user-images.githubusercontent.com/44377/79054355-c30d2a00-7c4c-11ea-91a0-cdb80ee34ae0.png)

3.0.0-rc.6
![image](https://user-images.githubusercontent.com/44377/79054389-05cf0200-7c4d-11ea-98df-4857cb7b0fb3.png)

Freetype version 2.8.1-2ubuntu2
Pango version 1.40.14-1ubuntu0.1

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/79055356-3be69480-7c01-11ea-8e0f-ff46c1b3e842.png)
It looks very normal here on Chromium, which uses latest Harfbuzz.
Note that Pango 1.40 comes from 4 years ago, which is considered outdated.

**Comment by be5invis** [comment]
[iosevka-term.zip](https://github.com/be5invis/Iosevka/files/4465455/iosevka-term.zip)
Can you try this which is built on my computer. I'd like to exclude the influence of `otfcc` which has a newer alpha (0.10.x, but then I discontinued it).

**Comment by be5invis** [comment]
Another cause may be font caching — caching may lead to incorrect shaping results especially the newer commit massively changed how non-encoded glyphs arranged.

**Comment by be5invis** [comment]
I can confirm that it should be an issue of otfcc 0.9.5, but it is fixed by otfcc 0.10.3-alpha. cc. @cyanohao

**Comment by IceMan81** [comment]
@be5invis Could you release the otfcc alpha version via brew as well?

**Comment by be5invis** [comment]
@IceMan81 I do not have macintosh machines. That is the problem.
@liam0205 did that for me.

**Comment by be5invis** [comment]
Also I do have plan to remove it from the dependencies in the future but it may take a lot of time.

**Comment by IceMan81** [comment]
@be5invis Understood! 
@Liam0205 Would you be able to push out the alpha versions to homebrew?

**Comment by Liam0205** [comment]
@Ice Moving house, I could do this later these days.

**Comment by alexeyten** [comment]
> Can you try this which is built on my computer.
This works well.
Will update otfcc.
Thank you for a great font, btw. :smiley:

**Comment by IceMan81** [comment]
> @IceMan81 Moving house, I could do this later these days.

@Liam0205 @be5invis 
I've an open PR for the updated tap definition. Could one of you take a look and accept?
https://github.com/caryll/homebrew-tap/pull/4
