### ISSUE TITLE
Upside-down Latin epsilons

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#491]
* Your font version: 3.0.0-rc.6
* Your font variant: Extended
* Your operating system (name and version): macOS 10.14.6
* Your application using Iosevka: hb-view

---

Some Latin epsilons are upside-down, probably because a turned epsilon and a reversed epsilon are easily confused.
* U+029A LATIN SMALL LETTER CLOSED OPEN E
* U+1D08 LATIN SMALL LETTER TURNED OPEN E
* U+1D4C MODIFIER LETTER SMALL TURNED OPEN E
![ʚᴈᵌ](https://user-images.githubusercontent.com/1124347/79079145-52f9b500-7cdb-11ea-8a5f-2197baced747.png)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/79083536-b851a400-7ce3-11ea-9e36-38497d68f0f4.png)
Fixed.
