### ISSUE TITLE
Emojis & symbols support

### ISSUE THREAD

**Issue by akarzim** [be5invis/Iosevka#494]
* Your font version: 3.0.0-rc6
* Your font variant: custom sp-term with dlig on
* Your operating system (name and version): macOS 10.15.3
* Your application using Iosevka: iTerm + Neovim

---

It would be wonderful to have full support for monochromatic emojis and symbols to use in our terminal instead of the overly coloured ones from the operating system.

Here are some examples from the Symbola font and the current rendering on my terminal:

<img width="1548" alt="image" src="https://user-images.githubusercontent.com/130560/79115197-81cc6580-7d85-11ea-850b-6a0271eb356a.png">
<img width="701" alt="image" src="https://user-images.githubusercontent.com/130560/79115369-f2738200-7d85-11ea-9264-6967b3d2e69b.png">

- https://unicode-table.com/en/blocks/miscellaneous-symbols/

<img width="1540" alt="image" src="https://user-images.githubusercontent.com/130560/79115519-58600980-7d86-11ea-8160-51d4fe5338ed.png">
<img width="731" alt="image" src="https://user-images.githubusercontent.com/130560/79115536-657cf880-7d86-11ea-8efe-879dff9039b0.png">

- https://unicode-table.com/en/blocks/dingbats/

<img width="1493" alt="image" src="https://user-images.githubusercontent.com/130560/79116921-fd301600-7d89-11ea-8749-6e4e92598583.png">
<img width="1389" alt="image" src="https://user-images.githubusercontent.com/130560/79116964-11741300-7d8a-11ea-906b-c73e1d74b942.png">
<img width="1918" alt="image" src="https://user-images.githubusercontent.com/130560/79116886-e5f12880-7d89-11ea-8f84-71c902d22e04.png">

- https://unicode-table.com/en/blocks/miscellaneous-symbols-and-pictographs/

<img width="1468" alt="image" src="https://user-images.githubusercontent.com/130560/79117069-61eb7080-7d8a-11ea-8074-4290a7729fb0.png">
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/130560/79117051-539d5480-7d8a-11ea-837d-5d7196cd1d16.png">

- https://unicode-table.com/en/blocks/emoticons/

<img width="1483" alt="image" src="https://user-images.githubusercontent.com/130560/79117099-79c2f480-7d8a-11ea-9388-60b07c0970c9.png">
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/130560/79117201-c9092500-7d8a-11ea-8a25-3c8a7f860222.png">

- https://unicode-table.com/en/blocks/transport-and-map-symbols/

<img width="1484" alt="image" src="https://user-images.githubusercontent.com/130560/79117310-15546500-7d8b-11ea-831b-fe7e675c6235.png">
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/130560/79117288-053c8580-7d8b-11ea-9726-4b700db3cff3.png">

- https://unicode-table.com/en/blocks/supplemental-symbols-and-pictographs/

<img width="1477" alt="image" src="https://user-images.githubusercontent.com/130560/79117479-81cf6400-7d8b-11ea-942e-688366f7f813.png">

- https://dn-works.com/wp-content/uploads/2020/UFAS-Docs/Symbola.pdf

**Comment by be5invis** [comment]
Mark as “Needs Justification”.

**Comment by be5invis** [comment]
**I really really do not think this is a good idea.**
Emoji is essentially a complex script and may take > 20000 glyphs to fully implement it.
This should be done with some third-party fonts and, well if that font exists, I can write some script to integrate it into a special version of Iosevka — just like Nerd fonts?

**Comment by akarzim** [comment]
I didn't know about nerd fonts, thanks for pointing that out!

And you're right, the emoji is a huge set of glyphs that would only be useful in very rare situations. Moreover, these situations include programming specific glyphs that are not part of the official Unicode standard. The use cases I see are shell prompts and terminal-based applications like Vim or Mutt.

**Comment by paolobolzoni** [comment]
> This should be done with some third-party fonts and, well if that font exists, I can write some script to integrate it into a special version of Iosevka — just like Nerd fonts?

How difficult is to merge two fonts (like Iosevka and Nerd)? Can you give some pointers? I'd really like to have a all integrated from for my shell.

**Comment by wimstefan** [comment]
> How difficult is to merge two fonts (like Iosevka and Nerd)? Can you give some pointers? I'd really like to have a all integrated font for my shell.
There is quite abundant information about it in the [Nerd Fonts repository](https://github.com/ryanoasis/nerd-fonts#font-patcher) - did you try that already?

**Comment by paolobolzoni** [comment]
In the Nerd repository I saw how to add the icons, but for example how can I merge Iosevka and IPAex Mincho ensuring that each japanese character is exactly twice as wide as each european letter?

**Comment by wimstefan** [comment]
> In the Nerd repository I saw how to add the icons, but for example how can I merge Iosevka and IPAex Mincho ensuring that each japanese character is exactly twice as wide as each european letter?

I'm afraid I can't help you with that specific issue ...

**Comment by eternaleye** [comment]
Some of these symbols may merit support individually, rather than en masse - e.g. Raku (neé Perl 6) has a [family of operators](https://docs.raku.org/type/atomicint#Operators) based on `U+269B ⚛ ATOM SYMBOL` for atomic operations. [This page](https://docs.raku.org/language/unicode_ascii) summarizes Raku's use of unicode.

**Comment by throwaway571** [comment]
> In the Nerd repository I saw how to add the icons, but for example how can I merge Iosevka and IPAex Mincho ensuring that each japanese character is exactly twice as wide as each european letter?

@paolobolzoni Why not just use Sarasa Gothic?

**Comment by paolobolzoni** [comment]
@throwaway571 
That's why: https://github.com/be5invis/Sarasa-Gothic/issues/134

**Comment by be5invis** [comment]
Closing as out of scope. Again, it is not a goal for Iosevka in a reasonable time frame.
If certain programming system used some of the symbols please file a separate issue to track it.

**Comment by nalply** [comment]
I found a way with the foot terminal: use Noto Emoji as font fallback for emojis. I am sure, modern editors and terminals can configure font fallbacks. This seems to be a better solution anyway because this allows more flexible combination of font features.

 So no need for Iosveka to include emojis!
