### ISSUE TITLE
Add glyphs for Mahjong, Domino, Playing Cards, Dice, etc.

### ISSUE THREAD

**Issue by akarzim** [be5invis/Iosevka#495]
* Your font version: 3.0.0-rc6
* Your font variant: custom sp-term with dlig on
* Your operating system (name and version): macOS 10.15.3
* Your application using Iosevka: iTerm + Neovim

---

In the vein of emojis and symbol support (#494), how about support for mahjong, domino, chess and playing cards characters?

<img width="1550" alt="image" src="https://user-images.githubusercontent.com/130560/79115879-4fbc0300-7d87-11ea-9f05-02bb8c2d907c.png">
<img width="702" alt="image" src="https://user-images.githubusercontent.com/130560/79115898-5f3b4c00-7d87-11ea-9053-d8bc277de6ed.png">

- https://unicode-table.com/en/blocks/mahjong-tiles/
- https://unicode-table.com/en/blocks/domino-tiles/
- https://unicode-table.com/en/blocks/playing-cards/

<img width="1468" alt="image" src="https://user-images.githubusercontent.com/130560/79117395-49c82100-7d8b-11ea-88b3-882f4026ed7d.png">

- https://dn-works.com/wp-content/uploads/2020/UFAS-Docs/Symbola.pdf

**Comment by be5invis** [comment]
Mark as “Needs Justification”.
