### ISSUE TITLE
Traditional szlig in Aile/Etoile

### ISSUE THREAD

**Issue by eiszfuchs** [be5invis/Iosevka#496]
I noticed that Aile/Etoile lack some character variants that made Iosevka stand out - at least for me, especially the traditional glyph for ß (szlig). It would mean the world to me if we could get this stylistic alternative in Aile/Etoile, too, if it is not too much to ask for. ❤️

**Comment by juarezr** [comment]
Yet another reference: [How to draw a Capital Sharp S](https://typography.guru/journal/how-to-draw-a-capital-sharp-s-r18).

**Comment by be5invis** [comment]
Move into #776. Closing.
