### ISSUE TITLE
Wrong glyph for U+1DF0 COMBINING LATIN SMALL LETTER U WITH LIGHT CENTRALIZATION STROKE

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#497]
* Your font version: 3.0.0-rc.6
* Your font variant: Extended
* Your operating system (name and version): macOS 10.14.6
* Your application using Iosevka: hb-view

---

U+1DF0 COMBINING LATIN SMALL LETTER U WITH LIGHT CENTRALIZATION STROKE is based on U+03BC GREEK SMALL LETTER MU, but a centralization stroke is diagonal, whereas the leg of a mu is vertical. (Without the rest of the Teuthonista phonetic symbols, supporting U+1DF0 isn’t particularly useful anyway.)
![uᷰ](https://user-images.githubusercontent.com/1124347/79243691-f4037f80-7e43-11ea-84bc-997563a1b0bf.png)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/79289494-3d70c080-7e7e-11ea-9f55-899be73e019e.png)
Fixed
