### ISSUE TITLE
Ḩḩ cedilla coming from the left leg

### ISSUE THREAD

**Issue by AlsoScratch** [be5invis/Iosevka#499]
I've been a bit indecisive about this one but the fonts I see that support this character have the cedilla coming from the left leg:

_Source Code Pro_
<img width="43" alt="Screenshot 2020-04-18 at 9 30 28 PM" src="https://user-images.githubusercontent.com/48752273/79639079-d7f13c80-81bb-11ea-8608-93181520ac04.png">
<img width="42" alt="Screenshot 2020-04-18 at 9 31 00 PM" src="https://user-images.githubusercontent.com/48752273/79639092-eb040c80-81bb-11ea-8d87-c3f3f291f601.png">

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/79641237-13075780-814b-11ea-97a9-9daf62fc1752.png)
Fixed.
