### ISSUE TITLE
Full block U+2588 █

### ISSUE THREAD

**Issue by mkarmona** [be5invis/Iosevka#50]
IMHO full block has to be [fully joined](https://en.wikipedia.org/wiki/Block_Elements), but there is a vertical gap between two lines. (Left: iosevka tweaked params. Right: iosevka original)
![iosevka-mod-and-blocks](https://cloud.githubusercontent.com/assets/5394232/12224818/74dee9be-b7f1-11e5-972d-9102bb6298aa.png)

**Comment by be5invis** [comment]
I think it is rounding error rather than a bug.
