### ISSUE TITLE
Combining small capitals have capital glyphs

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#500]
* Your font version: 3.0.0-rc.7
* Your font variant: Iosevka Extended
* Your operating system (name and version): macOS 10.14.6
* Your application using Iosevka: hb-view

---

Combining small capital Latin letters (U+1DDB, U+1DDE, U+1DDF, U+1DE1, and U+1DE2) are rendered as combining capital letters. Here they are, beside U+036F COMBINING LATIN SMALL LETTER X to show the x-height.
![xͯxᷛxᷞxᷟxᷡxᷢ](https://user-images.githubusercontent.com/1124347/79640693-e0685980-8160-11ea-939f-14ba96e1236d.png)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/79641006-c1120200-8149-11ea-9e90-9e8fbf09c263.png)
Fixed.
