### ISSUE TITLE
Wrong glyph for U+228E MULTISET UNION

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#501]
* Your font version: 3.0.0-rc.7
* Your font variant: Iosevka Extended
* Your operating system (name and version): macOS 10.14.6
* Your application using Iosevka: hb-view

----

The glyph for U+228E MULTISET UNION should have a plus sign instead of a dot. The current glyph would be appropriate for U+228D MULTISET MULTIPLICATION.
![⊎](https://user-images.githubusercontent.com/1124347/79642035-2aedd400-8169-11ea-907f-421ed45eec78.png)

**Comment by be5invis** [comment]
Fixed.
