### ISSUE TITLE
Extra hook on Cyrillic digraph uk

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#503]
* Your font version: 3.0.0-rc.7
* Your font variant: Iosevka Extended
* Your operating system (name and version): macOS 10.14.6
* Your application using Iosevka: hb-view

----

The glyphs for U+0478 CYRILLIC CAPITAL LETTER UK and U+0479 CYRILLIC SMALL LETTER UK have hooks on the u. They are supposed to look like the sequences <U+041E CYRILLIC CAPITAL LETTER O, U+0443 CYRILLIC SMALL LETTER U> and <U+043E CYRILLIC SMALL LETTER O, U+0443 CYRILLIC SMALL LETTER U> (or, more traditionally, <U+1C82 CYRILLIC SMALL LETTER NARROW O, U+0443 CYRILLIC SMALL LETTER U>), so if U+0443 has no hook, neither should they.
![уѸѹ](https://user-images.githubusercontent.com/1124347/79700804-805bdb00-8266-11ea-8768-071842c6924a.png)

**Comment by be5invis** [comment]
Fixed.
