### ISSUE TITLE
R-stroke (u+024c) error

### ISSUE THREAD

**Issue by AlsoScratch** [be5invis/Iosevka#504]
At weight 1 there is an obvious seam
<img width="128" alt="Screenshot 2020-04-21 at 2 31 50 PM" src="https://user-images.githubusercontent.com/48752273/79832883-ee2a1300-83dc-11ea-9e40-6a6474bc3892.png">

At weight 2–3 the seam is less obvious but still there if you look closely
<img width="113" alt="Screenshot 2020-04-21 at 2 37 38 PM" src="https://user-images.githubusercontent.com/48752273/79833411-e7e86680-83dd-11ea-8277-7fcc86bab5dd.png"><img width="93" alt="Screenshot 2020-04-21 at 2 40 19 PM" src="https://user-images.githubusercontent.com/48752273/79833673-5d543700-83de-11ea-86fc-0c5dbda917fd.png">

At 5+ that problem is gone but there's a new one

From there onwards, the bar begins to disappear behind the stem (to me it becomes bad at 6+)
and at 9 it glitches out completely
<img width="96" alt="Screenshot 2020-04-21 at 3 16 43 PM" src="https://user-images.githubusercontent.com/48752273/79836720-20d70a00-83e3-11ea-9174-813ea0cbac2a.png">

After you provide a fix please show me what it looks like in all weights.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/79860500-9ca36900-8387-11ea-84d5-8837d7d02e4d.png)
![image](https://user-images.githubusercontent.com/240091/79860568-b775dd80-8387-11ea-8a61-0ed21841d7d1.png)
![image](https://user-images.githubusercontent.com/240091/79860558-b2189300-8387-11ea-95d2-fb1dc3b1ec58.png)

Fixed.

**Comment by AlsoScratch** [comment]
There are 9 weights in total. Can I see them all?
