### ISSUE TITLE
Wrong glyph for U+21B9 LEFTWARDS ARROW TO BAR OVER RIGHTWARDS ARROW TO BAR

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#505]
* Your font version: 3.0.0-rc.7
* Your font variant: Iosevka Extended
* Your operating system (name and version): macOS 10.14.6
* Your application using Iosevka: hb-view

----

The glyph for U+21B9 LEFTWARDS ARROW TO BAR OVER RIGHTWARDS ARROW TO BAR is reversed.
![↹](https://user-images.githubusercontent.com/1124347/79891353-dfd4fa80-83ce-11ea-8278-25e33d0445e0.png)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/79927856-efb40500-83f5-11ea-8c77-909856a23278.png)
