### ISSUE TITLE
IPA tone letters

### ISSUE THREAD

**Issue by throwaway571** [be5invis/Iosevka#508]
The characters in the range U+02E5–U+02E9 represent tones in the IPA, from extra high (˥) to extra low (˩). These are meant to form ligatures with each other to graphically represent the contour of the tone, as shown in the following image. These are not optional typographical ligatures, they are the solution Unicode came up with to encode the potentially infinite space of tone contours.
![image](https://user-images.githubusercontent.com/62322214/80022765-64884d00-8491-11ea-9cba-012e5f634a0a.png)

The only monospace font I’ve found that both supports them and renders them properly is Consolas, and there, two- and three-character ligatures are rendered within a single character space.

**Comment by be5invis** [comment]
Mark as a post-3.0 feature.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/82187684-9da1ba80-98a1-11ea-82ff-0f7ecb5db7d1.png)
It now look slike this — Note that I kept the widths unchanged.

**Comment by be5invis** [comment]
It can surely handle such cases:
![image](https://user-images.githubusercontent.com/240091/82188212-6253bb80-98a2-11ea-9d67-9c7849f415ef.png)
