### ISSUE TITLE
Iosevka Fixed Curly has the wrong style for '@'

### ISSUE THREAD

**Issue by al2me6** [be5invis/Iosevka#509]
* Your font version: 3.0.0-rc7
* Your font variant: Fixed Curly
* Your operating system (name and version): Arch Linux
* Your application using Iosevka: N/A

According to the stylistic sets chart, the curly variant should have the default style (cv31) `@`. (Regular Iosevka Fixed also has cv31.) However, it is actually using cv32:

![image](https://user-images.githubusercontent.com/35266431/80169401-49adf980-85b3-11ea-92a2-64ae00f8b678.png)

**Comment by be5invis** [comment]
Fixed. Will be there in next release.

**Comment by al2me6** [comment]
Wow, thank you for the quick response!
