### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by mkarmona** [be5invis/Iosevka#51]
This [var](https://github.com/be5invis/Iosevka/blob/master/glyphs/symbol-punctuation.ptl#L156) is used without definition. I supose this var has to be defined as [this line](https://github.com/be5invis/Iosevka/blob/master/glyphs/symbol-punctuation.ptl#L154).

After supposedly fix it, the compiltion process fails at this point:

``` bash
  onegroup.mk:113: recipe for target 'build/.pass1-iosevka-light.ttf' failed
  make[1]: *** [build/.pass1-iosevka-light.ttf] Error 139
  make[1]: Leaving directory '/home/mkarmona/sources/Iosevka'
  makefile:23: recipe for target 'fonts-default' failed
```

**Comment by mkarmona** [comment]
ok, it was my fault. Something wrong with my merge. Let me check the compilation process.

**Comment by mkarmona** [comment]
Yes, it was my fault.

**Comment by mkarmona** [comment]
Ok, confirmed. When I use these params compilation fails with the messege I posted in my first comment:

```bash
leading = 1210
width = 520
```

**Comment by be5invis** [comment]
@mkarmona
Your parameter will produce NaN values of control points for /supturnae (`ᵆ`).
Version 1.7.1 will contain:
* A proper fix to eliminate NaN values produced by `[hookend]`
* A patch to suppress NaN values in SVG.
