### ISSUE TITLE
No U+1D0D LATIN LETTER SMALL CAPITAL M in 3.0.0-rc.8

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#510]
* Your font version: 3.0.0-rc.8
* Your font variant: Iosevka Extended
* Your operating system (name and version): macOS 10.14.6
* Your application using Iosevka: hb-view

---

Support for U+1D0D LATIN LETTER SMALL CAPITAL M was dropped in version 3.0.0-rc.8, most likely in 3150ca118cb57fb7ca9b1fd68b8915fa13ffbd7d.

**Comment by be5invis** [comment]
Oh I moved `smcpM` to `letters-unified-basic` but fotgot to add the unicode mapping back.

**Comment by be5invis** [comment]
Fixed.
