### ISSUE TITLE
Rationale for double-wide glyphs being in the Default spacing?

### ISSUE THREAD

**Issue by sharpjs** [be5invis/Iosevka#511]
Can you explain the rationale for introducing double-wide glyphs in the _Default_ spacing of `3.0.0-rc.1`, as opposed to putting them in a _Double_ variant?

Respectfully, I disagree with the choice.  How much my sentiment is based on any actual insight, rather than personal preference or lack of understanding, I don't know.  Specifically, I am one of those programmers who meticulously add spaces to align code elements vertically in harmony with the lines above and below.  I maintain that code so aligned is more readable.

```csharp
var foo = 1;
var barBaz = 789;
var quux = 0xF00F;
```
vs.
```csharp
var foo    =   -1;
var barBaz =  789;
var quux   = 0xFF;
```

Given the stated mission,

> The default Iosevka family's spacing is also updated to focus on code editing solely.

the _Default_ spacing introduces some seemingly (to me) counterproductive aspects.

---

**First,** the double-wide glyphs render inconsistently across programs

* Visual Studio 2019 (16.5.4) on Windows 10 (19041.208)\
![image](https://user-images.githubusercontent.com/708461/80230717-2ad95280-8607-11ea-9e5c-a112e48a7883.png)

* Windows Terminal (0.11.1121.0) on Windows 10 (19041.208)\
![image](https://user-images.githubusercontent.com/708461/80231987-05e5df00-8609-11ea-89df-9a961fbb2fd2.png)

* MinTTY 3.1.0 on Windows 10 (19041.208)\
![image](https://user-images.githubusercontent.com/708461/80233666-b9e86980-860b-11ea-88af-c773e2c0a7b1.png)

* Terminal on macOS 10.15.3\
![e34c37b7-6f91-4b5c-9bbd-bae05b9fe640](https://user-images.githubusercontent.com/708461/80234388-f1a3e100-860c-11ea-9ff1-feea1a16e23d.jpg) ![10a49361-12a0-4f81-ac87-88ae85680d0f](https://user-images.githubusercontent.com/708461/80234462-10a27300-860d-11ea-95c3-1c66d1881100.jpg)

---

**Second,** code vertically aligned with Iosevka will be misaligned when viewed in non-Iosevka environments when the line contains a double-wide glyph:

This text in Iosevka:\
![image](https://user-images.githubusercontent.com/708461/80235001-e7cead80-860d-11ea-8269-dc158120b18a.png)

Presents on GitHub as:\
![image](https://user-images.githubusercontent.com/708461/80235067-08970300-860e-11ea-95ba-898f927176c9.png)

---

Of course, I could simply use the *Term* spacing to solve both of these problems.  I do exactly that currently.  My concern with that path is twofold:

* The *Default* variant is what most new users will install.  If the font has perceived rendering faults (regardless of whether it's the program to blame), then new users are likely to uninstall Iosevka and not try the *Term* variant.  If installed via, say, a package manager, users might not even be aware of *Term*.  **In my opinion, it is better to have the *Term* variant be the default.**  Prefer "arrows are too tiny" to "arrows don't render correctly".  For example:

  Variant | Double-Wides | Ligatures
  --|:--:|:--:
  _Default_ | - | Yes
  _Double_ | Yes | Yes
  _Fixed_ | - | -

  (I'm not good at names.)

* I am (perhaps irrationally) worried that the *Term* variant will be discontinued some day.

My goal with this issue is not to revert the change — just to understand it.  I suspect you have considered these issues at length already and made the decision with full knowledge of the trade-offs.

Again, I submit this issue with the utmost respect.  Thank you for your tireless work on Iosevka.  I remain a patron regardless of any action taken (or not taken) in response to this issue.

**Comment by be5invis** [comment]
I will not discontinue Term, and all these problems is why I **keep** Term.

**Comment by be5invis** [comment]
Ideally, if an editor / terminal emulator has an assumption of characters' width, it could apply certain OpenType features (`NWID`/`WWID` in Iosevka) to request the desired glyphs. Though, there's no applications doing that yet.

**Comment by be5invis** [comment]
I'd like to do this:
  * The default will still have "wide" arrows. This IS by design and won't be changed during 3.x versions.
  * However I'll leverage the "collection export", so starting from the next release, users will download the package containing all spacing variants ("wide", Term and Fixed) by default. This will improve the discoverability of Term and Fixed variants.
    * The existing single-group packages will be still be provided.
    * The collection packages will also contain the TTC files.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/80270062-e03cf200-8669-11ea-9ca2-e77274657a33.png)
Contents in a collection package will look like this.

![image](https://user-images.githubusercontent.com/240091/80270074-f5b21c00-8669-11ea-8189-47af5b3c5cbe.png)
Inside the `ttf` directory you will have every spacing variants.

**Comment by be5invis** [comment]
Close as mitigated.

**Comment by sharpjs** [comment]
Thank you for the responses, @be5invis.  My concerns have been fully addressed:
- The double-width glyphs are by design and will remain the default. ✔️
- Term isn't going away, so stop the irrational worrying, @sharpjs. 😄 ✔️

Also, I discovered that in the Default spacing, **U+2001 is a double-wide space**.  That makes it possible to align vertically in the Default spacing and have it continue to align in most non-Iosevka environments.  That largely invalidates my second argument.

Thanks again for taking the time to consider my questions and concerns.

**Comment by be5invis** [comment]
@sharpjs Well if you need em-space, U+2003 EM SPACE is preferred. Though some programming languages may not support using these fancy spaces.
Another solution may be [elastic tabstops](http://nickgravgaard.com/elastic-tabstops/) so you can even use proportional fonts in code editing. Some editors implemented this.

**Comment by sharpjs** [comment]
Ah, I'll use U+2003 instead if I'm in that situation and the language supports it.  Most languages should at least allow it in comments.
