### ISSUE TITLE
Soft-dotted characters with hard-dotted glyphs

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#513]
* Your font version: 3.0.0-rc.8
* Your font variant: Iosevka Extended
* Your operating system (name and version): macOS 10.14.6
* Your application using Iosevka: hb-view

---

Some [Soft_Dotted](https://www.unicode.org/Public/13.0.0/ucd/PropList.txt) characters’ dots are not being removed in the presence of above-base marks, such as U+1AB2 COMBINING INFINITY:

* U+029D LATIN SMALL LETTER J WITH CROSSED-TAIL
* U+02B2 MODIFIER LETTER SMALL J
* U+1D62 LATIN SUBSCRIPT SMALL LETTER I
* U+1DA4 MODIFIER LETTER SMALL I WITH STROKE
* U+1DA8 MODIFIER LETTER SMALL J WITH CROSSED-TAIL
* U+2071 SUPERSCRIPT LATIN SMALL LETTER I
* U+2C7C LATIN SUBSCRIPT SMALL LETTER J

![ʝ᪲ʲ᪲ᵢ᪲ᶤ᪲ᶨ᪲ⁱ᪲ⱼ᪲](https://user-images.githubusercontent.com/1124347/80314613-8438b180-87c0-11ea-8dc3-f3fea613c64d.png)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/80330166-4ad06800-87f9-11ea-96dd-9f1896a56fe7.png)
Fixed
