### ISSUE TITLE
No styling in Bulgarian, Macedonian, or Serbian

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#514]
* Your font version: 3.0.0-rc.8
* Your font variant: Iosevka Extended
* Your operating system (name and version): macOS 10.14.6
* Your application using Iosevka: hb-view

---

Only the default style is available in text tagged as Bulgarian, Macedonian, or Serbian. That is because the font includes the language system tags 'BGR ', 'MKD ', and 'SRB ' but only uses them with the 'locl' features. All other lookups use only 'dflt', which excludes those three. For example, here is ⟨д0⟩ with 'ss01' in no language:
![д0](https://user-images.githubusercontent.com/1124347/80415029-e74d4580-889f-11ea-855b-6427ba76abd0.png)
and ⟨д0⟩ with 'ss01' in Bulgarian:
![д0](https://user-images.githubusercontent.com/1124347/80414952-ce449480-889f-11ea-8da5-1df08f3ddd34.png)

**Comment by be5invis** [comment]
Fixed.
