### ISSUE TITLE
Styles do not apply to all closely related characters

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#516]
* Your font version: 3.0.0-rc.8
* Your font variant: Iosevka Extended
* Your operating system (name and version): macOS 10.14.6
* Your application using Iosevka: hb-view

---

Many styles apply to certain characters but not to others closely related to them. For example, 'cv84' adds a baseline serif to U+0066 LATIN SMALL LETTER F but not to U+24A1 PARENTHESIZED LATIN SMALL LETTER F.
![f⒡](https://user-images.githubusercontent.com/1124347/80556464-9f164c00-89a1-11ea-869a-cf95443c5842.png)
If you agree that groups of similar characters should be styled consistently, I can compile a list of the groups I think this issue applies to.

**Comment by be5invis** [comment]
This will need a major change to the auto-build system that generates them.
Mark as post-3.0.0 feature request.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/82776819-0e485a00-9e01-11ea-9893-70dd7f064a2a.png)
