### ISSUE TITLE
Adding option for straight equal sign ligature

### ISSUE THREAD

**Issue by crides** [be5invis/Iosevka#518]
Hi, I really like Iosevka for its sleekness. The ligatures are great for programming. One thing I always want is straight lines for equal sign ligatures, without the little gap on the character boundaries. On lower resolution displays, the gap (or however it's called) will be more obvious and look more like separate characters. On higher resolution screens, this is probably fine. So is it possible to add a variant for those ligatures but without the white gaps and add a option for the variant?

**Comment by crides** [comment]
Just to illustrate the problem for others, these are some screenshots of the problem:

![maim-2020-05-04--01-26-36](https://user-images.githubusercontent.com/15631555/80940908-a45f0680-8da6-11ea-9750-f52349d93884.png)
![maim-2020-05-04--01-29-16](https://user-images.githubusercontent.com/15631555/80940977-d4a6a500-8da6-11ea-95b5-78d31971280e.png)

**Comment by be5invis** [comment]
This is what it looks like at 12ppem, and the gap is almost invisible.
Since it may be hinting / metric rounding related, you can try increase/decrease the text size by 1 pixel or use the unhinted version.
![image](https://user-images.githubusercontent.com/240091/82282819-8cac8400-9949-11ea-82f0-b7292bdbb0cb.png)

**Comment by be5invis** [comment]
I've submitted a change that makes `==` ligatures overlap more to avoid gaps under small text size. You could grab the `dev` branch and test whether this works.

**Comment by crides** [comment]
It does seem like reducing or increasing font sizes help, but when the gaps disappear other characters also happen to squeeze closer together, which is probably the reason why the gaps disappear.

I'll try out the `dev` branch tomorrow, as I don't have the build tools right now.

**Comment by be5invis** [comment]
@crides You can try out this package to see whether it works.

[iosevka-dev-ttf.zip](https://github.com/be5invis/Iosevka/files/4648270/iosevka-dev-ttf.zip)

**Comment by crides** [comment]
Great, I can confirm that is working. One thing though, the two lines seems to be closer together. Is that from the 3.0 versions? I was using 2.3.3 (last I checked was the one before 3.0) and didn't upgrade.

**Comment by be5invis** [comment]
This will be landed in 3.1.
Closed as fixed.
