### ISSUE TITLE
Adding Rambla like style for small letter 'f'

### ISSUE THREAD

**Issue by wimstefan** [be5invis/Iosevka#519]
I really love the configurability of Iosevka which enables us to mold the font to our personal likings. Thank you so much for this @be5invis !!! 🙏🏽

That also means that I dare to offer some suggestions for single letters that I like from other fonts 😏
The next on my list is a Rambla like 'f' style with a stem as long as the v-f-tailed style but straight and without bottom tail. 

Here's an image from the Ramba letter 'f':
![rambla-letter-f](https://user-images.githubusercontent.com/4605934/80913835-ed33a280-8d47-11ea-9cc7-1a97bd034619.png)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/82997522-53b08700-9fbb-11ea-9c10-006496951f46.png)

**Comment by wimstefan** [comment]
Wonderful!
Thank you so much :) 
And it's only by now that I've noticed that the horizontal stroke is a little bit underneath the x-height line ... but that's common to all variants of 'f' so I guess that's by design ;-)
