### ISSUE TITLE
Underscore character rendering problems

### ISSUE THREAD

**Issue by v-chernyshev** [be5invis/Iosevka#520]
* Your font version: iosevka-term-ss08-3.0.0-rc.8
* Your font variant: Regular
* Your operating system: Windows 10, Version 10.0.18363 Build 18363
* Your application using Iosevka: wsltty 3.1.4.2

I've recently upgraded from RC4 to RC8 and have noticed that the `_` character stopped rendering at font size 11. The steps to reproduce for me are:

- Install the latest SS08 term font for all users.
- Download and install the latest version of wsltty from https://github.com/mintty/wsltty/releases. I assume that the WSL subsystem is already set up.
- Launch WSL Terminal, right-click anywhere in the window, pick Options -> Text and select Iosevka Term SS08 - Regular - Size 11.
- Run `vim`.
- Try to type `_`, the character doesn't render for me, the output is blank.

Quite surprisingly, size 10 works fine and there are no problems with size 11 for e.g. Iosevka Term SS02. Admittedly I don't know if this problem is due to the font or there's a bug in wsltty, but as mentioned before everything was fine when I used the RC4 version of the font instead of RC8.

**Comment by be5invis** [comment]
It should be clipping? Does MinTTY suport increasing line height? That should be able fix this.

**Comment by v-chernyshev** [comment]
Yep, that's clipping indeed, thanks! `mintty` does have configurable line height:

> Vertical spacing adjustment (`RowSpacing = 0`)
>
> Additional row padding.
>
> Note: Mintty adjusts row spacing according to the font metrics, to compensate for tight or tall spacing of some fonts (e.g. Courier, Consolas, FreeMono, Monaco). The `RowSpacing` value is added to that.

So whatever logic they have to support automatic detection of the line height broke when I upgraded the font from RC4 to RC8. Setting `RowSpacing` to 1 fixes the problem for me.

**Comment by be5invis** [comment]
Fonts' built-in line height is a total mess... Every application has its own quirk.
Closed as external.
