### ISSUE TITLE
Add support for WHITE SUN WITH RAYS (U+263c, ☼)

### ISSUE THREAD

**Issue by gnuvince** [be5invis/Iosevka#521]
* Your font version: **3.0.0-rc8**
* Your font variant: **Custom, Term**
* Your operating system (name and version): **Linux, Debian 10**
* Your application using Iosevka: **mate-terminal**

In the roguelike [Dungeon Crawl: Stone Soup](https://github.com/crawl/crawl), the character `U+263c` can be used to display a fading cloud (e.g., a fading fire or a dissipating poisonous cloud). This character is currently not support in Iosevka. Could a design be created for it and added in a future release?

**Screenshot \#1: Source Code Pro (which has support for U+263c)**

![2020-05-04-161132_1442x927_scrot](https://user-images.githubusercontent.com/39868/81009175-22acbe80-8e22-11ea-960e-4d177a47b41e.png)

**Screenshot \#2: Iosevka**

![2020-05-04-161206_1202x902_scrot](https://user-images.githubusercontent.com/39868/81009210-322c0780-8e22-11ea-83f9-051eef126a1a.png)

Thank you for your hard work!

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/82406177-c8fbe500-9a1a-11ea-88ac-55ee0a09b2a8.png)
Fixed. You will get both wide and narrow variants.
In the Term subfamily the narrow one will be used.
