### ISSUE TITLE
v-l-serifed top serif is too similar to the number 1

### ISSUE THREAD

**Issue by mustaqimM** [be5invis/Iosevka#522]
* Your font version: `version 3.0.0-rc.8`
* Your font variant: `sp-term`

---

Describe your problem here. Provide pictures and files if necessary.

The top serif of the letter `l` looks too similar to the number `1`.

Pragmata Pro
![Pragmata](https://user-images.githubusercontent.com/24436622/81042150-000cbb00-8e9f-11ea-979e-4904b1f7b58c.png)

Iosevka
![image](https://user-images.githubusercontent.com/24436622/81042073-e1a6bf80-8e9e-11ea-9468-6f22aaf0c8b2.png)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/89005853-4fa22d80-d2ba-11ea-8199-cc496e39b5aa.png)
Added a new variant `v-l-serifed-asymmetric` so this could get resolved.
