### ISSUE TITLE
How do I change Ligations to JavaScript

### ISSUE THREAD

**Issue by sebbonit** [be5invis/Iosevka#523]
* Your font version:  v3.0.0-rc.8
* Your font variant: 07-iosevka-curly-3.0.0-rc.8.zip
* Your operating system (name and version): MacOS 10.13
* Your application using Iosevka: VsCode

I can't exactly understand this font, I'd love to change my ligations to Javascript eg. === will be 3 lines (I have only two right now)
If someone could help me I'd much appreciate it, thanks.

**Comment by be5invis** [comment]
If you are using VSCode you can do this in your user settings:
```
"[javascript]": {
	"editor.fontLigatures": "'calt' off, 'JSPT' on"
}
```
Note: `'calt' off` is required to avoid ligation conflicts.
