### ISSUE TITLE
v-middle-caret request

### ISSUE THREAD

**Issue by paolobolzoni** [be5invis/Iosevka#526]
Inspired by #515 I would ask for a circumflex ^ lower than ```v-caret-high``` but higher than ```v-caret-low```. Basically the peak of the ```^``` symbol would aligned to the top of the capital M as in many other fonts.

**Comment by be5invis** [comment]
I think for `caret` we can just modify `v-caret-low`. It is too low now and needs some elevation.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/82281059-3b01fa80-9945-11ea-86dd-d2825f243e76.png)

**Comment by paolobolzoni** [comment]
My main problem with the low caret is that looks similar to the low tilde, so unless someone really loves the current status `v-caret-low` I agree with the change.

**Comment by be5invis** [comment]
Since this is issue is mainly about legibility of low `^`, I'd like to close this for now.

**Comment by paolobolzoni** [comment]
So be it.

**Comment by AlsoScratch** [comment]
Is this in 3.0.1?

**Comment by be5invis** [comment]
@AlsoScratch This is planned in 3.1.0.

**Comment by paolobolzoni** [comment]
![pngout](https://user-images.githubusercontent.com/1133562/86990092-c75acc00-c1d6-11ea-943f-5303d2658a89.png)

After using the new low caret I have to say I like it. But I still feel is a bit too low.

In the picture are how it is now on the top, and how I think it should be in the bottom. As you can see it is an hair higher, but it helps to separate it from the low tilde more.
