### ISSUE TITLE
shorter/more square variant?

### ISSUE THREAD

**Issue by pvinis** [be5invis/Iosevka#53]
hello. would that be of interest? can i already compile it?
i like fonts that are more square than tall.

**Comment by athlonUA** [comment]
this is monospaced font... Imagine what happens if font will be more square

**Comment by AluisioASG** [comment]
I think the idea is to make the font shorter, not wider.  Though maybe just changing the line height would be enough?

**Comment by felipezacani** [comment]
I would love that. Also, I think the "m" character should have more space between the vertical lines, the space is almost not visible in windows.

**Comment by athlonUA** [comment]
this is monospaced font...

**Comment by pvinis** [comment]
i meant what @AluisioASG said. i would like to have the font a bit shorter. is that possible? if i change the line height on my editor, it just looks crammed because the lines collide.

**Comment by be5invis** [comment]
@pvinis So you can decrease the `cap` and `xheight` in `parameters.toml`.

**Comment by jonhoo** [comment]
I'm surprised that you chose to close this as wontfix @be5invis. You already provide the `-medium`, `-light`, `-heavy` variants -- would it not also be possible to provide a `-short` variant? Like @pvinis and @AluisioASG, I also find the default settings to provide a font that's too tall and narrow (a sentiment it seems I'm [not](https://news.ycombinator.com/item?id=14012731) alone in).

**Comment by be5invis** [comment]
@pvinis @jonhoo @felipezacani @athlonUA 
Everything about the widths are moved to #196.

**Comment by be5invis** [comment]
@jonhoo There are aready two "hidden" styles, `expanded` and `compressed`, which widen and narrowen Iosevka by 15%. However glyphs under these styles (especially `expanded`) **would have problems** since they are designed to be narrow.
