### ISSUE TITLE
Iosevka Term Light shows the character "per mille sign" for codepoint 2026 (must be "horizontal ellipsis")

### ISSUE THREAD

**Issue by mc6312** [be5invis/Iosevka#531]
* Your font version: 3.0.0 (release)
* Your font variant: Iosevka Term Light
* Your application using Iosevka: XFCE Terminal.

Iosevka Term Light shows the character "per mille sign" - ‰ for codepoint 2026 (must be "horizontal ellipsis" - …)

**Comment by be5invis** [comment]
I've validated the font file and mapping of U+2026 is correctly to "horizontal ellipsis".
![image](https://user-images.githubusercontent.com/240091/82257339-ba270c80-990c-11ea-85ea-ba545f34683b.png)
It should be a font caching issue or your software doesn't correctly render the text.
Closed as external.
