### ISSUE TITLE
Bulgarian Cyrillic characters get Latin variants

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#532]
* Your font version: 3.0.0
* Your font variant: Extended
* Your operating system (name and version): macOS 10.14.6
* Your application using Iosevka: hb-view

---

In Bulgarian, five glyphs are replaced with glyphs for Latin letters whose default forms they happen to resemble. Some of the Latin glyphs have character variants or stylistic sets, and some of these variants are inappropriate for Cyrillic.

Here are U+0434 CYRILLIC SMALL LETTER DE by default and with 'cv11' and 'cv24'.
![ддд](https://user-images.githubusercontent.com/1124347/82218909-98b52900-98ea-11ea-8b4d-6741f79c76c2.png)

Here are U+0438 CYRILLIC SMALL LETTER I and U+0439 CYRILLIC SMALL LETTER SHORT I by default and with 'cv90'.
![ийий](https://user-images.githubusercontent.com/1124347/82219625-8d163200-98eb-11ea-85cd-dffcf82b0409.png)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/82278948-3edf4e00-9940-11ea-9077-c38ddefda7ed.png)
Fixed.
