### ISSUE TITLE
Please provide better proportional fonts

### ISSUE THREAD

**Issue by bill-myers** [be5invis/Iosevka#534]
Iosevska's approach is awesome: the creation of an ultimate font that can replace all other monospace fonts by being the union of them and thus being strictly better than them.

However, proportional fonts are more efficient in terms of information per screen space, so it's important to provide an ultimate proportional font as well; however, the semi-proportional Iosevka fonts are severely lacking, missing character variants and especially character variants with different width (e.g. narrower "t" and "j").

It would be nice to have proportional fonts as good and flexible as the monospace ones.

**Comment by be5invis** [comment]
The quasiproportionals' goal is not replacing fonts like Helvetica or Inter. It is still targeting technical writing use cases. And currently I disabled variants on purpose since many of them will generate broken shape under quasiproportionals' metrics.

**Comment by MMMikeM** [comment]
Hi be5invis, really loving the quasi-proportional options. In VS code it is possible to select a different font style for different scopes. Is it possible to build, for example, the oblique variant of a standard family, such as slab, as one of the quasi-proportional versions of the font? I would love to use it for comments and strings.
