### ISSUE TITLE
Past GitHub Release entries all pointing to the latest stylesets.png

### ISSUE THREAD

**Issue by vszakats** [be5invis/Iosevka#535]
As in title, e.g.:
<https://github.com/be5invis/Iosevka/releases/tag/v2.3.3> now shows the image for 3.0.0.

Using the image link below would fix this:
<https://github.com/be5invis/Iosevka/blob/319b7e4a488ce298bd3ea2bd581cdc6ad7f5c793/images/stylesets.png> (where `319b7e4a488ce298bd3ea2bd581cdc6ad7f5c793` is the commit hash of the given release.)

**Comment by be5invis** [comment]
I can fix this for 3.0.1 and later, but for past releases, there are 137 of them currently. Edit all of them by hand?

**Comment by vszakats** [comment]
I think sticking to the versioned link in the future should solve this nicely. Or perhaps for 2.3.3 — I went there to lookup which 3.0.0 variant matches the previous stable release that I had installed.

And most importantly: Thank you for this font, it's truly great!

**Comment by be5invis** [comment]
@vszakats I've updated the messages for 2.3.3 and 3.0.0. Future releases will have the images pinned to their corresponding tag.

**Comment by vszakats** [comment]
It's looking good! — Thank you @be5invis!
