### ISSUE TITLE
update brew install file to v3

### ISSUE THREAD

**Issue by razagill** [be5invis/Iosevka#536]
Please update the homebrew file for the latest version `3.0`.

The current version at `brew cask install font-iosevka` is `2.3.3` as stated here https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-iosevka.rb

**Comment by georgianfire** [comment]
Shouldn't this issue be submitted the the `homebrew/homebrew-cask-fonts` repo instead?

**Comment by georgianfire** [comment]
While I was looking at how the homebrew cask can be patched I realized it was relying on the separate ttc packages which are missing in the v3.0.0. This has made patching homebrew non-trivial. Therefore I have opened #537 discussing this issue.

**Comment by be5invis** [comment]
Please file issue at the cask rather than here. I do not maintain *any* packages in *any* package manager. TTC packages needed by @georgianfire is added in 3.0.1.
Closed.

**Comment by alindeman** [comment]
https://github.com/Homebrew/homebrew-cask-fonts/pull/2044
