### ISSUE TITLE
Separate TTC packages missing in release v3.0.0

### ISSUE THREAD

**Issue by georgianfire** [be5invis/Iosevka#537]
Until 3.0.0-rc8 there used to be separate `ttc-iosevka-${variant}-${version}.zip` packages provided in the release assets. While in 3.0.0 the ttc file are only included in the `pkg-iosevka-${variant}-${version}.zip`. Can someone please shed some light on the rationale behind this change?

I'm looking for ttc packages because some package managers depend on those to install iosevka. For example, [homebrew](https://github.com/Homebrew/homebrew-cask-fonts/blob/f8b612bb8d78f34a6f52b920e4ba5aaa35331b37/Casks/font-iosevka.rb) and [void linux](https://github.com/void-linux/void-packages/blob/fd6825ef85903b4e3e7ee8b5eabe3f6d0e3ac8c5/srcpkgs/font-iosevka/template).

The ttc packages are more desired than ttf packages by package managers because they are usually smaller in size. For comparison:
* ttc-iosevka-2.3.3.zip is 8.1 MB
* ttc-iosevka-3.0.0-rc.8.zip is 14.8 MB
* ttf-iosevka-3.0.0.zip is 49.6 MB
* pkg-iosevka-3.0.0.zip is 151 MB

I would really appreciate if @be5invis can continue to release ttc packages in 3.0.1, that would make patching package managers to provide the latest version of Iosevka much easier.

**Comment by be5invis** [comment]
I do not know they depend on the TTC-only package. I'd like to add it back in 3.0.1.
Still, they _should_ use the `pkg`-prefixed ones even it is larger. TTC may have compatibility issues on many software.

**Comment by be5invis** [comment]
Fixed in 3.0.1. Closed.
