### ISSUE TITLE
Match 1 and 7 styles

### ISSUE THREAD

**Issue by AlsoScratch** [be5invis/Iosevka#539]
Currently, not all of the style sets have the `1` and `7` match the font they are based on:

![Style Sets](https://raw.githubusercontent.com/be5invis/Iosevka/master/images/stylesets.png)

(Sorry I can't bother to check all actual fonts and list them all out.)

**Comment by be5invis** [comment]
Fixed.

**Comment by be5invis** [comment]
(Actually I found that most monospace fonts adds the base serif of `1`... So should I change my default?)

**Comment by AlsoScratch** [comment]
> (Actually I found that most monospace fonts adds the base serif of `1`... So should I change my default?)

I suggest not.

**Comment by wimstefan** [comment]
> (Actually I found that most monospace fonts adds the base serif of `1`... So should I change my default?)

Well since Iosevka is all about configurability you could make it optional as well ... ;-)
