### ISSUE TITLE
Please, stop changing established variants between releases

### ISSUE THREAD

**Issue by nomad-software** [be5invis/Iosevka#542]
* Your font version: Iosevka, Version 3.0.1
* Your font variant: Iosevka Term
* Your operating system (name and version): Ubuntu 20.04
* Your application using Iosevka: Vim, VS Code, various other editors

I used to use 'Iosevka Term' as my default font for coding and it was great. The only thing I wanted from it was ligatures. Imagine my surprise when ligatures where added in the new version. I installed it immediately and was shocked to see v3.0 is an entirely different font. Loads of the glyphs have been replaced for different variations (the letters are different shapes and curved differently) and it just looks horrible after being used to an earlier version.

I download all of the currently [released variations](https://github.com/be5invis/Iosevka/releases) and compared each one to my old 'Iosevka Term' and 'Iosevka Term Curly' is the closest match. Infact, it's identical apart from the lowercase 'g' (which is now open instead of squiggly) which I can live with. So it looks like 'Iosevka Term' is a new variation and what was 'Iosevka Term' is now called 'Iosevka Term Curly'.

Please, please, do not change established glyphs variations in releases or start changing names. I expect 'Iosevka Term' or 'Iosevka Term Curly' to essentially be the same font forever, albeit with minor tweaks, i.e. add new unicode support, or else there's no point giving the variation a name.

Here's a comparison of the difference in glyphs in the new version of 'Iosevka Term'.

![](https://i.imgur.com/Tqszlp5.gif)

This might not seem like a big deal to you guys but this is a real big deal in typography. I used to work as a reprographic artist who specialised in type and I've never heard of a font spontaneously changing like this. Also, this renders all font libraries (Online and offline books) which carry this font as obsolete.

As a side note, I know I can customise the font to look however I want but I haven't got time to mess about like that. I just want to download a variation and get going. Plus I tried building my own variation and npm just errors all the time.

I also want to say that I am grateful for this font and is my favourite coding font.

**Comment by be5invis** [comment]
I am following [semver](https://semver.org/). The decision of making a major version change (3.0.0) instead of minor version change (like 2.4) is because this is a breaking change.
Close as by design.
