### ISSUE TITLE
Inconsistent version numbers

### ISSUE THREAD

**Issue by knuesel** [be5invis/Iosevka#545]
* Your font version: 3.0.1
* Your font variant: Regular
* Your operating system (name and version): Ubuntu 20.04
* Your application using Iosevka: n/a

The ttf file stores inconsistent version information in the "head" and "name" tables, as can be seen by running `ttx iosevka-regular.ttf`:

* head.fontRevision = 1.0
* name.Version = "Version 3.0.1; ttfautohint (v1.8.3)"

According to https://silnrsi.github.io/FDBP/en-US/Versioning.html these two versions should match. 

It seems that fontconfig on Linux uses head.fontRevision: executing `fc-match -f '%{fontversion}\n' iosevka` gives 65536, which means 1.0.

Windows on the other hand uses the name.Version, see https://docs.microsoft.com/en-us/typography/opentype/spec/head

**Comment by be5invis** [comment]
Fixed the computation.
Note that since Iosevka follows `semver` I only keep one digit for `patch` and two digits for `minor`.
