### ISSUE TITLE
Thinko fix

### ISSUE THREAD

**Issue by moosotc** [be5invis/Iosevka#547]
`
From aa0831b721d324ee0e6b8099a1d5565ceb4b041d Mon Sep 17 00:00:00 2001
From: malc <moosotc@gmail.com>
Date: Sat, 23 May 2020 18:18:44 +0300
Subject: [PATCH] Fix typo

---
 variants.toml | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/variants.toml b/variants.toml
index a759ae2c..3d786c1d 100644
--- a/variants.toml
+++ b/variants.toml
@@ -168,7 +168,7 @@ l = 'hooky'
 [simple.v-l-zshaped]
 tag = 'cv10'
 sampler = 'l'
-description = 'Z-shaped `i`'
+description = 'Z-shaped `l`'
 l = 'zshaped'
 
 [simple.v-l-serifed]
-- 
2.26.2

`

**Comment by moosotc** [comment]
I don't understand why this was closed. The description for "el" mentions 
"eye", an the inline patch tried to fix that, what am i missing?

**Comment by be5invis** [comment]
@moosotc Your patch has been be applied in this commit: https://github.com/be5invis/Iosevka/commit/b60c55e3731f7c339514b30f3faa7482e3f64c4a

**Comment by moosotc** [comment]
Belleve Invis <notifications@github.com> writes:

> @moosotc Your patch has been be applied in this commit:
> https://github.com/be5invis/Iosevka/commit/b60c55e3731f7c339514b30f3faa7482e3f64c4a

Oh, this was commited to the dev branch and thus i've missed it, sorry
for the noise. Btw the variants file is not terribly consitent wrt
backticks around character names also there are, what looks like,
spurious underscores sprinkled around...
