### ISSUE TITLE
Can we have a ligature version where the ++ aren't connected?

### ISSUE THREAD

**Issue by pushqrdx** [be5invis/Iosevka#549]
* Your font version: latest
* Your font variant: ss12
* Your operating system: macOS mojave
* Your application using Iosevka: vscode

Describe your problem here. Provide pictures and files if necessary.
The font is pretty much perfect, and i like the ligatures very much however having the ++ ligaturized is a bit odd, and there seems to be no option to have all ligatures except that one. So can we have that?

**Comment by be5invis** [comment]
This should be customizable with custom build like this:

```
[buildPlans.iosevka-custom]
design = ['calt-center-ops', 'calt-arrow', 'calt-html-comment', 'calt-trig', 'calt-llgg', 'calt-llggeq', 'calt-eqeq', 'calt-ineq', 'calt-exeq', 'calt-kern-dotty']
......
```

**Comment by pushqrdx** [comment]
@be5invis thanks for the quick answer, and for the awesome font!
