### ISSUE TITLE
没有人发现数字3是头大脚小的吗？

### ISSUE THREAD

**Issue by MadMaxChow** [be5invis/Iosevka#55]

**Comment by be5invis** [comment]
![image](https://cloud.githubusercontent.com/assets/240091/12533813/a565a6e0-c278-11e5-8bd8-953d8c7149a8.png)
The upper contour and the lower one have same width.

**Comment by MadMaxChow** [comment]
但为什么从视觉上看是头大脚轻呢？估计是大部分的字形中数字3都是上半部稍小一点，这样会显得更稳重。

**Comment by be5invis** [comment]
![image](https://cloud.githubusercontent.com/assets/240091/12542094/d217f1a2-c359-11e5-973c-62fd9b90e3f6.png)
![image](https://cloud.githubusercontent.com/assets/240091/12542099/db7eacf4-c359-11e5-809b-868ec42b277a.png)
So how about this?

**Comment by be5invis** [comment]
@MadMaxChow I added a commit to add visual corrections on three-like characters (three, epsilon and cyrze).

**Comment by be5invis** [comment]
Released in 1.7.3.
