### ISSUE TITLE
Make width blendable

### ISSUE THREAD

**Issue by derVedro** [be5invis/Iosevka#554]
Hey, I am trying to mimic Source Code Pro with its wider look for my IDE. Source Code Pro is already a nice font but since I saw the superiorness of Iosevka I don't want miss that. So build my onw Iosevka ttf variant. I spend some time trying stuff and replace glyphs in *private-build-plans.toml* is quick task. But I don't realy understand what is going on with font wideness. I ended with setting *width* to 530 in  *parameters.toml*. I am not quite sure that's the right place to do it. I got an extended Iosevka font that is nice but I feel like I missed something. e.g I do not understand what *buildPlans.iosevka-custom.widths.extended* section in *private-build-plans.toml* is for? I played with shape setting of it in vanilla example config, but I couldn't see any differences.

**Comment by be5invis** [comment]
The parameters in `[buildPlans.iosevka-custom.widths.extended]` are width _grades_ instead actual character width. Currently only two width grades (5 and 7) are available.

**Comment by derVedro** [comment]
It's pity that overriding `width` in `[buildPlans.iosevka-custom.metric-override]` in private build plan doesn't change anything. Two grades are not fine enough for me. I'm afraid I have to dive into wd- magic. Can you give me some hints, what that _wd-N.multiplies_ are for?

**Comment by be5invis** [comment]
I see, you want things like `wd-7.5`?
Fine let me change the title...

**Comment by be5invis** [comment]
Now, in your `private-build-plans.toml` you can specify your characters' width like this:

```
[buildPlans.iosevka-custom.widths.normal]
shape = 500        # Unit Width, measured in 1/1000 em.
menu  = 5          # Width grade for the font's names.
css   = "normal"   # "font-stretch' property of webfont CSS.

[buildPlans.iosevka-custom.widths.extended]
shape = 576
menu  = 7
css   = "expanded"
```

We now use the actual "unit" width in the config file to customize the width. Older grades are still supported but will show up a warning and converted to the new width when building.

**Comment by derVedro** [comment]
Mother of god! That is it! It works like a charm.Thank you!
