### ISSUE TITLE
[feature request] a quick tool for cherry picking and setup a font

### ISSUE THREAD

**Issue by derVedro** [be5invis/Iosevka#555]
There are already some nice things like [Variants à la Carte](https://typeof.net/Iosevka/) and [specimen](https://typeof.net/Iosevka/specimen) there, so maybe one day there will be a tool that will provide a ready for use config file for a custom build? Maybe with some additional stuff like weights and widths, types etc.

**Comment by be5invis** [comment]
Well, actually I wanted to do this, a customization page that produces a configuration _or_ a `font-feature-settings` CSS value.

**Comment by GTMxCode** [comment]
It's wide open man, you can do whatever you want if you build your own. Set up a private build based off the default example and go from there. Although I do have to admit be5invis must be a mad genius of sorts and the code takes some times to digest (depending on how deep you go digging I suppose), especially the Patel, but within the entire project there are enough examples of the syntax to achieve whatever you want. The quick tool is the design = [] array in the private build plans toml and the image of all the available variants to plug in there..

**Comment by naiyerasif** [comment]
Although Iosevka is pretty open for people to customize for their taste, there is a certain level of familiarity with tooling required to achieve this. For people just looking to customize and grab, it is certainly a task. 

A good example how this should be done is [here](https://input.fontbureau.com/download/?customize&fontSelection=fourStyleFamily&regular=InputSans-Regular&italic=InputSans-Italic&bold=InputSans-Bold&boldItalic=InputSans-BoldItalic&a=0&g=0&i=0&l=0&zero=0&asterisk=0&braces=0&preset=default&line-height=1.2&email=) (image below)

![image](https://user-images.githubusercontent.com/19614213/85886607-0581e400-b804-11ea-85ad-ce2feb4ba748.png)

**Comment by be5invis** [comment]
Customizer is landed in website. Closing.
