### ISSUE TITLE
monofur like shapes

### ISSUE THREAD

**Issue by moosotc** [be5invis/Iosevka#556]
0435 е CYRILLIC SMALL LETTER IE
044D э CYRILLIC SMALL LETTER E
0434 д CYRILLIC SMALL LETTER DE

Latin small - aegljrw
[e looks the same in both cyrillic and latin]

**Comment by be5invis** [comment]
Monofur's design is very different from Iosevka so adding them needs further justification.

**Comment by moosotc** [comment]
Belleve Invis <notifications@github.com> writes:

> Monofur's design is very different from Iosevka so adding them needs
> further justification.

Okay, i lack the qualificatiosn/typographical-knowledge to justify this.
It's just that with https://tpaste.us/8XDO one is very close to monofur
sans what has been asked for in this feature request and iosevka being
"bigger".
