### ISSUE TITLE
U+1E9D LATIN SMALL LETTER LONG S WITH HIGH STROKE has a low stroke

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#558]
* Your font version: 3.0.1
* Your font variant: Extended
* Your operating system (name and version): macOS 10.14.6
* Your application using Iosevka: hb-view

---

The stroke of U+1E9D LATIN SMALL LETTER LONG S WITH HIGH STROKE is not high: it is even lower than the stroke of U+0066 LATIN SMALL LETTER F. It should be closer to the height of other Latin letters’ ascenders’ strokes, as in U+0111 and U+0127.
![ẝfđħ](https://user-images.githubusercontent.com/1124347/83288649-bbc8be00-a1b1-11ea-9e09-92636dfe549b.png)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/83319307-3b767d00-a1f2-11ea-977d-068b07e393b7.png)
