### ISSUE TITLE
U+045D CYRILLIC SMALL LETTER I WITH GRAVE lacks Bulgarian variant

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#560]
U+045D CYRILLIC SMALL LETTER I WITH GRAVE is used in Bulgarian. It should have a localized form like U+0438 CYRILLIC SMALL LETTER I.
![ѝи](https://user-images.githubusercontent.com/1124347/83339496-746b2c00-a29c-11ea-8fc2-95881bf2de23.png)

---

* Your font version: 3.1.0
* Your font variant: Extended
* Your operating system (name and version): macOS 10.14.6
* Your application using Iosevka: hb-view

**Comment by be5invis** [comment]
Fixed in recovery branch. Will land into 3.1.1.
