### ISSUE TITLE
Incomplete leg in curly ⟨R⟩

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#561]
With 'cv83', the diagonal leg of ⟨R⟩ and related letters does not fully meet the bowl.
![Rʀ](https://user-images.githubusercontent.com/1124347/83340418-7a193f80-a2a5-11ea-8af1-97c39de2bff0.png)

---

* Your font version: 3.1.0
* Your font variant: Extended
* Your operating system (name and version): macOS 10.14.6
* Your application using Iosevka: hb-view

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/83340869-120d2e00-a292-11ea-9cf5-cbec17be0500.png)
![image](https://user-images.githubusercontent.com/240091/83340873-20f3e080-a292-11ea-8158-a8b2d41e4159.png)
