### ISSUE TITLE
Make digit six (6) like (9) cv96 choice variant

### ISSUE THREAD

**Issue by it-mikhail** [be5invis/Iosevka#562]
Make digit six (6) like (9) cv96 choice variant

**Comment by be5invis** [comment]
You mean a `6` with a closer hook? like `9` under `cv96`?
Ah I need to rename some style selectors.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/83341737-d4150780-a29b-11ea-8ca6-869c6ba4bf4f.png)

**Comment by it-mikhail** [comment]
Cool, thanks!

**Comment by it-mikhail** [comment]
Can you name the approximate dates when this wonderful update will appear? :)

**Comment by be5invis** [comment]
@it-mikhail Should be late June.
