### ISSUE TITLE
ҕ comes out the other side at small weights

### ISSUE THREAD

**Issue by AlsoScratch** [be5invis/Iosevka#564]
<img width="387" alt="Screenshot 2020-05-31 at 10 13 36 AM" src="https://user-images.githubusercontent.com/48752273/83342992-bbeaca00-a327-11ea-82fb-50239e61e428.png">

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/83343135-49d49f80-a2ab-11ea-973a-7dc9eb5507f8.png)
