### ISSUE TITLE
U+1DB2 MODIFIER LETTER SMALL PHI lacks serifs

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#565]
U+1DB2 MODIFIER LETTER SMALL PHI is derived from U+03D5 GREEK PHI SYMBOL instead of from U+0278 LATIN SMALL LETTER PHI, which in the Slab fonts are distinct.
![ᶲɸ](https://user-images.githubusercontent.com/1124347/83343525-a5158a80-a2c9-11ea-90cd-231a676e0a08.png)

---

* Your font version: 3.1.0
* Your font variant: Iosevka Slab Extended
* Your operating system (name and version): macOS 10.14.6
* Your application using Iosevka: hb-view

**Comment by be5invis** [comment]
I've inspected all the serif fonts I have, here is how the string `U+1DB2 U+0278 U+03c6 U+03d5` looks like:

Brill
![image](https://user-images.githubusercontent.com/240091/83343792-dc793c80-a2b3-11ea-8914-302fa15ad400.png)

Cambria
![image](https://user-images.githubusercontent.com/240091/83343785-c23f5e80-a2b3-11ea-9c04-b15cecf6a5e8.png)

Times New Roman
![image](https://user-images.githubusercontent.com/240091/83343789-cec3b700-a2b3-11ea-8be1-601b6c5855a3.png)

For all these fonts, U+0278 has serifs but U+03D5 doesn't have them.

As a result, this will be the fixed glyphs:
![image](https://user-images.githubusercontent.com/240091/83343833-590c1b00-a2b4-11ea-8b31-b9d5fcf41e59.png)
