### ISSUE TITLE
[Glyph Request] Missing Mathematical Operators

### ISSUE THREAD

**Issue by snavatar** [be5invis/Iosevka#567]
I noticed that the glyph of `U+228E MULTISET UNION` (sum type in Agda) is not present in Iosevka (however `U+228D MULTISET MULTIPLICATION` is). Checked the font specimen and found that some mathematical operators are not implemented, so I opened this issue.

I guess some glyphs may be easier to implement than others, for they can be made by combining existing glyphs (e.g. `U+2214 DOT PLUS`, `U+221B CUBE ROOT`, as well as the three multiset operators `U+228C ~ U+228E`, etc).

(As for myself, I only want U+228E yet ;P)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/83469530-d9f22080-a434-11ea-99a1-000daadedfb5.png)
