### ISSUE TITLE
Small gaps in very light fonts

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#569]
U+22B6, U+22B7, U+22B8, and U+A78E have some small gaps between strokes which are only visible in the lighter-weight fonts.
![⊶⊷⊸ꞎ](https://user-images.githubusercontent.com/1124347/83362861-9fb84e80-a362-11ea-9953-6301349e83d6.png)

---

* Your font version: 3.1.0
* Your font variant: Iosevka Thin Extended
* Your operating system (name and version): macOS 10.14.6
* Your application using Iosevka: hb-view

**Comment by be5invis** [comment]
I validated U+22B6, U+22B7, U+22B8 and they do not have gaps under thin extended. Belts are fixed.

![image](https://user-images.githubusercontent.com/240091/83396234-85a55d00-a3b0-11ea-8d05-80dbf0e78ee3.png)

**Comment by dscorbett** [comment]
I checked again: the gaps in the three mathematical symbols appear in Iosevka Slab Thin Extended, not Iosevka Thin Extended.
