### ISSUE TITLE
Compose symbol is not symmetric

### ISSUE THREAD

**Issue by 11Kilobytes** [be5invis/Iosevka#57]
Consider the text `f ∘ g`. It is rendered like this by emacs: ![image](https://cloud.githubusercontent.com/assets/1944582/12575750/b7122422-c417-11e5-8eec-3e14b25a826a.png). The bug is that the compose symbol is not centred properly.

**Comment by 11Kilobytes** [comment]
This is a bug in emacs, sorry.

**Comment by be5invis** [comment]
Iosevka does not support this symbol for now, may be caused by font linking.
