### ISSUE TITLE
[Feature Request] More variants of parentheses

### ISSUE THREAD

**Issue by krasimirkrustev** [be5invis/Iosevka#570]
Can you make more variants of parentheses (Monaco/PT Mono style, Menlo/Meslo LG style, etc.)?

**Comment by be5invis** [comment]
"More Curly" and "Less Curly"?
Interesting but seem not very necessary for Iosevka.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/83934527-a847c500-a766-11ea-87da-e89a1b352e77.png)
