### ISSUE TITLE
Build system tries to print control characters when it is not safe

### ISSUE THREAD

**Issue by moosotc** [be5invis/Iosevka#571]
`npm` run build -- ttf-unhinted::iosevka-clam >output` works fine but running the same command from within emacs results in (abridged):
`
> iosevka@3.1.0 build /home/malc/x/rcs/git/fonts/Iosevka
> verda -f verdafile.js "ttf-unhinted::iosevka-clam"

[1G⢀⠀ [?25l[1G⡀⠀ Complete 1 - Executing 0 - Pending 0 (100%) | CPU:000% - RAM:000%[1G⠄⠀ Complete 11 - Executing 0 - Pending 14 (044%) | CPU:000% - RAM:000%[1G⢂⠀ Complete 21 - Executing 0 - Pending 09 (070%) | CPU:000% - RAM:000%[2K[1G[?25h♦ "gen/index" {"o":"build/iosevka-clam/iosevka-clam-regular.otd","oCharMap":"...
`

**Comment by be5invis** [comment]
The progress bar outputs to STDERR. You may need to redirect STDERR or use the building system inside an interactive environment.

**Comment by moosotc** [comment]
Belleve Invis <notifications@github.com> writes:

> The progress bar outputs to STDERR. You may need to redirect STDERR or
> use the building system inside an interactive environment.

Not sure what it has to do with anything. Anyway, to demonstrate the
issue (better hopefully):

Running following script (build.sh) from within emacs results in
following being shown in the compilation window/buffer:

-*- mode: compilation; default-directory: "~/xsrc/snippets/bin/configure/" -*-
Compilation started at Mon Jun  1 02:54:16

sh build.sh

> iosevka@3.1.0 build /home/malc/x/rcs/git/fonts/Iosevka
> verda -f verdafile.js "ttf-unhinted::iosevka-clam"

[1G⢀⠀ [?25l[1G⡀⠀ Complete 1 - Executing 0 - Pending 0 (100%) | CPU:000% - RAM:000%[1G⠄⠀ Complete 10 - Executing 0 - Pending 00 (100%) | CPU:000% - RAM:000%[2K[1G[?25hFinished with 16 targets updated.[?25h
completed

> iosevka@3.1.0 build /home/malc/x/rcs/git/fonts/Iosevka
> verda -f verdafile.js "ttf-unhinted::iosevka-clam"


Compilation finished at Mon Jun  1 02:54:18

================================================================================
build.sh

#!/bin/sh
cd $HOME/x/rcs/git/fonts/Iosevka
npm run build -- ttf-unhinted::iosevka-clam
echo completed
npm run build -- ttf-unhinted::iosevka-clam | cat

================================================================================
IOW redirect forces isatty to return false somewhere within the bowels
of verda/npm/node/v8/whathaveyou and one gets a silent build

**Comment by be5invis** [comment]
I've uploaded an update of dependencies, and now if stdout is redirected, it will also hide the progress bar.
