### ISSUE TITLE
Refactor: Leverage GSUB Alternate substitutions in `cv##` features.

### ISSUE THREAD

**Issue by be5invis** [be5invis/Iosevka#572]
This will massively reduce the need of feature tags of character variant features.

**Comment by AlsoScratch** [comment]
Interesting. How would this work?

**Comment by be5invis** [comment]
@AlsoScratch Like this: `font-feature-settings: 'cv01' 1, 'cv02' 2, ...`
Use numbers instead of on/off.

**Comment by AlsoScratch** [comment]
I've never seen that before... it would certainly be fascinating to see how that would reduce the need for `cv##` tags.

**Comment by AlsoScratch** [comment]
> @AlsoScratch Like this: `font-feature-settings: 'cv01' 1, 'cv02' 2, ...`
> Use numbers instead of on/off.

I'm rather concerned about backward compatibility and application support.

**Comment by be5invis** [comment]
@AlsoScratch 
4.0 is a major change, so we can make breaking changes.

**Comment by AlsoScratch** [comment]
My main concern is application support; whether will it work in VSCode, CSS, etc.

**Comment by be5invis** [comment]
@AlsoScratch VSCode and CSS just support it well.
