### ISSUE TITLE
Remove slab from 1 in slabbed version for default style

### ISSUE THREAD

**Issue by xsrvmy** [be5invis/Iosevka#575]
In the default style for the Slab version, 1 and lower L are extremely close, and are hard to tell apart at smaller sizes. A solution to this is to make the 1 not slabbed by default. Alternate solution would be to use a different lower L.

**Comment by be5invis** [comment]
I'd like to close this as by design. The choice of `1` shape under Slab is like this since the very initial version of Slab. You can also leverage OT features / customization to change the shape.
