### ISSUE TITLE
Support all glyphs for standard ASCII set displaying

### ISSUE THREAD

**Issue by dwellervoid** [be5invis/Iosevka#577]
It is useful, when the terminal font supports all possible ASCII glyphs. Iosevka 3.1.1 supports most of them, but not yet all, as you can see on the image (extra bold SS14 variant was used):
![ascii](https://user-images.githubusercontent.com/25480132/83546939-278c8d00-a50a-11ea-977b-4218c78de909.jpg)
Other fonts like e.g. Lucida Console support full set of ASCII glyphs, so it will be great, if iosevka will support them too. Maybe all glyphs are already exist in font, so only mapping should be corrected.

Look at glyphs with codes 0x01, 0x02 and maybe 0x7F, they are absent.

**Comment by be5invis** [comment]
This is CP437, not ASCII.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/83584857-2c970f80-a4fd-11ea-833a-4d78e373cac5.png)

**Comment by paolobolzoni** [comment]
![pngout](https://user-images.githubusercontent.com/1133562/84980257-8ab62a80-b16c-11ea-815c-9f9463a9069d.png)

I rebuilt iosevka from the dev branch, how can I see those glyphs? Since it is not Ascii, do I need to something unusual?

**Comment by be5invis** [comment]
@paolobolzoni You can try grab the chars from https://en.wikipedia.org/wiki/Code_page_437
