### ISSUE TITLE
iosevka extra-extended (wd-8 and wd-9) seem incompatible with directwrite

### ISSUE THREAD

**Issue by deathaxe** [be5invis/Iosevka#579]
Please forgive me when missing some obvious setting. These are my first steps with private build plans. 

Just want to make use of the new `wd-8` and `wd-9` to create `extra-` and `ultra-extended` font variants with otherwise default values in parameters.toml as I've learned hacking in custom values there might have unwanted results.

The font build process runs fine.

My issue now is - I can't judge whether it is an application limitation or caused by propably missing font attributes - that Sublime Text is not able to use `iosevka custom extra-extended` and `...-ultra-extended` with DirectWrite. It falls back to GDI rendering which disables ligatures.

The normal and extended font variants work just perfect.

The error messages are:

```
font face "iosevka custom light extra-extended" could not be used with direct write, using gdi instead
font face "iosevka custom light extra-extended" has different widths for bold characters, disabling to prevent text reflow
```

It also seems bold fonts to have a different width, which seems incompatible as well.

Any ideas what I am missing or propably could try to fix it?

I am just curious as I didn't see such issues when hacking the font width parameter in the parameters.toml before.

---

* Your font version: 67e64e3887f9e436c9af6193268b1ec2b0a2e480
* Your font variant: custom (ss09)
* Your operating system (Windows 10 x64 2004):
* Your application using Iosevka: Sublime Text 4074

If you have problem when building Iosevka, please provide these information:

* Your Node.js version: 14.3
* Your _otfcc_ version: 0.10.4
* Your `private-build-plans.toml`, if present:

```
[buildPlans.iosevka-custom]               # <iosevka-custom> is your plan name
family = "Iosevka Custom"                 # Font menu family name
design = ["ss09"] 
snapshotFamily = 'iosevka'
snapshotFeature = '"NWID" on, "ss09" on'

###################################################################################################
# Override default building widths
# When buildPlans.<plan name>.widths is absent, all widths would built and mapped to
# default values.
# IMPORTANT : Currently "shape" property only supports integers between 3 and 9 (inclusive), while
#             "menu" only supports integers between 1 and 9 (inclusive).
#             If you decide to use custom widths you have to define all the widths you
#             plan to use otherwise they will not be built.

[buildPlans.iosevka-custom.widths.normal]
shape = 5          # Width grade of glyph shapes. NOT actual character width.
menu  = 5          # Width grade for the font's names. NOT actual character width.
css   = "normal"   # "font-stretch' property of webfont CSS.

[buildPlans.iosevka-custom.widths.extended]
shape = 7
menu  = 7
css   = "expanded"

[buildPlans.iosevka-custom.widths.extra-extended]
shape = 8
menu  = 8
css   = "extra-expanded"

[buildPlans.iosevka-custom.widths.ultra-extended]
shape = 9
menu  = 9
css   = "ultra-expanded"

# End width section
################################################################################################### 
```

**Comment by be5invis** [comment]
DWrite can load them correctly:
![image](https://user-images.githubusercontent.com/240091/83678295-6108db00-a592-11ea-9592-9d02b2f6e016.png)

I suspect that Sublime Text uses compatible family names to select fonts, so you _may_ need to use the compatible font family name `Iosevka Custom LtXEx`. Why not `Iosevka Custom Light Extra-Extended`? Because it is too long (more than 31 characters).

**Comment by deathaxe** [comment]
Ok, thanks. Need to ask sublimehq then, because setting `Iosevka Custom LtXEx` fails with

```
font face "Iosevka Custom LtXEx" could not be found, defaulting to "Consolas"
```

Any idea why the bold font has a different width?

**Comment by be5invis** [comment]
@deathaxe In Iosevka, width and weight are two different dimensions. There could be narrow bold font or wide thin font.
The issue you are describing seems an issue of Sublime Text's font selection mechanism. I think you should raise a bug to them.
Closed as external.

**Comment by deathaxe** [comment]
Those error messages were side effects of ST falling back to GDI font rendering.

It turned out ST uses the `LOGFONT` data type to create fonts on Windows. Hence a font name may not exceed 32 chars. It looks like there is no implementation to fall back to the compatible name in such situations.

I am able to work around this limitation for most / relevant font variants by ommiting the `Custom` token from the font name.

Your font works perfect as is on Linux and MacOS.

Thanks again for takeing the time pushing me into the correct direction.
