### ISSUE TITLE
Bottom-most line of glyphs (q, @) is cut at small size in xterm

### ISSUE THREAD

**Issue by tpoisot** [be5invis/Iosevka#58]
**Problem:**

Using `*.faceName:     xft:Iosevka:size=9:antialias=false` and lower sizes in `xterm` (v. 322) results in the glyps `g`, `@` (and possibly `p` and `y`) being cut. See the attached image. 

![2016-01-31_12h51m51](https://cloud.githubusercontent.com/assets/579329/12703824/545cdab4-c81a-11e5-993e-357c554ab5d7.png)

**Expected behavior:**

The glyphs are displayed entirely.

**Additional informations:**

1. The problem does not occur using `urxvt`
2. The problem does not occur when using `:size=10` in `xterm`
3. I got this version from https://aur.archlinux.org/packages/ttf-iosevka -- version 1.7.3-1
4. Changing the line height scaling in `Xterm` is not fixing the problem.

**Comment by be5invis** [comment]
Have you tried to increase `leading` in `parameters.toml` and rebuild your own one?

**Comment by tpoisot** [comment]
No -- as I said, I use the AUR package, which gets the latest release from github (I have not built the font myself).

**Comment by be5invis** [comment]
I think it is a combination of rounding error and the default line height.
Building your own version (with `leading` tweaked) may solve this, but AFAIK I cannot modify the line height in the default release.

**Comment by tpoisot** [comment]
Might be an issue with xcode, since I was unable to reproduce the issue with other terminal emulators.
