### ISSUE TITLE
Variant request: 't', 'j' and 'f' with short square elements instead of big round ones

### ISSUE THREAD

**Issue by eternal-sorrow** [be5invis/Iosevka#581]
I'd like to have more "square" variants of these glyphs that were more "in style" with `v-i-zshaped` and `v-l-zshaped` or `v-i-hookybottom` and `v-l-hookybottom`. I mean the shape of the "hook" element of these glyphs.

In any case, thank you so much for this great font!

**Comment by naiyerasif** [comment]
I'm looking forward to cook-up a more **grotesk** version of Iosevka if these variants are added. I'd also advocate for such variants for "g" (strongly preferred) and "y" (not so strongly preferred, I could live with `cv48` variant).

**Comment by wynn5a** [comment]
I hope someone can add variant for `t` , `f`, `j` like `Iosevka Aile` style.  🥇

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/89631511-b80e8300-d855-11ea-9cea-fa0c620b78b3.png)

**Comment by eternal-sorrow** [comment]
That's better, but not exactly what I proposed. The "hooks" are flat that's OK, but the corner part of the hook still has some curve. I proposed exactly sharp strait angles.
