### ISSUE TITLE
Questionable U+1D24 LATIN LETTER VOICED LARYNGEAL SPIRANT

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#584]
U+1D24 LATIN LETTER VOICED LARYNGEAL SPIRANT looks like U+0493 CYRILLIC SMALL LETTER GHE WITH STROKE: it has a crossing stroke, and it has no ascender, unlike [the only glyph for U+1D24 from a primary source included in its Unicode proposal](https://www.unicode.org/L2/L2002/02141-n2419-uralic-phonetic.pdf#page=33). Is this glyph attested for this character?
![ᴤ](https://user-images.githubusercontent.com/1124347/83959197-1fa15580-a848-11ea-864c-fdb06597717e.png)

---

* Your font version: 3.1.1
* Your font variant: Iosevka Extended Italic
* Your operating system (name and version): macOS 10.14.6
* Your application using Iosevka: hb-view

**Comment by be5invis** [comment]
IDK where I got this -- some other fonts may have this glyph (and made it wrong...)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/83960715-ddc0e100-a840-11ea-9768-2692cecbc484.png)
