### ISSUE TITLE
Misplaced descender on U+04AC/U+04AD CYRILLIC CAPITAL/SMALL LETTER TE WITH DESCENDER

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#585]
The descenders of U+04AC CYRILLIC CAPITAL LETTER TE WITH DESCENDER and U+04AD CYRILLIC SMALL LETTER TE WITH DESCENDER should be at the right ends of the bottom serifs.
![Ҭҭ](https://user-images.githubusercontent.com/1124347/83974755-a3495980-a8bd-11ea-9dc0-dd53f9b3a79f.png)

---

* Your font version: 3.1.1
* Your font variant: Iosevka Slab Extended
* Your operating system (name and version): macOS 10.14.6
* Your application using Iosevka: hb-view

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/83979088-a72aab00-a8c0-11ea-938f-a05f39c7e610.png)
