### ISSUE TITLE
Curly-legged U+01A6 LATIN LETTER YR loses its descender

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#586]
When `v-capital-r-curly` is enabled, U+01A6 LATIN LETTER YR’s descender is removed.
![Ʀ](https://user-images.githubusercontent.com/1124347/83978435-730db500-a8d5-11ea-97fc-c18bb74ff890.png)

---

* Your font version: 3.1.1
* Your font variant: Iosevka Extended
* Your operating system (name and version): macOS 10.14.6
* Your application using Iosevka: hb-view

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/83979246-ba8a4600-a8c1-11ea-93fb-9d9105981004.png)
