### ISSUE TITLE
Extraneous serif in Bulgarian U+044E CYRILLIC SMALL LETTER YU

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#587]
The Bulgarian form of U+044E CYRILLIC SMALL LETTER YU has a serif in the middle of the left stroke, left over from the default form.
![ю](https://user-images.githubusercontent.com/1124347/83980423-b53df300-a8e3-11ea-80b6-a5d8fad7c89c.png)

---

* Your font version: 3.1.1
* Your font variant: Iosevka Slab Extended
* Your operating system (name and version): macOS 10.14.6
* Your application using Iosevka: hb-view

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/83982948-5e361f00-a8df-11ea-860e-15422c88eebb.png)
