### ISSUE TITLE
Any "different" variant of B or 8 to better tell them appart

### ISSUE THREAD

**Issue by moosotc** [be5invis/Iosevka#589]

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/84102195-9fecc580-a9c4-11ea-9a17-bceb3e335d89.png)
…… I think they are pretty distinctive already now...
Could you please provide some samples about "more distinctive" `B` and `8`?

**Comment by moosotc** [comment]
Belleve Invis <notifications@github.com> writes:

> ![image](https://user-images.githubusercontent.com/240091/84102195-9fecc580-a9c4-11ea-9a17-bceb3e335d89.png)
> …… I think they are pretty distinctive already now...
> Could you please provide some samples about "more distinctive" `B` and `8`?

Among the fonts on my system, following are OK in this regard:
    alegreya
    beograd
    dudu cyrillic
    code2003
    noto sans
    pt astra sans|serif
    pt serif
    symbla
    xo oriel

following are less so:
    montserratt alternates
    pt sans
    raleway v4020
    ubuntu
    ubuntu mono
    xo caliburn

The presence of pt astra sans in one list an pt sans in the other is
supsect i'll admit, but...

"...for the rational mind, type design can be a maddening game of drawing
things differently in order to make them appear the same." [1]
 
[1] https://en.wikipedia.org/wiki/Overshoot_(typography)

**Comment by be5invis** [comment]
The problem is that, in most proportional fonts, we can make `B` much wider than `8`, but Iosevka is mostly a monospace font, so we cannot do that :(

**Comment by moosotc** [comment]
Belleve Invis <notifications@github.com> writes:

> The problem is that, in most proportional fonts, we can make `B` much
> wider than `8`, but Iosevka is mostly a monospace font, so we cannot
> do that :(

I have no ground to argue either way.. After looking in a close up
redering of B8 in `montserrat alternates` (a proportional one) it is
evident that B is much wider than 8 yet the _my_ brain plays games and
makes it very hard for me to distinguish the two at certain sizes. It is
also worth noting how symbola utilizes both serifs and stroke width in
B8 case, and Dudu Cyrillic's solution is probably the best one (for me),
but that one is a fantasy one(?) so can wonder where `normal` typefaces
dare not to go.

**Comment by moosotc** [comment]
Belleve Invis <notifications@github.com> writes:

> The problem is that, in most proportional fonts, we can make `B` much
> wider than `8`, but Iosevka is mostly a monospace font, so we cannot
> do that :(

I have located a monospaced font where B8 problem is not as accute and i
can understand why [1]:

https://github.com/belluzj/fantasque-sans
https://www.fontsquirrel.com/fonts/fantasque-sans-mono

[1] By making B less symmetrical vertically

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/84221861-05a38500-aa8b-11ea-8e49-9172924d50cf.png)
I'd like to add something like this. Note that distorting `B` will break the natural proportion and made it look less pleasing -- this is the cost of more differentiation.

**Comment by moosotc** [comment]
Belleve Invis <notifications@github.com> writes:

> ![image](https://user-images.githubusercontent.com/240091/84221861-05a38500-aa8b-11ea-8e49-9172924d50cf.png)
> I'd like to add something like this. Note that distorting `B` will
> break the natural proportion and made it look less pleasing -- this is
> the cost of more differentiation.

Thank you.
