### ISSUE TITLE
Font hinting - any further work planned?

### ISSUE THREAD

**Issue by IceMan81** [be5invis/Iosevka#59]
@be5invis Are you thinking about doing additional hinting work for Iosevka to bring it closer in hint quality to fonts like PragmataPro? I've been playing around with the hinting parameters for ttfautohint along with changing the underlying freetype lib to see impact, but I've not yet settled on a combination of changes. 

I'm not sure if there is something to be done with fontforge to improve hinting.

**Comment by be5invis** [comment]
The automatic `ttfautohint`ed result looks good for me. Since the point index is not maintained by the building program, maintaining an additional hinting database is not a good idea.

**Comment by efermi** [comment]
It's not always good though, see for example how bad the horizontal symmetry is on 10pt:
![snapshot152](https://cloud.githubusercontent.com/assets/3966555/14159699/44360db6-f6e8-11e5-8d18-f80a68ce4b05.png)

**Comment by be5invis** [comment]
However the important thing used for gridfitting, point index, cannot be maintained in the current workflow. However if MS released a standalone version of the VTT hinter, maybe you can try it.

**Comment by be5invis** [comment]
Closed due to inactivity
