### ISSUE TITLE
Combining lines should connect left and right

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#590]
U+0305 COMBINING OVERLINE, U+0332 COMBINING LOW LINE, U+0333 COMBINING DOUBLE LOW LINE, and U+033F COMBINING DOUBLE OVERLINE should be wider so they connect to adjacent instances of the same character, as U+0336 COMBINING LONG STROKE OVERLAY does.
![x̲̅x̲̅x̳̿x̳̿](https://user-images.githubusercontent.com/1124347/84031405-9d0db880-a963-11ea-8405-710b1dd58b4e.png)

---

* Your font version: 3.1.1
* Your font variant: Iosevka Extended
* Your operating system (name and version): macOS 10.14.6
* Your application using Iosevka: hb-view

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/84102557-a7f93500-a9c5-11ea-94db-70aa5c5ac7c4.png)
