### ISSUE TITLE
v-v-curly, v-x-curly, maybe v-y-curly not applied in slab variant

### ISSUE THREAD

**Issue by pv4** [be5invis/Iosevka#591]
If downloading "Iosevka Fixed Curly" or "Iosevka Fixed Curly Slab" or building a font variant for myself, the lowercase k/v/w/x/y look like at the picture.

![Untitled](https://user-images.githubusercontent.com/2502094/84033186-24c5e800-a9a1-11ea-887d-cc7d9b9e9d28.png)

Slab variants of k/w are still curly while v and x becomes straight. y becomes straight as well but it has a different shape so I'm unsure whether it should still be curly too (but I'd like it to).

---

* Your font version: 3.1.1
* Your font variant: sp-fixed (probably does not matter)

**Comment by pv4** [comment]
What's interesting, slab italic v doesn't seem to be affected by the bug (it's curly) while slab italic x is still affected.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/84102091-62883800-a9c4-11ea-9115-cadb45075cae.png)
Actually they _are_ different but not _very_ different...

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/84114218-d3d5e400-a9e0-11ea-964c-6dd1086aa840.png)

**Comment by pv4** [comment]
Great, thank you! So fast!

The attached is the commit backport for 3.1.1 release. I did it for me but it might be useful for someone else.

[Iosevka-3.1.1-vxy_slab_curly.patch.gz](https://github.com/be5invis/Iosevka/files/4754716/Iosevka-3.1.1-vxy_slab_curly.patch.gz)
