### ISSUE TITLE
Inconsistent stroke widths in heavy delta-like components

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#593]
Glyphs with a delta-like component, though not U+0394 GREEK CAPITAL LETTER DELTA itself, have horizontal strokes thinner than the serifs, so the horizontal stroke appears counterbored. The image shows <U+0394, U+2206, U+2207, U+234B, U+234D, U+2352, U+2354, U+2359, U+2362, U+236B>.
![Δ∆∇⍋⍍⍒⍔⍙⍢⍫](https://user-images.githubusercontent.com/1124347/84154341-fabe0580-aa34-11ea-8178-167a725ff3d6.png)

---

* Your font version: 3.1.1
* Your font variant: Iosevka Slab Heavy Extended
* Your operating system (name and version): macOS 10.14.6
* Your application using Iosevka: hb-view

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/84221984-47343000-aa8b-11ea-9d14-1a7d1955a7b9.png)
