### ISSUE TITLE
Variant request numerals, z, and q

### ISSUE THREAD

**Issue by pagerc** [be5invis/Iosevka#595]
In the spirit of request additional variants for legibility, here's some ideas:

Support 7-segment display numerals variants (seems it's a unicode block now)
* https://en.wikipedia.org/wiki/Seven-segment_display
* https://en.wikipedia.org/wiki/Symbols_for_Legacy_Computing

Numeral 1 variants:
* 1 center aligned (no notch)

Numeral 4 variants:
* 4 with the connection to the body not crossing the body (same as current, except no pixels right of the leg)
* 4 like an American football goal with a leg
```
|_|
  |
```
Numeral 7 variants:
* 7 with a hash through the center
* 7 with a footer
* 7 with a hash and footer
* 7 with a notch and hash
* 7 with a notch and footer
* 7 with a notch, hash, and footer
```
____    ____   ____    ____    ____     ____
   /       /      /   |   /   |   /    |   /
 -/-      /     -/-     -/-      /       -/-
 /      _/_    _/_      /      _/_      _/_
```

Numeral 9 variants:
* Like a 7 that's close looped at top, but angled leg from top right to bottom left
```
 ___
|__/
  /
 /
```

Letter z and Z with a hash through the body
```
 ____
    /
  -/-
  /___
```

Letter q with a right tail at the bottom.
```
 __
|__|
   |_
```

Stylistic justification for the hashes on 7 and Z where I've read during the punchcard era, adding hashes to 7 and Z helped differentiate them from 1 and 2.

**Comment by be5invis** [comment]
I may reject `7`-with-serif, but `7` and `Z` with crossbar is pretty nice.

**Comment by be5invis** [comment]
And as a note, Z-with-hash will conflict with U+01B5 `LATIN CAPITAL LETTER Z WITH STROKE` and U+01B6 `LATIN SMALL LETTER Z WITH STROKE`.

**Comment by be5invis** [comment]
> Support 7-segment display numerals variants
It's already supported.

**Comment by pagerc** [comment]
I feel a the q with tail would look nice with the l with a tail. So I'll be disappointed if I can't at least contribute this glyph to be added.

The 1 center aligned would be just a straight line, indistinguishable from an l. I like my l to hook/curve and my 1 to be a straight line with no notch.

7 crossbar is the only one I really care about and think 7 with crossbar and notch might be nice for some folks.

Any style open 4 would be a nice option.

I think for the z with crossbar, it's ok for it to come in semblance with the other Unicode glyph. We're talking about stylistic rendering of alpha numerics to suit the style of folks and help with disambiguation.

**Comment by be5invis** [comment]
@pagerc The reason for `q` seems legit now.

**Comment by be5invis** [comment]
@pagerc About Z: Iosevka now generates U+01B5 and U+01B6 (as well as all the other accented Z's) _from_ `Z` and `z`, so how should they look like?

**Comment by pagerc** [comment]
I view it as an option that the same glyph for U+01B5 and U+01B6 be usable as the letter 'z'. I don't see a reason they need to be graphically distinct in this instance.

If you need a distinction, maybe shrink the strike by 2 pixels in length in the true z.

**Comment by be5invis** [comment]
Adding a barred `Z` for `Z` but _not_ derived letters like ŹźŻżŽž? Seems legit.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/84335153-10245400-ab49-11ea-8a20-a3e646f23721.png)
So far...
The tailed `q` looked a little strange though, and it also conflicts with U+024B `ɋ`.

**Comment by pagerc** [comment]
Those look great, I really like the q with a tail! What looks strange? 
That glyph it conflicts with isn't rendering in my phone...

**Comment by pagerc** [comment]
I'm not sure I see the issue with using alternate Unicode glyph as the default for z and q if the style is desired. The normative Unicode glyph for non-ascii codepoints should render as the standard, but ASCII base can have flare.

**Comment by pagerc** [comment]
Can we get a closed 4 with no bits looking like a toddler couldn't stop the line right?

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/84340755-40beba80-ab56-11ea-8ce3-45f41667015b.png)
@pagerc I am making the tail smaller so they could be distinguished.
Also your non-crossing `4`.

**Comment by pagerc** [comment]
Phenomenal work, thanks so much!

**Comment by pagerc** [comment]
Regarding the 1, yes I think that variant referenced works.

Is there a chance for a 4 that's an upside down and mirrored h?

**Comment by be5invis** [comment]
@pagerc Are there any other fonts having a `4` like `Ч` (instead of the current "open"-`4`)?

**Comment by pagerc** [comment]
Pacifica and Caveat in Google docs. Looking for others less cursivey.

**Comment by be5invis** [comment]
@pagerc I could not find exactly what is Pacifica. Google fonts has Pacifico but the the `4` in it has crossing.
And both Pacifico and Caveat are handwriting-styled, which are too different from Iosevka's style.

**Comment by pagerc** [comment]
https://www.typography.com/fonts/numbers/overview

Numbers Greenback

I think the open 4 is used in US currency serial numbers, but only because that's the only reference I can find to a font with an open 4.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/84344938-e37c3680-ab60-11ea-948f-c1786e319c71.png)
This seems legit.

**Comment by pagerc** [comment]
Not a bad alternative there, still like my straight lines open 4 too with no intersection

**Comment by pagerc** [comment]
Seems the open 4 is common for teaching kids to hand write.
http://www.proteacher.net/discussions/showthread.php?t=204159

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/84350842-f6960300-ab6e-11ea-97a9-7cd37e2a5d12.png)

**Comment by pagerc** [comment]
![image](https://user-images.githubusercontent.com/1564837/84405149-c5045280-abd5-11ea-8793-ba9735c9fc4e.png)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/84451971-61941800-ac09-11ea-8db4-3327d7c632d7.png)
![image](https://user-images.githubusercontent.com/240091/84461456-5816aa00-ac21-11ea-91b9-1ceaf0b93342.png)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/84469144-38897c80-ac35-11ea-968f-99409f22bf82.png)

For your `1` request it is already implemented in `dev`.

**Comment by wimstefan** [comment]
Could we possibly have the option of a straight crossbar for both versions of `z` back? I simply *love* the crossbar of the `7` (especially since the latest fix) but I can't really get used to the diagonal crossbar you've implemented for `z` ...
