### ISSUE TITLE
Implement CGJ-based diacritics.

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#596]
An above-base diacritic following an above-base double diacritic should be rendered above it. For example, here is <U+0075, U+0361, U+034F, U+0301, U+0069> from Unicode’s [figure 7-11](https://www.unicode.org/versions/Unicode13.0.0/ch07.pdf#page=45).
![u͡͏́i](https://user-images.githubusercontent.com/1124347/84330229-da856800-ab54-11ea-956a-acdcc0352ef2.png)
The same goes for below-base diacritics following below-base double diacritics.

---

* Your font version: 3.1.1
* Your font variant: Iosevka Extended
* Your operating system (name and version): macOS 10.14.6
* Your application using Iosevka: hb-view

**Comment by be5invis** [comment]
It looks like that there is almost no font properly implemented the ties' behavior. I suspect whether current OTL mechanism _could_ implement them. Most fonts just place the tie very far away from the letters -- I could do that, but it is not a proper solution.
@dscorbett Do you know any font that does this job _well_?

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/84343308-a6ae4080-ab5c-11ea-9187-2f7e75f4521b.png)
Make this change first. Proper support will be move into #597.

**Comment by be5invis** [comment]
@dscorbett AFAIK such CGJ-based tie-marks are not supported by any fonts I know. Could you please provide an example of one font supported that?

**Comment by be5invis** [comment]
This must be the trickiest OTL feature I ever made, but it works. The idea is that if an above mark is after an above tie, then it will be replaced into a mark with the same shape but different mark class, and that attaches to the tie.
Close as fixed.

![image](https://user-images.githubusercontent.com/240091/84346444-d6f9dd00-ab64-11ea-804e-3305b8bcf4f9.png)

The string is `
u\u0303\u0361\u034f\u030ei\u030a u\u030e u\u034f\u030e u\u0303\u035f\u034f\u0348i\u030a u\u0348 u\u034f\u0348`.

**Comment by dscorbett** [comment]
The only other fonts I know that support this are Noto Sans, Noto Sans Mono, and Noto Serif.
![ũ͡͏̎i̊](https://user-images.githubusercontent.com/1124347/84389585-45ba5300-abc4-11ea-9975-9e52a91fedda.png)![ũ͡͏̎i̊](https://user-images.githubusercontent.com/1124347/84389587-45ba5300-abc4-11ea-8adb-64d9eef10492.png)![ũ͡͏̎i̊](https://user-images.githubusercontent.com/1124347/84389588-45ba5300-abc4-11ea-9b0e-0ce151182f99.png)
They manage it without substituting marks for clones in different mark classes. Can’t you use the same anchor for attaching U+030E to U+0361 as for U+030E to (e.g.) U+0300? The only difference is that U+0361 would have no attaching mark anchor point for that anchor, just a base mark anchor point.
