### ISSUE TITLE
Add Indian Rupee Sign (₹) (U+20B9)

### ISSUE THREAD

**Issue by vizzmay** [be5invis/Iosevka#598]
I am currently using Iosevka Curly 3.1.1 and I have noticed that it doesn’t have the Indian Rupee Sign (₹) (U+20B9).

Note that this is different from the generic Rupee Sign (₨) (U+20A8) which this font has.

For reference, a list of fonts that have implemented Indian Rupee Sign: https://www.fileformat.info/info/unicode/char/20b9/fontsupport.htm

**Comment by be5invis** [comment]
Landed in Dev. Closed.
![image](https://user-images.githubusercontent.com/240091/84854284-1a959080-b016-11ea-81bb-0b84d81d4de4.png)
