### ISSUE TITLE
More slanted variants - Reverse Italic Oblique, Stronger Slant

### ISSUE THREAD

**Issue by sirinath** [be5invis/Iosevka#599]
Is it possible to reverse italic and oblique so that the font slants left or backwards? Also, stronger slant variants for document preparation and writing.

**Comment by be5invis** [comment]
Changing slope will diffidently create a lot of broken shapes... The only slope I've tested is 10°.
Mark as needs justification.

**Comment by sirinath** [comment]
When writing documents some times it is needed to use different formatting elements consistently.  Adding a weight to the slant will give an additional dimension in formatting where one can use italic within italics within italics (if there are 3 slants). Back slant along with forward slant can be used for 2 different types of italics. 

E.g. the following passage uses English in normal text and Pali in italic. In this case italic-italic is not used but if the English get italicised then the Pali will become italic within italic. 

![image](https://user-images.githubusercontent.com/637415/84562456-55779a00-ad72-11ea-81e5-9e4db0c4380e.png)

Source document: http://www.themindingcentre.org/dharmafarer/wp-content/uploads/2019/01/3.11-Maha-Rahulovada-S-m62-piya.pdf

**Comment by be5invis** [comment]
@sirinath There's already Oblique, which lives alongside Italic. You could use Oblique for Pali transliteration and further turn it into Italic.

**Comment by sirinath** [comment]
If the slant is the same nobody can really tell the difference. Italic, italic-italic, italic-italic-italic, upright italic, back italic, back italic-italic, back italic-italic-italic should be distinguishable for a casual reader. Formatting is to increase clarity. If it cannot be distinguished as different then this is lost.

**Comment by be5invis** [comment]
If you want more slope levels then I can make this into the backlog. I think slope angles less than 10° should work, but not tested.

**Comment by sirinath** [comment]
May be following slope angles might be good to have:
- Italics (light italic, italic, strong italic): -15, -10, -5 (back italics/left-leaning italics); 0 (upright italic); 5, 10, 15 (italics)
- Oblique: -15, -10, -5; 5, 10, 15

(This is very generic but if there are more variety of fonts for writing it will be good.)

**Comment by be5invis** [comment]
@sirinath AFAIK there's no well-known names for different slope grades, so it will require creating separate family names. Also, I will probably **not** make reverse (left-leaning) slopes, since it may create thousands of broken shapes.

**Comment by sirinath** [comment]
If italic, italic in italic and italic in italic in italic it is fine. 

They can be called: italic, italic-italic (italic in italic), italic-italic-italic (italic in italic in italic).

If you can get the left-leaning italics to work it will be good to have. 

Also it would be good to have writing font variants.

**Comment by be5invis** [comment]
What does "writing font variants" mean? Cursive?
It's too far away from Iosevka's style and I will not make it.

**Comment by sirinath** [comment]
What I meant is you only 3 targeted for writing and documentation: Aile, Etoile, Sparkle. If you have more it will be good as you can expect all other features to work than mixing different fonts. Few variants optimised for screen and also a few optimised for print.

**Comment by be5invis** [comment]
@sirinath I call them _quasi-proportional families_
Changing slope should work on monospace variants -- though looks a little meaningless...
This is a 4.0 goal so it won't be landed soon. And official builds will not contain them: it will only be available in custom builds.

**Comment by clsn** [comment]
I think the usual printer's convention for using italics inside italics is that they get printed in roman type.  I've never seen extra-slanted italics used for that purpose (or any other for that matter.)
The classic TeX/Latin Modern unslanted italic is a wonderful violation of expectations, though.

**Comment by clsn** [comment]
I tried these out... 15° slant is hard to tell from the normal 10°.  20° slant is recognizable.  0° slant on the italic isn't _quite_ as jarring as the Latin Modern Unslanted, but still interesting.  -10° slant also came out perfectly fine, if you like that sort of thing.  This was all purely fiddling with the values in parameters.toml.

**Comment by be5invis** [comment]
Angle customization is now supported.
Note that, reverse oblique is currently disabled since it will likely create broken geometry.
If you **really** want to, you can change this line in `verdafile.js`:
```js
const VlSlopeAngle = { validate: x => x >= 0 && x <= 15 };
```
into things like
```js
const VlSlopeAngle = { validate: x => x >= -5 && x <= 15 };
```
