### ISSUE TITLE
Listing in Codeface

### ISSUE THREAD

**Issue by chrissimpkins** [be5invis/Iosevka#6]
This typeface was recommended for inclusion in [Codeface](https://github.com/chrissimpkins/codeface) by @efermi ([Issue Report](https://github.com/chrissimpkins/codeface/issues/104)).  Checking to see if you are at a release stage where you would be prepared to list it at this point.

**Comment by be5invis** [comment]
@chrissimpkins Maybe you should checkout the glyph list at [http://be5invis.github.com/Iosevka]. If you think the glyph coverage is enough now then add to your website.

**Comment by chrissimpkins** [comment]
No problem. I will include it.  Wanted to confirm that you are at a stage where you are prepared to release it for general use.

**Comment by be5invis** [comment]
Maybe after 0.1.0 release i think.

**Comment by chrissimpkins** [comment]
That sounds good.  I will leave the issue report open and check back.

**Comment by be5invis** [comment]
@chrissimpkins r0.1.0 is out, you can list it into Codeface now.

**Comment by chrissimpkins** [comment]
Sounds great Belleve.  I will try to add it later today.

**Comment by chrissimpkins** [comment]
Iosevka is now included in Codeface.  Great looking font Belleve.  I am happy to push updates whenever you release.  Just let me know.

**Comment by be5invis** [comment]
@chrissimpkins Thanks.
