### ISSUE TITLE
Support for ISO 15919, UNRSGN, IAST, ALA-LC, Hunterian, IPA Characters and Symbols

### ISSUE THREAD

**Issue by sirinath** [be5invis/Iosevka#600]
Support for following characters and symbols for writing:
- ISO 15919, 
- UNRSGN, 
- IAST, 
- ALA-LC, 
- Hunterian transliteration,
- IPA Unicode Symbols

The above is to use non-English languages with Roman Script or Roaman transliteration.

**Comment by be5invis** [comment]
Could you give me a list of characters that are still missing?

**Comment by sirinath** [comment]
E.g. from ISO 15919 - ǣ, ñ, s̤, ◌ँ,

**Comment by be5invis** [comment]
@sirinath For your example, `ǣ`, `ñ`, `s̤` are already supported.
The Candrabindu in your comment is the one in Devanagari block (U+0901). Iosevka already supports U+0310 COMBINING CANDRABINDU which is designed for transliterations.
![image](https://user-images.githubusercontent.com/240091/84563695-3812e380-ad12-11ea-9ca6-49d51a6dab60.png)

**Comment by sirinath** [comment]
If the following can be presented then we are good, hence this can be closed:
 
ISO 15919
-- |
a
ā
æ
ǣ
i
ī
u
ū
ŭ
r̥
r̥̄
l̥
l̥̄
e
ē
ê
ai
o
ō
ô
au
ṁ
ṃ
m̐
n̆
ḥ
ẖ
ḫ
ḵ
k
kh
g
gh
ṅ
n̆g
c
ĉ
ch
j
jh
ñ
n̆j
ṭ
ṭh
ḍ
ḍh
ṛ
ṛh
ṇ
n̆ḍ
t
th
d
dh
n
n̆d
p
ph
b
bh
m
m̆b
ṟ
ṯ
ṉ
ḻ
y
ẏ
r
r̆
l
ḷ
v
ś
ṣ
s
h
’
q
k͟h
ġ
z
f
s̱
s̤
h̤
ẕ
ż
ẓ
t̤


IAST | -
-- | --
a | A
ā | Ā
i | I
ī | Ī
u | U
ū | Ū
ṛ | Ṛ
ṝ | Ṝ
Ḷ |  
Ḹ |  
e | E
ai | Ai
o | O
au | Au
ṃ | Ṃ
ḥ | Ḥ
˜ |  
'  |  

velars | palatals | retroflexes | dentals | labials | Category
-- | -- | -- | -- | -- | --
k  K | c  C | ṭ  Ṭ | t  T | p  P | tenuis stops
kh  Kh | ch  Ch | ṭh  Ṭh | th  Th | ph  Ph | aspirated stops
g  G | j  J | ḍ  Ḍ | d  D | b  B | voiced stops
gh  Gh | jh  Jh | ḍh  Ḍh | dh  Dh | bh  Bh | breathy-voiced stops
ṅ  Ṅ | ñ  Ñ | ṇ  Ṇ | n  N | m  M | nasal stops
h  H | y  Y | r  R | l  L | v  V | approximants
  | ś  Ś | ṣ  Ṣ | s  S |   | sibilants

Ligations :

Char | Latin
-- | --
a | a
ā | aa
æ | ae
ǣ | aee
i | i
ī | ii
u | u
ū | uu
ŭ | ^u
r̥ | ,r
r̥̄ | ,rr
l̥ | ,l
l̥̄ | ,ll
e | e
ē | ee
ê | ^e
ai | ai
o | o
ō | oo
ô | ^o
au | au
ṁ | ;m
ṃ | .m
m̐ | ~m
n̆ | ^n
ḥ | .h
ẖ | _h
ḫ | ^h
ḵ | _k
k | k
kh | kh
g | g
gh | gh
ṅ | ;n
n̆g | ^ng
c | c
ĉ | ^c
ch | ch
j | j
jh | jh
ñ | ~n
n̆j | ^nj
ṭ | .t
ṭh | .th
ḍ | .d
ḍh | .dh
ṛ | .r
ṛh | .rh
ṇ | .n
n̆ḍ | ^n.d
t | t
th | th
d | d
dh | dh
n | n
n̆d | ^nd
p | p
ph | ph
b | b
bh | bh
m | m
m̆b | ^mb
ṟ | _r
ṯ | _t
ṉ | _n
ḻ | _l
y | y
ẏ | ;y
r | r
r̆ | ^r
l | l
ḷ | .l
v | v
ś | ;s
ṣ | .s
s | s
h | h
’ |  
q | q
k͟h | _kh
ġ | .g
z | z
f | f
s̱ | _s
s̤ | ,s
h̤ | ,h
ẕ | _z
ż | ;z
ẓ | .z
t̤ | ,t

**Comment by be5invis** [comment]
@sirinath I can confirm that all the transliteration letters are supported.
The symbol `෴` is in the Sinhala block so I won't add it to the char set. It should be implemented by a Sinhala font.
Closed.

**Comment by sirinath** [comment]
Great. Just to confirm the language-specific ligations is also there?

**Comment by be5invis** [comment]
@be5invis Iosevka's "language-specific ligations" is for programming languages. All the composite letters in your list worked well.

**Comment by sirinath** [comment]
OK.
