### ISSUE TITLE
Slab v-u-without-bar doesn't have top serifs

### ISSUE THREAD

**Issue by pv4** [be5invis/Iosevka#601]
Uppercase U has the serifs, both cases of v have them as well.
![Untitled](https://user-images.githubusercontent.com/2502094/84581061-db80f880-ade5-11ea-991d-ab78bdc3fa6e.png)

---

* Your font version: 3.1.1

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/84582465-1f054380-ada1-11ea-9b5a-52148124788a.png)
