### ISSUE TITLE
add npm install patel semver to Build from Source section of the Readme

### ISSUE THREAD

**Issue by dixius99** [be5invis/Iosevka#604]
**Is your feature request related to a problem? Please describe.**
Not sure if this is just me, but to get Iosevka 3.1.1 to build correctly for me on macOS Catalina, I need to `npm install patel semver`, neither of which are listed when I do `npm list`. I've had to install `patel` for some time, but installing `semver` in this way appears to be new since 3.0.1.

**Describe the solution you'd like**
Can we add something about this to the Building from Source section of the Readme? Or, if there is a reason I have to do this but not others, could we put something in about the reason?

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by be5invis** [comment]
They were listed in `devDependencies`. Moved to `dependencies` so this could be fixed.
