### ISSUE TITLE
The figure 6 very closely resembles cyrillic letter б

### ISSUE THREAD

**Issue by StoyanDimitrov** [be5invis/Iosevka#605]
Well, it could be just me but the form of the figure 6 very much looks like the cyrillic letter б. Especially after other numbers, most prominent example being 9.

I truly understand that this is more or less a cultural issue.

---

* Your font version: 3.1.1
* Your font variant: Curly Extended
* Your operating system (name and version): Windows 7
* Your application using Iosevka: text editor

![iosevka-6-and-б](https://user-images.githubusercontent.com/10962709/84887719-b6121a00-b085-11ea-95e2-5f9c1e2e06a6.png)

Of course it is not directly evident from the image provided as there could easily be made distinction between 6 and б.

**Comment by orlin** [comment]
Interesting observation, myself a Bulgarian I can certainly recognize the challenge and wish for a better distinction among all characters, be it numbers or letters in any language.  This is a prime reason for custom-building an Iosevka after all.  A perfection of design with regards to personal use.  Perhaps it would help if the 6 were more rounded down in trajectory just like the 9's tail is rounded up.  Though I would rather as well see slylistic variations of "б".

**Comment by be5invis** [comment]
@StoyanDimitrov @orlin 
Well in `dev` there are three purposed variants for `6` so we should be able to distinguish it with `б`.
![image](https://user-images.githubusercontent.com/240091/84975157-9573af80-b0d9-11ea-9555-fc324ad15fd3.png)

**Comment by be5invis** [comment]
I plan to do this:

 * Default `6` and `9` to the new straight-bar variant for better style consistency;
 * Make `6` and `9` curly in the Curly variants and `ss20` style.

As a result it will look like this:
![image](https://user-images.githubusercontent.com/240091/85088962-25772f00-b196-11ea-993c-f83c7f03b0fb.png)

This, in normal case, will have pretty good distinction between `6`, `b` and `б`.
Closed as fixed.
