### ISSUE TITLE
Differentiate between "not equal" ligatures

### ISSUE THREAD

**Issue by akarzim** [be5invis/Iosevka#608]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [ ] Some other monospace/programming fonts supported the requested variant. Provide images below.

------

Why not distinguish the `/=` ligature from the `!=` ligature for those who want to enable both the default ligature and Haskell's "not equal" ligature when using discretionary ligatures (`dlig`)?

Here is a proposal based on the oblic bang:

![diff](https://user-images.githubusercontent.com/130560/85004106-74ea3a80-b157-11ea-9753-7c6793dc192e.png)

**Comment by be5invis** [comment]
For Haskell, it is preferred to use `HSKL` rather than `dlig`. In most editors if the user could enable `dlig` then he/she should be able to enable `HSKL` and use Haskell-specific ligatures for Haskell. AFAIK, VSCode support such configuration.

**Comment by akarzim** [comment]
I use Vim in a terminal to write code. So Vim uses the font used by the console/terminal. It makes no sense (and it is not possible) to change the terminal's font depending on the file being edited.

**Comment by be5invis** [comment]
@akarzim I will not add ambiguous ligation for `dlig`, but I can add a `calt`-customization option `calt-exeq-alt-1` for an alternative `exeq`, so you could customize like this:

```toml
[buildPlans.iosevka-custom]
design = [
  'calt-center-ops', 'calt-arrow', 'calt-arrow2', 'calt-trig', 'calt-llgg', 'calt-eqeq',
  'calt-ineq', 'calt-slasheq', 'calt-exeq-alt-1', 'calt-ltgt-diamond', 'calt-plusplus',
  'calt-dotoper', 'calt-kern-dotty', 'calt-logic'
]
```

**Comment by akarzim** [comment]
Looks perfect. Thank you!
