### ISSUE TITLE
Slab uppercase R curly leg is not curly enough

### ISSUE THREAD

**Issue by pv4** [be5invis/Iosevka#609]
Like in #591 for other glyphs, the right leg of R curly slab variant doesn't look curly enough. I do can see it is curly indeed, but is it possible to make it "more curly" as it was done in #591 please?

---

* Your font version: 3.1.1

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/85086954-f8744d80-b190-11ea-93f5-824cea7cac1a.png)
