### ISSUE TITLE
Variant request: abdgmnpqr without bars

### ISSUE THREAD

**Issue by edubart** [be5invis/Iosevka#610]
Would be cool to have possibility to have variants for the characters `abdgmnpqr` without the "tiny" bars, this is something already possible on `u` glyph for example (with `v-u-without-bar`/`cv90`). To be more specific:

- on `a` with `cv02` remove the upper right bar (but leave the lower right)
- on `b` remove the lower left bar
- on `d` remove the lower right bar
- on `g` remove the upper right bar
- on `m` remove the upper left bar
- on `n` remove the upper left bar
- on `p` remove the upper left bar
- on `q` remove the upper right bar
- on `r` remove the upper left bar

This is more a personal desire because I usually write characters by hand in that style and I can almost match all my hand written characters with Iosevka except these details.

In any case, thank you very much for this great font!

**Comment by be5invis** [comment]
This kind of shape for _these_ letters is very uncommon in monospace fonts and goes somehow far away from Iosevka's current visual style.
Also the "barless" `r` will conflict with U+027E Latin Small Letter R with Fishhook `ɾ`.
Mark as _needs justification_.

**Comment by edubart** [comment]
Ubuntu Mono has barless for these letters (except `a`).

![](https://i.gyazo.com/25f4c9af548409b8d93d01dc077f2547.png)
https://fonts.google.com/specimen/Ubuntu+Mono?category=Monospace&preview.text=abdgmnpqr&preview.text_type=custom

Maybe `r` `n` `m` could be left out, I find more appealing on letters with "`o`" circle like `abdpq`.

**Comment by be5invis** [comment]
I see, but really, these are very handwrite-ish and "Humanist", compared to Iosevka's more Grotesque-ish design.

**Comment by edubart** [comment]
Ok, thanks for the response! I appreciate what Iosevka already offers.
