### ISSUE TITLE
Give U+0192 full top arch

### ISSUE THREAD

**Issue by AlsoScratch** [be5invis/Iosevka#611]
**Is your feature request related to a problem? Please describe.**
The U+0192 shape seems to be a copy of `f` with `cv53`. This can result in problems differentiating them.

**Describe the solution you'd like**
I feel it would be more consistent if U+0192 had a full semi-circular top arch, like default `f`.

**Describe alternatives you've considered**

**Additional context**
<img width="112" alt="Screenshot 2020-06-19 at 10 47 41 PM" src="https://user-images.githubusercontent.com/48752273/85145294-f4265e00-b27e-11ea-9005-6b589eb3bd22.png">
You can probably just take the part below the baseline from U+0191 and attach it on to `f`.
<img width="118" alt="Screenshot 2020-06-20 at 11 49 02 AM" src="https://user-images.githubusercontent.com/48752273/85190578-38037c80-b2ec-11ea-8926-60539338efaf.png">

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/85190721-106ece80-b270-11ea-8d36-79a38c4d14b9.png)
