### ISSUE TITLE
ľ mark too high

### ISSUE THREAD

**Issue by AlsoScratch** [be5invis/Iosevka#613]
Describe your problem here. Provide pictures and files if necessary.

<img width="131" alt="Screenshot 2020-06-21 at 11 49 23 AM" src="https://user-images.githubusercontent.com/48752273/85216298-508b9980-b3b5-11ea-8255-a1844e782da2.png">

---

* Your font version: 3.2.0
* Your font variant: Fixed
* Your operating system (name and version): macOS 10.15.5
* Your application using Iosevka: Font website

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/85217007-8fcbd300-b340-11ea-9c4b-ea027f9e1e6e.png)
