### ISSUE TITLE
Cap R with bar too high now

### ISSUE THREAD

**Issue by AlsoScratch** [be5invis/Iosevka#614]
Describe your problem here. Provide pictures and files if necessary.
<img width="129" alt="Screenshot 2020-06-21 at 12 06 15 PM" src="https://user-images.githubusercontent.com/48752273/85216510-dad4fd00-b3b7-11ea-96ac-0c838ab727a0.png">

---

* Your font version: 3.2.0
* Your font variant: Fixed
* Your operating system (name and version): macOS 10.15.5
* Your application using Iosevka: Font website

**Comment by be5invis** [comment]
![Uploading image.png…]()
