### ISSUE TITLE
7 with stroke issues

### ISSUE THREAD

**Issue by AlsoScratch** [be5invis/Iosevka#615]
The bar through the stem should be about the same thickness as the top. And I don't think it's supposed to completely change position in old-style figures.

<img width="171" alt="Screenshot 2020-06-21 at 12 23 34 PM" src="https://user-images.githubusercontent.com/48752273/85216675-0eb12200-b3ba-11ea-8833-e1cfe10534af.png">

---

* Your font version: 3.2.0
* Your font variant: Fixed
* Your operating system (name and version): macOS 10.15.5
* Your application using Iosevka: Font website

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/85217134-4a100a00-b342-11ea-8fe4-3f050cf21e0a.png)
