### ISSUE TITLE
D that is less like O

### ISSUE THREAD

**Issue by moosotc** [be5invis/Iosevka#616]
-- *Please provide your your justification here.*
At certain size, in certain conditions, due to visual system ailment i can't tell what i'm looking at at a glance.
![shot](https://user-images.githubusercontent.com/10325345/85216890-dea25880-b392-11ea-8323-c29ccf0c4705.png)

**Comment by paolobolzoni** [comment]
While I can understand the sentiment, the font in the picture does not look like Iosevka to me. Here is how it appears in my system

![pngout](https://user-images.githubusercontent.com/1133562/85240907-e0444d00-b474-11ea-9920-f31f99b96ef2.png)

About the topic, would be possible to bump a bit the left vertical line of the D so it is not straight and distinguish more to the O?

**Comment by moosotc** [comment]
Paolo Bolzoni <notifications@github.com> writes:

> While I can understand the sentiment, the font in the picture does not
> look like Iosevka to me. Here is how it appears in my system
>

Pirture is of 'fantasque sans mono', sorry for not making it clear.

> ![pngout](https://user-images.githubusercontent.com/1133562/85240907-e0444d00-b474-11ea-9920-f31f99b96ef2.png)
>
> About the topic, would be possible to bump a bit the left vertical
> line of the D so it is not straight and distinguish more to the O?

**Comment by moosotc** [comment]
And to further clarify the picture shows what "better for me"-rendering look like.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/85376117-25f02c80-b4ec-11ea-9767-92b3029828b8.png)

**Comment by moosotc** [comment]
Belleve Invis <notifications@github.com> writes:

> ![image](https://user-images.githubusercontent.com/240091/85376117-25f02c80-b4ec-11ea-9767-92b3029828b8.png)

For me (extra expanded) adding v-capital-d-more-rounded to design
does not make any difference whatsoever, perhaps i'm missing something
important?

**Comment by paolobolzoni** [comment]
Did you download the "dev" branch? I got the code with
```git clone -b dev --depth=1 'https://github.com/be5invis/Iosevka.git'```
and it worked for me.

To match the style of Fantasque Sans Mono I'd kinda expected the top half of the D be like VXBH and the bottom half be like VXBG, though.

**Comment by moosotc** [comment]
moosotc@gmail.com writes:

> Belleve Invis <notifications@github.com> writes:
>
>> ![image](https://user-images.githubusercontent.com/240091/85376117-25f02c80-b4ec-11ea-9767-92b3029828b8.png)
>
> For me (extra expanded) adding v-capital-d-more-rounded to design
> does not make any difference whatsoever, perhaps i'm missing something
> important?

I retract that, sorry and thank you. (Apparently my vision problems are
even more severe than i thought)

**Comment by paolobolzoni** [comment]
![pngout](https://user-images.githubusercontent.com/1133562/85382626-1c150a80-b57a-11ea-993c-71223f4bfc3c.png)

Kinda like this. (It does not matter anymore, though)
