### ISSUE TITLE
The character(s) Ѳ/ѳ

### ISSUE THREAD

**Issue by Emexus** [be5invis/Iosevka#617]
- The requested character is...
  - [ ] Latin
  - [X] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [ ] Symbol
- [X] Some other monospace/programming fonts supported this character. Provide images below.
![image](https://user-images.githubusercontent.com/20151443/85217778-9ab05300-b394-11ea-9d1a-d1112fb68182.png)

------

This character is part of the Cyrillic alphabet, me and some contacts use it quite a bit. With not that many fonts correctly supporting it (especially with the use of combining diacritics) it couldn't hurt to have this character here too, even if the use of it is likely to be not all that high.
( Note that this character shouldn't be confused with the Greek Theta )

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/85218696-7ed78d80-b351-11ea-88ce-d4a964cf02e6.png)

**Comment by alexeyten** [comment]
I think author referred to cyrilllic letter oe https://en.wikipedia.org/wiki/Oe_(Cyrillic), not archaic fita

**Comment by Emexus** [comment]
> 
> 
> I think author referred to cyrilllic letter oe https://en.wikipedia.org/wiki/Oe_(Cyrillic), not archaic fita

Sorry for the confusion, I should have noted it as archaic, the Oe character already is supported by Iosevka.

**Comment by alexeyten** [comment]
Oh, sorry
