### ISSUE TITLE
Reversed E is upside-down

### ISSUE THREAD

**Issue by AlsoScratch** [be5invis/Iosevka#618]
I believe it should only be upside-down if it's called 'turned', not 'reversed'.
<img width="44" alt="Screenshot 2020-06-21 at 3 14 10 PM" src="https://user-images.githubusercontent.com/48752273/85218956-fbaa4c00-b3d1-11ea-823d-9e7227986bb1.png">

---

* Your font version: 3.2.0
* Your font variant: Fixed
* Your operating system (name and version): macOS 10.15.5
* Your application using Iosevka: Font website

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/85221304-adf8f980-b367-11ea-9d9e-6b1d49207b16.png)
