### ISSUE TITLE
Extendedness is not applied to circled/squarred characters

### ISSUE THREAD

**Issue by moosotc** [be5invis/Iosevka#619]
All "boxed" letters follow default narrow style disregarding the values of [buildPlans.*.widths.*]

**Comment by be5invis** [comment]
`buildPlans.<plan name>.widths` doesn't change the metrics of enclosed symbols (like `Ⓐ`).
For them, they default to wide by default and could be switched into narrow if you include `sp-term`/`sp-force-monospace`/`sp-fixed` in the `design` options in the building plan.

**Comment by moosotc** [comment]
Belleve Invis <notifications@github.com> writes:

> `buildPlans.<plan name>.widths` doesn't change the metrics of enclosed
> symbols (like `Ⓐ`).
> For them, they default to wide by default and could be switched into
> narrow if you include `sp-term`/`sp-force-monospace`/`sp-fixed` in the
> `design` options in the building plan.

Ah, thing is i want(and use) extended _AND_ sp-fixed..
https://github.com/moosotc/snippets/blob/master/bin/configure/private-build-plans.toml

**Comment by be5invis** [comment]
@moosotc The width but work, but remember, `sp-fixed` will wipe out all glyphs wider than one cell to please certain software like FontConfig, so you will get narrow enclosed letters.

**Comment by be5invis** [comment]
@moosotc If you simply want to disable ligatures, use `no-ligation` instead of `sp-fixed`.

**Comment by moosotc** [comment]
Belleve Invis <notifications@github.com> writes:

> @moosotc If you simply want to disable ligatures, use `no-ligation`
> instead of `sp-fixed`.

That works, thank you. Though sp-fixed making things non fixed in the
case of my build-plans is counter-intuitive.
