### ISSUE TITLE
Clarity of exclamation mark (!)

### ISSUE THREAD

**Issue by IceMan81** [be5invis/Iosevka#62]
I find that its hard to notice the exclamation mark while looking at a page full of code - it almost looks like a vertical bar. If the space between the vertical bar & the dot is increased, then it would be a bit more visible.

**Comment by be5invis** [comment]
So does this one looks better?
![image](https://cloud.githubusercontent.com/assets/240091/13171717/3b3dd3ca-d72f-11e5-9a10-37c3bcc477cf.png)


Compared to the current one:
![image](https://cloud.githubusercontent.com/assets/240091/13171671/0b7d47ce-d72f-11e5-91dd-c026f54a1fe7.png)

**Comment by IceMan81** [comment]
@be5invis Yes, definitely a lot better! Thank you!
