### ISSUE TITLE
Open octothorpe

### ISSUE THREAD

**Issue by paolobolzoni** [be5invis/Iosevka#621]
The octothorpe of IBM Plex looks somewhat weird, but it is well readable even when displayed very small. Since Iosevka is used for code and it is very tight I think it would be a valuable addition to have a bit more breeze in the text.

![IBM Plex mono octothorpe](https://user-images.githubusercontent.com/1133562/73898294-45374600-48cc-11ea-8d3a-57104df5a469.png)
(IBM Plex mono octothorpe)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/85823962-8329ef00-b733-11ea-9fd3-c0d3c186d03b.png)

**Comment by paolobolzoni** [comment]
Even after downloading the latest dev code this simple build plan leave the number sign closed and upright... Am I missing something?

I open the resulting regular font with DTL OTMaster and checked the octothorp with Glyph Index (gid) 6.

```
 $ cat private-build-plans.toml
# parameters.toml

[buildPlans.iosevka-paopao]
family = "Iosevka Paopao test"

design = [ "sp-fixed", "VXBI" ]
hintParams = ["-a", "sss"]

[buildPlans.iosevka-paopao.weights.light]
shape = 300
menu  = 300
css   = 300

[buildPlans.iosevka-paopao.weights.regular]
shape = 500
menu  = 400
css   = 400

[buildPlans.iosevka-paopao.weights.bold]
shape = 700
menu  = 700
css   = 700

[buildPlans.iosevka-paopao.slants]
upright = "normal"
italic = "italic"
```

**Comment by be5invis** [comment]
@paolobolzoni What's your command used to build fonts. I used `npm run build -- contents::iosevka-paopao` and the result match expectation.
![image](https://user-images.githubusercontent.com/240091/86103879-294a6180-ba72-11ea-8928-a47ec5276669.png)

**Comment by paolobolzoni** [comment]
The command was the same. The I tried to fully reset the building environment. But after compiling ```otfcc```it fails at one test:
```
[...] [==========] 1990 tests from 183 test suites ran. (5981 ms total)
[  PASSED  ] 1989 tests.
[  FAILED  ] 1 tests, listed below:
[  FAILED  ] premake_http.http_redirect
HTTP response code said error
The requested URL returned error: 404 Not Found
```
Of course, previously this did not happen. I will try to understand more.

**Comment by paolobolzoni** [comment]
I know it is not great, but merely skipping the otfcc tests after the compilation and then resetting the whole building environment gave the expected result.
