### ISSUE TITLE
v-u-without-bar and italic cyri/cyrtse(/cyrdzhe)

### ISSUE THREAD

**Issue by pv4** [be5invis/Iosevka#625]
When using v-u-without-bar the generated `u` glyph is used for italic variant of `cyri`, `cyrtse` and `cyrdzhe`. As a result the mentioned cyrillic glyphs look incorrect for me as for native Russian speaking man.

On the picture attached the red regions are what looks wrong. The green region is what is done right (to simplify comparison for you).

The attached patch fixes the issue for me. `cyri.italic` and `cyrtse.italic` must refer to `u.withBar` instead of just `u`.

The `cyrdzhe.italic` glyph is also fixed in the patch. I've never seen this one in my life but according to https://en.wikipedia.org/wiki/List_of_Unicode_characters#Cyrillic it is symmetric and therefore should refer to `u.withoutBar`.

I only noticed these three glyphs but there may be other ones as well that become incorrect when using different variants for latin glyphs they refer to.

![comparison](https://user-images.githubusercontent.com/2502094/86386394-5aa57600-bc9a-11ea-9772-0857b5fde46d.png)
[Iosevka-3.2.2-cyrillic_italic.patch.gz](https://github.com/be5invis/Iosevka/files/4865566/Iosevka-3.2.2-cyrillic_italic.patch.gz)

---

* Your font version: 3.2.2

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/86425675-a22c0200-bc9a-11ea-8a0b-cde1fc24fe70.png)

**Comment by pv4** [comment]
Just for the record. You're right. The `cyrdzhe.italic` can be unsymmetric. The attached image is from wikipedia.

![Serbian-italic](https://user-images.githubusercontent.com/2502094/86469849-ea9efa80-bd42-11ea-808b-8c58fd90b956.png)

**Comment by eevan78** [comment]
I'm а native Serbian.
In italic variants off all typefaces, the lowercase letter dzhe (џ) has the vertical line in the middle of the character width.
The one in the proposed glyph here should be moved a bit to the right, so that it sits in the center, like it is on the uppercase Џ.

![](https://user-images.githubusercontent.com/240091/86425675-a22c0200-bc9a-11ea-8a0b-cde1fc24fe70.png)

**Comment by be5invis** [comment]
@eevan78 Italic `џ` is handled in different ways in sans-serif fonts: some of them use off-center bars and some of them use detached bar. Perhaps we could try the detached variant.

Noto Sans
![image](https://user-images.githubusercontent.com/240091/89999899-4c0c9000-dc44-11ea-9b0c-325565e1aa9f.png)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/90003101-71030200-dc48-11ea-9a43-b837f7ae4b07.png)
This should look better

**Comment by eevan78** [comment]
Yes, I agree, this one looks better. Thanks!
