### ISSUE TITLE
v-w-straight with short middle for readability

### ISSUE THREAD

**Issue by pv4** [be5invis/Iosevka#626]
For me the current `v-w-straight` variant looks mush less readable than `v-w-curly` mostly because of its longer middle (especially at small font sizes). In curly variant the space at the top between the legs (marked by the green color on the picture) allows to recognize the letter faster. In the current straight variant the space is much less (marked by the red color) which makes it harder to recognize the letter, especially in sequences like "NWM".

The patch attached fixes that by just setting the height of the middle in straight variant equal to the height in curly variant. Maybe you will find it too brute and that some more improvements should be made further (e.g. change thickness of the middle components).

My HUMBLE opinion is that the current straight variant is unreadable and could be just replaced by something like the suggested one without adding a new v-w-* variant.

![comparison](https://user-images.githubusercontent.com/2502094/86387145-65acd600-bc9b-11ea-9221-e8cff40ca5b4.png)
[Iosevka-3.2.2-w.patch.gz](https://github.com/be5invis/Iosevka/files/4865629/Iosevka-3.2.2-w.patch.gz)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/86426802-6e061080-bc9d-11ea-95ab-c76b02c40695.png)
