### ISSUE TITLE
v-k-cursive forces v-k-straight for other k variants

### ISSUE THREAD

**Issue by pv4** [be5invis/Iosevka#627]
When using `v-k-cursive` for italic latin `k` other referred letters become straight.

On the picture are uppercase and lowercase latin and cyrillic glyphs. In current implementation (without editing `params/variants.toml`) it's impossible to make lowercase latin `k` cursive while making other variants of `k` (e.g. cyrillic `k`) curly. Moreover, even if changing `params/variants.toml` the leg of cursive `k` is straight (and smaller than the curly variant) though it should be curly if other `k` variants are curly.

I understand that drawing a separate variant of cursive `k` with curly leg can create extra unnecessary complication. And I don't want to waste your time. Even with this issue unfixed Iosevka is one of the best fonts I've seen anyway and I use it wherever I can: in Linux gui interfaces, in terminals (Linux/Windows/macOS), in Firefox (I force Iosevka over the fonts sites suggest).

So this issue is just a notice. Please, feel free to close it without any action if you wish. For me, italic variant of `v-k-curly` works fine.

![k](https://user-images.githubusercontent.com/2502094/86388908-3a77b600-bc9e-11ea-8266-6df218c66c93.png)

---

* Your font version: 3.2.2

**Comment by be5invis** [comment]
I'd like to add `v-k-curly-cursive`, but adding a fourth `k` is unnecessary.
![image](https://user-images.githubusercontent.com/240091/86428658-27ff7b80-bca2-11ea-9429-b5450e3c082b.png)

**Comment by pv4** [comment]
Thank you.
