### ISSUE TITLE
"Fat" exclamation mark

### ISSUE THREAD

**Issue by paolobolzoni** [be5invis/Iosevka#628]
I use Iosevka in my terminal, and most of my job is in the terminal. When programming the exclamation mark has the meaning of **not** and seldom I miss it in the expressions, it is especially a problem with Javascript as some values are _falsy,_ but not _false_ (e.g., _null_ `!!null` is false, but `null == false` is also false).  Iosevka is very thigh, but for its shape the exclamation mark can be made a bit wider without problems.

Still, I understand it can look out of place.

Here is an example, a M as reference, the exclamation mark as it is, a wider one.

![pngout](https://user-images.githubusercontent.com/1133562/86998686-db5cf880-c1eb-11ea-8711-d32d8f2fc30f.png)

**Comment by be5invis** [comment]
Shouldn't the highlighter do the job to make the `!` thicker?

**Comment by paolobolzoni** [comment]
The terminal emulator handles bold, but I am not sure how to tell it to make the exclamation marks bold. However, fair enough. Closing.
