### ISSUE TITLE
Single-storey 'a' with a slightly tail botton-right tail.

### ISSUE THREAD

**Issue by V2clemjqNLPafssN** [be5invis/Iosevka#631]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] Some other monospace/programming fonts supported the requested variant. Provide images below.

------

Please add a variant for 'a' with a slightly tail botton-right tail like Space Mono (left) and without the tooth like Monaco (right).
![I wrote them](https://s1.ax1x.com/2020/07/14/Uauf4H.md.jpg)
### Space Mono:
![a in Space Mono](https://user-images.githubusercontent.com/43498546/87431962-f380ad80-c619-11ea-9e6c-be6031e67070.png)
### Monaco:
![a in Monaco](https://user-images.githubusercontent.com/43498546/87431983-f9768e80-c619-11ea-9193-115158d5d488.png)

**THANKS!!**

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/87507671-a48b4600-c622-11ea-802e-898762640bfd.png)

**Comment by V2clemjqNLPafssN** [comment]
Lowercase `u` also need a slightly tail botton-right tail.
![u](https://s1.ax1x.com/2020/07/15/U08qDH.th.jpg)
