### ISSUE TITLE
request sparkle ligatures

### ISSUE THREAD

**Issue by liangjingkanji** [be5invis/Iosevka#633]
I like iosevka sparkle, but no ligatures.  And I like this style.
![image](https://user-images.githubusercontent.com/21078112/87662429-c86e9900-c794-11ea-97ff-1403b6123f1e.png)

**Comment by liangjingkanji** [comment]
Jetbrains mono of ligature is beautiful

**Comment by be5invis** [comment]
Sparkle is quasi-proportional so all the symbols are supposed to use real Unicode characters (for inequality are `≤` and `≥` instead of ligation.
