### ISSUE TITLE
7 middle bar should be as thick as the top bar

### ISSUE THREAD

**Issue by AlsoScratch** [be5invis/Iosevka#634]
At bold weights, the middle bar in the `7` is much thinner than the top bar. I feel they should be almost about the same thickness.

<img width="124" alt="Screenshot 2020-07-17 at 12 36 28 PM" src="https://user-images.githubusercontent.com/48752273/87749159-78421600-c82a-11ea-95c9-61d4f676b8dd.png">

**Comment by be5invis** [comment]
Well all the crossbars in Iosevka share the same thickness grade. You can compare this with other glyphs with the same crossbar.

**Comment by AlsoScratch** [comment]
To me, it looks strange, especially at weight 9.

**Comment by AlsoScratch** [comment]
I feel this is different from the other characters that contain a "crossbar" like `Đ` or `Ħ`.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/87762156-814dcb80-c7c7-11ea-9f06-2b57d7596431.png)

**Comment by AlsoScratch** [comment]
Seems about right.
