### ISSUE TITLE
Single-storey 'u' with a slightly tail botton-right tail and 'Q' like Vehicle registration plates

### ISSUE THREAD

**Issue by V2clemjqNLPafssN** [be5invis/Iosevka#636]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [ ] Some other monospace/programming fonts supported the requested variant. Provide images below.

------

Lowercase `u` also needs a slightly tail botton-right tail like #631 .
Uppercase `Q` needs a variant like Vehicle registration plates. Here's the example.
**The 1992 standard**
![92Q](https://user-images.githubusercontent.com/43498546/87875577-c4e14900-ca04-11ea-9b84-f86ce2acd2d1.png)
**New Energy Vehicles Plates**
![NewEnergyQ](https://user-images.githubusercontent.com/43498546/87875538-6d42dd80-ca04-11ea-9ff0-a72b543f35e1.png)

THANKS

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/87882434-d7339680-c9b4-11ea-9543-947174fceed2.png)
