### ISSUE TITLE
Tailed two-story a

### ISSUE THREAD

**Issue by throwaway571** [be5invis/Iosevka#637]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [ ] Some other monospace/programming fonts supported the requested variant. Provide images below.

------

This is mostly to round out the list of character variants for `a`.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/88031633-b0c74580-caf1-11ea-8ced-6b590f3a7321.png)
