### ISSUE TITLE
Flipped asterisk

### ISSUE THREAD

**Issue by paolobolzoni** [be5invis/Iosevka#638]
Recently I had to write graphics-related code and seldom I noticed I was mixing up the asterisk for multiplication with the plus.

Perhaps to flip the asterisk or push it a bit up (like the low caret) would help?

Here how it looks a five stars flipped asterisk.
![pngout](https://user-images.githubusercontent.com/1133562/88026367-bb74ef80-cb70-11ea-816f-4661d2b80ab3.png)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/88033390-2df3ba00-caf4-11ea-861c-980580f808b7.png)

**Comment by paolobolzoni** [comment]
Thanks, it works really well. As I suspected, the vertical stroke on top was confusing my sight.
