### ISSUE TITLE
Variant request swash for bdhkpr, mirror ear/tail of i, j, no ear capital J, no-descender Q with straight leg, M and W with strokes meeting baseline/capital line respectively, zZ with horizontal dash

### ISSUE THREAD

**Issue by pagerc** [be5invis/Iosevka#640]
### Swash tails (maybe ears too?) for bdhkpr:
![image](https://user-images.githubusercontent.com/1564837/88422374-26fcce00-cdb8-11ea-970b-5cebe4765732.png)

We have swash tails for i, j, q, u, and y so this is extending the supported characters with lower-case swash tails.

### Mirror ear/tail of i and j:
![image](https://user-images.githubusercontent.com/1564837/88422578-793def00-cdb8-11ea-9162-eeb99d2266af.png)

### No ear capital on J:
![image](https://user-images.githubusercontent.com/1564837/88423402-bb1b6500-cdb9-11ea-947d-e9313c386c06.png)

### No-descender Q with straight leg:
Provides the option to have all capitals with no-descenders.
![image](https://user-images.githubusercontent.com/1564837/88422974-097c3400-cdb9-11ea-9f20-d2e5d46b1f3c.png)

### M and W with interior strokes meeting baseline and capital line respectively:
![image](https://user-images.githubusercontent.com/1564837/88423370-ad65df80-cdb9-11ea-9d63-2316fdc66fda.png)

### Horizontal dash on lower/capital zZ:
Option to set variants for z and Z to same symbol used for; U+01B5 Ƶ LATIN CAPITAL LETTER Z WITH STROKE and U+01B6 ƶ LATIN SMALL LETTER Z WITH STROKE.
ƶƵ
Per this discussion:
https://github.com/be5invis/Iosevka/issues/595

### Bonus (D with dash (requested elsewhere, included here for completeness of unicode variant for ASCII subset)
Option to set variant for D to same symbol used for; U+0110 LATIN CAPITAL LETTER D WITH STROKE.
Đ

### Bonus (two-more 4 variants):
![image](https://user-images.githubusercontent.com/1564837/88423585-fae24c80-cdb9-11ea-9c55-a367ef8f779e.png)

------
Justification:
The swash options are for stylistic choices by users.
The no-descender Q resolves an inconsistency amongst the current capital letters.
Design option for M/W to be full height across body.
Horizontal dash is preferred over slanted mark 
Bonus requests!

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/88446430-aef5ce80-cdde-11ea-9774-60b16b64cff9.png)

**Comment by be5invis** [comment]
I'd like to reject “D as `Đ`” and “mirrored” `i`/`j`. “D as `Đ`” will create too many confusions, since it is the capital form of *three different letters* (`ð`, `đ` and `ɖ`). Mirrored `i`/`j` are too unusual and doesn't match Iosevka's style.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/88447018-e1ee9100-cde3-11ea-86c6-40f7ea8a1bbe.png)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/88447582-90e19b80-cde9-11ea-9aa2-a3c006e2135f.png)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/88453348-f8fca580-ce1a-11ea-9933-ee40c5be58c7.png)

**Comment by be5invis** [comment]
OK, all justified variants are added. Closing this.
