### ISSUE TITLE
Variant % with unobstructed diagonal and circles on either side

### ISSUE THREAD

**Issue by pagerc** [be5invis/Iosevka#643]
I think the existing dotted percent with the dots being inverted to create circles would accomplish this variant look:
![image](https://user-images.githubusercontent.com/1564837/88449759-76beb200-ce17-11ea-93cc-8d7e6b784df5.png)

------
Traditional percent

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/88455517-b642c980-ce2a-11ea-9d8f-677be4eed8b9.png)

**Comment by pagerc** [comment]
I thank you kindly for all of your hard work on this. I'm humbly pointing out that I'd like an option with circles instead of ovals. Is that possible?

**Comment by be5invis** [comment]
@pagerc Iosevka's outline is pretty narrow so using circles would severely unbalance the geometry.
