### ISSUE TITLE
Missing variants of compound glyphs on specimen page

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#644]
https://typeof.net/Iosevka/specimen is missing some variants for characters made of multiple pieces, where each piece has its own variant. For example, here is the specimen of U+246C CIRCLED NUMBER THIRTEEN.
![Specimen of ⟨⑬⟩](https://user-images.githubusercontent.com/1124347/88482039-baefa680-cf2c-11ea-9978-0427bf12a014.png)
This is missing two variants (`'NWID' on, 'VXAM' on, 'cv46' on` and `'WWID' on, 'VXAM' on, 'cv46' on`), shown here in Iosevka Extended 3.3.1.
![⑬⑬](https://user-images.githubusercontent.com/1124347/88482222-e6bf5c00-cf2d-11ea-8f6c-2008ab0962cd.png)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/88492981-89de9880-cf63-11ea-9413-5d73c1c09ed7.png)
