### ISSUE TITLE
Legibility test block suggestion

### ISSUE THREAD

**Issue by pagerc** [be5invis/Iosevka#645]
Dropping this test block for consideration for partial/full inclusion.
```
!ilI17 AHH-eye-ell-Eye-one-seven
co0ODQ see-oh-zero-Oh-Dee-Cue
b6&B80 bee-six-et-Bee-eight-zero
sS5$S  ess-Ess-five-dollar-Ess
abcdefghijklmnopqrstuvwxyz .?!'"
ABCDEFGHIJKLMNOPQRSTUVWXYZ ,;:-_
1234567890 ,._-+=>< --__ ~-+=><
!@#$%^&*() <> '"`~_-=+*\/|!?,.:;
{}[]()<>$*-+=/#_%^@\&|~?'" !,.;:
a@ B8 dbqp E3 i! 96 G6& g9qCGQ
coO08BbODQ |!iIlL17 $5SZ2zsz
TtijJlFPRK vvw VVW \/V
```

Reasons for the test block are to highlight potential text legibility concerns:
- OCR error rate
- character kerning creates touching characters: {}[]()<>vvVV\/--__
- characters for math/programming not x-height centered: {}[]()<>~-+*=
- similar glyph shapes: b6&B80 coO08BbODQ |!iIlL17 $5SZ2zsz
- printed ink smudge/fade resistance: TtijJlFPRK
- mirrored/rotated glyphs (dyslexic resistance): a@ B8 dbqp E3 i! 96 G6& g9qCGQ
- symbol distinction: `'"!\|/

**Comment by be5invis** [comment]
Perhaps it could be used to generate preview images :)
Closed
