### ISSUE TITLE
Combining letters have overlapping descenders

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#646]
The descenders of combining above-base letters overlap the bases. For example, here is ⟨cᷗ⟩ (<U+0063 LATIN SMALL LETTER C, U+1DD7 COMBINING LATIN SMALL LETTER C CEDILLA).
![cᷗ](https://user-images.githubusercontent.com/1124347/88496983-dd191100-cf8c-11ea-9f59-02919d586d95.png)

---

* Your font version: 3.3.1
* Your font variant: Iosevka Slab Extended
* Your operating system: macOS 10.14.6
* Your application using Iosevka: hb-view

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/88501201-9c66cb00-cf7f-11ea-8e73-13d4abd054a9.png)
