### ISSUE TITLE
cyrpe.italic and cyrte.italic improvements after commit de85fce "Add tailed variant for `m`, `n` and `h`"

### ISSUE THREAD

**Issue by pv4** [be5invis/Iosevka#647]
As a native Russian speaker I should say that `cyrpe.italic` and `cyrte.italic` can have tails similar to italic latin `n` and `m`.

So, after the commit de85fce "Add tailed variant for `m`, `n` and `h`" the following improvement can be made:
```diff
-alias 'cyrpe.italic' null 'n.straight'
+alias 'cyrpe.italic' null 'n'
```

The similar can be made with
```
alias 'cyrte.italic' null 'm.normal'
```
except `cyrte` should not have `shortleg` variant.

Also you can look at https://i.stack.imgur.com/qJGGD.gif (taken from https://russian.stackexchange.com/questions/1552/why-does-italic-%D1%82-look-like-m ).

---

* Your font version: git

**Comment by be5invis** [comment]
I already have the variant influence for `cyrl/te`. Just added `cyrl/pe` to the basket.
![image](https://user-images.githubusercontent.com/240091/88520930-1a8b9780-cfa9-11ea-807d-f9815cfe6340.png)
