### ISSUE TITLE
'Rounder' variants for 'p', 'q' and the single-storey 'a'

### ISSUE THREAD

**Issue by xy-ren** [be5invis/Iosevka#648]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [ ] Some other monospace/programming fonts supported the requested variant. Provide images below.

I did not find a monospace font with these variants, but I think they are consistent with variants `VXBM` for 'b' and `VXBP` for 'd'.

------
I am requesting for 5 'rounder' variants. 2 are for the single-storey 'a', 2 are for 'q' and 1 is for 'p'. See the image. Right ones are sketched  by hand, may not be that accurate.

![2020-07-27 19-53-56屏幕截图](https://user-images.githubusercontent.com/25559236/88539448-d8fbfa80-d043-11ea-96a9-28516a9ab89c.png)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/88607052-173cee00-d033-11ea-9957-e63050373b08.png)

**Comment by xy-ren** [comment]
Thanks, really appreciate it!

**Comment by pv4** [comment]
v-g-earless-corner is fantastic!
