### ISSUE TITLE
Unicode Powerline characters

### ISSUE THREAD

**Issue by pagerc** [be5invis/Iosevka#649]
FYSA some of the powerline symbols are getting reviewed for consideration in unicode:
https://www.unicode.org/L2/L2019/19068r2-powerline-syms.pdf
http://www.unicode.org/L2/L2019/19343-script-adhoc-recs.pdf

> Recommendations: We recommend the UTC discuss the proposal and accept the following three
> characters, with code points in the (new) Graphics for Legacy Computing block:
> U+1FBCB VERSION CONTROL BRANCH SYMBOL
> U+1FBCC COLUMN NUMBER INDICATOR
> U+1FBCD LINE NUMBER INDICATOR.

I expect the mapping so that the new unicode symbols are copied from the PUA symbols currently in the font, and eventually deprecate the PUA symbols in the future.
U+E0A0 <-> U+1FBCB
U+E0A1 <-> U+1FBCC
U+E0A3 <-> U+1FBCD

**Comment by be5invis** [comment]
These chars are not in Unicode yet, so I will not add them now.
When they are added, I will implement them.
Close as by design
