### ISSUE TITLE
About the language provided in the project documentation.

### ISSUE THREAD

**Issue by suiyuebaobao** [be5invis/Iosevka#650]
Hello, when I browse the project documentation, I notice that the name in the language list seems to have a misspelled?

Chiga or China?

![-59b57a4fa6f8216a.jpg](https://user-images.githubusercontent.com/48700331/88743239-bb7b7d80-d176-11ea-9307-89b287c7c2bd.jpg)

**Comment by CyanoHao** [comment]
https://en.wikipedia.org/wiki/Kiga_language
“Chiga” is an alternative spelling of “Kiga”.

**Comment by suiyuebaobao** [comment]
Thanks to Kop！

So do fonts support Chinese？

**Comment by be5invis** [comment]
This font is LGC only, and does not have any CJK support.
Closed.
