### ISSUE TITLE
Release file for TTC format term variant?

### ISSUE THREAD

**Issue by vext01** [be5invis/Iosevka#651]
OpenBSD packager here.

We currently package the TTF versions of the `default` and `term` variants of Iosevka. We'd like to use the TTC fonts as they are smaller, however there doesn't seem to be a release file containing the `term` variant in TTC format.

Is that right? Any plan to make such a release file?

Thanks!

**Comment by be5invis** [comment]
Well the TTC artifacts contain "normal", Term and Fixed in same package. Like, `ttc-iosevka-3.3.1.zip` already has Iosevka Term.
Closed.

**Comment by vext01** [comment]
I see.

Thank you!
