### ISSUE TITLE
Vertical bar in italic to be upright?

### ISSUE THREAD

**Issue by 12425** [be5invis/Iosevka#652]
Vertical bar character `|` in italic or oblique is also oblique, which makes the table borders ugly.
In `DejaVu Sans Mono` it is upright, can you also make it upright, or add an option?
Thanks.

<pre><i>| H1  | H2  | H3  |
| --- | --- | --- |
|     |     |     |
|     |     |     |</i></pre>

**Comment by be5invis** [comment]
Slope of symbols is more like a design choice. JetBrains Mono and Victor Mono use slanted `|` while Source Code Pro uses upright (it also force math operators, arrows, most geometric symbols and pictograms to be upright). I currently only force box-drawing characters to be upright in italics, perhaps we could have an CV for `|`.

**Comment by 12425** [comment]
Thank you! Looking forward to it.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/88870810-2fe00c00-d1cb-11ea-8676-0443907fe098.png)

**Comment by 12425** [comment]
Sorry, but I'm afraid the commit only changed **sans**, but the **slab** vertical bar is still oblique.
By the way, can we add variant for upright *`[`* and *`]`*?

**Comment by be5invis** [comment]
@12425 In the specimen you could see `VXCZ` variants for them under Slab -- note that this variant is only visible under Italics.
![image](https://user-images.githubusercontent.com/240091/91271000-5cd20100-e72e-11ea-8f58-0365618a7cff.png)
For custom building, you need to include `v-bar-force-upright` style selector *after* `slab`. I tried a custom build and it worked.

**Comment by 12425** [comment]
My bad, I previewed it in NexusFont, which shows oblique bar. After installing to the system, it shows upright. Thank you.
