### ISSUE TITLE
Uppercase J with a symmetry serif like Inconsolata

### ISSUE THREAD

**Issue by xqwyrmvpz9** [be5invis/Iosevka#654]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] Some other monospace/programming fonts supported the requested variant. Provide images below.

------

![J](https://user-images.githubusercontent.com/43498546/89102482-35905880-d43c-11ea-9eb8-b524079cb846.PNG)
THANKS

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/89112695-90658800-d41b-11ea-8d72-705efc0bdc36.png)
