### ISSUE TITLE
Cross product of b d q p variants?

### ISSUE THREAD

**Issue by paolobolzoni** [be5invis/Iosevka#655]
The basic aspect of letters **b,** **d,** **q,** and **p** is the same, just rotated or mirrored.

I like how Iosevka now allows to give subtle differences for each; but the choices appear a bit arbitrary. Since Iosevka is programmatically generated, how difficult would it be to allow each variant to appear as the other three letters properly rotated or mirrored?
Even if possible, considering the combinatorial explosion, probably it is better after #572.

I had this idea because I'd like `VXBQ` mirrored for the **b** letter.

**Comment by be5invis** [comment]
The choice is not arbitrary: rightward tail only occurs on lowercase letters that ends vertically at bottom-right, that's said, `a`, `d`, `h`, `m`, `n`, `q` and `u`. This is a design choice.
Mark as needs justification.
