### ISSUE TITLE
Wrong thickness of some special characters at bold weights

### ISSUE THREAD

**Issue by pv4** [be5invis/Iosevka#656]
On the picture attached you can see `$` sign (and other ones) is thinner than `S` letter. The picture is done at `heavy` weight but the issue is present at all weights starting with `semibold` (maybe even `medium`).

Is this behavior expected?

![Untitled](https://user-images.githubusercontent.com/2502094/89726805-5f8edf80-da27-11ea-964a-bac218ab50e9.png)

---

* Your font version: 3.3.1

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/89728137-cc7e8700-d9df-11ea-8670-cff90011531d.png)

Hmm this looked better and heavier.
