### ISSUE TITLE
Releases could be more readable

### ISSUE THREAD

**Issue by Ptival** [be5invis/Iosevka#658]
**Is your feature request related to a problem? Please describe.**
On the releases page, it's quite hard to know whether the preview of a font corresponds to the one whose link comes before or the one whose link comes after.
In fact, I almost always pick the wrong one, because my brain expects "description then preview", but it's using "preview then description".

**Describe the solution you'd like**
Adding any sort of horizontal marker, or even making the spacing slightly larger between groups, would help make this clear.

**Comment by be5invis** [comment]
Since 3.4.1 the release notes are rearranged so you have the font list at left, and preview at right.
Closed.
