### ISSUE TITLE
The minisite works incorrectly in Safari

### ISSUE THREAD

**Issue by Toufukun** [be5invis/Iosevka#659]
Before an update to the website (at the end of July), the page can show in Safari, but in the Code and Terminal section, Iosevka, Iosevka Term, Iosevka Fixed look the same.

(Sorry, I didn't leave a screenshot of the history version.)

However, after that update, the page can't load at all.

<img width="987" alt="iosevka blank page" src="https://user-images.githubusercontent.com/6957041/89737338-24e47180-da3e-11ea-9c13-7073fa471520.png">

**Comment by be5invis** [comment]
Safari doesn't have `BitInt`...

**Comment by be5invis** [comment]
Switched to `jsbi` and it works now.
Closed.

**Comment by Toufukun** [comment]
Iosevka Term and Iosevka Fixed didn't get fixed. Is it because Safari doesn't support `NWID`?

<img width="1160" alt="iosevka term" src="https://user-images.githubusercontent.com/6957041/89754305-6100ec00-daa9-11ea-93ca-47661f76ab90.png">

**Comment by be5invis** [comment]
@Toufukun Hmm Safari doesn't like vendor-specific feature tags too, which **is** a part of OT standard  (see https://docs.microsoft.com/en-us/typography/opentype/spec/featuretags, “The tag space of tags consisting of four uppercase letters (A-Z) with no punctuation, spaces, or numbers, is reserved as a vendor space.”). But this is a Safari problem, not a font problem. Chromium (which uses Harfbuzz) and Firefox (on win32 at least, which uses DWrite) worked well.
