### ISSUE TITLE
Inziu Iosevka release with all SHS weights available and matched?

### ISSUE THREAD

**Issue by Artoria2e5** [be5invis/Iosevka#66]
Although it sounds like a bit too much to ask for, I am looking forward to some Inziu Iosevka Release with all the weights available, just for the sake of simplifying my Chrome font config without having to do some FontLink hack (too lazy to do this for now; will post some Iosevka -> Inziu Iosevka SC fallback some day perhaps).

Hmm, I guess you will want to keep the sfdhanautohinted Inziu part and keep reusing it across Inziu Iosevka releases……

**Comment by be5invis** [comment]
Are you kidding me?
Generating all Inziu weights will take six hours.

**Comment by Arthur2e5** [comment]
Yeah, so that's why I am talking about reusing the hinted part… (

**Comment by be5invis** [comment]
@Arthur2e5 You cannot reuse gridfits across weights.

**Comment by Arthur2e5** [comment]
I am talking about reusing the hinted inziu from a previous version, e.g.:

1. For 1.8.1 you can rip the hinted regular and bold from 1.8.0, and hint the 4 weights left (ignore medium)
2. For 1.8.2 and so on you keep using the 1.8.1 combined results, as long as SHS itself is not upgraded…

**Comment by be5invis** [comment]
1. SHS's weight list is extralight, light, regular, medium, bold and heavy. So the "thin" variant of Iosevka has no SHS match.
2. The Kana part, oh, I have to prepare M+ too (hopefully it has enough weights either).
3. I need to adjust parameters for the other four weights, for hinting.

**Comment by Arthur2e5** [comment]
Looking into some M+ weights, more specifically "thin" and "light", it appears that the control points are mostly matched with each other.

Note that they run
```Py
f.removeOverlap()
f.round()
```
on their fonts in the build scripts, so you may want to put your hands on the raw SVGs.

**Comment by Arthur2e5** [comment]
Uh… Regarding the parameters, I am actually curious about what characters you mainly use to figure out the parameters.

I guess for the metrics part you can start with extralight and heavy, just like the makers of the glyphs do…
