### ISSUE TITLE
Comma-derived quote & backquote

### ISSUE THREAD

**Issue by efermi** [be5invis/Iosevka#660]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] Some other monospace/programming fonts supported the requested variant. Provide images below.

------

[Luculent](http://eastfarthing.com/luculent/): 
![Screenshot_20200810_095840](https://user-images.githubusercontent.com/3966555/89758305-266e7200-daf0-11ea-95e1-d5f405b2db9e.png)
[LispM](https://github.com/unjordy/LispM-Font):
![Screenshot_20200810_101931](https://user-images.githubusercontent.com/3966555/89759593-2d4ab400-daf3-11ea-9036-cc16a3b350c4.png)

**Comment by be5invis** [comment]
Do you mean to have ASCII `'` and `` ` `` look like raised comma and reverse-comma?

**Comment by efermi** [comment]
Exactly, a stylistic variant.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/89764659-acb39580-daa9-11ea-98cc-6afe73e6eab8.png)

**Comment by efermi** [comment]
Thank you!

**Comment by pv4** [comment]
I think it would be logical to also have the same comma-derived style for double quotes `"`. Is it possible?

**Comment by be5invis** [comment]
@pv4 I do not see a lot of use cases for a curly ASCII `"`. The only use cases of paired (therefore needs to become curly) `` ` `` / `'` are Lisp and TeX, and they do not influence `"`.
For typographic uses, there are already `“ ” „ ‟`.

**Comment by pv4** [comment]
@be5invis Ok, now I see. Thanks for the explanation.
