### ISSUE TITLE
I variant with slimmer slabs

### ISSUE THREAD

**Issue by JHerseth** [be5invis/Iosevka#662]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] Some other monospace/programming fonts supported the requested variant. Provide images below.

------
I guess this purely is a preference thing, but is it possible to get a capital I variant with less heavy slabs.  For comparison here is Iosevka
![iosevka-i](https://user-images.githubusercontent.com/16666145/89833287-19d63200-db61-11ea-91d5-ace293d28cc2.png)
And here is  PragmataPro
![pragmatapro-i](https://user-images.githubusercontent.com/16666145/89833293-1a6ec880-db61-11ea-8242-c2657e675ba7.png)

Unrelated, I'm looking for documentation on what `leading`, `cap` and `xheight` does, and how they work in relation to each other.  Can you point me in the right direction? Thanks!

**Comment by be5invis** [comment]
Well `leading` alters then built-in line height of the font, `cap` changes the height of capital letters as well as ascender, and `xheight` changes the height of `x` and related letters/structures.

As for `I`, it simply synchronizes with other letters' ink width. You could compare the letters like `o` and `S`, and Iosevka has a larger ink width (smaller inter-letter space). Changing `I` solely could desynchronize the letterforms. You **could** do this by customizing `metric-override` like this:

```toml
[buildPlans.iosevka-custom]
family = "Iosevka Lynn"

[buildPlans.iosevka-custom.metric-override.multiplies]
sb = 1.1 # Increase sidebearings (inter-letter space)
```
However, adding metric override may produce broken shapes so be careful when playing with these numbers.

**Comment by JHerseth** [comment]
Thank you for the swift reply. I'll play around with the metric overrides and will see what happens :+1: 

I'll close this
