### ISSUE TITLE
[ligation request] LISP-like ligation?

### ISSUE THREAD

**Issue by integral-dw** [be5invis/Iosevka#663]
The `(*` ligature from the COQX set is really nice.  Do you think a LISP-like ligation set would be a good idea? As in, ligatures for (for example) `(+`, `(-`, `(/` or `;;`, `;;;`, `;;;;`?

**Comment by be5invis** [comment]
`(*` is about centering `*`. Therefore it is not needed for `(+`, `(-` and `(/` since they are already aligned.
There are already ligations for `;;`, `;;;` and `;;;;` to squish them together a little. Not very obvious though.

**Comment by integral-dw** [comment]
> (* is about centering *
Ah, I wasn't sure if it also did something fancy with the spacing, which is primarily why I was curious. I must admit I don't have the keenest eye was just curious whether you see any potential there.  Thanks!
