### ISSUE TITLE
Combining diacritics pile up but not down

### ISSUE THREAD

**Issue by melissaboiko** [be5invis/Iosevka#664]
You can do things like ‘ã́’ but not things like ‘a̪̥’.

![grafik](https://user-images.githubusercontent.com/74593/90124754-3476f980-dd61-11ea-9dfb-4bad183510d9.png)

Diacritics like that are used for phonetics and linguistics/philology work. Here’s a working example from a SIL font:

![grafik](https://user-images.githubusercontent.com/74593/90124791-40fb5200-dd61-11ea-94a8-65d3ac7f2fa3.png)

This is on Iosevka Term SS05. Thank you for a beautiful font.

**Comment by be5invis** [comment]
I cannot reproduce this. Also mark features are correct after some data validation.
![image](https://user-images.githubusercontent.com/240091/90171482-6df63780-dd56-11ea-82fe-d465d2995b55.png)

**Comment by melissaboiko** [comment]
The above was on emacs. I tried it on libreoffice and Iosevka worked just fine.

The only question is why a font like Charis seemed to work on emacs, but Iosevka didn’t.  But if we look closely at the ‘working’ example above, we can see that the under-ring is cut off at the bottom.  That’s not an screenshot issue, it’s how it looks like on screen.

I’m thinking maybe emacs’ font rendering doesn’t deal well with diacritics piled under, and cut them off at some invisible line.  And with Iosevka’s metrics this line maybe just happens to end up right below the first diacritic, so that you don’t see the second.  With the other font the line ends up in the middle of the 2nd diacritic.  If I pile more stuff under the 2nd, I can’t see them in the other font either.

So it looks like it’s a limitation of how emacs render fonts.  Sorry for the misunderstanding!
