### ISSUE TITLE
Better shape for A75B, A75A

### ISSUE THREAD

**Issue by clsn** [be5invis/Iosevka#665]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [ ] Some other monospace/programming fonts supported the requested variant. Provide images below.

------
The U+A75B LATIN SMALL LETTER R ROTUNDA variants currently available are basically small-caps versions of R with the left stem removed.  It looks overly elongated and basically just doesn't look like an "R" nestled up against the rounded letter before it.  I know there's no nestling that can be done in monospace, but still.  Below are six examples from other fonts, NON-monospaced except for Unifont:
![image](https://user-images.githubusercontent.com/44192/90207011-2fdb3100-ddb3-11ea-9a31-e4277b0c7d19.png)

I've made some versions of the letter in my own private DejaVu Sans Mono.  Think what you will about my (dubious) skills as a typefounder, but at least perhaps this gives you some ideas of how it might look in a monospaced font:  
![image](https://user-images.githubusercontent.com/44192/90206969-10440880-ddb3-11ea-840d-25dfdd72a294.png)
One consistent feature in all these examples, at least, is the lack of horizontal stem touching the diagonal one, and I think that may be where the greatest issues with the current design are.

So, please, a decent ꝛ, and you might as well throw in an Ꝛ while you're at it.  And for bonus points, how about a setting with contextual alternate rules so that r becomes ꝛ when it follows letters that are round on the right (bopþ etc.)  That's what it's for, after all.  (I have hacked-up fonts with such rules in them and use them all the time, it's kind of cool.)

Thanks for reading!

**Comment by be5invis** [comment]
Changing into such a cursive style may not be a good idea since Iosevka' style is pretty "serious".
Though we could have some improvements...

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/90210701-880a3700-dda3-11ea-8521-3ee41f9b4738.png)

**Comment by clsn** [comment]
It's not really a cursive style per se, nor is the letter necessarily particularly cursive.  It's practically a necessary feature in Fraktur (tends to be narrow and 2-like).  I don't think my attempt looks cursive (whether or not it looks good is a completely different question).  Most of the fonts shown above are not really cursive, and some are downright geometrical  Examples from Arimo, Tinos, and Junicode:
Arimo: 
![image](https://user-images.githubusercontent.com/44192/90210655-8bf68300-ddbc-11ea-8c78-5c49d0008778.png)
Tinos:
![image](https://user-images.githubusercontent.com/44192/90210682-9f095300-ddbc-11ea-9ea9-b2227ecf1452.png)
Junicode:
![image](https://user-images.githubusercontent.com/44192/90210716-bd6f4e80-ddbc-11ea-8353-0e2871ec1d0c.png)
Not sure how "good" these are either, but they certainly comport with the stateliness of the roman text around them.
Hm, looking at the examples you posted while I was typing this.  Just shortening that center line really does make a pretty big difference, I'll admit, especially the capital.  Feels to me like the lowercase one hasn't improved quite enough (and may need the top line shortened), but I that's me, and I am certainly no expert on the art.
Aww, and I spent all that space arguing with you about the whole cursive thing, and you went and made the change anyway without listening to me whine... Thanks!  I'll leave them there anyway, since it's good to see the letter in action in other faces.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/90213806-952b2400-ddab-11ea-94df-2f7d7d83b5c5.png)
Turning the upper half into a loop may not look that bad

**Comment by clsn** [comment]
Yeah!  That's pretty good.  Thanks!!  Would be cool if it could replace R/r after round letters automatically.  Just saying. :smile:

**Comment by be5invis** [comment]
@clsn I do not think auto replacing is a good idea since Iosevka is not designed as a font to handle historical documentations.
Closed as fixed.
