### ISSUE TITLE
Weights doesnt work on visual studio 2019

### ISSUE THREAD

**Issue by chiniara** [be5invis/Iosevka#666]
My variant font weights doesnt work on visual studio 2019 but it works fine on VsCode

The font works fine on the preview but it only shows the regular weight on the editor

I only modified the  private build plans and used the docker image to build it

---

* Your font version: git
* Your font variant: My own
* Your operating system : Windows 10
* Your application using Iosevka: Visual Studio 2019

* Your `private-build-plans.toml`, if present:
```
[buildPlans.apterminal]
design = [
  "VXDD",
  "cv08",
  "VXBF",
  "cv92",
  "cv46",
  "VXAE",
  "cv96",
  "VXAC",
  "VXAO",
  "cv32",
  "cv45",
  "sp-term",
  "no-ligation",
]
family = "Iosevka Apterminal"
hintParams = ["-a", "qsq", "-W"]
italic = ["italic-styles"]
oblique = ["oblique-styles"]
upright = ["upright-styles"]

[buildPlans.apterminal.weights.regular]
css = 400
menu = 400
shape = 400

[buildPlans.apterminal.weights.medium]
css = 500
menu = 500
shape = 500

[buildPlans.apterminal.weights.semibold]
css = 600
menu = 600
shape = 600

[buildPlans.apterminal.weights.bold]
css = 700
menu = 700
shape = 700

[buildPlans.apterminal.widths.normal]

css = "normal"
menu = 8
shape = 600

[buildPlans.apterminal.slopes]
italic = "italic"
upright = "normal"

[buildPlans.apterminal.metric-override]
leading = 1400
powerlineScaleX = 1
powerlineScaleY = 1
powerlineShiftX = 0
powerlineShiftY = 0
winMetricAscenderPad = 0
winMetricDescenderPad = 0

```
* The detailed error log:
  ```
![image](https://user-images.githubusercontent.com/6012227/90326021-871b0600-df59-11ea-957f-5fc47fe2557a.png)
![image](https://user-images.githubusercontent.com/6012227/90326026-9a2dd600-df59-11ea-85c0-d2d0b99d09be.png)

  ```

**Comment by be5invis** [comment]
Looks like that VS messed up with “compatible family name” (RBIBI only and limited to 31 chars, so when it overflows Iosevka will use abbreviation) and “WWS family name” (no limit). You can try to shorten your family name to see whether it works. Though I doubt that VS may not have multiple weight/width support at all.

**Comment by be5invis** [comment]
@chiniara And, if you want "Iosevka Apterminal" has a 600 width *by default*, the config could be written like this:

```toml
[buildPlans.apterminal.widths.normal]
css = "normal"
menu = 5
shape = 600
```

You currently assigning to `menu = 8` which will generate the menu width to Extra Extended rather than "Normal".

**Comment by chiniara** [comment]
> 
> 
> Looks like that VS messed up with “compatible family name” (RBIBI only and limited to 31 chars, so when it overflows Iosevka will use abbreviation) and “WWS family name” (no limit). You can try to shorten your family name to see whether it works. Though I doubt that VS may not have multiple weight/width support at all.

Hi @be5invis ,
thank you very much for your answer and tips :)

It seems that VS was really having problems with the font name, i renamed it to IoApt and set `menu=5` and now its working perfectly.
