### ISSUE TITLE
New 'a' 'm' 'n' 'r' 't' variants

### ISSUE THREAD

**Issue by Zhern** [be5invis/Iosevka#669]
I like the new VXBO-like variants of the 'b' 'd' 'g' 'p' 'q' chars (kind of "soft" corners, not round, but without the tail), and I think it could be extended to the 'a' 'm' 'n' and 'r' chars.
Out of this scope but still an idea, I think a right-side-only-straight-'t' char could be nice.

What do you think?

![image](https://user-images.githubusercontent.com/2686102/90380074-e5d8a080-e07b-11ea-84ff-809b188c2d16.png)

**Comment by throwaway571** [comment]
A right-side only curved t like in the main Ubuntu font (not Ubuntu Mono) would also make sense.

**Comment by be5invis** [comment]
The earless variants of `b` `d` `g` `p` `q` are about circle-bar joining, and it also applies single-storey `a`. For `m`, `n` and `r`, extending it to arch-bar joining might be considered stylistic set change.
For `t`, I do not see such shape occured in non-decorative fonts.
Could you please find more programming fonts that has the shapes you requested to further justify this request?

**Comment by Zhern** [comment]
I never saw these variants in other fonts (`a` `m` `n` `r` and `t`) and could not find any, all this could be technically considered as decorative. It is an idea to have something homogeneous with the earless (`a` `m` `n` `r`) and straight (`t`) variants.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/90716622-4295b000-e262-11ea-8174-eb7cfd9cc9b1.png)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/90718397-b1750800-e266-11ea-872d-a857f4ae0921.png)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/90743584-9b764000-e284-11ea-9181-83fd545dc795.png)

**Comment by be5invis** [comment]
I am confused what is the `m` you are expecting — is it something like [Monotype's Biome](https://www.fonts.com/font/monotype/biome), or a simple `m` with the ear removed?

**Comment by Zhern** [comment]
I am more expecting a MonotypeBiome-like variant.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/90842241-a62be600-e313-11ea-8d62-faff3e6c6595.png)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/90851265-04af8f00-e329-11ea-85ce-c83575999e14.png)
