### ISSUE TITLE
Slashes appear as asterisks.

### ISSUE THREAD

**Issue by ke7ofi** [be5invis/Iosevka#67]
Here's a sample: ![2016-02-24-094052_237x29_scrot](https://cloud.githubusercontent.com/assets/5540140/13294851/cbf41cea-dada-11e5-86c7-feca9915bd28.png)

**Comment by ke7ofi** [comment]
Actually, this appears to be only in the Firefox URL bar. Everywhere else that I've seen has been fine. Does that imply that it's Firefox's fault? I didn't have this problem with other fonts, though.

**Comment by alexeyten** [comment]
Have you restarted firefox and cleared fonts cache?

**Comment by ke7ofi** [comment]
That fixed it; sorry for creating a PEBKAC issue.
