### ISSUE TITLE
VXDK missing?

### ISSUE THREAD

**Issue by AlsoScratch** [be5invis/Iosevka#670]
Did I not check carefully, or is the tag `VXDK` missing?

**Comment by be5invis** [comment]
@AlsoScratch Ah it is missing, but doesn't matter. May be used by other variants later.

**Comment by be5invis** [comment]
Just added it to be an asymmetric serifed `i` like this:
![image](https://user-images.githubusercontent.com/240091/90488544-ed865c80-e0f0-11ea-87ae-9050b70487a6.png)
