### ISSUE TITLE
Short top `t` and x-height aligned `f`

### ISSUE THREAD

**Issue by efermi** [be5invis/Iosevka#672]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] Some other monospace/programming fonts supported the requested variant. Provide images below.

------

*Please provide your your justification here.*

In font design it is common (although not universal) to see crossbars in `f` and `t` aligned to x-height and for `t` to have its top somewhat short of cap height. Would you care to create the modifications of the VXDD and the VXDC variants of the letters in such design? I'm not sure if this should applied to all variants and for me personally these two would be enough.
This is how it looks now compared to DejaVu Sans Mono (bottom):
![Screenshot_20200820_230540](https://user-images.githubusercontent.com/3966555/90826599-67ae1f80-e343-11ea-996e-24c36044a834.png)
And here is what the result may look like:
![Screenshot_20200820_234927](https://user-images.githubusercontent.com/3966555/90826641-7dbbe000-e343-11ea-979e-1b1daf3688ab.png)

**Comment by be5invis** [comment]
Moving the crossbar of `f` may cause a lot of balancing issue, but adding a shorter neck variant of `t` seems feasible
![image](https://user-images.githubusercontent.com/240091/90849875-2a3a9980-e325-11ea-8a9a-6fd8444bf769.png)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/90849940-535b2a00-e325-11ea-9f77-ea3d18e0a24c.png)
