### ISSUE TITLE
Wrong output…

### ISSUE THREAD

**Issue by w1hm1** [be5invis/Iosevka#675]
I tried to create a variation of the font by using a configuration like this:

`design = ["VXDD", "cv24", "cv05", "VXDF", "cv08", "VXDC", "cv90", "VXCH", "VXBY", "VXCJ", "VXCA", "cv93", "VXAU", "VXAE", "cv65", "cv96", "VXBV", "cv99", "cv23", "VXAO", "cv32", "cv38", "cv62", "VXCZ", "cv67",]  
`

Doesn't work. Sorry. Maybe I'm stupid and ignorant but please, explain what's wrong here....

**Comment by paolobolzoni** [comment]
I have the same problem.

Here is the private build file:
```
# parameters.toml

[buildPlans.iosevka-dyslexia]
family = "Iosevka dyslexia"

design = [ "sp-fixed", "VXBK", "VXBQ", "VABA", "VXCV", "VXDM", "VXEG", "cv24",
"VXCC", "cv05", "cv98", "cv69", "cv27", "cv26", "VXCG", "cv87", "cv40", "cv89",
"cv71", "cv76", "cv78", "cv49", "VXBD", "cv74", "VXAQ", "VXBH", "cv91", "VXDB",
"VXCI", "cv42", "cv83", "cv80", "cv94", "cv51", "cv46", "VXAT", "VXBB", "cv65",
"cv96", "VXAC", "cv95", "cv17", "VXBW", "cv20", "cv23", "cv30", "VXAO", "cv37",
"VXBJ", "VXAI", "cv33", "cv54", "cv62", "VXCZ", "cv66" ]


italic = [ "italic-only", "VXBI" ]


hintParams = ["-a", "sss"]

[buildPlans.iosevka-dyslexia.weights.light]
shape = 300
menu  = 300
css   = 300

[buildPlans.iosevka-dyslexia.weights.regular]
shape = 500
menu  = 400
css   = 400

[buildPlans.iosevka-dyslexia.weights.bold]
shape = 700
menu  = 700
css   = 700


[buildPlans.iosevka-dyslexia.slants]
upright = "normal"
italic = "italic"
```

Here is the result:
![pngout](https://user-images.githubusercontent.com/1133562/91784910-00477800-ec3f-11ea-8756-4fb9f2756430.png)

As you can see, among others, ```VXCG``` had no effect: the n has no bended leg.

**Comment by be5invis** [comment]
@paolobolzoni I tried your config in latest `dev` and it worked as expected.
![image](https://user-images.githubusercontent.com/240091/91789944-87a3d580-ebc4-11ea-9162-d7cfaf20ead5.png)

**Comment by paolobolzoni** [comment]
What can I say... I am confused as you are, I used a totally new environment based on

```git clone -b dev --depth=1 'https://github.com/be5invis/Iosevka.git'```

I try again.

**Comment by be5invis** [comment]
@paolobolzoni Your version number looks outdated (3.3.1 vs. 3.4.6), so that may be the reason.

**Comment by paolobolzoni** [comment]
Yes, false alarm. It seems Docker is cleverer than I thought to avoid to recompute images.
