### ISSUE TITLE
Size of bullets

### ISSUE THREAD

**Issue by skalyan91** [be5invis/Iosevka#678]
Please consider increasing the sizes of `U+2022 • BULLET` and `U+2023 ‣ TRIANGULAR BULLET`. I use both of these in Emacs Org mode, and they’re nearly impossible to distinguish.

**Comment by be5invis** [comment]
It will now be much more clear. Closing.

![image](https://user-images.githubusercontent.com/240091/91242986-a8b88200-e6fd-11ea-8dbe-770666d65da6.png)

**Comment by skalyan91** [comment]
Thanks; it is.
