### ISSUE TITLE
Registered sign at superscript position

### ISSUE THREAD

**Issue by stone-zeng** [be5invis/Iosevka#679]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] Some other monospace/programming fonts supported the requested variant. Provide images below.

------

In a lot of fonts U+00AE REGISTERED SIGN `®` is designed in the superscript position, and is aligned of U+2122 TRADE MARK SIGN `™`. So please consider to add this variant.

![image](https://user-images.githubusercontent.com/18233088/91298443-9fe5b000-e7d2-11ea-951c-1471d9dd91d5.png)

![image](https://user-images.githubusercontent.com/18233088/91298437-9c522900-e7d2-11ea-932e-8b4933b18915.png)

![image](https://user-images.githubusercontent.com/18233088/91298405-91979400-e7d2-11ea-8bff-c47e80e0fe0e.png)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/91381132-6cf3ea00-e7db-11ea-9a16-12858b105a68.png)
