### ISSUE TITLE
Support ligature for Rule-Delayed as `:>`

### ISSUE THREAD

**Issue by kenkangxgwe** [be5invis/Iosevka#680]
Can we add ligature support for U+29F4 (`⧴`) for `:>` if not exists. Thanks

**Comment by be5invis** [comment]
There's centering to align `:` and `>` together, but I do not think combining `:>` into `⧴` is a good idea.

**Comment by kenkangxgwe** [comment]
This symbol comes from Mathematica's [`RuleDelayed`](https://reference.wolfram.com/language/ref/RuleDelayed.html) function which is also written as `:>`. It might be counterintuitive to transform `:>` instead of `:->`, but if this symbol is dedicated to be used in Mathematica (correct me if I am wrong), I guess it is promising to do so.  Btw, I propose to add a new tag, `WolframLanguage` to have ligatures like `[[` for `〚`

**Comment by be5invis** [comment]
Wait, aren't Mathematica automatically replacing the ASCII symbols to the non-ASCII one?

**Comment by kenkangxgwe** [comment]
Well, programming languages are orthogonal to frontends. We write Mathematica in IDE/editors as well.

**Comment by kenkangxgwe** [comment]
Any update? Thanks

**Comment by be5invis** [comment]
This needs to introduce a new ligation set, `colon-greater-as-colon-arrow` and a new tag `WFLM` enabling it.
Also, does Mathematica have `<:` and `<:>`?

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/92197242-0d728b80-ee26-11ea-9c9d-3c4b3702b060.png)

**Comment by stone-zeng** [comment]
Hope that there can be a feature tag for wolfram language (e.g. `WOLF`).

**Comment by be5invis** [comment]
@stone-zeng It's under `WFLM`.

**Comment by kenkangxgwe** [comment]
For the eqs and ineqs, I would like to have `!=` `==` `===` and `=!=` to be included in ligatures. Thus `!==` will be interpreted as `≠=`. Also pls consider add `[[` for `〚` and its mirror character. Thanks

**Comment by stone-zeng** [comment]
A (not complete) survey:

![image](https://user-images.githubusercontent.com/18233088/92203736-7accfd80-eeb4-11ea-8c4d-7adcac96ad1c.png)

**Comment by kenkangxgwe** [comment]
> Also, does Mathematica have <: and <:>?

No, it doesn't

@stone-zeng , no ligatures part seems ambiguous, better to remove that part so we can convince @be5invis to add more :-)

**Comment by be5invis** [comment]
@stone-zeng This are the symbols so far:

![image](https://user-images.githubusercontent.com/240091/92204124-a231b500-ee37-11ea-97fa-162994ad98fb.png)

**Comment by stone-zeng** [comment]
> Also pls consider add `[[` for `〚` and its mirror character. Th

`[[`/`]]` ligatures can be misleading when nested with `[`/`]` or even nested `[]` such as `f[g[x]]`. Is it possible to make correct ligatures according to bracket matching?

**Comment by be5invis** [comment]
@stone-zeng No. OT cannot do that.

**Comment by stone-zeng** [comment]
And I think it's better to use double lines for `===` and `!==`, as there is a congruent symbol `≡` is wolfram lang.

**Comment by kenkangxgwe** [comment]
> > Also pls consider add `[[` for `〚` and its mirror character. Th
> 
> `[[`/`]]` ligatures can be misleading when nested with `[`/`]` or even nested `[]` such as `f[g[x]]`. Is it possible to make correct ligatures according to bracket matching?

That sounds sad :(, I recall seeing this when I used Fira code.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/92204974-8c24f400-ee39-11ea-9704-4f8b73c51ae9.png)

**Comment by kenkangxgwe** [comment]
Is `^^` also good to be ligatured?

**Comment by be5invis** [comment]
`^^` doesn't look like to be an operator in any languages I know.
Closing as resolved.

**Comment by kenkangxgwe** [comment]
![image](https://user-images.githubusercontent.com/8650023/92211021-9f898c80-ee44-11ea-873b-237adcb7a9c0.png)
Just FYI, it means `BaseForm` in Wolfram Language though
