### ISSUE TITLE
Ligatures not showing up in quasi-proportional families

### ISSUE THREAD

**Issue by VulumeCode** [be5invis/Iosevka#682]
For the quasi-proportional families, the ligatures don't show up in my IDEs (Rider, VSCode, so very different ones)
They do show up for the monospace versions.

---

* Your font version: Release 3.4.6
* Your font variant: all quasi-proportional families
* Your operating system (name and version): Windows 10
* Your application using Iosevka: Rider, VSCode

**Comment by be5invis** [comment]
This is by design: ligations are turned off **on purpose** for quasi-proportionals.

**Comment by VulumeCode** [comment]
Oh, okay. I can appreciate that. However, on the releases page it says "ligatures: yes" for these fonts. https://github.com/be5invis/Iosevka/releases

I will try and see if I can compile my own version with ligatures for my IDE. I've been using Go Regular for years now but it doesn't have ligatures so Iosevka got me excited.

**Comment by be5invis** [comment]
The release pages' data is a typo. Just fixed that in 3.4.7 (which fixes another severe broken shapes).
