### ISSUE TITLE
Want to pin "n", "m", "p", and "u"'s design as an option from slab italic to sans italic like "r"

### ISSUE THREAD

**Issue by zero00072** [be5invis/Iosevka#684]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] Some other monospace/programming fonts supported the requested variant. Provide images below.

------

As the following custom image, I want to pin _`n`_, _`m`_, _`p`_, and _`u`_'s design as an option like _`r`_. Although I can custom it.

![iosevka](https://user-images.githubusercontent.com/2072036/92207011-1497a900-eebb-11ea-8ed7-4119972e5041.png)

**Comment by be5invis** [comment]
Introducing — Motion Serifs
![image](https://user-images.githubusercontent.com/240091/92221531-7c65d980-ee52-11ea-9cff-35640341da1e.png)

**Comment by pv4** [comment]
@be5invis
Should `slab` variant of `v-p-motion-serifed` have bottom serifs? This isn't an issue with `r` since it has separate `v-r-serifed`.

**Comment by be5invis** [comment]
@pv4 Motion-serifed variants will keep their shape as-is in Slab, just like `v-r-top-serifed`. They will actually "lose" some serifs.
