### ISSUE TITLE
U+279C heavy arrow displays as a box

### ISSUE THREAD

**Issue by step-** [be5invis/Iosevka#685]
'➜' U+279C Dec:10140 HEAVY ROUND-TIPPED RIGHTWARDS ARROW displays as a box for the Italics style. The Regular style displays correctly

Terminal font configuration `~/Xresources`
```
URxvt.font: xft:Iosevka Term SS09:style=Regular:size=13:antialias=true:hinting=slight
URxvt.boldFont: xft:Iosevka Term SS09:style=Bold:size=13:antialias=true:hinting=slight
URxvt.italicFont: xft:Iosevka Term SS09:style=Italic:size=13:antialias=true:hinting=slight
URxvt.boldItalicFont: xft:Iosevka Term SS09:style=Bold Italic:size=13:antialias=true:hinting=slight
```

See the screenshot for the text that follows.  A similar issue occurs for most heavy arrows in Italics style but I'm asking to fix just U+279C because it's the only one I use regularly.  Thank you.

P.S. I didn't check Bold Italics, it could be the same.

![iosevka-20200905](https://user-images.githubusercontent.com/1414102/92299973-5bd37780-ef57-11ea-86f3-c9396ef6274f.png)

```
  ➜
# ➜
  ➙ ➚ ➘ ➔ ➜ ➽ ➷ ➸ ➹ ➞ ➻ ➨ ➠ ➦ ➥
# ➙ ➚ ➘ ➔ ➜ ➽ ➷ ➸ ➹ ➞ ➻ ➨ ➠ ➦ ➥
```
---

* Your font version: (Release or git, version) 3.4.3
* Your font variant: Term SS09
* Your operating system (name and version): Linux Fatdog64 810
* Your application using Iosevka: urxvt

**Comment by be5invis** [comment]
Iosevka doesn't have support of U+279C, and the arrow you see in Regular is from fallback fonts.
You could check the character set in https://typeof.net/Iosevka/specimen.

**Comment by be5invis** [comment]
Closing as external. If you want to request character support of such dingbats, please file another issue and provide use case.

**Comment by step-** [comment]
Oops. Thank you.
