### ISSUE TITLE
Serifed flat hook lowercase f

### ISSUE THREAD

**Issue by xqwyrmvpz9** [be5invis/Iosevka#686]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [ ] Some other monospace/programming fonts supported the requested variant. Provide images below.

------

![f](https://user-images.githubusercontent.com/43498546/92322065-a50fee00-f061-11ea-8bbe-0dcdb7aea54f.png)
`f` with flat hook and bottom serif.
`f` with flat hook, bottom serif and crossbar placed right at X-height.

_THANKS_

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/92323410-5aed2500-efed-11ea-98d9-8fe4de11b591.png)
