### ISSUE TITLE
Update 'Building from Source' description steps

### ISSUE THREAD

**Issue by GregoryHorvath** [be5invis/Iosevka#688]
**Is your feature request related to a problem? Please describe.**
Was stuck a little bit with building my own variant based on the short description. It was only a little frustration, mostly with `otf2otc` because not even Google gives me sane results to get that from anywhere, I only found the `pip` solution on a random blog.

**Describe the solution you'd like**
Update the description with steps like:
- Copy the `ttfautohint` and `otfcc` files to the project's root folder
- You will also need `otf2otc` which can be installed via `pip3 install afdko`

**Comment by be5invis** [comment]
`otf2otc` is only used when building TTCs and is only used in my release pipeline. For TTF build it is not needed.

**Comment by be5invis** [comment]
Added link to otf2otc.
And putting deps inside project repo is not a good idea, providing links should be enough.
Close as resolved.
