### ISSUE TITLE
"All variants" release file

### ISSUE THREAD

**Issue by jeeger** [be5invis/Iosevka#691]
**Is your feature request related to a problem? Please describe.**

I'm packaging Iosevka for Gentoo linux ([bug here](https://github.com/gentoo/gentoo/pull/17409)), and I'd like to include all Iosevka variants in the package.
Currently, this requires either building all variants ourself, or downloading a long list of files.

**Describe the solution you'd like**
A single zip file that contains all variants (optionally just the TTF version) available on the release page.

**Describe alternatives you've considered**
Building the font on installing would pull in a dependency on `node.js` for every user of the package, which is undesirable.

**Additional context**

**Comment by be5invis** [comment]
I do not think downloading a large file works better than downloading a list of files.
Add to V4 timeframe.

**Comment by jeeger** [comment]
Hello! Thanks for the feedback!

I don't agree, however: The code at https://github.com/gentoo/gentoo/pull/17409/commits/f25060a91f18df09149bc8a5da4f3a916cee27db#diff-dc2915eb0f03288f8a4c5aadaf6986efR14 was "generated" by me by using wget and AWK, and that isn't even all of the variants.

If there's a quicker way to get a list of all variant zip files, that would solve the problem as well. Is such a thing available?

**Comment by be5invis** [comment]
@jeeger GitHub should have API to list artifacts of a release — then you could filter out the subset you need.

**Comment by chelovechishko** [comment]
`curl -i https://api.github.com/repos/be5invis/Iosevka/releases/tags/v3.6.3 > /tmp/gh_get_rest.txt`
`sed -r '$!N;$D; {/ttc|pkg/d}' /tmp/gh_get_rest.txt | ag '"name": "ttf|size|browser_download_url' | sed '$!N; /size.*size/!P; D' | sed '1d' | less`
```json
        "name": "ttf-iosevka-3.6.3.zip",
        "size": 80405423,
        "browser_download_url": "https://github.com/be5invis/Iosevka/releases/download/v3.6.3/ttf-iosevka-3.6.3.zip"
        "name": "ttf-iosevka-aile-3.6.3.zip",
        "size": 29583682,
        "browser_download_url": "https://github.com/be5invis/Iosevka/releases/download/v3.6.3/ttf-iosevka-aile-3.6.3.zip"
```

**Comment by re-xyr** [comment]
If you include all combinations of the character variants, that would be *a lot*.

**Comment by be5invis** [comment]
I'd like to re-mark this as Needs Justification. Iosevka's "all variant package" is about 7.3GB, and as @chelovechishko demonstrated, you can already get the list of artifacts and collect them using a script.
