### ISSUE TITLE
According to #684, hope cyrillic can be consistent

### ISSUE THREAD

**Issue by zero00072** [be5invis/Iosevka#692]
**Is your feature request related to a problem? Please describe.**
According to #684, we have several "Motion Serifed variants". Hope these be consistent to cyrillic.

My `private-build-plans.toml`:
```ini
[buildPlans.iozero]
family = 'IoZero'
design = ['no-cv-ss', 'cv92', 'VXDB', 'VXCJ', 'VXBL', 'VXBQ', 'VXDE', 'cv08',
          'VXEJ', 'VXCH', 'VXBF', 'VXBE', 'VXAC', 'cv51', 'cv46',
          'VXAF', 'cv65', 'cv97', 'cv21', 'cv23', 'cv30', 'cv45', 'cv62']
upright = ['VXBU', 'VXEG', 'cv11', 'VXBT', 'VXAH']
italic = ['VXBS', 'VXEL', 'VXEO', 'VXER', 'VXES', 'cv87', 'cv40', 'VXEU', 'VXAJ']
oblique = ['VXBU', 'VXEG', 'cv11', 'VXBT', 'VXAH']
```

![report](https://user-images.githubusercontent.com/2072036/94660509-53911100-0338-11eb-8373-16892ab8fcb2.png)

**Comment by be5invis** [comment]
Fixed cases for `п`, `џ` and `ш`.

For `ч`, I am thinking whether drive the motion serif mechanism with variants is the correct method. Perhaps we should have a "slab level" that controls all the serif behavior for (major - not `i` or `l`-like) lowercase letters: level 1 for partial slab, and level 2 for full slab.

**Comment by zero00072** [comment]
Excellent work! It's a nice idea to separate it to a new style if necessary.

Do what you want. It's always the best programming font.

**Comment by be5invis** [comment]
Closing in favor of #693.
