### ISSUE TITLE
CSS?

### ISSUE THREAD

**Issue by ShalokShalom** [be5invis/Iosevka#694]
The website promotes CSS to configure the fonts. 
Where do I apply this? I see no tool, input field or any documentation anywhere for it. 
I configured it [this way ](https://gist.github.com/ShalokShalom/032b7f3c5027e35cdc3ae169340b990f)and guess this is correct.

**Comment by be5invis** [comment]
Yes this is correct. Adding `font-feature-settings` will work.
Closing.

**Comment by ShalokShalom** [comment]
Adding to where?

**Comment by be5invis** [comment]
To use in websites, you can add the `font-feature-settings: ...` key-value pair to the selectors you'd like to influence.
For editors like VSCode that supports custom font features, you may need to refer their documents.

**Comment by ShalokShalom** [comment]
Aha, ok I see. Thanks
(You might add that _somewhere_ on your website.

**Comment by jozsefk9** [comment]
I can't figure out this too. Before I was not able to build custom fonts from source, now I can't apply CSS features. :) So another 5 to 10 years and there we are.
