### ISSUE TITLE
Egyptological alef, ayin, and yod

### ISSUE THREAD

**Issue by ucctheblend** [be5invis/Iosevka#695]
- The requested character is...
  - [x] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [ ] Symbol
- [ ] Some other monospace/programming fonts supported this character. Provide images below.

------

The Egyptological alef, ayin, and yod are required for [transliterating Ancient Egyptian](https://en.wikipedia.org/wiki/Transliteration_of_Ancient_Egyptian).

Designation | Lowercase | Capital
-- | -- | --
alef | ꜣ<br>U+A723 | Ꜣ<br>U+A722
ayin | ꜥ<br>U+A725 | Ꜥ<br>U+A724
yod | ꞽ<br>U+A7BD | Ꞽ<br>U+A7BC

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/94985870-e4b9e080-050e-11eb-9863-e560d12eb50f.png)
