### ISSUE TITLE
U+FFFD "REPLACEMENT CHARACTER" �

### ISSUE THREAD

**Issue by solson** [be5invis/Iosevka#698]
- The requested character is...
  - [ ] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [x] Symbol
- [x] Some other monospace/programming fonts supported this character. Provide images below.

------

I was dumping some data in a string while programming and noticed this rendering issue in my terminal, where I am using Iosevka:

![image](https://user-images.githubusercontent.com/26806/95121465-fb4a7c80-0746-11eb-83ea-76dcf208f2cd.png)

I figured out the issue is that the [`U+FFFD �` character](https://www.fileformat.info/info/unicode/char/fffd/index.htm) was being rendered in Noto Sans Mono (my system monospace fallback) because Iosevka doesn't support the character, as far as I can tell. If my method of checking was correct, I think over half of my monospace fonts support this character, so it would be great if Iosevka did as well.

**Comment by be5invis** [comment]
> I think over half of my monospace fonts support this character.

Really? I checked Fira Code and Source Code Pro and this character is not included. Usually, `U+FFFD` is used to represent conversion error, so I do not think most monospace fonts will cover it.

Mark as Needs Justification.

**Comment by solson** [comment]
> Usually, U+FFFD is used to represent conversion error

This is correct — and that's precisely the reason it came up when I was debugging code that does unicode conversions.

It's included in these fonts, for example:

![image](https://user-images.githubusercontent.com/26806/95146139-ff8d8e80-0774-11eb-93aa-7ffa7164062d.png)

**Comment by be5invis** [comment]
Considering the narrow-ness of Iosevka it may look like a hexagon.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/96359067-20ce7300-10c3-11eb-906c-99c0d1530229.png)
Closing as added.
