### ISSUE TITLE
Make em dash and horizontal arrows of the same height

### ISSUE THREAD

**Issue by re-xyr** [be5invis/Iosevka#699]
**Is your feature request related to a problem? Please describe.**
Currently, the height of em dash (and probably other dashes) is slightly higher than that of the horizontal arrows.

**Describe the solution you'd like**
Make them of the same height.

**Describe alternatives you've considered**
None.

**Additional context**
![image](https://user-images.githubusercontent.com/69201983/95202920-92313a80-0814-11eb-9076-b75a2bf864f9.png)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/95273556-3f498a00-07f8-11eb-95ca-cb5990f807d9.png)
They are supposed to be, but TTFAutohint does not know anything about symmetry, and may make them misaligned. Using the unhinted version _may_ fix this.
