### ISSUE TITLE
patel-c not found

### ISSUE THREAD

**Issue by bohoomil** [be5invis/Iosevka#7]
Hi,

When I run `sudo npm install patel-c -g`, all I get back is:

```
npm ERR! 404 Not Found
```

What am I supposed to do with it? :-)

Thank you for your assistance (and a great font).

**Comment by be5invis** [comment]
Oh, i am sorry, the library name is `patel`.
Readme updated.

**Comment by bohoomil** [comment]
Thank you very much!

However, there still is a little problem: when I try to build the fonts, I get the following error:

```
patel-c support/glyph.patel -o support/glyph.js --strict
: No such file or directory
makefile:45: recipe for target 'support/glyph.js' failed
make: *** [support/glyph.js] Error 127
```

As far as I can tell, none of the required `js` scripts (`glyph.js`, `stroke.js` and `parameters.js`) can be found in the repo (all the corresponding `*.patel` files do exist, though). Would you mind looking into it, please?

**Comment by be5invis** [comment]
`support/glyph.js` is compiled from `support/glyph.patel` using patel-c.

If you are using Windows you can replace your `make.exe` with [this](http://www.equation.com/servlet/equation.cmd?fa=make).

**Comment by bohoomil** [comment]
Thanks for clarification -- I'm using Linux. If the `js` script is meant to be "retrieved" from `glyph.patel`, then it simply doesn't happen (I installed all required Node dependencies)… Any ideas?

**Comment by be5invis** [comment]
Can you run `patel-c` from your shell directly?

**Comment by bohoomil** [comment]
Yep: the file is executable and in the path.

**Comment by be5invis** [comment]
What happens if you run `patel-c support/glyph.patel -o support/glyph.js --strict` manually?

**Comment by bohoomil** [comment]
I get

```
: No such file or directory
```

**Comment by be5invis** [comment]
Paste your `pwd` result and the complete error report.

**Comment by bohoomil** [comment]
I run make inside the copy of the repo, which is `/home/bohoomil/Iosevka.build`. The complete error report is exactly what I posted [above](https://github.com/be5invis/Iosevka/issues/7#issuecomment-128171053). The same happens when I issue the `patel-c glyph.patel -o glyph.js --strict` inside `support`.

**Comment by be5invis** [comment]
So what happens if you run `patel-c` alone? Can you see the same error report? It looks like something wrong happens when `npm` tries to create an executable file for `patel-c`.

**Comment by bohoomil** [comment]
`patel-c` run alone returns `: No such file or directory`. Yes, with or without `glyph.patel` the error is exactly the same.

**Comment by be5invis** [comment]
Hmmm I updated `patel` to ver 0.18.5. Does this version work?

**Comment by bohoomil** [comment]
Yes! Thank you so much! The family is here and looks great! :-)
