### ISSUE TITLE
slab 版本 和 非 slab 有何不同

### ISSUE THREAD

**Issue by catcat520** [be5invis/Iosevka#70]
slab 版本 和 非 slab 有何不同

当然还有一大堆 其他的版本，能不能整合一下呢，或者给个说明。。。

iosevka-1.8.0.7z
2.05 MB
iosevka-1.8.0.zip
959 KB
iosevka-slab-1.8.0.7z
2.19 MB
iosevka-slab-1.8.0.zip
869 KB
variant-hooky-iosevka-1.8.0.7z
2.05 MB
variant-hooky-iosevka-1.8.0.zip
868 KB
variant-zshaped-iosevka-1.8.0.7z
2.05 MB
variant-zshaped-iosevka-1.8.0.zip
944 KB
withfw-cc-iosevka-1.8.0.7z
2.21 MB
withfw-cc-iosevka-1.8.0.zip
1.02 MB
withfw-cc-iosevka-slab-1.8.0.7z
2.35 MB
withfw-cc-iosevka-slab-1.8.0.zip
936 KB
withfw-iosevka-1.8.0.7z
2.19 MB
withfw-iosevka-1.8.0.zip
1.01 MB
withfw-iosevka-slab-1.8.0.7z
2.33 MB
withfw-iosevka-slab-1.8.0.zip
Source code (zip)
Source code (tar.gz)

**Comment by be5invis** [comment]
See this:
![](https://raw.githubusercontent.com/be5invis/Iosevka/master/images/preview-all.png)

You can directly compare the preview areas marked as "Iosevka" and "Iosevka Slab". Iosevka Slab has serifs.
