### ISSUE TITLE
Upright cursive lowercase k, like Imprima

### ISSUE THREAD

**Issue by xqwyrmvpz9** [be5invis/Iosevka#700]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [ ] Some other monospace/programming fonts supported the requested variant. Provide images below.

------

![imprima-k](https://user-images.githubusercontent.com/43498546/95455346-4f03d280-09a0-11eb-9ae1-868300d1f8e8.png)
THANKS

**Comment by pv4** [comment]
With a curly leg this would be a nice alternative to `v-k-cursive` for `curly` variant. I mean, this variant would be a better alternative for `v-k-cursive` in `v-k-curly-cursive`.

**Comment by clsn** [comment]
Similar shape is also found in [Fantasque Sans Mono](https://github.com/belluzj/fantasque-sans), for whatever that is worth.

**Comment by be5invis** [comment]
I call it "upright" instead of "roman" 🙂.
Adding to backlog.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/96358765-d7c8ef80-10bf-11eb-93ff-b9daefd3a74d.png)
Close as fixed
