### ISSUE TITLE
Urdu Support

### ISSUE THREAD

**Issue by ZAKhan** [be5invis/Iosevka#702]
Can you please add support for urdu character set.

Regards

**Comment by be5invis** [comment]
Duplicate of #320, since Urdu use Arabic script.
Note: Iosevka won't support Nastaʼlīq since the style is too different.

**Comment by simurgh9** [comment]
> Iosevka won't support Nastaʼlīq since the style is too different.

I think a better way to say this is that, nastalique by definition is variable pitch (both in x-axis and y-axis). A good arabic glyph set here should still be considered though.
