### ISSUE TITLE
Line-height is broken

### ISSUE THREAD

**Issue by Matt-Gleich** [be5invis/Iosevka#704]
Describe your problem here. Provide pictures and files if necessary.

Hello! So I am having a problem with the line-height for my editor, Visual Studio Code. As seen below it the line-height is very large and isn't centered.

<img width="473" alt="Screen Shot 2020-10-24 at 10 14 50 PM" src="https://user-images.githubusercontent.com/43759105/97097492-6bae3480-1647-11eb-97d2-a10ccd019100.png">

It is also broken in Font Book (the macOS font explorer):

Iosevka font: 

<img width="999" alt="Screen Shot 2020-10-24 at 10 23 17 PM" src="https://user-images.githubusercontent.com/43759105/97097502-84b6e580-1647-11eb-983a-0c4f7f97aac6.png">

Normal font: 

<img width="999" alt="Screen Shot 2020-10-24 at 10 23 36 PM" src="https://user-images.githubusercontent.com/43759105/97097506-900a1100-1647-11eb-93e2-28d74e3d7e9a.png">

Everything was working fine until I upgraded to v3.7.0 via homebrew cask. It works fine in iTerm2 but seems to be broken for everything else. This is happening for all versions of Iosevka. Thanks for making this font by the way :)

---

* Your font version: 3.7.0
* Your font variant: Extralight
* Your operating system (name and version): macOS Catalina 10.15.7
* Your application using Iosevka: Visual Studio Code & Font Book

**Comment by Matt-Gleich** [comment]
I downgraded to v3.6.0 and it is fixed.

**Comment by singularitti** [comment]
Same problem here!

**Comment by Matt-Gleich** [comment]
A temporary fix is to run the following:
```bash
brew cask uninstall font-iosevka
```
and
```bash
brew cask install https://raw.githubusercontent.com/Homebrew/homebrew-cask/fonts/cac2f2b4bfb3d3dc06b69f6b4873761629d54a4a/Casks/font-iosevka.rb
```

**Comment by be5invis** [comment]
[iosevka-ttf-20201024-a.zip](https://github.com/be5invis/Iosevka/files/5434114/iosevka-ttf-20201024-a.zip)
@Matt-Gleich @singularitti Did this build fixed the issue?

**Comment by Matt-Gleich** [comment]
Looks like it. The homebrew cask just needs to be updated

**Comment by Matt-Gleich** [comment]
I can look into that now.

**Comment by singularitti** [comment]
Yeah it works for me. Thanks!

**Comment by michaelperrygoodman** [comment]
This is broken for me, but only when using Termina or iTerm2. It looks correct when using VSCode

**Comment by Matt-Gleich** [comment]
@michaelperrygoodman does the updated font that was posted also not work?

**Comment by michaelperrygoodman** [comment]
@Matt-Gleich It doesn't seem to work unless there's some kind of system font caching. Here's a screenshot of the ttf in that zip:
<img width="715" alt="Screen Shot 2020-10-24 at 11 05 12 PM" src="https://user-images.githubusercontent.com/1195409/97098665-84214d80-164d-11eb-8bb6-581720548b8c.png">

**Comment by be5invis** [comment]
@michaelperrygoodman I think you should fully uninstall existing Iosevka and reinstall the fonts I posted, to avoid any caching issues.

**Comment by michaelperrygoodman** [comment]
@be5invis Yeah, I have deleted them from the font folder and installed the update from the zip a few times. Going to try a reboot again after removing and reinstall again

**Comment by be5invis** [comment]
@michaelperrygoodman Perhaps you could uninstall, reboot then install. This should be the cleanest.

**Comment by michaelperrygoodman** [comment]
@be5invis The reboot seems to have cured it. Everything looking nice again!

**Comment by be5invis** [comment]
Closing as fixed

**Comment by Matt-Gleich** [comment]
Thank you!

**Comment by singularitti** [comment]
I have updated the homebrew fonts.

**Comment by Matt-Gleich** [comment]
Thank you @singularitti!
