### ISSUE TITLE
= sign messed up in 1.8.1

### ISSUE THREAD

**Issue by tpoisot** [be5invis/Iosevka#71]
I've upgraded to 1.8.1 (from the releases page), and all the `=` signs are replaces by something longer. I'm not sure the ligatures should be activated by default...

![2016-03-06_19h27m06](https://cloud.githubusercontent.com/assets/579329/13558377/a3cca908-e3d1-11e5-95bd-b159f15389e5.png)

**Comment by be5invis** [comment]
It looks like that lookup 43 is mis-applied.
What's the software (editor/terminal/...) you are using?

**Comment by be5invis** [comment]
@tpoisot Does this one still have the same problem?
http://7xpe0v.com1.z0.glb.clouddn.com/iosevka-regular.ttf

**Comment by dgeibi** [comment]
gnome-terminal on Arch Linux has this problem

**Comment by be5invis** [comment]
@dgeibi Does the version in the link I mentioned before still have this problem?

**Comment by dgeibi** [comment]
@be5invis sorry, the ttf file can't be downloaded

**Comment by be5invis** [comment]
@dgeibi How about this?
http://7xpe0v.com1.z0.glb.clouddn.com/iosevka-regular-182a.ttf

**Comment by dgeibi** [comment]
![_2016-03-07_21-00-04](https://cloud.githubusercontent.com/assets/2224764/13570177/a06a19d6-e4a7-11e5-8685-3c04f5db39f0.png)

still not correct

**Comment by kelaun** [comment]
Same issue on Manjaro Linux using Terminator. 
I installed the font through the AUR package which is at version 1.8.1-1

**Comment by be5invis** [comment]
I can confirm that the replacement glyph is `ligeq.lr`. I looks like that freetype mis-triggered a replacement.

**Comment by be5invis** [comment]
@dgeibi @tpoisot @kelaun How about this?
http://7xpe0v.com1.z0.glb.clouddn.com/iosevka-regular.182b.ttf

**Comment by kelaun** [comment]
Not working for me. It still gives the same issue.

**Comment by be5invis** [comment]
Found this: https://github.com/larsenwork/monoid/issues/138
and this: https://github.com/larsenwork/monoid/issues/31

I think it is a GNOME Terminal bug, rather than an Iosevka's.
I'll provide a non-ligature version with different font-family name in 1.8.2.
The README will be updated either to notify this.

**Comment by be5invis** [comment]
@dgeibi @tpoisot @kelaun 
In release 1.8.2 I provided three variants without ligation support. They are also assigned to a separate family so that it can co-exist with the existing Iosevka (which can be used in editors).

**Comment by dgeibi** [comment]
Thanks! It works well!
