### ISSUE TITLE
README descriptions of `v-one-nobase` and `v-one-base` interchanged

### ISSUE THREAD

**Issue by bob-swinkels** [be5invis/Iosevka#711]
There is an issue in the readme in the style of the `1` character. The descriptions of `v-one-nobase` and `v-one-base` seem to be interchanged. 

> - Styles for `1`:
>   - `v-one-nobase`, `cv50`: `1` with bottom serif (default for Sans).
>   - `v-one-base`, `cv51`: 1 without bottom serif (default for Slab).
>   - `v-one-line`, `VXAM`: 1 drawn just like a straight line.

I believe this needs to be: 

> - Styles for `1`:
>   - `v-one-nobase`, `cv50`: `1` **without** bottom serif (default for Sans).
>   - `v-one-base`, `cv51`: 1 **with** bottom serif (default for Slab).
>   - `v-one-line`, `VXAM`: 1 drawn just like a straight line.

This seems to be introduced when the README's automatic generation was added, and I think this needs to be corrected in the `variants.toml` file.

**Comment by be5invis** [comment]
Fix expected to be landed with next release
