### ISSUE TITLE
全角字符":"显示错误,请增加等宽字符

### ISSUE THREAD

**Issue by nuoyan001** [be5invis/Iosevka#72]
全角字符":"显示错误,请增加等宽字符

**Comment by be5invis** [comment]
What's the version you are using? The Inziu and `withfw` variants has a full-width colon.

**Comment by nuoyan001** [comment]
1.8.1

**Comment by nuoyan001** [comment]
Inziu IosevkaCC SC 1.81

**Comment by be5invis** [comment]
I think it is a bug in your IDE. The Iosevka's full-width colon is completely normal.
By design, the full-width colon is centered, just like Microsoft YaHei.
Closed.
