### ISSUE TITLE
cv46 and cv47 not working?

### ISSUE THREAD

**Issue by AlsoScratch** [be5invis/Iosevka#721]
Describe your problem here. Provide pictures and files if necessary.

---

* Your font version: 4.0.0-alpha.1
* Your font variant: Fixed
* Your operating system (name and version): macOS 10.15.7
* Your application using Iosevka: Atom

I believe cv46 and cv47 are supposed to change the `¶` and `^` symbols.
<img width="400" alt="Screenshot 2020-11-10 at 10 59 08 AM" src="https://user-images.githubusercontent.com/48752273/98622276-17dc6480-2344-11eb-91a8-6e83615869fb.png">

**Comment by be5invis** [comment]
I believe it is a bug in Harfbuzz, limiting the total size (?) of feature-value combinations.
It is not reproducible on other platforms.
For a workaround, creating a custom build will mitigate this -- the features are "baked" into the font so you will not need to specify them in CSS. You can also try to apply some `ss##` feature then override with `cv##` features to reduce the quantity of total feature applications.
Closing as external.
