### ISSUE TITLE
U+0462 CYRILLIC CAPITAL LETTER YAT and U+0463 CYRILLIC SMALL LETTER YAT

### ISSUE THREAD

**Issue by van-de-bugger** [be5invis/Iosevka#727]
Yat is not used in modern Russian alphabet, but is the *only* letter from old (pre-1918) Russian alphabet missed in Iosevka. Other old Russian letters (І, Ѳ, Ѵ, and even Ѷ) are already present in Iosevka.

Yat is present in many other monospace fonts:

Cousine:
![Yat-in-Cousine](https://user-images.githubusercontent.com/721164/98969107-92ada700-251f-11eb-94e4-c7366d04152c.png)
DejaVu Sans Mono:
![Yat-in-DejaVuSansMono](https://user-images.githubusercontent.com/721164/98969154-9e996900-251f-11eb-87e2-df043e49dbb1.png)
Drois Sans Mono:
![Yat-in-DroidSansMono](https://user-images.githubusercontent.com/721164/98969169-a35e1d00-251f-11eb-830f-1e0c9c0caeeb.png)
Liberation Mono:
![Yat-in-LiberationMono](https://user-images.githubusercontent.com/721164/98969201-a9ec9480-251f-11eb-86a1-fc2a0940e823.png)
Source Code Pro:
![Yat-in-SourceCodePro](https://user-images.githubusercontent.com/721164/98969223-ae18b200-251f-11eb-8f29-598809d35b9f.png)

**Comment by be5invis** [comment]
Closing in favor of https://github.com/be5invis/Iosevka/commit/3d194b63bc1fcf3bf38d781fb0904fa0b831085f
