### ISSUE TITLE
Add more punctuations or symbols to gain better compatibility in several special, CJK-oriented environments

### ISSUE THREAD

**Issue by nuoyan001** [be5invis/Iosevka#73]
我重新做了测试,并总结了一下问题,

当IDE字体 设置为9号 所有字符显示正常
当设置为 10号时  全角空格显示有点异常,但不会显示错误
当设置为11号时  基本全角符号都有点问题出现,中文下更严重
http://chuantu.biz/t2/30/1457369959x1026960977.jpg

当设置为12号时  全角空格显示出错
http://chuantu.biz/t2/30/1457370056x1026960977.jpg
图片表示--||

13号14号 如上
再大未测试
字体名称
Inziu IosevkaCC SC
Inziu IosevkaCC Slab SC
版本 1.8.1

补充一个
"≠" 显示太丑了 "÷" 太短了 "×" 有点小
能否修改一下

**Comment by be5invis** [comment]
Please provide a link to the IDE you mentioned. I will not fix Iosevka for a specific environment, especially developed for a specific language, even a specific font (like SimSun).

**Comment by nuoyan001** [comment]
真心谢谢你,对这个问题的在意
环境是易语言
www.eyuyan.com
有关图像我只能这样找个地方上传一下
问题应该在空格上
9号 10号显示一切正常
11号显示最混乱,12号只有全角空格或空格显示有点小问题
并不是我之前所说的 ":"的问题

**Comment by be5invis** [comment]
11 is an odd number, perhaps related to rounding. The IDE may using some grid-based positioning to place characters, therefore rounding error or missing glyphs (like the Kome Symbol `※`)  will distort the entire thing.
I will not fix the rounding error for 11px, however I will add more punctuations and symbols in the future, and it will eventually fix your problem.

**Comment by nuoyan001** [comment]
如果再次更新的话,把空格符号修正一下吧
我现在只能使用10号,12号使用时总感觉有点怪怪的
在使用10号的时候会有点小,如果再把 "≠"   "÷"   "×"  ... 再重画一下就更好了
期待下次更新

**Comment by be5invis** [comment]
Iosevka does not contain the Ideographic Space (U+3000, `　`). I think the incorrect rendering is related to the missing Kome symbol `※`. For mathematical symbols, they simply share the same glyph size with the half-width.

**Comment by Arthur2e5** [comment]
Note that @nuoyan001 mentions *Inziu* Iosevka. I can confirm that `uni3000` is in Inziu IosevkaCC Regular with fontforge,

**Comment by be5invis** [comment]
Kome has been added in the latest release.
As long as some symbols under CC variant is enwiden.
I think this issue can be closed.
