### ISSUE TITLE
1/10 fraction is not correct on the website

### ISSUE THREAD

**Issue by AlsoScratch** [be5invis/Iosevka#736]
Describe your problem here. Provide pictures and files if necessary.

---

* Your font version: 4.0.0-beta.2
* Your font variant:
* Your operating system (name and version): macOS 10.15.7
* Your application using Iosevka: Google Chrome

<img width="228" alt="Screenshot 2020-11-15 at 10 42 55 PM" src="https://user-images.githubusercontent.com/48752273/99187849-ecb6a280-2793-11eb-924b-a745718504da.png">
OpenType has failed to apply to the bottom digit 1. However, it appears to be fine in the TTF.

**Comment by be5invis** [comment]
It looks like that, for this particular character, with `cv36` applied, `cv37` won't be effective for lower half. This should be a bug in the font.
