### ISSUE TITLE
Variants for ŧ and better ţ variants

### ISSUE THREAD

**Issue by AlsoScratch** [be5invis/Iosevka#737]
The character `ŧ` should have variants just like `t`.
Also, I suggest improving the diacritic connection in the other variants for `ţ`: (the left 2 are good)
<img width="250" alt="Screenshot 2020-11-15 at 10 51 02 PM" src="https://user-images.githubusercontent.com/48752273/99188084-1b814880-2795-11eb-83f1-2c53b520ece4.png">

**Comment by AlsoScratch** [comment]
Can I see what they look like?

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/99224480-3fe02380-279b-11eb-9229-4b51cccb17f4.png)
![image](https://user-images.githubusercontent.com/240091/99224496-466e9b00-279b-11eb-9f54-fb8f8c0748e6.png)
