### ISSUE TITLE
Can't build from clean checkout

### ISSUE THREAD

**Issue by dmcooke** [be5invis/Iosevka#738]
Running `npm run -- build ttf::iosevko` fails with 'Error: Cannot find module '../glyphs/index'. It appears the build system is not building `font-src/glyphs/index.js` from `font-src/glyphs/index.ptl`.

Examing `verdafile.js`, it appears that [in the definition of `Scripts`](https://github.com/be5invis/Iosevka/blob/922ca29aa70790b6c3d6fbd14274b41eec2860c7/verdafile.js#L879) the tasks added to the `subGoals` variable are only those for which a .js file _already exists_, which is not the case for the .ptl files in a clean checkout.

Changing this to a union instead of an intersection (adding `CompiledJs` goals for each `.ptl` file, and `sfu` goals for each `.js` not in the .ptl list) makes the build complete successfully.

**Comment by pv4** [comment]
Me too.

For me the fix (see below) is to partially revert the last part of commit fe53c125feae18d7da770c4dfb479a13cb5342c3 .

```diff
diff -Napur Iosevka.orig/verdafile.js Iosevka/verdafile.js
--- Iosevka.orig/verdafile.js	2020-11-15 15:57:39.618114286 +0300
+++ Iosevka/verdafile.js	2020-11-15 15:59:01.019117136 +0300
@@ -876,10 +876,8 @@ const Scripts = task("scripts", async ta
 	const jsFromPtlSet = new Set(jsFromPtlList);
 
 	let subGoals = [];
-	for (const js of jsList) {
-		if (jsFromPtlSet.has(js)) subGoals.push(CompiledJs(js));
-		else subGoals.push(sfu(js));
-	}
+	for (const js of jsFromPtlSet) subGoals.push(CompiledJs(js));
+	for (const js of jsList) if (!jsFromPtlSet.has(js)) subGoals.push(sfu(js));
 	await target.need(subGoals);
 });
 const UtilScripts = task("util-scripts", async target => {
```
