### ISSUE TITLE
Issue with rendering = after upgrade to 1.8.2

### ISSUE THREAD

**Issue by Gonzih** [be5invis/Iosevka#74]
Hi,

After I updated to 1.8.2 I noticed issue with rendering of = sign.

Iosevka:

![3eccad16-ce33-4ece-b01c-fa41769f4b5c](https://cloud.githubusercontent.com/assets/266275/13773786/74e3207e-ea9b-11e5-8d97-e51970a89f34.png)

Inconsolata:

![9b781b6a-8e08-4bc1-9344-eb2d4e539379](https://cloud.githubusercontent.com/assets/266275/13773789/7d87e5c0-ea9b-11e5-9124-a79fa3e53d5f.png)

Is that a regression or something related to the IosevkaNL change?

**Comment by be5invis** [comment]
As I mentioned before in #71, some environments, especially some Linux environments, cannot handle ligature features correctly. The `IosevkaNL` is designed for such situations. 
Closed.

**Comment by Gonzih** [comment]
Got it, thanks! Maybe some examples of the issues can be provided in description what is IosevkaNL. I at first thought that it is something related to the dutch locale so did not even look at this variant. NL is very confusing abbreviation imho.
