### ISSUE TITLE
Remove Bottom Bar from 1 in Slab Variant

### ISSUE THREAD

**Issue by varbhat** [be5invis/Iosevka#743]
Hello ,

For a font to be perfectly readable , it's characters must be distinct enough . 1 and l are such characters that are similar.
In Iosevka Slab Variant , both 1 and l differ only in slant in the top bar. To  make that more distinct and readable , I would like to suggest to remove bottom bar from 1 in Slab Variant. 

![iosevka](https://user-images.githubusercontent.com/68165364/99808413-d2e7d780-2b66-11eb-9506-88d216549fc8.png)

Above image is screenshot of 1s and ls in Slab Variant. Readability is very less in that image (They look similar) . 

I am using  3.7.1 version.

**Comment by be5invis** [comment]
Mark as Needs Justification. Slab is a subfamily targeting aesthetics over distinguishability. It **should** have serifs even if it reduces distinguishability.

**Comment by be5invis** [comment]
And, you can always customize with a family removing bottom serif of “1” from Slab.
