### ISSUE TITLE
website: possibly mislabeled version on Inziu Iosevka page

### ISSUE THREAD

**Issue by MingcongBai** [be5invis/Iosevka#75]
As seen here.

![2016-03-16 11-16-26](https://cloud.githubusercontent.com/assets/5006263/13821761/8f5302da-eb68-11e5-9427-4cbb1067fb21.png)

The top link with version labeled "1.8.16" returns 404. While I am able to download 1.8.3 release (which is not listed on the page). Is this a mislabeled version?

Best Regards,
Mingcong (Jeff) Bai

**Comment by be5invis** [comment]
Fixed.
