### ISSUE TITLE
Unequal glyphs size

### ISSUE THREAD

**Issue by UzayrQamarxyz** [be5invis/Iosevka#753]
* Your font version: Iosevka version 4.0.0-beta.3
* Your font variant: Default, Term, Term Fixed
* Your operating system (name and version): Artix Linux
* Your application using Iosevka: Using it as my terminal font

Glyphs sizes are not equal

![Iosevka](https://user-images.githubusercontent.com/52358137/99905787-dc06af00-2cf4-11eb-95c4-57141001c0b5.png)

Above is the result of all the three mentioned fonts.

**Comment by UzayrQamarxyz** [comment]
Gathering from what I see in ryanoasis/nerd-fonts#127 this issue occurs only in the mono spaced fonts
However this still doesn't explain why default version here still has this problem.

![1606055516](https://user-images.githubusercontent.com/52358137/99906545-854fa400-2cf9-11eb-9f98-4fca662bd646.png)

**Comment by be5invis** [comment]
Iosevka does **NOT** contain those pictograms.
And, the behavior of pictograms in terminals are implementation-defined.
I think you should raise an issue to your terminal's author.
Closing as external.
