### ISSUE TITLE
Ellipsis is dissociated when placed directly before or after some characters

### ISSUE THREAD

**Issue by std282** [be5invis/Iosevka#757]
When I place an ellipsis directly before [after] some characters, its right [left] dot slightly shifts towards the character, which is not desirable. It's as if the character "pulls" the nearest dot towards itself.

Here's examples. 
At the first line the ellipsis is surrounded by spaces, and it looks OK.
At the second line the ellipsis is placed directly before right parenthesis, and the third dot is pulled towards the parenthesis.
At the third line the ellipsis is placed next to comma, and the first dot is pulled towards the comma.

![iosevka_ellipsis](https://user-images.githubusercontent.com/31089329/100319111-2d05f400-2fd0-11eb-8c5b-7ce310bb4782.png)

I tried to find characters that pull the nearest dot towards itself, and found those: ``~!#^&*-+=()[]{}:;<>,/?``

I also tried to build the font with disabled ligations ``"kern-dotty"`` and ``"dot-as-operator"``, but to no avail. It might deserve the attention as well.

This behaviour can also be observed with the stock versions of Iosevka (for example, default Iosevka).

---

Font version: 4.0.0-beta.3
Font variant: custom build
OS: Windows 10 Pro 20H2
Application: Visual Studio Code

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/100333155-1b4c2e80-2f87-11eb-98b9-62ddd8830953.png)
