### ISSUE TITLE
Ligation Request: More Haskell arrows

### ISSUE THREAD

**Issue by skalyan91** [be5invis/Iosevka#765]
Please consider adding ligatures for `>>`, `>>>`, `>=>` and `<=<`. See [here](https://hackage.haskell.org/package/base-4.14.0.0/docs/Control-Monad.html) and [here](https://downloads.haskell.org/~ghc/7.10.1/docs/html/users_guide/arrow-notation.html) for details of usage.

**Comment by be5invis** [comment]
These are already included under `HSKL` feature, and are *not* planned to be added into `calt`.

**Comment by skalyan91** [comment]
I understand that; in fact I am using a custom build that defaults to the Haskell ligation set.

However, the four ligatures I mentioned don’t seem to be supported. It is possible that my version of the font is out of date (I will update it at the next opportunity); but I don’t see any mention of these ligatures in the readme, or in the release notes.

**Comment by be5invis** [comment]
`<<` and `<<<` are included (and by default), just not so obvious. They look a little kerned.
`<=<` and `>=>` are indeed supported under `HSKL`. README doesn't need to support everything.
![image](https://user-images.githubusercontent.com/240091/100840792-40c7b500-342b-11eb-9f76-eddb8777067d.png)

**Comment by skalyan91** [comment]
Oh! Sorry, I’ll just update to the latest version of the font, then.

Apologies for opening an unnecessary issue!
