### ISSUE TITLE
Hook tailed 'q' variant - 'handwriting style'

### ISSUE THREAD

**Issue by OJFord** [be5invis/Iosevka#766]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [ ] Some other monospace/programming fonts supported the requested variant. Provide images below.

(The closest I've found are 'monospace', 'Prestige Elite', and 'UM Typewriter', which each have a horizontal serif extending both sides of the tail, but not flicking up.)

------

*Please provide your your justification here.*

I would like a variant of `q` that looks more like how (in my experience) it's usually handwritten - not cursive exactly, just with the 'hook' or 'flick' back up.

Wikipedia image (lower left):
[![](https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Q_and_g_comparison.svg/225px-Q_and_g_comparison.svg.png)](https://en.wikipedia.org/wiki/Q#/media/File:Q_and_g_comparison.svg)

**Comment by be5invis** [comment]
I think we already had this (`cv25#2`)?
![image](https://user-images.githubusercontent.com/240091/100939541-482ea300-34ab-11eb-835d-d2ecee263d90.png)
Or you need something like IBM Plex Italic's upward-going tail?

**Comment by OJFord** [comment]
I mean more like this:
![](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.bigactivities.com%2Fprinting%2Falphabet%2Flowercase%2Fimages%2Fsmall_q_instructions.png)

**Comment by be5invis** [comment]
Put in backlog for now. This may also influence other letters (like `n` and `m`).

**Comment by be5invis** [comment]
Merge into #795. Closing.
