### ISSUE TITLE
Ligatures for {| and |}

### ISSUE THREAD

**Issue by asazernik** [be5invis/Iosevka#767]
- The requested character is...
  - [ ] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [x] Punctuation
  - [ ] Symbol
- [x] Some other monospace/programming fonts supported this character. Provide images below.

------

This pair is common in Javascript with Flow type annotations, where this is used in type annotations to denote an exact object type. (`{ a: number }` specifies a type that can have properties other than `a`, while `{| a: number |}` specifies a type that has only the property `a`.)

The Fira versions of these ligatures are below.
 
![image](https://user-images.githubusercontent.com/1307640/101151002-e4ed5f80-35d5-11eb-82a0-a8aa51eaf4c6.png)

**Comment by be5invis** [comment]
I have to say one thing... Fira's version is horrible. We need more crafted design.

**Comment by asazernik** [comment]
Fair enough. I prefer Fira's ligature to the two adjacent characters, but that's a low low bar.

**Comment by be5invis** [comment]
Plan to make something like this. Also adding `[|` and `|]` for Haskell-ish idiom bracket.
![image](https://user-images.githubusercontent.com/240091/101267673-2aae4300-3710-11eb-9c1c-87a9ff782ec8.png)

**Comment by be5invis** [comment]
@asazernik They are now in `dlig`.

**Comment by be5invis** [comment]
Closing. I am targeting a version 4.0.2 release tomorrow with these included, as well as fixes of symbols.
