### ISSUE TITLE
Characters CYRILLIC LETTER YAT not displaying in the mono variants

### ISSUE THREAD

**Issue by KSundstrom** [be5invis/Iosevka#770]
Letters CYRILLIC CAPITAL LETTER YAT (U+0462) and CYRILLIC SMALL LETTER YAT (U+0463) do not display for me using Iosevka's mono variants (Iosevka Roman & Italic, Iosevka Curly Roman & Italic, Iosevka Slab Roman & Italic, and Iosevka Curly Slab Roman & Italic), whereas the proportional variants (Iosevka Aile Roman & Italic, Iosevka Etoile Roman & Italic, and Iosevka Sparkle Roman & Italic) do display the letters.

In Iosevka Roman & Italic:
![Iosevka marked](https://user-images.githubusercontent.com/1502103/101992659-b3ebe980-3cbd-11eb-9442-2fd20ec57191.jpg)
![Iosevka Italic marked](https://user-images.githubusercontent.com/1502103/101992692-be0de800-3cbd-11eb-994e-4f747c74dfbf.jpg)

In Iosevka Aile Roman & Italic:
![Iosevka Aile marked](https://user-images.githubusercontent.com/1502103/101992694-c23a0580-3cbd-11eb-9e3f-a3c5d4da5644.jpg)
![Iosevka Aile Italic marked](https://user-images.githubusercontent.com/1502103/101992696-c49c5f80-3cbd-11eb-9962-3d3fd115f707.jpg)

---

* Your font version: 4.0.3
* Your font variant: Iosevka Roman & Italic, Iosevka Curly Roman & Italic, Iosevka Slab Roman & Italic, and Iosevka Curly Slab Roman & Italic (as opposed to Iosevka Aile Roman & Italic, Iosevka Etoile Roman & Italic, and Iosevka Sparkle Roman & Italic)
* Your operating system (name and version): Windows 10 Home/20H2/29.‎5.‎2020/19042.685/Windows Feature Experience Pack 120.2212.551.0
* Your application using Iosevka: Notepad++/7.9.1/64-bit

**Comment by be5invis** [comment]
I am very sure that these characters **are** included in Iosevka v4.0.3 and the font is well formed. Could you please try to uninstall the fonts first, then restart computer, then reinstall them? This will resolve caching-related issues.
![image](https://user-images.githubusercontent.com/240091/101993573-875db080-3c70-11eb-8a54-4674aba7cf8a.png)

**Comment by KSundstrom** [comment]
I will try it and report back.

P.S. Let me also express here how much I appreciate your fonts and your work on them! I use them very extensively.

**Comment by KSundstrom** [comment]
> I am very sure that these characters **are** included in Iosevka v4.0.3 and the font is well formed. Could you please try to uninstall the fonts first, then restart computer, then reinstall them? This will resolve caching-related issues.

A thorough removal of all variants, a reboot and a reinstallation did indeed resolve this. Interesting! There seemed to be many overlapping font files on my system for some reason. My apologies for the inconvenience! This issue can of course be closed.
