### ISSUE TITLE
Character Variant Request: "off-kilter" 'e', or one that looks like a rotated cv12=4 (doublestorey-toothless-rounded) 'a'

### ISSUE THREAD

**Issue by AndydeCleyre** [be5invis/Iosevka#771]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [ ] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
  - ~If the build has this *and* cv12=4, it could conflict with `Latin Small Letter Turned A`~
- [ ] Some other monospace/programming fonts supported the requested variant. Provide images below.

------

I'm interested in getting an `e` that's *somehow* off-kilter, and noticed that the `doublestorey-toothless-rounded` `a` variant already provides a suitable shape for such an `e` if it's rotated 180°. So it seems like an opportunity to expand this project with a more distinctive `e`, without introducing any totally new forms.

What do you think?

**Comment by be5invis** [comment]
Could you provide an image of this?

**Comment by AndydeCleyre** [comment]
Line | Difference from my current build
--- | ---
2 | None
3 | cv12=4, to show the `a` that can become an `e`
1 | `e` is replaced by a rotated `a` from line 3

![image](https://user-images.githubusercontent.com/1787385/102304125-b30bbf80-3f2a-11eb-9069-f1c6258947ad.png)

**Comment by pv4** [comment]
Hello.

Sorry for intervention, but it seems for me that @AndydeCleyre asks for italic/cursive variant of latin `e` like in DejaVu Serif (without the right corner between the horizontal bar and the top arc).

![e-italic](https://user-images.githubusercontent.com/2502094/102374335-43510f80-3fd2-11eb-910a-000d2d4b040f.png)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/102567192-ddc65700-4095-11eb-8c28-27ef0dd87200.png)![image](https://user-images.githubusercontent.com/240091/102567231-efa7fa00-4095-11eb-97fc-412856f7f79a.png)

Looks really weird in Upright, though nice in Italic.

**Comment by AndydeCleyre** [comment]
I think it makes for a handsome and distinctive upright choice. Thanks so much!

It *is* a bit strange, at least at first, kind of like the `a` is smirking behind its `e` disguise. 

But it also helps me clearly identify the letter as a unique form at a glance, and adds a fun variation to the overall line forms.

![image](https://user-images.githubusercontent.com/1787385/102653814-87145800-413d-11eb-9262-920ee7f7f1ef.png)
