### ISSUE TITLE
cyrl/U=straight is hardcoded when y=cursive/cursive-flat-hook is used

### ISSUE THREAD

**Issue by pv4** [be5invis/Iosevka#773]
Hello!

In my `private-build-plans.toml` I have
```toml
capital-y = 'curly'
y = 'cursive-flat-hook'
```

As a result `cyrl/U` uses the variant similar to `y.straight` while I expect one like `y.curly` (NOT `capital-y.curly`). I can just edit `params/variants.toml` before building and set `selector."cyrl/U" = "curly"` manually so it's not a big problem personally for me.

This issue in big is somewhat similar to #627 in that a hard-coded default for a depending glyph is used if a variant of the dependency is choosen which cannot be used for the dependent glyph. So when one uses this variant for the dependency glyph the variant for the dependent glyph cannot be choosen. I don't know whether it's possible to fix the issue in big without creating a separate variant set for each dependening glyph (e.g. allowing something like `cyrl.U = "curly"` in `private-build-plans.toml` which would create TONS of glyphs/variants to document and hard to read and use for people who only knows/uses one or two languages).

#627 was fixed by creating a separate variant which was logical because it also influenced another latin glyph (uppercase `K`). For this issue this solution is not the best one since english-speaking people won't even see a benefit from using a new variant if it's introduced.

As a simple solution, `selector."cyrl/U"` should be set in `prime.capital-y` instead of `prime.y` (the appearence of `cyrl/U=straight|curly` must be kept as is i.e. inherited from `LOWERCASE y`). But the issue will popup again when/if a new variant for `capital-y` is added not supported by `cyrl/U`.

As a better solution, maybe this issue should be thought on for some time to decide what whould be done for the best (by tagging it by "Far future" or anything like that).

Also feel free to just close the issue without any action since for now I have a way to get what I want.

**Comment by be5invis** [comment]
Cyrillic capital U follows the shape of `y`, so they should be grouped together. I am curious, does a Cyrillic capital U look cursive make sense? (i.e., orthographically acceptable.) If so, I can add them back to the variant selector system.

![image](https://user-images.githubusercontent.com/240091/102662364-8d9dd200-4133-11eb-99d0-fe9c31056661.png)![image](https://user-images.githubusercontent.com/240091/102662383-95f60d00-4133-11eb-85fb-a97c1b2e1913.png)

**Comment by be5invis** [comment]
Or, I can simply add a `cv60` for Cyrillic capital U only.

**Comment by pv4** [comment]
> does a Cyrillic capital U look cursive make sense?

If you mean cyrillic capital `U` having exactly the same variant as latin `y`, then yes, it's fine.

And what relates to cyrillic capital `U` CURSIVE, `y=cursive` makes it even better approach than `y=curly/straight`. The only downside is that capital U becomes looking more cursive while other capital letters still look more like just slanted upright ones (but there is a similar issue with lowercase latin letters #620 so I see no problem here).

BTW, AFAIU cursive `y` styles can be applied to latin `capital-y` as well, does it worth implementing it too?

I don't see a reason to waste `cv` namespace by creating a separate tag for cyrillic capital U. Moreover, if the variant will be set in `params/variants.toml`, `prime.y.variants.*` then those 0.1% people unsatisfied with the default setting (same as for latin `y`) would be able to edit that file to achieve what they want.

Well, as a final word, the attached image looks great for me (edited in gimp from `y=cursive-flat-hook`):

![image](https://user-images.githubusercontent.com/2502094/102667960-cbcedc00-419b-11eb-96d6-03c295f53679.png)

**Comment by be5invis** [comment]
@pv4 I think allocating `cv60` to Cyrillic capital U is worthy, since in the default case you do not want it to become cursive under italics.

**Comment by pv4** [comment]
@be5invis I've just looked through many (latin) fonts, and in most of them "cursiveness" is mostly applied for lowercase letters only while keeping capital letters looking like slanted upright ones. There is probably a font design rule I'm not aware of that causes such solutions (I'm a software developer, not a designer).

So, now I think that you might be right and adding `cv60` is worthly. I'm just afraid that it's not a good long-term solution. Won't we get hundreds `cv`-s later just because every language supported has its issues?
