### ISSUE TITLE
Iosevka Aile: toothles capital G?

### ISSUE THREAD

**Issue by van-de-bugger** [be5invis/Iosevka#774]
Hi,

It seems toothless capital G would look more naturally in Iosevka Aile.

**Comment by be5invis** [comment]
Aile follows default settings. Customization is not planned yet.

**Comment by van-de-bugger** [comment]
I have managed to build customized Aile by copying ~60 lines of code from `build-plans.toml` to `private-build-plans.toml`, but having a more convenient method like `inherits = "aile"` would be great.

**Comment by be5invis** [comment]
@van-de-bugger Problem of Aile is that, there are some variants (notably the `narrow`s) are *not* accessible in conventional `cv##` system. Also, it may be very easy to create broken shapes with CV/SS enabled.
Put this target to 4.x and investigate.

**Comment by be5invis** [comment]
Move into #776. Closing.
