### ISSUE TITLE
Support more letter variants for quasi-proportional

### ISSUE THREAD

**Issue by franklx** [be5invis/Iosevka#776]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [ ] Some other monospace/programming fonts supported the requested variant. Provide images below.

------
Letters **j**, **r**, **t** and **f** in the Aile quasi-proportional font are tied to the "narrow" design: building with other variants outputs a glyphs with completely wrong spacing; letters **i** and **l** have better (but still wrong) spacing.
For example I tried building a custom version of the Aile font with following settings:
```toml
f = "flat-hook-extended"
r = "earless-rounded"
l = "tailed"
```
![iosevka-demo](https://user-images.githubusercontent.com/12377/102709547-1dff2280-42ac-11eb-82bd-e1ab08b67691.png)

I could try creating the variants by myself but I don't have enough understanding of how the build system works.

**Comment by be5invis** [comment]
I may implement this in next major version.
Currently there aren't customization for quasi-proportional, and the reason turning it off is because that some shapes are broken when they are first implemented. May need a full review and a lot of testing.

**Comment by rekollekt** [comment]
Maybe single-storey lowercase letter-a have been already completed, isn't? x)
![Screen Shot](https://user-images.githubusercontent.com/15945329/103017016-40f73400-4543-11eb-9c07-0382106560dc.png)

**Comment by stone-zeng** [comment]
Single-storey `ɑ` is not only a style but also a character: LATIN SMALL LETTER ALPHA U+0251.

**Comment by rekollekt** [comment]
Of course yes x) It "just"... an IPA phonetic symbol.

**Comment by be5invis** [comment]
Quasi-proportional supported customization since v5.0. Closing.
