### ISSUE TITLE
Optimize with disabled anti-aliasing

### ISSUE THREAD

**Issue by TsavyPrince** [be5invis/Iosevka#777]
**Is your feature request related to a problem? Please describe.**
When using this font and disabling anti-aliasing, it looks pretty bad, unless it's at 18 pt or 9 pt.

**Describe the solution you'd like**
Add alternatives for characters to optimize disabled anti-aliasing.

**Comment by be5invis** [comment]
Iosevka uses `ttfautohint` which is not optimized for bilevel rasterizers.
Doing manual hints is not feasible, and is not the way modern fonts doing.
Closing as out of scope.
