### ISSUE TITLE
thermometer symbol

### ISSUE THREAD

**Issue by petr-fischer** [be5invis/Iosevka#78]
Hello, it's rather stupid issue, but can you add this unicode char to the font?

http://www.fileformat.info/info/unicode/char/1f321/index.htm

:)

**Comment by be5invis** [comment]
Why do you need this? Is this symbol used in some editor configurations (like Powerline?)

**Comment by petr-fischer** [comment]
Yes something similar - I am using i3 wm + i3 status bar. In the status bar, there is status info like cpu usage, battery usage etc etc and also cpu temperature! I am also using your famous iosevka font for everything monospaced, so, temperature char will be superb! :) :) In fact, I am surprised, that there is special symbols like "thermometer" in Unicode standard. So, of course, you can close this issue :)

**Comment by be5invis** [comment]
I need a full list of the symbols used.

**Comment by be5invis** [comment]
Consolidated to #81. Closed.
