### ISSUE TITLE
Add U+2306 PERSPECTIVE ⌆

### ISSUE THREAD

**Issue by rekollekt** [be5invis/Iosevka#780]
It seems to be that missing (in Iosevka and Iosevka Aile too) perspective glyph (U+2306). Please add U+2306 glyph: ⌆

**Comment by be5invis** [comment]
Are there any use cases of this symbol in programming?

**Comment by rekollekt** [comment]
`https://link.springer.com/article/10.1007/BF01185432`
![Screen Shot](https://user-images.githubusercontent.com/15945329/103014526-2e7afb80-453f-11eb-8684-a73479f26a65.png)

**Comment by rekollekt** [comment]
FYI @be5invis: https://github.com/rsms/inter/issues/319

**Comment by rekollekt** [comment]
Please add character variants of U+2306 PERSPECTIVE ⌆:
![gh](https://user-images.githubusercontent.com/15945329/120098895-c2797080-c138-11eb-9c0f-843ecc2fc31b.png)
(Please same add to U+2305 PROJECTIVE ⌅.)
