### ISSUE TITLE
Add U+0E3F Thai Currency Symbol Baht ฿

### ISSUE THREAD

**Issue by bkhl** [be5invis/Iosevka#781]
- The requested character is...
  - [x] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [x] Symbol
- [ ] Some other monospace/programming fonts supported this character. Provide images below.

------

Would be nice if the lack of this character could stop messing up character spacing in my editor when I do my plain-text book keeping.

Bitcoin people might also like it as it's a popular alternative character for that.

I know it's stretching it but I thought maybe it's a simple request as it should be relatively straight forward to derive from the B character.

As for design in various fonts, it seems it always comes with a horizontal stroke through the entire character, never an interrupted stroke like with some versions of the dollar sign.

Examples from a fairly authoritative Thai monospace font, TLWG Typo.

Including the B character (identical apart from the stroke as far as I can tell), and also illustrating that this font does that despite actual using an interrupted stroke for the dollar sign:

![image](https://user-images.githubusercontent.com/34634/102994366-83277200-4551-11eb-98e8-6dd063cab762.png)

![image](https://user-images.githubusercontent.com/34634/102994605-f5985200-4551-11eb-889e-0777e807a98a.png)

![image](https://user-images.githubusercontent.com/34634/102994670-13fe4d80-4552-11eb-834e-e48bebb8eead.png)

**Comment by be5invis** [comment]
`U+20BF` is a specialized Bitcoin symbol.

**Comment by bkhl** [comment]
Thanks!
