### ISSUE TITLE
U+202F: Narrow no-break space

### ISSUE THREAD

**Issue by van-de-bugger** [be5invis/Iosevka#782]
- The requested character is...
  - [ ] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [x] Symbol
- [x] Some other monospace/programming fonts supported this character. Provide images below.

The character is present in Adobe Source Code Pro, Google Noto Sans  Mono, Google Roboto Mono, DejaVu Sans Mono, Hack. I do not provide images because the symbol is just blank.

------

This character is frequently used in French, Russian, German and Mongolian languages, see [wikipedia](https://en.wikipedia.org/wiki/Non-breaking_space#Width_variation).

Regardless of its name, Narrow no-break space in *monospace* Iosevka should be as wide as regular space (and as wide as other characters).

In quasi-proportional Iosevka fonts Narrow no-break space may be narrower than regular space. In DejaVu Sans, Google Arimo, Liberation Sans and Gnu Free width of Narrow no-break space is approximately 2/3 of regular space width. However, I think it is too wide, 1/2 of regular space would be enough:

1. In a Russian typographic manual there are requirements to use "2 point space" (*point* is 1/72 of inch) to separate em-dash from surrounding text, use the same "2 point space" between degree sign and scale (e. g. 10° C), etc.

2. There is a [proposal](https://www.unicode.org/L2/L2020/20008-core-text.pdf) (not yet accepted, though) to make `U+202F Narrow no-breaking space` a non-breaking version of `U+2009 Thin space`.

**Comment by be5invis** [comment]
Added in earlier commits.
