### ISSUE TITLE
Allow onum-height equal to x-height

### ISSUE THREAD

**Issue by pv4** [be5invis/Iosevka#784]
Currently there is an ability to have different digit forms (onum/lnum) using `digit-form = lining/old-style`. But the default onum height is slightly above than x-height (see #402).

Mixed text (lowercase letters and old-style figures) looks messy in such a setup since lowercase letters have one height, digits like 0/1/2 have another height, digits like 3/8 have yet another one. Besides, the height of 0/1/2 differs from the height of 3/8 very little and it looks like the person designed them was so drunk that he was just unable to make them of the same height so the height difference is not intentional but is happened by an accident (in other fonts presented in #402 this effect is even more).

With onum height equal to x-height the height of 0/1/2 differs from the height of 3/8 in the same degree as lowercase letter height differs from the height of letters like b/d/k/l and is obviously made intentionally.

I cannot say anything about readability of onum height being equal to x-height though since my build of upright variant (used by me mostly) has lining figures while old-style figures are used in italic variant which I only use in window manager window titles and in comments in my code.

When doing my builds I apply the following patch to make onum height equal to x-height:
```patch
--- Iosevka-dev.orig/font-src/glyphs/number/index.ptl   2020-09-21 01:55:09.000000000 +0300
+++ Iosevka-dev/font-src/glyphs/number/index.ptl        2020-09-21 02:04:43.991384746 +0300
@@ -8,7 +8,7 @@ glyph-module
 
 glyph-block Digits-Shared : begin
        glyph-block-export OnumHeight
-       define OnumHeight : mix XH CAP 0.375
+       define OnumHeight : mix XH CAP 0.0
 
        glyph-block-export ShiftDown
        define [ShiftDown] : glyph-proc
```

Is it possible to make a variant-like option like `digit-form` allowing to have different onum heights and to do that in `private-build-plans.toml` without patching, anything like `onum-height = x-height|above-x-height` please?

**Comment by be5invis** [comment]
This should lie in the area of metric overrides. Added `onumZeroHeightRatio` to control that — set to `1` will make `onum` digits the same height as `x`.
