### ISSUE TITLE
Private build plan builds wrong variants

### ISSUE THREAD

**Issue by spacekookie** [be5invis/Iosevka#785]
I'm trying to build a font with a lot of custom variants. I've noticed that a few letters actually don't build the variants that are documented in the README. I tried searching the issue tracker but couldn't find anything about this yet. Please link me to relevant issues that I might have missed.

Following the variants that don't behave the way they should. Screenshot of the built font is attached.

- "v-f-tailed" produces CV15-11 instead of CV-15-3
- "v-capital-i-serifless" produces CV05-1 instead of CV05-2
- "v-u-toothless-rounded" produces CV28-1 instead of CV28-3

---

* Your font version: Release 3.7.1
* Your font variant: custom
* Your operating system (name and version): NixOS unstable channel
* Your application using Iosevka: LibreOffice and emacs

If you have problem when building Iosevka, please provide these information:

* Your Node.js version: 14.15.1
* Your _otfcc_ version:

* Your `private-build-plans.toml`, if present
```
[buildPlans]
[buildPlans.iosevka-kookiefonts]
design = ["v-capital-g-toothless-corner", "v-capital-i-serifless", "v-capital-j-serifless", "v-a-doublestorey-tailed", "v-b-toothless-corner", "v-d-toothless-corner", "v-f-tailed", "v-g-earless", "v-i-tailed", "v-j-serifless", "v-l-tailed", "v-m-earless-corner-double-arch", "v-n-earless-rounded-straight", "v-p-earless-corner", "v-q-earless-corner", "v-r-earless-corner", "v-u-toothless-rounded", "v-y-cursive-flat-hook", "v-asterisk-low", "v-zero-dotted", "v-dollar-open", "v-numbersign-slanted", "v-at-fourfold"]
family = "Iosevka Kookie"
```

* The detailed error log: getting the log is kinda tricky because it spams the output with updates about how much CPU and RAM the builder is using, and I've failed to disable that. If you have an idea how to do that I'll update this issue.
![Screenshot from 2020-12-25 14-43-57](https://user-images.githubusercontent.com/7669898/103137127-82641c80-46c6-11eb-8edc-38f0e59b0e34.png)

**Comment by be5invis** [comment]
Well, I no longer maintain v3. Could you please try to upgrade your profile to V4-compatible ones? Use [the customizer](https://typeof.net/Iosevka/customizer) to create your profile and rebuild.
