### ISSUE TITLE
slab serif C for mathbf

### ISSUE THREAD

**Issue by xzackli** [be5invis/Iosevka#787]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] Some other monospace/programming fonts supported the requested variant. Provide images below.

------

Commit https://github.com/be5invis/Iosevka/commit/73619b0d6ddf0b093d6fd524a9f4489855bf39b6 added support for math bold and italics to resolve #444, but the difference between regular weight and the mathbf weight is hard to distinguish when looking at code. For example, in the following snippet I've made `M` mathbf to indicate it's a matrix.

![image](https://user-images.githubusercontent.com/8048811/103257855-edc91b00-4960-11eb-92ab-b5e1dbe9ebbe.png)

If I change the mathbf to slab-serif and increase the font weight (i.e. https://github.com/be5invis/Iosevka/compare/master...xzackli:master), I think you get a really nice looking math styling, which is clearly distinguishable from the regular font.

![image](https://user-images.githubusercontent.com/8048811/103258086-caeb3680-4961-11eb-89e6-01f86f521489.png)

This is similar to what happens with Menlo,

![image](https://user-images.githubusercontent.com/8048811/103258724-4cdc5f00-4964-11eb-9661-339a50141632.png)

I'm happy with these changes, except that for some reason in my line of work, matrices with the letter C are very common. The slab Iosevka C looks like the sans version! Would it be possible to add a slab variant for C/c that includes serifs, to aid in this distinguishability? Such serifs can be seen in other slab serif fonts like [Clarendon](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Clarendon.svg/1920px-Clarendon.svg.png) or [Courier New](https://en.wikipedia.org/wiki/Slab_serif#/media/File:Courier.svg). 

Finally, perhaps mathbf in Iosevka could be slab by default?

(thanks for such a beautiful and customizable font!)

**Comment by be5invis** [comment]
> Finally, perhaps mathbf in Iosevka could be slab by default?

`mathbf` directly derives from "normal" style so **NO** for sans-serif.

> A slab variant for C/c that includes serifs

I think we can make `C` / `c` grow serifs directly under Slab...
