### ISSUE TITLE
Suggestions for new motion-serif character variants... and more

### ISSUE THREAD

**Issue by NoxUltima** [be5invis/Iosevka#789]
- [x] The requested variant shape does not go too far away from the current design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] Some other monospace/programming fonts supported the requested variant. Provide images below.

<small>(This is my first GitHub post)</small>

I have grew fond of using Iosevka for a while now. I thought of some interesting but useful variants that could be added.

First, I'd like to suggest adding motion serifs to additional letters: b d g k q, to complete the motion serif set (so far there's h, m, n and p). The motion serif variant for g and q is the same as p, but reversed. This is Vivala Code:

![variants for b d g k q](https://www.smashingfonts.com/previews/11063.jpg)
![](https://d1ly52g9wjvbd2.cloudfront.net/img16/V/I/NMY_Vivala-Code-Regulara.png)
![](https://d1ly52g9wjvbd2.cloudfront.net/img16/V/I/NMY_Vivala-Code-Regulara1.png)

And a motion serif variant for a as well in Cascadia Code.

![Cascadia Code a](https://github.com/microsoft/cascadia-code/blob/main/images/cascadia-code.png?raw=true)

The capital letters L and Z can have serifs on the bottom right. Z could also have a serif on tbe top left too. Below is a sample of Gintronic:

![variants for L and Z](https://typography.guru/uploads/monthly_2019_04/GintronicSample.png.fd83763a49dfe1a2ef47853df939f0bc.png)

Capital Q can also have its tail going straight through the bottom, like in Dank Mono or Sweden Sans:

![Straight notch Q](https://miro.medium.com/max/875/1*ufUWiElDMPwDJ-f0oN0NBQ.png)

I hope this is enough variants. I appreciate your work and I'm glad to provide my own contributions and suggestions on this font :smile:

---

#### Bonuses (for consideration only)

I found this (Furtive Mono Code) in Behance a while back. I thought these would also be neat additions, if that's good enough.

Alternative curly y:

![](https://mir-s3-cdn-cf.behance.net/project_modules/fs/32181152149647.59071350b67be.png)

Alternate capital G, J, 1 (similar to Operator Mono) and asterisk \* (motion-serif a is also proposed above):

![](https://mir-s3-cdn-cf.behance.net/project_modules/fs/3fd22452149647.59071350b62ad.png)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/103488817-c17c2700-4dc4-11eb-9daa-559a74f8dd4c.png)
(Note the shape `d` **has** bottom-right serif, like that in `m`, `n`)

**Comment by NoxUltima** [comment]
Wow, so fast! Thanks :smiles:
