### ISSUE TITLE
want this symbol:⍟

### ISSUE THREAD

**Issue by chenjuntong** [be5invis/Iosevka#79]
I am using this theme and Iosevka for my zsh, but it doesn't work well.
https://github.com/bhilburn/powerlevel9k
![pic][1]
  [1]: http://ww4.sinaimg.cn/large/6ccda21fjw1f3f4w4boctj206201kglk.jpg

**Comment by chenjuntong** [comment]
Today I find that another zsh theme needs more symbols for GIT.It seems that these symbols are used frequently.
Thanks for your work. @be5invis 

ZSH_THEME_GIT_PROMPT_STASHED=' ⚑'
ZSH_THEME_GIT_PROMPT_DIVERGED=' ⚡'
ZSH_THEME_GIT_PROMPT_AHEAD=' ⬆'
ZSH_THEME_GIT_PROMPT_BEHIND=' ⬇'

**Comment by be5invis** [comment]
Consolidated to #81. Closed.
