### ISSUE TITLE
Black Rightwards Arrow

### ISSUE THREAD

**Issue by bitmappergit** [be5invis/Iosevka#792]
- The requested character is...
  - [ ] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [x] Symbol
- [ ] Some other monospace/programming fonts supported this character. Provide images below.

------

Hi! I've been using Iosevka to work with Agda and Cedille, and i noticed that ➡ is not supported by Iosevka, which Cedille uses for arrow types.

I would really appreciate the addition of it.

**Comment by be5invis** [comment]
`➡` (`U+27A1`) is already there. However it is also an Emoji, so maybe your text editor cannot assign it to Iosevka.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/104235855-6e305700-540a-11eb-9099-8195bc7d4949.png)

**Comment by bitmappergit** [comment]
Apologies, I got a little confused when looking it up, it's apparently supposed to be "HEAVY WIDE-HEADED RIGHTWARDS ARROW" with codepoint U+2794.
