### ISSUE TITLE
Sharper bend variant for some characters (inspired by IBM Plex Mono)

### ISSUE THREAD

**Issue by kauesena** [be5invis/Iosevka#795]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] Some other monospace/programming fonts supported the requested variant. Provide images below.

------

[IBM Plex Mono](https://github.com/IBM/plex) provides this design feature (as standard) in its italic version:
![image](https://user-images.githubusercontent.com/30255100/104788551-3b22f600-5771-11eb-8069-1c5a6d1e6f47.png)

**Comment by kauesena** [comment]
I forgot to add: wonderful work! Thank you very much!

**Comment by be5invis** [comment]
That's a large request, put to backlog for now.
