### ISSUE TITLE
IBM Plex Mono stylistic set

### ISSUE THREAD

**Issue by kauesena** [be5invis/Iosevka#796]
I suggest the addition of an IBM Plex Mono stylistic set alongside the other ones. For fans of IBM Plex Mono, it would be nice to have Iosevka with an IBM Plex flavour. 
![image](https://user-images.githubusercontent.com/30255100/104812678-b2dd3900-57e2-11eb-9515-6a9b8541a38d.png)

**Comment by alexeyten** [comment]
@be5invis  there is a typo `ss14` should be `ss15`
https://github.com/be5invis/Iosevka/commit/4486da078e8b07115527ce12851155f7551c9a76#diff-e66d60cd40145bdc9dab54ed635b06bd003cd10cf9a22f4c22b7fe482f2e428dR2647

**Comment by JimEBlevins** [comment]
### **Iosevka** `SS15` as a _Greek monospace_ typeface emulating **IBM Plex Mono**

Emulating the spirit of **IBM Plex Mono**  (but without its "high-g" turns), **Iosevka** with _stylistic set_ `ss15` is especially useful as a _Greek monospace_ font, which **IBM Plex Mono** lacks. 

As a bonus, **Iosevka** `ss15` handles not only _modern_ monotonic Greek but also _ancient_ polytonic Greek. 

[κῦδος](https://en.wiktionary.org/wiki/%CE%BA%E1%BF%A6%CE%B4%CE%BF%CF%82#Ancient_Greek)!
