### ISSUE TITLE
Customizer persistent storage

### ISSUE THREAD

**Issue by oovm** [be5invis/Iosevka#798]
[Customizer](https://typeof.net/Iosevka/customizer) cannot save the results of the last configuration.

I noticed that a url will be generated, but the result of this url is wrong and cannot be parsed losslessly.

Maybe we can write each option to `IndexedDB`, so that it can be stored persistently and facilitate the import and export of json configuration

**Comment by be5invis** [comment]
The URL is used to launch the customizer with some parameters initialized. It should be cleared after the initialization. As for persistence... maybe importing TOML directly?
