### ISSUE TITLE
Ligatures of == and === have glitch

### ISSUE THREAD

**Issue by Jeff11** [be5invis/Iosevka#799]
Font version 4.5.0, SS14

On MacOS 11.1 with Android Studio 4.1.1 the `==` and `===` symbols have a glitch. Antialiasing setting doesn't matter.

See line 8 of the screenshot for an example of `===`

![image](https://user-images.githubusercontent.com/7838820/104949285-00160200-59bf-11eb-9d5a-edca16f84280.png)

**Comment by Jeff11** [comment]
are also affected

**Comment by be5invis** [comment]
Looks like rounding error. Java has some quirks on handling text metrics.

**Comment by be5invis** [comment]
Resolve as duplicate of #594. It looks like JetBrains also did antialiasing wrong.
Closing.
