### ISSUE TITLE
Glyph proposal about 3,4,9

### ISSUE THREAD

**Issue by MadMaxChow** [be5invis/Iosevka#8]
Enhanced symbol of recognition and consistency of style, like:

![snip20150815_6](https://cloud.githubusercontent.com/assets/13810505/9289365/b36a0a54-439f-11e5-94b6-4748322de34b.png)

**Comment by Zhichao-Hong** [comment]
+1.  I liked the enhancement.  But it is more of personal taste.

**Comment by be5invis** [comment]
I do not think changing the shape of numbers is a good idea, but recently I made some neat fixes about them:
![image](https://cloud.githubusercontent.com/assets/240091/10711795/a680aedc-7ab9-11e5-8e65-de8e7e9523ca.png)

**Comment by be5invis** [comment]
With the latest changes about numbers, I think this issues can be closed.
