### ISSUE TITLE
Bottom part of certain letters get cut off

### ISSUE THREAD

**Issue by eizua** [be5invis/Iosevka#80]
In some text editors I use, the bottom part of certain letters ("g", "y", "p", etc.) get cut off because the space between each line of text is rendered too close. Here are some screenshots from editors Emacs, Vim, and Textadept:

Emacs: 
![emacs_snippet](https://cloud.githubusercontent.com/assets/19015730/14943477/1e188cc4-100d-11e6-8ca9-f78a57517624.png)

Vim:
![vim_snippet](https://cloud.githubusercontent.com/assets/19015730/14943480/34dd2712-100d-11e6-8562-5fdd1e5b350d.png)

Textadept:
![ta_snippet](https://cloud.githubusercontent.com/assets/19015730/14943484/43388dc4-100d-11e6-9ca9-1ea410240761.png)

Emacs renders the font correctly, but in Vim and Textadept, they get cut off. These are at font size 9.
If I increase it to 10 for Vim and Textadept, the problem goes away. However, the reason I use Iosevka Term is because it's thin enough to still be readable at smaller sizes - 10 is already too large for me.

These screenshots were taken from a machine running Ubuntu MATE 16.04, but I've experienced this issue even when it was still on 14.04. I can post my config files for these editors if necessary, but I'm not really doing anything special (other than the usual keybindings/plugin loading/colorscheme setting stuff).

Any thoughts on how this can be fixed (other than switching editors)? Thanks in advance!

**Comment by be5invis** [comment]
Rounding error related to line height I think.
Given that Iosevka is not designed for extremely low text size, you can try to build your variant with leading increased. (In `parameters.toml`, increase the `leading` parameter.)

**Comment by eizua** [comment]
Installed Node 6.0. Built FontForge, `ttfautohint` 1.5, `otfcc` 0.1.6 manually. Followed the steps provided [here](https://github.com/be5invis/Iosevka#building-from-source).
Using `make STYLE_COMMON=term DONTHINT=1` got me the following results:

Textadept:
![donthint-ta](https://cloud.githubusercontent.com/assets/19015730/14951181/a2ba44b4-1089-11e6-9f39-ce765f841691.png)

Vim:
![donthint-vim](https://cloud.githubusercontent.com/assets/19015730/14951191/b4daed7e-1089-11e6-826d-00cee20f6884.png)

Using `make STYLE_COMMON=term` with `leading` set to 1900 in `parameters.toml` got me the following:

Textadept:
![leading1900-ta](https://cloud.githubusercontent.com/assets/19015730/14949775/35c9be16-107f-11e6-9abd-57f7ac06ed80.png)

Vim:
![leading1900-vim](https://cloud.githubusercontent.com/assets/19015730/14949783/3ebd2b52-107f-11e6-9590-0ec2ad67925e.png)

The line height increase was at least evident on Vim, but the letters "g", "y", "j", etc. are still cut for some reason on both editors. Tried increasing it from 1250 to 1300, then 1500, then 1900, but no dice. :(

**Comment by be5invis** [comment]
@eizua I just added a `descenderPad` parameter to `parameters.toml` which pads the descender. You can try to increase this value to see whether this works.

**Comment by eizua** [comment]
@be5invis Setting `descenderPad` to 50 fixed it! I didn't even have to change `leading`'s value at all. As proof:

Vim:
![fixed-vim](https://cloud.githubusercontent.com/assets/19015730/14962527/dc695fcc-10d1-11e6-9047-9ac65e434894.png)

Textadept:
![fixed-ta](https://cloud.githubusercontent.com/assets/19015730/14962541/ebd88d20-10d1-11e6-8c50-eaa8011ea0bf.png)

Now I don't have to think about switching editors. Thanks a bunch!
