### ISSUE TITLE
Bug: Glitch with curly capital K/'%' | Feature Request: Straight variant for capital Æ, Slab-serif S

### ISSUE THREAD

**Issue by NoxUltima** [be5invis/Iosevka#800]
### Glitches with K and %

It appears that on a super-wide 600-650em font and a bold weight, the top diagonal of the K (curly variant) is a bit too thick.

The bottom diagonal appears to be glitching out, and it happens regardless of width.

![k](https://user-images.githubusercontent.com/16898444/105001823-50e33480-5a6b-11eb-8f85-39f3024e5759.png)

There's also some overlaps between where they join too...

![pls fix k](https://user-images.githubusercontent.com/16898444/105001838-56d91580-5a6b-11eb-81ef-f6f66a8376a3.png)

\[Update] The lines on default % are too wide, especially on thinner weights. (See below pic)

### Add straight variant for uppercase &AElig;, make it default

![curly variants](https://user-images.githubusercontent.com/16898444/105002314-031afc00-5a6c-11eb-973f-84e398c568fa.png)

So far, &AElig; is the only one that is left curly unlike the other characters with diagonal lines. It should have a straight variant as the default and get a variant selector.

### Two slabs on S/s

In Iosevka Slab, the letter S should have two serifs, one on both sides of the terminals, like in most slab-serif fonts. Currently it only has one on the top like C and G.

![](https://oxford-typography.hotglue.me/?development.head.144977079992)

Besides, Thanks for the excellent work though! Really enjoyed your font! 😄

---

* Your font version: (Release or git, version) 4.5
* Your font variant: Iosevka Curly/Extended
* Your operating system (name and version): Windows 10 Home
* Your application using Iosevka: N.A.

**Comment by be5invis** [comment]
Next time, please file one issue for one bug / feature request.

**Comment by NoxUltima** [comment]
Sure, thanks for the quick reply.
