### ISSUE TITLE
More visible math operators

### ISSUE THREAD

**Issue by kauesena** [be5invis/Iosevka#804]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] Some other monospace/programming fonts supported the requested variant. Provide images below.

After the possibility to cherry-pick symbols, for me, the biggest advantage of Iosevka for is its coverage of many mathematical symbols. However, some look oddly small and difficult to read depending on the context, such as `↦`,`⊂` and `∞`. I do believe it must be a challenge to design those characters for a monospace font, but somehow DejaVu Mono makes them appear less odd in contexts where the font is very small and they seem less small in comparison with other characters. 
![image](https://user-images.githubusercontent.com/30255100/105385356-07712180-5bf2-11eb-8349-c128baa9ba70.png)
Implementing bigger variants to those characters would be possible in Iosevka? Or the current mathematical glyphs are already as big as they can be?
Thank you once more for this already splendid font.

**Comment by nsemrau** [comment]
Instead of grafting on another set of slightly different versions of various glyphs, maybe a review to make the form of some mathematical glyphs bigger in general could take place?

**Comment by kauesena** [comment]
@be5invis Oh. I closed the issue by accident.

**Comment by kauesena** [comment]
>Maybe a review to make the form of some mathematical glyphs bigger in general could take place? Instead of grafting on another set of slightly different versions of various glyphs.

Or as you suggest. Replacing some of the mathematical glyphs altogether.

**Comment by be5invis** [comment]
I think larger `⊂` is doable. `↦` and `∞` are already wide in non-Terminal editions.

**Comment by kauesena** [comment]
Increasing `⊂` would already be excellent. And I'll give Iosevka extended a try.

**Comment by VladimirMarkelov** [comment]
My 2 cents: to me, from the picture above, Iosevka's variant is easier to understand with a quick glance. In DejaVu case, the symbol `⊂` is almost as big as `C` and it takes some time to understand that the string includes a mathematical symbol; in Iosevka case, I notice that there is a symbol that is less than any other, so I understand that a string contains something besides letters in no time.

**Comment by kauesena** [comment]
>In DejaVu case, the symbol ⊂ is almost as big as C and it takes some time to understand that the string includes a mathematical symbol

That is something to worry about if the way forward were replacing instead of creating a variant. I can, nonetheless, distinguish `C` and `c` from `⊂` rather easily, but I suppose it must be mostly due to the colour scheme. 
**Iosevka Extended**
![image](https://user-images.githubusercontent.com/30255100/105424011-44a2d700-5c25-11eb-9a1f-11d559aac147.png)


**DejaVu Mono**
![image](https://user-images.githubusercontent.com/30255100/105423756-e544c700-5c24-11eb-9ffb-97bcd7c1eca1.png)

**Comment by be5invis** [comment]
If we enlarge it to the same size as ∈ then it will look too like `c`:
![image](https://user-images.githubusercontent.com/240091/105434945-51b5cb00-5c11-11eb-946d-90b023572edf.png)

Reducing it a little looks better:
![image](https://user-images.githubusercontent.com/240091/105434632-c63c3a00-5c10-11eb-8f1a-86310dc95b1f.png)

**Comment by kauesena** [comment]
You are right. In the second image is the size a little greater than the
current one or is it the current one?

**Comment by kauesena** [comment]
I had read through email and not seen the commit referencing the issue.

**Comment by be5invis** [comment]
@kauesena Well they are both enlarged, the first image enlarged it more.
Since you are fine with the second option I'd like to close this issue as resolved.
