### ISSUE TITLE
Underlined O form for capital omega

### ISSUE THREAD

**Issue by thomaswuhoileong** [be5invis/Iosevka#805]
The capital letter omega is sometimes written as O with an underline (see https://en.wikipedia.org/wiki/File:Kos_citt%C3%A0,_piazza_eleftherias,_edificio_razionalista,_targa.JPG for an example). Although this form is probably used only in handwriting, it might be interesting to add this variant.

**Comment by be5invis** [comment]
This is very like out of scope. Please provide examples that other digital fonts, which are _not_ targeting historical representation, has this form.
