### ISSUE TITLE
Top motion serifs for A, B, D, E, F, P, R, Z, v, w, y, z

### ISSUE THREAD

**Issue by NoxUltima** [be5invis/Iosevka#806]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] Some other monospace/programming fonts supported the requested variant. Provide images below. 
(in brackets)

------

From #789 I brought out Z/z again as it currently has a **bottom** serif, so adding a motion serif on **top** will round it out.

<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/16898444/105448050-7a40d200-5cb0-11eb-8464-86a95c4143e7.png"></td>
<td><img src="https://user-images.githubusercontent.com/16898444/105448258-ef140c00-5cb0-11eb-8732-5af2f8c4f6e5.png"></td>
</tr>
</table>

I appreciate your work. Thank you so much!

**Comment by be5invis** [comment]
As I said in #800, please split your issue, one issue for one variant "kind".
CLOSING.

**Comment by NoxUltima** [comment]
I deeply apologize. Sorry for the trouble.
