### ISSUE TITLE
Consolidation of Symbol Requests

### ISSUE THREAD

**Issue by be5invis** [be5invis/Iosevka#81]
| ✓ | Ch. | Unicode | Name | Proposed Glyph Name |
| --- | --- | --- | --- | --- |
| |⋈|U+22C8| | |
| |⋉|U+22C9| | |
| |⋊|U+22CA| | |
| |⸘|U+2E18|Gnaborretni| |
| |⇊|U+21CA|Downwards Paired Arrows| |
| |⤤|U+2924|North East Arrow with Hook| |
| |↧|U+21A7|Downwards Arrow from Bar| |
|  | `➦` | U+27A6 | Heavy Curved Black Upwards and Rightwards Arrow | /uptorightarrowsymb |
|  | `⚙` | U+2699 | Gear | /gear |
|  | `🌡` | U+1F321 | Thermometer | /thermometer |
|  | `⌛` | U+231B | Hourglass | /hourglass |
|  |      |    | Half brackets and integrals | |
| 1.13.3 |◐|U+25D0|Circle with Left Half Black| |
| 1.13.3 |◑|U+25D1|Circle with Right Half Black| |
| 1.13.3  |◒|U+25D2|Circle with Lower Half Black| |
| 1.13.3  |◓|U+25D3|Circle with Upper Half Black| |
| 1.13.3  |◔|U+25D4|Circle with Upper Right Quadrant Black| |
| 1.13.3  |◕|U+25D5|Circle with All But Upper Left Quadrant Black| |
| 1.11.4 | `❯`| U+276F | HEAVY RIGHT-POINTING ANGLE QUOTATION MARK ORNAMENT| (auto) |
| 1.10.2 | ` ` | Various | APL Symbols | (no name assignment) |
| 1.10.1 | `‽` | U+203D | Interrobang | /interrobang |
| 1.9.1 | `℃` | U+2103 | Degree Celsius | /degC |
| 1.9.1 | `✚` | U+271A | Heavy Greek Cross | /heavygreekcross |
| 1.9.1 | `✖` | U+2716 | Heavy Multiplication X | /heavycross |
| 1.9.1 | `⬡` | U+2B21 | White Hexagon | /whitehexagon |
| 1.9.1 | `⬢` | U+2B22 | Black Hexagon | /blackhexagon |
| 1.9.1 | `⬣` | U+2B23 | Horizontal Black Hexagon | /hblackhexagon |
| 1.8.5 | `⚑` | U+2691 | Black Flag | /blackflag |
| 1.8.5 | `⚡` | U+26A1 | High Voltage Sign | /bolt |
| 1.8.5 | `✘` | U+2718 | Heavy Ballot X | /heavyballotcross |
| 1.14.2 | `⬆` | U+2B06 | Upward Black Arrow | /uparrowsymb |
| 1.14.2 | `⬇` | U+2B07 | Downward Black Arrow | /downarrowsymb |

**Comment by be5invis** [comment]
Done `/blackflag` and `/heavyballotcross`.

**Comment by geier** [comment]
I would love to see ✚ 'HEAVY GREEK CROSS' (U+271A) in Iosevka, several git/scm prompts for shells use it to signal that files have changed (example: https://github.com/olivierverdier/zsh-git-prompt).

**Comment by be5invis** [comment]
Done /bolt and /circlestar

**Comment by geier** [comment]
Awesome, thanks! In case we ever meet face to face, I'd love to invite you to a beer or two (or other beverages of your choice)!

**Comment by be5invis** [comment]
@geier well you may have to pay a lot of plane ticket cost

**Comment by megapctr** [comment]
Hi! I'd like to request a [hourglass character (u231b)](http://www.fileformat.info/info/unicode/char/231b/index.htm). I use it to indicate background jobs in my shell prompt.

**Comment by AndydeCleyre** [comment]
Hi,

For that rare but celebrated occasion when someone uses an [interrobang](https://en.wikipedia.org/wiki/Interrobang) (‽) (U+203D), it would be nice to have one in this amazing font. There's also a corresponding "inverted interrobang" or "gnaborretni" (⸘) (U+2E18).

The simple and straightforward route is to simply overlap the `!` and `?`, but in my opinion that too closely resembles a `P` or `D` or simply a smudged question mark to be semantically obvious at a glance. An image [search](https://www.google.com/search?q=interrobang&tbm=isch) indicates that there is some room for alternatives, such as these demonstrate:

- question mark with hat

![screenshot_20160824_171309](https://cloud.githubusercontent.com/assets/1787385/17948286/28b86378-6a1e-11e6-8be6-63db2d893f69.png)

- shared dot, angled paths

![2886229996_147ec96702](https://cloud.githubusercontent.com/assets/1787385/17948338/6d53ea34-6a1e-11e6-8d2a-c2f7720caf8f.jpg)

![hbkbumyh](https://cloud.githubusercontent.com/assets/1787385/17948381/ac7ad600-6a1e-11e6-829a-0304ab4ff025.jpeg)

![interrobang](https://cloud.githubusercontent.com/assets/1787385/17948388/b261b7dc-6a1e-11e6-9fb8-24ce40d022bb.jpg)

- layered interleaving

![screenshot_20160824_171852](https://cloud.githubusercontent.com/assets/1787385/17948451/ededfde2-6a1e-11e6-960a-077bb8db5e7b.png)

![screenshot_20160824_171918](https://cloud.githubusercontent.com/assets/1787385/17948455/f1c39008-6a1e-11e6-9928-35ddfa953b47.png)

**Comment by geier** [comment]
I have some more symbol suggestions:
 * inbox tray (U+1F4E5) 📥                                                                                                                      
 * envelope (U+2709) ✉                                                                                                                      
 * return symbol (U+23CE) ⏎                                                                                                                      
 * paperclip (U+1F4CE) 📎                                                                                                                      
 * page with curl (U+1F4C3) 📃                                                                                                                      
 * ant (U+1F41C)   🐜                                                                                                                      
 * lock (U+1F512) 🔒                                                                                                                      
 * black universal recycling symbol (U+267B) ♻  

I use those as [tags in alot](https://github.com/geier/dotfiles/blob/master/.config/alot/config), a terminal based email program.

Also, I'd like to see any global symbol, such as GLOBE WITH MERIDIANS (U+1F310),  EARTH GLOBE EUROPE-AFRICA (U+1F30D) or EARTH GLOBE ASIA-AUSTRALIA (U+1F30F), which I'd like to use in a calendar program as the symbol for 'change timezone'.

**Comment by demhydraz** [comment]
I'd like to see support for mathematical capital double-struck letters, i.e. things from U+1D538 to U+1D550 along with U+2115 ℕ and U+2124 ℤ.

**Comment by be5invis** [comment]
@geier @demhydraz 
Perhaps I should initiate a new project called “Imposed Iosevka” and provide a mechanism to add icon-like symbols into Iosevka, using the script in ryanoasis/nerd-fonts#83.

**Comment by be5invis** [comment]
Req: half-block triangles (◣◤◥◢)

**Comment by fitojb** [comment]
I would like to request the ISO/IEC/IEEE power symbols, [in Unicode since version 9.0](http://www.unicode.org/L2/L2014/14009r-power-symbol.pdf):

```
Power          U+23FB   ⏻
Power on/off   U+23FC   ⏼
Power on       U+23FD   ⏽
Power off      U+2B58   ⭘
Sleep mode     U+23FE   ⏾
```

**Comment by jxy** [comment]
Can you please add some essential APL related symbols?
```
0x2218    ∘   RING OPERATOR
0x22a2    ⊢   RIGHT TACK
0x22a3    ⊣   LEFT TACK
0x22a4    ⊤   DOWN TACK
0x22a5    ⊥   UP TACK
0x22c6    *   STAR OPERATOR
0x22f8    ⋸   ELEMENT OF WITH UNDERBAR
0x2336    ⌶   APL FUNCTIONAL SYMBOL I-BEAM
0x2337    ⌷   APL FUNCTIONAL SYMBOL SQUISH QUAD
0x2339    ⌹   APL FUNCTIONAL SYMBOL QUAD DIVIDE
0x233d    ⌽   APL FUNCTIONAL SYMBOL CIRCLE STILE
0x233f    ⌿   APL FUNCTIONAL SYMBOL SLASH BAR
0x2340    ⍀   APL FUNCTIONAL SYMBOL BACKSLASH BAR
0x2349    ⍉   APL FUNCTIONAL SYMBOL CIRCLE BACKSLASH
0x234b    ⍋   APL FUNCTIONAL SYMBOL DELTA STILE
0x234e    ⍎   APL FUNCTIONAL SYMBOL DOWN TACK JOT
0x2352    ⍒   APL FUNCTIONAL SYMBOL DEL STILE
0x2355    ⍕   APL FUNCTIONAL SYMBOL UP TACK JOT
0x2359    ⍙   APL FUNCTIONAL SYMBOL DELTA UNDERBAR
0x235d    ⍝   APL FUNCTIONAL SYMBOL UP SHOE JOT
0x235e    ⍞   APL FUNCTIONAL SYMBOL QUOTE QUAD
0x2360    ⍠   APL FUNCTIONAL SYMBOL QUAD COLON
0x2363    ⍣   APL FUNCTIONAL SYMBOL STAR DIAERESIS
0x2364    ⍤   APL FUNCTIONAL SYMBOL JOT DIAERESIS
0x2365    ⍥   APL FUNCTIONAL SYMBOL CIRCLE DIAERESIS
0x2368    ⍨   APL FUNCTIONAL SYMBOL TILDE DIAERESIS
0x236a    ⍪   APL FUNCTIONAL SYMBOL COMMA BAR
0x236b    ⍫   APL FUNCTIONAL SYMBOL DEL TILDE
0x236c    ⍬   APL FUNCTIONAL SYMBOL ZILDE
0x2371    ⍱   APL FUNCTIONAL SYMBOL DOWN CARET TILDE
0x2372    ⍲   APL FUNCTIONAL SYMBOL UP CARET TILDE
0x2373    ⍳   APL FUNCTIONAL SYMBOL IOTA
0x2374    ⍴   APL FUNCTIONAL SYMBOL RHO
0x2375    ⍵   APL FUNCTIONAL SYMBOL OMEGA
0x2376    ⍶   APL FUNCTIONAL SYMBOL ALPHA UNDERBAR
0x2377    ⍷   APL FUNCTIONAL SYMBOL EPSILON UNDERBAR
0x2378    ⍸   APL FUNCTIONAL SYMBOL IOTA UNDERBAR
0x2379    ⍹   APL FUNCTIONAL SYMBOL OMEGA UNDERBAR
0x237a    ⍺   APL FUNCTIONAL SYMBOL ALPHA
0x2395    ⎕   APL FUNCTIONAL SYMBOL QUAD
0x25ca    ◊   LOZENGE
```

**Comment by robertgzr** [comment]
How is #90 coming along? I would love to help out a little with these requests.

**Comment by leiserfg** [comment]
I love iosevka but i think that if a less esoteric language where used for making it (js or at most a classical lisp), more people could help to add glyphs.

**Comment by be5invis** [comment]
@leiserfg You can provide vectors...
I do not have much time on this project currently, maybe I should really make an API now.

**Comment by leiserfg** [comment]
A way to test the added glyph without needing to build the full typography can help too. "Let's do Iosevka awesome again" :D

**Comment by be5invis** [comment]
@leiserfg Well, there is a proposed font called *WUGNER* uses a publisher-subscriber pattern that allows us for partial building, but Iosevka is still made in the traditional way :(

**Comment by be5invis** [comment]
@jxy Will be completely done in 1.10.2 :)

**Comment by MarisaKirisame** [comment]
http://lucacardelli.name/indexArtifacts.html
Licsx.zip in Font

**Comment by AndydeCleyre** [comment]
Still in love with this font, thanks.

The interrobang looks great. It would be nice to have a matching inverted interrobang (⸘) (U+2E18).

**Comment by jxy** [comment]
Thanks for the great font.  May I request for a couple of more symbols?
```
0x220a    ∊    SMALL ELEMENT OF
0x25ca    ◊    LOZENGE
```
In addition, can we have the star symbol and the circle at the same height and same size respectively in the following symbols:
```
0x233d    ⌽    APL FUNCTIONAL SYMBOL CIRCLE STILE
0x2349    ⍉    APL FUNCTIONAL SYMBOL CIRCLE BACKSLASH
0x25cb    ○    WHITE CIRCLE
0x2365    ⍥    APL FUNCTIONAL SYMBOL CIRCLE DIAERESIS
0x2296    ⊖    CIRCLED MINUS
0x235f    ⍟    APL FUNCTIONAL SYMBOL CIRCLE STAR
0x002a    *    ASTERISK
0x22c6    ⋆    STAR OPERATOR
0x2363    ⍣    APL FUNCTIONAL SYMBOL STAR DIAERESIS
```

**Comment by therockmandolinist** [comment]
If/when you get the time, it would also be nice to have:
```
U+275A ❚ Heavy Vertical Bar
U+2759 ❙ Medium Vertical Bar
U+2758 ❘ Light Vertical bar
```
And maybe
```
U+25A0 ■ Black Square
U+25AA ▪ Black Small Square
U+2B1D ⬝ Black Very Small Square
```
Though I feel more strongly about the bars, since there's way more variants of squares and I'm not sure which would be best to implement.

**Comment by skalyan91** [comment]
I would like to see

`U2237 ∷ Proportion`

as this gets used a lot in Haskell font-lock mode in Emacs.

Other symbols from the "Mathematical Operators" block would be nice, but not as essential for me.

**Comment by benoliver999** [comment]
I'd like to request

`U+2630 ☰ Trigram for Heaven`

Pretty please!

**Comment by AndydeCleyre** [comment]
Hi,

Just a reminder:

> There's also a corresponding "inverted interrobang" or "gnaborretni" (⸘) (U+2E18).

I expect it will be simple, since interrobang is already there now, but I've never done kerning before, so `¯\_(ツ)_/¯`.

**Comment by AndydeCleyre** [comment]
Ch.|Unicode|Name
---|-------|----
⸘|U+2E18|Gnaborretni
⇊|U+21CA|Downwards Paired Arrows
⤤|U+2924|North East Arrow with Hook
↧|U+21A7|Downwards Arrow from Bar

**Comment by AndydeCleyre** [comment]
Ch.|Unicode|Name
---|-------|----
◐|U+25D0|Circle with Left Half Black
◑|U+25D1|Circle with Right Half Black
◒|U+25D2|Circle with Lower Half Black
◓|U+25D3|Circle with Upper Half Black
◔|U+25D4|Circle with Upper Right Quadrant Black
◕|U+25D5|Circle with All But Upper Left Quadrant Black

**Comment by be5invis** [comment]
Added.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Andy Kluger<mailto:notifications@github.com>
发送时间: 2017年7月16日 2:21
收件人: be5invis/Iosevka<mailto:Iosevka@noreply.github.com>
抄送: Belleve Invis<mailto:be5invis@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [be5invis/Iosevka] Consolidation of Symbol Requests (#81)

Ch.

Unicode

Name

◐

U+25D0

Circle with Left Half Black

◑

U+25D1

Circle with Right Half Black

◒

U+25D2

Circle with Lower Half Black

◓

U+25D3

Circle with Upper Half Black

◔

U+25D4

Circle with Upper Right Quadrant Black

◕

U+25D5

Circle with All But Upper Left Quadrant Black

**Comment by therockmandolinist** [comment]
These would be nice:

| Ch. | Unicode | Name                      |
|-----|---------|---------------------------|
| ↰   | U+021B0 | Up Arrow With Tip Left    |
| ↱   | U+021B1 | Up Arrow With Tip Right   |
| ↲   | U+021B2 | Down Arrow With Tip Left  |
| ↳   | U+021B3 | Down Arrow With Tip right |

**Comment by zhaojinxiang** [comment]
lack of the char '⏎ ' 
⏎ | return symbol (U+23CE)

**Comment by zhaojinxiang** [comment]
Ch. | Unicode | Name
-- | -- | --
⏎ | U+23CE | Return Symbol
⋈ | U+22C8 | 1.Bowtie 2.Natural Join
⋉ | U+22C9 | Left Normal Factor Semidirect Product (LaTeX: `\ltimes`)
⋊ | U+22CA | Right Normal Factor Semidirect Product (LaTeX: `\rtimes`)

**Comment by jbaum98** [comment]
Would it be possible to add mathematical blackboard characters?

| Ch. | Unicode | Name                                 |
|-----|---------|--------------------------------------|
| 𝔸   | U+1D538 | Mathematical Double-Struck Capital A |
| 𝔹   | U+1D539 | Mathematical Double-Struck Capital B |
| ℂ   | U+2102  | Double-Struck Capital C              |
| 𝔻   | U+1D53B | Mathematical Double-Struck Capital D |
| 𝔼   | U+1D53C | Mathematical Double-Struck Capital E |
| 𝔽   | U+1D53D | Mathematical Double-Struck Capital F |
| 𝔾   | U+1D53E | Mathematical Double-Struck Capital G |
| ℍ   | U+210D  | Double-Struck Capital H              |
| 𝕀   | U+1D540 | Mathematical Double-Struck Capital I |
| 𝕁   | U+1D541 | Mathematical Double-Struck Capital J |
| 𝕂   | U+1D542 | Mathematical Double-Struck Capital K |
| 𝕃   | U+1D543 | Mathematical Double-Struck Capital L |
| 𝕄   | U+1D544 | Mathematical Double-Struck Capital M |
| ℕ   | U+2115  | Double-Struck Capital N              |
| 𝕆   | U+1D546 | Mathematical Double-Struck Capital O |
| ℙ   | U+2119  | Double-Struck Capital P              |
| ℚ   | U+211A  | Double-Struck Capital Q              |
| ℝ   | U+211D  | Double-Struck Capital R              |
| 𝕊   | U+1D54A | Mathematical Double-Struck Capital S |
| 𝕋   | U+1D54B | Mathematical Double-Struck Capital T |
| 𝕌   | U+1D54C | Mathematical Double-Struck Capital U |
| 𝕍   | U+1D54D | Mathematical Double-Struck Capital V |
| 𝕎   | U+1D54E | Mathematical Double-Struck Capital W |
| 𝕏   | U+1D54F | Mathematical Double-Struck Capital X |
| 𝕐   | U+1D550 | Mathematical Double-Struck Capital Y |
| ℤ   | U+2124  | Mathematical Double-Struck Capital Z |

Also, to me it makes sense to add the same glyphs for the characters in the Letterlike Symbols block to the blank spots in the Mathematical Alphanumeric Symbols. For example, I think we should have the same glyph at U+2102 and at U+1D53A.

**Comment by dragonJACson** [comment]
Ch. | Unicode | Name
-- | -- | --
⇠ | U+21e0 | Leftwards Dashed Arrow
⇡| U+21e1 | Upwards Dashed Arrow
⇢| U+21e2 | Rightwards Dashed Arrow
⇣| U+21e3 | Downwards Dashed Arrow

**Comment by sergeevabc** [comment]
“Thin triangle”, please. Consolas has one as follows.

![](https://pli.io/421JO.png)

**Comment by be5invis** [comment]
@sergeevabc @dieggsy  Added in 1.14.2

**Comment by madbence** [comment]
`U+2630 ☰ Trigram for Heaven` would be nice, it's used by [`airline`](https://github.com/vim-airline/vim-airline/blob/5a065e8b822fd127e90bb9c8217cb17f1aad2095/autoload/airline/init.vim#L87) in `vim`!

**Comment by 4e6** [comment]
Request for `➜` [heavy round-tipped rightwards arrow (U+279C)](http://graphemica.com/%E2%9E%9C)
It is used in some of the fish shell prompts, for example in [robbyrussel](https://github.com/fish-shell/fish-shell/blob/376a4eca58fd0c16545548c4c4b87569521eeccc/share/tools/web_config/sample_prompts/robbyrussell.fish#L71)

**Comment by sharpjs** [comment]
I would _love_ a `U+002A * Asterisk` variant that is six-pointed, as in Menlo.

Iosevka with all the Menlo variants is my favourite font.

**Comment by skalyan91** [comment]
I would like `U+2016 ‖ Double Vertical Line` (which is used in IPA to indicate an intonational boundary), as well as the following dingbats that are used by Emacs Org mode for section headers:
```
U+2738 ✸ Heavy eight pointed rectilinear black star
U+273F ✿ Black florette
```

**Comment by Wulfsta** [comment]
I would like to second the request for blackboard bold characters that @jbaum98 suggested.

**Comment by lshoravi** [comment]
I'd love a c with overhang, like this:

![image](https://user-images.githubusercontent.com/42211142/46012169-9d4f1d00-c0c8-11e8-91c0-5c51f133d546.png)

**Comment by twse** [comment]
I would like to request the additions of some Abkhazian characters found in PF DIN Mono Pro.

**Comment by van-de-bugger** [comment]
I would like to have U+23CF EJECT SYMBOL. It is used by perl6 (rakudo) in error messages to report error position in the source.

**Comment by johnfraney** [comment]
For Python developers who use [pipenv](https://pipenv.readthedocs.io/en/latest/), it would be nice to have `U+1F40D 🐍 SNAKE` since it's shown during `pipenv install`.

**Comment by be5invis** [comment]
@johnfraney 
To add Emoji support I need a serious designer... It should be better handled using font fallback (for Conhost, see https://github.com/Microsoft/console/issues/190)

**Comment by johnfraney** [comment]
@be5invis I did some more digging into fallback fonts and emoji support. After installing [`noto-fonts-emoji`](https://www.archlinux.org/packages/extra/any/noto-fonts-emoji/) I'm able to see the snake (🐍) in my terminal. Thanks very much for this font!

**Comment by casheera** [comment]
Hi. Seems "Vertical Ellipsis" (U+22EE) is missed

**Comment by casheera** [comment]
And also would be nice to have Julia's ligature "<:"

**Comment by danipozo** [comment]
I would like to second @tpapp's request for mathematical alphanumerical symbols, and I would love to see mathematical symbols added in general.

**Comment by be5invis** [comment]
I'd like to close this issue now.
For further character / symbol requests, please open separate issues.
