### ISSUE TITLE
Add all lowercase variants of u to the capital

### ISSUE THREAD

**Issue by NoxUltima** [be5invis/Iosevka#811]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] Some other monospace/programming fonts supported the requested variant. Provide images below.

------

![U](https://user-images.githubusercontent.com/16898444/105450427-66e43580-5cb5-11eb-98f3-0d187e4f502b.png)

**Comment by pv4** [comment]
Fixing this issue could you please make ALL the variants of lowercase `u` be available for the uppercase one (including `toothless`/`tailed` variants as well as the ones requested in #813)? I'd personally like to use `toothless-corner` variant for the uppercase `u`.
