### ISSUE TITLE
capital-r=curly leg upper end is too high

### ISSUE THREAD

**Issue by pv4** [be5invis/Iosevka#816]
Reproducable only in `slab` variant, both `upright` and `italic`. `sans` is not affected. Notable on at least `thin`, `regular` and `heavy` (in different degree), not checked another weights. The attached picture contains `thin` and `heavy`.

Version: dev branch commit "Add double-v and asymmetric variants of `W` and `w` (#812)." (bc5523f31287dbf555b7a58b41d44cdbb10e203a).

![image](https://user-images.githubusercontent.com/2502094/105611627-75227680-5dc7-11eb-9ffd-07ec8a1efd42.png)

**Comment by be5invis** [comment]
Fixed in Dev
