### ISSUE TITLE
capital-u=toothless-corner-motion-serifed has right top serif

### ISSUE THREAD

**Issue by pv4** [be5invis/Iosevka#817]
In `toothless-corner-motion-serifed` variant the uppercase `u` has a serif at the top right while the lowercase `u` does not have it (as well as `v` and `w`).

Is it a bug or an expected behavior?

Version: dev branch commit "Add double-v and asymmetric variants of `W` and `w` (#812)." (bc5523f31287dbf555b7a58b41d44cdbb10e203a).

![image](https://user-images.githubusercontent.com/2502094/105611898-4b6a4f00-5dc9-11eb-96a1-259a2cb1fc33.png)

**Comment by be5invis** [comment]
Then I will give you both.
