### ISSUE TITLE
Motion serifs for H, K, M, N, X, x, Y, inspired by Museo

### ISSUE THREAD

**Issue by NoxUltima** [be5invis/Iosevka#818]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] Some other monospace/programming fonts supported the requested variant. Provide images below.

------

This is a continuation of my previous issue #806, to add motion serifs to letters with diagonal and horizontal lines.

![H, K, M, N, X, Y](https://user-images.githubusercontent.com/16898444/105619689-1c3af880-5e30-11eb-84d8-ad0c98998cba.png)

**Comment by NoxUltima** [comment]
Temporarily closing as still work in progress

**Comment by be5invis** [comment]
@NoxUltima I am working on this.

**Comment by NoxUltima** [comment]
Thanks so much! :smile:
