### ISSUE TITLE
Slanted 5 like Helvetica or Futura

### ISSUE THREAD

**Issue by NoxUltima** [be5invis/Iosevka#820]
- [x] The requested variant shape does not go too far away from Iosevka's design.
  - [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
  - [x] Some other monospace/programming fonts supported the requested variant. Provide images below.
  
![image](https://user-images.githubusercontent.com/16898444/105651316-7d76d080-5ef1-11eb-82ae-22de1b3bb828.png)

**Comment by NoxUltima** [comment]
To justify, number 5 is the only variant without a selector, and I've seen the slanted 5 in many other sans serif fonts such as Helvetica and Futura (the vertical line connecting the 5 to the bowl is **quite** slanted). It's not necessarily _that_ slanted, though the slant is more pronounced in Futura.

**Comment by pv4** [comment]
@be5invis
Though the variant implemented differs very little from the upright one, it looks much, much more beautiful! This is the case where a little difference makes huge result. Thanks!
