### ISSUE TITLE
Capital U (cv18) variants not displaying properly in README

### ISSUE THREAD

**Issue by NoxUltima** [be5invis/Iosevka#825]
Describe your problem here. Provide pictures and files if necessary.

---

A mistake in the picture in `README.md` - all the capital U variants in `cv18` appear to be the same glyph - a lowercase `u` instead.

![](https://github.com/be5invis/Iosevka/raw/dev/images/charvars.png)

Anyway thanks for the font!

**Comment by be5invis** [comment]
Fixed in dev. Closing.
