### ISSUE TITLE
`make webfonts` tries copying wrong css file

### ISSUE THREAD

**Issue by cobalamin** [be5invis/Iosevka#83]
Running `make webfonts` fails on the step of copying the css files:

```
make[1]: *** No rule to make target 'webfont-csses/01.iosevka.css', needed by 'dist/webfonts/01.iosevka.css'.  Stop.
make[1]: Leaving directory '/home/chipf0rk/dev/lib/Iosevka'
makefile:62: recipe for target 'webfonts-default' failed
```

As one can see in the repo, this file does indeed not exist: https://github.com/be5invis/Iosevka/tree/master/webfont-csses
And I can't see it being generated anywhere, so I'm guessing either the Makefile or the filename of the css should be amended to fix this.

Relevant lines in `onegroup.mk`: https://github.com/be5invis/Iosevka/blob/4fa5176ca9c9a4cb71423a4ea493b30a7b2a4bb8/onegroup.mk#L147-L149

Not a biggie of course, the important make steps run fine, but still, it fails at the moment :)

**Comment by be5invis** [comment]
@cobalamin I think the latest update in `master` fixes this.

**Comment by be5invis** [comment]
@cobalamin Does it work?

**Comment by cobalamin** [comment]
I'll test it later today, the setup for building was too hard to redo it on a different machine ;)

**Comment by cobalamin** [comment]
Well, mostly. But you should update the README since the make command seems to be `make webfont-pkg` now. And for Iosevka Slab, I get nothing in the webfonts directory at all now.

**Comment by be5invis** [comment]
@cobalamin The `webfont-pkg` only makes the web font package for one "group" (sans-serif now). I added a `webfonts` target to build web fonts for both sans-serif and slab-serif. You can checkout the latest commit.

**Comment by cobalamin** [comment]
Works fine now, thank you for your work :) I love this font, so I need the webfonts so I can use it on my website :D

I said that because before opening this issue, `make webfonts` worked (up until the CSS problem), and then after the first response by you, it didn't exist anymore. It's however mentioned as a command here: https://github.com/be5invis/Iosevka/blob/master/README.md#building-the-web-font
So I guess it behaves as before (or rather, as intended) now, right? Then this can be closed.

**Comment by be5invis** [comment]
Yes it was, but I changed the directory name in 1.8.3 so it does not work until the recent fix.
Closed.
