### ISSUE TITLE
Clarified information on the Releases tab?

### ISSUE THREAD

**Issue by hl2guide** [be5invis/Iosevka#836]
**Is your feature request related to a problem? Please describe.**
Please provide clearer instructions on the **releases** tab on GitHub.

**Describe the solution you'd like**

Could you please clarify some of the terms you have used on the releases tab?

- What's the difference between Super-TTC and TTC?
- What's a TTF and when should it be used?
- What's an unhinted/hinted font and when should it be used?
- What's a WebFont and when should it be used?

_I know some of the above personally but your awesome font should have enough info for
users not to pick the wrong option._

**Comment by barrosfelipe** [comment]
Came here looking for the same information. For such an awesome release write-up, more information on the above points is surely missing.

All of them, but especially @hl2guide points 1, 2 and 3.
