### ISSUE TITLE
Add true motion serifs to C/c, G and S/s for Sans as well, like Recursive Mono

### ISSUE THREAD

**Issue by NoxUltima** [be5invis/Iosevka#837]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] Some other monospace/programming fonts supported the requested variant. Provide images below.

------

Following issue #822, there has already been an addition of ~~motion~~-serifed variants for `S`/`s`.

I would consider adding "true" motion serifs to `Cc`, `G` and `Ss` as well (top or both ends in `Ss`). This means a new type of serif for curved shapes.

Here's Recursive Mono which shows what I mean:

![C](https://user-images.githubusercontent.com/16898444/105812217-b776ce00-5fe8-11eb-990e-a09d9e5eca21.png)
![C-1](https://user-images.githubusercontent.com/16898444/105812219-b8a7fb00-5fe8-11eb-995e-e1e26f296509.png)

Thank you so much!

**Comment by be5invis** [comment]
Oh, finally, all letters have variants 🏆

**Comment by be5invis** [comment]
(And I don't want to grow variants for `O`/`o`, as changing its shape will influence too many letters: `e`, `b`, `p`, ......)

**Comment by NoxUltima** [comment]
I'm still preparing the image... wait up
Don't do o pls it'll wreck everything 😆

**Comment by alexeyten** [comment]
With this implemented I'd like to have option to set different styles for Latin `C/c` and Cyrillic `С/с` (es) #274

**Comment by be5invis** [comment]
@alexeyten This is out of scope. They Latin `C` and Cyrillic `С` **are supposed to look the same**. If you really want to differentiate, you could build two variants, subset them individually, and combine them together.
