### ISSUE TITLE
N with diagonal going to the middle, like Pragmata Pro

### ISSUE THREAD

**Issue by NoxUltima** [be5invis/Iosevka#838]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] Some other monospace/programming fonts supported the requested variant. Provide images below.

------

![](https://miro.medium.com/max/3168/1*3HVG0i3CBHS8IorGEe5c9A.png)

**Comment by be5invis** [comment]
I hope this is the last set you added. I still wants to keep some designs consistency across the variants for Iosevka, rather than making it a “super font” that “contains everything”.

**Comment by NoxUltima** [comment]
Yeah sure, thanks! That was a lot though
