### ISSUE TITLE
以后发布能提供一个集合打包下载么

### ISSUE THREAD

**Issue by catcat520** [be5invis/Iosevka#84]
现在有10种字体，每次点击下载很累

不知道以后会不会增加到 100种字体，那样每次点击下载就要几个小时了

**Comment by yoonhakcher** [comment]
同意。
下载列表看着都眼花了

**Comment by be5invis** [comment]
Some packages are conflict to others, therefore I do not think the “all-in-one” package is unfeasible.
下载页面中的包有一些是相互冲突的，我不认为「all-in-one」可行。

**Comment by catcat520** [comment]
![2016-05-07_144630](https://cloud.githubusercontent.com/assets/9632762/15090697/e61e79be-1462-11e6-9b25-f4a39ea87d69.gif)
这样 然后打包一个 7z 就ok了

**Comment by be5invis** [comment]
@catcat520 冲突的部分不会打包到一起，所以还是拆成三个

**Comment by be5invis** [comment]
Included in 1.8.6. Closed.
