### ISSUE TITLE
Spaceship git status (⇡! ) display incorrect

### ISSUE THREAD

**Issue by dinhquochan** [be5invis/Iosevka#844]
Iosevka:
<img width="1192" alt="Screen Shot 2021-01-28 at 1 13 42 AM" src="https://user-images.githubusercontent.com/9979458/106034931-19792580-6106-11eb-909b-55e38f85bc96.png">

MonoLisa:
<img width="1192" alt="Screen Shot 2021-01-28 at 1 13 13 AM" src="https://user-images.githubusercontent.com/9979458/106034945-1da54300-6106-11eb-89d9-e5883b3ee150.png">

* Your font version: 5.0.0-beta.1
* Your font variant: Iosevka
* Your operating system (name and version): macOS 11.1
* Your application using Iosevka: iTerm2, Alacritty, Terminal.app

**Comment by dinhquochan** [comment]
Iosevka Term is perfect:

**Comment by be5invis** [comment]
Close as by design. Arrows are designed to be wide in Iosevka but narrow in Iosevka Term.
