### ISSUE TITLE
Duplicate Ruble sign (U+20BD) to U+20CF

### ISSUE THREAD

**Issue by VladWinner** [be5invis/Iosevka#845]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [ ] Some other monospace/programming fonts supported the requested variant. Provide images below.

------

Before the official Unicode consortium allocation of the glyph under the ruble sign (2014), some sites and software used the unassigned glyph U+20CF to draw the ruble sign, its absence in this font still breaks the display in some cases (because officially there is an unassigned space and not all fonts add this workaround, for the most part only Russian font studios). It would be nice to keep this workaround working, and remove ruble sign from U+20CF only in future when a new sign appears on the unassigned glyph (which may take decades, because of this is latest currency glyph and there is many other unassigned glyphs for future currencies). The problem will probably seem irrelevant for this monospaced font, but given the large glyph coverage, it would be good to be able to provide the greatest compatibility in all situations.

Samples:
[Russian article](https://habr.com/ru/post/122191/#post-content-body:~:text=В%20шрифтах%20PT) about a workaround for the ruble sign, June 2011 (Yandex translation to English)
![image](https://user-images.githubusercontent.com/13555921/106091427-79d78980-613d-11eb-914f-c0c0957de8f4.png)

Partial (system?) fallback ­­­— for italic (Telegram Desktop app, Windows 10, embedded Open Sans font)
![image](https://user-images.githubusercontent.com/13555921/106090867-3e888b00-613c-11eb-9aa6-c308f59cfef1.png)

Some modern sites still use this symbol via U+20CF. However, glyph only works directly on the sites, when "PT Sans for web" is embedded
![image](https://user-images.githubusercontent.com/13555921/106092648-c58b3280-613f-11eb-9fa8-03b6b117863a.png)![image](https://user-images.githubusercontent.com/13555921/106095807-7a741e00-6145-11eb-87fb-60ed0f751419.png)

**Comment by be5invis** [comment]
I do not see any other programming font covers U+20CF. It looks like only PT Sans/Serif did this.

**Comment by VladWinner** [comment]
This substitution was cut out of many fonts that previously added it, based on the logic that with the introduction of the official character in Unicode, U+20BD will be used everywhere instead of U+20CF. But as a matter of fact, it is not true. Since such substitution does not conflict/overlap any of the existing symbols, this seems to be a valid solution until the currency symbols are completely filled in by Unicode consortium. U+20CF as a ruble sign was used for 7 years before the Unicode update, and as I found out, it continues to be used with additional glyph implementation (via manual webfont fallback). Adding this glyph is need at the same level as adding of any currency signs to Iosevka in general.
