### ISSUE TITLE
Add a way for using precompiled ligatures as ligature replacement

### ISSUE THREAD

**Issue by leiserfg** [be5invis/Iosevka#846]
Some programs using cell drawing (like kitty term) have issues with the not Fixed variations of Iosevka. I really like both and given that Iosevka includes a `compatibility-ligatures` feature, I was thinking how hard would it be to use that and point the ligature "cluster" to be replaced by the compatibility one and the required amount of empty spaces to complete the size of the cluster.  

Maybe it can be an extra parameter of the `compatibility-ligatures` that does the ligature substitution.
In any case, thanks a lot @be5invis, your work is awesome.

**Comment by be5invis** [comment]
I do not do workarounds for one specific software, especially when the software's behavior is **wrong** (compared to other terminals that properly shapes text).

**Comment by leiserfg** [comment]
I understand your point, the way that kitty draws is a hack we can say, but it's the only way it affords to draw ligatures way faster than other terminals, only being surpassed in speed by other terminals that don't support ligatures. I added support for DUAL fonts into <https://wezfurlong.org/wezterm/>  just to use Iovsevka with ligatures in another GPU accelerated terminal, but it's slower than kitty by around 5x and has drawing issues.
