### ISSUE TITLE
Add a variant selector for Greek capital Gamma or Cyrillic Ge

### ISSUE THREAD

**Issue by NoxUltima** [be5invis/Iosevka#849]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] Some other monospace/programming fonts supported the requested variant. Provide images below.

------

I was wondering, as for consistency, since the capital L already has a motion serifed variant, and capital gamma/Cyrillic ge shares the same basic shape as L but vertically mirrored. 

![20210130_091027.jpg](https://user-images.githubusercontent.com/16898444/106342265-387ce080-62db-11eb-943a-5cb6836adf92.jpg)

**Comment by be5invis** [comment]
It should be better to introduce a separate selector for `capital-gamma`.

**Comment by NoxUltima** [comment]
Sure, I'm fine with that. Like `cyrillic-capital-u` already has a separate one with `y`.
