### ISSUE TITLE
Messy Code in OneNote

### ISSUE THREAD

**Issue by chenjuntong** [be5invis/Iosevka#85]
![](http://ww1.sinaimg.cn/large/6ccda21fgw1f3xo251vogj20jf08otd9.jpg)

Copy some words from outside to OneNote has no problem.
Copy some words from OneNote to OneNote (another position)  and it becomes messy code.

**Comment by be5invis** [comment]
Looks like fallback information lost. External apps may be a combination of “Iosevka” and “Inziu Iosevka”. You can force set the font to Inziu Iosevka.
