### ISSUE TITLE
Cursive forms for v, w, x, z (IBM Plex, Recursive Mono, Decima Mono)

### ISSUE THREAD

**Issue by NoxUltima** [be5invis/Iosevka#852]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] Some other monospace/programming fonts supported the requested variant. Provide images below.

------

![v, w](https://user-images.githubusercontent.com/16898444/106345020-28b7c900-62e8-11eb-89be-ed89dc9c0677.png)

Also, continuing from #362, I also agree on adding 'cursive' forms of x and z like those in IBM Plex Mono (possibly even Recursive Mono too.

![x, z](https://user-images.githubusercontent.com/16898444/106355900-16fd1280-6336-11eb-976e-a17e1011db5f.png)

**Comment by be5invis** [comment]
Aligns with #620, handwriting effort

**Comment by kauesena** [comment]
Some of the labels in the picture got mixed up,  did they not?

**Comment by NoxUltima** [comment]
Yeah a mistake, the last one was supposed to be Ibm plex

**Comment by kauesena** [comment]
Regarding v and w, I think IBM Plex design is very similar to Recursive, if I remember well. I did not know Recursive Mono, bu the way. A very nice font it is.

**Comment by NoxUltima** [comment]
> Yeah that was a mistake, the last one was supposed to be IBM Plex.

Updated as of just now.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/107115729-7ae67600-6823-11eb-9dbd-69b474ed033f.png)

**Comment by be5invis** [comment]
`x` and `z` are much more complicated, and the style matching will become a big problem.

**Comment by kauesena** [comment]
The cursive `v` and `w` look great. 

> `x` and `z` are much more complicated, and the style matching will become a big problem.
I was afraid that would really be a challange to implement. I only hope you can manage the handwritting effort eventually in the far future. The cursive variants of `r`, `s`, `x` and `z` would be splendid for the italic slant. I am ignorant to the difficulties you'd face implementing these character variants, but perhaps allowing them just for the italic slant would make things somewhat easier.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/110461919-ea4ec000-8084-11eb-9bad-cf5baf781d56.png)

**Comment by NoxUltima** [comment]
That z shape looks very beautiful!

(Now there's only x left!)

**Comment by wimstefan** [comment]
@be5invis sorry for bothering you again but would it be possible to get a cursive variant of capital-z as well? The lowercase variant looks simply stunning and it would be fantastic to have the same variant in uppercase :)
