### ISSUE TITLE
Flat-topped lowercase delta, rounded lowercase xi (Jetbrains Mono, Liberation Mono)

### ISSUE THREAD

**Issue by NoxUltima** [be5invis/Iosevka#856]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] Some other monospace/programming fonts supported the requested variant. Provide images below.

------

Here's two alternate shapes for Greek lowercase Delta and Xi, both from JetBrains Mono. Here's some other fonts which I've gathered as well: 

![delta xi](https://user-images.githubusercontent.com/16898444/113967978-c4bffc80-9864-11eb-82cb-696ac41977ba.png)

**Comment by be5invis** [comment]
Put in backlog. May do that after v5.0.

**Comment by NoxUltima** [comment]
Sure. Thanks smile 😊

**Comment by pv4** [comment]
In university (physics) we used the forms implemented in the current Iosevka version. Wikipedia contains these forms as well: https://en.wikipedia.org/wiki/Delta_(letter) , https://en.wikipedia.org/wiki/Xi_(letter) . It would be great if the current forms are kept (either as defaults or as variants), please do not remove them.
