### ISSUE TITLE
Add Circled Zero With Slash (U+1F10D)

### ISSUE THREAD

**Issue by Tazshelby2016** [be5invis/Iosevka#861]
- The requested character is...
  - [ ] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [X] Symbol
- [ ] Some other monospace/programming fonts supported this character. Provide images below.

------
This symbol is the official Unicode character for CC0. Unicode added this as a textual way to represent it, necessary in text-only documents, and useful overall. Fira Code plans to support it and the other Creative Commons symbols (See Unicode Block ‘Enclosed Alphanumeric Supplement’). It is a circled variant of U+0030 FE00, a variation of the glyph for zero recognized as an official character. The slash in U+0030 FE00 goes from the bottom left to the top right within the zero.
![New Piskel (38)](https://user-images.githubusercontent.com/54291363/106395205-80c4fd00-63c6-11eb-86c9-5cebd2cd8508.png)

**Comment by be5invis** [comment]
In Unicode it looks like this.
![image](https://user-images.githubusercontent.com/240091/106405401-e925d580-63ea-11eb-9061-a0c1347ba1db.png)
