### ISSUE TITLE
Split $ and ¢ like Recursive Mono

### ISSUE THREAD

**Issue by NoxUltima** [be5invis/Iosevka#863]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] Some other monospace/programming fonts supported the requested variant. Provide images below.

------

From the image below, the bar is split in two parts around the middle.
Can we also add variants for &cent; too to match that of $?

![Dollar](https://user-images.githubusercontent.com/16898444/106402295-cb488700-6463-11eb-86ba-6f0b7e9a0a2b.png)

**Comment by be5invis** [comment]
`¢` will need a matrix of variants. Otherwise you or other people will file another dozen of issues requesting some combinations...

**Comment by be5invis** [comment]
But, one interesting solution might be leveraging `cvDecompose` mechanism (that I added for composites) to treat `c` and the `|` part separately.

**Comment by NoxUltima** [comment]
Yeah sure I'm fine either way

**Comment by be5invis** [comment]
@NoxUltima 
> **this time**
Wait...

**Comment by NoxUltima** [comment]
> this time

I meant unlike the variants for `c` and `s`.
