### ISSUE TITLE
Base-serifed i and l, to complement r

### ISSUE THREAD

**Issue by NoxUltima** [be5invis/Iosevka#865]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] Some other monospace/programming fonts supported the requested variant. Provide images below.

------

In #851 I proposed adding base-serifed `r`, like that of Decima Mono, and I thought of doing the same for `i` and `l` too to smoothen things out.

![i, l](https://user-images.githubusercontent.com/16898444/106406513-73664c00-6474-11eb-993a-101d083fa200.png)

**Comment by be5invis** [comment]
“Complement” doesn’t justify such request.

**Comment by NoxUltima** [comment]
The Arnold font has the base-serifed `l` to distinguish it from `1`, `I`, `i` or `I`, by removing the top serif completely, without introducing a new shape for the `l`. I added `i` for completeness sake.

![](https://i.pinimg.com/originals/89/e6/51/89e65131b29bd600006a92e50cbdc53c.png)

**Comment by be5invis** [comment]
If you find another font doing this then it could further justify this request, but I do not think one letterform existed in only one font worth adding.

**Comment by NoxUltima** [comment]
There are plenty more but this is the only case for a monospaced font doing this. A couple include Audimat (which also has a monospaced counterpart):

![](https://imgs2.fontbrain.com/imgs/00/cc/ec029f4d4af31e603de48ef19455/sa-720x400-333333@2x.png)

**Comment by be5invis** [comment]
Audimat Mono doesn't have that. Label is kept.

**Comment by NoxUltima** [comment]
I don't think I've found anything thus far except these two.

**Comment by pv4** [comment]
@NoxUltima I thought about making the similar request a time ago but finally I decided the `l` variant suggested wouldn't be readable enough. I ended up with `i/l=serifed-asymmetric` for `slab`, `i/l=zshaped` for `sans`, and `one=*-long-top-serif` for both which looks distinguishable from them and also allows to recognize `1` even for people who have hever seen Iosevka. Try such a setup if you wish.

P.S. I tried `flat-tailed` earlier but the result didn't look pleasant for me. In 5.0.0 I switched from `zshaped` to `flat-tailed` and now I like how it looks. Either `flat-tailed` become better in latest releases or something happend with my perception :)

**Comment by NoxUltima** [comment]
Yeah I originally wanted to add base-serifed `i`, `l` and `r` all at once in #851 but I didn't find i and l in many monospaced fonts like this one.

**Comment by pv4** [comment]
Btw if implementing this variant of `l` then "Latin Small Letter Turned L", U+A781 ( https://unicode-table.com/en/A781/ ) will be undistinguished from latin uppercase `T`.

**Comment by NoxUltima** [comment]
On second thoughts I'll just have to scratch this. Closing.
