### ISSUE TITLE
Two variants of curly 7 (Source Code Pro/Liberation Mono, and Gintronic)

### ISSUE THREAD

**Issue by NoxUltima** [be5invis/Iosevka#866]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two ~~monospace/programming~~ fonts, created by different designers, supported the requested variant. Provide images below.

------

Since #362, a variant for curly `z` has been added, but the design of `7` throughout is mostly straight. 

The black one on the left has a concave curve while the Gintronic one curves like a nice s-shape like that of `2`. I do prefer the Arial one is enough but I do believe the Gintronic one looks appealing as it harmonizes with curly `Z` and default `2`. I brought `2` up in green for illustration. 

I'm fine if either one or even **both** of these gets added. Unlike my previous issue, this one _quite_ makes the mark.

<img alt="7" src="https://user-images.githubusercontent.com/16898444/106410443-d6101580-647d-11eb-984d-d671e6f4083a.png">

**Comment by acarasimon96** [comment]
I would like to add that Source Code Pro and Liberation Mono also have a curly 7 like in Helvetica/Arial. I'm too busy to upload pictures at this time, but I'm sure most of us have seen those fonts before.

I was about to make a new issue like this, but thanks for getting my idea covered, @NoxUltima.

**Comment by NoxUltima** [comment]
If **both** can be added, then that's a +1

**Comment by be5invis** [comment]
> I propose one of two options

If I did only one, you will open another. So both will be introduced.

**Comment by NoxUltima** [comment]
> I propose one of two options

It's okay. And I actually didn't mean that.

**Comment by NoxUltima** [comment]
So we going for it?
