### ISSUE TITLE
Present created variants in the issues that asked for them?

### ISSUE THREAD

**Issue by pv4** [be5invis/Iosevka#868]
@be5invis 
A time ago when adding a new variant you always attached a picture with it to the issue (e.g. #591 , #669 ). That was a good tradition but now it has gone away.

Is it possible to return that tradition back please so that it's possible to see a new variant image right in the issue without a need to build `sample-images:pre` or wait a new release (with all-variants image on the main github page)?

**Comment by be5invis** [comment]
Oh yeah I just forgot to take screenshots, since there are so many of these issues.
Closing.

**Comment by wimstefan** [comment]
No wonder - the rate of new variants has quadrupled 😏
It's incredible how productive you are @be5invis 👍🏼🙏🏼

**Comment by NoxUltima** [comment]
Some of my favorites were the

- hooked j
- asymmetric w
- 1, 5 and 7
- open P and R
- enlarged U
- motion serifs everywhere 😂
