### ISSUE TITLE
Operators vertical alignment

### ISSUE THREAD

**Issue by MrWaz** [be5invis/Iosevka#87]
Well.. first I'm in love with your font.. 

I put it everywhere, in my IDE, in my fav text editor, even in thunderbird to write emails in markdown.

But i had to tune it by myself to fix what I find to be annoying when writing code. 
I'm writing a lot of code involving ':=' combination and when using other coding fonts (consolas, pragmata pro, fira....), the ':' & '=' are vertically centered.. this is not the case with iosevka, in which the top equal sign horizontal bar is at the same level than the top dot of ':'.. 

I tried to play with your code but cannot find a nice way to solve this in a nice way for every size, weight and operators.. I've a acceptable build now but seems it would be nice to have an official solution if it can be found.

All the best

**Comment by be5invis** [comment]
Well... In Master branch there is a ligation moves colon when it is before equal. However it is not published yet.
![image](https://cloud.githubusercontent.com/assets/240091/15759407/1a1e29ce-2941-11e6-9c57-c9a52e9cd191.png)
