### ISSUE TITLE
BQN programming language support

### ISSUE THREAD

**Issue by mlochbaum** [be5invis/Iosevka#870]
- The requested character is...
  - [ ] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [X] Symbol
- [X] Some other monospace/programming fonts supported this character. Provide images below.

------

I'm the author of the [BQN](https://mlochbaum.github.io/BQN/index.html) programming language, which is related to APL but uses a different character set. From the existing characters it looks like Iosevka is an excellent font for BQN programming, and since double-struck characters were added it's very close to having full character support. There are six fairly simple characters missing, so I thought I'd request support for these. BQN is new and very niche, so feel free to simply close this issue if you're not interested.

The missing characters are `⎉⚇⌜⎊⟜⥊`, or U+2389, U+2687, U+231C, U+238A, U+27DC, and U+294A. I also think that the mirror image `⊸`, U+22B8, is too small and would be difficult to read in any use case (but it's remarkable that I only have one significant issue with the font!). I can split that into a separate issue if you'd like.

Here are samples of fonts that support these characters. The fonts are described and linked on BQN's [fonts page](https://mlochbaum.github.io/BQN/fonts.html). Of these, only Fairfax HD and Julia Mono have support independently of BQN. I contributed these characters to 3270, and the DejaVu mod is DejaVu Sans Mono where I've added some characters and changed others to work with BQN better. BQN386 was extended from APL386 by a collaborator.

![bqn_chars](https://user-images.githubusercontent.com/1320219/106622278-6d8a6c80-6541-11eb-85e2-79d438c2de30.png)

The BQN386 version of the circled bar with notch `⎉` is a deliberate break from Unicode's specifications to match the related character `˘` better. I don't think such a change is necessary even for a BQN-specific font.

**Comment by be5invis** [comment]
Mark as post 5.0. Note that Iosevka will follow Unicode on `⎉`, the inner shape will be a `V` instead of an arc.

**Comment by be5invis** [comment]
Added them. Note that you may need `NWID` feature / using the Term variant, since many of these symbols are in the range of geometric shapes, therefore they follow geometric dimensions.

**Comment by mlochbaum** [comment]
I've built a term-spaced version and everything looks outstanding. Code is very readable. Thank you!
