### ISSUE TITLE
Space-aware m in mono

### ISSUE THREAD

**Issue by clsn** [be5invis/Iosevka#871]
Purely a "gee this sounds cool" feature; feel free to chuck it in the bin.

It's something I've experimented with a little while obsessing with various types of monospaced fonts last year.  Thing about mono fonts is that most of the letters look okay... except the lowercase m.  (maybe the w, uppercase M, a few others, but m is generally the worst offender.)  It's true even in Iosevka Term.  The m has to be cramped to avoid bumping into the letters on either side... but usually there's plenty of room.  It's generally only when you're dealing with "mm" or "wm" or something that you need that extra space.  I started making more relaxed "m"s with context-sensitive alternates when they were near another "m" or "M" or whatever, and it really looked good (I thought).  The "m"s no longer stood out as being cramped.  Think it over.

(in some, I made a "mm" ligature which was like a four-humped "m", centered where the two characters would have been.  There were circumstances in which I actually liked it, but sane people wouldn't.)

Maybe I can make some pictures.

**Comment by be5invis** [comment]
I think Monoid did this? But it does not look very implementable in current OTL mechanism.
