### ISSUE TITLE
Add more variants to Greek lowercase lambda, following lowercase y and Cyrillic capital U

### ISSUE THREAD

**Issue by NoxUltima** [be5invis/Iosevka#872]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] ~At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.~

------

Since Cyrillic capital U (&Ucy;) already has variants added from the 'y' a long time ago, can we make lambda **share the same variants as Cyrillic U and 'y'**, since its design is only a vertically mirrored 'y'? 

Iosevka doesn't have any flat-hooked lambda yet - the current one looks a bit like JetBrains mono (shown on the right). The left is a motion serifed flipped 'y' from my latest build of Iosevka.

![lambda](https://user-images.githubusercontent.com/16898444/106713853-fedb0b00-6635-11eb-8673-0681c3de13f6.png)

**Comment by be5invis** [comment]
I do not think cursive variants make sense for `λ`.

**Comment by NoxUltima** [comment]
Yeah. Except for the cursives.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/106716223-0907f580-65b3-11eb-9349-f91a6560bef3.png)

**Comment by be5invis** [comment]
Note: no plan for `λ` with hook at right bottom.

**Comment by NoxUltima** [comment]
Thanks! Now that's better!
