### ISSUE TITLE
Sync lowercase a variants for alpha and i for iota

### ISSUE THREAD

**Issue by NoxUltima** [be5invis/Iosevka#873]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] Some other monospace/programming fonts supported the requested variant. Provide images below.

------

So I wanted to expand on the variants of alpha by adding **only the single storey** variants for that of lowercase 'a'.

The single-storey 'a'-like construction also can be seen in a number of programming monospace fonts such as JetBrains Mono, Cascadia Code and Gintronic. 

Shown here is Gintronic:

![20210203_161317.jpg](https://user-images.githubusercontent.com/16898444/106717624-ef11f580-663a-11eb-9085-6f5dc069bc96.jpg)

And Greta Mono:

![20210203_161502.jpg](https://user-images.githubusercontent.com/16898444/106717669-ff29d500-663a-11eb-9d16-4a94a86b4b14.jpg)

I especially like the tailed variant of alpha on the right in both typefaces.

---

The current form of iota only has one variant, which is the flat-hooked serifed `i` form. Syncing all the variants of `i` to iota would suffice.

**Comment by be5invis** [comment]
I'd like to make `α` look significantly different from `a`.
Put in backlog for now.

**Comment by NoxUltima** [comment]
I was also planning to do the same for iota with the variants of `i`

**Comment by be5invis** [comment]
As I still have a little bandwidth... Make them into V5.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/106723796-576dc200-65bc-11eb-9333-c7e8be088388.png)
![image](https://user-images.githubusercontent.com/240091/106723809-5b99df80-65bc-11eb-8004-a17d22d81481.png)
