### ISSUE TITLE
Change the shape of Greek pi and tau to introduce tails

### ISSUE THREAD

**Issue by NoxUltima** [be5invis/Iosevka#875]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

Tailed lowercase pi and tau are very common letterforms in many programming fonts. Shown on the right is JetBrains Mono, whereas Iosevka's pi and tau (left) do not have curly tails, much like Gill Sans. The tau would have a long tail like the current iota.

I am proposing this as I don't want both of these lowercase letters to look too much like their Cyrillic counterparts, much like &pcy; and &tcy;, which they currently do.

![pi tau](https://user-images.githubusercontent.com/16898444/106739846-9cddce00-6654-11eb-92fd-ebe59742ae44.png)

**Comment by be5invis** [comment]
I think we can just change the default instead of introducing variants.

**Comment by pv4** [comment]
> I think we can just change the default instead of introducing variants.

Year, from my university years (physics) they should look like @NoxUltima suggests rather than they do in the current version. Wikipedia confirms this too: https://en.wikipedia.org/wiki/Pi_(letter) , https://en.wikipedia.org/wiki/Tau both have bottom right tail.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/106854688-978e7c80-6670-11eb-8469-b0b6845aeefa.png)
