### ISSUE TITLE
Uppercase J with (descending) flat hook (Gill Sans, Fira Mono and Novel Mono Pro)

### ISSUE THREAD

**Issue by NoxUltima** [be5invis/Iosevka#876]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

This is one of my long-lost variant requests - a `J` with the hook going **slightly below** the baseline. The hook does not curve upward unlike all the other `J` variants, but rather diagonally downward, so it looks more like `]`.

![](https://d1ly52g9wjvbd2.cloudfront.net/img16/A/D/ADBE_Novel-Mono-Pro-RegularA.png) 
![](http://www.fonts2k.com/font-previews/large/824/fira-mono-ot-large.png)

Unhooked under-baseline `J` will look more like Gill Sans, and is much more suitable for quasi-proportional Aile/Etoile, but they are to be rendered narrower, like `I`:

![](https://d1ly52g9wjvbd2.cloudfront.net/img16/A/D/ADBE_Gill-Sans-Nova-Shadowed-MediumA.png)

**Comment by be5invis** [comment]
> The hook does not curve upward unlike all the other `J` variants, but rather diagonally downward, so it looks more like `]`.

This is Humanist style, doesn't match Iosevka.

**Comment by NoxUltima** [comment]
I know.

**Comment by be5invis** [comment]
@NoxUltima I tried, it is ugly.

**Comment by NoxUltima** [comment]
Or a half-curly hook similar to that of `i=curly` when upright? It leans more toward the Gill Sans variant.

**Comment by be5invis** [comment]
@NoxUltima That will become the “compact” variant as I am planning.

**Comment by NoxUltima** [comment]
I would love to use the serifed compact variant, kind of looks nice

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/106880546-578bc180-6691-11eb-8bd8-f46dfafd0ca3.png)
