### ISSUE TITLE
Remove unnecessary serifs on Greek lowercase letters

### ISSUE THREAD

**Issue by NoxUltima** [be5invis/Iosevka#878]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.

------

These letters lack motion serifed variants so I thought of adding them to the font as well. I've previously done the same for Cyrillic &ncy; following H.

![20210204_171956.jpg](https://user-images.githubusercontent.com/16898444/106871475-3d8fc480-670d-11eb-8a15-aa74c302ca44.jpg)

**Comment by be5invis** [comment]
Serifs doesn't make sense for lowercase Greek.
Mark as Needs Justification.

**Comment by NoxUltima** [comment]
I first thought I wanted the Greek styles to match up with the Latin and Cyrillic. Like how the alpha and iota I added earlier was based on an earlier variant of lowercase a and i.

**Comment by be5invis** [comment]
@NoxUltima I should remove them.

**Comment by be5invis** [comment]
Also for `μ` its tail should be mandatory — sync with other Greek letters.

**Comment by be5invis** [comment]
**DECISION**: Motion serif doesn’t make sense for Greek.

**Comment by NoxUltima** [comment]
Okay. We should do the same for Slab too.
