### ISSUE TITLE
Fix Cyrillic zhe and ka; add traditional forms too

### ISSUE THREAD

**Issue by NoxUltima** [be5invis/Iosevka#879]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

Cyrillic zhe shares similar designs as K (being two k placed back to back).

Iosevka's rendition of zhe has to be with the variant of `capital-k = "symmetric-connected"`, I believe.

![20210204_182034.jpg](https://user-images.githubusercontent.com/16898444/106879151-be52be80-6715-11eb-8995-7803a07b2a8b.jpg)

Fira Code:

![20210204_182043.jpg](https://user-images.githubusercontent.com/16898444/106879158-c01c8200-6715-11eb-9280-c924c6f02524.jpg)

Hack: 

![20210204_182051.jpg](https://user-images.githubusercontent.com/16898444/106879164-c1e64580-6715-11eb-94c8-1f53e73095de.jpg)

Alternatively, we can create a separate variant selector for Cyrillic ka/zhe.

**Comment by be5invis** [comment]
Does the Hack’s variant have another font from a different designer have?
“Sync” doesn’t justify this case enough, as `Ж` comes from a different origin than `K`, and is also much more compact than `K`.

**Comment by NoxUltima** [comment]
> 

The Hack variant, I believe has to deal with the Bulgarian locale. SF Mono also has that particular variant.

SF Mono distinguishes the 

![20210204_190519.jpg](https://user-images.githubusercontent.com/16898444/106884225-f957f080-671b-11eb-8998-4184316e0283.jpg)

**Comment by be5invis** [comment]
I think we should detach `cyrl/Ka` and `cyrl/ka` with `K` and force the `symmetric-connected` variant.

**Comment by NoxUltima** [comment]
Yes, and perhaps add the forms like those in Source Code Pro as an alternative: `traditional`.

**Comment by be5invis** [comment]
I'd like to do the `symmetric-connected` as first step. “Traditional” after 5.0.

**Comment by NoxUltima** [comment]
Sure. You can leave this open.

**Comment by pv4** [comment]
@NoxUltima do you speak Russian?

1. Latin uppercase K and cyrillic (Russian) uppercase K usually have the same shape. There are no reasons for them to be different besides to be distinguished in text containing both latin and cyrillic K. But this is a difficult topic since in such a case we should also think about all the similar-looking glyphs: AaBCcEeHMOoPpTXxy. And don't forget about other languages.

2. From your variants, the latter lowercase zhe with the middle bar of caps height is not standard for Russian cyrillic (I don't know though whether it's standard for some another country using cyrillic).

I also agree with @be5invis that Zhe is more compact than K. I'm just unable to imagine how Zhe would look like in slab style, heavy weight, if using `K=curly`-like variant. It seems it will look like an inkblot.

**Comment by be5invis** [comment]
@pv4 So I will still build all the variants for Cyrillic KA but default them to a different variant. “Traditional” ones will be added later —— much later I think.

**Comment by NoxUltima** [comment]
@pv4 Not really but I'm trying to... But I'm quite obsessed with languages, and I made a lot of conlangs that use Cyrillic as its primary script.

**Comment by pv4** [comment]
> detach `cyrl/Ka` and `cyrl/ka` with `K` and force the `symmetric-connected` variant.

@be5invis does it mean `cyrl/ka=curly` will be removed? That would be a sad news. I like curly variants of letters more than straight ones and the current `cyrl/ka=K=curly` is the best choice for me.

**Comment by be5invis** [comment]
@pv4 No. It will be still there.

**Comment by NoxUltima** [comment]
> No. It will be still there

I hope that's true for the rest of the &Kcy; variants.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/106888826-f5848980-669b-11eb-9717-6ba14e3184a9.png)

**Comment by pv4** [comment]
> @pv4 No. It will be still there.

Oh, thanks! Ok then.

I was afraid anything could regress compared to what it is now.

**Comment by be5invis** [comment]
Closing this for now. For the “traditional” variants please file another issue.
