### ISSUE TITLE
Inside-crossing variants of Q?

### ISSUE THREAD

**Issue by NoxUltima** [be5invis/Iosevka#880]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested **variants**. Provide images below.

------

This issue is a continuation of #808. I wanted to add two more variants for Q, both whose tails go inside the circle and are slightly curved. 
The only difference between them is that the first goes to the bottom right and ends there; the second makes a 90-degree clockwise turn and crosses the baseline.

![Q2](https://user-images.githubusercontent.com/16898444/106968194-576bee80-6783-11eb-88a9-fc521dc76408.png)

**Comment by pv4** [comment]
I think @be5invis will end up with a phobia of entering Iosevka issue list soon.

**Comment by NoxUltima** [comment]
I don't know.
This is the last one I have.

**Comment by pv4** [comment]
> Unless it's really important like filing bugs.

I think filling bugs is exactly what open source community is good in. Lots of people report errors they meet in real-life usage of a product. So there is no problem in reporting bugs.

**Comment by NoxUltima** [comment]
Yeah agreed.

**Comment by be5invis** [comment]
Please provide at least two existing fonts **for each variant** to justify them.

**Comment by dixius99** [comment]
> I think @be5invis will end up with a phobia of entering Iosevka issue list soon.

I think it would be interesting to see how often each of the extensive list of character variants are actually used. Iosevka is already the most customizable font that I'm aware of.

@be5invis is very gracious in accommodating our variant requests, and finding a way to make it all look cohesive. At some point it will likely become overwhelming to actually sift through all of the options.

**Comment by NoxUltima** [comment]
The curved Q form is quite prevalent in typewriter fonts:

![image](https://user-images.githubusercontent.com/16898444/106966583-99476580-6780-11eb-8654-a4907d3a0e9a.png)

**Comment by pv4** [comment]
@NoxUltima The last variant would be a challenge to implement for bold weights (the picture contains `heavy` weight). There doesn't seem to be a place for the "tilde" :(

![image](https://user-images.githubusercontent.com/2502094/106969168-6474e780-675b-11eb-888d-f629b25771de.png)

**Comment by NoxUltima** [comment]
Ya sure; I think the first is easier to do...

**Comment by be5invis** [comment]
@NoxUltima Actually your images shows **five** different designs: Corner, Straight (Simplon Mono), Tilde-like (ITC Avant Garde), Arch (Linefeed), and Wave-like (Selectric).

**Comment by NoxUltima** [comment]
I am discarding the tilde and wave-like forms as it would look too ugly and hard to implement in heavier sizes.

**Comment by be5invis** [comment]
And, I plan to remove the detached-tailed variant unless you find enough justification. (The Sans is proportional, and The Sans Mono has a design very to the existing Q).

**Comment by NoxUltima** [comment]
> And, I plan to remove the detached-tailed variant unless you find enough justification. (The Sans is proportional, and The Sans Mono has a design very to the existing Q).

**FF Nuvo Mono** also has the detached tail as well.

**Comment by be5invis** [comment]
> FF Nuvo Mono also has the detached tail as well.

FF Nuvo Mono’s design is further different (it’s tail shape is like `^`).

**Comment by be5invis** [comment]
I can keep the oblique tail-detached but the horizontal one will be removed.
And, Please justify the cornered variant. **At least two existing fonts from different designers,** as it is very unusual. The Straight one also require further justification.

**Comment by NoxUltima** [comment]
> I can keep the oblique tail-detached

And make the tail longer, just like in Fedra. 


> The Straight one also require further justification.

I'd consider removing both, as, first, Euclid (proportional) has exactly the corner variant as I described,

**Comment by NoxUltima** [comment]
> FF Nuvo Mono’s design is further different (it’s tail shape is like ^).

Should we add that of FF Nuvo as well?

**Comment by NoxUltima** [comment]
I'd consider removing the ones I am proposing now, as only Euclid (proportional) has exactly the corner variant as I described, Simplon Mono for the straight-crossing one. Again both are very unusual forms, so I am closing this issue.
