### ISSUE TITLE
More open 5

### ISSUE THREAD

**Issue by AlsoScratch** [be5invis/Iosevka#882]
It would be nice if this part of the `5` was made more open, I feel it would look better.

<img width="93" alt="Screenshot 2021-02-08 at 12 27 31" src="https://user-images.githubusercontent.com/48752273/107176062-51873f00-6a09-11eb-9684-ec9d91bee13a.png">

Before you commit the changes, could you show the new shape to me first?

**Comment by be5invis** [comment]
Are you requesting a variant or a design change?

**Comment by AlsoScratch** [comment]
A design change, please.

**Comment by be5invis** [comment]
↓ Current
![image](https://user-images.githubusercontent.com/240091/107199899-d9d6f700-69ab-11eb-8524-133f5d94c357.png)
↓ Purposed, just _slightly_ more open
![image](https://user-images.githubusercontent.com/240091/107199856-c3c93680-69ab-11eb-8d32-5c00fb36e7c0.png)

**Comment by AlsoScratch** [comment]
I would like it to be more open that.

**Comment by be5invis** [comment]
@AlsoScratch Could you please clarify you want **even more** open then the image? Adding more space will make its design inconsistent with existing figures.

**Comment by AlsoScratch** [comment]
The new one is better for sure. I guess we’ll go with that.

**Comment by pv4** [comment]
Btw is it okay that the left border of the vertical straight and the left border of the round part are not aligned? The current version has the similar issue.

![image](https://user-images.githubusercontent.com/2502094/107227549-91abe900-6a2c-11eb-87d5-22b2fd3b72fe.png)

**Comment by AlsoScratch** [comment]
@pv4 Yeah I'm fine with that.

**Comment by pv4** [comment]
@AlsoScratch I wrote that to @be5invis to ensure it's not a bug :)

**Comment by be5invis** [comment]
@pv4 This is by design. Search “overshoot”.
