### ISSUE TITLE
Trigram characters misaligned

### ISSUE THREAD

**Issue by kauesena** [be5invis/Iosevka#883]
I believe the the trigram characters `☰☱☲☳☴☵☶☷` should have the split and whole bars aligned, which is not currently the case in Iosevka. 

![image](https://user-images.githubusercontent.com/30255100/107230464-df5d2d00-69fd-11eb-91ab-69a0cfc1fc1e.png)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/107311530-5e288900-6a43-11eb-8df0-cc72b65635f9.png)
