### ISSUE TITLE
The space between the accent and the glyph should not be a fraction of the accent height

### ISSUE THREAD

**Issue by mkarmona** [be5invis/Iosevka#886]
I am trying to configure a more compact version and an increased in the visibility of the punctuation and brackets of the fantastic Iosevka font. One of the actions I took was to reduce the [leading of the font](https://github.com/mkarmona/Iosevka/blob/849ba8ce006cc06cf4a03c356904f20b48a9fdab/private-build-plans.toml#L96). But this created a problem with some accents as they got overlayed by the line below when the uppercase is used, for example, the letter `Ñ`.
Then, in order to address that problem, I decreased the height of the accent and that brought tighter the accent and the glyph. So I realised that the accent uses its own height to compute [the distance to the glyph](https://github.com/be5invis/Iosevka/blob/1b7addc93ca632a094a820613d7f183350b18027/font-src/glyphs/marks/index.ptl#L28). So here the bug or I would rather say _feature to add?_ 

- Should the accent have a configurable fixed scalar to add as a separator? 

Here my [whole changeset](https://github.com/be5invis/Iosevka/compare/master...mkarmona:ot-dz)

**Comment by be5invis** [comment]
`accentBaseOffset` and `accentStackOffset` now control them.
