### ISSUE TITLE
Top ring in per mille sign not connected in variants

### ISSUE THREAD

**Issue by acarasimon96** [be5invis/Iosevka#887]
When using `font-feature-settings: "cv83" 4;` in CSS or `percent=rings-continuous-slash-also-connected` in `private-build-plans.toml`, the per mille sign is missing a connecting line between the slash and top ring unlike the percent sign.

![image](https://user-images.githubusercontent.com/17580077/107313515-e57bf980-6a4f-11eb-9294-282cb25e1708.png)

I'm not sure if this is considered as a variant request, but I think it's more of a bug as it might have been accidentally left out when the connected ring variant was added. I am using version 5.0.0-rc.1, both on a custom build and normal Iosevka.

By the way, thank you for all the hard work you've done for this massive release and your super speedy response to issues.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/107315050-c4fd7080-6a4a-11eb-89f9-0ac4e3b186b5.png)
