### ISSUE TITLE
Is there a way to reduce font disk size?

### ISSUE THREAD

**Issue by habamax** [be5invis/Iosevka#889]
Is there a way to reduce font disk size for the custom builds?

Currently each font is about 2.7M:

![image](https://user-images.githubusercontent.com/234774/107481961-0f3c3a00-6b90-11eb-8974-9f02d6e4feea.png)

In comparison with Jetbrains Mono:

![image](https://user-images.githubusercontent.com/234774/107482278-84a80a80-6b90-11eb-814d-feb5b5cb9cba.png)

Building with or without ligatures has no visible effect on disk size.

My build plan:

```
[buildPlans.iosevka-habamax]
family      = "Iosevka Habamax"
spacing     = "term"
no-ligation = true
serifs      = "sans"


[buildPlans.iosevka-habamax.variants.design]
three     = 'flattop'
four      = 'open-non-crossing'
six       = 'open-contour'
nine      = 'open-contour'
asterisk  = 'hex-low'
bar       = 'force-upright'
percent   = 'rings-continuous-slash'
f         = 'flat-hook'
j         = 'flat-hook-serifed'
g         = 'single-storey-flat-hook'
t         = 'flat-hook'
l         = 'serifed-flat-tailed'
r         = 'serifed'
y         = 'straight-turn'


[buildPlans.iosevka-habamax.variants.italic]
f = 'flat-hook-tailed'
k = 'straight'
r = 'top-serifed'
y = 'cursive-flat-hook'


[buildPlans.iosevka-habamax.weights.regular]
shape = 400  # Weight for glyph shapes
menu  = 400  # Weight for menu name
css   = 400  # Weight for webfont CSS


[buildPlans.iosevka-habamax.weights.bold]
shape = 700
menu  = 700
css   = 700


[buildPlans.iosevka-habamax.slopes]
upright = "normal"
italic  = "italic"


[buildPlans.iosevka-habamax.widths.normal]
shape = 600
menu  = 5
css   = "normal"
```

**Comment by be5invis** [comment]
Because even you specify a variant selector the `cv##`/`ss##` features are still present, and all variants are still there. Adding `no-cv-ss = true` should reduce the footprint _a lot_.

**Comment by be5invis** [comment]
You can also further reduce the footprint by using `pyftsubset` to subset the font to the characters you need.

**Comment by habamax** [comment]
> Because even you specify a variant selector the `cv##`/`ss##` features are still present, and all variants are still there. Adding `no-cv-ss = true` should reduce the footprint _a lot_.

3 times less, ~900K! Thank you!

**Comment by alexeyten** [comment]
> You can also further reduce the footprint by using `pyftsubset` to subset the font to the characters you need.

Could [exclude-chars](https://github.com/be5invis/Iosevka/blob/master/private-build-plans.sample.toml#L105-L111)  do the same?

**Comment by habamax** [comment]
> > You can also further reduce the footprint by using `pyftsubset` to subset the font to the characters you need.
> 
> Could [exclude-chars](https://github.com/be5invis/Iosevka/blob/master/private-build-plans.sample.toml#L105-L111) do the same?

I was thinking the same, although not sure if there is an easy way to exclude everything that I don't need :)
