### ISSUE TITLE
v-underscore-low variant

### ISSUE THREAD

**Issue by bitserf** [be5invis/Iosevka#89]
The _v-underscore-low_ variant does not seem to be respected in latest head (I checked on commit f7797f1).

Here is a PDF showing the comparison. On the left is my previous version of Iosevka built from source, maybe a month ago? On the right, is current.

[Iosevka-Compare.pdf](https://github.com/be5invis/Iosevka/files/297235/Iosevka-Compare.pdf)
<img width="1245" alt="compare" src="https://cloud.githubusercontent.com/assets/167841/15773684/621c7cd6-29cc-11e6-8cbc-454886969d1a.png">

The command I use to build is:

```shell
$ make STYLE_COMMON='v-tilde-low v-asterisk-low v-underscore-low v-paragraph-low'
```

Is _v-underscore-low_ still supported? I did not see it in README.

**Comment by be5invis** [comment]
Oh double mapped `underscore.high` to `_`. Fixed in the latest commit.

**Comment by bitserf** [comment]
Confirmed :tada:
