### ISSUE TITLE
Ballot box (check box) characters

### ISSUE THREAD

**Issue by kauesena** [be5invis/Iosevka#890]
- The requested character is...
  - [ ] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [X] Symbol
- [X] Some other monospace/programming fonts supported this character. Provide images below.
-----
I think the charactes `☐`  and `☑` would be nice additions to the font. Liberation Mono and Free Mono provide them. 
![image](https://user-images.githubusercontent.com/30255100/107508980-8bc71c80-6b80-11eb-8b81-d687b7605a99.png)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/107604861-3160a700-6be6-11eb-8ff7-f928feb69433.png)
