### ISSUE TITLE
Ligature request: Chained ----- and ~~~~~

### ISSUE THREAD

**Issue by NoxUltima** [be5invis/Iosevka#893]
- The requested character is...
  - [ ] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [x] Symbol
- [x] Some other monospace/programming fonts supported this character. Provide images below.

------

Since Iosevka has support for arrows, the current OpenType ligature feature allows one to produce straight, fat and wavy arrows with any combination of `<>` and `-=~` characters, but it only works when there is at least **one** `<` or `>` character in the sequence of `~`. 

Perhaps we can extend this mechanism similar to `+` and `=` chaining, as shown in the image below. I added little whitespaces between the `-` characters so it is a bit easier to parse each character, like what has been done to `=`.

![](https://user-images.githubusercontent.com/16898444/107877955-79473d00-6f0a-11eb-9ec5-8f7ba0323be6.png)

The below images show the current behavior of `----`, `====` and `~~~~`, as well as arrow-combinations of either of those characters with `<` or `>`:

<table>
<th><code>~</code></th>
<th><code>=</code></th>
<th><code>-</code></th>
<tr><td>
<img src="https://user-images.githubusercontent.com/16898444/107877638-a1ce3780-6f08-11eb-8e33-a9db9f44c60d.png">
</td><td>
<img src="https://user-images.githubusercontent.com/16898444/107877646-b5799e00-6f08-11eb-940c-8a67808de4bc.png">
</td><td>
<img src="https://user-images.githubusercontent.com/16898444/107877639-a2ff6480-6f08-11eb-9e65-7f66e8f8e8bc.png">
</td></tr>
</table>

The sequence of `-` characters is used in Markdown to separate *table headings* from table *cells*, and also for creating line *dividers* in code comments. The below image shows Iosevka and Fira Code, and their rendering of the character sequence `|-----|`:

<img alt="v, w" src="https://user-images.githubusercontent.com/16898444/107878049-202bd900-6f0b-11eb-87da-871924e24052.png">

PS: The below font is Sudo Code (Jeremy Banka), currently the only font I know with a long sequence of wavy `~` but no support for wavy arrows:

<img alt="v, w" src="https://user-images.githubusercontent.com/16898444/107878177-d263a080-6f0b-11eb-9734-2061d889a951.png">

**Comment by NoxUltima** [comment]
Fira Code has some support for `-` of indefinite length, and this ligature kicks in starting with 4 `-` characters side by side. This long line is used in Markdown to separate table headings from table cells.

![2021-02-14 21_08_44-_Untitled - Notepad](https://user-images.githubusercontent.com/16898444/107877674-d9d57a80-6f08-11eb-9fbb-4747d6de63e9.png)

The below font is **Sudo Code** (Jeremy Banka) and the last wavy line is just a bunch of `~`.

![](https://www.jeremybanka.com/images/sudo-loji.png)

**Comment by be5invis** [comment]
Maybe valid for `dlig`
