### ISSUE TITLE
Markdown heading ligatures ## ### #### ##### ###### (`dlig`)

### ISSUE THREAD

**Issue by NoxUltima** [be5invis/Iosevka#894]
- The requested character is...
  - [ ] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [x] Symbol
- [x] Some other monospace/programming fonts supported this character. Provide images below.

------

![Markdown Heading Ligatures](https://user-images.githubusercontent.com/16898444/107922275-bfec7400-6faa-11eb-8ec8-73417866a700.png)

![Cascadia Code](https://user-images.githubusercontent.com/16898444/107922376-e01c3300-6faa-11eb-998f-618f4aa3d7f3.png)

![2021-02-15 16_28_30-_Untitled - Notepad](https://user-images.githubusercontent.com/16898444/107922377-e27e8d00-6faa-11eb-8974-cf306a4979f3.png)

**Comment by be5invis** [comment]
I do not think this is very necessary though.

**Comment by NoxUltima** [comment]
Like the title says, sequences of "#" is used for Markdown headings. Especially since I write in Markdown a lot and I use the IBM Plex open hash shape a lot and write in very amall sizes with a slightly bold weight, I would want to be able to count the number of # characters, the fact is that I use the vertical space between the # as a hint for how many # characters there are. 

Here another issue I found relating to the use of the ## ligature: 

https://github.com/tonsky/FiraCode/issues/287

And, to add on that, the ### sequence in CoffeeScript is used for block comments.

I think this has become a common feature in many programming fonts nowadays.
