### ISSUE TITLE
Small 'm' looks bad in extended mode, 13/14pt. Ok in 12/15.

### ISSUE THREAD

**Issue by vjalle** [be5invis/Iosevka#896]
Small 'm' looks bad in VS Code, using the extended version, 13/14pt size. Ok in 12/15 size.
Normal (not extended) version is OK.

![image](https://user-images.githubusercontent.com/79142437/108053222-6ab56e80-704d-11eb-8aaf-3ce8cbace8c1.png)

If not visible in the picture: the gap between the legs is not even, the letter looks lopsided.
I'm using a custom build with all default settings, but "extended as normal" because of the bug in Code that prevents switching to Extended.
The issue is present with all variants.

Version: custom build with default settings, "extended as normal", based on 5.0.1
All variants seem to be affected.
Win10
VS Code 1.53.2

Maybe some further settings in the build plan could help?

**Comment by be5invis** [comment]
You may need to enable antialiasing. Bilevel (black-and-white) rendering is not supported.

**Comment by vjalle** [comment]
Thanks for the quick response.
Somehow I have the feeling that the Windows settings are ignored by VS Code? I mean I managed to make all text blurry but no change to the shape of m. Anyway, managed to fix 'm' by plugging different numbers instead of 538 below.

[buildPlans.iosevka-custom.widths.normal]
shape = 538
menu = 5
css = "normal"

Working combinations: 557 for 13pt, 633 for 14pt and 576 for 15pt (scaled from the 500/576 for normal/extended). As a side effects other letters look a bit weird, but not as bad as m was before.

Is there a better solution by tinkering with the parameters? Otherwise I'll live with this... Still the best font for my eyes.
Thanks!
