### ISSUE TITLE
SS17 Term/Fixed show SS15

### ISSUE THREAD

**Issue by peterwu** [be5invis/Iosevka#897]
The Term and Fixed variants of SS17 still show SS15.

![Screenshot from 2021-02-16 10-13-33](https://user-images.githubusercontent.com/584751/108082372-050eb580-7040-11eb-9e2f-ff7b195d49f6.png)

---

* Your font version: 5.0.1
* Your font variant: Term/Fixed
* Your operating system (name and version): Fedora 33
* Your application using Iosevka: Emacs

**Comment by be5invis** [comment]
Fixed in hotfix branch. Closing.
