### ISSUE TITLE
some suggest

### ISSUE THREAD

**Issue by hpfs0** [be5invis/Iosevka#9]
it is recommended adding support for Japanese and special symbols.

**Comment by be5invis** [comment]
CJK glyphs will NOT be included in Iosevka, as Iosevka being an typeface for european languages.
However maybe I will create a variant with full-width punctuations which is compatible to most CJK typefaces, mainly affects punctuations like “” and — (/emdash).

**Comment by hpfs0** [comment]
Thank you for your answer.
Like ① this symbol sometimes is not displayed.

**Comment by be5invis** [comment]
Some circled glyphs are supported recently.

**Comment by Arthur2e5** [comment]
@be5invis maintains a version  called Inziu Iosevka which combines the full-width version of Iosevka with a hinted Source Han Sans variant called Inziu, available on [Baidu Disk](http://yun.baidu.com/s/1sjp2GO1#path=%252F%25E5%25AD%2597%25E4%25BD%2593%252FInziu%252FInziu%2520Iosevka). Unfortunately it appears that the latest combined version has not been built as of 2015-10-22.

**Comment by Arthur2e5** [comment]
FYI, updated link: https://be5invis.github.io/Iosevka/inziu.html
