### ISSUE TITLE
Cache intermediate build outputs

### ISSUE THREAD

**Issue by rben01** [be5invis/Iosevka#900]
**Is your feature request related to a problem? Please describe.**
If you build a custom version of Iosevka and then change a single character's setting in my `build-plan.toml`, rebuilding Iosevka takes a very long time even though 99% of the previous build's glyphs will be reused in the new version of the font. This lengthy build seems unnecessary when most of the necessary information has already been computed.

**Describe the solution you'd like**
Ideally, individual glyphs would be cached during a build so that they could quickly be reused in subsequent builds that use the same character settings. Only glyphs that don't exist in the cache should be built from scratch.

Faster builds would allow users to compare variants more easily to see which they prefer in a given context (it can be hard to evaluate glyphs in a vacuum).

**Describe alternatives you've considered**
Patience.

**Additional context**
I don't know how font's or Iosevka's build process work, so maybe this isn't feasible. Hopefully it is though.

**Comment by be5invis** [comment]
Well caching glyph set is one of my ideas but it is considered hard to implement.
Put to backlog for now.

**Comment by be5invis** [comment]
In recent changes, we are caching results of geometry operations, which significantly reduced build time to 1/3 (on a 32-core system, 3m → 1m). We may introduce more caching in the future to further improve building performance.

Resolve as fixed.
