### ISSUE TITLE
Wrong parentheses (cv76) in SS07 (Monaco style). 

### ISSUE THREAD

**Issue by krasimirkrustev** [be5invis/Iosevka#902]
In the latest 5.0.4 release, the parentheses (cv76) in SS07 (Monaco style) are type 1 and they should type 2.
![charvars](https://user-images.githubusercontent.com/3158689/109394734-2bcac700-7931-11eb-9f4e-d5b600ebd1e5.png)

**Comment by be5invis** [comment]
It is pretty vague, but from my view, it looks closer to paren/normal (cv76#1). Variant 2 should be more different than an arc.

![image](https://user-images.githubusercontent.com/240091/109402944-e1d0e980-790e-11eb-8b0d-a02e38eaf664.png)
