### ISSUE TITLE
Proper design of the italics in the Aile variant.

### ISSUE THREAD

**Issue by kamekku14** [be5invis/Iosevka#903]
For some reason, the italics of the Aile variant uses non-cursive letterforms instead of the usual cursive ones. (Kinda like Input Sans, I think?) I don't think that this is far too controversial for me, but it looks very annoying to see this!

**How Aile's italic variant looks like:**   
![image](https://user-images.githubusercontent.com/66167734/109418378-09a17980-7a03-11eb-999b-b3939aa62bd5.png)

**What would Aile's italic variant looked like:**   
![image](https://user-images.githubusercontent.com/66167734/109418715-d4962680-7a04-11eb-8481-9537edd0cc2c.png)

**Comment by be5invis** [comment]
Aile's style is chosen to look close to neo-grotesque sans-serifs, so not having cursive italics is by design.
Closed.

**Comment by NoxUltima** [comment]
I think the lowercase k and y are still cursive in the aile variant... While the rest are neo-grotesque

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/109650245-c97cec80-7b11-11eb-87f5-bfd58385b07d.png)
V5.0.5 will be something like this :).

**Comment by NoxUltima** [comment]
That one looks awesome!
