### ISSUE TITLE
Affinity Suite ligatures not displaying.

### ISSUE THREAD

**Issue by cooltrooper** [be5invis/Iosevka#906]
I'm intending to use the font as it seems very suitable for documentation, but non of the code ligatures seem to work.
Other fonts like Jetbrains Mono or fira code ligatures work as expected. All is fine in VSCode.
![image](https://user-images.githubusercontent.com/542148/110177703-469fae80-7dfd-11eb-8a14-4c7e09d2900e.png)

---

* Your font version: (Release or git, version) 5.04
* Your font variant: all
* Your operating system (name and version): OSX
* Your application using Iosevka: Affinity Deisgner/Publisher

**Comment by kenmcd** [comment]
Works correctly for me testing with Affinity Publisher v1.9.1.979 on Windows 10.
The fonts have some internal naming issues which may be confusing APub.
The Oblique fonts are in their own style group, but are marked as Italic.
That is incorrect per the OpenType specs.
Affinity apps expect all fonts to be correctly configured to modern standards.

I only installed one TTF file - iosevka-regular.ttf
So only install just the specific TTF fonts you actually need (and no Obliques).
And do not use the TTC files.
Try that and report back. :-)

**Comment by be5invis** [comment]
@kenmcd Not sure what "marked as Italic" mean exactly but for `OS/2::fsSelection` the Spec said the bit 0 denotes either Italic or Oblique, and this bit is synchronized with `head::macStyle`.

**Comment by be5invis** [comment]
But some software (notably Chromium) may get trouble with Oblique. However, I think the original bug is more about the shaping implementation, they may use a broken shaper on certain platforms.

**Comment by kenmcd** [comment]
If there is only one font in a style group it must be marked as Regular.
I can find the OpenType spec link for you, but I expect you know where to look.

**Comment by be5invis** [comment]
@kenmcd If you mean `name` entries then the current Iosevka's behavior is correct for name ID 1/2, i.e., Obliques are assigned to a separate family and used `Regular` as its subfamily name. For `OS/2::fsSelection`, there is a note in the Spec:

> This bit, unlike the ITALIC bit (bit 0), is not related to style-linking in applications that assume a four-member font-family model comprised of regular, italic, bold and bold italic. It may be set or unset independently of the ITALIC bit. In most cases, if OBLIQUE is set, then ITALIC will also be set, though this is not required.

**Comment by be5invis** [comment]
@kenmcd I searched through the spec for `head`, `OS/2`, and `name` and doesn't find anything other than `name` entries said that if one family has only one font instance its should be marked as Regular. If your link is still valid, please share it.

**Comment by cooltrooper** [comment]
I removed all fonts and just installed the ttf for Iosvka Regular and the proplem persists.

**Comment by be5invis** [comment]
@cooltrooper Are _all_ ligations broken, or only a certain subset of ligations are broken?

**Comment by be5invis** [comment]
@cooltrooper And how do other Apple applications behave?

**Comment by cooltrooper** [comment]
Works fine in notes, text edit and fontbook, but not word.

**Comment by be5invis** [comment]
So this should be a problem with Affinity software since Iosevka works properly in many other places. I suspect Affinity incorrectly implemented text shaping on certain platforms, which caused this issue.
(Word is another story: it disables OT features by default and you have to manually enable it.)
Closing as external.

**Comment by cooltrooper** [comment]
I've started a thread on their support forums, for reference:
https://forum.affinity.serif.com/index.php?/topic/136875-iosevka-issues/
