### ISSUE TITLE
Ligation Request issue template

### ISSUE THREAD

**Issue by NoxUltima** [be5invis/Iosevka#907]
**Is your feature request related to a problem? Please describe.**

This is not related to improving the font per se.

Since there's already issue templates for making variant and character requests and there is a new `Ligation Request` label added, may I suggest adding a new issue template for making requests for ligations too (and have it attached to the label as well), rather than manually assigning the `Ligation Request` tag after an issue has been posted.

;)

**Describe the solution you'd like**

The template will include two questions, mainly the programming language(s) and sample images of the ligation in other fonts. 

---

- [ ] In what programming language(s) is this character sequence in?
- [ ] How is it usually rendered in different programming fonts? Provide images below.

---

**Comment by be5invis** [comment]
Added.

**Comment by NoxUltima** [comment]
Thanks! :smile:
