### ISSUE TITLE
cyrillic letters з, э and с are lower than others

### ISSUE THREAD

**Issue by habamax** [be5invis/Iosevka#908]
Describe your problem here. Provide pictures and files if necessary.

---

* Your font version: 5.0.5
* Your font variant: my own
* Your operating system (name and version): windows 10
* Your application using Iosevka: gvim

![image](https://user-images.githubusercontent.com/234774/110363249-5f090680-8053-11eb-8544-8a695eb607c0.png)

![image](https://user-images.githubusercontent.com/234774/110363271-67614180-8053-11eb-9913-3a2f56e60ec0.png)

## private build plan:

```
[buildPlans.iosevka-habamax]
family      = "Iosevka Habamax"
spacing     = "term"
no-cv-ss    = true
no-ligation = true
serifs      = "sans"


[buildPlans.iosevka-habamax.variants.design]
three     = 'flattop'
four      = 'open-non-crossing'
six       = 'open-contour'
seven     = 'bend-serifless'
nine      = 'open-contour'
asterisk  = 'hex-low'
bar       = 'force-upright'
percent   = 'rings-continuous-slash'
f         = 'flat-hook'
j         = 'flat-hook-serifed'
i         = 'serifed-flat-tailed'
g         = 'single-storey-flat-hook'
t         = 'flat-hook'
l         = 'serifed-flat-tailed'
r         = 'serifed'
y         = 'straight-turn'


[buildPlans.iosevka-habamax.variants.italic]
f = 'flat-hook-tailed'
k = 'straight'
r = 'top-serifed'
y = 'cursive-flat-hook'
i = 'serifed-diagonal-tailed'
q = 'tailed'


[buildPlans.iosevka-habamax.weights.regular]
shape = 400  # Weight for glyph shapes
menu  = 400  # Weight for menu name
css   = 400  # Weight for webfont CSS


[buildPlans.iosevka-habamax.weights.bold]
shape = 700
menu  = 700
css   = 700


[buildPlans.iosevka-habamax.slopes]
upright = "normal"
italic  = "italic"


[buildPlans.iosevka-habamax.widths.normal]
shape = 600
menu  = 5
css   = "normal"

```

**Comment by habamax** [comment]
Looks like hinting issue?

![image](https://user-images.githubusercontent.com/234774/110363870-2584cb00-8054-11eb-9114-ccdf996e3e8e.png)

**Comment by be5invis** [comment]
From the bitmap, it looks like that these letters are not get hinted. Could you please upgrade `ttfautohint` to the latest edition?

**Comment by habamax** [comment]
> I cannot reproduce this on my system. From the bitmap, it looks like that these letters are not get hinted. Could you please upgrade `ttfautohint` to the latest edition?

I have the latest `ttfautohint` version:
![image](https://user-images.githubusercontent.com/234774/110427305-98279200-80b8-11eb-8544-1aa833d8ea8e.png)


btw, there is no issue with slab version

![image](https://user-images.githubusercontent.com/234774/110427737-42071e80-80b9-11eb-92af-1bcdf7d47f9c.png)

**Comment by habamax** [comment]
I have just rebuilt it with current master and still the same result: 
[iosevka-habamax-regular.zip](https://github.com/be5invis/Iosevka/files/6106336/iosevka-habamax-regular.zip)

Btw, for some reason it is again has ~2M size (I have `no-cv-ss    = true`) as you suggested earlier to reduce font size.

**Comment by habamax** [comment]
And it only happens to non-slab 13pt, 14pt, 15pt -- the rest is OK.

**Comment by be5invis** [comment]
Strange the geometry has too many points:

![image](https://user-images.githubusercontent.com/240091/110436495-27a55480-8069-11eb-83b4-17d6a8872d3f.png)

Could you please remove `node_modules`, then `npm install` again and rebuild?

**Comment by be5invis** [comment]
I should have a build pass to check whether dependencies are outdated...

**Comment by habamax** [comment]
> Could you please remove node_modules, then npm install again and rebuild?

Done. Font size has been again reduced, but hinting fo 14pt is odd:

![image](https://user-images.githubusercontent.com/234774/110438049-15f29a00-80c7-11eb-9324-28f41b365630.png)

![image](https://user-images.githubusercontent.com/234774/110438329-4c301980-80c7-11eb-8c5d-47caee1fff84.png)

**Comment by be5invis** [comment]
@habamax Perhaps you need to do a full rebuild after upgrading dependencies: run `npm run clean` before you build.

**Comment by be5invis** [comment]
Detailed steps:

* Remove `node_modules`, `pacakge-lock.json` (if present), `yarn.lock` (if present)
* Run `npm install`
* Run `npm run clean`
* Build your fonts

**Comment by habamax** [comment]
1. there are no `package-lock.json` and no `yarn.lock` in the `Iosevka` folder I do `git pull` to
2. deleted `node_modules` and did `npm install`
3. did `npm run clean`
4. built with `npm run build -- ttf::iosevka-habamax`

Same result

**Comment by habamax** [comment]
> * Remove `node_modules`, `pacakge-lock.json` (if present), `yarn.lock` (if present)
> * Run `npm install`
> * Run `npm run clean`
> * Build your fonts

This should be the solution but we need step 0 -- properly remove prev font.

In my case it was cached by windows and newly applied font didn't have effect.

Thank you!
