### ISSUE TITLE
Character width issue (Aile, italic, cyrillic small letter sha, U+448)

### ISSUE THREAD

**Issue by arma-gast** [be5invis/Iosevka#909]
Hi!

First of all thanks for a great job!

There is an issue with width of cyrillic small letter sha (U+448) variants cv45(4) and cv45(6) in Aile Italic of any weight.

Screenshot taken from Iosevka specimen:

![image](https://user-images.githubusercontent.com/6592298/110755308-d7d9af80-8259-11eb-8077-72865e8ae472.png)

---

* Your font version: 5.0.5
* Your font variant: Aile (any) Italic
* Your operating system (name and version): macOS 11.2.3, macOS 10.15.7
* Your application using Iosevka: any

**Comment by be5invis** [comment]
This was fixed by an earlier commit. Should land in 5.0.6.
Closing.

**Comment by arma-gast** [comment]
Version 5.0.6, letter still has incorrect width:

![image](https://user-images.githubusercontent.com/6592298/111063432-7d418d00-84bf-11eb-9b7b-4726d49d4703.png)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/111064130-39229e00-8467-11eb-99d9-a2b33cc8dc84.png)

**Comment by be5invis** [comment]
5.0.7 should have this.
