### ISSUE TITLE
Missing Control Panel Metadata

### ISSUE THREAD

**Issue by WangZishi** [be5invis/Iosevka#91]
虽然不是太重要，但是要够完美不是吗？
![image](https://cloud.githubusercontent.com/assets/8288105/15927101/2e57dd0a-2e72-11e6-89fc-4d53c8c2037a.png)

**Comment by be5invis** [comment]
I have absolutely no clue how these fields are corresponded to OpenType fields. Other Open Source fonts like @tonsky’s Fira Code has this problem either. Perhaps to display this information I need a real certificate to sign them, instead of using a “dummy” DSIG.

**Comment by chrissimpkins** [comment]
Here are your name tables in Iosevka vs. those in Akzidenz-Grotesk for comparison:

<img width="1200" alt="iosevka" src="https://cloud.githubusercontent.com/assets/4249591/15953339/e6f9b8c2-2e97-11e6-88a2-b2f78543bd0d.png">

<img width="1204" alt="agrot" src="https://cloud.githubusercontent.com/assets/4249591/15953341/eb4ef464-2e97-11e6-8ae2-f2c7dd11e020.png">

Manufacturer names are coming from nameID 8.  I can't read the other values to interpret what they are in the fonts but hopefully this points to the missing data in your OpenType tables.

**Comment by be5invis** [comment]
@chrissimpkins Adobe's opensource fonts have this problem either.
Is it related to registering achVendID?

**Comment by chrissimpkins** [comment]
@be5invis how are you adding it, in a font editor?

**Comment by be5invis** [comment]
@chrissimpkins The script

**Comment by be5invis** [comment]
@chrissimpkins I’ve tried to add nameid 7, 8, 9, 10 to Iosevka and it does not work.
Also tested Adobe’s SSP and SCP, no metadata.
@kenlunde thought that it may be related to localized name strings, but Cambria, with metadata shown, has only English strings.

**Comment by be5invis** [comment]
As mentioned in adobe-fonts/source-code-pro, these metadata are maintained by a database maintained by Microsoft. I can not fix it for now.
If I got employed by Microsoft, I will reopen this.

**Comment by kenlunde** [comment]
@be5invis One of my guesses was going to be that the metadata was hard-wired. I am glad that my colleague, who responded to the related SCP and SSP issues that you opened, knew that it was.

Given that the metadata is hard-wired on a per-font basis, and because there are many fonts out in the wild, I doubt that Microsoft has the motivation nor desire to do anything about this.

**Comment by WangZishi** [comment]
原来是这样，至少知道了这暂时是不可能做到的了

**Comment by be5invis** [comment]
As mentioned [here](http://typedrawers.com/discussion/comment/20527#Comment_20527), these matadata are stored in `fms_metadata.xml`. If you REALLY want to show them you can edit this file.

**Comment by kenlunde** [comment]
It makes one wonder why font developers even bother with putting metadata into the 'name' table. Microsoft, as one of the founding companies of TrueType and OpenType, is setting a very poor example.

**Comment by be5invis** [comment]
@kenlunde
Perhaps for non-SFNT compatibility? There are many old bitmap fonts, and they have metadata shown.

**Comment by kenlunde** [comment]
I guess my point is that Windows should have a mechanism for extracting such metadata from fonts that include a 'name' table and include strings for these particular entries. Reputable font developers, such as Adobe, could easily be white-listed for this purpose, and the `OS/2.achVendID` value could be used to trigger this behavior. Adobe has two such values: _ADBE_ (for commercial fonts) and _ADBO_ (for open source fonts).
