### ISSUE TITLE
No ligatures after patching

### ISSUE THREAD

**Issue by mfocko** [be5invis/Iosevka#910]
I cannot seem to be able to patch Iosevka with Nerd Font patcher and keep the ligatures, the problem is not present with extended version of the font (either Iosevka itself or the Curly Slab variant).

Since the ligatures are fine for extended variants, I suspect it might be problem with the font, not the patcher.

Thanks for your help.

---

* Your font version: 5.0.5
* Your font variant: Iosevka (Curly Slab)
* Your operating system (name and version): Fedora 33 (patched on archLinux with latest version from git and dependencies in archLinux)
* Your application using Iosevka: Visual Studio Code

**Comment by mfocko** [comment]
Now I noticed that stylistic sets are kept for extended variants after patching, but not for the normal width of font.

**Comment by be5invis** [comment]
It should be something wrong with the patcher, or FontForge which is what the patcher uses.

**Comment by mfocko** [comment]
Thanks, I'll open issue there then

**Comment by mfocko** [comment]
seems to be fine with 5.0.6 🤔 what the hell is going on? :D

**Comment by be5invis** [comment]
Perhaps the patcher doesn't work sell. Closing as external.
