### ISSUE TITLE
Comma, semicolon and ampersand character variants

### ISSUE THREAD

**Issue by rekollekt** [be5invis/Iosevka#912]
Please more rounded/curly and more incised version too for comma and semicolon; and please more legible (smaller angle) versions too for ampersand:
![comma-semicolon-ampersand](https://user-images.githubusercontent.com/15945329/111060741-86bafd00-849f-11eb-8d07-9c4a4ac5dc2f.png)

**Comment by be5invis** [comment]
Ampersand is chosen to have current form as a design choice.
Comma looks legit.

**Comment by rekollekt** [comment]
Okay, but optically it is not enough readable (confluence) for eyes and deserve for more incised (bottom circles) and less angle (top circles) for variants:
![ampersand](https://user-images.githubusercontent.com/15945329/111062821-a9eba980-84ab-11eb-8429-ec1a8c0a682c.png)

**Comment by be5invis** [comment]
I do not want to change the shape too much, but this will help legibility.
![image](https://user-images.githubusercontent.com/240091/111065236-f0beac80-8475-11eb-9215-d4462ea74fe5.png)

**Comment by rekollekt** [comment]
> I do not want to change the shape too much, but this will help legibility.
> ![image](https://user-images.githubusercontent.com/240091/111065236-f0beac80-8475-11eb-9215-d4462ea74fe5.png)

A little more incised and rounded/curly? 🙂

**Comment by be5invis** [comment]
@rekollekt Sort of, and better smoothing around the overall shape.

**Comment by be5invis** [comment]
Comma change will be in 5.0.7 hotfix (and with another hotfix for Cyrillic SHA). Ampersand needs further investigation perhaps in 5.1.0.

**Comment by rekollekt** [comment]
THX

**Comment by NoxUltima** [comment]
Oh wait, what about comma shapes from JetBrains Mono as well? Perhaps that might be there in version 6.0, I'm not sure...

<img alt="Commas" src="https://user-images.githubusercontent.com/16898444/111114093-9e35cc80-8517-11eb-9d76-9e59ddb9cbf7.png">

**Comment by rekollekt** [comment]
@be5invis Any news about ampersand issue?

**Comment by be5invis** [comment]
@rekollekt I plan to modify the ampersand to something like this, so it will be more clear.
![image](https://user-images.githubusercontent.com/240091/115342972-fb98eb00-a15f-11eb-9cba-d04dfdfb70ca.png)

**Comment by rekollekt** [comment]
Please add more incised for readable ampersand:
![png](https://user-images.githubusercontent.com/15945329/120096622-d4edad00-c12c-11eb-9b98-72e64b83b1d5.png)
