### ISSUE TITLE
Backslash `\\` ligatures

### ISSUE THREAD

**Issue by NoxUltima** [be5invis/Iosevka#914]
- [x] A programming language requires this ligation. Provide the information below. (JS, Java, C#, Python, etc)
- [x] This ligation is implemented in other programming fonts. Provide samples below.

------

Sometimes backslashes can be quite confusing for escape sequences, in strings and regular expressions in many (or any) programming languages.

It can be quite difficult to count the number of escape backslashes when there are many of them in a row, therefore we cannot distinguish what characters we are escaping, such as in the sequence `` \\\` `` (literal `` \` ``) and `\\\\` (literal `\\`). 

Below is Fira Code (`ss06` enabled).  

<img alt="Backslashes" src="https://user-images.githubusercontent.com/16898444/111117210-1605f600-851c-11eb-8f7e-3a92eb103c03.png">

What it would do is slightly thinning the *first* backslash in a pair of characters.

Another option is to slightly move the first backslash to the right so that each pair of backslashes can be distinguished. The lighter color shows the original position of the backslashes when used on their own.

<img alt="Backslashes" src="https://user-images.githubusercontent.com/16898444/111117068-d3441e00-851b-11eb-8b4f-a3718400072a.png">

Or we can combine the above two ideas to produce something like this. The lighter backslash is Iosevka `Extralight` weight, and the regular glyphs are the `Regular` weight.

<img alt="Backslashes" src="https://user-images.githubusercontent.com/16898444/111115841-038abd00-851a-11eb-8040-e1b28d2af098.png">

---

If there is any other suggestions regarding how to render backslash sequences more properly and clearly, please let me know down in the comments! :smile:

As always, thanks for the beautiful font @be5invis!

_**Additional Comments:** Cascadia Code has a dedicated `\\` ligature, where the two backslashes are spaced a little bit more closer, but it does not work for 3 consecutive `\` and longer._

_Recursive Mono also has some ligatures for common escape sequences like `\b` `\d` `\n` `\r` `\s` `\t` but each are separate ligatures._

**Comment by NoxUltima** [comment]
Another option is to slightly move or "kern" the first backslash to the right so that each pair of backslashes can be distinguished. The lighter color shows the original position of the backslashes when used on their own.

<img width="360" alt="Backslashes" src="https://user-images.githubusercontent.com/16898444/111115027-eb666e00-8518-11eb-80ae-9ec745eb4f2c.png">

**Comment by be5invis** [comment]
The problem is, you _need_ to distinguish whether a backslash should be interpreted as an escape leader. Like: do you want to turn the two-backslash sequence in UNC paths (`\\machine\directory\file`) into an ligation?

**Comment by NoxUltima** [comment]
> The problem is, you _need_ to distinguish whether a backslash should be interpreted as an escape leader. Like: do you want to turn the two-backslash sequence in UNC paths (`\\machine\directory\file`) into an ligation?

I am aware of that.

Shifting the backslash to the right won't change anything...

This is only used for only for specific languages that uses backslashes for escapes, especially C-derived languages like Java, JS, Swift and more. In strings and regular expressions are _all_ where they really appear.

**Comment by be5invis** [comment]
Mark as Needs Justification.
I do not think there's any text editor that could apply different OT features depending on the token's type. I could create an `STRG` feature for strings only, but turning them on is a harder task.

**Comment by NoxUltima** [comment]
Yeah you might. 

And you're right.
