### ISSUE TITLE
Would like parenthesis and slash similar to version 2.x

### ISSUE THREAD

**Issue by npydyuan** [be5invis/Iosevka#915]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [?] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.
![old paren and slash](https://user-images.githubusercontent.com/11370291/111401074-97819380-8696-11eb-84cd-3e9adb976758.jpeg)
------
(I use the "curly" style of Iosevka exclusively.) I prefer the look of the taller parenthesis and slash characters as they were in the version 2.x days (the ones closer to the word "old" in the attached image). They stand out better to my eyes when scanning across my screen. They look more dynamic, confident, and perhaps playful or dashing. Sorry, it's hard to explain! The older parenthesis and slash characters just make me happy when I see them. I would like to be able to choose them when I customize. Thanks for considering!

**Comment by be5invis** [comment]
I think you could try increase `paren-size` with `metric-override`:

```toml
[buildPlans.iosevka-custom.metric-override]
parenSize = 1000 # 966 is default
```

**Comment by wimstefan** [comment]
> ```toml
> parenSize = 1000 # 966 is default
> ```

I was curious and tried that immediately but I can't see a difference ...

**Comment by npydyuan** [comment]
At first I didn't either, but there is a difference; it's just subtle. However when increasing the value to 1120 I now have parens and slashes as tall as the old ones, with the additional difference that they extend lower below the baseline as well.
<img width="320" alt="1000" src="https://user-images.githubusercontent.com/11370291/111602559-748fd600-87a1-11eb-9ca0-0278f0254226.png">
<img width="320" alt="1120" src="https://user-images.githubusercontent.com/11370291/111602558-748fd600-87a1-11eb-9106-b160b0cc9c6b.png">

**Comment by be5invis** [comment]
Resolve as fixed since the metric is overridable.
