### ISSUE TITLE
i dot off center

### ISSUE THREAD

**Issue by AlsoScratch** [be5invis/Iosevka#918]
Describe your problem here. Provide pictures and files if necessary.

---

* Your font version: 5.0.8
* Your font variant: Iosevka Fixed
* Your operating system (name and version): macOS 11.1 (20C69)
* Your application using Iosevka: 

<img width="101" alt="Screenshot 2021-03-19 at 16 20 32" src="https://user-images.githubusercontent.com/48752273/111751172-1d881f00-88cf-11eb-96df-2c8e07575a9a.png">
It looks a bit too much to the right

**Comment by be5invis** [comment]
The geometry itself looks fine. Rounding error is **not** controllable and is mostly impossible to fix.
![image](https://user-images.githubusercontent.com/240091/111817045-c10b0c80-889a-11eb-9f63-e937a5b7bd5e.png)

**Comment by AlsoScratch** [comment]
It used to look better in the previous versions

**Comment by be5invis** [comment]
Revert to last anchor placement, hope it worked.
