### ISSUE TITLE
Wider U+2665

### ISSUE THREAD

**Issue by rekollekt** [be5invis/Iosevka#919]
Please more harmonized U+2665:
![u](https://user-images.githubusercontent.com/15945329/111862203-10614380-8954-11eb-999a-1ec22077faf4.png)

**Comment by be5invis** [comment]
It needs to fit in one cell, and vertically squashing it will make it too small.

**Comment by rekollekt** [comment]
For Aile too?

**Comment by be5invis** [comment]
I do not think we could make suit card symbols having different widths.

**Comment by rekollekt** [comment]
Okay, but it's so very longish and therefore unfriendly, however U+2665 is friendly and thus more roundish according to semantic of shape :)

**Comment by be5invis** [comment]
Well, `U+2665` is introduced to represent the Heart symbol in playing cards suit, so making it longer is not a bad choice, especially considering Iosevka is originally made as a very slender, monospace typeface. Heart for "friendliness" and "love" may use `U+2764` (Heavy Black Heart) instead.

**Comment by rekollekt** [comment]
Good idea but I didn't find U+2764 in characters.

**Comment by be5invis** [comment]
U+2764 is not included in the current version. Please file a separate issue requesting it.

**Comment by be5invis** [comment]
Closing in favor of #920.
