### ISSUE TITLE
symbol request

### ISSUE THREAD

**Issue by WangZishi** [be5invis/Iosevka#92]
## White Hexagon
Character: `⬡`
Unicode number: `U+2B21`
## Black Hexagon
Character: `⬢`
Unicode number: `U+2B22`
## Horizontal Black Hexagon
Character: `⬣`
Unicode number: `U+2B23`

终端里面的一些地方会使用这些符号，在1.8.6里面显示出来的是方框，希望能够加入这些。

**Comment by be5invis** [comment]
Consolidated to #81. Closed.
