### ISSUE TITLE
i/j dot off center #2

### ISSUE THREAD

**Issue by pv4** [be5invis/Iosevka#921]
The issue mentioned in #918 is also observable on `i=hooky` and `j=flat-tailed` (I use these).

According to what I see at https://raw.githubusercontent.com/be5invis/Iosevka/master/images/charvars.png it also seems to happen on other "top serifed" variants of `i` and `j` (in less degree on some of them). I'm afraid it's not an "alignment issue" but instead is a "perception issue" (as well as e.g. "overshoot" one).

On the attached image (imho):
- a `red` circle selects the affected variants,
- a `yellow` circle selects the variants affected in less degree,
- a `dashed yellow` circle selects the variant I'm not sure about whether it is affected in less degree or unaffected at all.

Also note please that `j=2` variant has dot placement different from other "top serifed" `j` variants. And `j=4` variant has the dot moved to the left even more.

Could you please spend some time investigating the question and fix the issue in general if possible?

P.S. I'm very sorry if this issue hurts you :( On a huge font size I do see the glyphs are geometrically symmetric and correct. But my perception (and as far as we see, not only my) tells another story.

![image](https://user-images.githubusercontent.com/2502094/111925757-16653a80-8aa2-11eb-9e99-74fc8d5424cc.png)

**Comment by be5invis** [comment]
My plan is:

 * Serifed `i` and `l`: dot is centered to 1/2 glyph width;
 * Base shape with top serif towards left and bottom tail towards the right: dot is centered to 1/2 glyph width;
 * Base shape with only top serif, or with top serif and bottom tail towards the left: dot is aligned to the left 1/3 of the vertical bar;
 * Otherwise (straight bar, or only bottom tail): dot is aligned to the center of the vertical bar.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/111927259-5d850880-8a6d-11eb-8e6b-4c0cbc563369.png)
![image](https://user-images.githubusercontent.com/240091/111927272-65dd4380-8a6d-11eb-8b1f-20f694178b50.png)

**Comment by pv4** [comment]
Now `j`s look ideally.

>     * Base shape with only top serif, or with top serif and bottom tail towards the left: dot is aligned to the left 1/3 of the vertical bar;

These ones are fine too.

>     * Serifed `i` and `l`: dot is centered to 1/2 glyph width;
>     * Base shape with top serif towards left and bottom tail towards the right: dot is centered to 1/2 glyph width;

Looking at the pictures I think these would still look better if moved to the left 1/3 of the vertical bar as well. What do you think?

**Comment by be5invis** [comment]
> Looking at the pictures I think <u>these</u> would still look better if the dot is aligned to the left 1/3 of the vertical bar as well.

Could you please clarify what are "these"?

**Comment by pv4** [comment]
In the comment above I quoted a part of your message and the commented it.

So under "these" I mean "serifed i and l" and "base shape with top serif towards left and bottom tail towards the right". In other words I think ALL top-serif variants would look better with the dot aligned to the left 1/3 of the vertical bar.

This decision was not obvious for me when I was looking at the original variant table before the commit. But after you made the change I think the new ("dot is aligned to the left 1/3 of the vertical bar") variants look much better, and that the rest of top-serifed variants would look much better too if being changed the same way.

I mean, I'd suggest the following plan:

- Serifed i and l: _dot is aligned to the left 1/3 of the vertical bar_;
- Base shape with top serif towards left and bottom tail towards the right: _dot is aligned to the left 1/3 of the vertical bar_;
- Base shape with only top serif, or with top serif and bottom tail towards the left: dot is aligned to the left 1/3 of the vertical bar;
- Otherwise (straight bar, or only bottom tail): dot is aligned to the center of the vertical bar.

**Comment by be5invis** [comment]
@pv4 The "dot is aligned to the left 1/3 of the vertical bar" decision is made because for these variants, the bar is actually off-center (for visual balancing of course). For the _serifed_ and _z-like_ variants, the bar is mostly right at the center of glyph width, therefore shifting the dot is not necessary. If I do that, you will see the dots are precepted _left-offseting_.

**Comment by pv4** [comment]
Here is r5.0.9 custom build of two glyphs with different "algorithms" of dot placement (`ftview` with hinting turned off). `heavy` weight at the top, and `regular` weight at the bottom. On both it's visible that dot placement relative to the vertical bar is different.

The `j` variant is more pleasant for me. Probably, for me the best variant would be to align the right dot border to the right vertical bar border (taking overshoot into account). But that's just me.

![image](https://user-images.githubusercontent.com/2502094/112055663-0bb4af00-8b4f-11eb-9c55-97d78d3d0dab.png)

**Comment by be5invis** [comment]
@pv4 It's all about balance. The `j` has all the decorative features at left, so the dot needs to be moved leftward a little, otherwise, it will look unbalanced; The `i`, on the other hand, has decorative features at _both left and right_, so there's no need for the dot to be moved.

**Comment by pv4** [comment]
Well, you had shown that you know more details about fonts even if they're related cyrillic fonts (my "native speaking" fonts) :)

And now I'm not even sure I'm right. I just saw an inconsistence and decided to let you know about it.

I trust you, and your words sound logically. So let's close the issue.

Thanks for the detailed explanations!

**Comment by NoxUltima** [comment]
Oh wait something's a bit off with the j in Aile/Etoile... now it's too far skewed off to the right...

![2021-03-24 15_19_45-Ionix Propo Condensed Light (OpenType)](https://user-images.githubusercontent.com/16898444/112270267-4a6d6680-8c2e-11eb-95ff-4c583e9e9200.png)
