### ISSUE TITLE
Rounded e variants for æ and œ too

### ISSUE THREAD

**Issue by NoxUltima** [be5invis/Iosevka#923]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

As of now, the e part in both characters is still straight when `e=rounded`. I suggest rounding the e part of the &aelig; and &oelig; ligatures/letters, especially in italics. Here's two fonts I brought below for comparison.

<img alt="aeoe italics" src="https://user-images.githubusercontent.com/16898444/112272775-776f4880-8c31-11eb-9eca-f25da34b3a50.png">

(Note, in some fonts such as Roboto Mono andi the single-storey variant of a is used, but in order not to get confused especially at small sizes the a part of the &aelig; is double-storey)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/112299261-de522900-8c54-11eb-9786-0e6302b49951.png)
