### ISSUE TITLE
j dot off center #3 (Aile/Etoile)

### ISSUE THREAD

**Issue by NoxUltima** [be5invis/Iosevka#924]
Something's a bit off with the j in Aile/Etoile. The dot is too far skewed off to the right because its narrower than the normal mono/slab counterpart. I think the dot's position was hardcoded.

This is evident in the serifed variants of `j`.

![2021-03-24 15_26_10-Iosevka Customizer and 1 more page - Profile 1 - Microsoft​ Edge](https://user-images.githubusercontent.com/16898444/112270966-31b18080-8c2f-11eb-8091-5efe94156bf2.png)

---

* Your font version: (Release or git, version) 5.0.9
* Your font variant: Iosevka Custom
* Your operating system (name and version): Windows 10
* Your application using Iosevka: the specimen website

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/112286727-d8eee180-8c48-11eb-8e74-2620ca82cfe9.png)

**Comment by NoxUltima** [comment]
Thanks so much!
