### ISSUE TITLE
Slab Uppercase A with Top Serif

### ISSUE THREAD

**Issue by Kotori142857** [be5invis/Iosevka#925]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

![COURIER PRIME](https://user-images.githubusercontent.com/43498546/112319755-5702c500-8ce9-11eb-8ca0-0dbdb355f459.png)
![CUTIVE MONO](https://user-images.githubusercontent.com/43498546/112321235-c4632580-8cea-11eb-8ff1-e3ab0c4c3068.png)

**Comment by pv4** [comment]
@be5invis , I guess this should only be applied to `*-motion-serifed` variants, not the default `slab`. In commit 274358f97d39a51e13483301c4cb95cc18da8068 it's applied even for slab variant of non-motion-serifed `straight/curly`. Is this a bug? Should I open a new issue for this?

**Comment by be5invis** [comment]
@pv4 It's a new variant with 3 serifs (always visible).
