### ISSUE TITLE
Character Variant Request: Box version of colon, semicolon, period and comma.

### ISSUE THREAD

**Issue by PyGamer0** [be5invis/Iosevka#927]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

Menlo
![image](https://user-images.githubusercontent.com/64531844/112710776-9d267700-8ee9-11eb-8d3d-0cc267c0e50f.png)

Monoid
![image](https://user-images.githubusercontent.com/64531844/112710939-bbd93d80-8eea-11eb-8c60-5e1269da2771.png)

**Comment by be5invis** [comment]
Punctuation only. Diacritics will not be synchronized.

**Comment by NoxUltima** [comment]
That includes `!` and `?`.

**Comment by NoxUltima** [comment]
> Punctuation only. Diacritics will not be synchronized.

Does that include i and j?

**Comment by be5invis** [comment]
> Does that include lowercase i and j?

No. Diacritic influence is why I rejected a similar past request. Punctuation-only seems legit.

**Comment by be5invis** [comment]
However, there are more derived punctuations, like curly quotes, Math (`∷`), APL symbols (`⍮`) …

**Comment by NoxUltima** [comment]
I was just wondering. Thanks @be5invis

**Comment by be5invis** [comment]
To realize this is **a lot of** work and may introduce thousands of glyphs, even if we care only about punctuations.

**Comment by PyGamer0** [comment]
I actually only want these 4 characters 😄

Thanks for the font 😀, it's amazing.

**Comment by PyGamer0** [comment]
Well I only need these 4 characters.

**Comment by PyGamer0** [comment]
Just noticed this now; thanks.
