### ISSUE TITLE
Extra word typo in copyright notice

### ISSUE THREAD

**Issue by Ming-Hua** [be5invis/Iosevka#929]
After installing Iosevka fonts and when viewing it in Windows 10's font preview (accessed from Start Menu - Settings - Personalize - Fonts, exact names may be different, as I'm using Chinese version of Windows and the above is my translation), I spotted an extra word in the font's copyright description.  It says (emphasis mine):

"... This **is** licence is available with a FAQ at: ..."

The first "is" should be deleted and the sentence should read "This licence is available...", IMO.  And I believe this copyright description is embedded in the font files and therefore the typo should be fixed by the Iosevka developers.

Thanks for the great font and keep up the good work.

---

* Your font version: 5.0.9
* Your font variant: Iosevka Fixed TTF (but presumably the bug exists for all variants)
* Your operating system (name and version): Windows 10
* Your application using Iosevka: Windows 10 Settings - Personalize - Fonts

**Comment by alexeyten** [comment]
The text is here https://github.com/be5invis/Iosevka/blob/4866cbb6eb4cb33348baeca6d80049f41635da43/params/parameters.toml#L7
