### ISSUE TITLE
Issue with character width

### ISSUE THREAD

**Issue by WangZishi** [be5invis/Iosevka#93]
Name: Heavy Wide-Headed Rightwards Arrow
Character: ➔
Unicode number:  U+2794

不是很懂这个为什么会这个样子，但我怀疑是宽度问题
Not really understand why this like this, but I suspect the problem is the width
![image](https://cloud.githubusercontent.com/assets/8288105/15972808/0fb0bfbe-2f73-11e6-9c29-8f47e984c544.png)

![image](https://cloud.githubusercontent.com/assets/8288105/15973150/6c310e0a-2f74-11e6-83f3-7244e3918bf0.png)
这里也会直接叠起来
Here also directly stack up

英语不是很好，我用Google翻译的，见谅了。
English is not very good, I used Google Translate, forgive me.

**Comment by be5invis** [comment]
➔ is not included in Iosevka. I can not control the fallback behavior, especially for Conemu.

**Comment by WangZishi** [comment]
那么，如果我没有理解错的话，这个宽度应该是 ConEmu 控制的，这是 ConEmu 的 Bug 是吗？我应该去给 ConEmu 提这个 issue？

**Comment by be5invis** [comment]
Perhaps.
