### ISSUE TITLE
Fix designs of some Cyrillic letters: ЋЂҺ

### ISSUE THREAD

**Issue by NoxUltima** [be5invis/Iosevka#931]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

What I'm concerned about is the top-bars and humps of the three Cyrillic uppercase letters described below. 

At the moment, the top bars of the `cyrl-Dje` and `cyrl-Tshe` are too short to the point that they easily get confused for the top slab in `cyrl-Shha`. In Slab, I suggest the top bars should have serifs like `T`, as in Courier New.

As in Cascadia Code I would suggest basing the design of `cyrl-Dje` and `cyrl-Tshe` on `cyrl-Shha` too, as the hump is flat, lowered and less rounded, so the design is more consistent and less confusing against their lowercase. 

The below image shows how they look like in various programming fonts, for comparison. The green ones are what I proposed.

<img alt="ЋЂҺ" src="https://user-images.githubusercontent.com/16898444/113238438-41dfe600-9255-11eb-833f-3e63cc85969d.png">

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/113252822-36061b00-9279-11eb-9005-cd0b6418395c.png)
![image](https://user-images.githubusercontent.com/240091/113252850-3dc5bf80-9279-11eb-9b88-d761fcc9d577.png)

**Comment by be5invis** [comment]
I'd like to keep the arch shape. The bar length is fixed, and in Slab vertical serifs are added.

**Comment by NoxUltima** [comment]
There we go!

**Comment by 8118553189** [comment]
> - [x] The requested variant shape does not go too far away from Iosevka's design.
> 
> - [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
> 
> - [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.
> 
> 
> 
> ------
> 
> 
> 
> What I'm concerned about is the top-bars and humps of the three Cyrillic uppercase letters described below. 
> 
> 
> 
> At the moment, the top bars of the `cyrl-Dje` and `cyrl-Tshe` are too short to the point that they easily get confused for the top slab in `cyrl-Shha`. In Slab, I suggest the top bars should have serifs like `T`, as in Courier New.
> 
> 
> 
> As in Cascadia Code I would suggest basing the design of `cyrl-Dje` and `cyrl-Tshe` on `cyrl-Shha` too, as the hump is flat, lowered and less rounded, so the design is more consistent and less confusing against their lowercase. 
> 
> 
> 
> The below image shows how they look like in various programming fonts, for comparison. The green ones are what I proposed.
> 
> 
> 
> <img alt="ЋЂҺ" src="https://user-images.githubusercontent.com/16898444/113238438-41dfe600-9255-11eb-833f-3e63cc85969d.png">
> 
>
