### ISSUE TITLE
Weird behaviour with dotted i/j and diacritic marks on (Xe/Lua)LaTeX

### ISSUE THREAD

**Issue by cagprado** [be5invis/Iosevka#932]
Diacritic marks (including dotted i/j) have strange behavior on both XeLaTeX and LuaLaTeX using `fontspec` when enabling Caracter Variant OTF feature. There's also a problem only with XeLaTeX when choosing a Stylistic Set.
The problem does *not* occur for pre-customized fonts, only if I choose to select the styles/sets within `latex`.
The problem does *not* occur if no style/set is chosen and the font is used as default.

For XeLaTeX, using the font have no problem in normal contexts but the diacritic marks disappear when using with `\url{}` command (matter of fact that's how I first noticed it, j's and i's without the dot):

![xelatex](https://user-images.githubusercontent.com/910629/113238646-c07f6680-92db-11eb-9f87-7b9bcfaad6b5.png)

For LuaLaTeX the problem is kind of opposite, `\url{}` works fine but then on normal contexts, using the font leads to stacked diacritic marks:

![lualatex](https://user-images.githubusercontent.com/910629/113238824-19e79580-92dc-11eb-91ff-c08619c60e2f.png)

A minimum working example code:
```latex
\documentclass{article}
\usepackage{hyperref, fontspec}

\setmonofont {Iosevka Slab} [
  % any combination of these three lines trigger the problem
  CharacterVariant={85:2} % Lua/Xe both break
  StylisticSet=20         % only breaks in XeLaTeX
  RawFeature=+ss20        % only breaks in XeLaTeX
]

\begin{document}
  \noindent \texttt {This is a jizz wót?} (texttt) \\
  \noindent \url    {This is a jizz wót?} (url)
\end{document}
```

I think this might be related to #kovidgoyal/kitty/issues/3026.  Although issues with kitty-iosevka are well known, this one in particular seems to share the same trigger (i/j/diacritic marks break rendering when ss or cv are selected).

---

* Your font version: 5.1.1-1 (Aur: https://aur.archlinux.org/packages/ttc-iosevka-slab/)
* Your font variant: Iosevka Slab, not pre-customized
* Your operating system (name and version): ArchLinux (rolling)
* Your application using Iosevka: xelatex/lualatex (fontspec)

**Comment by be5invis** [comment]
I think it is a problem about how those TeX programs deal with one-to-many substitution? When enabling CV/SS features, composite letters (with diacritics) will get decomposed into bases and diacritics, and then the base will be substituted. + @clerkma

**Comment by be5invis** [comment]
From @clerkma, it looks like XeTeX doesn't properly handle OT's one-to-many substitutions correctly in math mode, which is used by Iosevka's CV/SS support (it breaks `i` into `ı` and `̇` and applies CV substitution to the bar part). Switching into such behavior is intentional to reduce glyph quantity (otherwise it will break OT's 64K boundary easily).

Resolve as External. Please file a bug to XeTeX.
