### ISSUE TITLE
Broken shape of small capital AE in Slab

### ISSUE THREAD

**Issue by NoxUltima** [be5invis/Iosevka#933]
Describe your problem here. Provide pictures and files if necessary.

![small capitals 3](https://user-images.githubusercontent.com/16898444/113241031-54a8e980-925a-11eb-9e85-e5d95d103ea0.png)

---

* Your font version: (Release or git, version): 5.1.1
* Your font variant: Iosevka Slab
* Your operating system (name and version): Windows
* Your application using Iosevka:

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/113251347-fa6a5180-9276-11eb-8956-0e27ea83c76f.png)
