### ISSUE TITLE
Shorter stemmed lowercase t variants

### ISSUE THREAD

**Issue by NoxUltima** [be5invis/Iosevka#934]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [ ] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

Since issue #672, there are three separate variants for the flat-hooked `t` with three different stem heights, the highest being the ascender height (shared among most of the t variants currently). 

I was thinking could we expand this to the other tailed variants of `t` too (curly-hooked, asymmetric and crossed `t`)? 

![90947286-76e7a880-e3e9-11ea-859b-3a88683bebee.png](https://user-images.githubusercontent.com/16898444/113372925-2ab4fd00-9316-11eb-899f-9e410425985f.png)

For instance, in Futura, the t height is shorter than both the capital and ascender height.

![Futura-Font.jpg](https://user-images.githubusercontent.com/16898444/113374373-74ebad80-9319-11eb-845b-393941bf1045.jpg)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/113374916-27743e00-9323-11eb-8409-a57946790c0a.png)
