### ISSUE TITLE
r=compact-* top tail length?

### ISSUE THREAD

**Issue by pv4** [be5invis/Iosevka#937]
The "top tail" length (*) of latin small `r` is same for `serifless` and `compact` variants. But for their `top-serifed` variants this's not true, and the length is different. The `compact-serifed` seems to be affected as well. Not sure whether `corner-hooked-*` variants are affected.

Could you please consider making the "top tail" of `compact` serifed variants as long as their "regular" equivalents? Would it look better?

![image](https://user-images.githubusercontent.com/2502094/113588700-0449d700-9620-11eb-9768-90530d8ed3cd.png)

(*) Under "top tail length" I mean the horizontal distance between the right side of the whole glyph and the right side of the vertical bar.

**Comment by be5invis** [comment]
I changed that in 5.2.1 and it looks more balanced in the text flow.
Closing as by design.
