### ISSUE TITLE
Distribute fonts and css in git repository to make cdnjs work

### ISSUE THREAD

**Issue by aymanbagabas** [be5invis/Iosevka#942]
**Is your feature request related to a problem? Please describe.**
https://github.com/be5invis/Iosevka/issues/468

**Describe the solution you'd like**
Distribute fonts in the Git repository at `dist/{font-variant}/*.(css|ttf|woff2)`

**Describe alternatives you've considered**
Host distributed fonts in a CDN

**Additional context**
I've created a draft PR for cdnjs/packages https://github.com/cdnjs/packages/pull/685 to add Iosevka to their CDN, however, currently Iosevka does not distribute the fonts in the Git repository rather in Github releases which cdnjs doesn't support.

cdnjs supports either npm/git package distributions. If we can distribute the fonts in a directory along with tagging each release, we would be able to use cdnjs as a free CDN service at the cost of having the fonts and css assets in the repository. [cdnjs/packages/CONTRIBUTING](https://github.com/cdnjs/packages/blob/master/CONTRIBUTING.md)

@be5invis what do you think?

**Comment by be5invis** [comment]
It will only have Iosevka / Slab / Aile / Etoile, no SS or Term / Fixed variations...

**Comment by aymanbagabas** [comment]
> It will only have Iosevka / Slab / Aile / Etoile, no SS or Term / Fixed variations...

It'd also be great if the generated css files are minified.

Lmk if I can help with anything:)

**Comment by be5invis** [comment]
Alternatively, I think it is possible for you to set up a repository that holds web font versions of Iosevka, and you can grab its contents from Iosevka Releases using an automated workflow. I do not want to maintain "packages" on my own since it will reduce the bandwidth that is used in actual font development.

**Comment by aymanbagabas** [comment]
@be5invis would you be interested in using GH actions to automate this process? I can come up with a GH actions workflow to build the fonts, tag the release, and push them to another repository.

**Comment by Diablo-D3** [comment]
I, too, wish there was a repository that just held the most recent release of files.

**Comment by aymanbagabas** [comment]
Idea: Automate building and publishing the fonts using GitHub actions.

We could use GitHub actions to automatically build the fonts, and then push them back to the repository on every commit to master under a directory such as `dist`. For releases, we could also create a workflow to trigger when a release is created, and since we already have the fonts built and stored in the repository, we could [generate release notes](https://github.com/be5invis/Iosevka/tree/master/utility/generate-release-note), package the fonts and update the release body to have the notes and the packaged fonts.

I noticed [FiraCode](https://github.com/tonsky/FiraCode) font is doing a similar thing but only uploads the font assets to GitHub actions artifacts.

Quick Google search gave me these two actions that would be useful in automating this
- https://github.com/marketplace/actions/github-push
- https://github.com/marketplace/actions/update-github-release

**Comment by be5invis** [comment]
It should be better to set up a new repository that grabs releases of Iosevka and once the version is changed, publish its contents.

**Comment by aymanbagabas** [comment]
> It should be better to set up a new repository that grabs releases of Iosevka and once the version is changed, publish its contents.

@be5invis Do you mind creating a new repository `Iosevka-font` for instance? If we're going to leverage Github actions, both repositories should have the same owner. Then we'd add a workflow in this repository to trigger on push and/or new release to build the fonts, tag them, and push them to the other repository.

**Comment by be5invis** [comment]
@aymanbagabas I think grabbing releases doesn't need extra auth. It's just an artifact download.

**Comment by aymanbagabas** [comment]
@be5invis I've created a new repository [iosevka-fonts](https://github.com/aymanbagabas/iosevka-fonts) that contains the releases in `dist/` and checks for updates daily using a corn job. Let me know if this looks good. I only included these fonts `iosevka iosevka-aile iosevka-curly iosevka-curly-slab iosevka-etoile iosevka-slab iosevka-sparkle`

**Comment by be5invis** [comment]
@aymanbagabas LGTM.

**Comment by aymanbagabas** [comment]
I think this can be closed now since https://github.com/cdnjs/packages/pull/705 is merged. Anyone can use cdnjs and/or JSDelivr to get the fonts from [iosevka-fonts](https://github.com/aymanbagabas/iosevka-fonts) as the example below:

```
https://cdn.jsdelivr.net/gh/aymanbagabas/iosevka-fonts@v6.1.2/dist/iosevka/iosevka.min.css
https://cdnjs.cloudflare.com/ajax/libs/Iosevka/6.0.0/iosevka-etoile/iosevka-etoile.min.css
```

Available fonts are `iosevka iosevka-aile iosevka-curly iosevka-curly-slab iosevka-etoile iosevka-slab iosevka-sparkle` you can replace the font version and variant in the URL.

**Comment by aymanbagabas** [comment]
@be5invis should we add a short blurb under Installation in the readme?

**Comment by be5invis** [comment]
@aymanbagabas Feels free to submit a PR
