### ISSUE TITLE
charvars.png doesn't match (new) capital J variants in 6.0.0-preview.2

### ISSUE THREAD

**Issue by fcintra3** [be5invis/Iosevka#946]
The image file charvars.png hasn't been update to reflect the reorganization of capital J variants. I suppose other variant samples may also be out of date, but I haven't checked them out.

![variants2](https://user-images.githubusercontent.com/69120483/114457870-e8f94180-9bb4-11eb-9b04-0ba41fa51c68.png)

![variants1](https://user-images.githubusercontent.com/69120483/114457827-de3eac80-9bb4-11eb-9185-247f908d725a.png)

**Comment by be5invis** [comment]
Images will get synchronized every time when publishing a new version. This will be automatically fixed in preview.3.
Closing.
