### ISSUE TITLE
4 with lower horizontal bar

### ISSUE THREAD

**Issue by Kotori142857** [be5invis/Iosevka#947]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [ ] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

![4](https://user-images.githubusercontent.com/43498546/114566729-23daa280-9ca5-11eb-9035-014c58324dc0.jpg)

**Comment by be5invis** [comment]
Should be able to simply lower all bars in the open variant

**Comment by be5invis** [comment]
Making the bar that low doesn't sync well with other digits. Adjusted to this:
![image](https://user-images.githubusercontent.com/240091/114811259-a2e1e080-9d62-11eb-88ca-512fc711bca3.png)
