### ISSUE TITLE
Request for 3 more characters used by Webpack logs

### ISSUE THREAD

**Issue by akarzim** [be5invis/Iosevka#949]
- The requested character is...
  - [ ] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [x] Symbol
- [ ] Some other monospace/programming fonts supported this character. Provide images below.

------

Webpack logs use 3 characters missing in Iosevka :
- ℹ [U+2139](https://unicode-table.com/en/2139/)
- ｢ [U+FF62](https://unicode-table.com/en/FF62/)
- ｣ [U+FF63](https://unicode-table.com/en/FF63/)

Logs:

```
ℹ ｢wdm｣: Compiling...
ℹ ｢wdm｣: Compiled successfully.
```

Expected result:

<img width="835" alt="image" src="https://user-images.githubusercontent.com/130560/114840510-2b01cd80-9dd7-11eb-8432-ed0a7472e4e9.png">

**Comment by be5invis** [comment]
I do not think most monospace fonts do them, especially `U+FF62` and `U+FF63`, which are the half-width counterpart of CJK symbols `「` and `」`.

**Comment by be5invis** [comment]
`ℹ` is added as a slightly bolder `i`.

**Comment by be5invis** [comment]
Mark `U+FF62` and `U+FF63` as Needs Justification.

**Comment by akarzim** [comment]
Thanks for the information symbol 🙇 

Maybe `U+FF62` and `U+FF63` are out of scope for Iosevka. And maybe `U+2E22` ... `U+2E25` would have been a better choice of characters by the Webpack team. By the way, these characters are not supported by Iosevka either ;)

**Comment by be5invis** [comment]
`U+2E22` ... `U+2E25` are just added in Dev.

**Comment by akarzim** [comment]
Lovely! Thanks again for the great work you do on this font!
