### ISSUE TITLE
Add cursive variant for `capital-z` as well

### ISSUE THREAD

**Issue by wimstefan** [be5invis/Iosevka#951]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
_I'm only asking for a capital version of an existing Iosevka glyph variant._ 
------
You've provided us already with cursive variants for `z` in #852 and especially `z = "cursive-with-horizontal-crossbar"` looks simply incredible! I was wondering if you could provide those variants for `capital-z` as well?

PS: there is a little typo by the way in the description of the two cursive variants with a crossbar - `dsitinction` instead of `distinction`

**Comment by be5invis** [comment]
I do not think cursive makes sense for capital letters.
Mark as Needs Justification.

**Comment by wimstefan** [comment]
Fair enough. For me it is about visual consistency and none of the `capital-z` variants matches the `cursive-with-horizontal-crossbar` which is vert distinct as you can see below:
![scrot-2021-04-16-12:16](https://user-images.githubusercontent.com/4605934/115010528-d1b89d80-9ead-11eb-8de4-43c33c331bc7.png)

I understand your reasoning that Iosevka is **not** a handwriting typeface but it offers possibilities that go beyond a mere monospace. The `capital-z` is also an exception in the sense that `cursive-with-horizontal-crossbar` is so distinctive that it much more needs an equivalent capital pair than the other letter pairs ...

But of course I'll respect whatever your decision will be! 🙏

**Comment by wimstefan** [comment]
Thank you very much! 🙏
