### ISSUE TITLE
Slanted e and semicircular double storey g (Monofur)

### ISSUE THREAD

**Issue by NoxUltima** [be5invis/Iosevka#956]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [ ] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

I found Monofur while back and found two awesome letter forms of e and g that Iosevka can hopefully support.

Monofur's slanted e and single-storey double-arc g:

![download.png](https://user-images.githubusercontent.com/16898444/115104170-47de0280-9f89-11eb-9602-b62cce889465.png)

The same variant of lowercase g in Nexa:

![a3c391eebc850d5e2c49cba446b872c3.gif](https://user-images.githubusercontent.com/16898444/115104204-752ab080-9f89-11eb-88eb-4cb82c29ec9c.gif)

**Comment by be5invis** [comment]
Only one monospace font has this and considered a characteristic feature of geometric sans-serif. Mark as Needs Justification.

**Comment by NoxUltima** [comment]
I'll leave it here for now...

**Comment by NoxUltima** [comment]
I'd say otherwise, for the g, and I am withdrawing the e from the proposal.

Here's Belinsky, another monospace. I hope this is enough to justify.

![download.jpeg](https://user-images.githubusercontent.com/16898444/116208292-5a1f2400-a773-11eb-8a02-75c9b45df75a.jpeg)
