### ISSUE TITLE
Inziu Iosevka在PyCharm下中括号显示不正常

### ISSUE THREAD

**Issue by MisLink** [be5invis/Iosevka#96]
其他地方都是正常的样子，只有PyCharm：
![pic](https://cloud.githubusercontent.com/assets/8280169/16713371/213bd9b8-46d8-11e6-90ef-5df860245987.png)
猜测其它Jetbrains家产品也有同样的问题？

**Comment by be5invis** [comment]
Yes, and it is the bug within the Java’s rasterizer, I cannot fix it.
