### ISSUE TITLE
Atkinson Hyperlegible lower case "q"

### ISSUE THREAD

**Issue by sdothum** [be5invis/Iosevka#962]
- The requested character is...
  - [X] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [ ] Symbol
- [ ] Some other monospace/programming fonts supported this character. Provide images below.

------

While a monospace version of the [Atkinson Hyperlegible font](https://brailleinstitute.org/freefont) is not available from the Braille Institute, after seeing some requests for one, i wrote up an article [here](http://thedarnedestthing.com/iosevka%20hyperlegible) to create a look-alike monospace version using Iosevka.

The only missing character is the lower case "q", though, i think my use of the q="diagonal-tailed" actually worked out reasonably well -- if not with a more exaggerated curl. A version of q="tailed" would have been better IF the tail could have been more pronounced (longer) like l="flat-tailed". Any chance of creating a version of q="tailed" (regular and italic) with just an extended (longer) tail (not worrying about the subtle upward curl just to make things easier)? i realize that there is not a whole lot of room for the tail which could render the diagonal-tailed a better candidate visually.

Regardless, i am very pleased with how my version of a monospace Hyperlegible font turned out using Iosevka -- the diagonal tailed q still captures the essence of the font imo. Thank you for creating, maintaining and sharing Iosevka with the community!

**Comment by be5invis** [comment]
I have to say, Iosevka is **NOT** a typeface targeting dyslexia, low-vision legibility, or anti-tampering. I still want to control the styles it has.

**Comment by be5invis** [comment]
Also this variant conflicts with `U+024B` (`ɋ`).

**Comment by sdothum** [comment]
Interesting.. did not think to check the remaining character set. That character is what i am looking for.

Thank you for pointing that out. i appreciate your typeface objectives and the effort it takes to meet those needs.

Thank you for Iosevka!
