### ISSUE TITLE
[Aile] Remove Oblique styles

### ISSUE THREAD

**Issue by cssobral2013** [be5invis/Iosevka#969]
As @be5invis stated in #968, the Oblique and Italic weights will be the same on Iosevka Aile, version 6.0.0 onwards, so I'm opening this issue to remove Oblique styles from being available from Iosevka Aile downloads.

**Comment by be5invis** [comment]
This will be a breaking change targeting V7.

**Comment by be5invis** [comment]
OK, I'd like to resolve this as "by design", considering some of the Cyrillic letters *do have different shapes under Italic and Oblique, even if it is Aile*. This is required by Cyrillic orthography.

**Comment by be5invis** [comment]
This is the word `шарикоподшипниковый` in upright and italic, and you could observe many letters (like `и`, `п` and `д`) are shaped very differently.

![image](https://user-images.githubusercontent.com/240091/118345034-cd9c9180-b4e6-11eb-8cc6-e53ec5c747be.png)
![image](https://user-images.githubusercontent.com/240091/118345038-d4c39f80-b4e6-11eb-933a-dea09fee89e6.png)
