### ISSUE TITLE
t=flat-hook-short-neck* neck length depends on weight

### ISSUE THREAD

**Issue by pv4** [be5invis/Iosevka#970]
When building `t=flat-hook-short-neck` or `t=flat-hook-short-neck2`:
1. `t` has different neck heights depending on the weight. `heavy` has the longest neck, `thin` has the shortest one (marked with dots on the first image attached: `thin` and `heavy` of `flat-hook-short-neck2`).
2. the "visual height" differs even more (I guess it's somehow related to stem thickness). Look at "thread" and "sorted" on the second image: `regular` and `bold` (unsure) and `t=flat-hook-short-neck`.

Are these an intended behavior?

![image](https://user-images.githubusercontent.com/2502094/116172025-78483e00-a6f9-11eb-9ac4-17b4cae94a86.png)
![image](https://user-images.githubusercontent.com/2502094/116172384-3370d700-a6fa-11eb-979f-d0c86be9c9dc.png)

**Comment by be5invis** [comment]
Well to achieve visual alignment, the height of the top need, actually, _sligntly lower_ when getting bolder. Anyway, this will get updated in v6.1.0.
Closing as Resolved.
