### ISSUE TITLE
Iosevka fails to show the equal sign at size 13

### ISSUE THREAD

**Issue by KamranMackey** [be5invis/Iosevka#98]
At font size 13, the equal sign fails to show up. This happened when I was on Linux as well and is happening in every code editor/IDE I use. Other font sizes are fine. I've attached a screenshot. (the missing character beside the / is the equal sign) 

**Steps to reproduce**:
1. Open any IDE or code editor (I'm using Intellij IDEA)
2. Find the font settings for your IDE or code editor (For IDEA and other JetBrains IDEs it's under Editor -> Colors & Fonts -> Font)
3. If using IDEA or other JetBrains IDEs create a modified scheme (default ones are read-only)
4. Set your font to Iosevka and font size to 13.
5. Equal sign should fail to appear.

**Version**: 1.9.1
**Variant**: Regular
**Ligatures enabled**: No

**Screenshot at font size 13**: 
![font size 13](https://cloud.githubusercontent.com/assets/1617100/16914795/6a34f760-4cb1-11e6-9cbc-75294cd79bce.PNG)

**Screenshot at font size 14** (the equal sign appears fine at this font size and every other font size):
![font size 14](https://cloud.githubusercontent.com/assets/1617100/16915034/af5f8a0c-4cb2-11e6-981f-97bdc14c7f0b.PNG)

**Comment by KamranMackey** [comment]
Added a second screenshot with font size set to 14. Equal sign appears fine at that font size and at every font size I've tried.

**Comment by robertgzr** [comment]
I don't know if this is related at all but since it happens at size 13 specifically...

Ligatures break in iTerm2 at font sizes that are not multiples of 2
![](https://u.pomf.is/dvdyfw.png)

I noticed it because 13 is basically my default everywhere...

version: `1.9.1`
variant: `Regular`

**Comment by be5invis** [comment]
It is a bug of Java's rasterizer. It has some serious bugs when dealing with TTF references with gridfit. Sorry but I can not fix it.
Closed.

**Comment by KamranMackey** [comment]
@be5invis No, it can't be. It happens with VIM and other text editors.

**Comment by be5invis** [comment]
@KamranMackey screenshot?

**Comment by KamranMackey** [comment]
@be5invis sure, hang on.

**Comment by KamranMackey** [comment]
@be5invis Nevermind, turns out it is a bug with Java's rasterizer. You were right. Has the bug been reported?

**Comment by be5invis** [comment]
@KamranMackey I have no idea. Perhaps I should provide an build option to turn off referencify...

**Comment by KamranMackey** [comment]
@be5invis would be a good idea.

But wait, what's referencify?

**Comment by be5invis** [comment]
@KamranMackey Turning outline into glyph references.
It massively reduces file size, but Java hate it :(

**Comment by KamranMackey** [comment]
@be5invis Ah, I see. Sounds really cool, but why does Java's rasterizer hate it?

**Comment by be5invis** [comment]
@KamranMackey __I DON'T KNOW__
maybe related to the TT instr interpreter

**Comment by KamranMackey** [comment]
@be5invis Maybe. But what's the TT instr interpreter?

**Comment by KamranMackey** [comment]
Sorry, I'm a noob when it comes to these kinds of things :D

**Comment by be5invis** [comment]
@KamranMackey THE THING FITS GLYPHS’ OUTLINE TO PIXEL GRID FOLLOWING THE FONT’S EMBEDDED PROGRAM CALLED “TT INSTRUCTIONS”. IT IS IMPORTANT TO DISPLAY TEXT CLEARLY ON SCREEN. PERIOD.

**Comment by KamranMackey** [comment]
Ah, alright.

P.S. The caps lock is real xD
