### ISSUE TITLE
Character Block Requests (Letters)

### ISSUE THREAD

**Issue by ghost** [be5invis/Iosevka#983]
- The requested character is...
  - [x] Latin
  - [x] Cyrillic
  - [x] Greek
  - [ ] Punctuation
  - [ ] Symbol
- [x] Some other monospace/programming fonts supported these characters. Provide images below.

------

Coverage as of version 9.0.1. Fallback, greyed out characters come from Consolas. 

### Cyrillic Supplement

![2021-08-02 12_43_12-Iosevka Specimen](https://user-images.githubusercontent.com/16898444/127805455-306b1c8a-474f-49f7-9637-5e79ae7f13cf.png)

### Greek and Coptic (Coptic characters `U+03E2` to `U+03EF` excluded)

![2021-08-02 12_41_56-Iosevka Specimen](https://user-images.githubusercontent.com/16898444/127805456-119f4495-cb99-4f65-ad00-5e5c583baa2e.png)

### Phonetic Extensions Supplement (characters with downward-left and downward-right hooks)

![2021-08-02 12_43_32-Iosevka Specimen](https://user-images.githubusercontent.com/16898444/127805451-6715ef3b-c1ee-4eae-9254-fb11cc41f923.png)

### Phonetic Extensions (rotated letters only)

![2021-08-02 12_43_22-Iosevka Specimen](https://user-images.githubusercontent.com/16898444/127805453-4a039fab-0567-48ac-bc4a-e0a6d00d2dca.png)

### Latin Extended C

![2021-08-02 12_45_36-Iosevka Specimen](https://user-images.githubusercontent.com/16898444/127805447-a62b2f70-12cd-4cb4-b97d-88a35e535000.png)

**Comment by be5invis** [comment]
Put in backlog for a while -- no timetable though.

**Comment by NoxUltima** [comment]
Thanks for the reply!

**Comment by be5invis** [comment]
Well, I bump the version to 7 because there are breaking changes, which doesn't mean that it has very significant change.

**Comment by nxltm** [comment]
Added Latin script - see top post.

**Comment by jmcwilliams403** [comment]
Closable?
