### ISSUE TITLE
Lowercase c, open aperture

### ISSUE THREAD

**Issue by iikkabn** [be5invis/Iosevka#984]
- [ ] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

Lowercase c can be difficult to separate from lowercase o.
Fonts with open aperture c: Fira Mono, Inconsolata, Menlo, Oxygen Mono, Source Code Pro, Ubuntu Mono

**Comment by be5invis** [comment]
This is a style mismatch. Open contour "c" is considered humanist, which is not conformal to Iosevka's design style.
