### ISSUE TITLE
Longer tailed variant for lowercase L (l letter)

### ISSUE THREAD

**Issue by GulajavaMinistudio** [be5invis/Iosevka#985]
- [ ] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

I'm seeing the l variant from Jetbrains mono and Fira code font. And i see they have l tailed with longer tail. 
Jetbrains Mono l letter
![Screenshot_2021-05-09_11-21-05](https://user-images.githubusercontent.com/11639412/117560580-199ba080-b0b9-11eb-9326-da18746a2310.png)

Firacode l letter
![Screenshot_2021-05-09_11-20-19](https://user-images.githubusercontent.com/11639412/117560586-27512600-b0b9-11eb-8f9c-c359502df92b.png)

Can you add more longer tail variant for tailed l and tailed i like those fonts ? I see Iosevka variant "l" tailed in cv37 , but love to see longer tail variant like that.

**Comment by be5invis** [comment]
`l = "serifedTailed"` (`cv37`#8) should look like that.
![image](https://user-images.githubusercontent.com/240091/117560863-7447e480-b046-11eb-897f-2cad4d1f9b8c.png)

**Comment by GulajavaMinistudio** [comment]
oh i see. The length for tail style is adjusted for Iosevka. So for me, it doesn't look too long like tailed style in jetbrains mono.

**Comment by be5invis** [comment]
I do not think extending the tail works well with Iosevka's design.
Resolve as by design.
