### ISSUE TITLE
Fixes for PT Mono Style (SS16)

### ISSUE THREAD

**Issue by VladWinner** [be5invis/Iosevka#986]
I propose to modify SS16 (PT Mono Style) version to better match the source font

### Direct replacement
Italic _`a`, `а`_ → `'cv26' 13` 
> according to available Italic from other PT fonts

`D` → `'cv04' 2`
`K` → `'cv11' 4`
`К` (Capital Cyrillic Ka) → `'cv11' 4`
`L` → `'cv12' 2`
`c` → `'cv28' 4`
`с` (Cyrillic Es) → `'cv28' 4`
`d` → `'cv29' 6`
`f` → `'cv31' 17`
`t` → `'cv44' 11`
`ɜ` → `'cv57' 3`
`Г`, `г` → apply `slab` style
`0` → `'cv62' 7`
`8` → `'cv70' 3`
`^` → `'cv76' 1`
`$` → revert back to `default` (turn off `slab` style)

### Replacement that requires new variants
`h` → `'cv33' 3` but without motion serif at bottom
`k` → `'cv36' 12` but with motion serif at bottom
`к` → `'cv60' 4` but with motion serif at bottom 
> here top motion serifs are not presented in "PT Mono" specially to emphasize difference between Cyrillic Ka `к` and Latin `k`

`З`, `з` → add inward serif at top (like `'cv28' 4`)
`э` → add inward serif at top (like `'cv28' 4`)
`ф` → `slab` style but with top serif only

I used "Cherry-Picking" from Iosevka website to search for replacements

**Comment by VladWinner** [comment]
> This is not implementable. `$`'s `S` part follows `S` (because it is an `S`).

Roger that.

**Comment by VladWinner** [comment]
@be5invis 7.0.0-preview.1 comment: there are still unchanged glyphs left here.
I decided to make a simple description to help you with remaining tags.
![image](https://user-images.githubusercontent.com/13555921/118416766-ea3cf300-b6b9-11eb-8481-730cc30bf177.png)

**Comment by be5invis** [comment]
@VladWinner fixed
