### ISSUE TITLE
Adding Apple Symbol ()

### ISSUE THREAD

**Issue by VladWinner** [be5invis/Iosevka#987]
- The requested character is...
  - [ ] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [x] Symbol
- [x] Some other monospace/programming fonts supported this character. Provide images below.
![image](https://user-images.githubusercontent.com/13555921/117900758-9786c400-b2d2-11eb-8b68-89a89c7eeb23.png)
"Segoe UI Emoji" is not a monospaced font, but was provided for informational purposes.
------

Apple Symbol could be used to indicate the OS in some cases (UI, workspace).

**Comment by be5invis** [comment]
This is a pictogram/trademark outside Unicode, and I don't have plans to support such symbols. It would be better to use composite fonts like Nerd font.
Close as by design.
