### ISSUE TITLE
U+20A7 PESETA SIGN: Incorrect glyph

### ISSUE THREAD

**Issue by van-de-bugger** [be5invis/Iosevka#988]
Iosevka glyph for U+20A7 PESETA SIGN looks like P letter with horizontal stroke:

![iosevka-regular](https://user-images.githubusercontent.com/721164/118035019-58f51600-b373-11eb-8bfb-c4cda684cd10.png)

It is incorrect. Currency symbol for Spanish peseta should be a ligature "Pt" or "Pta" (singular forms) or "Pts" or "Ptas" (plural forms). Looks like "Pts" is preferred form for compatibility with [CP-437](https://en.wikipedia.org/wiki/Code_page_437). 

See also: Wikipedia article [Spanish peseta](https://en.wikipedia.org/wiki/Spanish_peseta#Symbol).

U+20A7 PESETA SIGN in other monospace fonts:

![DejaVuSansMono](https://user-images.githubusercontent.com/721164/118035242-a3769280-b373-11eb-86da-1698c6455b8c.png) (DejaVu Sans Mono)
![DroidSansMono](https://user-images.githubusercontent.com/721164/118035250-a6718300-b373-11eb-9174-64ba7391086d.png) (Droid Sans Mono)
![LiberationMono-Regular](https://user-images.githubusercontent.com/721164/118035262-a96c7380-b373-11eb-8add-a941ad66f03e.png) (Liberation Mono)
![NotoSansMono-Regular](https://user-images.githubusercontent.com/721164/118035267-ab363700-b373-11eb-9397-822a47d14f7a.png) (Noto Sans Mono)
![RobotoMono-Regular](https://user-images.githubusercontent.com/721164/118035272-acfffa80-b373-11eb-869d-b48e861aee7a.png) (Roboto Mono)

---

* Your font version: 6.1.3
* Your font variant: All (Iosevka, Aile, Etoile)
* Your operating system: Fedora 33

**Comment by ChiefMikeK** [comment]
Duplicate of #451
