### ISSUE TITLE
Online Builder Tool ?

### ISSUE THREAD

**Issue by GulajavaMinistudio** [be5invis/Iosevka#993]
**Is your feature request related to a problem? Please describe.**
Not everyone have tech savvy knowledge and have time to build custom font one by one.

**Describe the solution you'd like**
I have idea, what about online builder tools for Iosevka Font ? We can customize font by selecting from checkbox on font variant, and previewing it before download.

**Describe alternatives you've considered**
You can take a reference from Input Font, it have customizable variant with online builder tool. Here is the link to take a look [https://input.djr.com/preview/](https://input.djr.com/preview/)

**Additional context**
Here screenshot on online builder font taken from Input webpage
![Screenshot_2021-05-15 Input Fonts for Code — Preview](https://user-images.githubusercontent.com/11639412/118333212-88ec1700-b535-11eb-9700-8d49bf21595c.png)

**Comment by be5invis** [comment]
Well, the blocker is `ttfautohint`, which depends on `freetype` that used `setjmp`/`longjmp`, so you cannot make it compiled into WebAssembly and use in web pages.
Closing as external.

**Comment by alexeyten** [comment]
I was thinking about tool that will not build font from scratch, but modify prebuilded font to change default glyphs.
Something like what [OTFeatureFreezer](https://github.com/twardoch/fonttools-opentype-feature-freezer#opentype-feature-freezer) do with stylistic sets, but with character variants. I guess this should be possible.
