### ISSUE TITLE
Add more single sided bar t variants

### ISSUE THREAD

**Issue by AlsoScratch** [be5invis/Iosevka#997]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [ ] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

*Please provide your justification here.*
I would like variants for `t` with the bar on one side but also for the other bottom shapes (bent/ flat/ diagonal) and stem heights.
<img width="477" alt="Screenshot 2021-05-16 at 12 31 36" src="https://user-images.githubusercontent.com/48752273/118385594-d2765800-b642-11eb-906e-4d893bc5feb6.png">

**Comment by be5invis** [comment]
Please justify with samples of existing monospace / programming fonts using these shapes.

**Comment by AlsoScratch** [comment]
Because there are already some, that is:
<img width="63" alt="Screenshot 2021-05-16 at 17 20 53" src="https://user-images.githubusercontent.com/48752273/118392229-1c733400-b66b-11eb-8378-a91873828549.png">
Just need them for the other existing bottom shapes.

**Comment by be5invis** [comment]
@AlsoScratch Well, “making some cartesian product complete” doesn’t justify a variant. For `t`, I did not see any programming fonts using these.
